### ISSUE TITLE
SyncUp/SyncDown with no Id

### ISSUE THREAD

**Issue by migue1s** [forcedotcom/SalesforceMobileSDK-iOS#1000]
I was working on creating a basic app which syncs a salesforce contact to a soup. If there is no 'Id' field in the SOQL query/indexPath, the sync will say it is successful, "done", return the appropriate amount of objects and yet the soup will remain empty.
I propose having the SDK either output an error saying it needs to include the 'Id' field or automatically retrying the query with an 'Id' field if the soup remains empty after a 'success'.

The code I was using, for clarity:
```ObjC
    //Generating the query
    NSString *soqlQuery = [NSString stringWithFormat:@"SELECT FirstName, LastName, Name FROM Contact"];
    SFSyncTarget *syncTarget = [SFSyncTarget newSyncTargetForSOQLSyncDown:soqlQuery];
    SFSyncOptions *syncOptions = [SFSyncOptions newSyncOptionsForSyncDown:SFSyncStateMergeModeOverwrite];
    //Run the query
    __weak MainMenuTableViewController *weakSelf = self;
    [self.syncManager syncDownWithTarget:syncTarget options:syncOptions soupName:kContactSoupName updateBlock:^(SFSyncState* sync) {
        if ([sync isDone]) {
            [weakSelf showLocalData];
        } else if ([sync hasFailed]) {
            NSLog(@"The sync failed");
        }
```

Changing 
```ObjC
NSString *soqlQuery = [NSString stringWithFormat:@"SELECT FirstName, LastName, Name FROM Contact"];
```
To
```ObjC
NSString *soqlQuery = [NSString stringWithFormat:@"SELECT Id, FirstName, LastName, Name FROM Contact"];
```
and adding the indexPath for 'Id' was enough to fix it for me, but I had to spend an intense amount of time to discover the issue.

**Comment by bhariharan** [comment]
We have fixed this [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1372).
