### ISSUE TITLE
iOS 8.3 Critical Bug - Hybrid App crashes with Unable to bootstrap_look_up port unknown error code (1102)

### ISSUE THREAD

**Issue by gauravkheterpal** [forcedotcom/SalesforceMobileSDK-iOS#1005]
Mobile SDK version - 3.1
Hybrid app - built using Sencha Touch
Target Device - iPhone, iPad
iOS Version - 8.3

We've had an app running in production for a while now. Ever since iOS 8.3 came out, we've had reports of the app terminating on start up. Debugging the logs, we see the following error

Unable to bootstrap_look_up port with name com.xxx.xxx.gsEvents: unknown error code (1102)
Apr 22 14:18:33 iPhone SpringBoard[54] <Warning>: Unable to deliver -[UIRemoteApplication showTopMostMiniAlertWithSynchronizationPort:] message to port 0: (ipc/send) invalid destination port

This happens when PIN security is enabled on our org. 

In case PIN security is disabled, we see a white screen and the logs show

 [Error] module com.salesforce.plugin.smartstore not found
	require (cordova.js, line 59)
	localRequire (cordova.js, line 49)
	global code (inline.js, line 24)

[Log] deviceready has not fired after 5 seconds. (cordova.js, line 1169)
[Log] Channel not fired: onDOMContentLoaded (cordova.js, line 1162)
[Log] Channel not fired: onCordovaConnectionReady (cordova.js, line 1162)
[Log] Channel not fired: onCordovaInfoReady (cordova.js, line 1162)

This works okay with iOS 8.1 though.

I presume this would a show stopper bug for all apps on iOS 8.3. Can you advise if upgrading to SDK 3.2 will fix this or if this is a known issue with an ETA for fix.

cc @khawkins @akhileshgupta @bhariharan

**Comment by khawkins** [comment]
We had some weird UI hanging issues that surfaced with 8.3, which we patched and fixed in 3.2.  I'd say give it a try and see if it helps your situation.  Or try replacing libSalesforceSDKCore.a from the 3.1.2 binaries for your existing app.

**Comment by khawkins** [comment]
We had some weird UI hanging issues that surfaced with 8.3, which we patched and fixed in 3.2.  I'd say give it a try and see if it helps your situation.  Or try replacing libSalesforceSDKCore.a from the 3.1.2 binaries for your existing app.

**Comment by gauravkheterpal** [comment]
@khawkins Thanks. The upgrade to SDK 3.2 does fix this issue but it has broken several other things related to PIN security feature which used to work well with 3.1

I'm closing this bug and will file new bugs for the other issues observed related to pin security
