### ISSUE TITLE
Issue upgrading SF iOS sdk version 3.2 with iOS 8.3 app

### ISSUE THREAD

**Issue by ratishmah** [forcedotcom/SalesforceMobileSDK-iOS#1006]
I am updating my  iOS 8.3 version app with latest SF sdk version 3.2. i am getting this error during initial loading of the app during downloading of data.

Error Domain=CSFNetworkErrorDomain Code=1007 "Value supplied to CSFURLFormEncode is not a number or string" UserInfo=0x7aa81b70 {key=q, value=<53454c45 43542056 49505f43 75727265 6e745f59 6561725f 5f632c4e 616d652c 4f776e69 6e675f50 6172746e 65725f5f 632c4361 7465676f 72795f31 375f5f63 2c436174 65676f72 795f365f 44657363 72697074 696f6e5f 5f632c42 696c6c69 6e67506f 7374616c 436f6465 2c436174 65676f72 795f385f 5f632c4f 776e6572 73686970 2c436174 65676f72 795f3134 5f446573 63726970 74696f6e 5f5f632c 4350505f 52656769 6f6e5f43 61745f43 6f64655f 32305f5f 632c4361 7465676f 72795f38 5f446573 63726970 74696f6e 5f5f632c 43617465 676f7279 5f31335f 44657363 72697074 696f6e5f 5f632c57 65627369 74652c43 72656174 65644461 74652c53 686f775f 4163636f 756e745f 5f632c42 696c6c69 6e67436f 756e7472 792c4361 7465676f 72795f32 305f5f63 2c436174 65676f72 795f3134 5f5f632c 4e757472 69736f6c 7574696f 6e735f52 65746169 6c65725f 5f632c42 696c6c69 6e675374 72656574 2c436174 65676f72 795f3130 5f446573 63726970 74696f6e 5f5f632c 43617465 676f7279 5f315f44 65736372 69707469 6f6e5f5f 632c4542 49445f5f 632c5061 72656e74 49642c52 65636f72 64547970 652e4e61 6d652c50 50475f52 6567696f 6e5f4361 745f436f 64655f32 365f5f63 2c564950 5f436c61 696d5f42 795f5072 6576696f 75735f59 6561725f 5f632c43 61746567 6f72795f 31395f5f 632c4361 7465676f 72795f31 325f4465 73637269 7074696f 6e5f5f63 2c57686f 6c657361 6c655f43 50505f5f 632c5068 6f6e652c 43617465 676f7279 5f355f44 65736372 69707469 6f6e5f5f 632c4c61 73744d6f 64696669 65644279 2e4e616d 652c4361 7465676f 72795f31 315f4465 73637269 7074696f 6e5f5f63 2c4d6170 70696e67 5f416464 72657373 5f47656f 6c6f6361 74696f6e 5f5f4c61 74697475 64655f5f 732c4361 7465676f 72795f31 305f5f63 2c437265 6469745f 436f6c6c 65637469 6f6e5f4d 616e6167 65725f5f 632c416e 6e75616c 52657665 6e75652c 43617465 676f7279 5f345f5f 632c4e75 6d626572 4f66456d 706c6f79 6565732c 53686970 70696e67 4c6f6e67 69747564 652c4269 6c6c696e 674c6f6e 67697475 64652c54 7970652c 43617465 676f7279 5f31355f 5f632c52 375f5265 7461696c 65725f5f 632c5379 7374656d 4d6f6473 74616d70 2c436174 65676f72 795f335f 5f632c41 63636f75 6e745f41 63746976 655f466c 61675f5f 632c4269 6c6c696e 67436974 792c4361 7465676f 72795f39 5f5f632c 43617465 676f7279 5f31325f 5f632c43 61746567 6f72795f 31315f5f 632c5573 65725f44 6566696e 65645f41 64647265 73735f5f 632c4167 72694d69 6e655f53 75627363 72696265 725f5f63 2c436174 65676f72 795f3136 5f5f632c 43617465 676f7279 5f335f44 65736372 69707469 6f6e5f5f 632c4361 7465676f 72795f31 5f5f632c 43617465 676f7279 5f325f44 65736372 69707469 6f6e5f5f 632c5368 69707069 6e675374 72656574 2c4d7963 6f67656e 5f4f7264 6572696e 675f5f63 2c564950 5f47524f 5745525f 5f632c43 61746567 6f72795f 345f4465 73637269 7074696f 6e5f5f63 2c436174 65676f72 795f375f 5f632c43 75727265 6e745f43 726f705f 59656172 5f315f5f 632c5368 69707069 6e67506f 7374616c 436f6465 2c536869 7070696e 67537461 74652c43 61746567 6f72795f 32305f44 65736372 69707469 6f6e5f5f 632c4c61 73744163 74697669 74794461 74652c50 72657669 6f75735f 43726f70 5f596561 725f5f63 2c4d6f6e 73616e74 6f5f4f72 64657269 6e675f5f 632c4c61 73745265 66657265 6e636564 44617465 2c436174 65676f72 795f355f 5f632c43 61746567 6f72795f 31395f44 65736372 69707469 6f6e5f5f 632c4269 6c6c696e 674c6174 69747564 652c5265 7461696c 65725f53 65617263 685f5479 70655f5f 632c4c61 73745669 65776564 44617465 2c4d6169 6c696e67 5f436f75 6e74795f 5f632c41 6772696d 696e655f 4b65795f 5f632c54 69636b65 7253796d 626f6c2c 49735f48 6f757365 5f486f6c 645f5061 72656e74 5f5f632c 5649505f 43757272 656e745f 43726f70 5f596561 725f315f 5f632c49 7344656c 65746564 2c505047 5f436c61 73736966 69636174 696f6e5f 4361745f 436f6465 5f32375f 5f632c57 686f6c65 73616c65 5f536565 645f5f63 2c536869 7070696e 67436974 792c4361 7465676f 72795f36 5f5f632c 42696c6c 696e6753 74617465 2c4d6169 6e5f5068 6f6e655f 5f632c4f 776e6572 49642c43 61746567 6f72795f 31385f5f 632c4372 65646974 5f436f6c 6c656374 696f6e5f 4d616e61 6765725f 50686f6e 655f5f63 2c4d6173 74657252 65636f72 6449642c 43617465 676f7279 5f31335f 5f632c4d 61707069 6e675f41 64647265 73735f47 656f6c6f 63617469 6f6e5f5f 4c6f6e67 69747564 655f5f73 2c436174 65676f72 795f3135 5f446573 63726970 74696f6e 5f5f632c 4e4b5f4f 72646572 696e675f 5f632c41 63636f75 6e744e75 6d626572 2c446f5f 4e6f745f 4d61696c 5f5f632c 474c4e5f 5f632c45 6e645f55 7365725f 52657365 6c6c6572 5f436174 5f436f64 655f3031 5f5f632c 43617465 676f7279 5f325f5f 632c4361 7465676f 72795f31 385f4465 73637269 7074696f 6e5f5f63 2c436f72 6e5f5a6f 6e655f43 61745f43 6f64655f 32315f5f 632c4375 7272656e 745f4372 6f705f59 6561725f 5f632c49 6e647573 7472792c 42696c6c 696e6753 74617465 436f6465 2c506879 73696361 6c5f4164 64726573 735f5f63 2c564950 5f436c61 696d5f42 795f4375 7272656e 745f315f 5f632c43 61746567 6f72795f 395f4465 73637269 7074696f 6e5f5f63 2c4a6967 73617743 6f6d7061 6e794964 2c536567 6d656e74 6174696f 6e5f325f 5f632c50 68797369 63616c5f 41646472 6573735f 47656f63 6f64655f 5f4c6f6e 67697475 64655f5f 732c5649 505f5072 6576696f 75735f43 726f705f 59656172 5f5f632c 43617465 676f7279 5f31365f 44657363 72697074 696f6e5f 5f632c43 61746567 6f72795f 31375f44 65736372 69707469 6f6e5f5f 632c4361 7465676f 72795f37 5f446573 63726970 74696f6e 5f5f632c 43726561 74656442 792e4e61 6d652c56 49505f43 6c61696d 5f42795f 43757272 656e745f 59656172 5f5f632c 52375f41 7574686f 72697a65 645f5265 7461696c 65725f5f 632c5365 676d656e 74617469 6f6e5f33 5f5f632c 49735061 72746e65 722c5068 79736963 616c5f41 64647265 73735f47 656f636f 64655f5f 4c617469 74756465 5f5f732c 53686970 70696e67 436f756e 7472792c 4661782c 53686970 70696e67 436f756e 74727943 6f64652c 4c617374 4d6f6469 66696564 44617465 2c536567 6d656e74 6174696f 6e5f315f 5f632c53 68697070 696e6753 74617465 436f6465 2c556e69 74795f5f 632c4964 2c536869 7070696e 674c6174 69747564 652c4269 6c6c696e 67436f75 6e747279 436f6465 2046726f 6d204163 636f756e 7420>, NSLocalizedDescription=Value supplied to CSFURLFormEncode is not a number or string}

Any help will be appreciated.﻿ Please reply asap.

Thanks,
Ratish

**Comment by shawn-butler-tavant** [comment]
The issue here is for any SFRestAPI query longer than (NSUInteger const CSFParameterMaximumQueryStringDataLength = 1024) characters then the parameter style is set by the framework to CSFParameterStyleURLEncoded.

As a result of this style parameter binding in the implementation in CSFParamterStorage.m of - (BOOL)bindURLEncodedParametersToRequest:(NSMutableURLRequest*)request error:(NSError *__autoreleasing *)error transforms the query parameters into NSConcreteMutableData representation of that string where the TODO exists.

~line 251 CSFParamterStorage.m

    NSMutableDictionary *formParameters = [NSMutableDictionary dictionaryWithCapacity:self.parameters.count];
    [self.parameters enumerateKeysAndObjectsUsingBlock:^(NSString *key, id obj, BOOL *stop) {
        NSValueTransformer *transformer = [NSValueTransformer networkDataTransformerForObject:obj];
        if (transformer) {
            // TODO: What happens when the value is an NSData or something else?
            id result = [transformer transformedValue:obj];
            if (result) {
                formParameters[key] = result;
            } else {
                success = NO;
            }
        } else if ([obj conformsToProtocol:@protocol(CSFActionInput)]) {
            NSObject<CSFActionInput> *objInput = (NSObject<CSFActionInput>*)obj;
            NSData *data = [objInput formatJSONData:error];
            if (data) {
                formParameters[key] = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
            } else {
                success = NO;
            }
        } else {
            formParameters[key] = obj;
        }
    }];

Subsequently these formParameters are processed by NSString * CSFURLFormEncode(NSDictionary *info, NSError **error) function in CSFInternalDefines.m which is presently coded to only handle NSNumber and NSString types not NSConcreteMutableData bytes.  When encountering byte data the error pasted above is propagated by this function.

**Comment by ratishmah** [comment]
Shawn, you are correct. Setting the size more than 1024 will fix the problem.

**Comment by akhileshgupta** [comment]
@MikeNachbaur can you take a look at this? How should this be tackled in our networking layer?

**Comment by ClaudeSutterlin** [comment]
This is causing us a lot of issues when upgrading an enterprise app to the latest SDK. A quick resolution would be much appreciated.

**Comment by bhariharan** [comment]
We have a fix for this in our ```unstable``` branch [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1073), and this will be in our next release.
