### ISSUE TITLE
PIN Security Issues in mobile SDK 3.2

### ISSUE THREAD

**Issue by manish-metacube** [forcedotcom/SalesforceMobileSDK-iOS#1007]
Hi All, 

We have recently upgraded our app with mobile SDK 3.2 and got some more serious issue with PIN screen. I am attaching some screenshots. 

App Detail - 

SDK Version - Mobile SDK version - 3.2, 
iOS Version - 8.3 
App Nature - Hybrid app - built using Sencha Touch
Target Device - iPhone, iPad <br />

![img_0714-2](https://cloud.githubusercontent.com/assets/2398709/7319782/a8861846-eab5-11e4-944c-9ae2735c0530.png)
1. PIN screen stuck on home screen, user needs to kill app. (happens sometime).  

![img_0713](https://cloud.githubusercontent.com/assets/2398709/7319783/a8a7e5f2-eab5-11e4-911f-1e61eaefb1f4.PNG)
2. Keyboard remains open after entering pin 
Step to reproduce - Kill app at pin screen and restart.

![img_0712](https://cloud.githubusercontent.com/assets/2398709/7319784/a8aa975c-eab5-11e4-8dec-c94b51e83d5f.PNG)
3. PIN screen prompted text distorted.
Step to reproduce - Keep ideal app for given timeframe. 

Our app is running in production, can some look on these on priority and provide a workaround or solution?

Can we have any expected date to fix this?

@khawkins

**Comment by carlcarter** [comment]
I have also seen the first issue on a Native iOS app with SDK 3.2 on iOS 8.2 (deployment target 7.1). 

Additionally, when the pin screen first loads and I select the pin textbox there is a delay before the keyboard pops up which could be up to a couple of seconds.

**Comment by bhariharan** [comment]
This has been fixed in the ```unstable``` branch, by [this](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1041) pull request. It will be in our next release.
