### ISSUE TITLE
After upgrade to 3.2 logging out breaks all future requests

### ISSUE THREAD

**Issue by cgreening** [forcedotcom/SalesforceMobileSDK-iOS#1014]
After upgrading to 3.2 when we logout of our application we can login to the application successfully, but all requests fail with the following error:

__Network action must have an instance hosts__

**Comment by paweldudek** [comment]
@cgreening they will fail if you log in using the same account. Check out my PR for details.

**Comment by akhileshgupta** [comment]
We are working on this issue and will keep you posted once the fix is released.

**Comment by wmathurin** [comment]
We have released a patch yesterday (https://github.com/forcedotcom/SalesforceMobileSDK-iOS/tree/v3.2.1) which we believe fixed you issue.

**Comment by jeffreyjackson** [comment]
Anyone know when the tags may get bumped for cocoapods to catch this?  I'd rather not run :head on our Podfile for local troubleshooting and support purposes.

**Comment by bhariharan** [comment]
@jeffreyjackson Coming up soon.

**Comment by jeffreyjackson** [comment]
cc @brad36
