### ISSUE TITLE
Unit test crashing when trying to use logger

### ISSUE THREAD

**Issue by B82607** [forcedotcom/SalesforceMobileSDK-iOS#1029]
I'm trying to run a unit test - any unit test - and my application crashes. I am using CocoaPods, SDK v 3.1.3, and running the app on device/simulator works just fine. But when `AppDelegate` `init` is called, and then tries to access the `SalesforceSDKManager`, it crashes in `SFUserAccountManager`, line 542:
```objc
[self log:SFLogLevelDebug format:@"There is no user account file in this user directory: %@", orgPath];
```
The crash given is `EXC_BAD_ACCESS`.

If I comment out all the Salesforce related code, the test naturally works. 

Let me know if more details are needed, or if there are any suggestions.

**Comment by akhileshgupta** [comment]
Can you provide more details on why it crashes on this line? Is the "orgPath" or "SFLogLevelDebug" nil? Did you try to just comment out this line and try running your test?

**Comment by B82607** [comment]
@akhileshgupta 
I wish I could provide more details about *why* it crashes, but I can't. I can provide more details about how my environment is setup, and what I'm seeing. The first crash I actually hit is 
```objc  
[self log:SFLogLevelInfo msg:@"Launching the Salesforce SDK."];
```

If I comment that line out, it just keeps crashing wherever `log:msg:` is actually called. It then gets to a point that it crashes in code I can't see, since it is in a static library.

I have my AppDelegate setting up the Salesforce stack, similar to they way a forceios native project is setup (except I'm using CocoaPods). In `application:didFinishLaunchingWithOptions:`, I have `[[SalesforceSDKManager sharedManager] launch]` at the end, and the full stack setup in `AppDelegate init`. If I comment out all the code for Salesforce in `AppDelegate`, the unit test target runs just fine. Commenting the code out doesn't seem like a viable way to unit test, though...

**Comment by akhileshgupta** [comment]
Can you share a sample unit test project that we can use to reproduce this issue? That will really help us dig out the issue and resolve it.

BTW, we have plenty of unit tests as part of the SDK library projects. You can also try to look at them to compare your tests: [SalesforceRestAPITests.m](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceRestAPI/SalesforceRestAPITests/SalesforceRestAPITests.m)

**Comment by B82607** [comment]
I couldn't reproduce it in a new project (as I couldn't share the one having the problem). I decided to delete my project's unit test target, and reimport the files that contained my tests. This seems to have fixed the problem.
