### ISSUE TITLE
SmartSync fails forever if quit app when syncing.

### ISSUE THREAD

**Issue by tuyennguyen266** [forcedotcom/SalesforceMobileSDK-iOS#1045]
When the app is syncing using SmartSync, if user turns off the app then opens the app later. The app can not resync with callback is never called.

**Comment by bhariharan** [comment]
@tuyennguyen266 We don't support background sync at this time. We will consider adding support for this in a future release.

**Comment by tuyennguyen266** [comment]
@bhariharan The issue here is not syncing in background. The issue is after go back from background, app come to foreground and from now on, the app can not sync anymore. For more details, here is the steps:
Step 1: start the app first time and sync down all data.
Step 2: modify data on Salesforce and start the app 2nd time. When the app is syncing, turn off the app.
Step 3: start the app 3rd time, from now on the app can not sync, callback is also never called. So if we put code in callback to update UI, the app never call it.
Step 4: start the app n.. time, the result is the same as step 3.

**Comment by wmathurin** [comment]
In step 2, are you killing the app or simply leaving the app?
In step 3, are you doing a resync or a fresh sync down?
In step 4, do you mean foregrounding the app or restarting the app?

**Comment by tuyennguyen266** [comment]
@wmathurin:
In step 2, are you killing the app or simply leaving the app?
--> Killing the app or leaving the app will make the same result.
In step 3, are you doing a resync or a fresh sync down?
--> Doing a resync.
In step 4, do you mean foregrounding the app or restarting the app?
--> Restarting the app.

**Comment by wmathurin** [comment]
We have released a patch yesterday (https://github.com/forcedotcom/SalesforceMobileSDK-iOS/tree/v3.2.1) which we believe fixed you issue.
