### ISSUE TITLE
Resync not working after first app closing

### ISSUE THREAD

**Issue by McFlyssss** [forcedotcom/SalesforceMobileSDK-iOS#1047]
I'm using the resync methods in 3.2 SDK version and I found what seems to be an issue. Let me describe the process that we are following:

Each time the app launches we call sync/resync methods to keep data updated. We store the syncId that the SDK returns after each sync process only if the sync status is equals to 'SFSyncStateStatusDone'. 
Then the next time we try to sync we check if we have syncId and if so we use resync to update data.

This works most of the times except if we close the app after the very first sync. In that specific case after launching the app again the resync process fails:
ERROR|SFSmartSyncSyncManager|Sync XX not found
ERROR|SFSmartSyncSyncManager|Cannot run reSync:XX:no sync found

When the first resync fails we just call sync again in order to get the data again. After this everything works as expected and we can resync as many times as we need.

**Comment by wmathurin** [comment]
Where/how do you store the syncId for sync processes that completed?

**Comment by McFlyssss** [comment]
I store the syncId in [NSUserDefaults standardUserDefaults]

**Comment by wmathurin** [comment]
The same issue was reported here: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1045
We are looking into it.

**Comment by McFlyssss** [comment]
I don't think it's exactly the same issue but both could be related. After diving more into it I realise that looks like that after closing the app for the first time the data is no there anymore, not even the cached data. Then after the first time you can close the app as many times as you want and the data will be there.

Hope this clue could help.

Cheers

**Comment by wmathurin** [comment]
We have released a patch yesterday (https://github.com/forcedotcom/SalesforceMobileSDK-iOS/tree/v3.2.1) which we believe fixed you issue.

**Comment by McFlyssss** [comment]
I've been trying to get this path thru cocoapods and I don't get it. Is there any way to do it?

Thanks again

**Comment by jeffreyjackson** [comment]
@McFlyssss the team will have to tag the repo as a new version before cocoapods will recognize that it has been updated.  If you are feeling brave you can append `, :HEAD` to the pod in the `Podfile` to get whats most recent on the master branch.

**Comment by carlcarter** [comment]
this works:

pod 'SalesforceMobileSDK-iOS', :git => 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git', :tag => 'v3.2.1', :submodules => 'true'

**Comment by McFlyssss** [comment]
@jeffreyjackson and @carlcarter Thanks for your advice. Them both work.

**Comment by McFlyssss** [comment]
@wmathurin sorry but after applying the patch the issue it's still there. 
Shall we open it again?

**Comment by McFlyssss** [comment]
Looks like this issue has been fixed in 3.3

Thanks!
