### ISSUE TITLE
[Noob] Problems with the command  "./install.sh"

### ISSUE THREAD

**Issue by CesarRN** [forcedotcom/SalesforceMobileSDK-iOS#1051]
Hello all.

I have problems with two things.

First of all I have to use the command:
git clone git://github.com/forcedotcom/SalesforceMobileSDK-iOS.git
Instead of
git clone https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git

Is it ok?  is a mistake use it?

Well, I clone the repo with the command above but I have problems when I try to execute the command/file "install.sh"

$ ./install.sh 
Synchronizing submodule url for 'external/ThirdPartyDependencies'
Synchronizing submodule url for 'external/cordova-ios/cordova-ios'
Synchronizing submodule url for 'external/ocmock'
Synchronizing submodule url for 'external/shared'
Cloning into 'external/ThirdPartyDependencies'...
fatal: unable to access 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Dependencies.git/': Failed connect to github.com:8080; Operation timed out
Clone of 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Dependencies.git' into submodule path 'external/ThirdPartyDependencies' failed

What´s wrong?
How can I solve it?

Thanks!!

**Comment by akhileshgupta** [comment]
@CesarRN can you post your question on our G+ forums since this is not a SDK bug: [https://plus.google.com/communities/114225252149514546445](https://plus.google.com/communities/114225252149514546445)

We will try to resolve your query there.
