### ISSUE TITLE
removeEntries method doesn't delete

### ISSUE THREAD

**Issue by McFlyssss** [forcedotcom/SalesforceMobileSDK-iOS#1059]
I could not remove records from the local DB. I'm calling (void)removeEntries: fromSoup: 

I've tried both sending array with id's @(xxxx,xxxx,xxxx) and @('xxxx','xxxx','xxxx') and none of them work. The records are never deleted.

The method (void)clearSoup does work. 

Could be some issue related with FMDB?

Cheers

**Comment by wmathurin** [comment]
The question is what values are you passing in as ids?

Here is some sample code that should help:

```objective-c
NSArray* soupIndices = [SFSoupIndex asArraySoupIndexes:
                                        @[[self createFullTextIndexSpec:@"FirstName"],
                                          [self createFullTextIndexSpec:@"LastName"]]];

[store registerSoup:@"Characters" withIndexSpecs:soupIndices];

NSDictionary* employee1 = @{@"FirstName": @"James", @"LastName" : @"Bond"};
NSDictionary* employee2 = @{@"FirstName": @"Hugo", @"LastName" : @"Drax"};

NSArray* savedEmployees =  [self.store upsertEntries:@[employee1, employee2] toSoup:@"Characters"];
[store removeEntries:@[savedEmployees[0][@"_soupEntryId"], savedEmployees[1][@"_soupEntryId"]] fromSoup:@"Characters"];

**Comment by wmathurin** [comment]
Hopefully the sample code above will help. Closing issue since we don't believe there is a bug around removeEntries (we are using it in tests / sample apps without issues). Please reopen if you think otherwise.

**Comment by McFlyssss** [comment]
Than you so much for your help! 
I was passing the record Id instead of the _soupEntryId.

Sorry for the inconveniences and thank you again!
