### ISSUE TITLE
SmartSync: App crashes if sync up an object that has been deleted on server side

### ISSUE THREAD

**Issue by tuyennguyen266** [forcedotcom/SalesforceMobileSDK-iOS#1062]
Step 1: sync down all data
Step 2: delete an object on server side
Step 3: modify that object on client side
Step 4: sync up then app crashes.

May be the clue below can help:
When call method fetchRecordModificationDates... to compare serverTime and localTime, there is no record returned from server make the following code crash.
```
        if (nil != response) {
            NSDictionary *record = response[@"records"][0]; // CRASH HERE
            if (nil != record) {
                NSString *serverLastModifiedStr = record[self.modificationDateFieldName];
                if (nil != serverLastModifiedStr) {
                    NSDate *testServerModifiedDate = [SFSmartSyncObjectUtils getDateFromIsoDateString:serverLastModifiedStr];
                    if (testServerModifiedDate != nil) {
                        serverLastModifiedDate = testServerModifiedDate;
                    }
                }
            }
        }
```

**Comment by wmathurin** [comment]
We are reproducing the issue here and we are working on a fix.

**Comment by wmathurin** [comment]
FYI, We fixed the issue in the unstable branch. It will ship in the next patch / release.
