### ISSUE TITLE
How to make default selected as custom host

### ISSUE THREAD

**Issue by manish-metacube** [forcedotcom/SalesforceMobileSDK-iOS#1068]
Hi All, 

I am developing a hybrid application using Salesforce Mobile SDK 3.2. We have a customer requirement to ship the application custom host pre populated. 

I would like my application to start on my domain by default, instead of going on production ( login.salesforce.com). Whatever changes I made to configuration it will always take me to default production url when running app very first time. 

Even If i have deleted production setting and run the app. It will create a new item (with blank string) and take app to login.salesforce.com. 

@khawkins, @bhariharan Can you please look on this?

Here is code changes for root.plist file 
![screen shot 2015-06-23 at 3 45 39 pm](https://cloud.githubusercontent.com/assets/2398709/8303895/f8aea526-19be-11e5-9ca2-591660d70751.png)
![screen shot 2015-06-23 at 3 47 11 pm](https://cloud.githubusercontent.com/assets/2398709/8303922/364eb5ce-19bf-11e5-8ce9-f85984756456.png)
![screen shot 2015-06-23 at 3 47 27 pm](https://cloud.githubusercontent.com/assets/2398709/8303923/364ed540-19bf-11e5-9f94-8235665eea9c.png)

**Comment by akhileshgupta** [comment]
Please followup the conversation at the [Google+ Post](https://plus.google.com/106245938507947148265/posts/DMUXqatwUrA)

**Comment by manish-metacube** [comment]
Hi, 

https://developer.salesforce.com/forums/?id=906F0000000Ay3sIAC
above post help me in resolving the issue.

**Comment by bhariharan** [comment]
Please use our Google+ community for issues/queries.
