### ISSUE TITLE
SmartSQL comparing to NULL

### ISSUE THREAD

**Issue by McFlyssss** [forcedotcom/SalesforceMobileSDK-iOS#1070]
Hello guys,

I've been trying to compare SmartStore fields to NULL and it's not working in some cases.
Let me introduce you my situation.

For a query like this:

```javascript
<SFSoupQuerySpec:> { 
  queryType:"16" 
 smartSql:"SELECT {Object_0__c:Id},  {Object_0__c:Object_1__c} FROM {Object_0__c} WHERE {Object_0__c:Object_1__c} != 'NULL'" 
 pageSize: 1000
}
```

This is working and this query returns something like this:
```javascript
(
{
    "Object_1__c" = a0hb2GeTYAA0;
    Id = a0ib4FpjdAC;
},
{
    "Object_1__c" = a0hb2G3cQAAS;
    Id = 4Gq4oAAC;
},
{
    "Object_1__c" = a0hb0000AA4;
    Id = a0ib0vg8AAD;
},
{
    "Object_1__c" = a0hb00AAO;
    Id = a0ibOH5ZAAW;
},
{
    "Object_1__c" = a0hb0000SAAS;
    Id = 33mhAAA;
},
{
    "Object_1__c" = a0hb0fqfAAC;
    Id = a0ib0000AC;
}
)
```

If I query for all objects I've got this

```javascript
<SFSoupQuerySpec:> { 
  queryType:"16" 
 smartSql:"SELECT {Object_0__c:Id},  {Object_0__c:Object_1__c} FROM {Object_0__c} '" 
 pageSize: 1000
}

(
{
    "Object_1__c" = "<null>";
    Id = b0003vAAC;
},
{
    "Object_1__c" = "<null>";
    Id = a0ib000AAC;
},
{
    "Object_1__c" = "<null>";
    Id = a0ib0000AC;
},
{
    "Object_1__c" = a0hb00fAAC;
    Id = a008Uv3yAAC;
},
{
    "Object_1__c" = "<null>";
    Id = a008Uv3zAAC;
},
{
    "Object_1__c" = "<null>";
    Id = 08Uv40AAC;
},
... 
)
```

This returns all objects including the ones where the Object_1__c is NULL

But if I try to do the following query

```javascript
<SFSoupQuerySpec:> { 
  queryType:"16" 
 smartSql:"SELECT {Object_0__c:Id},  {Object_0__c:Object_1__c} FROM {Object_0__c} WHERE {Object_0__c:Object_1__c} = 'NULL'" 
 pageSize: 1000
}
```

No results there. But we've seen there are several objects with no value for that field. Any suggestions? 

Thanks!

**Comment by wmathurin** [comment]
The server returned the string "<null>" to represent null values so you will have to match that string in your query.
The following query should work as expected:

SELECT {Object_0__c:Id},  {Object_0__c:Object_1__c} FROM {Object_0__c} WHERE {Object_0__c:Object_1__c} = '<null>'

**Comment by McFlyssss** [comment]
Hi again!

```javascript
<SFSoupQuerySpec:> { 
  queryType:"16" 
 smartSql:"SELECT {Object_0__c:Id}, {Object_0__c:Object_1__c} FROM {Object_0__c} WHERE {Object_0__c:Object_1__c} = ''" 
 pageSize: 1000}
```

Still no results

**Comment by wmathurin** [comment]
Github messed up my previous comment (I should have escaped the &lt; of &lt;null>). Here is what I meant to say:

The server returned the string "&lt;null>" to represent null values so you will have to match that string in your query.
The following query should work as expected:

SELECT {Object_0__c:Id}, {Object_0__c:Object_1__c} FROM {Object_0__c} WHERE {Object_0__c:Object_1__c} = '&lt;null>'

**Comment by wmathurin** [comment]
To match for null, you should use IS NULL like you would with regular SQL
SELECT {Object_0__c:Id}, {Object_0__c:Object_1__c} FROM {Object_0__c} WHERE {Object_0__c:Object_1__c} IS NULL

**Comment by wmathurin** [comment]
Closing since this is a "how to" question rather than a bug. Re-open if you feel otherwise.

**Comment by McFlyssss** [comment]
That's working. Thanks!
