### ISSUE TITLE
CocoaPods fails when using !use_frameworks

### ISSUE THREAD

**Issue by btelintelo** [forcedotcom/SalesforceMobileSDK-iOS#1072]
We changed our pod file to use_frameworks!, like so:

platform :ios, "8.0"
use_frameworks!
pod 'SalesforceMobileSDK-iOS'

Now when I run pods install, I get the following error:
[!] The 'Pods' target has transitive dependencies that include static binaries: (/Users/project/Pods/OpenSSL-Universal/lib-ios/libcrypto.a and /Users/project/Pods/OpenSSL-Universal/lib-ios/libssl.a)

None of my other libraries have this issue.

I am using the latest cocoapods version 0.37.x

**Comment by wmathurin** [comment]
Our next release (3.3) is just around the corner (a few days away) and we no longer depend on open ssl.
Could you try it out and let us know if you still have any issues?
You need the following in your podfile:
 pod 'SalesforceMobileSDK-iOS', :git => 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git', :branch => 'unstable', :submodules => 'true'

**Comment by btelintelo** [comment]
I tried it and it fixed the cocoapods issue, but it still has problems with the imports.  For example, In SFRestRequest.h, the compiler is complaining about this format: #import <SalesforceSDKCore/SalesforceSDKConstants.h>

**Comment by nekonari** [comment]
I'm not sure if this is related, but 3.3.1 is failing to build on Xcode 7 with the following error:
```SalesforceMobileSDK-iOS-prefix.pch
'SalesforceCommonUtils/SFLogger.h' file not found```

I did find another issue on this, and there it said this problem was fixed, but I am running into it...

Any ideas?

**Comment by nekonari** [comment]
Never mind. It appears, it was indeed the issue with `use_frameworks!` which was required when using `RealmSwift`... now to find a way to apply `use_frameworks!` to just this pod..

**Comment by davidmdavis** [comment]
I'm having the same issue described by nekonari. 
    
    SalesforceMobileSDK-iOS-prefix.pch
    'SalesforceCommonUtils/SFLogger.h' file not found

Any suggestions besides removing use_frameworks!?

**Comment by nekonari** [comment]
I worked around by manually adding the library that requires `use_frameworks!` so I can add this pod. Very frustrating workaround... but it did the job for now.

**Comment by mgetzbw** [comment]
Is there any update on this, this is blocking using swift based apps

**Comment by wmathurin** [comment]
FYI, fixed in unstable (with that commit https://github.com/forcedotcom/SalesforceMobileSDK-iOS/commit/ebcff22c572bd4dc1fa74b94ee9839ba2f94ede8). Will be in our next release.

**Comment by mgetzbw** [comment]
@wmathurin just tested against unstable, verified that it's still breaking on public headers
