### ISSUE TITLE
MALFORM_ID issue when syncing parent and child through Mobile SDK 3.0

### ISSUE THREAD

**Issue by anandkumars12** [forcedotcom/SalesforceMobileSDK-iOS#1074]
I need to sync parent and child at a time to salesforce. I generate temporary order id in the app and associate that with child record. When I try to sync both parent and child at a time parent sync will be success but child doesn't. I get MALFORM_ID issue for child record.

Is there any way I can resolve this?

**Comment by wmathurin** [comment]
Can you give us more details.
Do you have a native or a hybrid application?
Are the parent and the child in two separate soups?

**Comment by anandkumars12** [comment]
It's a hybrid app and parent and child are in separate soup.

**Comment by wmathurin** [comment]
You need to save the children to the server first then replace the generated child id in the parent records and then finally save the parents to the server.
