### ISSUE TITLE
How to differentiate newly added and modified records

### ISSUE THREAD

**Issue by anandkumars12** [forcedotcom/SalesforceMobileSDK-iOS#1075]
I am using Salesforce Mobile SDK version 3.0 with Cordova to build Hybrid app for iOS. 

I have a situation like this in the app :

When I create an order I need to insert business partner associated with the order but when I update an existing order it shouldn't update the business partner. 

I do maintain a ignore list where it has got the fields which shouldn't update  when record is updated. But here user will create one order and will update one existing order. 
How do I differentiate between which record is updated and which is inserted?

**Comment by wmathurin** [comment]
Are you using smartsync.js or the smartsync plugin or neither?
If you are using smartsync.js or the smartsync plugin, then the records are stored in smartstore with additional flags: __local__, __locally_created__, __locally_updated__, __locally_deleted__.

**Comment by anandkumars12** [comment]
Yes, I so use smartsync.js and with the addition flags set when records added or modified. But in sync up method I do create ignore list in which I ignore few fields for updated records but those field shouldn't be ignored for newly added record. 

Creating ignore list will be executed only once before sync up. 

Can you give an simple example to deal with this kind of situation?

**Comment by wmathurin** [comment]
Look at the sync method in the AccountEditor.html sample app (https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/master/samples/accounteditor/AccountEditor.html line 367).
Line 393: we do:             return record.get("__locally_deleted__") ? record.destroy(options) : record.save(null, options);

You could do something similar if you need to handle newly added records differently from updated records. You would decide based on record.get("__locally_created__").

**Comment by anandkumars12** [comment]
I hope you have not understood my problem. I am already using  __locally_created__, __locally_updated__ flags when I modify data. when I do manual sync I want Business_partner__c field should be ignored for updated records but it shouldn't be ignored for newly created records.

Since I have added new record, modified existing record and sync both these at the same time I don't have control over separating new and updated record so that I can ignore   Business_partner__c field only for updated record.

**Comment by wmathurin** [comment]
How do you sync? Do you use the SmartSync cordova plugin or do you simply call save in a loop?
If you call save in a loop you could first check to see if you record was newly created and adjust the field list accordingly.

**Comment by anandkumars12** [comment]
I use smartsync of Cordova plugin. I use syncup method to sync data.
sync up method just accepts table name and field list.
Can you give example of saving in a loop?

On Thu, 2 Jul 2015 12:10 am Wolfgang Mathurin <notifications@github.com>
wrote:

> How do you sync? Do you use the SmartSync cordova plugin or do you simply
> call save in a loop?
> If you call save in a loop you could first check to see if you record was
> newly created and adjust the field list accordingly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1075#issuecomment-117791865>
> .
>
-- 

Thanks
Anand

**Comment by wmathurin** [comment]
A good example is the account editor
https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/master/samples/accounteditor/AccountEditor.html

You need to use include jquery.min.js, underscore-min.js, backbone-min.js, smartsync.js (there are all in the SalesforceMobileSDK-Shared repo).

smartsync.js is a very rich library, and there is a good amount of information about it in the MobileSDK guide. https://github.com/forcedotcom/SalesforceMobileSDK-Shared/raw/master/doc/mobile_sdk.pdf

Here is what you could do in your code.
```javascript
var cache = new Force.StoreCache("accounts", [ {path:"Name", type:"string"} ]);
cache.init();
var Account = Force.SObject.extend({
    sobjectType: "Account",
    cache: cache
});

var AccountCollection = Force.SObjectCollection.extend({
    model: app.models.Account,
    fieldlist: ["Id", "Name" ... ],
    cache: cache
});

// To get locally created/updated/deleted accounts
var localAccounts = new app.models.AccountCollection();
localAccounts.config = {type:"cache", cacheQuery: {queryType:"exact", indexPath:"__local__", matchKey:true, order:"ascending", pageSize:25}};
localAccounts.fetch({
            success: function(data) {
                 syncUp();
            },
            error: function() {
                alert("Failed to fetch local records");
            });

// Recursive function to save back locally created/udpated/deleted records to the server
function syncUp() {
        if (localAccounts.length == 0 || localAccounts.at(0).get("__sync_failed__")) {
            // we push sync failures back to the end of the list - if we encounter one, it means we are done
            return;
        }
        else {
            var record = localAccounts.shift();
            var fieldlist = record.get("\__locally_created__") ? [field list for newly created] : [field list otherwise];
            var options = {
                fieldlist: fieldlist,
                success: function() {
                    if (localAccounts.length > 0) { syncUp(); }
                },
                error: function() {
                    record = record.set("__sync_failed__", true);
                    localAccounts.push(record);
                    syncUp();
                }
            };
            return record.get("__locally_deleted__") ? record.destroy(options) : record.save(null, options);
        }

}
```
If you further questions, I recommend we continue this discussion on the [Mobile SDK community](https://www.sfdc.co/mobilesdkcommunity)

**Comment by anandkumars12** [comment]
Thanks for the response, do you have Angular JS example?

**Comment by akhileshgupta** [comment]
@anandkumars12 SDK's smartsync JS library is built using Backbone JS instead of Angular JS. If you want to build the same functionality using Angular, you can look here for reference: [https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/master/libs/smartsync.js](https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/master/libs/smartsync.js)
