### ISSUE TITLE
ENABLE_BITCODE

### ISSUE THREAD

**Issue by jeffreyjackson** [forcedotcom/SalesforceMobileSDK-iOS#1084]
this is a warning from iOS9 SDK, Salesforce SDK and many of its dependencies throw up this warning at the present time.

**Comment by bhariharan** [comment]
@jeffreyjackson Thanks for reporting this. We haven't tested against ```iOS 9``` yet.

**Comment by vibgy** [comment]
@jeffreyjackson  - I'm having trouble getting it to work in XCode 7 with iOS9. Is it even working for you? After disabling ENABLE_BITCODE for the Salesforce pod, the bridging header gives error when I try to include any salesforce sdk header files. Like this:

```
/tfly-Bridging-Header.h:4:9: error: 'SFRestAPI+QueryBuilder.h' file not found
#import <SFRestAPI+QueryBuilder.h>
        ^
<unknown>:0: error: failed to import bridging header 'tfly-Bridging-Header.h'
```

**Comment by jeffreyjackson** [comment]
We've disabled bitcode for our project, since its an enterprise app and will not benefit from this.  I'm not seeing any errors otherwise.

**Comment by bhariharan** [comment]
We won't be supporting bitcode at this time, since we're dependent of ```SQLCipher``` being built with bitcode enabled. However, our ```3.1.1``` patch release should address the other outstanding ```iOS 9``` issues.

**Comment by bhariharan** [comment]
@jeffreyjackson We have generated new binaries with bitcode enabled, so bitcode will be supported in our upcoming release. Meanwhile, if you want to start using it right away, it's available on our ```unstable``` branch [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1201/).
