### ISSUE TITLE
Neverending SSL errors 

### ISSUE THREAD

**Issue by jeffreyjackson** [forcedotcom/SalesforceMobileSDK-iOS#1092]
```
"Salesforce Error : can't connect to salesforce: An SSL error has occurred and a secure connection to the server cannot be made."
```

iOS 9b2 device, iOS 8.4 SDK, SF SDK 3.3.0 - Works
iOS 9b2 device, iOS 9.0b2 SDK, SF SDK 3.3.0 - ERROR
iOS 8.4 device, iOS 8.4 SDK, SF SDK 3.3.0 - Works

I believe the issue stems from a combination of the recent 3.3 SDK and iOS 9 beta.

cc @brad36

**Comment by wmathurin** [comment]
You need to turn off App Transport Security by adding a few entries in your app info plist file.
See https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1090

**Comment by wmathurin** [comment]
We refined the settings here https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1122

**Comment by jeffreyjackson** [comment]
cc @brad36
