### ISSUE TITLE
Documentation Layout is broken

### ISSUE THREAD

**Issue by mokamoto** [forcedotcom/SalesforceMobileSDK-iOS#1097]
Salesforce Mobile SDK for iOS Reference
http://forcedotcom.github.io/SalesforceMobileSDK-iOS/Documentation/masterTOC.html

It has wrong layout. Could you please check it?

**Comment by rwhitley** [comment]
Mitsuhiro-san, thank you for bringing this to our attention. I've issued a pull request for the fix.

Best regards,
Richard

**Comment by bhariharan** [comment]
This issue has been fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1098).
