### ISSUE TITLE
Warning message in Xcode 6.4 using SalesforceMobileSDK-iOS 3.3

### ISSUE THREAD

**Issue by sjacs5537** [forcedotcom/SalesforceMobileSDK-iOS#1099]
I am using SalesforceMobileSDK-iOS-Distribution and copy all required .a and header files to my project.

When I build my project, I got the warning below:

ld: warning: instance method 'outputCachePointers' in category from /My_Location/SalesforceNetwork-Release/libSalesforceNetwork.a(CSFNetwork+Caching.o) overrides method from class in /My_Location/SalesforceNetwork-Release/libSalesforceNetwork.a(CSFNetwork.o)

**Comment by jeffreyjackson** [comment]
I'm seeing the same thing, but only for simulator builds.  device builds seem ok.  

There is an open issue already here: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1058

**Comment by bhariharan** [comment]
Closing this, since we have an open issue for this already.
