### ISSUE TITLE
Settings Bundle not working in iOS9

### ISSUE THREAD

**Issue by jeffreyjackson** [forcedotcom/SalesforceMobileSDK-iOS#1100]
The settings bundle isn't working with iOS9, I'm using SDK 3.3.

None of the settings are passing through to the settings.app.

Please see screenshot below:

![img_0008 png](https://cloud.githubusercontent.com/assets/867999/8525664/4e4da502-23d0-11e5-901b-6637cf936533.png)

**Comment by bhariharan** [comment]
We're looking into moving the login host changer into the login view controller and removing the ```Settings``` bundle altogether. Stay tuned!

**Comment by jeffreyjackson** [comment]
cc @brad36

**Comment by jeffreyjackson** [comment]
@bhariharan do you have an estimate as to when there will be an SDK update that is compatible with iOS9?

**Comment by wmathurin** [comment]
In 4.0 for sure and maybe earlier in a 3.3 patch. Date is TBD.

**Comment by jeffreyjackson** [comment]
I appreciate the quick response, I'm trying to understand if it will be ready before iOS9 release (expected on Sept 9 or so).  Since the current SDK breaks functionality when built on iOS9

**Comment by wmathurin** [comment]
4.0 won't be out by then but the patch should be.

**Comment by jeffreyjackson** [comment]
@wmathurin thanks for following up, do you have a tentative idea as to when the patch will be made available?  The current SDK creates breaking issues when users upgrade to iOS9

**Comment by wmathurin** [comment]
No hard date but shooting to have it out by the time iOS9 comes out of beta.

**Comment by wmathurin** [comment]
It seems to work fine with Xcode 7 beta 6 (and SDK 3.3.1).
Please re-open, if it behaves differently for you.

**Comment by brad36** [comment]
I am using Xcode 7 beta 5 (7A176x) , SDK 3.3.1, iOS9b5, this appears to remain an intermittent issue in my testing on a device. I found that simply restarting the settings app restores the settings. I've not yet established what causes the settings to disappear in the first place.

**Comment by brad36** [comment]
Appears I can quite reliably reproduce by re-installing while the settings app is open

**Comment by carlcarter** [comment]
I can confirm I'm also experiencing the same issue with beta6/sdk3.3.1.

We actually overwrite the salesforce settings.bundle during a build phase with one we've cloned and added extra options of our own and experiencing the same issue as @brad36 and @jeffreyjackson have expressed.

**Comment by khawkins** [comment]
Just as a point of added color, the Settings app was broken in a number of ways in the iOS 8 SDK and simulator, all the way through the final betas of iOS 8, possibly even into/after RTM.  I wouldn't be surprised if it is again for iOS 9.

**Comment by carlcarter** [comment]
The fact that I am inserting the bundle myself during a build phase outside of the SDK does suggest thats probably the case here also @khawkins - shall retest tomorrow with the gm.

**Comment by sumanthness** [comment]
Though iOS 9 is released, I am not able to see the Sales Force settings in iPad Setting.
Can anybody please update on this ? if there is any workaround or resolution for this issue.

**Comment by ratishmah** [comment]
My custom host settings on iOS 9 isn't working. I was redirected to login.salesforce.com automatically. Any ideas when this issue will be resolved?

**Comment by shwetachitlangia** [comment]
Any update on this issue? I am still facing it. 

Is it still open?

**Comment by shwetachitlangia** [comment]
@bhariharan @wmathurin Could you please tell us when this issue will be resolved? This is blocking testing of our app for users.

**Comment by yfujiki** [comment]
It seems it is Settings app on iOS 9-9.1. You have to restart Settings app after re-installing the app. So lame...

http://stackoverflow.com/questions/2683793/settings-bundle-not-showing-up-in-iphone-settings

**Comment by wmathurin** [comment]
In our upcoming release, we are getting rid of the settings bundle.
Instead the login screen will have an extra button that allows you to change login host.
You can already try it in unstable: the change came with https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1368. And the removal of the settings bundle is coming in with: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1379.
