### ISSUE TITLE
Typo in plists for disabling Forward Secrecy

### ISSUE THREAD

**Issue by JeremyWright** [forcedotcom/SalesforceMobileSDK-iOS#1101]
Hey Guys,

Looks like the reason that the ATS changes for iOS9 might not have worked is because the change appears to have a typo.

https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1090/files#diff-61b7530e111ed4d10da1874684e74653R55

`NSExceptionDomamins` Should probably be `NSExceptionDomains`

**Comment by bhariharan** [comment]
@JeremyWright Indeed! Have you verified it works after fixing the typo?

**Comment by JeremyWright** [comment]
No, unfortunately I'm not really setup to test this. It's something our
team caught when researching the PFS problem on ios9.

On Monday, July 6, 2015, Bharath Hariharan <notifications@github.com> wrote:

> @JeremyWright <https://github.com/JeremyWright> Indeed! Have you verified
> it works after fixing the typo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1101#issuecomment-119019777>
> .
>


-- 
*Jeremy Wright *| *Lead Mobile Developer*
sales*force*.com
*Office: *(902) 720-4714
*Cell: *(902) 717-0310

**Comment by bhariharan** [comment]
Thanks for reporting this though. I'll take a look.

**Comment by JeremyWright** [comment]
Cool, was going to look at this tomorrow. I'll let you know if it works out if you haven't already fixed it.

**Comment by jeffreyjackson** [comment]
cc @brad36

**Comment by JeremyWright** [comment]
Hey heads up, I just tried getting this to work in our test apps, and it it doesn't seem to want to take.

Both on ios9 beta 1 and beta 2...

**Comment by bhariharan** [comment]
Thanks for trying @JeremyWright.

**Comment by jeffreyjackson** [comment]
Has this been tested on iOS9 b3? cc @JeremyWright

**Comment by bhariharan** [comment]
Nope - I haven't done any ```iOS 9``` testing yet. I'm hoping @JeremyWright will have some info on this front.

**Comment by JeremyWright** [comment]
I was playing with it on the b3,

I was able to get this to finally behave by adding the: `NSThirdPartyExceptionRequiresForwardSecrecy` key.

```xml
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>yourdomain.com</key>
			<dict>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<false/>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
				<false/>
			</dict>
		</dict>
	</dict>
```

**Comment by wmathurin** [comment]
We fixed it here: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1122

**Comment by jeffreyjackson** [comment]
cc @brad36
