### ISSUE TITLE
iOS9 requires authentication every launch

### ISSUE THREAD

**Issue by jeffreyjackson** [forcedotcom/SalesforceMobileSDK-iOS#1104]

**Comment by jeffreyjackson** [comment]
cc @bhariharan

**Comment by bhariharan** [comment]
So, the sample apps don't work on ```iOS 9```? We haven't looked into ```iOS 9``` yet.

**Comment by wmathurin** [comment]
The fix is available on unstable see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1123
