### ISSUE TITLE
Post multipart/form-data request using SFRestRequest 

### ISSUE THREAD

**Issue by sjacs5537** [forcedotcom/SalesforceMobileSDK-iOS#1118]
I am trying to upload attachment to a feed through Chatter REST API using salesforce SDK V3.2 for iOS, I checked the document at https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/intro_input.htm#cc_upload_binary_files and wrote some codes to post it. However, I got the error message:

Error Domain=CSFNetworkErrorDomain Code=400 "Binary data included but file attachment information is missing. If providing rich JSON/XML input in multipart REST, make sure to include Content-Type header in the part." UserInfo=0x7fa1bad94260 {NSLocalizedFailureReason=POST_BODY_PARSE_ERROR, isAuthenticationFailure=false, NSLocalizedDescription=Binary data included but file attachment information is missing. If providing rich JSON/XML input in multipart REST, make sure to include Content-Type header in the part., action=<SFRestAPISalesforceAction: 0x7fa1bad98030, POST "">}

Here is my testing code:

SFRestMethod method = SFRestMethodPOST;
SFRestRequest *request = [SFRestRequest requestWithMethod:method path:nil queryParams:paramDict];
request.endpoint = @"/services/data/v33.0/connect/communities/0DB28000000Cafi/chatter/feed-elements";

NSString *filestr= [[NSBundle mainBundle] pathForResource:@"Pic" ofType:@"png"];
[request addPostFileData:[NSData dataWithContentsOfFile:filestr] paramName:@"feedElementFileUpload" fileName:@"test.png" mimeType:@"image/png"];
[request setCustomHeaders:[NSDictionary dictionaryWithObject:@"multipart/form-data" forKey:@"Content-Type"]];
[[SFRestAPI sharedInstance] send:request delegate:self];

Printing description of paramDict:
{
    body =     {
        messageSegments =         (
                        {
                text = "test msg";
                type = Text;
            }
        );
    };
    capabilities =     {
        content =         {
            description = "Test image";
            title = "test.png";
        };
    };
    feedElementType = FeedItem;
    subjectId = 0F928000000Ches;
}

Can SFRestRequest post multipart/form-data request? Or is there anything I am missing or wrong?

**Comment by sjacs5537** [comment]
cc @bhariharan 
It seems cannot be done by SFRestRequest.
I use AFNetworking and import accessToken into HTTPHeaderField to do this job finally.
Here is the detail:
http://qiita.com/pomu0325/items/9325ef6a72c4f36a7c3f

**Comment by wmathurin** [comment]
We support file upload. You should look at SFRestRequest+Files.m, in particular the requestForUploadFile method.

**Comment by sjacs5537** [comment]
@wmathurin 
Thanks for reply

But requestForUploadFile do not support to post a new feed item, upload a binary file, and attach it to the new feed item as the document mention in my previous comment.

**Comment by wmathurin** [comment]
Indeed we don't provide a method that does the post to feed with file but you could write your own and use the implementation of requestForUploadFile as inspiration

```objective-c
NSString *path = [NSString stringWithFormat:@"/%@/chatter/{put the right path}", self.apiVersion];
NSMutableDictionary *params = [NSMutableDictionary dictionary];
// add the right params here
SFRestRequest *request = [SFRestRequest requestWithMethod:SFRestMethodPOST path:path queryParams:params];
[request addPostFileData:data paramName:FILE_DATA fileName:name mimeType:mimeType];

**Comment by sjacs5537** [comment]
@wmathurin 
Your code looks similar to my testing code in my previous comment.

But it will return error as below:
Error Domain=CSFNetworkErrorDomain Code=400 "Binary data included but file attachment information is missing. If providing rich JSON/XML input in multipart REST, make sure to include Content-Type header in the part." UserInfo=0x7fa1bad94260 {NSLocalizedFailureReason=POST_BODY_PARSE_ERROR, isAuthenticationFailure=false, NSLocalizedDescription=Binary data included but file attachment information is missing. If providing rich JSON/XML input in multipart REST, make sure to include Content-Type header in the part., action=}

Anyway, I use AFNetworking to do that finally.
Thanks.
