### ISSUE TITLE
Cannot close SFAuthenticationManager after launch is called

### ISSUE THREAD

**Issue by sjacs5537** [forcedotcom/SalesforceMobileSDK-iOS#1132]
Did the SDK provide any function to close the OAuth webview in SFAuthenticationManager???

I tried to add a close button using the SFAuthenticationManagerDelegate:

- (void)authManager:(SFAuthenticationManager *)manager willDisplayAuthWebView:(UIWebView *)view;

But I cannot find any function to close the webview directly.

I try to call [[SFAuthenticationManager sharedManager].authViewController dismissViewControllerAnimated:YES completion:nil]; directly in my code, but the "_isLaunching" flag is already set to YES in SalesforceSDKManager, so I cannot call [[SalesforceSDKManager sharedManager] launch]; again after the webview is dismissed.

Any other possible way to do that?

Thank you

**Comment by sjacs5537** [comment]
cc @bhariharan @wmathurin 
I wrote my own method to force the OAuth webview to quit and reset the state by:
[SFPushNotificationManager sharedInstance].deviceSalesforceId = nil;
[[SFAuthenticationManager sharedManager] logout];
[[SFAuthenticationManager sharedManager].authViewController dismissViewControllerAnimated:YES completion:nil];

If I do not set deviceSalesforceId = nil, the SDK will crash in SFPushNotificationManager.m:
line 251:     NSString *deviceSFID = [[NSString alloc] initWithString:[pref stringForKey:kSFDeviceSalesforceId]];
because [pref stringForKey:kSFDeviceSalesforceId] will return nil.

It seems to need to reset _deviceSalesforceId in:
- (BOOL)unregisterSalesforceNotifications

Please ignore above comments if the flow of closing OAuth webview is not acceptable.

**Comment by wmathurin** [comment]
Could you explain why one would need to do that? Thanks.

**Comment by sjacs5537** [comment]
We have a app which can get and display public and private information from salesforce account.
Unless the user kill the app, they are not able to cancel their login decision or close the OAuth webview, our app like 'frozen' and they cannot browse any other public information.
It is the user experience from our app user.

**Comment by wmathurin** [comment]
I see, we will investigate. Thanks.

**Comment by huminzhi** [comment]
The issue is fixed or solved in latest build.
