### ISSUE TITLE
Pin Security Issue - App fails to require pin if timeout occurs in background

### ISSUE THREAD

**Issue by jeremyhenson** [forcedotcom/SalesforceMobileSDK-iOS#1147]
(validated this with a fresh, unmodified, app built with forceios 3.3.0)

The app stops asking for a pin if the timer expires while the app is running in the background.

The log shows this error:
```
Warning: Attempt to present <UINavigationController: 0x7ea06260> on <UIViewController: 0x7be899e0> whose view is not in the window hierarchy!
```

**Comment by wmathurin** [comment]
Thanks for bringing up this issue to our attention. We will investigate and post updates here.

**Comment by bhariharan** [comment]
@jeremyhenson I can't reproduce this issue on our sample apps in the ```unstable``` branch. When the app is launched, the PIN screen does show up, even if the timeout occurred in the background. Feel free to reopen this issue if you encounter it on our ```unstable``` branch.
