### ISSUE TITLE
iOS9 + login = SSL error

### ISSUE THREAD

**Issue by mtetlow** [forcedotcom/SalesforceMobileSDK-iOS#1155]
I am receiving this error: An SSL error has occurred and a secure connection to the server cannot be made. when the login screen is loading after an upgrade of an app to ios9 beta and SalesforceMobileSDK 3.3.0 via cocoapods.

Here is the log: https://gist.github.com/mtetlow/853873a9d4352748d915 

It appears adding this to the info.plist:
`<key>NSAppTransportSecurity</key>  
  <dict>  
  <key>NSAllowsArbitraryLoads</key>  
  <true/>  
  </dict> ` 
resolves the issue. Source of this is: http://stackoverflow.com/questions/5040531/ssl-error-in-connection-to-server-through-iphone .

I would rather not do this. Any idea what the issue is here? It seems to be something to do with the overall connection, though it does seem to identify as TLS1.2.

**Comment by wmathurin** [comment]
The server does not (yet) support forward secrecy. So instead of allowing arbitrary loads, you can simply disable the requirement forward secrecy for the salesforce.com/force.com domains (see below).

NB: those changes are already in the unstable branch (https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1122)

```xml
 <key>NSAppTransportSecurity</key>
    <dict>
      <key>NSExceptionDomains</key>
      <dict>
        <key>salesforce.com</key>
        <dict>
          <key>NSIncludesSubdomains</key>
          <true/>
          <key>NSExceptionRequiresForwardSecrecy</key>
          <false/>
        </dict>
        <key>force.com</key>
        <dict>
          <key>NSIncludesSubdomains</key>
          <true/>
          <key>NSExceptionRequiresForwardSecrecy</key>
          <false/>
        </dict>
      </dict>
    </dict>
  </dict>

**Comment by mtetlow** [comment]
Thanks for the prompt response!
