### ISSUE TITLE
Bunch of warnings

### ISSUE THREAD

**Issue by nekonari** [forcedotcom/SalesforceMobileSDK-iOS#1164]
Am I the only one receiving 4 deprecations warnings in `SFPushNotificationManager.m` and 34 issues in `SQLCipher`?

<img width="419" alt="screen shot 2015-08-27 at 3 38 22 pm" src="https://cloud.githubusercontent.com/assets/3915008/9531051/a85f0782-4cd1-11e5-920e-0c90c6713476.png">

FYI, I'm developing with Xcode 6.4 targeting iOS 8+ in Swift.

**Comment by wmathurin** [comment]
The Mobile SDK supports iOS 7.0 (and of course iOS 8.0 and iOS 9.0).
At some point in the (near) future, we will drop support for iOS 7.0 and at that point we will stop using APIs that were deprecated in iOS 8.0.
