### ISSUE TITLE
+ (NSURL*)urlForAction:(CSFAction*)action error:(NSError**)error crashes the app

### ISSUE THREAD

**Issue by dcacenabes** [forcedotcom/SalesforceMobileSDK-iOS#1168]
CSFAction.m file

Line 64:
NSMutableString *baseUrlString = [NSMutableString stringWithString:[action.enqueuedNetwork.account.credentials.apiUrl absoluteString]];

action.enqueuedNetwork.account.credentials.apiUrl is nil

2015-09-02 14:07:15.704 crew[66254:4666289] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSPlaceholderMutableString initWithString:]: nil argument'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001105a0c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000011012bbb7 objc_exception_throw + 45
	2   CoreFoundation                      0x00000001105a0b9d +[NSException raise:format:] + 205
	3   Foundation                          0x000000010d9427d1 -[NSPlaceholderMutableString initWithString:] + 99
	4   Foundation                          0x000000010d94275b +[NSString stringWithString:] + 45
	5   crew                                0x000000010b32c4d1 +[CSFAction urlForAction:error:] + 337
	6   crew                                0x000000010b331f61 -[CSFAction createURLRequest:] + 65
	7   crew                                0x000000010b32f397 -[CSFAction start] + 647
	8   Foundation                          0x000000010d930383 __NSOQSchedule_f + 184
	9   libdispatch.dylib                   0x0000000110dd5614 _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x0000000110dbc6a7 _dispatch_queue_drain + 2176
	11  libdispatch.dylib                   0x0000000110dbbcc0 _dispatch_queue_invoke + 235
	12  libdispatch.dylib                   0x0000000110dbf3b9 _dispatch_root_queue_drain + 1359
	13  libdispatch.dylib                   0x0000000110dc0b17 _dispatch_worker_thread3 + 111
	14  libsystem_pthread.dylib             0x0000000111142a9d _pthread_wqthread + 729
	15  libsystem_pthread.dylib             0x00000001111403dd start_wqthread + 13
)

**Comment by dcacenabes** [comment]
Forgot to say this happens in 3.3

**Comment by wmathurin** [comment]
Thanks for reporting the issue. We will investigate and let you know what we find out.

**Comment by McFlyssss** [comment]
Same happening here. Any clue on this?

**Comment by McFlyssss** [comment]
I realised if we completely close the app and run it again everything works fine again.

**Comment by huminzhi** [comment]
@McFlyssss #1189 is fixed in latest unstable branch, not sure if you can try and see if you still encounter this with latest code?

**Comment by huminzhi** [comment]
It seems already fixed. Please let us know if you still see it..
