### ISSUE TITLE
Cannot call SFRestAPI.sharedInstance().send from Swift class

### ISSUE THREAD

**Issue by craigisakson** [forcedotcom/SalesforceMobileSDK-iOS#1172]
I built a bare bones app from forceios and am trying to call the Rest API in Swift but the send method does not seem to be recognized.

Everything else seems to be working.  Here is a link to the issue in the forum.

https://developer.salesforce.com/forums/?id=906F0000000BURcIAO

**Comment by wmathurin** [comment]
There is an example (in the unstable branch):
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/unstable/build/app_template_files/__NativeSwiftTemplateAppName__/__NativeSwiftTemplateAppName__/RootViewController.swift

To see it in action, clone the repo. Go to build/app_template_files and run createApp.sh.
For the app type, make sure to choose native_swift. 

createApp.sh is the script that forceios invokes to generate new apps.
Once we release 4.0, we will push the new version of forceios to npm.
In the mean time, you need to run the createApp.sh directly.

In 4.0, you can create native (objective-c), native (swift) and even react native apps. And the generated apps are leveraging cocoapods to pull the SDK source code. So debugging (and updating) should be a lot easier.

**Comment by wmathurin** [comment]
Do you have a bridging header ?
For an example, look at https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/unstable/build/app_template_files/__NativeSwiftTemplateAppName__/__NativeSwiftTemplateAppName__/Bridging-Header.h

You need also to have the right setting in your xcode project.
See the line with SWIFT_OBJC_BRIDGING_HEADER in
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/unstable/build/app_template_files/__NativeSwiftTemplateAppName__/__NativeSwiftTemplateAppName__.xcodeproj/project.pbxproj

**Comment by craigisakson** [comment]
Hi Wolfgang,

Thank you very much for your input.  I updated my bridging header to match your example and it worked!  My previous header looked like:

#import <UIKit/UIKit.h>
#import "SFRestAPI.h"
#import "SFRestRequest.h"

Thanks again for your help!
