### ISSUE TITLE
Clone issue from the repo

### ISSUE THREAD

**Issue by sjacs5537** [forcedotcom/SalesforceMobileSDK-iOS#1179]
I follow the installation guide and got the error:
./install.sh 
Synchronizing submodule url for 'external/ThirdPartyDependencies'
Synchronizing submodule url for 'external/cordova-ios/cordova-ios'
Synchronizing submodule url for 'external/fmdb'
Synchronizing submodule url for 'external/ocmock'
Synchronizing submodule url for 'external/shared'
Submodule path 'external/ThirdPartyDependencies': checked out '2d0c1f0b5a704a69ca98a2b29af434b8dd9ad189'
Submodule path 'external/cordova-ios/cordova-ios': checked out '5cee36c6716c771d475c2c835560435d9feef351'
fatal: Not a git repository: ../../.git/modules/external/fmdb

**Comment by wmathurin** [comment]
We have never seen that. Did you start from a clean clone (meaning where you updating an existing repo and did you clone the repo)? What version of git are you using?

**Comment by sjacs5537** [comment]
Solve it by deleting all local repo and re-clone.
Thanks
