### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by odyssey1357** [forcedotcom/SalesforceMobileSDK-iOS#1184]
Hello
How can we manually refresh token? There is CSFTokenRefresh class that you use in CSFAction for refresh token when request is failed, but this class is in private folder and I can't import this file in my project (I added SF SDK via Cocoapods). Can you recommend some solution?
Thanks

**Comment by powerje** [comment]
I force a refresh using the SFAuthenticationManager classes `loginWithCompletion:failure` method.

**Comment by wmathurin** [comment]
Please post this type of question on our G+ community https://plus.google.com/communities/114225252149514546445.
We typically use github issues for bugs.
