### ISSUE TITLE
Switching orgs and logging out of one instance automatically logs you into the previous instance

### ISSUE THREAD

**Issue by manish-metacube** [forcedotcom/SalesforceMobileSDK-iOS#1187]
Steps to reproduce

1) Set the app settings environment to Production
2) Log into a Production environment 
3) Go back to the app settings and set the environment to Sandbox
4) Reopen the app (You will be asked for login as expected)
5) Log into a Sandbox environment
6) Log out
Result: a white screen is displayed, and after a delay, the app refreshes and you are logged into the Production instance you were logged into in step 2. 

We need to use single user instance in our app, using [SFAccountManagerPlugin] (https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/multiuser_hybrid.htm#hybrid_switch_to_user) methods we are able to remove last session when user switches environment after step #5. But if user doesn't login in step #5 and kill the app, App will take first session and on the backend environment still shows Sandbox. Any way to fix missmatch?

Regards,
Manish Kumar

**Comment by wmathurin** [comment]
@bhariharan is it the expected behavior?

**Comment by bhariharan** [comment]
This is expected behavior. If the user is logged into 2 accounts and logs out of 1, the app will automatically switch to the remaining existing account.
