### ISSUE TITLE
SFSmartStoreDatabaseManager is not properly initialized during logout which prevents sync from working when you log back in

### ISSUE THREAD

**Issue by jackiedpeacock** [forcedotcom/SalesforceMobileSDK-iOS#1189]
We are using v3.3 of the Mobile SDK for iOS. The issue is that when a user logs out of our mobile app and then logs back in as the same user (without closing/restarting the mobile app) the sync no longer works. The following are the details of the source of the problem in the SDK.

When a logout occurs in the SDK - the following sequence of events occur:
a. In the SalesforceSDKManager - the willLogoutUser method gets called. This in turn calls removeAllStoresForUser.
b. In the removeAllStoresForUser - the SFSmartStoreDatabaseManager's removeSharedManagerForUser gets calls. This results in the user's database object from before removed from the SFSmartStoreDatabaseManager's sDatabaseManagers dictionary. Note that in the SFSmartStoreDatabaseManager there is a user object stored - and that at this point still contains the user information for the user being logged out.
c. In the SFSmartSyncManager, the willLogoutUser method gets called. This in turn calls removeSharedInstanceForUser.
d. In the removeSharedInstanceForUser method, it calls SFSmartStore's sharedStoreWithName method - which results in a call to SFSmartStoreDatabaseManager's sharedManagerForUser - which results in a call to initWithUser - which sets its user property to the user that now does not contain credentials information (e.g. user.credentials.userId is nil) and adds the user's database to the sDatabaseManager (basically undoing what was done in b).

Now - the login screen will appear. If you log back in as the same user, and then call SFSmartSyncSyncManager sharedInstance to get an instance of the sync manager - sharedInstance will return nil - so you cannot sync your data - so the data in the app is empty. The reason why it's returning nil is the user.credentials.organizationId and user.credentials.userId stored by the user in the SFSmartStoreDatabaseManager are nil. So - in the following chain of calls that result from calling sharedInstance - the last call returns nil - which bubbles up through the calls to the sharedInstance as nil.

SFSmartSyncManager - sharedInstanceForUser
SFSmartSyncManager - sharedInstanceForStore
SFSmartStore - storePath
SFSmartStoreDatabaseManager - fullDbFilePathForStoreName
SFSmartStoreDatabaseManager - storeDirectoryForStoreName
SFSmartStoreDatabaseManager - rootStoreDirectory
SFDirectoryManager - directoryForUser <--This generates a warning in the log that the credentials are missing because the user.credentials.organizationId and userId are nil. This method then returns a nil which results in a nil being returned by the sharedInstance - so - we are unable to make any sync calls.

I think the resolution to this should be that during logout you should not be adding back the database store of the user logging out - and - you need to ensure the user property that is stored in the SFSmartStoreDatabaseManager gets properly initialized during log out.﻿

**Comment by wmathurin** [comment]
Thanks for bringing it up. We will investigate and update this issue with our progress.

**Comment by e-bacho** [comment]
Bump! Any updates on this? I also have the same problem in a Hybrid app

**Comment by wmathurin** [comment]
The issue was fixed in the unstable branch https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1234 and will be part of our next release.
