### ISSUE TITLE
Community URL is dropping the '/' between community name page name in hybrid app

### ISSUE THREAD

**Issue by craigisakson** [forcedotcom/SalesforceMobileSDK-iOS#1195]
I am creating a hybrid app with the new SDK.  I created the app from forceios and am making it a hybrid remote app.  The user is able to login but the forward slash between the community and the page name is being dropped somewhere in the OAuth flow.

https://sandbox-mydomain-nao.cs24.force.com/communityname/home

is some how transposed to 

https://sandbox-mydomain-nao.cs24.force.com/communitynamehome

I have the same exact settings as an app that is pointing to the same community only using a previous version of the sdk and it is working correctly.

Any help that can be provided would be greatly appreciated.

Thanks!!
Craig

**Comment by kchitalia** [comment]
What version of the Mobile SDK are you using?

**Comment by craigisakson** [comment]
3.3.0

**Comment by huminzhi** [comment]
The issue is fixed or solved in latest build.
