### ISSUE TITLE
libSalesforceCommonUtils.a(SFCrypto.o) does not contain bitcode

### ISSUE THREAD

**Issue by hari8815** [forcedotcom/SalesforceMobileSDK-iOS#1197]
In my hybrid mobile app with mobile sdk 3.3.0, I am getting following error "ld: '/Plugins/com.salesforce/libSalesforceCommonUtils.a(SFDateUtil.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7". It happens after the ios 9.0 and xcode 7.0 update. Please help me to resolve this issue.

I have updated the salesforce sdk to 3.3.1. Now I am getting different error message  "/Plugins/com.salesforce/libSalesforceCommonUtils.a(SFCrypto.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64"

**Comment by bhariharan** [comment]
@hari8815 We are aware of this. For now, ```SalesforceMobileSDK``` works only with bitcode disabled. We have done this across the board [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1188). We will evaluate enabling bitcode in a future release.

**Comment by hari8815** [comment]
@bhariharan Thanks, Now i can able to run. Also we are planning for app store submission, disabling bitcode may affect the release?

**Comment by bhariharan** [comment]
@hari8815 I don't imagine that's the case, but that's something for you to check with Apple. We will be supporting bitcode in a future release. Stay tuned!

**Comment by khawkins** [comment]
According to [Apple's docs](https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html#//apple_ref/doc/uid/TP40012582-CH35-SW3):

> **Note:** For iOS apps, bitcode is the default, but optional. If you provide bitcode, all apps and frameworks in the app bundle need to include bitcode. For watchOS apps, bitcode is required.

So as for being required, the short answer is, "It depends."

**Comment by bhariharan** [comment]
We have enabled bitcode in our ```unstable``` branch. Feel free to check it out [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1201/). This will be a part of our upcoming release.
