### ISSUE TITLE
After upgrading to iOS 9 App is asking for login screen all times

### ISSUE THREAD

**Issue by manish-metacube** [forcedotcom/SalesforceMobileSDK-iOS#1198]
Hi All, 

We have recently upgraded our devices to iOS 9 and after upgrade we have seen following issues- 

1. App is logging out even if user has kill the app or run twice in simulator (it will ask for login again)
2. When user re-login pin screen doesn't appear(if configured).
3. App is unable to use smartstore at all. 
4. re-login again will solve the problem. 

Can someone provide fix for these issues?

@khawkins  Can you help me on this? it's very critical and we have release scheduled. 

Regards,
Manish Kumar

**Comment by bhariharan** [comment]
We have fixed the ```iOS 9``` login issues in our latest patch release (```v3.3.1```). For more information on the changes, or if you need to make the same changes on an older version of ```Mobile SDK```, follow the instructions in our blog post [here](https://rwhitleysfdc.wordpress.com/2015/09/29/tips-for-upgrading-mobile-sdk-apps-for-ios-9/).
