### ISSUE TITLE
Stuck on splash screen when push notification pop-up appears

### ISSUE THREAD

**Issue by maubardsylpheo** [forcedotcom/SalesforceMobileSDK-iOS#1199]
Hi,

I tried to use Mobile SDK with my app. 
When you activate Push Notifications on a native app, you are stuck in the splash screen.

To reproduce 
- Create a new project using forceios
- Add this line in init method : 
if ([[UIApplication sharedApplication] respondsToSelector:@selector(registerUserNotificationSettings:)]) {
            UIUserNotificationSettings *settings = [UIUserNotificationSettings settingsForTypes:UIUserNotificationTypeBadge|UIUserNotificationTypeSound|UIUserNotificationTypeAlert categories:nil];
            [[UIApplication sharedApplication] registerUserNotificationSettings:settings];
        }
- When you launch the app for the first time, a pop-up (push notification authorization) appears. Wait for login screen to load before clicking ok.
- When you click on ok, you are now stuck on splash screen.

Is there a workaround ?

Thanks,

Best regards,

Marion @ Sylpheo

**Comment by wmathurin** [comment]
What version of the Mobile SDK are you using?
We made a fix in 3.3 in that area (see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1080/files).
If you generated your application with an older version of the SDK, you should manually apply the changes from the fix linked above in your AppDelegate.m

**Comment by maubardsylpheo** [comment]
Hello Wolfgang,

Thanks for your quick answer. I tested with the last version published on forceios. I don’t use SF push notifications, but notifications coming from another service. I will look at your change in AppDelegate.

Thanks !

Marion AUBARD
Ingénieur développement projets Salesforce et mobilité
Sylpheo
www.sylpheo.com <http://www.sylpheo.com/>
marion.aubard@sylpheo.com <mailto:marion.aubard@sylpheo.com>
Lundi-Jeudi: 8H30-12H 13H30-17H 
Vendredi: 8H30-12H 

[+] Add me to your address book <https://ws.evercontact.com/kwaga-bin/titan/WEB/me.pl/9967957841396253200/i>

**Comment by maubardsylpheo** [comment]
Thanks, it works ! Well done !

Best regards,

Marion @ Sylpheo
