### ISSUE TITLE
SF SDK 3.3.1 app is working on ios 8 but stuck at launch screen in iOS9

### ISSUE THREAD

**Issue by ratishmah** [forcedotcom/SalesforceMobileSDK-iOS#1200]
SF SDK 3.3.1 app is working on ios 8 but stuck at launch screen in iOS9. I can't proceed to login screen. 
No Logs in console as well. Please help me on this.

**Comment by wmathurin** [comment]
Could you give us more information. Is it a native or an hybrid application? Did you create the application with forceios or are you using cocoapods?

**Comment by ratishmah** [comment]
I got that working only after i commented out the code for crash reporting tool that i am using in the project. Thanks for the swift reply.
