### ISSUE TITLE
SFDateUtil.toSOQLDateTimeString returns wrong time format

### ISSUE THREAD

**Issue by fobin** [forcedotcom/SalesforceMobileSDK-iOS#1204]
Calling 
```
SFDateUtil.toSOQLDateTimeString(NSDate(), isDateTime: true)
```
Returns two different time stamps depending on iPhone clock settings and language. If user has selected 24-hour clock everything works at it returns 
```
2015-10-06T17:59:26.000Z
```
If clock is set to 12-hour format and language is set to for example Finnish or German it returns like this:
German:
```
2015-10-06T6:11:44 nachm..000Z
```
Finnish:
```
2015-10-06T6:15:00 ip..000Z
```

English and US seem to work ok in both settings.

iOS 9, XCode 7.0.1. 
Notice! In simulator it seems to work always since you cannot change the clock between 12 and 24 hours format.
Cannot debug further since no access to Utils.

**Comment by fobin** [comment]
And a solution to mitigate this problem I create the timestamp by hand now forcing the locale change to give me 24 hour timestamp.

```
private func createSalesforceTimeString() -> String {
        let locale = NSLocale(localeIdentifier: "en_US_POSIX")
        let formatter = NSDateFormatter()
        let timeZone = NSTimeZone(abbreviation: "GMT")
        formatter.timeZone = timeZone
        formatter.locale = locale
        formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.000"
        
        return formatter.stringFromDate(NSDate())
    }
```

**Comment by bhariharan** [comment]
```SFDateUtil``` doesn't exist in the ```Mobile SDK``` anymore.

**Comment by jeffreyjackson** [comment]
I whipped up two of the methods [here](https://github.com/jeffreyjackson/SFDateUtil)
