### ISSUE TITLE
PIN Lock not present after iOS Auto-Lock 

### ISSUE THREAD

**Issue by hari8815** [forcedotcom/SalesforceMobileSDK-iOS#1208]
I am working on salesforceSDK hybrid mobile app (ionic app).I have enabled pin lock in SFDC connected app settings. After SF login and oAuth confirmation,the pin-lock black screen presented correctly. Now let the device display to turned-off and auto-locked. After this, if i open the device with auto-lock password and open the hybrid app, it fails to show up the pin lock black screen. Also the app hangs at this point of time. Need to force close the app every time, when this situation encountered.

**Comment by wmathurin** [comment]
Could you tell us what version of the Mobile SDK you are using?

**Comment by hari8815** [comment]
@wmathurin  Currently I am using 3.3.2. Previously it was 3.3.0. Both version has this issue. Hard to reproduce this issue, when we run the app from xcode. To reproduce, disconnect from xcode and test like end user.

**Comment by hari8815** [comment]
@wmathurin  Any update on this issue?

**Comment by hari8815** [comment]
This issue also exist in the latest sdk 4.0.0

**Comment by huminzhi** [comment]
The issue is fixed or solved in latest build.
