### ISSUE TITLE
Single Sign-On in SFDC

### ISSUE THREAD

**Issue by rovqapint** [forcedotcom/SalesforceMobileSDK-iOS#1212]
With integration of Single Sign-On in SFDC it allows to login via other Portals. With checked option in My domain  "Disable login via "test.salesforce.com" we are forcing users to use our custom Portal login procedure. But in case of System Administrators, or Users who do not have access to custom Portal there is a hack in browser with parameter "/?login" added to existing url (e.g. "https://name--testfs.cs6.my.salesforce.com/?login ", which allows to login via test.salesforce.com anyway. How can we integrate the same behavior into SFDC iOS SDK?  (such as now standard SFDC iOS SDK does not allow to use url types like "https://name--testfs.cs6.my.salesforce.com/?login", because I assume this is strictly html stuff)

**Comment by bhariharan** [comment]
This is not possible out of the box. However, the Mobile SDK is open source, so you're welcome to override our stock components to suit your requirements.
