### ISSUE TITLE
Salesforce iOS native app UI not showing proper with IOS 9.

### ISSUE THREAD

**Issue by narendermyname** [forcedotcom/SalesforceMobileSDK-iOS#1214]
salesforce iOS native app created with forceios ui not showing proper.
it shows black screen in top and bottom area.

![simulator screen shot 16-oct-2015 3 31 28 pm](https://cloud.githubusercontent.com/assets/5429320/10539172/689a8df8-741b-11e5-9c34-a168c1213b53.png)

**Comment by wmathurin** [comment]
This is fixed that in unstable (our upcoming release).
If you can't wait simply make that change in your app: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/commit/4bf17b6db1132e1627fb0bd864acdbbf29cc7094
