### ISSUE TITLE
Change Password part of oAuth process doesn't appear to be functional on iOS9

### ISSUE THREAD

**Issue by brad36** [forcedotcom/SalesforceMobileSDK-iOS#1217]
I'm using SDK 3.3.1. When the oAuth screen requires the user to change their password, and takes them into the Change Password page, then the 8 character / 1 letter / 1 number status lights don't come on, and the change password button never becomes enabled. Seems to work OK on iOS8 though

**Comment by brad36** [comment]
We have discovered this is an issue with some hardware keyboards on iOS9 only

**Comment by bhariharan** [comment]
The 'Change Password' flow is within the WebView on the login page, which Mobile SDK has no control over. We are simply rendering the login page on mobile.
