### ISSUE TITLE
Objective-c enum declarations should play nice with Swift

### ISSUE THREAD

**Issue by fobin** [forcedotcom/SalesforceMobileSDK-iOS#1218]
This from SFSyncDownTarget:
```
typedef enum {
  SFSyncDownTargetQueryTypeMru,
  SFSyncDownTargetQueryTypeSosl,
  SFSyncDownTargetQueryTypeSoql,
  SFSyncDownTargetQueryTypeCustom
} SFSyncDownTargetQueryType;
```

Should be converted to NS_ENUM to function with Swift. And there are others like this also.

**Comment by mgetzbw** [comment]
@wmathurin @bhariharan I will be slowly making pulls on this as I get to bits that are particularly egregious. If there are headers that you would prefer I focus on let me know, I am trying to be very conservative in what I do for now as I don't want to cause any implementation changes.

**Comment by wmathurin** [comment]
Done here https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1380
Will be part of our next release.
