### ISSUE TITLE
iOS app get crashed when accessed from apple watch app

### ISSUE THREAD

**Issue by narendermyname** [forcedotcom/SalesforceMobileSDK-iOS#1219]
I have native iOS app and watch app.
I logged in with salesforce credential in my app then i access same app from apple watch app every thing  works fine but some times my iOS app get crashes below is log.

Oct 27 10:46:24 Tej-Pals-iPhone securityd[94] <Error>:  s3dl_query_row decode genp,rowid=239 failed (-25308): Error Domain=NSOSStatusErrorDomain Code=-25308 "ks_crypt: e00002e2 failed to 'od' item (class 9, bag: 0) Access to item attempted while keychain is locked." UserInfo={NSDescription=ks_crypt: e00002e2 failed to 'od' item (class 9, bag: 0) Access to item attempted while keychain is locked.}
Oct 27 10:46:24 Tej-Pals-iPhone securityd[94] <Error>:  securityd_xpc_dictionary_handler REFEDGE[954] copy_matching Error Domain=NSOSStatusErrorDomain Code=-25308 "ks_crypt: e00002e2 failed to 'od' item (class 9, bag: 0) Access to item attempted while keychain is locked." UserInfo={NSDescription=ks_crypt: e00002e2 failed to 'od' item (class 9, bag: 0) Access to item attempted while keychain is locked.}
Oct 27 10:46:24 Tej-Pals-iPhone REFEDGE[954] <Error>:  SecOSStatusWith error:[-25308] Error Domain=NSOSStatusErrorDomain Code=-25308 "ks_crypt: e00002e2 failed to 'od' item (class 9, bag: 0) Access to item attempted while keychain is locked." UserInfo={NSDescription=ks_crypt: e00002e2 failed to 'od' item (class 9, bag: 0) Access to item attempted while keychain is locked.}
Oct 27 10:46:24 Tej-Pals-iPhone securityd[94] <Error>:  s3dl_query_row decode genp,rowid=239 failed (-25308): Error Domain=NSOSStatusErrorDomain Code=-25308 "ks_crypt: e00002e2 failed to 'od' item (class 9, bag: 0) Access to item attempted while keychain is locked." UserInfo={NSDescription=ks_crypt: e00002e2 failed to 'od' item (class 9, bag: 0) Access to item attempted while keychain is locked.}
Oct 27 10:46:24 Tej-Pals-iPhone securityd[94] <Error>:  securityd_xpc_dictionary_handler REFEDGE[954] copy_matching Error Domain=NSOSStatusErrorDomain Code=-25308 "ks_crypt: e00002e2 failed to 'od' item (class 9, bag: 0) Access to item attempted while keychain is locked." UserInfo={NSDescription=ks_crypt: e00002e2 failed to 'od' item (class 9, bag: 0) Access to item attempted while keychain is locked.}
Oct 27 10:46:24 Tej-Pals-iPhone REFEDGE[954] <Error>:  SecOSStatusWith error:[-25308] Error Domain=NSOSStatusErrorDomain Code=-25308 "ks_crypt: e00002e2 failed to 'od' item (class 9, bag: 0) Access to item attempted while keychain is locked." UserInfo={NSDescription=ks_crypt: e00002e2 failed to 'od' item (class 9, bag: 0) Access to item attempted while keychain is locked.}
Oct 27 10:46:24 Tej-Pals-iPhone securityd[94] <Critical>:  SecDbKeychainItemCopyEncryptedData ks_encrypt_data (db): failed: Error Domain=NSOSStatusErrorDomain Code=-25308 "ks_crypt: e00002e2 failed to 'oe' item (class 9, bag: 0) Access to item attempted while keychain is locked." UserInfo={NSDescription=ks_crypt: e00002e2 failed to 'oe' item (class 9, bag: 0) Access to item attempted while keychain is locked.}
Oct 27 10:46:24 Tej-Pals-iPhone securityd[94] <Error>:  securityd_xpc_dictionary_handler REFEDGE[954] add Error Domain=NSOSStatusErrorDomain Code=-25308 "ks_crypt: e00002e2 failed to 'oe' item (class 9, bag: 0) Access to item attempted while keychain is locked." UserInfo={NSDescription=ks_crypt: e00002e2 failed to 'oe' item (class 9, bag: 0) Access to item attempted while keychain is locked.}
Oct 27 10:46:24 Tej-Pals-iPhone REFEDGE[954] <Error>:  SecOSStatusWith error:[-25308] Error Domain=NSOSStatusErrorDomain Code=-25308 "ks_crypt: e00002e2 failed to 'oe' item (class 9, bag: 0) Access to item attempted while keychain is locked." UserInfo={NSDescription=ks_crypt: e00002e2 failed to 'oe' item (class 9, bag: 0) Access to item attempted while keychain is locked.}
Oct 27 10:46:24 Tej-Pals-iPhone REFEDGE[954] <Error>: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: v_Data)'
	*** First throw call stack:
	(0x183e18f48 0x1988dbf80 0x183d044e0 0x10013c014 0x10013c950 0x10019c42c 0x10019a188 0x100199d78 0x1988dcfc8 0x1988e38f8 0x1988eddb8 0x1001b984c 0x1001b789c 0x1000dc378 0x189421324 0x18964facc 0x189653e0c 0x189650f50 0x18dc377c4 0x18dc37b44 0x183dd0544 0x183dcffd8 0x183dcdcd8 0x183cfcca0 0x18941a1c8 0x189414ffc 0x1000db1d0 0x19912a8b8)
Oct 27 10:46:24 Tej-Pals-iPhone SpringBoard[57] <Warning>: BSXPCMessage received error for message: Connection invalid
Oct 27 10:46:24 Tej-Pals-iPhone SpringBoard[57] <Warning>: HW kbd: Failed to set (null) as keyboard focus
Oct 27 10:46:24 Tej-Pals-iPhone SpringBoard[57] <Warning>: UNNotificationRegistrarConnectionListener connection invalidated
Oct 27 10:46:24 Tej-Pals-iPhone diagnosticd[85] <Error>: error evaluating process info - pid: 954, puniqueid: 954
Oct 27 10:46:24 Tej-Pals-iPhone com.apple.xpc.launchd[1] (UIKitApplication:com.pointofreference.REFEDGE[0xb8c8][954]) <Notice>: Service exited due to signal: Abort trap: 6
Oct 27 10:46:25 Tej-Pals-iPhone ReportCrash[955] <Notice>: Formulating report for corpse[954] REFEDGE
Oct 27 10:46:25 Tej-Pals-iPhone ReportCrash[955] <Warning>: saved type '109_REFEDGE' report (1 of max 25) as /var/mobile/Library/Logs/CrashReporter/REFEDGE_2015-10-27-104624_Tej-Pals-iPhone.ips
Oct 27 10:46:25 Tej-Pals-iPhone SpringBoard[57] <Warning>: Application 'UIKitApplication:com.pointofreference.REFEDGE[0xb8c8]' crashed.
Oct 27 10:46:25 Tej-Pals-iPhone assertiond[69] <Error>: assertion failed: 13B143: assertiond + 56388 [758324CA-52B5-382E-92E7-A885A3A90E65]: 0x3
Oct 27 10:46:25 Tej-Pals-iPhone Unknown[69] <Error>: 
Oct 27 10:46:25 Tej-Pals-iPhone UserEventAgent[23] <Warning>: 1244013251825: id=com.pointofreference.REFEDGE pid=954, state=0
Oct 27 10:46:25 Tej-Pals-iPhone assertiond[69] <Error>: assertion failed: 13B143: assertiond + 56388 [758324CA-52B5-382E-92E7-A885A3A90E65]: 0x3
Oct 27 10:46:25 Tej-Pals-iPhone Unknown[69] <Error>: 
Oct 27 10:46:48 Tej-Pals-iPhone CommCenter[81] <Notice>: Snapshot path [/var/wireless/Library/Logs/CrashReporter/Baseband/] was removed
Oct 27 10:46:48 Tej-Pals-iPhone crash_mover[956] <Notice>: (Warn ) <crash_mover.m nps_countProfiles:278> no profiles detected
Oct 27 10:47:53 Tej-Pals-iPhone syncdefaultsd[957] <Notice>: (Note ) SYDAlwaysOnAccount: no account (null)
Oct 27 10:47:53 Tej-Pals-iPhone syncdefaultsd[957] <Notice>: (Note ) SYDAccount: no account
Oct 27 10:47:53 Tej-Pals-iPhone syncdefaultsd[957] <Notice>: (Note ) SYDPIMAccount: no account (null)
Oct 27 10:48:28 Tej-Pals-iPhone backboardd[61] <Notice>: [HID] [MT] MTSimpleHIDManager::setPropertyInternal detection mode: 255->6 (deferring until bootloaded)
Oct 27 10:48:28 Tej-Pals-iPhone sharingd[65] <Notice>: 10:48:28.160 : Tethering: Identifier needs fixing
Oct 27 10:48:28 Tej-Pals-iPhone SpringBoard[57] <Warning>: [MPUSystemMediaControls] Enabling lock screen media controls updates for screen turning on.
Oct 27 10:48:28 Tej-Pals-iPhone SpringBoard[57] <Warning>: [MPUSystemMediaControls] Updating supported commands for now playing application.
Oct 27 10:48:28 Tej-Pals-iPhone backboardd[61] <Notice>: [HID] [MT] MTSimpleHIDManager::deviceDidBootload device bootloaded
Oct 27 10:48:28 Tej-Pals-iPhone backboardd[61] <Notice>: [HID] [MT] MTSimpleHIDManager::setPropertyInternal detection mode: 6->6 
Oct 27 10:48:28 Tej-Pals-iPhone SpringBoard[57] <Notice>: -[UABestAppSuggestionManager notifyBestAppChanged:type:options:bundleIdentifier:activityType:dynamicIdentifier:when:confidence:deviceName:deviceIdentifier:deviceType:] (null) UASuggestedActionType=0 (null)/(null) opts=(null) when=2015-10-27 05:18:28 +0000 confidence=1 from=(null)/(null) (UABestAppSuggestionManager.m #319)
Oct 27 10:48:31 Tej-Pals-iPhone kernel[0] <Notice>: AppleKeyStore: operation failed (pid: 57 sel: 26 ret: e00002e2 '-536870174')
Oct 27 10:48:31 Tej-Pals-iPhone kernel[0] <Notice>: AppleKeyStore:Sending lock change 0 for handle 0
Oct 27 10:48:31 Tej-Pals-iPhone UserEventAgent[23] <Error>:  LockStateNotifier aksNotificationCallback posting notification: com.apple.mobile.keybagd.lock_status
Oct 27 10:48:31 Tej-Pals-iPhone UserEventAgent[23] <Notice>: (Note ) PIH: Lock status changed.
Oct 27 10:48:31 Tej-Pals-iPhone backboardd[61] <Notice>: [HID] [MT] MTSimpleHIDManager::setPropertyInternal detection mode: 6->3 
Oct 27 10:48:31 Tej-Pals-iPhone MobileMail[174] <Warning>: Key bag transitioning from locked to unlocked
Oct 27 10:48:32 Tej-Pals-iPhone locationd[66] <Warning>: notify name "com.apple.locationd.DumpDiagnostics" has been registered 40 times - this may be a leak
Oct 27 10:48:33 Tej-Pals-iPhone searchd[157] <Warning>: ====^^^^ DuetExpert missing data, count -> people:0 applicationDeepLinks:0 applications:8 requests:22 missingAllDataRequests:0
Oct 27 10:49:34 Tej-Pals-iPhone SpringBoard[57] <Warning>: [MPUSystemMediaControls] Disabling lock screen media controls updates for screen turning off.
Oct 27 10:49:34 Tej-Pals-iPhone backboardd[61] <Notice>: [HID] [MT] MTSimpleHIDManager::setPropertyInternal detection mode: 3->255 
Oct 27 10:49:34 Tej-Pals-iPhone kernel[0] <Notice>: AppleKeyStore: operation failed (pid: 57 sel: 26 ret: e00002e2 '-536870174')
Oct 27 10:49:34 Tej-Pals-iPhone UserEventAgent[23] <Error>:  LockStateNotifier aksNotificationCallback posting notification: com.apple.mobile.keybagd.lock_status
Oct 27 10:49:34 Tej-Pals-iPhone MobileMail[174] <Warning>: Key bag transitioning from unlocked to locking
Oct 27 10:49:34 Tej-Pals-iPhone UserEventAgent[23] <Notice>: (Note ) PIH: Lock status changed.
Oct 27 10:49:34 Tej-Pals-iPhone SpringBoard[57] <Warning>: [MPUSystemMediaControls] Updating supported commands for now playing application.
Oct 27 10:49:44 Tej-Pals-iPhone kernel[0] <Notice>: AppleKeyStore:Sending lock change 1 for handle 0
Oct 27 10:49:44 Tej-Pals-iPhone UserEventAgent[23] <Error>:  LockStateNotifier aksNotificationCallback posting notification: 

and one more thing some time my app gets logout  this can be after some hours or i killed app manual multiple time.
So, I want to make my app like salesforce1 means when i logging first it never logged out.

**Comment by bhariharan** [comment]
We have fixed the keychain permissions in our ```unstable``` branch. Feel free to reopen this issue if you still see it after upgrading to ```unstable```.
