### ISSUE TITLE
No callback to app after Reset password.

### ISSUE THREAD

**Issue by vishnu-sharma** [forcedotcom/SalesforceMobileSDK-iOS#1220]
I am using 3.3 iOS SDK. If user click on "Forgot your password?" link on the OAuth Login page, user is taken to a page where user can provide his email ID. On providing email id and submitting. A Informative page is displayed saying "Check your email". 
The issue is user have no option to come back to login screen from this point until he manually kill the iOS app and restart it.(Normally this is not expected.)  @khawkins  do you have any comments on this ?
![ios simulator screen shot oct 28 2015 7 27 41 pm](https://cloud.githubusercontent.com/assets/1821913/10790737/0bc7e9a6-7dab-11e5-9f26-d099a9820405.png)
![ios simulator screen shot oct 28 2015 7 27 58 pm](https://cloud.githubusercontent.com/assets/1821913/10790750/15611596-7dab-11e5-9c07-0f0965f153b9.png)

**Comment by bhariharan** [comment]
@vishnu-sharma Unfortunately, we don't control that page - we only display the standard mobile ```Salesforce``` authentication page within a ```UIWebView```.

**Comment by vishnu-sharma** [comment]
@bhariharan It means, I should log case in SFDC support for this behavior ?

**Comment by vishnu-sharma** [comment]
@bhariharan  This issue is accepted as bug by salesforce and they would be fixing this in upcoming build of salesforce-one. I don't know how we are going to update mobile SDK.
