### ISSUE TITLE
API endpoint retiring Jan 01

### ISSUE THREAD

**Issue by brad36** [forcedotcom/SalesforceMobileSDK-iOS#1221]
I received an email saying

"What is changing?
Currently, customers can use www.salesforce.com as an API endpoint that will route them to the correct instance. As of January 1, 2016, the internal routing will be retired, and any API endpoints will need to be changed if from www.salesforce.com to https://login.salesforce.com. 

Note: This only applies to API traffic; logging in from a browser by clicking “login” will still work. "

Am I correct in assuming that this change will not affect the Mobile SDK on iOS?

**Comment by carlcarter** [comment]
I believe thats correct however you do have the ability to override the initial endpoint using the key 'SFDCOAuthLoginHost' within your plist file.  If thats set to login.salesforce.com you should be ok 

(caveat - I don't work for SF)

**Comment by khawkins** [comment]
In the default case (i.e. barring explicit override behavior by the developer), the Mobile SDK does not use redirect/routing logic to form API requests.  API requests are made directly against the instance here the user is authenticated.  So you are correct: this should not impact Mobile SDK apps.

**Comment by khawkins** [comment]
Feel free to re-open if you have further questions.

**Comment by brad36** [comment]
ok, thank you both !
