### ISSUE TITLE
Community user can not edit or update record from mobile app using SalesforceMobileSDK-iOS.

### ISSUE THREAD

**Issue by vishnu-sharma** [forcedotcom/SalesforceMobileSDK-iOS#1225]
Configuring My Org to have community and connected app -
* Created a community in my org.
* Created a connected app.
* Cloned "Customer Community User" profile and enabled "API Enabled" named this profile as "Cloned Customer Community User Plus API Enabled"
* Than I added "Cloned Customer Community User Plus API Enabled" profile in connected app as a member.

Configuring mobile app -
Configured sample app available with SalesforceMobileSDK-iOS "RestAPIExplorer" iOS app to be able to access my org, this steps involves 
 * Adding my "RemoteAccessConsumerKey","OAuthRedirectURI" and adding "SFDCOAuthLoginHost" entry in iOS app.

Community user is able to login from mobile app, he is also able to fetch data but as I try to hit patch request or post request, I get error thrown by SDK. I believe that community user don't have access to updating data. Looks like its a bug. Can anybody confirm this ?

**Comment by bhariharan** [comment]
What is the error you're getting back, and what's the HTTP status of the response?
