### ISSUE TITLE
PIN security issue while switching orgs without killing the application

### ISSUE THREAD

**Issue by harshalijain** [forcedotcom/SalesforceMobileSDK-iOS#1230]
A user logs into a Production org where PIN security is enabled, creates a new PIN, and logs into the application. Then user switches to Sandbox org where also PIN security is enabled, and goes back to application, the Login screen appears for Sandbox . User enters credentials to login into Sandbox, but the PIN security screen is skipped, i.e. user is not able to set a new PIN for a new session on a different org.
Furthermore, if at this point, the user kills and restarts the app, PIN screen comes up, asking for the PIN  user created initially on Production org.

**Comment by bhariharan** [comment]
This is completely by design. The app has a single master passcode/PIN, irrespective of how many orgs the user logs in to. We choose the strictest PIN policy of all the orgs that the user is logged in to.
