### ISSUE TITLE
Reusing ACCESS_TOKEN in other places

### ISSUE THREAD

**Issue by nekonari** [forcedotcom/SalesforceMobileSDK-iOS#1235]
I may be in a wrong place to ask this, but can we reuse the `access_token` we get back when we launch the Salesforce SDK manager, to retrieve data from Salesforce REST API?

**Comment by bhariharan** [comment]
@nekonari Please post your questions on our [Google+ community](https://plus.google.com/u/1/communities/114225252149514546445?cfem=1).
