### ISSUE TITLE
Salesforce IOS app refresh token expired but app not shows login screen

### ISSUE THREAD

**Issue by narendermyname** [forcedotcom/SalesforceMobileSDK-iOS#1250]
I am using forces 3.3.1 version.
If we access any api using SFRestAPI shows below error.

Error Domain=com.salesforce.OAuth.ErrorDomain Code=672 "expired access/refresh token" UserInfo={error=invalid_grant, NSLocalizedDescription=expired access/refresh token}

this was working in earlier forces version.

**Comment by bhariharan** [comment]
@narendermyname As the error message says, your refresh token is invalid/has been revoked. You'll need to login again. This forum is reserved for known bugs/issues in ```Mobile SDK```. For other questions/discussions, please use our [Google+ Community](https://plus.google.com/communities/114225252149514546445).
