### ISSUE TITLE
Remove NSNotification Observers in dealloc()

### ISSUE THREAD

**Issue by Michaelcaulley** [forcedotcom/SalesforceMobileSDK-iOS#1257]
Should the registered nsnotifcations be unregistered in a dealloc function? I recently saw a 

EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000010 error 
at
SalesforceSDKManager.m line 407
-[SalesforceSDKManager handleAppWillResignActive:]

**Comment by wmathurin** [comment]
Fixed here https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1388
