### ISSUE TITLE
Podspec should pass lint in master branch

### ISSUE THREAD

**Issue by mgetzbw** [forcedotcom/SalesforceMobileSDK-iOS#1275]
The podspec should pass the following command in the stable branch:

    pod lib lint SalesforceMobileSDK-iOS.podspec 

Actual result:

* lint fails

Expected result:

* lint passes

Errors
==========
 >  -> SalesforceMobileSDK-iOS (3.3.1)
    - ERROR | [SalesforceMobileSDK-iOS/SalesforceSecurity, SalesforceMobileSDK-iOS/SalesforceOAuth, SalesforceMobileSDK-iOS/SalesforceSDKCore, and more...] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:24035:13: warning: ambiguous expansion of macro 'MAX' [-Wambiguous-macro]
    - NOTE  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.1.sdk/usr/include/sys/param.h:218:9: note: expanding this definition of 'MAX'
    - NOTE  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:8330:9: note: other definition of 'MAX'
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:24036:43: warning: ambiguous expansion of macro 'MAX' [-Wambiguous-macro]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:28429:14: warning: implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:30140:42: warning: implicit conversion loses integer precision: 'unsigned long long' to 'int' [-Wshorten-64-to-32]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:30303:11: warning: implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:30415:10: warning: implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:31556:33: warning: implicit conversion loses integer precision: 'long long' to 'int' [-Wshorten-64-to-32]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:33222:17: warning: implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:33531:11: warning: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Wshorten-64-to-32]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:33539:11: warning: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Wshorten-64-to-32]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:33831:19: warning: implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:33992:37: warning: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Wshorten-64-to-32]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:34206:53: warning: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Wshorten-64-to-32]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:62371:21: warning: ambiguous expansion of macro 'MIN' [-Wambiguous-macro]
    - NOTE  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.1.sdk/usr/include/sys/param.h:215:9: note: expanding this definition of 'MIN'
    - NOTE  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:8329:9: note: other definition of 'MIN'
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:62660:18: warning: ambiguous expansion of macro 'MIN' [-Wambiguous-macro]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:67716:22: warning: ambiguous expansion of macro 'MIN' [-Wambiguous-macro]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:67736:22: warning: ambiguous expansion of macro 'MIN' [-Wambiguous-macro]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:67909:12: warning: ambiguous expansion of macro 'MIN' [-Wambiguous-macro]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:78172:17: warning: ambiguous expansion of macro 'MIN' [-Wambiguous-macro]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:78206:18: warning: ambiguous expansion of macro 'MIN' [-Wambiguous-macro]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:85981:18: warning: ambiguous expansion of macro 'MAX' [-Wambiguous-macro]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:86012:18: warning: ambiguous expansion of macro 'MAX' [-Wambiguous-macro]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:86075:20: warning: ambiguous expansion of macro 'MAX' [-Wambiguous-macro]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:101589:22: warning: ambiguous expansion of macro 'MAX' [-Wambiguous-macro]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:101626:24: warning: ambiguous expansion of macro 'MAX' [-Wambiguous-macro]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:114074:39: warning: code will never be executed [-Wunreachable-code]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:114021:39: warning: code will never be executed [-Wunreachable-code]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:117262:19: warning: ambiguous expansion of macro 'MIN' [-Wambiguous-macro]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:138596:11: warning: ambiguous expansion of macro 'MIN' [-Wambiguous-macro]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:141250:14: warning: ambiguous expansion of macro 'MIN' [-Wambiguous-macro]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:141381:37: warning: ambiguous expansion of macro 'MAX' [-Wambiguous-macro]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:141403:43: warning: ambiguous expansion of macro 'MAX' [-Wambiguous-macro]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:8445:26: warning: unused variable 'sqlite3one' [-Wunused-const-variable]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:55832:20: warning: unused function 'sqlite3BtreeSetMmapLimit' [-Wunused-function]
    - WARN  | [SalesforceMobileSDK-iOS/SalesforceSDKCore, SalesforceMobileSDK-iOS/SalesforceNetwork, SalesforceMobileSDK-iOS/SalesforceRestAPI, and more...] xcodebuild:  SQLCipher/sqlite3.c:49687:20: warning: unused function 'sqlite3PagerState' [-Wunused-function]
    - NOTE  | [SalesforceMobileSDK-iOS/SalesforceSecurity, SalesforceMobileSDK-iOS/SalesforceOAuth, SalesforceMobileSDK-iOS/SalesforceSDKCore, and more...] xcodebuild:  Target Support Files/SalesforceMobileSDK-iOS/SalesforceMobileSDK-iOS-prefix.pch:5:9: fatal error: 'SalesforceCommonUtils/SFLogger.h' file not found

**Comment by wmathurin** [comment]
In 4.0.2 (just released), we decided to have a podspec per module and instead of publishing them to cocoapods.org, we have our own specs repo.
As a result, your podfile should look something like:

```
target 'YourApp' do

source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git' # need to be first 
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
pod 'SalesforceSDKCore'
pod 'SalesforceNetwork'
pod 'SalesforceRestAPI'
pod 'FMDB'
pod 'SmartStore'
pod 'SmartSync'


end
```
