### ISSUE TITLE
Each Pod Subspec should be its own pod

### ISSUE THREAD

**Issue by mgetzbw** [forcedotcom/SalesforceMobileSDK-iOS#1276]
This is to support modularizing the framework and supporting swift appropriately. Right now including the SDK in a Podfile results in all subspecs being pulled in even when they are not wanted.

**Comment by khawkins** [comment]
If you want to limit the SDK code that gets included in your project, configure your `Podfile` to install the subspec(s) that you want access to.  The dependencies are set up such that you'll only get the code you need.  For example:

`pod 'SalesforceMobileSDK-iOS/SalesforceRestAPI'`

I'm going to close this out, but feel free to comment if it's unclear.

**Comment by mgetzbw** [comment]
Tried that sadly they have undeclared interdependencies

On Tuesday, December 8, 2015, Kevin Hawkins <notifications@github.com>
wrote:

> If you want to limit the SDK code that gets included in your project,
> configure your Podfile to install the subspec(s) that you want access to.
> The dependencies are set up such that you'll only get the code you need.
> For example:
>
> pod 'SalesforceMobileSDK-iOS/SalesforceRestAPI'
>
> I'm going to close this out, but feel free to comment if it's unclear.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1276#issuecomment-163045108>
> .
>


-- 

------------------------------

*Michael Getz <http://www.bluewolf.com/people/michael-getz>* ─ Developer II
─ Bluewolf ─ O: 720 263 2988

→ Download Bluewolf’s Annual The State of Salesforce Report
<http://bit.ly/Zsb1xZ>
