### ISSUE TITLE
Crash: SFKeyStore.m line 32 -[SFKeyStore keyStoreDictionary]

### ISSUE THREAD

**Issue by dautovicharis** [forcedotcom/SalesforceMobileSDK-iOS#1277]
Used SalesForce SDK: SalesforceMobileSDK-iOS (3.3.1)
Device: iPhone 6
iOS: 9.1.0 (13B143)
JAILBREAK: NO
Environment: Production

Crash log:
[Crash.txt](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/55972/Crash.txt)

**Comment by huminzhi** [comment]
Hi, @dautovicharis , do you mind upgrading to latest SDK version and do you still see this crash?
