### ISSUE TITLE
BitCode Not enabled on Push plugin & Unable to build Hybrid app with MobileSDK.

### ISSUE THREAD

**Issue by hari8815** [forcedotcom/SalesforceMobileSDK-iOS#1308]
I have created iOS Hybrid app with latest MobileSDK 4.0.  During run time I am getting following error message regarding BitCode enablement in push plugin.

'/MobileSdk/sfios/platforms/ios/sfios/Plugins/phonegap-plugin-push/GCM/Libraries/libGGLCloudMessaging.a(GGLContext+CloudMessaging.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

When I search for this issue, I got following link: 
https://github.com/google/gcm/issues/91

It seems the cordova push plugin for ios added GCM service and those libraries not enabled BitCode.
As we know our SF MobileSDK depends on the push plugin. How we create a runnable app? Any alternate solution for this issue?

**Comment by bhariharan** [comment]
@hari8815 Have you tried disabling bitcode in your project settings in ```Xcode```?

**Comment by hari8815** [comment]
@bhariharan If I am disabling bitcode, I am getting "CFNetwork SSLHandshake failed" error, Unable to see oAuth screen. I have found solution regarding SSL issue in ios9 "http://stackoverflow.com/questions/30720813/cfnetwork-sslhandshake-failed-ios-9/30720929#30720929". In my app Info.plist configuration, I have removed NSExceptionDomains - salesforce.com,force.com xml nodes and kept NSAppTransportSecurity , NSAllowsArbitraryLoads> true xml node alone.
Now I am able to successfully build and run app in ipad. Is this approach correct? Does this produce any security conflicts?

**Comment by wmathurin** [comment]
Please have a look at tip #1 here:
https://rwhitleysfdc.wordpress.com/2015/09/29/tips-for-upgrading-mobile-sdk-apps-for-ios-9/

**Comment by hari8815** [comment]
@wmathurin @bhariharan  https://rwhitleysfdc.wordpress.com/2015/09/29/tips-for-upgrading-mobile-sdk-apps-for-ios-9/  tip #1 resolves the ssl issue. My question is: why this changes not included in Hybrid app, which is created with latest mobile sdk?  We successfully released a hybrid mobile app(with SDK v3.0.1) on the iOS store. Now we are creating new version with latest SDK. So info.plist modification affects app submission? or we need to wait for another version of SDK?

**Comment by bhariharan** [comment]
@hari8815 It looks like the push plugin we depend on does not have bitcode enabled. The rest of the Mobile SDK has bitcode enabled. Once the plugin is updated to support bitcode, everything should work fine.
