### ISSUE TITLE
DB encryption issue

### ISSUE THREAD

**Issue by McFlyssss** [forcedotcom/SalesforceMobileSDK-iOS#1309]
Hello guys,

Recently I moved to Salesforce V4 version. I created a new project from your template and I moved my current code there.

I have a db seed in the app that I encrypt after the app runs for the first time. What I do is place the seed in the proper folder and encrypt the file calling <code>[SFSmartStoreUpgrade updateEncryption];</code>

Since I moved to version 4 when I call this method the db can not be encrypted. Digging a bit in the source code I found out that in this method:

<code>
 (FMDatabase *)encryptOrUnencryptDb:(FMDatabase *)db
                                name:(NSString *)storeName
                                path:(NSString *)storePath
                              oldKey:(NSString *)oldKey
                              newKey:(NSString *)newKey
                               error:(NSError **)error
</code>

when calling 

<code>
FMResultSet *rs = [db executeQuery:@"SELECT sqlcipher_export('encrypted')"];
</code>

even if rs != nil if you log <code> [db lastErrorMessage]</code> you will see there is an unknown error there. 

The app doesn't log that error and the encryption is not performed.

Do you guys know how to make the encryption work again?

Thanks in advance,

Albert

**Comment by khawkins** [comment]
How are you consuming the Mobile SDK in your app?  Do you use forceios, a direct CocoaPods install, or something else?

**Comment by McFlyssss** [comment]
I used forceios this time. This is how SQLCipher looks after the installation. Maybe something is missing?

![screen shot 2015-12-28 at 19 17 09](https://cloud.githubusercontent.com/assets/5735738/12023223/9c5c2272-ad97-11e5-9347-b78d0bb91126.png)

Cheers

**Comment by khawkins** [comment]
@McFlyssss I'm pretty sure you're hitting an issue with our CocoaPods rollout, described [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1261/files#r48303685).  We're looking at the best solution to the issue, which we'll either submit as a patch or an update for the next point release.

In the meantime, can you try the following and verify whether or not it fixes your issue?

1. In your app workspace, click on the Pods project in Project Navigator.
2. Select the FMDB target.
3. In the Build Settings tab, find the "Other C Flags" setting.
4. Add `-DSQLITE_HAS_CODEC` to the (presumably at this point) empty list of options.
5. Delete any previous app instance from your device and/or simulator.
6. Run your app again.

This seemed to clear up encryption issues in my environment, as a workaround.

**Comment by McFlyssss** [comment]
@khawkins the workaround worked for me!

Thanks!

**Comment by khawkins** [comment]
Great!  I'll leave this open to track the more permanent fix to come.

**Comment by bhariharan** [comment]
This is fixed in ```Mobile SDK 4.0.2```.
