### ISSUE TITLE
SDK 4.0.0 login incompatibility issue

### ISSUE THREAD

**Issue by pbenschop** [forcedotcom/SalesforceMobileSDK-iOS#1310]
<img width="327" alt="screen shot 2015-12-28 at 3 30 47 pm" src="https://cloud.githubusercontent.com/assets/2353981/12040248/3b315064-ae1c-11e5-8888-ea3644496f81.png">
If you run the stock SDK AccountEditor sample app and login with SDK 3.3.1, then terminate, switch to SDK 4.0.0, and start its version of this sample app, you get an SSL error reported (tapping retry will just repeat the scenario). See attached screenshot. The reason is that SDK 4.0.0 creates a new UUID to use a name for the subfolder in Data/Application:

/Users/peter/Library/Developer/CoreSimulator/Devices/9B906BA7-53D4-4C80-A0C1-7F6D069B52DF/data/Containers/Data/Application/17A1CE38-C2DA-4E8E-81A3-0F65BC9DCE69/Library/com.salesforce.mobilesdk.AccountEditor/00DA0000000KItSMAW/005A0000004GGqX/UserAccount.plist

As a result the existing user credentials are not found. In our app this SDK 4.0.0 behavior results in an app crash when calling getAuthCredentials in com.salesforce.plugin.oauth.js

---- Session.authorize calling Session.oauth.getAuthCredentials
*** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]

Detailed reproduction scenario:

Every time there is new Salesforce SDK release I rename the old folder and do a “fresh” git clone https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git. This way I can easily switch back and forth between the old and the new SDK release. 

- Load the Xcode workspace from my SalesforceMobileSDK-iOS-3.3.1 folder
- Select AccountEditor as the target
- Run the app on the simulator (iPhone 5 in this case) and login
- Terminate the app with xCode and exit xCode
- Load the Xcode workspace from SalesforceMobileSDK-iOS-4.0.0 folder
- Again select AccountEditor as the target
- Run the app on the simulator (iPhone 5 again)
- Observe SSL error message

If  I exit Xcode go back to the SalesforceMobileSDK-iOS-3.3.1 folder and run the AccountEditor app again, it automatically logs in as expected.

**Comment by hari8815** [comment]
Please follow tip#1 in the following url https://rwhitleysfdc.wordpress.com/2015/09/29/tips-for-upgrading-mobile-sdk-apps-for-ios-9/ It will resolve the SSL issue.

**Comment by pbenschop** [comment]
Thanks for pitching in, Hari, but I don't think these upgrade recommendations apply here. The SDK sample apps already contains the required ATS settings for iOS9, both in 3.3.1 and 4.0.0. The problem is related to the SDK 4.0.0 looking for user credentials in a different folder than where the SDK 3.3.1 was looking.

**Comment by khawkins** [comment]
Interesting.  I can't reproduce with Xcode 7.2.  I neither see the SSL error, nor a separate app bundle created for the simulator upon launching the app from the 4.0 repo.  Which version of Xcode are you running?

It sounds like, in your environment, two separate app bundles are being created in this scenario.  Normally I'd say that one won't otherwise affect the other, except for the fact that, in the simulators, the keychain is shared across apps, which generally causes some strange issues with multiple Mobile SDK apps running against the same simulator.  What happens if you run the same scenario, except against a device?

I'm not sure why you're getting two separate app bundles, when running against the vanilla Mobile SDK versions.  This should ultimately be driven by the Bundle ID, i.e. the `CFBundleIdentifier` value in Info.plist.  The formation of the bundle ID is slightly different between 3.3.1 and 4.0.0, but the end value is still the same: com.salesforce.mobilesdk.AccountEditor.  Is there any other reason that the value of the Bundle ID in your setup may be different?

**Comment by pbenschop** [comment]
Thanks, Kevin. I am also running the Xcode 7.2. In the 3.3.1 version of AccountEditor-Info.plist, the bundle identifier is set to ${BUNDLE_PREFIX}.${PRODUCT_NAME:rfc1034identifier} while in 4.0.0 this value is set to $(PRODUCT_BUNDLE_IDENTIFIER).  However, if change the 4.0.0 value of CFBundleIdentifier and set it to the 3.3.1, the result is the same i.e. same problem as described above. Also, in our own app, which exhibits the same problem, we did not change the bundle identifier.

This morning I tried running the same scenario on an iPad3 device but I am running into deployment problems (with any of the SDK 4.0.0 sample apps). I can deploy and run the 3.3.1 version of the sample apps just fine, but for the 4.0.0 I get the following error right at startup:

dyld: Library not loaded: @rpath/SalesforceHybridSDK.framework/SalesforceHybridSDK
  Referenced from: /var/mobile/Containers/Bundle/Application/613EF177-5629-4A8B-A1C8-9A27EF5397C8/AccountEditor.app/AccountEditor
  Reason: image not found

This happens with the stock SDK from Github without any modifications. I assume this is signing or certificate related but I have not been able to resolve it yet.

**Comment by khawkins** [comment]
Gah, I forgot about the issues running the samples on device in `master`—we've fixed that issue in `unstable`, and are considering back-porting it to the master branch.

The multiple bundles issue is perplexing.  Can we confirm that you're actually seeing two separate bundles on your simulator?  I.e. what does:

```
$ find /Users/peter/Library/Developer/CoreSimulator/Devices/9B906BA7-53D4-4C80-A0C1-7F6D069B52DF/data/Containers/Bundle/Application -name AccountEditor.app
```

turn up?

**Comment by pbenschop** [comment]
Just to be really sure I deleted all devices from the CoreSimulator directory and then reran my test, and then executed the find command:
```
Peters-MacBook-Pro-13:gvp peter$ find /Users/peter/Library/Developer/CoreSimulator/Devices/954A7C32-14CE-4BD0-AB87-86ECAD260A39/data/Containers/Bundle/Application -name AccountEditor.app

/Users/peter/Library/Developer/CoreSimulator/Devices/954A7C32-14CE-4BD0-AB87-86ECAD260A39/data/Containers/Bundle/Application/D8FA0998-D422-42DB-843E-F3E5506970BB/AccountEditor.app
```
Next, I put a breakpoint on the method loadUserAccountFromFile (SalesforceSDKCore/Classes/Security/SFUserAccountManager.m) to see what the filePath argument is in both cases:

SDK 3.3.1
```
/Users/peter/Library/Developer/CoreSimulator/Devices/954A7C32-14CE-4BD0-AB87-86ECAD260A39/data/Containers/Data/Application/23BF2BF3-8EA1-436A-A85C-65C972A4B841/Library/com.salesforce.mobilesdk.AccountEditor/00DA0000000KItSMAW/005A0000004GGqX/UserAccount.plist
```
SDK 4.0.0
```
/Users/peter/Library/Developer/CoreSimulator/Devices/954A7C32-14CE-4BD0-AB87-86ECAD260A39/data/Containers/Data/Application/644FDBFC-CCB2-41EB-9F6D-52C548BF86D5/Library/com.salesforce.mobilesdk.AccountEditor/00DA0000000KItSMAW/005A0000004GGqX/UserAccount.plist
```
As you can see, SDK 4.0.0 looks in a different subdirectory of the Application directory and of course, will not find the credentials. I also tried with the unstable branch, same result.

**Comment by khawkins** [comment]
Good to see that there's only one bundle for the app, anyway.  I don't really know why Xcode is creating different data containers; I've never seen that behavior before.  But there's nothing in the Mobile SDK that's influencing that location.  The location of those folders is completely abstracted from the Mobile SDK, and indeed from all iOS apps.  We're ultimately getting that root folder path from:
```obj-c
NSSearchPathForDirectoriesInDomains(NSLibraryDirectory, NSUserDomainMask, YES)
```
I wish I could offer a better answer, but I'm not really sure what that would be happening.
