### ISSUE TITLE
How to use SalesforceCommonUtils with 4.0

### ISSUE THREAD

**Issue by rajishere** [forcedotcom/SalesforceMobileSDK-iOS#1311]
We are running into multiple duplicate symbols issues when using libSalesforceCommonUtils.a alongside libSalesforceMobileSDK-iOS.a.

I need to use the SFDateUtil but don't find it in the new SDK.

Thank you,
Raj

**Comment by jeffreyjackson** [comment]
I'm looking for this also

**Comment by wmathurin** [comment]
We combined SalesforceCommon, SalesforceSecurity and SalesforceOAuth into SalesforceSDKCore for 4.0. Also we no open sourced the parts of libSalesforceCommonUtils.a that we used and brought them into SalesforceSDKCore as well. So the headers you were using from that library should now be part of SalesforceSDKCore.

**Comment by jeffreyjackson** [comment]
do you know where SFDateUtils is?  Im not seeing it in SalesforceSDKCore?

**Comment by bhariharan** [comment]
@jeffreyjackson We've taken away some classes that weren't directly used in the ```Mobile SDK```, hence those headers aren't available anymore.

**Comment by jeffreyjackson** [comment]
@bhariharan thanks for the update

**Comment by jeffreyjackson** [comment]
would you care to provide the source for these?  even just a gist would be great.  thanks for all your hard work on the SDK.

**Comment by rajishere** [comment]
@bhariharan I agree with @jeffreyjackson, we should look at adding support for SFDateUtil

**Comment by bhariharan** [comment]
We will consider adding it back in a future release.

**Comment by jeffreyjackson** [comment]
Hey guys, I attempted to recreate SFDateUtil [here](https://github.com/jeffreyjackson/SFDateUtil)

**Comment by rajishere** [comment]
Thank you @bhariharan

**Comment by huminzhi** [comment]
I am closing this issue if you are ok @rajishere , thank you!

**Comment by juliany** [comment]
Yes please add it to the core
