### ISSUE TITLE
SFRestDelegate

### ISSUE THREAD

**Issue by jeffreyjackson** [forcedotcom/SalesforceMobileSDK-iOS#1318]
Is this still available?

**Comment by wmathurin** [comment]
Yep it's there:
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceRestAPI/SalesforceRestAPI/Classes/SFRestRequest.h

**Comment by jeffreyjackson** [comment]
Is it not available via cocoapods install on version 4.0?
