### ISSUE TITLE
SFRestDelegate isn't available in 4.0 install with cocoapods

### ISSUE THREAD

**Issue by jeffreyjackson** [forcedotcom/SalesforceMobileSDK-iOS#1324]

**Comment by jeffreyjackson** [comment]
More specifically, I'm not seeing any reference to SalesforceRestAPI after cocoapods 4.0 install. @khawkins

**Comment by jeffreyjackson** [comment]
cc @wmathurin i know you closed the other github regarding this - but if you try a cocoapods install you'll notice the SalesforceRestAPI libs don't show up anywhere.

**Comment by wmathurin** [comment]
If you pod 'SalesforceMobileSDK-iOS', you only get SalesforceSDKCore. Before 4.0, you would get everything by default.
If you want other libraries you need to do something like:

pod 'SalesforceMobileSDK-iOS', :subspecs => [
    'SalesforceRestAPI'
]

**Comment by jeffreyjackson** [comment]
thank you
