### ISSUE TITLE
SDK 4.0: tableNameBySoupId in SFSmartStore.m throws error in ReactNative

### ISSUE THREAD

**Issue by rajaraodv** [forcedotcom/SalesforceMobileSDK-iOS#1329]
I am trying to run the reactnative demo app by running latest forceios (4.0.1). But when I open up the Xcode workspace, I get an **Expected a type** error in the following method. I am using **Xcode 7.2 (7C68)**
```
- (NSString *)tableNameBySoupId:(sqlite_int64)soupId {
```

### Steps to reproduce: 

1.  forceios create --apptype="react_native" --appname="RNTest" --companyid="com.test.salesforce" --organization="Salesforce" --packagename="com.test.mobileapps"
2. cd RNTest
3. pod install
4. open RNTest.xcworkspace
5. Run the app

<img width="910" alt="screen shot 2016-01-09 at 8 02 40 pm" src="https://cloud.githubusercontent.com/assets/626337/12219911/8c9d6d18-b70c-11e5-9688-da5c3c7d471e.png">

forceios version 4.0.1

**Comment by wmathurin** [comment]
Things regressed when SQLCipher released a new version which has deprecated some symbols.
We are working on a patch release which whould come out very soon.

**Comment by thajcak** [comment]
Probably already known, but this also occurs in native_swift projects.

**Comment by wmathurin** [comment]
Please upgrade to forceios 4.0.2 and both react native and native swift applications should build correctly.

**Comment by emily-jny** [comment]
Thanks @wmathurin I upgraded forceios 4.0.2 and update all pods, it works find now.

**Comment by rajaraodv** [comment]
Thanks

**Comment by VipulArvind** [comment]
Hi I am having this issue. My environment is slight different.

(1) I started with existing project
(2) I included the podfile and ran pod install to get Salesforce SDK with SmartSync
(3) I opened the workspace and I get this compilation error

My main difference is that I am not using forceios to create a project rather I am adding SDK to existing IOS Project.

Please help...

**Comment by wmathurin** [comment]
We are not publishing our spec to Cocoapods anymore. Instead, we maintain separate specs for each our of frameworks here. We will update our Specs repo every release.

For more information, please look at:
https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/ios_cocoapods.htm

**Comment by VipulArvind** [comment]
Ok. So what do i do to fix my issue?

**Comment by wmathurin** [comment]
Please read the link I just provided, it will show you how to setup your pod file properly.

**Comment by VipulArvind** [comment]
Thanks this solved the issue.
