### ISSUE TITLE
NSString ​* const kSOSLReservedCharacters = @"\\?&|!{}[]()^~*​:\"'+-"

### ISSUE THREAD

**Issue by jeffreyjackson** [forcedotcom/SalesforceMobileSDK-iOS#1330]
We have records in our Contacts with names that contain hyphens.  Whenever we try and sanitize our search query it fails essentially saying the query is malformed.  Do we need to escape our user's input in addition to sanitizing?  For example, the user can search for

```
El-Guapo
```

If we only sanitize using ```(NSString *) sanitizeSOSLSearchTerm:(NSString *)searchTerm``` then we get back:

```
El\-Guapo
``` 

This breaks the query.  Do we have another option to ensure we can add ```-``` to our search query?

**Comment by jeffreyjackson** [comment]
Thanks for following up on this @bhariharan

**Comment by jeffreyjackson** [comment]
any ideas on a quick fix for this?

**Comment by bhariharan** [comment]
@jeffreyjackson Not at this time. Unfortunately I haven't had a chance to take a look at this.

**Comment by wmathurin** [comment]
I created a contact called Hyphen-name
I tried the following and got the MALFORMED_SEARCH error (as expected).
```
search = @"FIND {Hyphen-Name} IN NAME FIELDS LIMIT 1";
request = [[SFRestAPI sharedInstance] requestForSearch:search];
[[SFRestAPI sharedInstance] send:request delegate:self];
```
Then I tried, the following and I got the contact back.
```
search = [SFRestAPI SOSLSearchWithSearchTerm:@"Hyphen-Name" fieldScope:nil objectScope:nil limit:1];
// search should now be @"FIND {Hyphen\\-Name} IN NAME FIELDS LIMIT 1"
request = [[SFRestAPI sharedInstance] requestForSearch:search];
```

What are you doing differently?

**Comment by jeffreyjackson** [comment]
I'm performing a SFRestRequest with something similar to the following:

`NSString *sanitizedSearchString = [SFRestAPI sanitizeSOSLSearchTerm:contactSearchString];` where contactSearchString is something like _el-aneed_

then I'm performing a query similar to the following (note: all other special characters seem to escape correctly)
```
NSString *whereClause = [NSString stringWithFormat:@"Name LIKE '%%%@%%''", sanitizedSearchString];

NSString *soqlQuery = [NSString stringWithFormat:@"SELECT %@ FROM Contact WHERE %@ ORDER BY LastName, FirstName", ContactFieldList, whereClause];

request = [SFRestRequest requestWithMethod:SFRestMethodGET path:@"" queryParams:@{@"q":soqlQuery}];
```

**Comment by wmathurin** [comment]
Why are you calling sanitizeSOSLSearchTerm when doing a SOQL query?
There is no need to escape - when doing a SOQL query.

**Comment by brad36** [comment]
Sanitization is there to prevent SOQL injection attack. How to prevent it otherwise?

**Comment by jeffreyjackson** [comment]
@wmathurin please see this from the Mobile Development SDK Guide

https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/ios_rest_apis_SFRestAPI_QueryBuilder.htm

Specifically the very bottom section.

**Comment by wmathurin** [comment]
The problem is that you are using soSl sanitizer for a soQl query.

**Comment by brad36** [comment]
Does the SDK provide a way to sanitize SOQL queries?

**Comment by brad36** [comment]
It seems you are saying SOSL is not appropriate here. However I can't find any SOQL method either. You are aware that the absence of a SOQL sanitization method in the SDK will encourage developers to neglect countering SOQL injection, and thereby put end users' data at risk, right?

**Comment by brad36** [comment]
What is the SF recommended approach for sanitizing SOQL, given the special-character limitations presented by the issue in this thread?

**Comment by wmathurin** [comment]
For SOQL, all you need to do is add the escape character (\) to all single
quotation marks in a string that is passed in from a user. That way, all
single quotation marks are treated as enclosing strings, instead of
database commands.

We do provide SOQL and SOSL builder helpers. The SOSL builder does the
necessary escaping but the SOQL one doesn't (right now it takes the whole
WHERE clause as an argument). But that's something we could improve.

**Comment by brad36** [comment]
Ok that helps, thank you
