### ISSUE TITLE
Upgrade to 4.0 causes logout whenever app is opened.

### ISSUE THREAD

**Issue by mpullman** [forcedotcom/SalesforceMobileSDK-iOS#1333]
Hi,

When upgrading to 4.0 the current user is logged out. If i log in again and kill the app, when I go to reopen it, I'm presented with the login screen again.

If I delete the app and install a fresh version with version 4.0 of the SDK then it keeps me logged in.

Thanks

**Comment by mpullman** [comment]
I think the issue is caused in SFOAuthCredentials.m

```objective-c
if ([self isMemberOfClass:[SFOAuthCredentials class]]) {
                self.refreshToken = [coder decodeObjectOfClass:[NSString class] forKey:@"SFOAuthRefreshToken"];
                self.accessToken  = [coder decodeObjectOfClass:[NSString class] forKey:@"SFOAuthAccessToken"];
            }
```

where that key doesn't exist when upgrading.

**Comment by mattlacey** [comment]
I've been seeing this issue as well, getting pretty tedious logging in every time I test the app! :)

**Comment by fobin** [comment]
+1

**Comment by wmathurin** [comment]
We fixed the problem in unstable. It will be in our next release (4.2).
If you can't wait pull the change from: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1428
