### ISSUE TITLE
4.0.2 not showing up in pod update

### ISSUE THREAD

**Issue by jeffreyjackson** [forcedotcom/SalesforceMobileSDK-iOS#1336]

**Comment by bhariharan** [comment]
@jeffreyjackson We won't be publishing our spec to ```Cocoapods``` anymore. Instead, we maintain separate specs for each our of frameworks [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs/tree/v4.0.2). We will update our ```Specs``` repo every release.

**Comment by jeffreyjackson** [comment]
Thank you, i just noticed the updated documentation and have updated my Podfile accordingly.  I'm able to install 4.0.2 as suggested.
