### ISSUE TITLE
Way too many warnings in the iOS SDK 4.0.2

### ISSUE THREAD

**Issue by rajaraodv** [forcedotcom/SalesforceMobileSDK-iOS#1337]
I see around 10-15 warnings in Mobile SDK(4.0.2). They may 'harmless' but I think we should bring the number close to zero.

I am using Xcode 7.2
<img width="1086" alt="1" src="https://cloud.githubusercontent.com/assets/626337/12326533/45dd2684-ba86-11e5-83e7-a968af5a8a58.png">

**Comment by wmathurin** [comment]
Agreed. But it won't go down to zero since some are in dependent libraries (e.g. React).

**Comment by nekonari** [comment]
Glad to see I'm not the only one seeing "Null passed ..." and "CocoaLumberjack ..." warnings.

**Comment by nekonari** [comment]
I simply suppressed warnings with `-w` flag..

**Comment by xzhangyueqian** [comment]
can use cocoapods to inhibit these warnings. 
'podfile' insert: inhibit_all_warnings!

**Comment by kchitalia** [comment]
Thank you for your feedback. We are looking into this.
