### ISSUE TITLE
Dependency on deprecated SalesforceHybridSDK.framework still exists

### ISSUE THREAD

**Issue by nochum** [forcedotcom/SalesforceMobileSDK-iOS#1345]
The SDK 2.0 Release Notes state that: All hybrid dependencies are now decoupled from SalesforceHybridSDK.framework (which has been retired).

After cloning this repo I ran the install.sh and installed the SmartSyncExplorerHybrid application onto my iPad.  The application fails with the following error:

dyld: Library not loaded: @rpath/SalesforceHybridSDK.framework/SalesforceHybridSDK
  Referenced from: /var/mobile/Containers/Bundle/Application/025FAF7C-7CA6-45C4-B4C2-C72A93081D66/SmartSyncExplorerHybrid.app/SmartSyncExplorerHybrid
  Reason: image not found

What am I doing wrong?

**Comment by wmathurin** [comment]
Did you mean SDK 4.0?

Another way to run the hybrid sample app is to:
- run 'forceios create' (if you haven't installed it, first run 'npm install forceios' to install it)
- clone the https://github.com/forcedotcom/SalesforceMobileSDK-Shared repo 
- cp -r SharedRepoClone/samples/smartsyncexplorer* ForceIosGeneratedApp/www/
- run 'cordova build'

**Comment by khawkins** [comment]
If you check out the most recent changes to the `unstable` branch of the repo, this should be fixed there now too.  The sample apps were not embedding their dependent frameworks, which worked on the simulator, but didn't work on device.

Give that a try and let us know if you still see the problem.

**Comment by khawkins** [comment]
[This PR](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1348) describes the fix.
