### ISSUE TITLE
App crashes on logout in iOS8. SDK version 4.0.

### ISSUE THREAD

**Issue by rubenxifre** [forcedotcom/SalesforceMobileSDK-iOS#1349]
Hi,

I had no issues when logging out with the new version 4.0 of the SDK in iOS9. But when I tried to logout in iOS8, with the Device and Simulator, the app crashes when posting the notification SFUserAccountManagerDidChangeCurrentUserNotification in the class SFUserAccountManager.

Line (1244) where app crashes in class SFUserAccountManager:
```
[[NSNotificationCenter defaultCenter] postNotificationName:SFUserAccountManagerDidChangeCurrentUserNotification
														object:self
                                                      userInfo:@{ SFUserAccountManagerUserChangeKey : @(change) }];
```

Thanks in advanced!

**Comment by oolufemi** [comment]
Also having a problem with this line, getting EXC_BAD_ACCESS. When I use the : 
[[SFAuthenticationManager sharedManager] loginWithCompletion:...

Cheers

**Comment by wmathurin** [comment]
Fixed here: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1388
