### ISSUE TITLE
Default Login Endpoint not working

### ISSUE THREAD

**Issue by toddhalfpenny** [forcedotcom/SalesforceMobileSDK-iOS#1354]
Mobile SDK: 4.0.2
Hybrid App built with Cordova plugin (forceios)

It seem that I cannot overwrite the default login host ("login.salesforce.com") using the _Settings.bundle/Root.plist_ file. Seems this is also reported in the comments in #1100

I initially thought that by modifying this so that this part
```
<dict>
			<key>Key</key>
			<string>primary_login_host_pref</string>
			<key>Type</key>
			<string>PSMultiValueSpecifier</string>
			<key>Title</key>
			<string>LOGIN_HOST_TITLE</string>
			<key>DefaultValue</key>
			<string>mylogin.salesforce.com</string>
			<key>Titles</key>
			<array>
				<string>PRODUCTION_LOGIN_HOST_TITLE</string>
				<string>SANDBOX_LOGIN_HOST_TITLE</string>
				<string>CUSTOM_LOGIN_HOST_TITLE</string>
			</array>
			<key>Values</key>
			<array>
				<string>mylogin.salesforce.com</string>
				<string>test.salesforce.com</string>
				<string>CUSTOM</string>
			</array>
		</dict>
```
now looked like this ( (the _DefaultValue_ and production login value changed)
```
<dict>
			<key>Key</key>
			<string>primary_login_host_pref</string>
			<key>Type</key>
			<string>PSMultiValueSpecifier</string>
			<key>Title</key>
			<string>LOGIN_HOST_TITLE</string>
			<key>DefaultValue</key>
			<string>mylogin.force.com</string>
			<key>Titles</key>
			<array>
				<string>PRODUCTION_LOGIN_HOST_TITLE</string>
				<string>SANDBOX_LOGIN_HOST_TITLE</string>
				<string>CUSTOM_LOGIN_HOST_TITLE</string>
			</array>
			<key>Values</key>
			<array>
				<string>mylogin.force.com</string>
				<string>test.salesforce.com</string>
				<string>CUSTOM</string>
			</array>
		</dict>
```
This did not seem to work. If I got into the settings on the device then I can set the _Login Host_ to _Production_ and this value does take affect.

I have also tried adding this to the file (as per #869), but no joy still.
```
<key>SFDCOAuthLoginHost</key>
<string>mylogin.salesforce.com</string>
```
I have tested this on both devices and simulators (resetting contents/settings etc) but have no joy.

I cannot see any mention of "login.salesforce.com" in my project, perhaps I need to do a manual build of the IOS project as it appears in 'SFOAuthCredentials.m' (in the IOS github source)

**Comment by huminzhi** [comment]
@toddhalfpenny, sorry to follow up late, just wondering if you still see this issue?

**Comment by kchitalia** [comment]
This issue has been fixed in the latest version of the Mobile SDK.
