### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Ankish** [forcedotcom/SalesforceMobileSDK-iOS#1355]
There is so much varied content to install . It fails at various steps. Can anyone upload one simple document to integrate salesforce for Swift .

https://developer.salesforce.com/trailhead/mobile_sdk_native_ios/mobilesdk_ios_cocoapods .

This does not help.

**Comment by wmathurin** [comment]
The trailhead is out of date. However the dev guide is always up to date (https://github.com/forcedotcom/SalesforceMobileSDK-Shared/raw/master/doc/mobile_sdk.pdf).
Also this blog post (https://rwhitleysfdc.wordpress.com/2016/01/14/mobile-sdk-4-0-2-is-now-available/) highlights the recent changes and should get you unblocked. Please re-open the issue if you are still stuck

**Comment by wmathurin** [comment]
@rwhitley the trailhead is wrong now.

**Comment by rwhitley** [comment]
We are in the process of updating it...sorry for the delays.

**Comment by Ankish** [comment]
@wmathurin  @rwhitley . Do send a pod and simple steps to integrate with Swift. Thanks for the quick response !

**Comment by wmathurin** [comment]
Simply install forceios (version 4.0.2).
Run forceios create and choose native_swift for the application type.
Answer the other questions.
Then when it's all done, you open the workspace in the generated app directory and you will have a simple application written in swift which uses the mobile sdk through cocoapods.

**Comment by Ankish** [comment]
We need to integrate to an existing project . How do we proceed with that  ? Pod link available for integrating with existing projects ?

**Comment by wmathurin** [comment]
Yes. Please look at the dev guide page 35.

**Comment by rwhitley** [comment]
Also available here: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/ios_cocoapods.htm

**Comment by Ankish** [comment]
Thanks , this works ! . I recommend using the pdf . People looking for quick answer :

target 'XXX' do
    source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git' # needs to be first
    source 'https://github.com/CocoaPods/Specs.git'


pod 'SalesforceSDKCore'
pod 'SalesforceNetwork'
pod 'SalesforceRestAPI'
