### ISSUE TITLE
use terminal order "forceios create"  install salesforce ios sdk

### ISSUE THREAD

**Issue by xzhangyueqian** [forcedotcom/SalesforceMobileSDK-iOS#1365]
## use terminal order "forceios create"  install salesforce ios sdk have wrong.
like these:
![2016-01-26 1 46 38](https://cloud.githubusercontent.com/assets/15630448/12573380/408f8db4-c433-11e5-88e3-a3782df5bda0.png)

**Comment by xzhangyueqian** [comment]
i had tried to create a project by this order time after time, but also have wrong.

**Comment by xzhangyueqian** [comment]
![2016-01-26 1 56 29](https://cloud.githubusercontent.com/assets/15630448/12573480/a15e1f56-c434-11e5-9059-d6b95d07f145.png)

**Comment by wmathurin** [comment]
What version of forceios are you running?
With the latest version (4.0.2), you shouldn't see any errors.

**Comment by xzhangyueqian** [comment]
forceios version is 4.0.1, thanks

**Comment by wmathurin** [comment]
4.0.1 had issues (like the ones you encountered) that we resolved in 4.0.2. Please upgrade.
