### ISSUE TITLE
SmartStore causing the application to not build

### ISSUE THREAD

**Issue by georgehadly** [forcedotcom/SalesforceMobileSDK-iOS#1367]
I need a help with the SDK 4.0.2 using cocoapod, creating a Swift app with xcode 7.2 and application not building and gives error due to implicit casting in SmartStore.

podfile data

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git'

use_frameworks!
pod 'SalesforceSDKCore'
pod 'SalesforceNetwork'
pod 'SalesforceRestAPI'
pod 'FMDB'
pod 'SmartStore'
pod 'SmartSync'

<img width="1394" alt="screen shot 2016-01-27 at 7 35 22 pm" src="https://cloud.githubusercontent.com/assets/13555875/12622229/f5c61500-c52c-11e5-8bfa-410458ca6e97.png">

**Comment by wmathurin** [comment]
It doesn't look like you are using 4.0.2.
If you were, the sources in the pod file would be in a different order (the Salesforce source first).
```
source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git' # need to be first 
source 'https://github.com/CocoaPods/Specs.git'
```

**Comment by georgehadly** [comment]
Thank you so much . it was 4.0.2 but it seems that i need to remove the old cocoapod first then start it again.
