### ISSUE TITLE
Pods should specify a module_map

### ISSUE THREAD

**Issue by mgetzbw** [forcedotcom/SalesforceMobileSDK-iOS#1369]
https://guides.cocoapods.org/syntax/podspec.html#module_map

This should fix the non-modular includes issue that keeps popping up,

To be honest if this keeps up I may see if I can't get carthage support instead

**Comment by mgetzbw** [comment]
@bhariharan @wmathurin so digging through cocoapods it appears this issue may be their fault, apparently private headers are getting put in a `Pods/Headers` directory in some versions of cocoapods. Deleting that directory seems to fix the issues for me. I should note that the modular headers issue is a blocker for swift support as the swift compiler ignores the flag to allow non-modular includes. After manually deleting the directory everything builds fine with 4.1.0 using swift.

An explicit module map may still be advisable as it allows you to better control what gets exported, but at this time it's probably not required.

**Comment by bhariharan** [comment]
Cool....thanks @mgetzbw! I'll close this for now then.
