### ISSUE TITLE
Better align post-auth user credentials with local SFUserAccounts

### ISSUE THREAD

**Issue by khawkins** [forcedotcom/SalesforceMobileSDK-iOS#1376]
Investigating [this issue](https://plus.google.com/112889346876614390413/posts/Vue1hggTY3W) from the Google Plus Community led me to see that the post-authentication alignment of the new credentials with `SFUserAccountManager.currentUser` is pretty tenuous.  Most notably, `[SFUserAccountManager applyCredentials:]` doesn't explicitly check for existing `SFUserAccount` instances that may already fit the identity of the credentials returned, in favor of more or less blindly configuring a new user with the credentials identity.

This opens the door for having duplicate accounts in the local app, which is then a jumping-off point for other unexpected behavior.  Somewhere in the vicinity of `[SFAuthenticationManager finalizeAuthCompletion]`, the current user should be aligned with any existing account matching the identity of the auth credentials, before creating and/or updating a new account.

**Comment by kchitalia** [comment]
@khawkins I looked at the latest code and this seems to be taken care of. Please re-open if there is more work to be done here.

**Comment by khawkins** [comment]
It deceptively looks like it does, but it doesn't really.  If you look at `[SFUserAccountManager applyCredentials:]`, the pseudo-code representation of what it does is:
```
Given credentials:
if currentUser doesn't exist
    create new user and configure that as currentUser with the new credentials
else if currentUser does not align with the supplied credentials
    log a warning message and exit
else
    configure existing currentUser with the new credentials
```
But this bug is pointing out a use case that isn't covered above.  Namely, what if `currentUser` is not set—or is set to a user that doesn't align with the credentials—but the user that aligns with the given credentials *does* exist as another user in `SFUserAccountManager.userAccountMap`?  In this case, we're going to create a brand new user (and persist it) with the same identity as an existing user.

If a user already exists in this case, `currentUser` should be set to *that* user, and the new credentials information should then be applied accordingly.

**Comment by bhariharan** [comment]
I believe we've covered this with our recent account management refactoring effort.
