### ISSUE TITLE
Pass internal error info to custom errorPage

### ISSUE THREAD

**Issue by toddhalfpenny** [forcedotcom/SalesforceMobileSDK-iOS#1389]
SDK 4.0.0  and below - Is there a way to get error information in the a custom errorPage (as defined in bootconfig.json)?

Looking at the Dev Guide I can't see any mention at all, but looking at the [iOS source](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/745cb99d69f38a89592575b22688118fa2d3edb0/libs/SalesforceHybridSDK/SalesforceHybridSDK/Classes/SFHybridViewController.m#L113) it seems that if no errorPage is defined then some details (code, desc, context) are available.

It would be nice if these are also available in a custom errorPage so as to be used in an informative manner. We're happy to help with this but not sure where to start.

**Comment by wmathurin** [comment]
They are passed as query params and can be retrieved from the javascript side by parsing window.location.href. The URL is built here: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceHybridSDK/SalesforceHybridSDK/Classes/SFHybridViewController.m#L394
