### ISSUE TITLE
Custom host setting not working with new update

### ISSUE THREAD

**Issue by manish-metacube** [forcedotcom/SalesforceMobileSDK-iOS#1396]
Hi All, 

I have tried MobileSDK 4.1, With new SDK, environment change is part of login screen. With new one if user enters custom host, It's not working anymore. Getting following error. 
`ERROR|SFAuthenticationManager|Error during authentication: Error Domain=WebKitErrorDomain Code=101 "(null)" `

One more problem with new interface, if user has made typo in custom host, he has no choice to correct it except deleting app as screen flash with above error continuously. 

Do we have any fix for that?

-Manish Kumar

**Comment by bhariharan** [comment]
@manish-metacube We are aware of this issue and looking into it. Thanks for reporting it! Stay tuned for a fix.

**Comment by brad36** [comment]
I don't see the error that OP sees. The issue I see is a blue screen, no way out for the user, when I try to change login host on 4.1 (pic attached):

![img_0028](https://cloud.githubusercontent.com/assets/5522047/13258420/10d2b976-da21-11e5-978e-a17c85bbb0e6.PNG)

**Comment by bhariharan** [comment]
This issue has been fixed in ```master```. For the blue screen, you can click the ```Gear``` icon and change the server to a valid host. For an invalid custom host, you can use the ```Gear``` icon to create a new valid custom host. You won't need to uninstall the app.

**Comment by brad36** [comment]
I'm getting in 4.1.1, changing to sandbox gives blue screen, then changing back to production does nothing, leaves the screen blue unchanged. User is left confused and bewildered. After about 10 minutes, then the login eventually appears. Clearly they can't wait 10 minutes. The only real workaround for the user appears to be app switcher, close app. Do you really consider this fixed, or am I misunderstanding something?

**Comment by brad36** [comment]
Note the above is simply using the gear icon to try to change the login host for a fresh install of the app on 9.2.1, I'm not trying to do anything fancy

**Comment by jeffreyjackson** [comment]
I'm able to reproduce this error as well.

**Comment by brad36** [comment]
I'm still seeing this issue in 4.1.2

**Comment by brad36** [comment]
Switching to Sandbox using the gear icon gives blue screen, the gear icon doesn't fix the blue screen. In fact, I can't even log in to sandbox unless I use the "Use Custom Domain" link. @bhariharan Are we talking about the same issue? Is this really fixed?

**Comment by bhariharan** [comment]
@kchitalia Could you check and respond please?

**Comment by kchitalia** [comment]
Will take a look.

**Comment by kchitalia** [comment]
I ran the sample app (RestAPIExplorer) for our 4.1.2 version. I was able to use the gear icon to switch between Production and Sandbox.

**Comment by Prabuganesan** [comment]
Please add following code in appdelegate class and fix this issue.

[SalesforceSDKManager sharedManager].switchUserAction = ^(SFUserAccount *fromUser, SFUserAccount *toUser) {
            [weakSelf handleUserSwitch:fromUser toUser:toUser];
        };
