### ISSUE TITLE
Using a custom host, how do I remove options in settings?

### ISSUE THREAD

**Issue by rgoldiez** [forcedotcom/SalesforceMobileSDK-iOS#1400]
We are building an app that leverages Communities, and we have a custom OAuth endpoint for the community login.  No issues with our app or SDK (we're on SDK 4.0.2).  My question is whether or not I can remove the connection options from the settings for my app (iOS Settings -> My App).  I don't want the user to see or have the option of changing the login end point.

**Comment by bhariharan** [comment]
@rgoldiez Sure - when you build your app, remove the ```Settings``` bundle in the ```Mobile SDK```, and it won't show up.

**Comment by rgoldiez** [comment]
@bhariharan - Thanks for the info.  I'm guessing I will also lose the 'Logout Now' switch and the App Version, correct?

**Comment by bhariharan** [comment]
Yes that is correct. It is recommended that you have your own ```Logout``` button in your app.

**Comment by rgoldiez** [comment]
Got it.  Thanks for the fast reply!
