### ISSUE TITLE
How to know when I sync down is finished?

### ISSUE THREAD

**Issue by xzhangyueqian** [forcedotcom/SalesforceMobileSDK-iOS#1402]
hey all,
In `SObjectDataManager` class, how to know when I sync down is finished  with  the `refreshRemoteData` method?
in the `SFSyncState` block? But I wanna know when I sync is finished out of the class.

**Comment by wmathurin** [comment]
Please use this forum only to post known issues/bugs with the Mobile SDK. For other queries, please post on our Google+ community here (https://plus.google.com/communities/114225252149514546445).
