### ISSUE TITLE
Swift support: Specify nullability

### ISSUE THREAD

**Issue by mgetzbw** [forcedotcom/SalesforceMobileSDK-iOS#1412]
[Swift treats any api that does not explicitly specify nullability as implicitly unwrapped](https://developer.apple.com/swift/blog/?id=25), even when those apis can return `nil` and should be `Optional`. Implicit unwrapping can lead to bugs that a swift programmer simply cannot fix because the api is behaving as expected. We should specify nullability whenever possible to explicitly make it clear the intent of the API both in Objective-C and Swift.

**Comment by kchitalia** [comment]
Closing this out as PR has been merged.
