### ISSUE TITLE
Swift support: Use Objective-C lightweight Generics

### ISSUE THREAD

**Issue by mgetzbw** [forcedotcom/SalesforceMobileSDK-iOS#1413]
[Swift when it imports Objective-c apis uses the generic annotations to strongly type collections](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/WorkingWithCocoaDataTypes.html#//apple_ref/doc/uid/TP40014216-CH6-ID61). We should use this to limit what sort of data swift users of the SDK can pass to reduce the number of bugs and ensure we're getting the right data in.

**Comment by kchitalia** [comment]
Closing this issue as PR has been merged.
