### ISSUE TITLE
HTML File Input breaks once granted access to photo library

### ISSUE THREAD

**Issue by e-bacho** [forcedotcom/SalesforceMobileSDK-iOS#1424]
I have a page wrapped in a web view (**WKWebView**) which has a File Input to upload photos. By default iOS doesn't allow any application to access the photos library, instead it pops up a confirmation dialog **"YOUR APP Would Like to Access Your Photos"**. Once I allow access for the application, the page gets refreshed and the File Inputs stop working (not responding). 

The problem occurs only the first time you grant access to the photo library. Restarting the app fixes the problem.

I have replicated the same scenario without the SDK and it seems to be ok. I can confirm that something is broken in the SDK when the popup dialog to allow access to the photo library is shown by clicking on a File Input in **WKWebView**

**Comment by wmathurin** [comment]
We don't provide any components that make use of the WKWebView - so the page/screen you are referring too is one you must have built from the grown up. Once you are passed login, the SDK doesn't interfere with anything you show on the screen.
