### ISSUE TITLE
Subsequent sync down fails with no internet connection

### ISSUE THREAD

**Issue by vincee48** [forcedotcom/SalesforceMobileSDK-iOS#1429]
Using forceios (v4.1.1) with React Native (v0.20.0), calling any subsequent sync downs (after the initial load of data into the soup) on a prebundled package without any internet connection throws an error:

FAILED cause:Server call for sync down failed error:Error Domain=CSFNetworkErrorDomain Code=1004 "HTTP request returned an error" UserInfo={NSUnderlyingError=0x12eed5850 {Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." 

This prevents us from using the application offline without prior internet when application started up, which was previously working on forceios v4.0 and React Native v0.16.0. 

Simple steps to reproduce: 
1. forceios create (and follow steps)
2. Set up a prebundled package react-native bundle --platform ios --dev false --entry-file js/index.ios.js --bundle-output main.jsbundle
3. Include bundle in Xcode project
4. Initial run on device with WiFi to sync down
5. Turn off WiFi and shake to reload the application

**Comment by wmathurin** [comment]
You should only call sync down if you have an internet connection.
