### ISSUE TITLE
SFRestRequest queryParams deosn't allow NSDictionary<AnyObject,AnyObject>  anymore

### ISSUE THREAD

**Issue by oolufemi** [forcedotcom/SalesforceMobileSDK-iOS#1430]
This is a follow up to #1218 changes.

Prior to 4.1.1 I was able to call SFRestRequest with just NSDictionary with (AnyObject,AnyObject) but this has now been changed to NSDictionary with (String,String).

Specifically lines in SFRestRequest.m:
Line 115 -@property (nonatomic, strong) NSDictionary *queryParams;
Line 116 +@property (nullable, nonatomic, strong) NSDictionary<NSString*, NSString*> *queryParams;

We have defined our own rest interface methods and some of them have sub data. I.e ObjectA.ObjectB.FieldA. This doesn't work anymore. I want to know if this is the right approach. Or should I really be creating my own rest class using IOS's NSURLRequest and NSURLConnection classes?

**Comment by wmathurin** [comment]
When did you need non-string query parameters?

**Comment by oolufemi** [comment]
Thanks for looking into this.

Lets say I have a data structure defined for example as 
class Person
{
string id;
string name;
Type type;
}
class Type
{
string id
}

Then I define a salesforce doPost defined as
@HttpPost global static String doPost(Person person) {
return null;
}

The resultant JSON would be something like {"id":"P001","name":"foo boo", type:{"id":"T001"}}

We have defined a data structure with a lot of these type of coding and it worked before.

**Comment by wmathurin** [comment]
Fixed in unstable - see referenced pull request above.
