### ISSUE TITLE
App routing to Salesforce home page instead of Allow Access screen.

### ISSUE THREAD

**Issue by ksrvmahesh** [forcedotcom/SalesforceMobileSDK-iOS#1433]
Hi,

Navigate back to login screen from Forgot Password screen. Now, after login with user credentials, app is routing to Salesforce Home screen rather than Allow Access screen and can’t move any further beyond.

Attaching the log for reference.

[ForgotPassword Logs.txt](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/157698/ForgotPassword.Logs.txt)

**Comment by ksrvmahesh** [comment]
Any response to this post would be greatly helpful and appreciated.

**Comment by kchitalia** [comment]
This is a known issue, the server side team is aware of this and are working on this. This is outside of the control of the Mobile SDK team.

**Comment by huminzhi** [comment]
@ksrvmahesh The fix is likely to be in next salesforce core release (Safe harbor...)
