### ISSUE TITLE
App needs to re-login everytime it is fired up after user updates app

### ISSUE THREAD

**Issue by oolufemi** [forcedotcom/SalesforceMobileSDK-iOS#1435]
To reproduce, install version 1 which uses SalesforceMobileSDK 3.3.1 installed in simulator everything works fine, then I update to version 2 which uses 4.1.1. Now you'll have to login every time you fire up the app.

However, if I delete version 1 before installing version 2, Version 2 remembers I previously logged in on subsequent fire ups and everything works fine.

**Comment by fobin** [comment]
Exactly the same situation here.

**Comment by wmathurin** [comment]
We fixed the problem in unstable. It will be in our next release (4.2).
If you can't wait pull the change from: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1428

**Comment by oolufemi** [comment]
Hi @wmathurin 

Since the changes on  #1428 have been reverted. Should this ticket be re-opened?

Cheers

**Comment by wmathurin** [comment]
The proper fix went in with: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1456

**Comment by oolufemi** [comment]
Oh Ok. Looking forward to 4.2 then. 
Thanks
