### ISSUE TITLE
How to update SDK version to 4.1.1 with cocoapods?

### ISSUE THREAD

**Issue by xzhangyueqian** [forcedotcom/SalesforceMobileSDK-iOS#1445]
Hi guys,

How to update SDK version to 4.1.1 `with cocoapods`?
I find that only can update to 4.0.0

**Comment by wmathurin** [comment]
We won't be publishing our spec to Cocoapods anymore. Instead, we maintain separate specs for each our of frameworks [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs/tree/v4.0.2). We will update our Specs repo every release.

For more information, please look at:
https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/ios_cocoapods.htm
