### ISSUE TITLE
Long time no touch the program and program timeout logout to the login page.

### ISSUE THREAD

**Issue by vampire02170** [forcedotcom/SalesforceMobileSDK-iOS#1447]
My program is used to support offline work, but for a long time not touch program, such as operating again after 1 hour, will automatically pop up to the landing interface, that can change the timeout?Or other way?Very worried, please help me, thank you!

**Comment by wmathurin** [comment]
What kind of application are you building: native / hybrid local / hybrid remote?
What version of the SDK are you using?

**Comment by vampire02170** [comment]
native，4.1.1，Recently I found that seems to have not have this problem, a long time not touch will not automatically jump out
