### ISSUE TITLE
INVALID_QUERY_LOCATOR

### ISSUE THREAD

**Issue by Ded77** [forcedotcom/SalesforceMobileSDK-iOS#1450]
I receive an _INVALID_QUERY_LOCATOR_ error form the server when I'm trying to perform several syncDown synchronization in parallel.

`[SFSmartSyncSyncManager syncDownWithTarget:options:soupName:updateBlock:]`

Do I have to queuing these operations ? If i do it, it fix this issue, but I worry about performance.
Thank you.

**Comment by wmathurin** [comment]
You're hitting a server side limit, see:
https://help.salesforce.com/apex/HTViewSolution?id=000004410&language=en_US
