### ISSUE TITLE
In the condition of no net, local created a data without Id, but when I have a net want to delete this data，and delete not to drop.

### ISSUE THREAD

**Issue by vampire02170** [forcedotcom/SalesforceMobileSDK-iOS#1454]
In the condition of no net, local created a data without Id, but when I have a net want to delete this data, delete my use method is - (BOOL) dataLocallyDeleted (SObjectData *) data;Synchronization error, when they can't find the record Id, there is no other way to delete the data.Very worried, please help!!!!!

**Comment by wmathurin** [comment]
I'm not sure I follow. Locally created records should have a local id. When you sync them up to the server, the id is replaced with the server side id. To delete a locally created records that was never synched up to the server, simply use SFSmartStore's removeEntries method.

**Comment by vampire02170** [comment]
Thank you very much, I'll give it a try！

**Comment by vampire02170** [comment]
No local network condition how to query the Id of the new data(created by local)?
- (void)removeEntries:(NSArray*)entryIds fromSoup:(NSString*)soupName; 
The inside of the entryIds how to get?

**Comment by wmathurin** [comment]
To get the id of locally created records, you could run the following SmartStore query.

```objective-c
- (NSOrderedSet*) geLocallyCreatedRecordIds:(NSString*)soupName idField:(NSString*)idField {
    NSMutableOrderedSet* ids = [NSMutableOrderedSet new]; 
    NSString* dirtyRecordSql = [NSString stringWithFormat:@"SELECT {%@:%@} FROM {%@} WHERE {%@:__locally_created__} = '1' ORDER BY {%@:%@} ASC", soupName, idField, soupName, soupName, soupName, idField];
    SFQuerySpec* querySpec = [SFQuerySpec newSmartQuerySpec:dirtyRecordSql withPageSize:kSyncManagerPageSize];

    BOOL hasMore = YES;
    for (NSUInteger pageIndex=0; hasMore; pageIndex++) {
        NSArray* results = [self.store queryWithQuerySpec:querySpec pageIndex:pageIndex error:nil];
        hasMore = (results.count == kSyncManagerPageSize);
        [ids addObjectsFromArray:[self flatten:results]];
    }
}

- (NSArray*) flatten:(NSArray*)results {
    NSMutableArray* flatArray = [NSMutableArray new];
    for (NSArray* row in results) {
        [flatArray addObjectsFromArray:row];
    }
    return flatArray;
}
```

**Comment by vampire02170** [comment]
I used the method of  - (NSOrderedSet*) geLocallyCreatedRecordIds:(NSString*)soupName idField:(NSString*)idField;But give me return an error ：DEBUG|SFSmartStore|Unknown index path '__locally_created__' in soup 'productSelling' .productSelling Is my own built a table，No '__locally_created__' field in productSelling?Actually, I want to delete the local in the absence of the network to create a record, because don't want to sync on the server, what others methods?Please help me,thanks.

**Comment by vampire02170** [comment]
Add a question, soupEntryIds is what mean?SoupEntryIds is the default in the list?How can I get?

**Comment by wmathurin** [comment]
To be able to query on a given field, you need to have an index spec on that field when you registered the soup.
For smart sync to work, you need an index on \_\_local\_\_. (In the sample app, it gets done here: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/native/SampleApps/SmartSyncExplorer/SmartSyncExplorer/Classes/Data/SObjectDataSpec.m#L94)
If you need to query by \_\_locally\_created\_\_, make sure to also create an index on \_\_locally\_created\_\_

**Comment by vampire02170** [comment]
thanks very much,I have already solved the problem！

**Comment by vampire02170** [comment]
How to pass a SOQL statement query out a record? Have already write method?Please help me,thanks!!!

**Comment by wmathurin** [comment]
Please use github issues only for bugs/enhancements requests.
For "How to" questions, please go to our g+ community https://plus.google.com/communities/114225252149514546445
