### ISSUE TITLE
About big data

### ISSUE THREAD

**Issue by vampire02170** [forcedotcom/SalesforceMobileSDK-iOS#1455]
Salesforce request data a maximum of 10000 data back?If I request the data of more than 10000, how to send the request again?Need to do paging processing?SObjectDataSpec can hold more than 10000 data?Ask for advice, please

**Comment by wmathurin** [comment]
You can sync as much data as you wish from the server. Sync manager will automatically get the next set of results and stream them to SmartStore. If you get many records in a single call, your memory usage will be significant. If you get many records as part of a sync down, the size on disk of the database (SmartStore) will be significant, also the time to run the query on the server could become significant.
Make sure to test to see if the query time / memory usage / disk usage are within whatever constraints you have for your application (if your application is meant to run over wi-fi on a modern iPad, you can tolerate more data etc, but if you need to run on iPhone 4s over 3G, you probably need much lower limits).

NB: SmartSyncExplorer is just an example application. It pulls all the data into memory for the list view. Real world applications should do paging instead.

**Comment by vampire02170** [comment]
if (self.syncDownId == 0) {
        // first time
        NSString *soqlQuery = [NSString stringWithFormat:@"SELECT %@, LastModifiedDate FROM %@", [self.dataSpec.fieldNames componentsJoinedByString:@","], self.dataSpec.objectType];
        SFSyncOptions *syncOptions = [SFSyncOptions newSyncOptionsForSyncDown:SFSyncStateMergeModeLeaveIfChanged];
        SFSyncDownTarget *syncTarget = [SFSoqlSyncDownTarget newSyncTarget:soqlQuery];
        [self.syncMgr syncDownWithTarget:syncTarget options:syncOptions soupName:self.dataSpec.soupName updateBlock:updateBlock];
    }
Write SQL statements like @"SELECT Id,Name, LastModifiedDate FROM Account", only once, when upDown salesforce at most how many records returned to me?

**Comment by wmathurin** [comment]
That query is actually a SOQL query that is run on the server.
At most 2000 records will be returned per round trip to the server, but the sync down code repeatedly calls the server until there are no results left.

For SOQL/SOSL limits, please see: https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_soslsoql.htm
