### ISSUE TITLE
Can't remove header in login screen

### ISSUE THREAD

**Issue by dcacenabes** [forcedotcom/SalesforceMobileSDK-iOS#1460]
Hi,

We're using salesforce SDK in our app to login. We recently updated from version 3 to version 4.1.1, and we were surprised to get this new navigation bar on top.
[https://goo.gl/photos/W8TqduaWDWUcwzdk7]

We even did a build in release mode just to see that the bar is still there, and there's no option to disable it.

We don't like to provide our users a bar with the option to switch between sandbox and production. How can we get rid of this?

**Comment by Ded77** [comment]
It seems you have to provide a custom login screen or to modify the SDK.
[post on this subject](https://plus.google.com/111318623814882549200/posts/Xvmhpk4LsFv)

**Comment by kchitalia** [comment]
@dcacenabes I am working on a way to allow hiding the gear icon on the navigation bar. You will still see the navigation bar that says "Log In" but without the icon. You do have the ability to use colors of your choice for the navigation bar.

**Comment by kchitalia** [comment]
Please get the latest from unstable branch and you should be able to hide the gear icon and navigation bar.
