### ISSUE TITLE
When I logout, all the data in local will be cleared?

### ISSUE THREAD

**Issue by vampire02170** [forcedotcom/SalesforceMobileSDK-iOS#1463]
When I logout, all the data in local will be cleared ?   There is another problem.Log in to your account, after a long time not to run the program, the program will jump out to the login screen ?   The mechanism is inside?

**Comment by wmathurin** [comment]
On logout, we clear all user data (smartstore etc). 
However the app should only log out if the refresh token was revoked by an administrator on the server or the user actually logged out.
What kind of application are you building (native / hybrid local / hybrid remote)?
When have you seen it log out on its own?

**Comment by vampire02170** [comment]
I create native with 4.1.1 version;Have not seen automatic logout, so now I just don't know how long will automatically logout.Because my program should be used when there is no net, once published, will affect the use.

**Comment by wmathurin** [comment]
It will only log out if:
- the user chooses to log out
- the administrator revokes the refresh token for that user (that's a way to remotely wipe a device that got lost).

**Comment by vampire02170** [comment]
I know, thank you very much！
