### ISSUE TITLE
How to get the inside of the log in to your account information？

### ISSUE THREAD

**Issue by vampire02170** [forcedotcom/SalesforceMobileSDK-iOS#1464]
How to log in access to log in to your account when Alisa describes information?Just like this :  [SFUserAccountManager sharedInstance] currentUser. The userName;  But there was no Alisa describes the field of information,please help me,thanks!

**Comment by wmathurin** [comment]
To get the user information, you use the chatter rest api e.g https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/connect_resources_users_UserProfileInformation.htm

**Comment by wmathurin** [comment]
Please use this forum only to post known issues/bugs with the Mobile SDK. For other queries, please post on our Google+ community here (https://plus.google.com/communities/114225252149514546445).

**Comment by vampire02170** [comment]
thank you very much!
