### ISSUE TITLE
SalesforceMobileSDK - iOS HTTP or HTTPS is interact with the server?

### ISSUE THREAD

**Issue by vampire02170** [forcedotcom/SalesforceMobileSDK-iOS#1468]
My Xcode is version 7.3, SalesforceMobileSDK - iOS create native, is synchronous data interact with the server using HTTP or HTTPS?

**Comment by wmathurin** [comment]
Https.

**Comment by vampire02170** [comment]
Can choose the time synchronization?For example, I just want to synchronize data from now until a year ago?

**Comment by wmathurin** [comment]
You target the data you want to sync with a SOQL query. So if you want records from the last 12 months, you should specify that in your query.

**Comment by vampire02170** [comment]
Can you tell me where I can modify this SOQL?And how to write this SOQL statement?Thank you very much!!!!!

**Comment by wmathurin** [comment]
Please use this forum only to post known issues/bugs with the Mobile SDK. For other queries, please post on our Google+ community here (https://plus.google.com/communities/114225252149514546445).
