### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by rskuja** [forcedotcom/SalesforceMobileSDK-iOS#1470]
Any plans for Carthage support? Just pushing out compiled frameworks with releases would be enough.

**Comment by rskuja** [comment]
When making new release attach zip named similarly like this with similar contents and you are good to go. 
[SalesForceMobileSDK-iOS-4.1.1.framework.zip](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/197565/SalesForceMobileSDK-iOS-4.1.1.framework.zip)

**Comment by huminzhi** [comment]
The issue is fixed or solved in latest build.

**Comment by kgrigsby59** [comment]
I need this too.

**Comment by idStar** [comment]
Carthage support would be really welcome. It's often the lighter weight approach and many of us want to use frameworks that pull in the SF SDK in apps that also use the SF SDK, and we run as much of it as we can, using Carthage. Mixing in Cocoapods makes it quite difficult to get builds working.

I would really love to see this feature supported by Salesforce, for this SDK.

**Comment by quidcomobile** [comment]
Hi there,

Is there any news on Carthage support? Working with the v6.x SDK is a nightmare.

Thanks

**Comment by idStar** [comment]
No, not that I've heard. I'm not sure why it's not a priority, given Carthage's rise in popularity and it's minimalist, clean approach.

**Comment by bhariharan** [comment]
@quidcomobile Could you expand a bit on `"working with the v6.x SDK is a nightmare"`? It should work well using `forceios` and `Cocoapods`. Also, it is possible to use `Carthage` with `Mobile SDK` with our framework targets. All you need to do is create a root level `.cart` file and consume our framework targets.

**Comment by quidcomobile** [comment]
Hey @bbirman , 

If you have some some documentation, read me or step-by-step on how to build the frameworks using Carthage, that would be awesome. We use Carthage as dependency manager and I would prefer not to rely on Cocoapods.

Thanks in advance.

**Comment by idStar** [comment]
Agreed. Having some step by step instructions as part of this repo's README doc would be really helpful. Then, it's a self-serve proposition that others can leverage.

**Comment by bhariharan** [comment]
I'll look into it.

**Comment by khawkins** [comment]
To the extent that I've worked with Carthage and the Mobile SDK, the required documentation didn't need to go further than Carthage's [Cartfile docs](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md).  The bootstrapping of the Mobile SDK through Carthage is pretty down the middle as a Carthage use case, from my experience anyway.

**Comment by quidcomobile** [comment]
Thans @khawkins , @bhariharan 

I have managed to change my cartfile and I have now the frameworks all in order. Would be good to document this on READ.me though.

**Comment by bhariharan** [comment]
I have verified that consuming the Mobile SDK by following the steps outlined by Carthage works fine. We will update our developer guide to include these instructions.

**Comment by kamalmtxb2b** [comment]
I am using below command to include salesforce mobile sdk iOS through Carthage :
**github "forcedotcom/SalesforceMobileSDK-iOS" "master"**

but I am facing an error:
> A shell task (/usr/bin/env git checkout --quiet 77462ca5f450c903dce9e6b621497e036cecad76 (launched in /<path>/Carthage/Checkouts/SalesforceMobileSDK-iOS/external/fmdb)) failed with exit code 128:
> fatal: Cannot switch branch to a non-commit '77462ca5f450c903dce9e6b621497e036cecad76'

**Comment by bhariharan** [comment]
@kamalmtxb2b Once you create the `Cartfile`, run the following steps:
- Run carthage update --no-build. This will fetch the dependencies specified in your Cartfile.
- Navigate to `Carthage/Checkouts/SalesforceMobileSDK-iOS` and run `. install.sh` to fetch the dependencies needed by Mobile SDK.
- Run `carthage build` to build the schemes.
