### ISSUE TITLE
Hybrid App Logout problem

### ISSUE THREAD

**Issue by e-bacho** [forcedotcom/SalesforceMobileSDK-iOS#1482]
I noticed a problem when logging out from my hybrid app and then trying to login again (either same user or a different user, the issue is the same). I have tried logging out with both these methods:

`cordova.require("com.salesforce.plugin.sfaccountmanager").logout();`
and
`cordova.require("com.salesforce.plugin.oauth").logout();`

The app logs the user out and I get back to the oAuth web view to login again. Once I log in I get the following log in XCode:

```
WARN|SFDirectoryManager|Credentials missing for user <SFUserAccount username=XXX@XXX.XXX fullName=Test Account accessScopes={(
    web,
    api
)} credentials=<SFOAuthCredentials identifier="XXXXX" clientId="XXXXXX" domain="login.salesforce.com" identityUrl="(null)" instanceUrl="(null)" communityId="(null)" communityUrl="(null)" issuedAt="(null)" organizationId="(null)" protocol="https" redirectUri="testsfdc:///mobilesdk/detect/oauth/done">, community=(null)>
2016-04-08 09:54:15:706 MyApp[13745:d707] 

WARN|SFDirectoryManager|Credentials missing for user <SFUserAccount username=XXX@XXX.XXX fullName=Test Account accessScopes={(... 
```
repeats 4 times

If I log out, kill the app and then start it again and log in, everything seems to be fine.

Is there a different method that I should be using in order to log out?

**Comment by kchitalia** [comment]
@e-bacho What version of the SDK are you using?

**Comment by e-bacho** [comment]
@kchitalia I'm using 3.3.0

**Comment by huminzhi** [comment]
@e-bacho Not sure if you can upgrade to latest version and do you still see this issue?

**Comment by kchitalia** [comment]
@e-bacho Closing this issue. Please re-open if this issue still exists with our latest version of the Mobile SDK(v 4.2)

**Comment by quoctc** [comment]
It's still happen in SDK version 5.0
After i logged in the app say:
**WARNING com.salesforce <SFDirectoryManager>: Credentials missing for user .**
