### ISSUE TITLE
Unable to set custom login server with info.plist

### ISSUE THREAD

**Issue by BrettMN** [forcedotcom/SalesforceMobileSDK-iOS#1489]
After updating to the latest sfdc mobile sdk adding `SFDCOAuthLoginHost` with a custom login url does not show the user the custom login url.

This process is described in the [Mobile SDK Development Guide](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/oauth_custom_login_host.htm) as : 

> # Setting a Custom Login Server
For special cases—for example, if you’re a Salesforce partner using Trialforce—you can redirect your user’s login requests to a custom login URI.
## iOS Configuration
Before version 4.1, Mobile SDK apps for iOS defined their custom login URIs in the app’s Settings bundle. In Mobile SDK 4.1 and later, iOS apps no longer include a Settings bundle. Instead, during development you can edit your app’s info.plist file and set the SFDCOAuthLoginHost property to your custom login URI.

**Comment by kchitalia** [comment]
@BrettMN If you get the latest from the unstable branch this should work.

**Comment by BrettMN** [comment]
@kchitalia That's great to hear.  Problem is I used forcedroid to create a hybrid_local app and added ios as a platform afterwards.  Will using the unstable forcedroid branch create the ios project off of the SalesforceMobileSDK-iOS unstable branch?

**Comment by kchitalia** [comment]
@BrettMN This will be fixed in our next release.
