### ISSUE TITLE
How to use the CreatedDate field?

### ISSUE THREAD

**Issue by vampire02170** [forcedotcom/SalesforceMobileSDK-iOS#1491]
Hi, guy : 
I've got a problem，Salesforce will default create CreatedDate fields for each new tables,I just want to take this field to use, but will not change its value，finally, I synchronize the time of this table, it will give me an error and prevent me from synchronous CreatedDate fields, Salesforce is not let me to have a synchronous CreatedDate field?please help me，thanks.

**Comment by vampire02170** [comment]
I was using  native iOS 4.1.1 version

**Comment by bhariharan** [comment]
@vampire02170 ```CreatedDate``` is a reserved auto-populated field. You can't modify it using REST API.

**Comment by vampire02170** [comment]
SalesforceMobileSDK - iOS 4.1.1 version of the native, can not run on the ipad Mini 1 and the ipad Pro?A configuration or need to change the SDK?Now only can run on the device ipad 2.  why?I hope you can give me some advice,thanks.

**Comment by wmathurin** [comment]
We don't restrict the device but it has to run iOS 8 or above.
