### ISSUE TITLE
Crash: NSOperationQueue SFJsonUtils.m projectIntoJson

### ISSUE THREAD

**Issue by eescamilla** [forcedotcom/SalesforceMobileSDK-iOS#1495]
We use Crashlytics/Fabric for crash tracking and we received this crash:

Crashed: NSOperationQueue 0x16dfb8f0 :: NSOperation 0x1b0a0270
SIGABRT ABORT 0x0000000031d5cdf0

The line that is specified is: SFJsonUtils.m line 110 +[SFJsonUtils projectIntoJson:path:] in SalesforceMobildeSDK version 4.0 

Went back in history to see if this was a previous issue but didn't see anything related to this, appreciate your feedback

**Comment by wmathurin** [comment]
What were you doing at the time?
Do you have more detailed logs?

**Comment by kchitalia** [comment]
@eescamilla Can we please get details as asked in the previous post?

**Comment by kchitalia** [comment]
@eescamilla Closing this issue. Please re-open if the issue still exists with the latest version of the Mobile SDK(v 4.2)
