### ISSUE TITLE
Crash: SFUserAccountManager.m line 1244 -[SFUserAccountManager userChanged:]

### ISSUE THREAD

**Issue by hiralnaik** [forcedotcom/SalesforceMobileSDK-iOS#1496]
Crashlytics/Fabric crash. 

Below is the crash information. 

Fatal Exception: NSInvalidArgumentException
-[__NSCFString userAccountManagerDidChangeCurrentUser:]: unrecognized selector sent to instance 0x1579daf0

SFUserAccountManager.m line 1244
-[SFUserAccountManager userChanged:]

Logs
0x2a268749 -[NSNotificationCenter postNotificationName:object:userInfo:]
0x1b2cd7 -[SFUserAccountManager userChanged:] (SFUserAccountManager.m:1244)
0x1b1fff -[SFUserAccountManager setCurrentUser:] (SFUserAccountManager.m:1119)
0x175233 -[SFAuthenticationManager logoutUser:] (SFAuthenticationManager.m:475)
0x174e49 -[SFAuthenticationManager logout] (SFAuthenticationManager.m:421)
UIKit                          0x2cf45fe3 -[UIPresentationController transitionDidFinish:]
14 UIKit                          0x2d2cdaed -[_UIFullscreenPresentationController transitionDidFinish:]
15 UIKit                          0x2cf48173 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke_2
16 UIKit                          0x2cd8131f -[_UIViewControllerTransitionContext completeTransition:]
17 UIKit                          0x2cd811c3 -[UITransitionView notifyDidCompleteTransition:]
18 UIKit                          0x2cd80cb1 -[UITransitionView _didCompleteTransition:]
19 UIKit                          0x2cca48dd -[UIViewAnimationState sendDelegateAnimationDidStop:finished:]
20 UIKit                          0x2cca47ef -[UIViewAnimationState animationDidStop:finished:]
21 QuartzCore                     0x2c688961 CA::Layer::run_animation_callbacks(void*)
22 libdispatch.dylib              0x384ee2cf _dispatch_client_callout
23 libdispatch.dylib              0x384f1d2f _dispatch_main_queue_callback_4CF
24 CoreFoundation                 0x295b9609 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
25 CoreFoundation                 0x295b7d09 __CFRunLoopRun
26 CoreFoundation                 0x29504201 CFRunLoopRunSpecific
27 CoreFoundation                 0x29504013 CFRunLoopRunInMode
28 GraphicsServices               0x30f8f201 GSEventRunModal
29 UIKit                          0x2ccd0a09 UIApplicationMain
30 XXXXX                          0x89027 main (main.m:40)
31 libdyld.dylib                  0x3850faaf start

I Went back in history to see if this was a previous issue but didn't see anything related to this, appreciate your feedback

**Comment by wmathurin** [comment]
What version of the Mobile SDK are you using?

**Comment by hiralnaik** [comment]
We are using Mobile SDK 4.0.0.

**Comment by huminzhi** [comment]
Hi, @hiralnaik , I see you fixed this issue here:
https://github.com/hiralnaik/SalesforceMobileSDK-iOS/commit/7c4da8f1665f25ebee695a01c34f41f18befc4ce
Thank you very much! 
BTW, I noticed the title of that fix, so it only happens in ios8, not ios9? Thanks a lot!

**Comment by wmathurin** [comment]
It was also fixed in 4.1.1, see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/commit/659f879c7af70282c1c7afc44ede6765ef9a310a

**Comment by bhariharan** [comment]
Closing issue, since it's fixed.
