### ISSUE TITLE
How can I find the datas there are in local but  has not been synchronized to the server?

### ISSUE THREAD

**Issue by vampire02170** [forcedotcom/SalesforceMobileSDK-iOS#1504]
How can I find the datas there are in local but  has not been synchronized to the server?Without network created data, to prompt that have not synchronous data when I logout，But how do I know if there is not synchronous data? thanks!

**Comment by wmathurin** [comment]
Please use this forum only to post known issues/bugs with the Mobile SDK. For other queries, please post on our Google+ community here (https://plus.google.com/communities/114225252149514546445).
