### ISSUE TITLE
Getting "Insufficient Privileges" error screen during Login.

### ISSUE THREAD

**Issue by vkrychun** [forcedotcom/SalesforceMobileSDK-iOS#1505]
SalesforceMobileSDK-iOS v.3.2.2 
Sometime during login  with correct credentials we get "Insufficient Privileges" error. It's not reproducible permanently and happens from time to time.  One way to reproduce the issue explicitly, is waiting on the Login screen more than 20 min, and than enter credentials and try to submit. After that such error screen will definitely appear. It's not usual use case, but sometime it  happens even right after submitting credentials.

BTW. Same issue is reproducible with SalesforceMobileSDK-Android.

**Comment by vpetrovych** [comment]
Seems to be happening quiet consistently when you wait for some period of time on login screen. If I were to guess, I'd say session is timed out.

**Comment by huminzhi** [comment]
@vpetrovych I tried the step on sample app, so after a long period and login, I see this error: "You didn't complete the approval process before it expired. Please try again."
This is a correct error message, it seems in your app, the correct error message doesn't show up for some reason..

**Comment by huminzhi** [comment]
closing this issue as it seems working correctly in sample app.
