### ISSUE TITLE
How to launch deferred login

### ISSUE THREAD

**Issue by rachelleTRP** [forcedotcom/SalesforceMobileSDK-iOS#1506]
Hello, I'm trying to defer login so that it launches the salesforce login page on a button press. 

https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/salesforce_sdk_manager_ios.htm

It says in the above in the authenticateAtLaunch section that "At the appropriate time, send the authenticate message to SalesforceSDKManager to initiate authentication."

How to do this from react native js code?

**Comment by wmathurin** [comment]
It's done in unstable.
It's demonstrated in the sample app here: https://github.com/wmathurin/MyUserPicReactNative/
The key changes are here: https://github.com/wmathurin/MyUserPicReactNative/pull/3/files
