### ISSUE TITLE
bypass the PIN code security issue

### ISSUE THREAD

**Issue by kellianderson32** [forcedotcom/SalesforceMobileSDK-iOS#1507]
Steps to reproduce:
1.Enable touch id on device
2. Navigate to app and enter pin code
3. Wait for session timeout
4. Open the app
5. You will be asked to verify pin code or use touch id
6. Touch home button to switch to home screen
7. Go to the app again
8. App is re-opened and pin code is not requested﻿

**Comment by kellianderson32** [comment]
Looks like this got labeled a bug. Do you have any timeframe on fixing it?

**Comment by bhariharan** [comment]
@kellianderson32 Not at this time. We will take a look and post updates here.

**Comment by huminzhi** [comment]
@kellianderson32 May I know if you are reproducing this issue with those steps on our sample app(s)?
I am trying to reproduce this with our sample apps: SmartSyncExplorer and SmartSycnExplorerHybrid, however, cannot, those apps always asking me for passcode or touch ID (to use touch ID, I need to tap the button so the touch ID would not be automatically sent to the app.. we are wondering if in your code, the touch ID is somehow passed through to the app so it's got unlocked..

**Comment by huminzhi** [comment]
The issue is fixed in build:MobileSDK.iOS.4.2

**Comment by kellianderson32** [comment]
Is the new build available yet? If so where can I find it?

**Comment by bhariharan** [comment]
@kellianderson32 This is not a bug. On step 6 when home button is touched, touch ID is activated which unlocks PIN code.
