### ISSUE TITLE
Unable to add a Custom Login host programatically

### ISSUE THREAD

**Issue by rajishere** [forcedotcom/SalesforceMobileSDK-iOS#1512]
We have a requirement to redirect the login page to our login provider and allow users to switch login hosts between Production, SandBox and Custom on need basis. This was possible in earlier SDK with app respecting the login host chosen in the settings and an ability to have a default custom URL. This is dropped in new SDK. Even though we could have a default url on initial launch, this is lost when user taps on the settings icon on top right of login page. After that user has to type in the custom login host url which is not a right way.

After looking at the SDK we see that if SFSDKLoginHost and SFSDKLoginHostStorage are made public under SalesforceSDKCore we could use below code to add a login host programatically and avoid user having to type it and make mistakes

In App Delegate (preferably in did finish launch)
```
{
...
[self checkAndAddLoginHost];
...
}

- (void)checkAndAddLoginHost{
    NSString *customInstance = @"custominstance.my.salesforce.com";
    SFSDKLoginHost *loginHost = [[SFSDKLoginHostStorage sharedInstance]loginHostForHostAddress:customInstance];
    if(!loginHost){
        SFSDKLoginHost *systemLoginHost = [SFSDKLoginHost hostWithName:@"Custom" host:customInstance deletable:NO];
        [[SFSDKLoginHostStorage sharedInstance]addLoginHost:systemLoginHost];
    }
}
```
Please make those two headers public or give a way to do something similar

**Comment by kchitalia** [comment]
@rajishere What version of the SDK are you using? The latest version on the unstable branch has these two headers exposed as public headers.
One other option to consider is to add your custom host in the info.plist.

**Comment by rajishere** [comment]
@kchitalia thank you, if these are exposed, then we can wait till the next stable version is out and upgrade. Reg. custom host in plist, We had added that but that page is lost when user clicks on settings icon on top right of login page and user is auto redirected to Production login page. 

Since the initial issue of adding a programmatic login host is resolved now, we should be able to close this
