### ISSUE TITLE
SOS with MobileSDK 

### ISSUE THREAD

**Issue by hari8815** [forcedotcom/SalesforceMobileSDK-iOS#1523]
I am working on SOS implementation in my Hybrid ios app. I have followed the instruction mentioned in the SOS developer guide https://developer.salesforce.com/docs/atlas.en-us.sos.meta/sos/getting_started_ios-adding_sos_into_another_app.htm. In mobile sdk the UIWebView designed in "SFHybridViewController" class which is not writable. So I have created a custom class and interface the  "SFHybridViewController" class. Then updated "setupRootViewController" method in  "AppDelegate+SalesforceHybridSDK" class to load my custom class "self.viewController = [[SOSview alloc] initWithConfig:(SFHybridViewConfig*)[SalesforceSDKManager sharedManager].appConfig];". Now the SOS feature working in my app. But the app every time presenting the login screen. Please help me to debug this issue.

**Comment by huminzhi** [comment]
Sorry to reply late. Are you still facing this issue with latest sdk?

**Comment by huminzhi** [comment]
@hari8815 so if I understand your question correctly, you want to disable oauth flow and directly go to your web app without authentication. Is it right? Otherwise, I think this login screen is expected and you can login a salesforce account with it.. Let me know.. thank you!

**Comment by huminzhi** [comment]
@bhariharan @kchitalia @khawkins Do you know if we have some flag to disable oauth flow?

**Comment by khawkins** [comment]
Yes.  Presuming your hybrid app doesn't need to authenticate to Salesforce right away, or at all—i.e. the hybrid local app case and/or the hybrid remote app case where you're not hosted on Salesforce—you can set the `shouldAuthenticate` configuration in your `bootconfig.json` file to `false`.  This should bypass authentication at app startup.

**Comment by kchitalia** [comment]
@hari8815 Please try the approach suggested by @khawkins. Closing this issue, please re-open if it still exists with our latest version(v 4.2)
