### ISSUE TITLE
Formula Fields

### ISSUE THREAD

**Issue by GoliathDeveloper** [forcedotcom/SalesforceMobileSDK-iOS#1524]
Hi There

with the IOS MobileSDK 4.1.1 i’m using a formula fields in my SObjectDataSpec is there a way of excluding those formula fields from the SObjectDataManager refreshRemoteData as its causing the error below, ive also attached screenshots of the data and dataspec classes:

2016-05-06 08:57:58:480 Paperless-App[2700:88813] ERROR|SFSmartSyncSyncManager|
Sync type:syncUp id:282 FAILED cause:Server call for sync up failed error:Error Domain=CSFNetworkErrorDomain Code=400 “
Unable to create/update fields: Project_Task_Description__c, Status_Description__c.
Please check the security settings of this field and verify that it is read/write for your profile or permission set.
" UserInfo={NSLocalizedFailureReason=INVALID_FIELD_FOR_INSERT_UPDATE, isAuthenticationFailure=false, NSLocalizedDescription=Unable to create/update fields: Project_Task_Description__c, Status_Description__c.
Please check the security settings of this field and verify that it is read/write for your profile or permission set., action=<SFRestAPISalesforceAction: 0x7fe5eef3a2a0, PATCH "/sobjects/TaskStatus__c/a0hD000000GDrv3IAD" (0.00)>}

![sobjectdata](https://cloud.githubusercontent.com/assets/2816987/15116853/e8547d32-15fc-11e6-98b8-213a6e2f978f.png)
![sobjectdataspec](https://cloud.githubusercontent.com/assets/2816987/15116854/e855098c-15fc-11e6-87c4-5508d5c95dee.png)

Thanks,

**Comment by wmathurin** [comment]
SObjectDataSpec lives in the sample application SmartSyncExplorer. In the same application look at SObjectDataManager. The updateRemoteDate is the method that sends data up to the server.

```objective-c
- (void)updateRemoteData:(SFSyncSyncManagerUpdateBlock)completionBlock {
    SFSyncOptions *syncOptions = [SFSyncOptions newSyncOptionsForSyncUp:self.dataSpec.fieldNames mergeMode:SFSyncStateMergeModeLeaveIfChanged];
    [self.syncMgr syncUpWithOptions:syncOptions soupName:self.dataSpec.soupName updateBlock:^(SFSyncState* sync) {
        if ([sync isDone] || [sync hasFailed]) {
            completionBlock(sync);
        }
    }];
}
```
It calls "syncUp" passing in a SFSyncOptions that uses all the fields from the SObjectDataSpec.
If some fields are not writable, they should not be targeted by the SFSyncOptions.
In your application, the method that does the same work as the updateRemoteData should be passed a subset of the fields from the SObjectDataSpec (the ones you actually want/can change).

**Comment by GoliathDeveloper** [comment]
can you please provide an example as the response given is not clear.
