### ISSUE TITLE
use_frameworks! in Podfile shouldn't break React-Native integration

### ISSUE THREAD

**Issue by ivanbogdanov** [forcedotcom/SalesforceMobileSDK-iOS#1525]
steps to reproduce:
* run latest 'forceios create' with react_native template
* test it:  should run smoothly
* add  use_frameworks! to the project Podfile
* run 'pod update'
* result: the project doesn't compile

**Comment by wmathurin** [comment]
Fixed in upcoming release (see linked pull request above).
