### ISSUE TITLE
SFAuthenticationManager crashing when logging out

### ISSUE THREAD

**Issue by DarkRockman** [forcedotcom/SalesforceMobileSDK-iOS#1529]
An application which uses the Salesforce SDK v4 is crashing whenever the user is trying to log out of the application, as per the Xcode debugger the crash originates at class SFAuthenticationManager ln 444 (EXC_BAD_ACCESS code=1) when trying to enumerate delegates for broadcasting logout messages.

**Comment by wmathurin** [comment]
We believe this issue was fixed in 4.1.1
Please try with 4.1.1 and let us know if you still have the problem.

**Comment by DarkRockman** [comment]
While trying to update to latest SalesforceSDK (currently v4.1.2) Im no longer able to compile my project because the SalesforceSDKCore cant be compiled (specifically Pods/SalesforceSDKCore/libs/SalesforceSDKCore/SalesforceSDKCore/SalesforceSDKCore.h:30:9: 'SalesforceSDKCore/NSArray+SFAdditions.h' file not found)

The update was performed via the podfile adding a version specifier within the Salesforce SDK components (~> 4.1.2), any other advice I should follow up?

**Comment by wmathurin** [comment]
We are not publishing our spec to Cocoapods anymore. Instead, we maintain separate specs for each our of frameworks here. We will update our Specs repo every release.

For more information, please look at:
https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/ios_cocoapods.htm

Make sure your podfile is looks like the one in the documentation linked above.

**Comment by DarkRockman** [comment]
I have created a new project as a test with the forceios tool using type native_swift, the project, being unmodified also is unable to compile correctly, is this a different bug?

<img width="257" alt="screen shot 2016-05-12 at 8 04 51 am" src="https://cloud.githubusercontent.com/assets/3934741/15216812/3ce8527e-181e-11e6-9c13-04d2f46673f7.png">

**Comment by wmathurin** [comment]
We are not seeing the issue here. Are you sure you are running the latest version of forceios?

Can you try
```
forceios version
```
And make sure you are running on the latest version (4.1.2).
If you are not running 4.1.2, please update by doing:
```
sudo npm -g install forceios@4.1.2
```
