### ISSUE TITLE
Cannot create task from nil request！

### ISSUE THREAD

**Issue by vampire02170** [forcedotcom/SalesforceMobileSDK-iOS#1534]
When in the absence of the network, add and remove the same data at the local, then open the network, synchronous data, the program will crash, an error message:Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Cannot create task from nil request'，How to deal with this problem?

**Comment by huminzhi** [comment]
probably do a nil check before create task?

**Comment by kchitalia** [comment]
@vampire02170 Closing this issue.
