### ISSUE TITLE
.xcodeproj file format is too old

### ISSUE THREAD

**Issue by ivanbogdanov** [forcedotcom/SalesforceMobileSDK-iOS#1544]
Xcode 6.3-compatible is preferable: for better compatibility with build scripts. Right now it's using 3.2-compatible.

**Comment by bhariharan** [comment]
@ivanbogdanov All the sample apps and library projects in this repo have ```Xcode 7``` minimum requirement.

**Comment by bhariharan** [comment]
Done [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1546).
