### ISSUE TITLE
Is it possible to have SalesforceMobileSDK-iOS and SalesforceMobileSDK-Android in Single project?

### ISSUE THREAD

**Issue by manish-metacube** [forcedotcom/SalesforceMobileSDK-iOS#1553]
Hi all, 

We have developed an application using salesforce Mobile SDK. Currently we are looking to run same codebase for android as well. On looking on documentation it looks forceios is specifically creates app for ios and uses SalesforceMobileSDK-iOS. Can I simply add android platform and it will let run the app? or do i need to create separate project with forcedroid?

How i can have same mobilesdk shared for both?

**Comment by rwhitley** [comment]
Hi Manish,

For hybrid apps you can run cordova platform add with either a forceios or forcedroid app to add the opposing platform. For your case, the cordova plugin will create a Gradle project in the platforms/android folder. Import that folder into Android Studio to run the app.

Please use the SalesforceMobileSDK Google+ community for support questions. We use GitHub issues only to track Mobile SDK bugs.

Thanks.
