### ISSUE TITLE
After Upgradation to latest mobile SDK, SmartStore failed

### ISSUE THREAD

**Issue by ravish1234** [forcedotcom/SalesforceMobileSDK-iOS#1572]
When upgraded my SalesforceApp with latest mobile SDK, SALESFORCE_MOBILE_SDK_VERSION = "4.1.0", SmartStore failed while registering for soup. Below are the logs.

WARNING|SFSmartStore|sharedStoreWithName:user: Cannot create shared store with name 'defaultStore' for nil user. Did you mean to call [SFSmartStore sharedGlobalStoreWithName:]?
INFO|SFCrypto|Base app identifier not configured. Creating a new value.
INFO|SFCrypto|Saving the new base app identifier to the keychain.
Crypto|Successfully created a new base app identifier and stored it in the keychain.
WARNING|SFSmartStore|sharedStoreWithName:user: Cannot create shared store with name 'defaultStore' for nil user. Did you mean to call [SFSmartStore sharedGlobalStoreWithName:]?
TIMING com.salesforce.smartstore:pgSoupExists: 68ms
WARNING|SFSmartStore|sharedStoreWithName:user: Cannot create shared store with name 'defaultStore' for nil user. Did you mean to call [SFSmartStore sharedGlobalStoreWithName:]?
TIMING com.salesforce.smartstore:pgRegisterSoup: 5ms
ERROR: TIMING com.salesforce.smartstore:pgRegisterSoup failed

**Comment by bhariharan** [comment]
@ravish1234 Looks like you're trying to initialize ```SmartStore``` without a valid user account:

```
WARNING|SFSmartStore|sharedStoreWithName:user: Cannot create shared store with name 'defaultStore' for nil user. Did you mean to call [SFSmartStore sharedGlobalStoreWithName:]?
```

**Comment by ravish1234** [comment]
I am simply registering soup after user authentication which was working well in previous versions.

function registerSoup(soupName, indexes, successHandler, errorHandler) {
    checkIfSoupExists(soupName, function(param) {
        if (param) {
            clearSoup(soupName, function() {
                smartstore().alterSoup(soupName, indexes, true, successHandler, errorHandler);
            }, errorHandler);
        } else {
            smartstore().registerSoup(soupName, indexes, successHandler, errorHandler);
        }
    });
}
function checkIfSoupExists(soupName, successHandler, errorHandler) {
    smartstore().soupExists(soupName, successHandler, errorHandler);
}
var smartstore = function() {
return cordova.require("com.salesforce.plugin.smartstore");
};

Here I am building my old Salesforce App source code with latest cordova version 6.2.0 on platform ios@3.9.2 in xcode 7.3.

**Comment by ravish1234** [comment]
Hi Team,

Please do not close the issue unless proper solution is provided.

Thanks,
Bhavna Ravish

**Comment by bhariharan** [comment]
@ravish1234 What version of ```Mobile SDK``` did you upgrade from? Have you attempted to debug the plugin code to see why user is nil?

**Comment by ravish1234** [comment]
Version is SALESFORCE_MOBILE_SDK_VERSION = "2.3.0";

In our App, Salesforce login page is launched through Appbrowser Plugin. And only after user authentication and received access token, smartstore is accessed. And user authentication is happening successfully then how come smartstore is getting nil user. 

Can you please let me know in what scenario this can happen?

**Comment by bhariharan** [comment]
@ravish1234 ```Mobile SDK 2.3.0``` is almost 3 years old and unsupported at this point. A lot has changed since then, especially the way we persist encryption keys (we now use ```Keychain``` to store the encryption key). There are 2 recommended options:

* Generate a new app using the latest ```Mobile SDK``` and put your web assets in the new container.
* Do a step-by-step upgrade one version at a time, since we have documented upgrade steps from each version to the next.

If you see issues on runtime upgrades, you might need to add an upgrade step to migrate your data to the new structure. We don't support direct upgrades from much older versions, unfortunately.
