### ISSUE TITLE
Warning: Cannot create shared store with name 'defaultStore' for nil user

### ISSUE THREAD

**Issue by ravish1234** [forcedotcom/SalesforceMobileSDK-iOS#1576]
I am getting below warning, when I am trying to build the old Salesforce Hybrid App with latest SDK on xcode 7.3 . The App was working fine with older versions but giving warnings and then errors with latest versions. Please comment.

WARNING | SFSmartStore|sharedStoreWithName:user: Cannot create shared store with name 'defaultStore' for nil user.  Did you mean to call [SFSmartStore sharedGlobalStoreWithName:]?

**Comment by bhariharan** [comment]
Duplicate of #1572.
