### ISSUE TITLE
SFOAuthCoordinator:  - (void)stopRefreshFlowConnectionTimer throwing Exception

### ISSUE THREAD

**Issue by mattlacey** [forcedotcom/SalesforceMobileSDK-iOS#1580]
I've been completely unable to reproduce this, but some of our end users are experiencing crashes, and the majority of the crashes according to Crashlytics are in SFOAuthCoordinator.m, specifically in `stopRefreshFlowConnectionTimer`.

The exception is this:
> Fatal Exception: NSDestinationInvalidException *** -[SFOAuthCoordinator performSelector:onThread:withObject:waitUntilDone:modes:]: 

And is apparently caused by the thread `refreshTimerThread` being killed before the `invalidateRefreshTimer` message is processed by the following line:

    [self performSelector:@selector(invalidateRefreshTimer) onThread:self.refreshTimerThread withObject:nil waitUntilDone:YES];

From looking at the code I can't see a cause for this, and I'll keep trying to reproduce myself, but is there any safety mechanisms that could be put in place here?

**Comment by kchitalia** [comment]
What version for the sdk is the app using?

**Comment by mattlacey** [comment]
Hey Kunal, I'm specifying 4.1.0 in my podfile.

**Comment by mattlacey** [comment]
Bit more context:

![screen shot 2016-06-14 at 11 54 53 am](https://cloud.githubusercontent.com/assets/1256283/16028881/14596ad2-3227-11e6-92c8-83e414dbc9fa.png)

[The only other reference I can find online is here](https://plus.google.com/+MichaelSelevan/posts/Ab6itJbMsDT) where the poster indicated issues with making calls to authenticate in quick succession. Looking through the SDK code there seem to be mechanisms in place to deal with this but somehow it must be failing for our users.

The failures are happening a lot in an environment where there is a large amount of user switching taking place.

**Comment by mattlacey** [comment]
For what it's worth I've thrown a try/catch around the the line that sends a the stop message to the timer thread and that's not had any major repercussions. Given that the timer's thread is being killed anyway and it's just to stop it this doesn't seem totally unreasonable, but I'm still unable to determine the real cause of it.

**Comment by kchitalia** [comment]
@mattlacey We have not been able to reproduce this on our side. Closing out this issue.

**Comment by eescamilla** [comment]
I am still seeing this issue in Salesforce 4.3.0 

![image](https://cloud.githubusercontent.com/assets/7854174/24871469/87f9de84-1dce-11e7-862d-cc6126842322.png)

Line 900 points to the same as mentioned by @mattlacey 
![image](https://cloud.githubusercontent.com/assets/7854174/24871509/a6b84e32-1dce-11e7-8a20-ae51861289fa.png)

Will implement what @mattlacey's did but was there ever a solution from the Salesforce side?

**Comment by khawkins** [comment]
> was there ever a solution from the Salesforce side?

In a roundabout way.  We took out the timer entirely in 5.1, once we verified that the underlying timeout settings bugs in Cocoa had been rectified, and the standard timeout settings were being honored.  So going forward, there won't be a timer anymore, which should solve this problem.

**Comment by sgoldberg-sfdc** [comment]
See https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1969/files

**Comment by eescamilla** [comment]
@khawkins @sgoldberg-sfdc thanks for both of your replies! I see the PR was merged into dev branch which I believe @khawkins mentioned will be eventually merged into Master as 5.1 release. Do you guys have an ETA for 5.1? We have an upcoming release and am trying to figure out which branch we will point to on our next release.

**Comment by bhariharan** [comment]
5.1 is slated for the end of this month. #safeharbor

**Comment by eescamilla** [comment]
@bhariharan Thanks!
