### ISSUE TITLE
Is the incremental synchronization synchronous data?

### ISSUE THREAD

**Issue by liuyingjun** [forcedotcom/SalesforceMobileSDK-iOS#1583]
I am using  SalesforceMobileSDK-iOS 4.1.1 version of the native，Using refreshRemoteData synchronization method，What is the method incremental synchronization or full amount synchronization?Thank you very much, very urgent!

**Comment by bhariharan** [comment]
This forum is for know bugs or issues in ```Mobile SDK``` code. For other questions or issues, please post on our Google+ community [here](https://plus.google.com/communities/114225252149514546445).
