### ISSUE TITLE
Cannot add a Custom Login host programmatically

### ISSUE THREAD

**Issue by MishchanchukA** [forcedotcom/SalesforceMobileSDK-iOS#1591]
In earlier versions of SDK is possible to switch login hosts between Production, SandBox and Custom. But in latest version of SDK this possibility was dropped. 
I found that we can add custom host in SFSDKLoginHostStorage, but this class isn't public and we can't use it. 
Will you make this class public? Or maybe you can recommend some other way to add custom host?
I know about SFDCOAuthLoginHost key in plist for default host, but we need to add custom host to list of hosts.

**Comment by kchitalia** [comment]
@MishchanchukA Can you please try the latest code on our unstable branch, the SFSDKLoginHostStorage class is part of the public headers in that branch.

**Comment by bhariharan** [comment]
@MishchanchukA ```SFDCOAuthLoginHost``` key can be used to add a custom host to the list of hosts. It so happens that this custom host also becomes the default host. What's the exact use case?

**Comment by MishchanchukA** [comment]
@bhariharan when I added custom host to plist file with SFDCOAuthLoginHost key I can't see this host in list with hosts. And in this case when I open the hosts list, the first host (Production) is automatically selected and I have not possibility to select back custom host automatically. I need to add this host manually and then select it

**Comment by MishchanchukA** [comment]
@kchitalia thank you, this class is public in unstable branch. Do you plan keep this class as public in next release?

**Comment by kchitalia** [comment]
Yep, this class will be in the public headers going forward.
