### ISSUE TITLE
PIN entry issues in iOS SDK 4.1.2

### ISSUE THREAD

**Issue by carolinerawsonfairsailcom** [forcedotcom/SalesforceMobileSDK-iOS#1595]
We are seeing various issues with PIN entry in iOS SDK 4.1.2. These issues may be related to each other, so I am listing them together rather than seperately:

1)	When the app has been in the background and is then brought to the foreground, then PIN entry is never requested, even if it was in the background for longer than the PIN timeout. Note that when the Home button is pressed, the finger programmed for Touch ID is not used.
2)	Sometimes (maybe 10% of the time) when entering the correct PIN, the Done link does not work and the app does not open. This seems to happen only after lots of successful testing. Is there some kind of limit on the number of times the PIN can be entered?
3)	We also see that after the PIN entry screen being shown lots of times successfully (> 50 times), then we get a run of tests where the PIN entry screen is not shown after timeout (> 20 times).  Then after the string of failures, we see the expected behaviour again, and the PIN entry screen is shown once again. Is there some kind of limit on the number of times the PIN entry screen will be shown?
4)	Sometimes, after scenario 2 has happened (unable to open the app by clicking Done after entering the correct PIN) then if we go to Home and open the app again, there is no prompt for the PIN. Note that touch ID was not enabled in this scenario.

**Comment by huminzhi** [comment]
@carolinerawsonfairsailcom thank you for your feedback. so are you seeing these issues in our sample app or your app? Are you NOT seeing those before 4.1.2?

**Comment by carolinerawsonfairsailcom** [comment]
@huminzhi We are seeing these issues in our app. How do we get hold of your sample app? We would be happy to try the same scenarios there as well. We were always seeing issues with PIN code entry / touch ID, before 4.1.2 as well, but it took a while doing extensive testing to come up with the list of the 4 issues that I posted here, that's the only reason we didn't post them before. Some of the issues can be difficult to reproduce (2,3, and 4).

**Comment by huminzhi** [comment]
The issue is fixed or solved in latest build.

**Comment by carolinerawsonfairsailcom** [comment]
@huminzhi What is the version of the latest build? And when will it be available?

**Comment by huminzhi** [comment]
@carolinerawsonfairsailcom it turns out the issue is related to "SnapshotView", if you don't really use this feature, you can try to disable it (set useSnapshotView to NO) and see if it solves the issue.
On the other hand, I are fixing it in next release.. I cannot tell exactly when, but should be within a month. Thank you!

**Comment by huminzhi** [comment]
The issue is fixed or solved in latest build.

**Comment by carolinerawsonfairsailcom** [comment]
@huminzhi I tried to disable the Snapshot View, but could only find details relating to native app development https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/salesforce_sdk_manager_ios.htm Our app is a hybrid app. Is it possible to disable SnapShot view for a hybrid app? Also, will the fix that's in 4.2 apply to hybrid apps? Thanks
