### ISSUE TITLE
SDK fails to compile in XCode 8

### ISSUE THREAD

**Issue by mgetzbw** [forcedotcom/SalesforceMobileSDK-iOS#1596]
Currently the SDK fails to compile in XCode 8 due to usages of `objc_unretainedPointer` which is deprecated and removed, they suggest replacing it with `(__bridge void*)(self)`

**Comment by bhariharan** [comment]
@mgetzbw Thanks for reporting! We are aware of this. We're not certified on ```XCode 8``` or ```iOS 10``` yet.

**Comment by mgetzbw** [comment]
@bhariharan I'm going to do a quick test now with Find/Replace to see if that actually fixes the issue, I'll report my results

**Comment by gauravkheterpal** [comment]
+1

@mgetzbw @bhariharan - This is the first thing I tried after downloading XCode 8 at WWDC yesterday :) 

I hope there's a plan to quickly ensure the next version of SDK is compatible with XCode 8/ iOS 10.

**Comment by bhariharan** [comment]
Typically, we won't certify ourselves as working on ```Xcode 8``` or ```iOS 10``` until it goes GA.

**Comment by mgetzbw** [comment]
I figured, it looks like this fix is backwards compatible... so there should be no harm in using it prior, and telling people to use XCode 8 at their own risk. It seems to be working

**Comment by bhariharan** [comment]
Nice! Could you send us a pull request against ```unstable```?

**Comment by rgoldiez** [comment]
I grabbed the very latest unstable to get this support for xcode 8 / ios 10 and run into this runtime error....

![image](https://cloud.githubusercontent.com/assets/10797610/16808549/8f2d0efe-48e2-11e6-8603-ecf02cadcc4d.png)

**Comment by mgetzbw** [comment]
@rgoldiez iOS10 and xCode8 are unsupported at the moment, the commits I've done so far were for code compatibility and swift 3 support prep. Please check to see if there is a radar around the issue you're running into, if not create a test case and see if you can't report it to Apple. In this case I don't think the sdk is the problem: https://forums.developer.apple.com/thread/4743

**Comment by rgoldiez** [comment]
@mgetzbw - Bummer but thanks for the info.
