### ISSUE TITLE
Mobile App- Hard close and reopen doesn't prompt for touch ID

### ISSUE THREAD

**Issue by carolinerawsonfairsailcom** [forcedotcom/SalesforceMobileSDK-iOS#1625]
We'd like clarification - is the following behaviour expected or is it a bug? (seen in 4.1.2)
Touch ID enabled 
Login to the app
Kill the app
Click on the app button to launch it
Expected: Option to enter passcode and touch ID should be shown
Actual: Only the option to enter passcode is shown.

**Comment by bhariharan** [comment]
That's expected behavior. The pass code needs to be entered when the app is launched for the first time.

**Comment by carolinerawsonfairsailcom** [comment]
@bhariharan Just to clarify, the issue is that ONLY the passcode is requested, not the touch ID. We would expect to see the option to enter either passcode or touch ID (the same as when the PIN timeout is triggered). This doesn't only happen the first time the app is launched, but any time the app is closed and then reopened. Is it still expected behaviour?

**Comment by bhariharan** [comment]
Yes, I meant anytime the app is closed and restarted. We need the pass code stored in memory to compute the decryption key. Hence touch id is not shown when the app is restarted. This is expected behavior.
