### ISSUE TITLE
SFLogger issue when run the tests

### ISSUE THREAD

**Issue by hiralnaik** [forcedotcom/SalesforceMobileSDK-iOS#1675]
Please fill out the following details:

1. Version of Mobile SDK Used: 
4.2.0
2. Issue found in Native App or Hybrid App:
Own app
3. OS Version: 
iOS 9.3
4. Device: 
iPhone 6, iPad Air
5. Steps to reproduce:
Install latest SDK 4.2.0
Made necessary changes to the pod file
pod install
run the project
<img width="618" alt="screen shot 2016-08-01 at 12 29 52 am" src="https://cloud.githubusercontent.com/assets/7863227/17286640/b6f90338-577f-11e6-8965-6340d0e1629f.png">

6. Actual behavior:
7. Expected Behavior:
8. Error Log:
One of the two will be used. Which one is undefined.

**Comment by huminzhi** [comment]
@hiralnaik seems you should avoid define classes of same name in both unit test and its app.
http://stackoverflow.com/questions/6149673/class-foo-is-implemented-in-both-myapp-and-myapptestcase-one-of-the-two-will-be

**Comment by hiralnaik** [comment]
@huminzhi I resolved the error "One of the two will be used. Which one is undefined error." But I am still seeing this error. It was my mistake that I said the crash and log is related to each other. But it is completely different. It is still crashing the app on the same spot again again.

**Comment by huminzhi** [comment]
@hiralnaik may I know how you use SFLogger? It seems working ok in our sample Apps and unit tests, so wondering

**Comment by hiralnaik** [comment]
@huminzhi  I was about to response today at the end of the day.  I fixed it in my project. So we can close this issue. When I upgraded salesforce SDK to latest one and it seems working fine. 

Thanks for looking into this issue.

**Comment by bhariharan** [comment]
Thanks @hiralnaik!
