### ISSUE TITLE
Source should be provided for dist/SalesforceCommonUtils

### ISSUE THREAD

**Issue by turon** [forcedotcom/SalesforceMobileSDK-iOS#168]
We'd like to compile the SFRestAPI directly into our app, and be able to single-step through the implementation to debug.  Most source files are provided except the implementations of SalesforceCommonUtils:

NSData+SFAdditions.h		SFMD5.h
NSDictionary+SFAdditions.h	SFPadPickListViewController.h
NSObject+SFBlocks.h		SFPathUtil.h
NSString+SFAdditions.h		SFPhonePickListViewController.h
NSString+SFPathAdditions.h	SFPickListViewController.h
SFCoverView.h			SFTestContext.h
SFDateUtil.h			UIActionSheet+SFBlocks.h
SFDeviceInfo.h			UIAlertView+SFBlocks.h
SFEncryptionManager.h		UIBarButtonItem+SFAddtions.h
SFGradientView.h		UIDevice+SFHardware.h
SFKeychainItemWrapper.h		UILabel+SFAdditions.h
SFLogger.h

Also, it's weird that these headers are distributed inside a zip, and not as part of the github sources.  It'd be nice if the SDK were distributed as a clean set of source and headers that you can just drag into your XCode app, compile, and run.  Getting the basic sample app is pretty hard to build.  Typically, you just clone the github repo, double click on the xcode project, and hit the play button.

**Comment by jclark-dot-org** [comment]
+1.  Difficult to diagnose login issues & contribute without the ability to trace into things like NSURL+SFAdditions.

**Comment by fobin** [comment]
+1

**Comment by seriyvolk83** [comment]
In Xcode 7.0: ld: '/Users/*****/SalesforceCommonUtils/libSalesforceCommonUtils.a(NSData+SFAdditions.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bhariharan** [comment]
We will be working on distributing sources for ```SalesforceCommonUtils``` in the near future.

@seriyvolk83 We have added support for ```BITCODE``` in our ```unstable``` branch. [Here](https://rwhitleysfdc.wordpress.com/2015/10/05/ios-9-bitcode-support-and-salesforce-mobile-sdk/) is a post with more information.

**Comment by bhariharan** [comment]
We have moved the dependent sources from ```SalesforceCommonUtils``` into ```SalesforceSDKCommon``` in our ```unstable``` branch [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1252). Sources should now be available for every module in the Mobile SDK.

**Comment by khawkins** [comment]
:+1: :fireworks: :tada:
