### ISSUE TITLE
Crashing on CSFAction class looking for self.timingValues[endTime]

### ISSUE THREAD

**Issue by oolufemi** [forcedotcom/SalesforceMobileSDK-iOS#1702]
Please fill out the following details:

1. Version of Mobile SDK Used: 4.2
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 9.3
4. Device: Simulator
5. Steps to reproduce: It occurs sometimes on triggering: [[SFRestAPI sharedInstance] send:request delegate:delegate]. There is really no pattern of note. Other times it works fine allwoing the SFRequest to go through.
6. Actual behavior: as above
7. Expected Behavior: as above
8. Error Log: I have attached an image
![screen shot 2016-08-22 at 11 39 17](https://cloud.githubusercontent.com/assets/6328561/17852330/ae8453d4-685e-11e6-988d-9c15ae9bfeeb.png)

**Comment by huminzhi** [comment]
@oolufemi I tried very hard to reproduce, however, not able to.. Wondering if it's also happening on real devices?

**Comment by oolufemi** [comment]
@huminzhi I haven't experienced it on a real devices. But we have done limited testing so far.

**Comment by huminzhi** [comment]
@oolufemi I have a hard time to reproduce this issue.. May I close this issue for now? But feel free to reopen it if you get reproduce steps.. Thanks!
