### ISSUE TITLE
Downloadable Docset for any version beyond 4.0.0?

### ISSUE THREAD

**Issue by idStar** [forcedotcom/SalesforceMobileSDK-iOS#1706]
Looking at Cocoapods documentation for the native iOS SDK, this is the latest:

http://cocoadocs.org/docsets/SalesforceMobileSDK-iOS/4.0.0/

This is where documentation tools like [Dash](https://kapeli.com/dash) look to get the latest documentation. However, even in Dash, the full set of classes are not getting loaded. Perhaps the docset is not constructed in a standard way?

Further, it would be good to rev the docset to 4.1, 4.2, 4.3 etc. when these release tags get made, even if the underlying API hasn't changed.

In Dash, this is all I see available:

![dash](https://cloud.githubusercontent.com/assets/177464/17982347/73389cbc-6ad5-11e6-893e-debec0e06380.jpg)

On the Cocoapods site, I see more classes, but the version number is out of date:

![cocoadocs_org_-_salesforcemobilesdk-ios_reference_and_salesforce_mobile_sdk_guide_v4_3_pdf__page_68_of_407_](https://cloud.githubusercontent.com/assets/177464/17982433/cd662c2c-6ad5-11e6-85d6-a49a72a0835b.jpg)

Not sure why the docset is not formed well enough to be correctly rendering in mainstream documentation viewer tools like Dash.

**Comment by bhariharan** [comment]
@idStar We don't publish to `cocoapods.org` anymore. Our latest pod specs are available [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs).

**Comment by idStar** [comment]
Thanks @bhariharan. 

I am pulling in the latest cocoapods for the SF SDK from your forcedotcom specs repo, by virtue of listing it at the top of my Podfile before the cocoapods.org spec repo. 

However, it's not clear to me where to download the latest docset for version 4.3 that I could say, load into a tool like Dash.

Could you point me in the right spot? Thanks.

**Comment by bhariharan** [comment]
Our docs live [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS#documentation).

**Comment by idStar** [comment]
Thanks @bhariharan. I've bookmarked this for viewing in my browser. Do you guys by chance publish a downloaded docset version of this that we can install in local, native apps for offline access?

**Comment by bhariharan** [comment]
@idStar We don't, unfortunately.
