### ISSUE TITLE
Info : mac OS app

### ISSUE THREAD

**Issue by horatiu-potra-3pg** [forcedotcom/SalesforceMobileSDK-iOS#1708]
This is a info question. My team wants to make a desktop mac app and this app should communicate with salesforce. 

How can we make the login and other requests we need in order to send and get data from sales force.

Thank you!

**Comment by toddhalfpenny** [comment]
I would think this would be possible without the need for the Salesforce Mobile SDK.
One approach could be to build an app with [electron](http://electron.atom.io/) and [forcejs](https://github.com/ccoenraets/forcejs).

**Comment by bhariharan** [comment]
Please use our [Google+ community](https://plus.google.com/u/1/communities/114225252149514546445?cfem=1) for queries. This forum is reserved for known issues. To answer your question, most of our code is universal `Cocoa`, but there are parts that are mobile specific and may not work on `mac OS`. We don't officially support `mac OS`, nor have we tried it, so we don't know what issues you may run into.
