### ISSUE TITLE
iOS10 compatible version?

### ISSUE THREAD

**Issue by brad36** [forcedotcom/SalesforceMobileSDK-iOS#1732]
Can you advise (roughly) when you expect an iOS10 compatible version of the SDK to be released and which version number this will be?
Thanks

**Comment by bhariharan** [comment]
We will be taking a look at `iOS 10` compatibility soon. It should be a part of our `5.0` release, which is slated for close to the end of the year. #safeharbor

**Comment by brad36** [comment]
ok thanks
