### ISSUE TITLE
Cannot archive app with version 3.6

### ISSUE THREAD

**Issue by quoctc** [forcedotcom/SalesforceMobileSDK-iOS#1747]
Hi, i cant archive my app

1. Version of Mobile SDK Used: 3.6
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 8.2
4. Device:ipad
5. Steps to reproduce: cannot archive project
6. Actual behavior:
7. Expected Behavior:
8. Error Log:
Libs/SalesForceSDK/libs/SalesforceNetwork/SalesforceNetwork/SalesforceNetwork/Classes/Network/Action/CSFAction.m:64:54: Property 'credentials' cannot be found in forward class object 'SFUserAccount'
Libs/SalesForceSDK/libs/SalesforceNetwork/SalesforceNetwork/SalesforceNetwork/Classes/Network/Action/CSFAction.m:576:48: Property 'credentials' cannot be found in forward class object 'SFUserAccount'

Thanks for your helping!

**Comment by bhariharan** [comment]
@quoctc There is no `Mobile SDK v3.6`. Could you please check what version you're using?

**Comment by quoctc** [comment]
Hi, i dont know, could you please tell me where can i find the current version that i am using?

Thank and best regards.

**Comment by wmathurin** [comment]
It's defined in SalesforceSDKConstants.h

**Comment by quoctc** [comment]
Thank you so much!

I fixed it.

Best,
