### ISSUE TITLE
Salesforce Mobile SDK not compatible with IPv6-network

### ISSUE THREAD

**Issue by evifavaits** [forcedotcom/SalesforceMobileSDK-iOS#1758]
Please fill out the following details:

1. Version of Mobile SDK Used: 4.1.0
2. Issue found in Native App or Hybrid App: Hybrid app
3. OS Version: iOS 10
4. Device: iPad and iPhone (version not known)
5. Steps to reproduce: Connect on WIFI to an IPv6 network and open app
6. Actual behavior: app displays error message on launch, it shows message that you're not connected to the internet (see image below)
<img width="768" alt="attachment-4911081988400591634screenshot238" src="https://cloud.githubusercontent.com/assets/12133405/18868680/627e5360-84a9-11e6-843d-cfaca7710104.png">

7. Expected Behavior: app should be able to connect to an IPv6 network and should show login screen
8. Error Log: / 

Hi, 

We uploaded  a new version of an app that includes the SalesforceMobileSDK to the App Store and as you know or not apple always reviews the app before it is actually published on the stores. After the review we got a message from Apple saying that our app has been rejected, and this because it can't connect to an IPv6 network. 
After some researching I found the following in the apple developer library:
" Don’t Use IP Address Literals
Make sure you aren’t passing IPv4 address literals in dot notation to APIs such as getaddrinfo and SCNetworkReachabilityCreateWithName. " (see link: https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW1) 
The last one (SCNetworkReachabilityCreateWithName) is actually used in the SalesforceMobileSDK and to be more specific, in this file: SFSDKReachability.m.

Could you solve this issue by modifying the SFSDKReachability.m file and to not use SCNetworkReachabilityCreateWithName?

Thanks in advance! 

Evi Favaits

**Comment by bhariharan** [comment]
@evifavaits We have already updated our version of `SFSDKReachability` to be `IPv6` compliant (see latest version [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Common/SFSDKReachability.m)). This is available in our latest release, `4.3.1`. Please upgrade to `4.3.1` or grab our new version of `SFSDKReachability`.

**Comment by evifavaits** [comment]
Hi,

Did you change some other files to support IPv6? I've modified the SFSDKReachability.m and SFSDKReachability.h to be the latest versions and I've uploaded my app again to the app store but apparently Apple says it does not support IPv6. 

Thanks!
Evi

**Comment by bhariharan** [comment]
@evifavaits That should be it. There's nothing else in `Mobile SDK` that's specific to `IPv4` or anything related, for that matter. Do you know which file is being rejected?

**Comment by evifavaits** [comment]
@bhariharan No I don't know, I've asked them. Will keep you posted.
