### ISSUE TITLE
App crashes when store does not employ encryption

### ISSUE THREAD

**Issue by dfattlar** [forcedotcom/SalesforceMobileSDK-iOS#1760]
1. Version of Mobile SDK Used: 4.3.0, also seem to be present in 4.2.0
2. Issue found in Native App or Hybrid App: Hybrid - using ionic
3. OS Version: breaks in iOS 9.3.5, works in iOS 10
4. Device: iPhone/iPad
5. Steps to reproduce: 
   When building our ionic hybrid app from Xcode  --
   If running on iOS 9.3.5, the app crashed when trying to init the smartstore tables:

```
2016/09/27 20:31:25.772 TestApp[449:1607] DEBUG com.salesforce <SFSmartStore>: initWithName:user:isGlobal: defaultStore, user: 00D36000000rnTUEAY-00536000001iSQc-(null), isGlobal: 0
2016/09/27 20:31:25.773 TestApp[449:1607] INFO com.salesforce <SFSmartStoreUpgrade>: Migrating stores from legacy locations, where necessary.
2016/09/27 20:31:25.777 TestApp[449:6f0f] INFO com.salesforce <SFSmartStoreUpgrade>: Legacy SmartStore directory does not exist.  Nothing to do.
2016/09/27 20:31:25.777 TestApp[449:6f0f] INFO com.salesforce <SFSmartStoreUpgrade>: No legacy stores to migrate.
2016/09/27 20:31:25.777 TestApp[449:1607] INFO com.salesforce <SFSmartStoreUpgrade>: Updating encryption method for all stores, where necessary.
2016/09/27 20:31:25.786 TestApp[449:6f0f] INFO com.salesforce <SFSmartStoreUpgrade>: Number of stores to update: 1
2016/09/27 20:31:25.787 TestApp[449:1607] DEBUG com.salesforce <SFSmartStoreUpgrade>: ***Store 'defaultStore' currently does not employ encryption.***
```

If running on iOS 10, the build successfully passes through the initialization, and the app works:

```
2016-09-27 16:33:10.333659 TestApp[1126:226259] Updating encryption method for all stores, where necessary.
2016/09/27 20:33:10.335 TestApp[1126:1c03] INFO com.salesforce <SFSmartStoreUpgrade>: Number of stores to update: 1
2016-09-27 16:33:10.334810 TestApp[1126:226258] Number of stores to update: 1
2016/09/27 20:33:10.335 TestApp[1126:2503] INFO com.salesforce <SFSmartStoreUpgrade>: Store 'defaultStore' is already using the current encryption scheme.  Skipping.
2016-09-27 16:33:10.335361 TestApp[1126:226259] ***Store 'defaultStore' is already using the current encryption scheme.  Skipping.***
2016/09/27 20:33:10.345 TestApp[1126:1c03] DEBUG com.salesforce <SFSmartStore>: createLongOperationsStatusTableSql: CREATE TABLE IF NOT EXISTS long_operations_status (id INTEGER PRIMARY KEY AUTOINCREMENT, type TEXT, details TEXT, status TEXT, created INTEGER, lastModified INTEGER )
2016-09-27 16:33:10.345476 TestApp[1126:226259] createLongOperationsStatusTableSql: CREATE TABLE IF NOT EXISTS long_operations_status (id INTEGER PRIMARY KEY AUTOINCREMENT, type TEXT, details TEXT, status TEXT, created INTEGER, lastModified INTEGER )
2016/09/27 20:33:10.348 TestApp[1126:2503] DEBUG com.salesforce <SFSmartStore>: initWithName:user:isGlobal: defaultStore, user: -global-, isGlobal: 1 
```

The difference appears to be whether the **current encryption scheme** of the default store is used. Is this actually an iOS difference, or possibly a user setting?

**Comment by huminzhi** [comment]
@dfattlar sorry to reply late.  Just wonder if it happens to an upgrade path, does it still happen if you uninstall and reinstall the app on ios9.3?

**Comment by dfattlar** [comment]
@huminzhi Yes, same issue on fresh installs also.

**Comment by huminzhi** [comment]
@dfattlar it should be some setting as I am not able to reproduce this with any sample apps.. let me dig more to see what can be the setting... did you create the app through forceios create?

**Comment by huminzhi** [comment]
@dfattlar just to double confirm, the issues happens in ios9.3, but NOT ios10.0?
It seems to me some possibility vice versa... (there is some keychain issue with ios10.0, but ios9.3 should work)...

**Comment by dfattlar** [comment]
@huminzhi sorry for the delay, was busy at dreamforce. 
Yes, the app is definitely crashing in multiple iOS 9.3 instances, but is succeeding in multiple separate iOS 10 instances. I'll see if I can get one of the 9.3 instances upgraded to iOS 10 to check if that upgrade fixes their issue.

**Comment by dfattlar** [comment]
@huminzhi I followed up with a 9.3.1 user that was experiencing the crashing and had them upgrade to 10. The same app (not re-downloaded) began working immediately after upgrading to iOS 10.

**Comment by manjeetsharma** [comment]
Hi All,


I am facing almost same issue. The smartstore soups are getting registered but it crashes.It gives below error :

![screen shot 2018-04-17 at 8 12 52 pm](https://user-images.githubusercontent.com/10543360/38877194-c6f16b3e-427b-11e8-8013-fecc5ab1389b.png)
