### ISSUE TITLE
find: Salesforce/SalesforceMobileSDK-iOS/libs/SalesforceSDKCore: No such file or directory

### ISSUE THREAD

**Issue by CesarRN** [forcedotcom/SalesforceMobileSDK-iOS#1777]
Hello allo, 

I follow all this steps:

"
Open the Terminal App
cd to the parent directory where the repo directory will live
git clone https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git
After cloning the repo:

cd SalesforceMobileSDK-iOS
./install.sh
"

I clone into "Ejempos SDK Salesforce"

I open "SalesforceMobileSDK.xcworkspace", select SmartSyncExplorer target and press Build And Run.

I obtained an error.

Please fill out the following details:

1. Version of Mobile SDK Used: 4.3.1
2. Issue found in Native App or Hybrid App: Native \ SmartSyncExplorer
3. OS Version: iOS 10
4. Device: iPad and simulator
5. Steps to reproduce: Only Run the example, without changes
6. Actual behaviour: Error
7. Expected Behaviour: Run
8. Error Log:
usage: dirname path
find: Ejempos: No such file or directory
find: SDK: No such file or directory
find: Salesforce/SalesforceMobileSDK-iOS/libs/SalesforceSDKCore: No such file or directory

Can anyone help me?

Thanks.

**Comment by wmathurin** [comment]
What version of XCode are you using?

**Comment by CesarRN** [comment]
Hello wmathurin

Xcode - Version 8.0 (8A218a)   (I am using iOS 10)

Any idea?

Thanks!.

**Comment by wmathurin** [comment]
Mobile SDK 4.3 does not support Xcode 8 and/or iOS 10. Please use the latest from our unstable branch for Xcode 8 and/or iOS 10. This will be a part of our upcoming release.
