### ISSUE TITLE
Unable to launch the application in iOS 10 using Xcode 8,Swift 3

### ISSUE THREAD

**Issue by ksrvmahesh** [forcedotcom/SalesforceMobileSDK-iOS#1779]
Please fill out the following details:

1. Version of Mobile SDK Used:  4.3
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: iOS 10
4. Device: iPhone 6s
5. Steps to reproduce: 

- Use forceiOS create for creating the sample application.
- Created project isn't supporting the swift 3.0 syntax.
- Xcode 8 migrated the project supporting to swift 3.0
- Resolved few other compilation errors regarding syntax
- Launched the application.

6. Actual behavior: Application is unable to launch and crashing.
7. Expected Behavior: Application should run and salesforce test login screen should be visible
8. Error Log:  Attached below

[SalesforceLog.pdf](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/549019/SalesforceLog.pdf)

**Comment by bhariharan** [comment]
`Mobile SDK 4.3` does not support `Xcode 8` and/or `iOS 10`. Please use the latest from our `unstable` branch for `Xcode 8` and/or `iOS 10`. This will be a part of our upcoming release.
