### ISSUE TITLE
The certificate for this server is invalid. You might be connecting to a server that is pretending ..

### ISSUE THREAD

**Issue by manish-metacube** [forcedotcom/SalesforceMobileSDK-iOS#1785]
Please fill out the following details:

1. Version of Mobile SDK Used: 3.3
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: 9+
4. Device: iPhone 6
5. Steps to reproduce: Run app in MDM with custom host where certificate is not production ready 
6. Actual behaviour: It should run as expected
7. Expected Behaviour: Showing a popup that says. 

 "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “example.com” which could put your confidential information at risk.", 

8. Error Log:
Domain=NSURLErrorDomain Code=-1202 "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “example.com” which could put your confidential information at risk." UserInfo=0x14a730 {NSErrorFailingURLStringKey=https://example.com/, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSErrorFailingURLKey=https://example.com/, NSLocalizedDescription=The certificate for this server is invalid. You might be connecting to a server that is pretending to be “example.com” which could put your confidential information at risk., NSUnderlyingError=0x14a6c0 "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “example.com” which could put your confidential information at risk.", NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x14ec00>}

Hi All, 

We are running our app with the custom host using MDM. One of the issues reported is the certificate warning as mentioned above. This application is running on a closed network and we can not make changes on the server side.

Can we have some workaround to bypass this warning message using the mobile app? 

We can't upgrade SDK at this moment. 

I have googled it and found some related document but not sure where to put this changes. We do care that app might be rejected at apple's store if we use these non-public APIs.  

"http://stackoverflow.com/questions/11573164/uiwebview-to-view-self-signed-websites-no-private-api-not-nsurlconnection-i/15074358#15074358"
"http://stackoverflow.com/questions/6792213/ignoring-invalid-server-certificates-with-uiwebview"

It's very urgent. Any help is appreciated.  

Please let me know if you have any suggestions. 

@bhariharan 
@khawkins  any help?

Regards,
Manish Kumar

**Comment by bhariharan** [comment]
@manish-metacube This sounds like an issue with the custom host itself and the server presenting and invalid certificate. We don't control this on the client. We simply load the custom endpoint within `UIWebView` or `WKWebView` (in our latest release). My recommendation would be to fix the certificate on the server. Also, this forum is for known bugs/issues with `Mobile SDK`. Please use our `Google +` community for other queries.
