### ISSUE TITLE
UserAccount.plist file is removed from app library container automatically when data is stored and fetched from smartstore to associated watch app and when iPhone app is not running and device is locked

### ISSUE THREAD

**Issue by abinaya001** [forcedotcom/SalesforceMobileSDK-iOS#1834]
Please fill out the following details:

1. Version of Mobile SDK Used:  4.3.1
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: iOS 10 and Watch OS 3
4. Device: iPhone 5C
5. Steps to reproduce: 
   1. Have a iPhone and iWatch app.
   2.Have iPhone app is not running state and the device is locked.
   3. set the local notification. since the device is locked,local notification will be received to iWatch.
   4. Open the notification on iWatch.(When user opens the notification on iWatch, internally watch connectivity delegate method will be called on iPhone side)
   5.Launch iPhone app.
   5. User will be asked to login again as salesforce Sdk removes the useraccount.plist file from the app's library container. 
6. Actual behavior: User is asked to login the app every time connected app launches from not running state and user opens the notification from iWatch app.
7. Expected Behavior: User account file should be available even after user respond to the notification from iWatch app.
8. Error Log:
Nov 23 13:23:22 (CocoaLumberjack)[704] <Notice>: Could not retrieve user account data from '/var/mobile/Containers/Data/Application/4C4F582C-6869-44CE-A515-A44686CDB2E2/Library/{app bundle id}/00D36000000JflBEAS/00536000001pQxu/UserAccount.plist'
Nov 23 13:23:22(CocoaLumberjack)[704] <Notice>: Error deserializing the user account data: Error Domain=SFUserAccountManager Code=10002 "User account data could not be decrypted. Can't load account." UserInfo={NSLocalizedDescription=User account data could not be decrypted. Can't load account.}

Seems like there is a change in encryption/decryption key when session(session: WCSession, didReceiveMessage message: [String : AnyObject], replyHandler: ([String : AnyObject]) -> Void) method is called on iOS app when the app is not running and the device is locked.

Since encryption/decryption key is getting changed, user account.plist file is failed to get decrypted which leads the file getting deleted.

The application is in live now.  Many users are experiencing the issue due to which they are not able to use iWatch app itself.  Could you please look on the issue and update me ?

**Comment by trooper2013** [comment]
@abinaya001 Are you using Keychain Sharing & app groups?  You should take a look at [SmartSyncExplorer example](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/tree/unstable/native/SampleApps/SmartSyncExplorer) available in our **unstable** branch which uses our SDK  within extensions. This feature is available in our upcoming release (5.0) slated to be out there soon. The key to making it work along with keychain sharing and app groups, is to configure the SDK before you invoke the SDKManager.
```
[SFSDKDatasharingHelper sharedInstance].appGroupName = @"group.<app security group name>";
[SFSDKDatasharingHelper sharedInstance].appGroupEnabled = YES;
```

Meanwhile for 4.3.1 you could try to set the appropriate [Keychain Item Accessibility Constants](https://developer.apple.com/reference/security/1658642-keychain_services/1663541-keychain_item_accessibility_cons) for your app. By default we use the most secure mode for access to the keychain items.
e.g.
`[SFKeychainItemWrapper setAccessibleAttribute: kSecAttrAccessibleAfterFirstUnlock];`

Hope that helps.

**Comment by abinaya001** [comment]
@trooper2013 : keychain sharing and app groups are not being used.  I tried with latest sdk(5.0).  It didn't solve the issue.  I also tried with the below code which didnt solve the issue: 
[SFKeychainItemWrapper setAccessibleAttribute: kSecAttrAccessibleAfterFirstUnlock];

Please find the below error log:

20/12/16, 12:27:39 AppName(CocoaLumberjack)[461]: Could not retrieve user account data from '/path/to/UserAccount.plist'
20/12/16, 12:27:39 AppName(CocoaLumberjack)[461]: Error deserializing the user account data: Error Domain=SFUserAccountManager Code=10002 "User account data could not be decrypted. Can't load account." UserInfo={NSLocalizedDescription=User account data could not be decrypted. Can't load account.}

I get the log when i click on notification received to iWatch and iPhone is locked and iPhone app is not running on the device.  When i debugged through it,  I could find the below method calls.

The method "- (SFUserAccount *)loadUserAccountFromFile:(NSString *)filePath" is getting called which internally calls the method "[self loadUserAccountFromFile:filePath encrypted:YES account:&user error:nil]".

Since the later method returns "NO", system is trying to get the user account file by calling the method with the parameter encrypted to "NO". 

I assume that there is an issue with encryption system which deletes the useraccount.file which is stored in the library directory when user responds to notification from iWatch.

Could you please have a look at the issue ?  Please let me know if you need more inputs with regards to the issue.

**Comment by bhariharan** [comment]
@abinaya001 In order to use an extension (Apple Watch in this case), you need to enable keychain sharing and app groups. You need to add the following lines to configure the SDK before invoking SDKManager, as mentioned above.
```
[SFSDKDatasharingHelper sharedInstance].appGroupName = @"group.<app security group name>";
[SFSDKDatasharingHelper sharedInstance].appGroupEnabled = YES;
```
Please let me know if that solves the issue.

**Comment by urthakkar** [comment]
@abinaya001 can you please confirm that enabling the keychain sharing resolved the issue. Thanks

**Comment by trooper2013** [comment]
@abinaya001  Please look at the SmartSyncExplorer sample as I mentioned previously. From what I've understood in your report, it seems to me that  keychain sharing and app groups weren't enabled and/or the steps to configure the SDK were missing. We have been able to use the mobile SDK with extensions successfully.

**Comment by abinaya001** [comment]
@trooper2013 @bhariharan  Thank you for the continuous support !!. unfortunately, the issue has not solved yet even after enabling app group in the application.  I tested it with the latest sdk (5.0). I enabled the app group and keychain sharing with same keychain groups in both iOS app and iWatch target bundles with the below lines as advised by you.
[SFSDKDatasharingHelper sharedInstance].appGroupName = @"group.<app security group name>";
[SFSDKDatasharingHelper sharedInstance].appGroupEnabled = YES;

@bhariharan Please see the comments below:

1) Did you attempt to use the app on fresh install from Mobile SDK 5.0 (not an upgrade from a previous app). The reason I ask is because migration steps for extensions have to be done by the app itself. If the problem occurs on a fresh install with a clean state as well, it's more likely to be an SDK issue. - Yes. I installed the app freshly with the sdk 5.0.

2) Do you have passcode/PIN protection enabled in this app? If PIN protection is enabled, it adds some issues, since the PIN is used to encrypt data and hence is required to encrypt/decrypt account data. - No passcode is configured for the app.

Please see the error log below after enabling app groups and keychain sharing:

Jan  6 19:12:46 iPhone-5C (CocoaLumberjack)[438] <Notice>: Could not retrieve user account data from '/private/var/mobile/Containers/Shared/AppGroup/81A0AFBB-89E4-457A-BA91-42E9F4B200F6/{group.<app security group name>}/00D36000000JflBEAS/00536000001pQxu/UserAccount.plist'
Jan  6 19:12:46 iPhone-5C App_name(CocoaLumberjack)[438] <Notice>: Error deserializing the user account data: Error Domain=SFUserAccountManager Code=10002 "User account data could not be decrypted. Can't load account." UserInfo={NSLocalizedDescription=User account data could not be decrypted. Can't load account.}
Jan  6 19:12:46 iPhone-5C App_Name(CocoaLumberjack)[438] <Notice>: No current user account, so creating a new one.
Jan  6 19:12:50 iPhone-5C App_Name(CocoaLumberjack)[442] <Notice>: There is no user account file in this user directory: /private/var/mobile/Containers/Shared/AppGroup/81A0AFBB-89E4-457A-BA91-42E9F4B200F6/{group.<app security group name>}/00D36000000JflBEAS/00536000001pQxu
Jan  6 19:12:51 iPhone-5C App_Name(CocoaLumberjack)[442] <Notice>: No current user account, so creating a new one.

Data is shared between iPhone and watch apps using watch connectivity framework.  Please let me know if you need more inputs on the issue.

**Comment by trooper2013** [comment]
@abinaya001 There is probably one more thing you can check. The SalesforceSDK uses the most strict/secure  level for keychain access. You could change it by doing the following. 
```` 
[SFKeychainItemWrapper setAccessibleAttribute:kSecAttrAccessibleWhenUnlocked]; 
````
or 
````
[SFKeychainItemWrapper setAccessibleAttribute: kSecAttrAccessibleAfterFirstUnlock]; 
````
Please NOTE this step and the previously proposed settings need to be done, before any call to the SDKManager.

**Comment by abinaya001** [comment]
@trooper2013  I tried with the above solution with the sdk version 5.0.  It didn't work.  I am getting the following in the error log along with the above errors.

22/01/22, 17:04:18 App(CocoaLumberjack)[2931]: Upload failed 403 The requested API is not available to portal users. You may need to specify a community for portal user access.

Once the data is transferred from iWatch to iPhone after the user responds to the notification received in iWatch,the data is stored locally (in smart store) and API call is been made to post the data to org.

Will the forbidden error impact on user account file that is getting removed from local which causes the app to logout?

**Comment by urthakkar** [comment]
@abinaya001 can you try with another user license type? The "portal" users dont have perms to some of the APIs we need in 5.0

**Comment by bhariharan** [comment]
@abinaya001 The following error log has nothing to do with logout or any other impact on the app. It simply indicates that the user you're using has no API access.

```
22/01/22, 17:04:18 App(CocoaLumberjack)[2931]: Upload failed 403 The requested API is not available to portal users. You may need to specify a community for portal user access.
```

**Comment by trooper2013** [comment]
@abinaya001  You have been using the SalesforceSDK in the companion app and not necessarily in the extension. You just need to ensure that the correct accessibility constants are applied to both Keychain Sharing and File Protection. 

Note : The scenario you described requires the SDK to continue to work in background mode for the watch. Apply the correct accessibility constants using these helpers prior to the calls to SalesforceSDKManager.

```
[SFKeychainItemWrapper setAccessibleAttribute: kSecAttrAccessibleAfterFirstUnlock]; 
[SFFileProtectionHelper sharedInstance].defaultNSFileProtectionMode = NSFileProtectionCompleteUntilFirstUserAuthentication
```
