### ISSUE TITLE
SSL Pinning Issue for Salesforce Login Screen

### ISSUE THREAD

**Issue by khirod81** [forcedotcom/SalesforceMobileSDK-iOS#1854]
Please fill out the following details:

1. Version of Mobile SDK Used: 4.2.0
2. Issue found in Native App or Hybrid App: Hybrid
3. OS Version: iOS and Android
4. Device: All devices
5. Steps to reproduce:
SITUATION
We have build an app with Cordova and the SalesforceMobileSDK
During a security test it was pointed out that we should use SSL pinning in order to prevent Man-in-the-middle attacks.
In order to prevent this we have used an sslcertificatechecker plugin (https://www.npmjs.com/package/cordova-plugin-sslcertificatechecker).

COMPLICATION
This all works fine, except for the call where we do the login. The login itself is handled by the Salesforce MobileSDK while the add-on is only used in our own code-base, and therefore no code that we created is being touched during this login process. This also means that we cannot apply our SSL pinning solution for this step, meaning that the man-in-the-middle attack can still happen.

QUESTIONS
In order to secure the login process for Man-in-the-middle attacks, we think we need to make changes to the Salesforce MobileSDK itself. Something we don’t want (mainly because of upgradability reasons).
Therefore we have the following questions:
- What possibilities are there to implement SSL pinning (that also covers the login process)?
- What other options do you suggest for us to use?
6. Actual behavior: SSL Pinning to be not applied to login page
7. Expected Behavior: SSL Pinning to be applied to login page
8. Error Log: N/A

**Comment by bhariharan** [comment]
@khirod81 We don't have `SSL pinning` implemented in `Mobile SDK` out of the box, but it's very easy to implement this in our network layer. See [this](http://www.jonflanders.com/?p=1415) post for details on how to implement `SSL pinning`.
