### ISSUE TITLE
infinite redirect loop for Ios after Session Timeout (Similar to issue #1515)

### ISSUE THREAD

**Issue by GaneshSawant** [forcedotcom/SalesforceMobileSDK-iOS#1856]
Please fill out the following details:

1. Version of Mobile SDK Used:  forceIos 4.3.1
2. Issue found in Native App or Hybrid App: hybrid remote
3. OS Version:  IOS 10.12 Sierra 
4. Device: Iphone 6s , Iphone 5 Simulators, Ipad 2
5. Steps to reproduce: 
-Configure an hybrid remote app.
-Start the application and do the oauth flow.
-Stop the application.
-Let the session expire (or manually revoke the session from Salesforce).
-Start the application again.
6. Actual behavior: On Launching app after Session timeout, its actually showing blank screen (logs showing infine looping)
7. Expected Behavior: Even though Session is getting created in the back end, app should go to landing page instead its showing blank screen
8. Error Log:

We noticed that there was an issue raised for this and it has been already fixed, 

https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1515

Since we are using the latest version not sure if the fix is committed already.

P.S. Tried searching for the Class 'SFHybridViewController.m' in our project directory but was unsuccessful since its Binary or doing something wrong ?

**Comment by bhariharan** [comment]
@GaneshSawant We have fixed this in our upcoming release `Mobile SDK 5.0`, which will be rolling out sometime this month (#safeharbor).
