### ISSUE TITLE
v5.0 CSFDefines.h file not found?

### ISSUE THREAD

**Issue by helloniklas** [forcedotcom/SalesforceMobileSDK-iOS#1870]
Just updated the cocoa pod for iOS. In Swift I now get an error when compiling complaining that CSFDefines.h file not found?

**Comment by bhariharan** [comment]
@helloniklas We've moved a lot of stuff around and consolidated libraries in `Mobile SDK 5.0`. More specifically, we have rolled the `SalesforceNetwork` and `SalesforceRestAPI` libraries into `SalesforceSDKCore`. As a result, you need to update the pod specs in your app to use the new library and remove the old references. [Here](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/master/iOSNativeSwiftTemplate/Podfile) is an example. You'll probably need to update your header inclusions as well. For example, `CSFDefines.h` is now a part of `SalesforceSDKCore` as opposed to `SalesforceNetwork`. `CSFDefines` exists [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Network/Utilities/CSFDefines.h) and is still a public header.

**Comment by helloniklas** [comment]
@bbirman after setting up a new project with forceios I still run into other issues, in the end I manually had to add     pod 'CocoaLumberjack' as well, as this was otherwise crashing under Swift for some reason. It seems you pod dependencies are not correctly set.

**Comment by bhariharan** [comment]
@helloniklas Since a lot of stuff has moved around this release, we recommend generating a new app from our template using `forceios create` and moving your classes in. This should generate the pod specs correctly. You can get `forceios` [here](https://www.npmjs.com/package/forceios). Going forward, it should be easy to update the pod specs inline.

**Comment by helloniklas** [comment]
@bbirman That's what I did, and it then crashes on DDLog dispatch_once, unless I also include CocoLumerjack pod separately. 

Would be easier if you just specify what to put in the pod file to get this running, rather then having some dodgy node_js setup.

**Comment by bhariharan** [comment]
@helloniklas Could you list your steps of app creation here?

**Comment by helloniklas** [comment]
@bhariharan 
1. Created an native_swift with forceios
2. Moved the pod from there into my project, plus the node_modules folder, since that's what you're pointing at.
3. Did pod install on my project.

**Comment by bhariharan** [comment]
@helloniklas Moving the pod file over is probably not going to work. Let's continue [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1872). It appears to be the same issue.
