### ISSUE TITLE
v.50 crashes on start

### ISSUE THREAD

**Issue by helloniklas** [forcedotcom/SalesforceMobileSDK-iOS#1872]
After managed to update the pod to 5.0. 

I now get this when trying to run the app

2016-12-13 12:24:27.328333 MembershipApp[1495:262064] -[DDLog removeAllLoggers]: unrecognized selector sent to instance 0x174019530
2016-12-13 12:24:27.329704 MembershipApp[1495:262064] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[DDLog removeAllLoggers]: unrecognized selector sent to instance 0x174019530'
*** First throw call stack:

**Comment by bhariharan** [comment]
@helloniklas Which version of `CocoaLumberjack` are your pod specs pointing to? We use `2.4.0`.
```
sdkcore.dependency 'CocoaLumberjack', '~> 2.4.0'
```

I'd recommend regenerating an app using `forcedroid create` since a lot of stuff has moved around this release and moving your app's assets and classes in. This should ensure the dependencies are setup correctly. Let me know if that works for you.

**Comment by helloniklas** [comment]
@bbirman problem is your forceios didn't include the cocolumberjack dependency. If I add it it works fine now.

**Comment by bhariharan** [comment]
@helloniklas Are you generating `native_swift` app? I'll take a look.

**Comment by helloniklas** [comment]
@bbirman yes I am. Would be easier if you could just put pod 'SalesforceMobileSDK-iOS' and it would work. Seem your pod file is still pointing to 4.0 though.

**Comment by helloniklas** [comment]
@bhariharan to calrify, my pod files looks likes this to get it to work:

```
platform :ios, '10.0'

project 'MembershipApp.xcodeproj'
target 'MembershipApp' do
    
    source 'https://github.com/CocoaPods/Specs.git'
    
    use_frameworks!
    pod 'CocoaLumberjack'
    pod 'SalesforceAnalytics', :path => 'node_modules/SalesforceMobileSDK-iOS'
    pod 'SalesforceSDKCore', :path => 'node_modules/SalesforceMobileSDK-iOS'
    pod 'SmartStore', :path => 'node_modules/SalesforceMobileSDK-iOS'
    pod 'SmartSync', :path => 'node_modules/SalesforceMobileSDK-iOS'
    
end
```

**Comment by bhariharan** [comment]
@helloniklas Try replacing it with the following pod specs and let me know if that works:

```
platform :ios, '10.0'

project 'MembershipApp.xcodeproj'
target 'MembershipApp' do

source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git' # needs to be first
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
pod 'SalesforceAnalytics'
pod 'SalesforceSDKCore'
pod 'SmartStore'
pod 'SmartSync'

end
```

**Comment by bhariharan** [comment]
@helloniklas One more thing in those pod specs I gave above, please include version numbers (`5.0.0` for our libraries).

**Comment by helloniklas** [comment]
@bhariharan thanks that works fine. Not sure why this is not just in the main ReadMe under How to Instal using cocoa pods as is standard for GitHub repos. Would make it easier rather than having to use all that forceios npm stuff. Especially for users used to Carthage.

On another note, this v5.0 still doesn't work with Swift though. I have to manually add objective-c classes to get it to work as per this post, https://developer.salesforce.com/forums/ForumsMain?id=906F0000000DBhp

**Comment by bhariharan** [comment]
@helloniklas The `Cocoapod` install steps are part of our dev guide. Thanks for your feedback, we will make it more visible in our `README` as well. If the `CocoaLumberjack` crash is gone, let's talk about the `SFRestRequest` issue separately in your other post, since this one is resolved.

**Comment by helloniklas** [comment]
@bhariharan ok many thanks. I could not find any where in your dev guides where this is stated. I could only find it by creating the native_swift through forceios and then looking at the pod file. Anyhow, it's working now. Thanks.
