### ISSUE TITLE
Using a custom login screen?

### ISSUE THREAD

**Issue by helloniklas** [forcedotcom/SalesforceMobileSDK-iOS#1873]
I see there some very basic customisation options on SFLoginViewController.sharedInstance()

How would I go about to use a fully custom login screen with this SDK? Would I have to deal with he whole oAuth dance myself? Or is there an easy way to hook into the login flow from my own login view?

**Comment by trooper2013** [comment]
@helloniklas  There are ways for you to hook into the login flow but these are not for the purposes of customizing the login screen. The Login screen & OAuth flow are completely controlled by the salesforce platform. Community apps do have a way to achieve what you are looking for but it needs for you to create a user community.

**Comment by bhariharan** [comment]
@helloniklas Customizing the login screen is possible but it needs to be done on the server side, since we display it within a `WebView`.

**Comment by helloniklas** [comment]
@bhariharan thanks. Where can I find docs on how to customise this screen on the backend? I've looked in the Connected Apps section on Salesforce, but apart form uploading a log I can't seem to find how to change this login page.

**Comment by bhariharan** [comment]
@helloniklas I'm not sure where the documentation exists for that either, but you could start [here](https://help.salesforce.com/articleView?id=domain_name_login_branding.htm&type=0&language=en_US&release=204.17) maybe?

**Comment by helloniklas** [comment]
@bhariharan Thanks, so that sort of works, but, when presenting the SFLoginViewController the user then have to tap "User Custom Domain" then enter the domain setup, to see the custom page and login.

How would I set this as the default domain to use when the SFLoginViewController is presented. I can't seem to find any way of doing this.

**Comment by helloniklas** [comment]
ok, realised there's a key in the plist called SFDCOAuthLoginHost.

**Comment by bhariharan** [comment]
@helloniklas Yes - `SFDCOAuthLoginHost` is the way to go.
