### ISSUE TITLE
Salesforce remote hybrid app answer yes to push notifications causes app to be unresponsive stuck at the Loading... page

### ISSUE THREAD

**Issue by mlzur** [forcedotcom/SalesforceMobileSDK-iOS#1893]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.0.0
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: 9.3.5
4. Device: iPad 
5. Steps to reproduce: 
I have a remote hybrid app with push notifications that connects to a Salesforce community with a login page. The community login page is the first page that displays that allow users to login with username and password. Because the app is enabled for push notification, the app will also ask users permission to allow app to send them notifications. Steps are:
- App is first loaded and the message that prompts user to allow app to send them push notification is displayed. 
- Before you answer "Ok" button to allow push notification, wait for the community login page to finish displaying in the background 
- When the community login page is displayed in the background, click the "Ok" button to allow push notification
- A white page saying "Loading..." is displayed and stays there forever and app becomes unresponsive.

6. Actual behavior:

After clicking on the "Ok" button, the app displays a white screen with the words "Loading..." and stays unresponsive. 

The strange thing is if you click "Ok" button BEFORE the community login page gets loaded in the background, the app behaves correctly.

7. Expected Behavior:

After clicking "Ok" button the app should just stay on the community login page and not be displaying the white page displaying "Loading..." forever. 

8. Error Log:

**Comment by pbergner** [comment]
@huminzhi I'm experiencing an issue where the cordova barcode scanner plugin never comes back if its the user's first time and needs to ask for camera permissions. After camera permission is either accepted or denied it behaves correctly. Could this be related to this issue?

**Comment by bhariharan** [comment]
@pbergner We don't own the barcode scanner of the camera plugins. Please contact the appropriate owner of those plugins for issues with those plugins. I don't think it's related to the push notification issue here.
