### ISSUE TITLE
SDK 4.3 (and SDK 5.0) alters userAgent - Impacts certain web pages.

### ISSUE THREAD

**Issue by rgoldiez** [forcedotcom/SalesforceMobileSDK-iOS#1902]
I migrated my app (React Native) from SDK 4.2 to SDK 4.3.1 several months ago and just realized that the userAgent in a WebView went from the standard "Mozilla/5.0 ..." to a non-standard userAgent "SalesforceMobileSDK/iOS 10.2 ......" 

This causes a problem with certain web pages that use the user agent to determine how to deliver content (sites that use google charts).  

How do I set the user agent back to the default in SDK 4.3?  Also curious why this was changed.

**Comment by rgoldiez** [comment]
@bhariharan @wmathurin - Hey guys... just wanted to make sure you saw this and see if there's a workaround.

**Comment by bhariharan** [comment]
@rgoldiez We've always had a custom user agent in `Mobile SDK` - it helps us collect metrics on usage. You should be able to override it in your app like this:

```
[SalesforceSDKManager sharedManager].userAgentString =  ^ NSString* (NSString* qualifier) {
    return CUSTOM_USER_AGENT;
};
```

**Comment by rgoldiez** [comment]
Thank you @bhariharan ....  that worked!  I'm not sure why I wasn't seeing this "issue" in 4.2 (nor 4.0). Only started in 4.3 for me.
