### ISSUE TITLE
App crash when presenting login screen

### ISSUE THREAD

**Issue by davidmdavis** [forcedotcom/SalesforceMobileSDK-iOS#1903]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.0.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 10.1.1
4. Device: iPad Pro
5. Steps to reproduce: 
````
// Login
SFAuthenticationManager.shared().login(completion: success, failure: failure)
`````
6. Actual behavior: App crashes when presenting Salesforce login screen
7. Expected Behavior: Login screen should be presented.
8. Error Log: 
````
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SFOAuthCoordinator webView:didCommitNavigation:]: unrecognized selector sent to instance 0x174154690'
````

**Comment by huminzhi** [comment]
@davidmdavis Is it from native or hybrid app? In the details, it's said native, but the code seems from hybrid..
Also, just wondering if it's recoverable after kill and resume the app?

**Comment by davidmdavis** [comment]
Hi @huminzhi,

It's a native app using Swift. I omitted some of the details from code. Sorry for the confusion!

**Comment by fobin** [comment]
I've actually seen some launch crashes from our app after updating to 5.0.0. It crashes to launch screen but doesn't error out clearly in the log. Just hangs there. Relaunching the app it goes to login screen nicely.

**Comment by davidmdavis** [comment]
It looks like this issue was caused by an update to the NewRelic agent and has been fixed in the latest [release](https://docs.newrelic.com/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-5101).
