### ISSUE TITLE
Logging out does not delete user soups.

### ISSUE THREAD

**Issue by davidmdavis** [forcedotcom/SalesforceMobileSDK-iOS#1904]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.0.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 10.1.1
4. Device: iPad Pro
5. Steps to reproduce:
````
// Create store for current user
let store = SFSmartStore.sharedStore(withName: "UserStore", user: SFUserAccountManager.sharedInstance().currentUser)

// Create a soup in store
store.registerSoup("TestSoup", withIndexSpecs: indexSpecs, error: ())

// Sync some data
let manager = SFSmartSyncSyncManager.sharedInstance(forUser: SFUserAccountManager.sharedInstance().currentUser, storeName: "UserStore")
manager.syncDown(with: target, options: options, soupName: "TestSoup", update: update)

// Logout
SFAuthenticationManager.shared().logout()

// Login again
SFAuthenticationManager.shared().login(completion: success, failure: failure)
````
6. Actual behavior: After logging in again, old soups still exist.
7. Expected Behavior: Soups should be deleted after user logs out.
8. Error Log:

**Comment by trooper2013** [comment]
@davidmdavis See my comments related to #1906. As mentioned this could be a race condition caused by a logout that is still in progress.  Please follow the steps outlined in #1906.

**Comment by wmathurin** [comment]
Logout is asynchronous but does delete user soups. If you call login right away, you get a race condition.
