### ISSUE TITLE
Server Error Alert displacement

### ISSUE THREAD

**Issue by ksrvmahesh** [forcedotcom/SalesforceMobileSDK-iOS#1917]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.0
2. Issue found in Native App or Hybrid App:Native App
3. OS Version:10.2
4. Device: iPhone/iPad
5. Steps to reproduce:  
- Launch the application in airplane mode.  
- Observe the Network error alertView title "Server Error". 
- Press Home button, the application goes background. 
- Tap the Application, app comes into foreground. 
- Observe the position of network error alertView.
6. Actual behavior:  The position of network error alertView "Server Error" is on the top left the screen. Only "Retry" and "Dismiss" buttons are visible.
7. Expected Behavior: The position of network error alertView "Server Error" should be in the middle of the screen
8. Error Log: No Log, attached screenshots.

Attaching the screenshots for the reference.
![alert_on_top_left_ipad](https://cloud.githubusercontent.com/assets/17624443/22946988/597c2d3c-f2c7-11e6-8e9d-ef6615b83138.png)
![alert_on_top_left_iphone](https://cloud.githubusercontent.com/assets/17624443/22946991/597edb4a-f2c7-11e6-9444-e76afc74b98e.png)
![network error alert_ipad](https://cloud.githubusercontent.com/assets/17624443/22946990/597e47b6-f2c7-11e6-9b65-d55c364908c7.png)
![network error alert_iphone](https://cloud.githubusercontent.com/assets/17624443/22946989/597d41ea-f2c7-11e6-9ed6-d1bbcfd8b0cc.png)

**Comment by bhariharan** [comment]
@ksrvmahesh This should be fixed in our `dev` branch. Could you try the `dev` branch? Feel free to reopen this issue if you see the issue on `dev`.
