### ISSUE TITLE
Unable to load lightening component in mobile app

### ISSUE THREAD

**Issue by manish-metacube** [forcedotcom/SalesforceMobileSDK-iOS#1923]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.0 
2. Issue found in Native App or Hybrid App:  Hybrid App
3. OS Version: 10.2
4. Device: Simulator/ iPhone 6s
5. Steps to reproduce: will proivde in description 
6. Actual behavior: Not showing lightning app. 
7. Expected Behavior:Should show lightning app
8. Error Log: Attached

Hi all, 

I am unable to launch lightening component in newer SDK 5.0 

Here is what I did 

1. Created a div 
 `<div id="lightning" />`

2. Use following function to render lightening component 
```
function renderLighteningComponent() {
            if ($Lightning) {
                var urlComponents = force.getInstanceUrl(), newLighteningUrl = ".lightning.force.com";
                
                //updated url 
                newLighteningUrl = urlComponents[0].concat(newLighteningUrl).toLowerCase();

                $Lightning.use("c:mytestapp", function () {
                    $Lightning.createComponent(
                        "c:helloWorld",
                        {},
                        "lightning",
                        function (cmp) {
                            console.log("Component created!");
                            console.log(cmp);
                        });
                }, newLighteningUrl, force.getAccessToken());
            }
        }
```

3. Customised force.js to return instance URL and Access token. 

4. CORS setting in my index.html
`<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://*.force.com https://*.salesforce.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *;script-src 'self' https://*.force.com https://*.salesforce.com 'unsafe-inline' 'unsafe-eval'; connect-src https://*.force.com *; child-src 'self' gap:;">`
5. Config.xml changes 
	
```
	<access origin="*" />
    <access origin="*.my.salesforce.com" />
    <access origin="*.force.com" />
    <access origin="*.salesforce.com" />
```

When I run my application received following error  

`https://mydomain.lightning.force.com/c/mytestapp.app?aura.format=JSON&aura.formatAdapter=LIGHTNING_OUTFailed to load resource: Origin null is not allowed by Access-Control-Allow-Origin.`

`XMLHttpRequest cannot load https://mydomain.lightning.force.com/c/mytestapp.app?aura.format=JSON&aura.formatAdapter=LIGHTNING_OUT. Origin null is not allowed by Access-Control-Allow-Origin.`

Am I missing something?

It was just a fresh one-page app, still not working. 

Any help? 
@bhariharan ?

Regards,
Manish Kumar

**Comment by bhariharan** [comment]
@manish-metacube Lightning components are currently unsupported in the mobile container. Lightning's `CSP` settings are quite strict (see [here](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/csp_trusted_sites.htm)). If it is `CORS` related, you could try switching to `UIWebView` instead of `WKWebView`, but regardless, lightning components are unsupported at the moment and we can't guarantee that it'll run reliably.

**Comment by manish-metacube** [comment]
Hey @bhariharan , 

Do we have any workaround or alternate date when we can expect fix for this issue?

**Comment by bhariharan** [comment]
@manish-metacube Unfortunately, it is not under our control. Lightning components are built to run on the browser, not within a mobile container. Until the lightning team supports running inside a container, there is little we can do.

**Comment by manish-metacube** [comment]
OK. 

How do I enforce my app to use UIWebView using Mobile SDK 5.0 ?

lightning components worked in winter 16 orgs with locker service on/off and now on Spring 17 it only works with locker service off with UIWebView. Do you know why?

**Comment by bhariharan** [comment]
`WKWebView` doesn't allow `XHR` requests where the origin isn't specified. That's the only difference from the client side. I don't know what locker service is. You can switch to using `UIWebView` by following these steps:

In `AppDelegate+SalesforceHybridSDK.m` of the generated hybrid app, look for the method `setupRootViewController`.

Change this line in that method:

`self.viewController = [[SFHybridViewController alloc] initWithConfig:(SFHybridViewConfig*)[SalesforceSDKManager sharedManager].appConfig];`

to this:

`self.viewController = [[SFHybridViewController alloc] initWithConfig:(SFHybridViewConfig*)[SalesforceSDKManager sharedManager].appConfig useUIWebView:YES];`

This will make `UIWebView` the default.

However, I reiterate that lightning components are unsupported in the container, so things could break going forward.

**Comment by va1bhav** [comment]
@bhariharan In Hybrid SDK version 7.30, adding "useUIWebView:YES" shows below warning. What is the best practise to be followed now?
 
'initWithConfig:useUIWebView:' is deprecated: Deprecated in Salesforce Mobile SDK 7.2 and will be removed in Salesforce Mobile SDK 8.0. Will be removed

**Comment by bhariharan** [comment]
@va1bhav We have deprecated our usage of `UIWebView` as of `7.3` and it will be removed in `8.0`. Going forward, `WKWebView` will be the only webview type supported.
