### ISSUE TITLE
issue while updating older version of app

### ISSUE THREAD

**Issue by JKSTy** [forcedotcom/SalesforceMobileSDK-iOS#1924]
Version of Mobile SDK Used: 4.3
Issue found in Native App or Hybrid App: Native App
OS Version:  8.0, to 10.0
Device: Iphone & Ipad Simulator and Device
Expected Behavior: Nothing happens.
Error Log:
ERROR com.salesforce <SFUserAccountManager>: Error deserializing the user account data: Error Domain=SFUserAccountManager Code=10002 "User account data could not be decrypted. Can't load account." UserInfo={NSLocalizedDescription=User account data could not be decrypted. Can't load account.}

ERROR com.salesforce <SF_FMDatabase>: DB Error: 26 "file is encrypted or is not a database"
ERROR com.salesforce <SFSmartStore>: Error opening store 'defaultStore': out of memory
ERROR com.salesforce <SF_FMDatabase>: DB Error: 26 "file is encrypted or is not a database"
ERROR com.salesforce <SF_FMDatabase>: DB Error: 26 "file is encrypted or is not a database"

**Comment by bhariharan** [comment]
@JKSTy The logs simply indicate that the decryption failed, possibly because of a change in the encryption key. Which version of `Mobile SDK` did you upgrade from and to which version did to upgrade to? How did you create your app (using `Cocoapods` or `forceios`)? How did you perform the upgrade?

**Comment by TysonBunch** [comment]
@JKSTy - Curious if you have more information or have resolved this? @bhariharan

**Comment by wmathurin** [comment]
We are unable to reproduce the issue here. Please re-open if you are still running into this issue / and it involves the latest version of the Mobile SDK (and please provide more details like the version you were upgrading from).
