### ISSUE TITLE
Build fails after running "react-native link"

### ISSUE THREAD

**Issue by vinodr** [forcedotcom/SalesforceMobileSDK-iOS#1930]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.0.1
2. Issue found in Native App or Hybrid App: React Native (iOS)
3. XCode : Version 8.2.1
    CocoaPods: Version 1.2.0
4. Device: iPhone 5
5. Steps to reproduce: Create react native app using "forceios create" and run "react-native link"
6. Actual behavior: Build fails with the following error.
7. Expected Behavior: Build successful
8. Error Log:
<img width="260" alt="screen shot 2017-02-17 at 11 38 14 am" src="https://cloud.githubusercontent.com/assets/2153600/23080629/5c88f6c2-f506-11e6-9824-a9bf323b9895.png">

**Comment by wmathurin** [comment]
Why are you running react-native link?

I just ran forceios then I opened App/iOS/App.xcworkspace and was able to build without any problems.

Are you opening the generated workspace or project?

If you don't see the workspace, then the problem might be cocoapod.
Try the latest version by first doing
```
sudo gem install cocoapods
```
Then go to App/iOS and run 
```
pod update
```

**Comment by vinodr** [comment]
I am going thru the Dream House React Native tutorial (https://github.com/ForceDotComLabs/dreamhouse-mobile-react) and as part of it, I am trying to install and link the force theme package (as mentioned at https://github.com/ForceDotComLabs/react.force.base.theme).

I am using "react-native link" instead of "rnpm link", not sure if this makes any difference.

I am opening the workspace. It builds for me immediately after creating the app but fails after running the linking command.

I also have external libraries (iOS SDKs) that I am including in the mobile app, so I already have cocoapods installed and seems to be working correctly.

When I run "react-native link", two libraries called "libFMDB.a" and "libFMDB-ios.a" are getting added to the frameworks and libraries list, along with the salesforce base theme library, where the error is showing up. I can manually link just the salesforce theme library in my app for now but thought someone might be interested in knowing about the issue and fix it.

**Comment by wmathurin** [comment]
Please open an issue on the dreamhouse-mobile-react repo.
If you want to build react native application with SalesforceMobileSDK, please use our [forceios](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/ios_new_force_project.htm) command line tool.
