### ISSUE TITLE
Salesforce Passcode Pin Screen is black and not customisable

### ISSUE THREAD

**Issue by mlzur** [forcedotcom/SalesforceMobileSDK-iOS#1943]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.0.0
2. Issue found in Native App or Hybrid App: iOS Hybrid remote app
3. OS Version: 10.1
4. Device: iPhone, iPad
5. Steps to reproduce:
- Login to the app
- Wait for the inactivity timeout or kill the app (Connected app pin setting is 15 min)
- Go back to the app again, black passcode pin screen is displayed.
- passcode pin screen is black, colors of buttons, text box is not configurable in Localizable.strings. 

6. Actual behavior:

- Passcode pin screen is black, colors of buttons, text box is not configurable in Localizable.strings. 

- The black color is hardcoded in line 280 in SFPasscodeViewController -
[self.view setBackgroundColor:[UIColor blackColor]];

- Forgot password button colours are  hardcoded in lines 255,257.
- Passcode , error , instructions colours in lines 222, 232,235
- Title bar color, text color are not configurable
- No ability to add in image/logo

7. Expected Behavior:

Will it be possible to make all these properties take customisable colours (RGB) by externalising these in the localizable.strings ?

I have made some code changes myself by removing the black and updated to custom rgb colours in SFPasscodeViewController. Now i am incorporating those changes back into my project. But if these changes could be included in the next build that would be really appreciated.

8. Error Log:

**Comment by wmathurin** [comment]
You can provide your own screen for passcode input.
Look at the `SFSecurityLockout` class.
To see how the default one is setup, please look at: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Security/SFSecurityLockout.m#L95
