### ISSUE TITLE
Upgrading to 5.0.1 from 4.3 resulting in crash trying to open smartstore

### ISSUE THREAD

**Issue by mattlacey** [forcedotcom/SalesforceMobileSDK-iOS#1986]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.0.1
2. Issue found in Native App or Hybrid App: Hybrid (Local)
3. OS Version: 9.3/9.2
4. Device: iPad
5. Steps to reproduce: Upgrade application by creating new app (as per MobileSDK Guide) and copying in artefacts
6. Actual behavior: Crashing trying to open the store
7. Expected Behavior: Should work as before

I put the details of this issue here already:

https://plus.google.com/+MattLacey/posts/3BScDsRpkwM

![screen shot 2017-03-29 at 12 00 35 pm](https://cloud.githubusercontent.com/assets/1256283/24843342/2ec01a4c-1de5-11e7-8508-fef6e4b4147e.png)

It appears to be a keychain issue, and I wonder if it could be because this is a new application with the same bundle ID trying to create a store. I'm not sure how that stuff works internally, but given that's the recommended upgrade path it feels like it should work. I've seen this in the past and solved it by resetting the simulator and it's content, but this is happening on device, for clients, and this is not an option.

**Comment by Dmitry-Kravchuk** [comment]
Hi, just remove sqlite.tbd from Link Binaries in project settings.

**Comment by wmathurin** [comment]
It looks like this [dyld crash bug](https://github.com/artsy/eigen/issues/1246) which according to this [comment](https://github.com/artsy/eigen/issues/1246#issuecomment-219140317) was fixed in 9.3.2. Please re-open if you think your issue is different.
