### ISSUE TITLE
cleanResyncGhosts Completion block is not always called

### ISSUE THREAD

**Issue by mikecaulley** [forcedotcom/SalesforceMobileSDK-iOS#1997]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.0.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 10.3.1
4. Device: iPad Air 2
5. Steps to reproduce: n/a
6. Actual behavior: cleanResyncGhosts will sometimes fail, check of 3 conditions at the top of the function, but never call the completion block.
7. Expected Behavior: cleanResyncGhosts should call the completion block with SFSyncStateStatusFailed or another state instead of just returning
8. Error Log:

**Comment by bhariharan** [comment]
@mikecaulley We've fixed this as part of a sync target and manager refactoring effort in our `dev` branch. This will be a part of our upcoming `5.1` release. Feel free to reopen if you see an issue in `5.1` as well.
