### ISSUE TITLE
Project is not compiling with CocoaPods

### ISSUE THREAD

**Issue by diogowbrito** [forcedotcom/SalesforceMobileSDK-iOS#2009]
I've attached a sample project just with Salesforce pods, which is enough for reproducing the issue.

[Sample Project](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/958818/Test.zip)

1. Version of Mobile SDK Used: Doesn't Apply
2. Issue found in Native App or Hybrid App: Doesn't Apply
3. Tools Versions:
Pod: 1.2.1
Xcode: 8.3 (8E162)
4. Pulled Dependencies versions:
CocoaLumberjack (2.4.0)
SalesforceAnalytics (5.0.1)
SalesforceNetwork (4.3.1)
SalesforceRestAPI (4.3.1)
SalesforceSDKCore (5.0.1)
5. Device: 
iPhone Simulator
6. Steps to reproduce:
5.1. Create empty project
5.2. Setup and add pods dependencies
5.3. Install Pods
5.4. Compile Project
7. Actual behavior:
Project is not compiling
8. Expected Behavior:
Project should compile without warnings
9. Error Log:
```Test/Pods/SalesforceSDKCore/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Network/Network/Queue/CSFNetwork+Internal.h:27:9: 'CSFNetworkOutputCache.h' file not found```

**Comment by bhariharan** [comment]
@diogowbrito Your pod specs are incorrect. You don't need `SalesforceNetwork` and `SalesforceRestAPI`. They have been rolled into `SalesforceSDKCore` in `5.0.1`, so they're automatically included.

**Comment by bhariharan** [comment]
After removing those 2 entries from your `Podfile`, your sample project compiled fine for me. The `Podfile` in your test project looks like this now:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, ’10.0’
use_frameworks!

source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test
    pod 'SalesforceAnalytics'
	pod 'SalesforceSDKCore'
end
```

**Comment by diogowbrito** [comment]
Works perfectly @bhariharan. Thanks.
