### ISSUE TITLE
iOS iPad app Crashed

### ISSUE THREAD

**Issue by quoctc** [forcedotcom/SalesforceMobileSDK-iOS#2010]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.0.1
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: any (tested on iOS 9.2.1)
4. Device: ipad
5. Steps to reproduce: expired token when i open app and my app call to SFRestRequest 
6. Actual behavior:
7. Expected Behavior:
8. Error Log: 
https://screencast.com/t/1zMw1moUmK

App crashed at here when my app expired token:
NSAssert((nil != [self.view superview]), @"No superview for oauth web view after didBeginAuthenticationWithView");

**Comment by bhariharan** [comment]
@quoctc Could you try this with the latest version - `Mobile SDK 5.1.0`? We've reworked the REST API network layer and this shouldn't occur anymore.

**Comment by quoctc** [comment]
Thank for your quick response @bhariharan  
I will try it.

**Comment by TysonBunch** [comment]
@quoctc - Were you able to try with MobileSDK 5.1.0?

**Comment by quoctc** [comment]
Not yet, We have to release our app in this summer. So, we can’t upgrade new SDK.

**Comment by wmathurin** [comment]
Please re-open if you are able to reproduce the bug with our latest version Mobile SDK 5.1.
