### ISSUE TITLE
5.1 crashes all SFRestRequest SFRestAPI.sharedInstance().send calls

### ISSUE THREAD

**Issue by helloniklas** [forcedotcom/SalesforceMobileSDK-iOS#2014]
Please fill out the following details:

1. Version of Mobile SDK Used: 
5.1
2. Issue found in Native App or Hybrid App:
Native

3. OS Version:
10.3

After updating to v5.1 I now get an API crash in SFRequest.m at line 148:

            components.queryItems = queryItems;

Error message is
-[_TtGCs26_SwiftDeferredNSDictionarySSP__ stringByAddingPercentEncodingWithAllowedCharacters:]: unrecognized selector sent to instance

This is some sample code, but it happens pretty much everywhere.

```
        let segments: [String: String] = ["type" : "Text", "text" : message]
        let body: [String: Any] = ["messageSegments" : [segments]]
        let query: [String: Any] = ["body": body]
        let request = SFRestRequest(method: .POST, path: "/services/data/v39.0/connect/communities/\(Constants.communityId)/chatter/feed-elements/\(newsID)/capabilities/comments/items", queryParams: query)
        
        SFRestAPI.sharedInstance().send(request, fail: { (error) in
```

**Comment by helloniklas** [comment]
Trying with the SFJsonUtils util causes the same error,

`let query = SFJsonUtils.object(fromJSONString: "{\"body\": {\"messageSegments\": [{\"type\": \"Text\", \"text\": \"some text\"}]}}")`

**Comment by bhariharan** [comment]
@helloniklas You don't want to set the `body` of `POST` in `queryParams`. For a `POST`, `queryParams` should be `nil` and `body` should be set like this:
`[request setCustomRequestBodyDictionary:params contentType:kSFDefaultContentType];`

See this example in `SFRestAPI.m`:
```
- (SFRestRequest *)requestForCreateWithObjectType:(NSString *)objectType
                                           fields:(NSDictionary *)fields {
    NSString *path = [NSString stringWithFormat:@"/%@/sobjects/%@", self.apiVersion, objectType];
    SFRestRequest *request = [SFRestRequest requestWithMethod:SFRestMethodPOST path:path queryParams:nil];
    return [self addBodyForPostRequest:fields request:request];
}
```
The contents of `addBodyForPostRequest` are:
```
- (SFRestRequest *)addBodyForPostRequest:(NSDictionary *)params request:(SFRestRequest *)request {
    [request setCustomRequestBodyDictionary:params contentType:kSFDefaultContentType];
    return request;
}
```
Let me know if that works for you.

**Comment by helloniklas** [comment]
@bhariharan still gives error 411.

```
        let request = SFRestRequest(method: .POST, path: "/services/data/v39.0/connect/communities/\(Constants.communityId)/chatter/feed-elements/\(newsID)/capabilities/comments/items", queryParams: nil)
        
        request.setCustomRequestBodyDictionary(query, contentType: "application/json")
```

The kSFDefaultContentType doesn't seem to be accessible in Swift, not sure where it is, but sending in "application/json" gives error 411.

Not sure what that means, but this was all working fine under 5.0.1

**Comment by helloniklas** [comment]
@bhariharan it also spits out, A background URLSession with identifier com.salesforce.network already exists!

**Comment by helloniklas** [comment]
Here's the error in full:

```
2017-04-28 16:57:14.856 xxxxx[45168:2276667] A background URLSession with identifier com.salesforce.network already exists!
Optional("The operation couldn’t be completed. (https://xxxxx-developer-edition.eu11.force.com/services/data/v39.0/connect/communities/0DB0Y0000004Cj1WAE/chatter/feed-elements/0D50Y00000Im8q2SAB/capabilities/comments/items error 411.)")
```

**Comment by bhariharan** [comment]
@helloniklas You can ignore the background session warning. As for the response, I'm guessing it doesn't crash anymore right? `411` means `content length is not set`. After `request.setCustomRequestBodyDictionary(query, contentType: "application/json")`, add this line:
`[request setHeaderValue:[NSString stringWithFormat:@"%lu", (unsigned long)[query length]] forHeaderName:@"Content-Length"];`

Let me know if that works.

**Comment by helloniklas** [comment]
@bhariharan uh, how would this be set in Swift? query.length is not available I think, I need to count the bytes of the query?

**Comment by helloniklas** [comment]
@bhariharan right, if set as string this now works

```
        let query = "{\"body\": {\"messageSegments\": [{\"type\": \"Text\", \"text\": \"some text\"}]}}"
        let request = SFRestRequest(method: .POST, path: "/services/data/v39.0/connect/communities/\(Constants.communityId)/chatter/feed-elements/\(newsID)/capabilities/comments/items", queryParams: nil)
        request.setCustomRequestBodyString(query, contentType: "application/json")
        request.setHeaderValue("\(ULONG(query.characters.count))", forHeaderName: "Content-Length")

```

although, this must surely be a bug in the API?

**Comment by bhariharan** [comment]
@helloniklas Some endpoints are a little more finicky requiring `Content-Length` but most are not. We changed out underlying network stack recently that changed the expectations and how to use our Rest API library, which changed some things. I'll take a look at automatically setting `Content-Length` for some types in a future release.

**Comment by helloniklas** [comment]
@bhariharan ok, yeah, seems a bit awkward that it wouldn't be set by the API.  So if I want to use the setCustomRequestBodyDictionary, how would I set the length of the dictionary in Swift?  query.count doesn't work...

**Comment by bhariharan** [comment]
@helloniklas For `NSDictionary` what we do is:
```
NSData *body = [SFJsonUtils JSONDataRepresentation:bodyDictionary options:0];
if (body) {
    [self setCustomRequestBodyData:body contentType:contentType];
}
```
`NSData` has a `length` property that should work. You could do the same. Length has to be determined post conversion to `NSData`.
