### ISSUE TITLE
Unable to set a custom domain on SFUserAccountManager

### ISSUE THREAD

**Issue by sahitya8e7** [forcedotcom/SalesforceMobileSDK-iOS#2018]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.1
2. Issue found in Native App or Hybrid App: Native iOS
3. OS Version: iOS 10
4. Device: iPhone 7 plus
5. Steps to reproduce: Upgrade the Salesforce Mobile SDK from 4.2 to 5.1
6. Actual behavior: The build fails with the following error:
error: value of type 'SFUserAccountManager' has no member 'loginHost'
7. Expected Behavior: The project should build successfully.
8. Error Log:
error: value of type 'SFUserAccountManager' has no member 'loginHost'
        if let host = SFUserAccountManager.sharedInstance().loginHost {

I have been able to set a custom domain URL and change environments in the past by setting the loginHost variable on SFUserAccountManager. One simple line of code used to achieve this:

SFUserAccountManager.sharedInstance().loginHost = loginDomain

This does not work anymore. Apparently, loginHost is not an exposed property now on  SFUserAccountManager. 

Can you please let me know if this was replaced with something else (which I am clearly not finding)? 
Or was this intended to be hidden? In this case, what would be the new way of setting a custom domain?

**Comment by bhariharan** [comment]
@sahitya8e7 The new way to set it is:
```
[SFAuthenticationManager sharedManager].loginHost
```

**Comment by sahitya8e7** [comment]
Please reopen this issue, since the new way that you have provided doesnt seem to work.

The scenario is as follows:
We login to the app. - A loginhost is set and the instance is launched.

We logout from the app. - Call made: SFAuthenticationManager.shared().logout()
This step is supposed to set the isLaunching property of SFAuthenticationManager to false. But that doesnt seem to be happening.

We set the loginHost to a different value and try to launch the app. - This fails with the error "Launch already in progress."

My analysis: 
In logoutUser: API of SFAuthenticationManager, there is a check in the beginning for 

> if (user == nil)

This fails since the user is nil.
This used to work before because even after logout, the user was set to a temporary user

> <SFUserAccount username=(null) fullName=(null) accessScopes={...}

Can you please look into this? I can log a different issue too. Please let me know.

**Comment by sahitya8e7** [comment]
Hi @bhariharan , no need to open this issue. I have created another issue and referenced this there.

Thanks!
