### ISSUE TITLE
Issue after wrapping app in MDM. Application is showing white blank screen.

### ISSUE THREAD

**Issue by manish-metacube** [forcedotcom/SalesforceMobileSDK-iOS#2023]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.0
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: 10.2 
4. Device: Any iOS device
5. Steps to reproduce: Simply run it
6. Actual behavior: App is showing a white dead screen.
7. Expected Behavior: App should run seamlessly 
8. Error Log: attached
[logWithSDK5.txt](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/973369/logWithSDK5.txt)

Hi All, 

We are using SDK 5.0 for one of hybrid application. Recently we got a requirement to use app inside Air watch. There are two ways of that. 
1 Using Air watch SDK
2 Using air watch App wrapping. 

We prefer to 2 and use app wrapping so it doesn't require the code change.  
When wrapping our application in air watch app is unable to run. It's showing a white blocker screen. 

I have attached logs for details. We are looking for some help. It's very crucial. 

@bhariharan Do we support MDM like air watch or MobileIron?
How to proceed now?

Regards,
Manish Kumar

**Comment by bhariharan** [comment]
@manish-metacube There's nothing in the `Mobile SDK` that prevents this flow from working although we've never tried it. My guess is that it's a configuration issue, but this is something you need to work with `AirWatch` on troubleshooting. Looking at the logs, it looks like some network requests on the login screen are being suppressed, but I could be wrong. Please follow up with `AirWatch`.
```
May  3 18:17:50 iPhone mDNSResponder[92] <Info>: ShouldSuppressUnicastQuery: Query not suppressed for login.salesforce.com., qtype Addr, DNSServer . 8.8.8.8:53 allows A queries
May  3 18:17:50 iPhone mDNSResponder[92] <Info>:  18: Result code socket 19 closed  00000000 00000001 (0)
May  3 18:17:50 iPhone mDNSResponder[92] <Info>: GenerateNegativeResponse: Generating negative response for question login.salesforce.com. (AAAA)
May  3 18:17:50 iPhone mDNSResponder[92] <Info>: queryrecord_result_callback: Suppressed question login.salesforce.com. (AAAA)
May  3 18:17:50 iPhone mDNSResponder[92] <Info>:  18: DNSServiceGetAddrInfo(login.salesforce.com., AAAA) ADD    0 login.salesforce.com. AAAA
May  3 18:17:50 iPhone mDNSResponder[92] <Info>:  18: DNSServiceGetAddrInfo(login.salesforce.com., Addr) ADD   25 login.salesforce.com. CNAME login.l2.salesforce.com.
```

**Comment by gsbasso** [comment]
Ticket was previously opened with AirWatch and was ultimately escalated to their T3 support.

Here is what they ultimately reported:

> The issue is that, there is  a blocker page (white page) on top of the sales force webview page. When we wrap the app we have a blocker screen which AirWatch SDK provides. So AirWatch SDK blocker screen is under the Salesforce blocker screen and that's where the issue is of two blocker pages and app gets stuck.

As such, I'm not convinced that the issue isn't within the Salesforce SDK, or at the least that the issue cannot be resolved through a modification to the SDK.

Can we at least re-open issue?

**Comment by bhariharan** [comment]
@gsbasso Our topmost screen is the login screen unless the app has a splash screen. Since your app is a `Cordova` hybrid app, perhaps you need to remove your splash screen? As I mentioned, wrapping with `AirWatch SDK` is not something we've verified or supported.

**Comment by gsbasso** [comment]
There is a splash screen, yes, so that would be an interesting test (i.e. test the effect of suppressing the splash screen).

We've been told that there is no way to disable this "blocker screen" provided by the AirWatch SDK, at least not when wrapping.

**Comment by bhariharan** [comment]
If the white screen in front is indeed the case, then that would be the splash screen in the app.

**Comment by neerajsoni** [comment]
I created very similar app and wrapped with AirWatch. The screen that sticks to the screen is showing "Loading..." screen which is from Salesforce SDK. It is not the splash screen ideally, rather it is the InitialView and its InitialViewController has all its code.
