### ISSUE TITLE
Salesforce SDK 5.0 hybrid application wrapped with AirWatch - No login screen

### ISSUE THREAD

**Issue by neerajsoni** [forcedotcom/SalesforceMobileSDK-iOS#2026]
1. Version of Mobile SDK Used: 5.0
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: 10.3.1
4. Device: Any iOS device
5. Steps to reproduce: Create new app and wrap using airwatch app wrapping tool
6. Actual behavior: It freezes on "Loading..." screen
7. Expected Behavior: Should show login screen and enter into app after login

Hybrid application using Salesforce SDK 5.0 wrapped with AirWatch

A Hybrid application using Salesforce SDK 5.0, we are able to successfully login (OAuth) and run the application.

We tried to wrap (to run inside a container) the application using AirWatch we started facing issues.

When we run the wrapped application, it runs inside the airwatch container. It freezes on "Loading..." screen (attached the screenshot) and does not show the salesforce login screen.

On digging into it, we found that it is InitialView (with InitialViewController) of Salesforce Mobile SDK
which does not proceed to the login screen. 

Any idea of what is causing it not working after wrapping it?

![img_4492](https://cloud.githubusercontent.com/assets/1239964/25681803/a5b33620-3023-11e7-9003-8b4bcfd4a09c.jpeg)

**Comment by trooper2013** [comment]
@neerajsoni  Can you please try this out with 5.1.

**Comment by neerajsoni** [comment]
Version of Mobile SDK Used: 5.1

There is no change in the behaviour, I still see the freeze at "Loading..." screen 

Could you not close this ticket without solution?

**Comment by neerajsoni** [comment]
I know this is not a common combination of technology stack but if anyone has seen it or wants to try out to help.

Thanks!

**Comment by davidfekke** [comment]
Neerag,

Are you stuck on the loading screen, or is it just displaying a blank white
screen?

**Comment by neerajsoni** [comment]
I am stuck on the loading screen. The screenshot in my post is the only screen that stays forever on the phone. @davidfekke

**Comment by davidfekke** [comment]
Are you starting from the one of the templates? Are you using hybrid-local
or hybrid-remote?

**Comment by neerajsoni** [comment]
Its is hybrid-local which contains all the stuff locally. 

And the application's landing page is not et hit. It is has stopped just before login page. Having said that, the login page does not appear.

Just want to make a note here, this app works fine without wrapping using air watch.
But when wrapped then it freezes on to the loading screen only.

**Comment by bhariharan** [comment]
@neerajsoni As you have mentioned in your post, the app works fine without the `AirWatch MDM` wrapper. We haven't tested the `AirWatch` wrapping use case nor do we support it. It looks like something in the `AirWatch SDK` is causing it to break. Please work with `AirWatch` on getting to the bottom of the issue. There's little we can do without knowing what the `AirWatch SDK` does. Besides, our `Mobile SDK` is open source. You're welcome to make changes to the `Mobile SDK` to suit your needs.
