### ISSUE TITLE
Unable to set a custom domain on SFUserAccountManager - Referenced from #2018

### ISSUE THREAD

**Issue by sahitya8e7** [forcedotcom/SalesforceMobileSDK-iOS#2028]
Please fill out the following details:

Version of Mobile SDK Used: 5.1
Issue found in Native App or Hybrid App: Native iOS
OS Version: iOS 10
Device: iPhone 7 plus
Steps to reproduce: Upgrade the Salesforce Mobile SDK from 4.2 to 5.1
Actual behavior: The build fails with the following error:
error: Launch already in progress
Expected Behavior: The project should build successfully.
Error Log: Launch already in progress

the new way of setting the loginHost i.e., [SFAuthenticationManager sharedManager].loginHost does not work either.

The scenario is as follows:
We **login** to the app. - A loginhost is set and the instance is launched.

We **logout** from the app. - Call made: SFAuthenticationManager.shared().logout()
This step is supposed to set the isLaunching property of SFAuthenticationManager to false. But that doesnt seem to be happening.

We set the **loginHost** to **a different value** and try to login by calling launch API on SalesforceSDKManager. - This fails with the error "Launch already in progress."

**_My analysis_**:
In logoutUser: API of SFAuthenticationManager, there is a check in the beginning for

if (user == nil)
This fails since the user is nil.
This used to work before because even after logout, the user was set to a temporary user

<SFUserAccount username=(null) fullName=(null) accessScopes={...}
Can you please look into this?

**Comment by trooper2013** [comment]
@sahitya8e7 I'm not sure if you are reporting that setting custom domain doesn't work using [SFAuthenticationManager sharedManager].loginHost or if subsequent attempt to launch the app doesn't work.  I tried both of these scenarios and It looks good. Could you use forceios to create a sample project and try the scenario out first?  You  maybe inadvertently calling launch twice? Perhaps paste the snippet of code that does what you are describing (handling of login and logout)?

**Comment by wmathurin** [comment]
With the information provided, we cannot make any progress figuring out if there is indeed a bug. Please re-open this issue if you think there is a bug and please answer all the questions we asked in our May 10th post. Thanks.
