### ISSUE TITLE
Session Timeout Crash

### ISSUE THREAD

**Issue by mikecaulley** [forcedotcom/SalesforceMobileSDK-iOS#2031]
1. Version of Mobile SDK Used: 5.1
2. Issue found in Native App or Hybrid App: Native App - Swift
3. OS Version: 10.3.1
4. Device: iPad Air 2
5. Steps to reproduce: Set the connected app session timeout to 15 minutes. Allow the app to sit in the foreground for greater than 15 minutes. Perform any network request, i.e. a SFRestRequest.
6. Actual behavior:  The app crashes.
7. Expected Behavior: The app goes back to the login screen. SSO webview in our case.
8. Error Log:
<img width="1440" alt="screen shot 2017-05-08 at 9 31 51 am" src="https://cloud.githubusercontent.com/assets/8548731/25806709/21e502f8-33d2-11e7-99e7-0aa049899d37.png">

**Comment by bhariharan** [comment]
@mikecaulley Interesting. I can't reproduce this in our sample app. Session refresh appears to work fine for me and the request goes through successfully. Could you set some breakpoints in `SFRestAPI.m` in the `replayRequestIfRequired` method and let me know what the response is there? The code in there is responsible for the refresh flow and replays the request. Also, what REST request are you making?

**Comment by mikecaulley** [comment]
I think it may have to do with a physical device vs simulator. I'll try to get some testing in over the next few days and post back here with my findings.

**Comment by mikecaulley** [comment]
This seems to be a simulator only issue, we can mark it as closed for now.

**Comment by bhariharan** [comment]
Sounds good @mikecaulley.
