### ISSUE TITLE
"hidden iFrame" not present in advanced visualforce remoting refresh flow

### ISSUE THREAD

**Issue by mfpaulallen** [forcedotcom/SalesforceMobileSDK-iOS#2035]
1. Version of Mobile SDK Used: iOS 5.01
2. Issue found in Native App or Hybrid App: Hybrid Remote + Visualforce Remoting + UIWebView to allow use of localhost
3. OS Version:  OS X 10.12.4
4. Device:  XCode iOS Simulator 10.3
5. Steps to reproduce: 

     Wait for VisualForce tokens to expire while refresh tokens are still valid and try to using the OAuth Plugin to authenticate following the example in the Mobile SDK developer guide page 190:

````
// Refresh oauth token
cordova.require("com.salesforce.plugin.oauth").authenticate(
    function(creds) {
        // Reload hidden iframe that points to a blank page to
        // to refresh Visualforce domain cookies
        var iframe = document.getElementById("blankIframeId");
        iframe.src = src;
        // Refresh CSRF cookie
        // Get the provider array
        var providers = Visualforce.remoting.Manager.providers;
        // Get the last provider in the arrays (usually only one)
        var provider = Visualforce.remoting.last;
        provider.refresh(function() {
            //Retry call for a seamless user experience
        });
    },
    function(error) {
        console.log("Refresh failed");
    }
);
````

6. Actual behavior:

lots of problems:

````
cordova.require("com.salesforce.plugin.oauth").authenticate(
    function(creds) {
        var iframe = document.getElementById("blankIframeId");  //  <<<<< this is null
        iframe.src = src; //  ReferenceError: Can't find variable: src  -- where is this supposed to be defined?

        // Get the provider array
        var providers = Visualforce.remoting.Manager.providers;   //  WHY DO THIS? What do we do with providers array?

        // Get the last provider in the arrays (usually only one)
        var provider = Visualforce.remoting.last;
        provider.refresh(function() {  
           // running provder.refresh, I receive uncaught error SyntaxError: Unexpected token '<'  
               
               // CALLBACK IS NEVER CALLED

        });
    },
    function(error) {
        console.log("Refresh failed");
    }
);
````

I do see among my elements two  iframes -- one is for cordova ready:
````<iframe src="gap://ready" style="display: none;"></iframe>````

and another which is blank and hidden but does not have an ID:
````<iframe style="visibility: hidden !important; width: 0px !important; height: 0px !important; position: absolute !important; border: 0px !important;" src=""></iframe>````

this iframe.src === ''

7. Expected Behavior:

    it should work.  my callback should be called.  and my visualforce csrf tokens should be refreshed.

8. Error Log:

  I receive uncaught error while calling provider.refresh(callback)
````
[Error] SyntaxError: Unexpected token '<'
	eval (VFRemote.js:80:259)
	b (VFRemote.js:80:259)
	(anonymous function) (VFRemote.js:83:123)
	(anonymous function) (VFRemote.js:129)
	handleResponse (VFRemote.js:75:111)
	a (VFRemote.js:39:86)
	(anonymous function) (VFRemote.js:40:309)
````

callback is never called, session remains invalid.

Please advise.

**Comment by wmathurin** [comment]
The Mobile SDK does not modify the HTML/JavaScript loaded in the webview, so if the webview complains about a missing element, it means it is really missing.

I recommend you debug from safari: [steps](https://developer.apple.com/library/content/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/GettingStarted/GettingStarted.html) to see what your page actually holds.

Could you also continue this thread on our [G+ community](https://plus.google.com/communities/114225252149514546445). We reserve github issues for actual bugs in the Mobile SDK.
