### ISSUE TITLE
Salesforce Mobile SDK issue

### ISSUE THREAD

**Issue by wincychan** [forcedotcom/SalesforceMobileSDK-iOS#2049]
Please fill out the following details:

1. Version of Mobile SDK Used: 
5.1.0
2. Issue found in Native App or Hybrid App:
Native APP - React Native
3. OS Version:
10.12.4
4. Device:
iPhone 6
5. Steps to reproduce:
I have an issue when I tried to use Salesforce mobile SDK for React Native application. When I followed the steps at https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/react_native_intro.htm to create react native app by using Salesforce mobile SDK, salesforce standard login page was shown. I want to build simple customize login UI page without verification flow to get salesforce record. However, there's no way to skip salesforce standard login page with verification code flow to log in when salesforce mobile SDK is used. 

Image attached below
(A) and (B) are salesforce standard page when using salesforce mobile SDK
(C) is the app that I want to build with customize login UI and using salesforce mobile SDK but no verification flow

6. Actual behavior:
![a salesforce standard login page](https://cloud.githubusercontent.com/assets/28753498/26148928/e5efc1d8-3b2a-11e7-9b6a-1d92791c2773.png)
![b salesforce standard verification flow](https://cloud.githubusercontent.com/assets/28753498/26148934/ea42bbb4-3b2a-11e7-9010-c0ea1325d70b.png)

7. Expected Behavior:
![c customize login ui without verification flow](https://cloud.githubusercontent.com/assets/28753498/26148941/ee8a40e8-3b2a-11e7-8560-be627046db5f.png)

8. Error Log:
N/A

**Comment by bhariharan** [comment]
@wincychan If you want to keep screen `[A]` as the login screen and get rid of screen `[B]`, this can be done using configuration properties on the org that you're using. If you want to build a completely customized login screen like `[C]`, you need to build a custom login screen on the server side. There are a few options for this, such as community login pages, SSO login pages, etc. None of these are controlled or configured on the client side (in `Mobile SDK`). We simply display the configured login page within a `WebView` to perform authentication.

**Comment by helloniklas** [comment]
@bhariharan so the only way to authenticate is through your web view? No way of supplying the SDK with a valid token form other ways of authentication?

**Comment by bhariharan** [comment]
Currently, there is no native login support. The login process is entirely through the `WebView`.

**Comment by wincychan** [comment]
@bhariharan How to set configuration properties on the org to get rid of the screen [B] ?

**Comment by hkusoft** [comment]
@helenren I agree with @bhariharan, as is documented in [official developer doc](https://developer.salesforce.com/page/Digging_Deeper_into_OAuth_2.0_on_Force.com)

> Note that you should **avoid** the username and password flow wherever possible, since the other flows free your application from having to manage, store and protect user credentials, but be careful - if you use the web server profile you must store the client secret securely.

**Comment by helloniklas** [comment]
@hkusoft @bhariharan is there a way to set the valid auth tokens on the Sdk once they've been retrieved, say if single sign on via SAML provider has been enabled. Or could this just be added to the headers manually.

**Comment by bhariharan** [comment]
@helloniklas We do support SSO sign in flow. As long as you add the SSO endpoint you're using as the custom host in the Mobile SDK, we will kick off the sign in flow from there.
