### ISSUE TITLE
Setting auth token from external SAML provider on API

### ISSUE THREAD

**Issue by helloniklas** [forcedotcom/SalesforceMobileSDK-iOS#2050]
So we're using auth0 with SAML integration for authenticating to a salesforce comunity. 

How can I set the auth token on this API after retrieving it through auth0?

**Comment by bhariharan** [comment]
@helloniklas This forum is reserved for bugs in `Mobile SDK` code. Please post other queries or discussions in our [Google+ community](https://plus.google.com/u/1/communities/114225252149514546445).

**Comment by helloniklas** [comment]
@bhariharan thing is no one ever answer anything on that forum. Guess not many people are using this SDK...

**Comment by bhariharan** [comment]
@helloniklas We do make an effort to engage on the community. We have a large number of customers using this product.
