### ISSUE TITLE
pod error

### ISSUE THREAD

**Issue by Luffz** [forcedotcom/SalesforceMobileSDK-iOS#2051]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.1.0
2. Issue found in Native App or Hybrid App:Native
3. OS Version:
4. Device:
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

SalesforceAnalytics,SmartStore,SmartSync pod install Has been an error！

Installing CocoaLumberjack (2.4.0)
Installing SQLCipher (3.4.1)
Installing SalesforceSDKCore (5.1.0)
Installing SalesforceAnalytics (5.0.1)
Installing SmartStore (5.0.1)
Installing SmartSync (5.0.1)

[!] Error installing SmartSync
[!] /usr/bin/git -C /var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/d20170517-8231-h15zcn submodule update --init --recursive

Submodule 'external/CocoaLumberjack' (https://github.com/forcedotcom/CocoaLumberjack.git) registered for path 'external/CocoaLumberjack'
Submodule 'external/cordova-ios/cordova-ios' (https://github.com/apache/cordova-ios.git) registered for path 'external/cordova-ios/cordova-ios'
Submodule 'external/fmdb' (https://github.com/forcedotcom/fmdb) registered for path 'external/fmdb'
Submodule 'external/ocmock' (https://github.com/erikdoe/ocmock.git) registered for path 'external/ocmock'
Submodule 'external/react-native' (https://github.com/forcedotcom/react-native.git) registered for path 'external/react-native'
Submodule 'external/shared' (https://github.com/forcedotcom/SalesforceMobileSDK-Shared.git) registered for path 'external/shared'
Submodule 'external/wypopovercontroller' (https://github.com/sammcewan/WYPopoverController) registered for path 'external/wypopovercontroller'
Cloning into '/private/var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/d20170517-8231-h15zcn/external/CocoaLumberjack'...
Cloning into '/private/var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/d20170517-8231-h15zcn/external/cordova-ios/cordova-ios'...
Cloning into '/private/var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/d20170517-8231-h15zcn/external/fmdb'...
Cloning into '/private/var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/d20170517-8231-h15zcn/external/ocmock'...
Cloning into '/private/var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/d20170517-8231-h15zcn/external/react-native'...
error: RPC failed; curl 56 SSLRead() return error -9806
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://github.com/forcedotcom/react-native.git' into submodule path '/private/var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/d20170517-8231-h15zcn/external/react-native' failed
Failed to clone 'external/react-native'. Retry scheduled
Cloning into '/private/var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/d20170517-8231-h15zcn/external/shared'...
Cloning into '/private/var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/d20170517-8231-h15zcn/external/wypopovercontroller'...
Cloning into '/private/var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/d20170517-8231-h15zcn/external/react-native'...
error: RPC failed; curl 56 SSLRead() return error -9806
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://github.com/forcedotcom/react-native.git' into submodule path '/private/var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/d20170517-8231-h15zcn/external/react-native' failed
Failed to clone 'external/react-native' a second time, aborting

**Comment by Luffz** [comment]
[!] Error installing SmartSync
[!] /usr/local/bin/git clone https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git /var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/d20170518-7944-yjjofr --template= --single-branch --depth 1 --branch v5.1.0

Cloning into '/var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/d20170518-7944-yjjofr'...
error: RPC failed; curl 56 SSLRead() return error -9806
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

5.1.0 error

**Comment by wmathurin** [comment]
Did you create your application with forceios?
What does your podfile look like?

**Comment by Luffz** [comment]
that is a error of  create application with forceios 
Installing npm dependencies
npm ERR! git submodule -q update --init --recursive: error: RPC failed; curl 56 SSLRead() return error -36
npm ERR! git submodule -q update --init --recursive: fatal: The remote end hung up unexpectedly
npm ERR! git submodule -q update --init --recursive: fatal: early EOF
npm ERR! git submodule -q update --init --recursive: fatal: index-pack failed
npm ERR! git submodule -q update --init --recursive: fatal: clone of 'https://github.com/apache/cordova-ios.git' into submodule path '/private/var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/npm-7554-6ed2b614/git-cache-d56a4014/923446f020b2f904ac0a4fe3133cb579d5102c33/external/cordova-ios/cordova-ios' failed
npm ERR! git submodule -q update --init --recursive: Failed to clone 'external/cordova-ios/cordova-ios'. Retry scheduled
npm ERR! git submodule -q update --init --recursive: error: RPC failed; curl 56 SSLRead() return error -9806
npm ERR! git submodule -q update --init --recursive: fatal: The remote end hung up unexpectedly
npm ERR! git submodule -q update --init --recursive: fatal: early EOF
npm ERR! git submodule -q update --init --recursive: fatal: index-pack failed
npm ERR! git submodule -q update --init --recursive: fatal: clone of 'https://github.com/forcedotcom/react-native.git' into submodule path '/private/var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/npm-7554-6ed2b614/git-cache-d56a4014/923446f020b2f904ac0a4fe3133cb579d5102c33/external/react-native' failed
npm ERR! git submodule -q update --init --recursive: Failed to clone 'external/react-native'. Retry scheduled
npm ERR! git submodule -q update --init --recursive: fatal: unable to access 'https://github.com/forcedotcom/SalesforceMobileSDK-Shared.git/': SSLRead() return error -9806
npm ERR! git submodule -q update --init --recursive: fatal: clone of 'https://github.com/forcedotcom/SalesforceMobileSDK-Shared.git' into submodule path '/private/var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/npm-7554-6ed2b614/git-cache-d56a4014/923446f020b2f904ac0a4fe3133cb579d5102c33/external/shared' failed
npm ERR! git submodule -q update --init --recursive: Failed to clone 'external/shared'. Retry scheduled
npm ERR! git submodule -q update --init --recursive: error: RPC failed; curl 56 SSLRead() return error -9806
npm ERR! git submodule -q update --init --recursive: fatal: The remote end hung up unexpectedly
npm ERR! git submodule -q update --init --recursive: fatal: early EOF
npm ERR! git submodule -q update --init --recursive: fatal: index-pack failed
npm ERR! git submodule -q update --init --recursive: fatal: clone of 'https://github.com/apache/cordova-ios.git' into submodule path '/private/var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/npm-7554-6ed2b614/git-cache-d56a4014/923446f020b2f904ac0a4fe3133cb579d5102c33/external/cordova-ios/cordova-ios' failed
npm ERR! git submodule -q update --init --recursive: Failed to clone 'external/cordova-ios/cordova-ios' a second time, aborting
npm ERR! git submodule -q update --init --recursive: 
npm ERR! code 1
npm ERR! Command failed: git submodule -q update --init --recursive
npm ERR! error: RPC failed; curl 56 SSLRead() return error -36
npm ERR! fatal: The remote end hung up unexpectedly
npm ERR! fatal: early EOF
npm ERR! fatal: index-pack failed
npm ERR! fatal: clone of 'https://github.com/apache/cordova-ios.git' into submodule path '/private/var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/npm-7554-6ed2b614/git-cache-d56a4014/923446f020b2f904ac0a4fe3133cb579d5102c33/external/cordova-ios/cordova-ios' failed
npm ERR! Failed to clone 'external/cordova-ios/cordova-ios'. Retry scheduled
npm ERR! error: RPC failed; curl 56 SSLRead() return error -9806
npm ERR! fatal: The remote end hung up unexpectedly
npm ERR! fatal: early EOF
npm ERR! fatal: index-pack failed
npm ERR! fatal: clone of 'https://github.com/forcedotcom/react-native.git' into submodule path '/private/var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/npm-7554-6ed2b614/git-cache-d56a4014/923446f020b2f904ac0a4fe3133cb579d5102c33/external/react-native' failed
npm ERR! Failed to clone 'external/react-native'. Retry scheduled
npm ERR! fatal: unable to access 'https://github.com/forcedotcom/SalesforceMobileSDK-Shared.git/': SSLRead() return error -9806
npm ERR! fatal: clone of 'https://github.com/forcedotcom/SalesforceMobileSDK-Shared.git' into submodule path '/private/var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/npm-7554-6ed2b614/git-cache-d56a4014/923446f020b2f904ac0a4fe3133cb579d5102c33/external/shared' failed
npm ERR! Failed to clone 'external/shared'. Retry scheduled
npm ERR! error: RPC failed; curl 56 SSLRead() return error -9806
npm ERR! fatal: The remote end hung up unexpectedly
npm ERR! fatal: early EOF
npm ERR! fatal: index-pack failed
npm ERR! fatal: clone of 'https://github.com/apache/cordova-ios.git' into submodule path '/private/var/folders/ys/nnx8098s4_vcs1wlf899nym40000gn/T/npm-7554-6ed2b614/git-cache-d56a4014/923446f020b2f904ac0a4fe3133cb579d5102c33/external/cordova-ios/cordova-ios' failed
npm ERR! Failed to clone 'external/cordova-ios/cordova-ios' a second time, aborting
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/coopercher/.npm/_logs/2017-05-18T06_08_55_161Z-debug.log
/Users/coopercher
forceios failed

Command failed: npm install

forceios  method to create the failure,and i use pod ，
Podfile as follows

target 'SalesforceDemo1' do
source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git' # needs to be first 
source 'https://github.com/CocoaPods/Specs.git'

pod 'SalesforceSDKCore’
pod 'SmartStore', ‘~> 5.0.0’
pod 'SalesforceAnalytics’, ‘~> 5.0.0’
pod 'SmartSync’, ‘~> 5.0.0’
end

**Comment by wmathurin** [comment]
Can you install version 5.1.0 of forceios and try again?
Also what version of pod, npm and node do you have installed on your system.

**Comment by wmathurin** [comment]
Your error is similar to the one reported here http://stackoverflow.com/questions/38864141/ei-capitan-10-11-pod-setup-endup-with-56-sslread-return-error-36

Could it be a VPN issue?

**Comment by Luffz** [comment]
version as follow
xx:~ coopercher$ forceios version
forceios version 5.1.0
xx:~ coopercher$ pod --version
1.2.0
xx:~ coopercher$ node -v
v6.10.2
xx:~ coopercher$ npm -v
4.6.1

Podfile import SDK and forceios create all failed
I tried to open and close the VPN failed to create the whole

**Comment by Luffz** [comment]
Thank you very much, I find the problem, is the problem of VPN
