### ISSUE TITLE
Documents can't find

### ISSUE THREAD

**Issue by Luffz** [forcedotcom/SalesforceMobileSDK-iOS#2059]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.1.0
2. Issue found in Native App or Hybrid App:Native
3. OS Version:
4. Device:
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

In  Mobile SDK,how can i show my head portrait, url as follow:
https://celnet--c.ap1.content.force.com/profilephoto/7299000000031ej/F

**Comment by urthakkar** [comment]
@Luffz please use our Google community for such queries and benefit from larger developer audience on the platform.  https://plus.google.com/u/1/communities/114225252149514546445
