### ISSUE TITLE
SFSDK 5.1  movement to Coocoapods

### ISSUE THREAD

**Issue by SrinivasGit049** [forcedotcom/SalesforceMobileSDK-iOS#2060]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.1
2. iOS Native App 
3.All versions
4. All devices
5. pod update ‘SalesforceRestAPI’
6. Downloading 4.3.1 version
7. Download 5.1 version

**Comment by Michaelcaulley** [comment]
My pods are listed below. The SalesforceRestAPI should now be part of the core pod.
    
pod 'SmartSync', '5.1'
pod 'SmartStore', '5.1'
pod 'SalesforceAnalytics', '5.1'
pod 'SalesforceSDKCore', '5.1'

**Comment by bhariharan** [comment]
@SrinivasGit049 `SalesforceRestAPI` has been rolled into `SalesforceSDKCore`. Updating `SalesforceSDKCore` is sufficient.
