### ISSUE TITLE
Custom Endpoint API rest not working.

### ISSUE THREAD

**Issue by tzzx89** [forcedotcom/SalesforceMobileSDK-iOS#2061]
Please fill out the following details:

1. Version of Mobile SDK Used: 
5.1
2. Issue found in Native App or Hybrid App:
Native
3. OS Version:
IOS
4. Device:
Iphone 6s plus
5. Steps to reproduce:
I have a customised Endpoint called
'/services/apexrest/inspection/records/'
When use the sendRequest for react-native-force/src/react.force.net.js, I got exception with the release.
I tried sendRequest ('/services/apexrest', '/inspection/records/', successCB, errorCB, method, payload, headerParams, fileParams);

It doesn't work at all.
It was working for a previous version.

6. Actual behavior:
7. Expected Behavior:
8. Error Log:
Exception '-[__NSSingleEntryDictionaryI stringByAddingPercentEncodingWithAllowedCharacters:]: unrecognized selector sent to instance 0x17023c9c0' was thrown while invoking sendRequest on target SFNetReactBridge with params (
        {
        endPoint = "/services";
        fileParams =         {
        };
        headerParams =         {
        };
        method = POST;
        path = "/apexrest/inspection/records/";
        queryParams =         {
            dataFeed =             {
                changeRequests =                 (
                );
            };
        };
    },
    131
)

**Comment by bhariharan** [comment]
@tzzx89 There was a bug with `POST` requests in certain cases on the plugin. I have fixed it [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2021/files#diff-1b08e12298bbdf76ba39c229e7e56283R60). Could you cherry-pick that pull request and try it again? Let me know if that works.

**Comment by tzzx89** [comment]
@bhariharan ,

Thanks a lot. That really solves the issue.
