### ISSUE TITLE
SFAuthenticationViewHandler is calling back when calling SFRestAPI after login

### ISSUE THREAD

**Issue by SrinivasGit049** [forcedotcom/SalesforceMobileSDK-iOS#2064]
Please fill out the following details:
1. 5.1: 
2.Native app:
3. 10.3:
4. Simulator:
5. Steps to reproduce:

    SFAuthenticationManager *authenticationManager = [SFAuthenticationManager sharedManager];
    [authenticationManager setOauthClientId:json[@"oauth.clientId"]];
    [authenticationManager setOauthCompletionUrl:json[@"oauth.redirectUri"]];
    [authenticationManager setScopes:[NSSet setWithArray:@[@"api", @"web", @"full"]]];        
    [authenticationManager setLoginHost:@"login.salesforce.com"];

    SFAuthenticationViewHandler *authViewHandler = [[SFAuthenticationViewHandler alloc]initWithDisplayBlock:^(SFAuthenticationManager *authManager, WKWebView *webView) {
   Logic for loading login screen using webView instance i.e ex:[self.view addsubview:webView]
}
        [[SFAuthenticationManager sharedManager] loginWithCompletion:(SFOAuthFlowSuccessCallbackBlock)^(SFOAuthInfo *info) {
            SFOAuthCoordinator *coordinator = [SFAuthenticationManager sharedManager].coordinator;
            [[SFRestAPI sharedInstance] setCoordinator:coordinator];
            [[SFUserAccountManager sharedInstance] applyCredentials:coordinator.credentials];
            [self getObject)
}failure:{

}

-(void)getObject {
SFRestRequest *request = [[SFRestAPI sharedInstance] requestForRetrieveWithObjectType:@"SomeObject"
                                                                                 objectId:coordinator.credentials.userId
                                                                                fieldList:nil];
    [[SFRestAPI sharedInstance] sendRESTRequest:request failBlock:^(NSError *e) {

}completion{

}
}
When we execute above code the code is calling authViewHandler display block after SFRestAPI in getObjectMethod.
Hence we are redirected again to login screen
6. Actual behavior:
 authViewHandler display block is called
7. Expected Behavior:
 authViewHandler display block should not be called instaed completion block of requestForRetrieveWithObjectType should be called.

This is working fine in 4.3.x sdk and prior but not in 5.1 SFSDK

**Comment by bhariharan** [comment]
@SrinivasGit049 In `Mobile SDK 5.1` we require apps to explicitly set `currentUser` in certain auth flows. In this specific case, please replace your `loginWithCompletion` call with the following:
```
[[SFAuthenticationManager sharedManager] loginWithCompletion:^(SFOAuthInfo *authInfo, SFUserAccount *userAccount) {
        [SFUserAccountManager sharedInstance].currentUser = userAccount;
        [self getObject];
} failure:^(SFOAuthInfo *authInfo, NSError *authError) {

}];
```
Let me know if that works.

**Comment by SrinivasGit049** [comment]
This worked for us.We were able to login successfully.
But we are facing a new issue where app is redirecting to login every time we kill and relaunch the app instead of logging in directly using Oauth mechanism.

Steps to reproduce:
Login for the first time as below.
[[SFAuthenticationManager sharedManager] loginWithCompletion:(SFOAuthFlowSuccessCallbackBlock)^(SFOAuthInfo *info) {
SFOAuthCoordinator *coordinator = [SFAuthenticationManager sharedManager].coordinator;
[[SFRestAPI sharedInstance] setCoordinator:coordinator];
[[SFUserAccountManager sharedInstance] applyCredentials:coordinator.credentials];
[self getObject)
}failure:{

}
After successful login i.e once completion block of [[SFAuthenticationManager sharedManager] loginWithCompletion is called and  completion block of rest api inside getObject is called, kill the app and relaunch/re-run.

After relaunch/re-run, Once again after executing [SFAuthenticationManager sharedManager] loginWithCompletion: the 
[[SFAuthenticationViewHandler alloc]initWithDisplayBlock:^(SFAuthenticationManager *authManager, WKWebView *webView) is called instead of logging in automatically using Oauth of last login and we are redirected  to login screen again.

In SDK 4.x and above the completion handler of [[SFAuthenticationManager sharedManager] loginWithCompletion was getting called after we re-launch or re-run the app.

But in 5.1 it redirecting into login screen

**Comment by bhariharan** [comment]
@SrinivasGit049 Starting with `5.1`, `loginWithCompletion` is meant to be called only when the app requires authentication with the `WebView`. In other words, it should be called only to kick off the login process. When the app is killed and started up, or on the first-time startup for that matter, you should be using `[[SalesforceSDKManager sharedManager] launch];`. This will launch the app with the existing user or kick off login flow if no user is present. Take a look at how we do this in our sample app [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/native/SampleApps/SmartSyncExplorer/SmartSyncExplorer/Classes/AppDelegate.m#L119). Please follow the same pattern in your app's `AppDelegate`.

**Comment by SrinivasGit049** [comment]
Thank you this worked for me!
