### ISSUE TITLE
Getting malformed query when we try to pass datetime field in SOQL query through performSOQLQuery method

### ISSUE THREAD

**Issue by SrinivasGit049** [forcedotcom/SalesforceMobileSDK-iOS#2066]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.1
2. Issue found in Native App or Hybrid App:NATIVE
3. OS Version:iOS 10.3
4. Device:iPad Air simulator
5. Steps to reproduce:
Try to send an soql query with having date value of following type with 
ex:[SFRestAPI sharedInstance]performSOQLQuery:@"Select Name from Account where LastModifiedDate > 2017-03-21T12:11:06.000+0000"  failure:  success];

6. Actual behavior:
performSOQLQuery failure block is  is getting called with malformed query error
7. Expected Behavior:
Completion handler should be called with result of query containing records
8. Error Log:
errorCode = "MALFORMED_QUERY";
        message = "\nLastModifiedDate > 2017-03-21T12:11:06.000 0000\n                                         ^\nERROR at Row:1:Column:780\nline 1:780 no viable alternative at character ' '";

This was working fine in SFSDK 4.x but broken in 5.1

**Comment by bhariharan** [comment]
Thanks for reporting. I'll take a look.

**Comment by wmathurin** [comment]
I confirmed the bug.
It looks like the + is not url encoded (even though we use [NSURLQueryItems](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/RestAPI/SFRestRequest.m#L150).

**Comment by wmathurin** [comment]
Others have reported the same issue (for instance [here](https://stackoverflow.com/questions/41273994/special-characters-not-being-encoded-properly-inside-urlqueryitems). 
We will figure out a work around for our next release.

**Comment by wmathurin** [comment]
Fixed in dev.
