### ISSUE TITLE
Switching between sandbox and production in login screen is not happening at first attempt

### ISSUE THREAD

**Issue by SrinivasGit049** [forcedotcom/SalesforceMobileSDK-iOS#2069]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.1
2. Issue found in Native App or Hybrid App:Native
3. OS Version:iOS 10.3
4. Device:iPad Pro Simultor
5. Steps to reproduce:
Once login screen loads click on the settings icon on the top right.
Switch the login to sandbox from production.
6. Actual behavior:
The login screen doesn't load and it turns to dark blue instead.
<img width="678" alt="screen shot 2017-06-01 at 11 21 34 am" src="https://cloud.githubusercontent.com/assets/20944421/26666110/c73895a2-46bb-11e7-9f31-ce95e31868cf.png">
7. Expected Behavior:
The login screen should reload and should switch to sandbox login screen

**Comment by bhariharan** [comment]
@SrinivasGit049 Are you able to reproduce this on any of our sample apps? I can't seem to reproduce this issue.

**Comment by SrinivasGit049** [comment]
Thank you for your feedback.You can please close this issue as it worked for me after adding following code

    [SalesforceSDKManager sharedManager].switchUserAction = ^(SFUserAccount *fromUser, SFUserAccount *toUser) {
        [[SalesforceSDKManager sharedManager] launch];
    };
