### ISSUE TITLE
Build Failed: Value of optional type '[SFUserAccount]?' not unwrapped

### ISSUE THREAD

**Issue by aravindtrue** [forcedotcom/SalesforceMobileSDK-iOS#2072]
A newbie to native swift development!

Please fill out the following details:

1. Version of Mobile SDK Used: 5.1.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 10.12.5
4. Device: iPhone 6
5. Steps to reproduce: 
- forceios create
- native_swift
- Open in Xcode
- Build and run
8. Error:
<img width="724" alt="screen shot 2017-06-03 at 10 51 36 pm" src="https://cloud.githubusercontent.com/assets/5163972/26759529/e44ddcec-48b4-11e7-9bd4-a0ab92bb1938.png">

Solving the above issue,
![ttt](https://cloud.githubusercontent.com/assets/5163972/26764003/5f4020b4-4913-11e7-834f-f78addba03f0.png)

**Comment by aravindtrue** [comment]
Any updates? Not able to start the development.

**Comment by wmathurin** [comment]
It looks like our swift template is a bit outdated. We will fix it in our next release.

In the meantime simply change the following line in the generated application AppDelegate.swift:
Replace
```swift
SFUserAccountManager.sharedInstance().currentUser = allAccounts[0]
```
with
```swift
SFUserAccountManager.sharedInstance().currentUser = allAccounts![0]
```

**Comment by wmathurin** [comment]
Fixed in dev (see PR linked above).
