### ISSUE TITLE
app create twice record on salesforce at the same time or duplicated records created on Salesforce

### ISSUE THREAD

**Issue by quoctc** [forcedotcom/SalesforceMobileSDK-iOS#2080]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.0.1
2. Issue found in Native App or Hybrid App: native
3. OS Version: iOS 9.0 and above
4. Device: iPad
5. Steps to reproduce: call this function: 
[target createOnServer:objectType fields:fields completionBlock:completeBlockCreate failBlock:failedBlock];
when the app calling that function, background app and after 2 seconds foreground app. Sometime app will call that function or inside functions twice and it was created two records on Salesforce server. It's hard to reproduce.  My client has just got only one time. But I want to notify to see anybody have the same issue with me
6. Actual behavior:
7. Expected Behavior:
8. Error Log:
duplicated records created on Salesforce

**Comment by wmathurin** [comment]
Are you sure you did not have duplicated record in SmartStore?

As you see [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SmartSync/SmartSync/Classes/Manager/SFSmartSyncSyncManager.m#L434), we collect the "dirty" records and then iterate through them. So it's hard to see how the same record could by synced up twice.

**Comment by wmathurin** [comment]
Closing since we don't believe it's a bug with the SDK but rather a bug in your application (which allowed two copies of the same record to be created).

**Comment by quoctc** [comment]
No, It's not the application bug because I create a log when the user creates data and sync to Salesforce and all the information of data is same, and two records were created at the same time. Reviewed to the log, I see the app called to code below and my user background the app and foreground it 2 seconds later, I Logged and see the app call
```
case SFSyncUpTargetActionCreate:
            [self log:SFLogLevelInfo format:@"CREATE->RECORD TO SYNC UP: %@", sync.options.fieldlist];
            [target createOnServer:self record:record fieldlist:sync.options.fieldlist completionBlock:completeBlockCreate failBlock:failBlock];
            break;
```
The Logger just logged one line, but two records was created on Salesforce

**Comment by wmathurin** [comment]
All createOnServer does is to send a create request to the server (see [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/v5.0.1/libs/SmartSync/SmartSync/Classes/Util/SFSyncUpTarget.m#L157)).

Could you add a log line when the network request goes out ([there](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/v5.0.1/libs/SmartSync/SmartSync/Classes/Util/SFSmartSyncNetworkUtils.m#L36))?

Or better yet, you could upgrade to Mobile SDK 5.1 and make sure to do the following in your AppDelegate.m:
```Objective-c
[SFSyncManagerLogger setLevel:SFLogLevelDebug];
```
That way you will see very detailed log lines (including network requests etc).
