### ISSUE TITLE
Issues using FMDB via Cocoapods

### ISSUE THREAD

**Issue by puckdevteam** [forcedotcom/SalesforceMobileSDK-iOS#2093]
This issue is related to: [https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1191](url)
It was marked as fixed, but after updating to version 5.1 we still have problems using FMDB.

We tested the following scenarios both in our project and in a project generated using the salesforce sdk tool forceios native:

1. Not adding the FMDB pod, and try to import FMDB from SmartStore. This does not compile, giving an error “FMDB.h” file not found. 

`#import <FMDB.h>`

2. Adding FMDB as a pod in Podfile. After running pod install, FMDB 2.7.2 is installed and we can import it without any errors. When building the project, SmartStore is complaining about it can not find ‘FMDatabase.h’. In this case is the Salesforce SDK that fails to build. 

`pod 'FMDB'`

3. We also tried using Salesforce specific pod for FMDB but in this case we got the same result described in related issue about SQLCipher/fts versions:
SQLCipher/fts (~> 3.3.1) required by FMDB/FMDB (4.0.2)
SQLCipher/fts (~> 3.4.0) required by SmartStore/SmartStore (4.2.0)

`pod 'FMDB', '4.0.2'`

We attach some samples.

[Samples.zip](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/1097845/Samples.zip)

We look forward to hearing from you!

**Comment by bhariharan** [comment]
@puckdevteam You don't need `FMDB` in your pod specs anymore, since `FMDB` is compiled as part of our `SmartStore` library. Running the latest `forceios` to generate a template app will add these pods:
```
Downloading dependencies
Installing CocoaLumberjack (2.4.0)
Installing SQLCipher (3.4.1)
Installing SalesforceAnalytics (5.1.0)
Installing SalesforceSDKCore (5.1.0)
Installing SmartStore (5.1.0)
Installing SmartSync (5.1.0)
Generating Pods project
```
Your pod file should look more like this:
```
source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

pod 'SalesforceSDKCore', '5.1.0'
pod 'SalesforceAnalytics', '5.1.0'
pod 'SmartStore', '5.1.0'
pod 'SmartSync', '5.1.0'
```

**Comment by bhariharan** [comment]
@puckdevteam In the attached `Sample1`, I removed the line `#import <FMDB.h>` from `RootViewController.m` and uncommented the line `pod 'SmartSync'` from `Podfile` to make sure `SmartSync` was included. I was able to compile and deploy the app successfully after that.
![screenshot](https://user-images.githubusercontent.com/1820287/27804801-c02f297c-5fe5-11e7-9ac5-f99aacc58d24.png)

**Comment by bhariharan** [comment]
I modified the `Podfile` for attached `Sample2` to this:
```
# Uncomment this line to define a global platform for your project
 platform :ios, '10.0'

project 'MyTrailNativeApp.xcodeproj'
target 'MyTrailNativeApp' do
    
source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

pod 'SalesforceAnalytics'
pod 'SalesforceSDKCore'
pod 'SmartStore'
pod 'SmartSync'

end
```
Then I ran `pod update` from the command line like this:
```
pod update
Update all pods
Updating local specs repositories

CocoaPods 1.3.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.3.0.beta.2

Analyzing dependencies
[!] The version of CocoaPods used to generate the lockfile (1.2.1) is higher than the version of the current executable (1.2.0). Incompatibility issues may arise.
Removing FMDB
Downloading dependencies
Using CocoaLumberjack (2.4.0)
Using SQLCipher (3.4.1)
Using SalesforceAnalytics (5.1.0)
Using SalesforceSDKCore (5.1.0)
Using SmartStore (5.1.0)
Installing SmartSync (5.1.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 4 dependencies from the Podfile and 6 total pods installed.
```
Then I removed `#import <FMDB/FMDB.h>` from `RootViewController.m`. It builds and runs successfully after that.

**Comment by puckdevteam** [comment]
What about if we need to use FMDB in one of our classes? 
How should we import it?

`#import <FMDB.h>
  #import <SmartStore/FMDB.h>`

_This return an error: FMDB.h file not found & SmartStore/FMDB.h file not found._

**Comment by bhariharan** [comment]
You can add your own version of `FMDB` from their pod specs directly and use it if you want. We will be making this simpler to do in our next release of `Mobile SDK`.

**Comment by puckdevteam** [comment]
We can not:
> Adding FMDB as a pod in Podfile. After running pod install, FMDB 2.7.2 is installed and we can import it without any errors. When building the project, SmartStore is complaining about it can not find ‘FMDatabase.h’. In this case, Salesforce SDK fails to build.

We will wait for your solution in next release.

**Comment by wmathurin** [comment]
It's fixed in dev (for our next release). See https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2136
