### ISSUE TITLE
Login completion block is not triggered once you call [[SFAuthenticationManager sharedManager] cancelAuthentication]

### ISSUE THREAD

**Issue by puckdevteam** [forcedotcom/SalesforceMobileSDK-iOS#2100]
Please fill out the following details:

1. Version of Mobile SDK Used: **5.1**
2. Issue found in Native App or Hybrid App: **Native**
3. OS Version: **All iOS versions**
4. Device: **all**
5. Steps to reproduce:

- Init SDK and Launch login process 
- Cancel authentication process to be able to reload the login screen
- Launch SalesforceSDKManager again

```
    [[SFLogger sharedLogger] setLogLevel:SFLogLevelDebug];    
    [SalesforceSDKManager setInstanceClass:[SalesforceSDKManagerWithSmartStore class]];    
    [[self class] setDefaultLoginHostForSalesforceSDK];
    [SalesforceSDKManager sharedManager].connectedAppId = kRemoteAccessConsumerKey;
    [SalesforceSDKManager sharedManager].connectedAppCallbackUri = kOAuthRedirectURI;
    [SalesforceSDKManager sharedManager].authScopes = @[@"api"];


    [[SFAuthenticationManager sharedManager] cancelAuthentication];


    [SalesforceSDKManager sharedManager].postLaunchAction = completionBlock;
    [SalesforceSDKManager sharedManager].launchErrorAction = failureBlock;
    [[SalesforceSDKManager sharedManager] launch];

```

6. Actual behavior:

If we call _[[SFAuthenticationManager sharedManager] cancelAuthentication],_ _postLaunchAction_ is not executed after calling back _[[SalesforceSDKManager sharedManager] launch]_; 

 _CancelAuthentication_ method resets several stuffs for SFAuthenticationManager, but __isLaunching_ property is not reseted, so it does not go forward in _launch_ implementation.

7. Expected Behavior:
_PostLaunchAction_ should be executed after canceling the authentication.

8. Error Log: No log

**Comment by khawkins** [comment]
It's generally considered an anti-pattern to directly manage authentication if `SalesforceSDKManager.authenticateAtLaunch` is set to `YES`.  Why are you trying to cancel authentication before you launch the SDK manager?

**Comment by puckdevteam** [comment]
Thank @khawkins for your fast answer. 

We do it because we need to reload our custom login screen under some circumstances to avoid a couple of issues on login process. Perhaps, there is another way to do what we need after updating the SDK, we don't know.
Let me explain to you the issues we have:

We have a custom login url to login, reset the password and sign up a new user. Those functionalities are implemented in the same login webView we load. There is navigation between them to go to the different options. Saying that, our problems come: 

1. Firstly, we call _launch_ to present the login screen. From that screen, we tap on a link to reset the password (this new screen is loaded in the same webView). Then, we tap on another link to go back to the default login screen. We type login credentials and login succeeds, but postLaunchAction, and completionBlock are never called. 

2. Besides, there is another issue. If we stay several minutes on login screen without performing the login and then we type the credential, an error page shows up, with no way to go back and blocks are not called either:
> "We can't authorise you because of an OAuth error. You didn't complete the approval process before it expired. Please try again."

To avoid those ones, we implement _SFAuthenticationManager_ delegate and we call _cancelAuthentication_ depending on some logic to reload the login screen. 

Is that ok?? should we take a different approach?

**Comment by khawkins** [comment]
> From that screen, we tap on a link to reset the password (this new screen is loaded in the same webView). Then, we tap on another link to go back to the default login screen.

I think the details will be important here.  Does all of this flow happen within the context of the same web view?  If so, I would guess that your navigation may be losing the callback state during the process.  For instance, a typical call to the `/authorize` endpoint looks like this:
```
https://login.salesforce.com/services/oauth2/authorize?client_id=[Connected App Consumer Key]&redirect_uri=[Connected App Redirect URI]&display=touch&response_type=token&scope=web%20api%20refresh_token
```
All of these parameters are necessary for initiating authentication, and the `redirect_uri` value in particular is what ties the response back to the calling app.  If this information is lost via "re-navigating" back to the login page, the authentication callbacks will not happen.

You need to make sure the initial parameters passed to your login page are included when you navigate to login after the reset password.

**Comment by puckdevteam** [comment]
Yes, everything happens within the same web view and you're right, it's happening exactly that, when we navigate to previous page, all parameters are lost. 

We will have a look to see how to keep them. 

Thank you.

**Comment by wmathurin** [comment]
Closing issue since it is not discussing an actual bug in the SDK.
