### ISSUE TITLE
Folder "Utilities" is on "SalesforceSDKCore" and on "SalesforceNetwork. Why?

### ISSUE THREAD

**Issue by CesarRN** [forcedotcom/SalesforceMobileSDK-iOS#2101]
Please fill out the following details:

1. Version of Mobile SDK Used: SalesforceSDKCore 5.3.1// SalesforceNetwork (4.3.1)
2. Issue found in Native App or Hybrid App:Native (Objetive C)
3. OS Version:iOS 10
4. Device:iPad
5. Steps to reproduce: Pod update
Using SalesforceNetwork (4.3.1)
Using SalesforceRestAPI (4.3.1)
Installing SalesforceSDKCore 5.1.0 (was 4.3.1)
Installing SmartStore 5.1.0 (was 4.3.1)
Installing SmartSync 5.1.0 (was 4.3.1)
6. Actual behavior:
7. Expected Behavior:
8. Error Log:
/...../Pods/SalesforceSDKCore/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Network/Utilities/CSFDefines.h:51:16: Redefinition of '_CSFPrimitivePointer'

/..../Pods/SalesforceSDKCore/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Network/Utilities/CSFDefines.h:87:28: Redefinition of 'CSFInteractionContext'

And 20 more ....

I update my pods on my iOS project.

I found the same folder, with the same files/Classes in two pods:
SalesforceSDKCore contains Utilities with CSFAvailability, CSFDefines, CSFForceDefines, ...
and the same into SalesforceNetwork

Can I delete one of this pods?
Will SalesforceNetwork deprecated?

Thanks!

**Comment by bhariharan** [comment]
`SalesforceNetwork` was rolled into `SalesforceSDKCore`. Please remove `SalesforceNetwork` from your pod specs. The best way to ensure you have the right pod specs is to re-generate an app using `forceios` and plug in your current app into that shell.

**Comment by CesarRN** [comment]
Hello bhariharan,

Where or How can I read this type of changes?

I know is a bad practice, but I don´t update my pods regularly

In the other hand, I think is very "hard", very difficult re-generate with "forceios" regularly.


Thanks a lot.

**Comment by CesarRN** [comment]
Hi again.

How can I update "forceios" ??

I had install "forceios" in the past and now, I try to use again:


Getting cocoapods dependencies

Analyzing dependencies
Downloading dependencies
Installing CocoaLumberjack (2.3.0)
Installing SQLCipher (3.4.1)
Installing SalesforceNetwork (4.3.1)
Installing SalesforceRestAPI (4.3.1)
Installing SalesforceSDKCore (4.3.1)
Installing SmartStore (4.3.1)
Installing SmartSync (4.3.1)
Generating Pods project

/usr/local/lib/node_modules/forceios/build/app_template_files/createApp.sh: line 298: 65921 Abort trap: 6           pod install

There was an error creating the app.

Why forceios use  4.3.1 versions ?? 

-------

How can I updated my Salesforce´s libraries from my actual project?
Forceios created another project, I think is not a good idea, I will move my actual project to the forceios generated project ...
Are any other way?


THANKS

**Comment by CesarRN** [comment]
I update npm and execute "forceios" again.

This is the log:

Enter output directory for your app (leave empty for the current directory): 

********************************************************************************
*
*   Creating ios native application using Salesforce Mobile SDK
*     with app name:        XXXXXXXXXXX
*          package name:    com.XXXX.XXXXX.XXXX
*          organization:    XXXXX, S.A.
*   
*     in:                   XXXXXXXX
*   
*     from template repo:   https://github.com/forcedotcom/SalesforceMobileSDK-Templates#v5.1.0
*          template path:   iOSNativeTemplate
*
********************************************************************************

/Users/cesar/Desktop/forceiosB/xxxxxxxxx /Users/cesar/Desktop/forceiosB
Installing npm dependencies
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! warning: templates not found /var/folders/yt/bnqmq4cx4k7gyyn50q4rwx7w0000gn/T/pacote-git-template-tmp/git-clone-6213b19c
npm ERR! warning: templates not found /var/folders/yt/bnqmq4cx4k7gyyn50q4rwx7w0000gn/T/pacote-git-template-tmp/git-clone-6213b19c
npm ERR! warning: templates not found /var/folders/yt/bnqmq4cx4k7gyyn50q4rwx7w0000gn/T/pacote-git-template-tmp/git-clone-6213b19c
npm ERR! warning: templates not found /var/folders/yt/bnqmq4cx4k7gyyn50q4rwx7w0000gn/T/pacote-git-template-tmp/git-clone-6213b19c
npm ERR! warning: templates not found /var/folders/yt/bnqmq4cx4k7gyyn50q4rwx7w0000gn/T/pacote-git-template-tmp/git-clone-6213b19c
npm ERR! warning: templates not found /var/folders/yt/bnqmq4cx4k7gyyn50q4rwx7w0000gn/T/pacote-git-template-tmp/git-clone-6213b19c
npm ERR! warning: templates not found /var/folders/yt/bnqmq4cx4k7gyyn50q4rwx7w0000gn/T/pacote-git-template-tmp/git-clone-6213b19c
npm ERR! warning: templates not found /var/folders/yt/bnqmq4cx4k7gyyn50q4rwx7w0000gn/T/pacote-git-template-tmp/git-clone-6213b19c
npm ERR! error: no such remote ref ebe577be9afc4680b7125199e02617678bcf9ef5
npm ERR! Fetched in submodule path 'external/react-native', but it did not contain ebe577be9afc4680b7125199e02617678bcf9ef5. Direct fetching of that commit failed.
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cesar/.npm/_logs/2017-06-29T09_05_48_727Z-debug.log
/Users/cesar/Desktop/forceiosB
forceios failed

Command failed: npm install



How can I do to solve this issue?   :(


Thanks a lot

**Comment by bhariharan** [comment]
Looks like you have stale cached data. Could you wipe your `cocoapod` cache and `npm` cache and try again?

**Comment by annathomasQB** [comment]
> `SalesforceNetwork` was rolled into `SalesforceSDKCore`. Please remove `SalesforceNetwork` from your pod specs. The best way to ensure you have the right pod specs is to re-generate an app using `forceios` and plug in your current app into that shell.

Hi,

I'm facing the same issue - I tried removing SalesforceNetwork from Pod, but on pod update/pod install, I can see the SalesforceNetwork is again getting installed.

This is my podfile : 

   source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git'
    source 'https://github.com/CocoaPods/Specs.git'

    pod 'SalesforceSDKCore'
    pod 'SalesforceRestAPI'
    pod 'SmartStore'
    pod 'SmartSync'
    pod 'NSData+Base64'



Pod update shows the following : 

Installing CocoaLumberjack (2.4.0)
Installing FMDB (2.7.5)
Installing NSData+Base64 (1.0.0)
Installing SQLCipher (3.4.2)
Installing SalesforceAnalytics (5.3.1)
Installing SalesforceNetwork (4.3.1)
Installing SalesforceRestAPI (4.3.1)
Installing SalesforceSDKCore (5.3.1)
Installing SmartStore (5.3.1)
Installing SmartSync (5.3.1)
Generating Pods project
Integrating client project
Sending stats

[!] Found multiple specifications for `SalesforceAnalytics (6.2.0)`:
- /Users/annathomas/.cocoapods/repos/forcedotcom/SalesforceAnalytics/6.2.0/SalesforceAnalytics.podspec
- /Users/annathomas/.cocoapods/repos/master/Specs/6/e/3/SalesforceAnalytics/6.2.0/SalesforceAnalytics.podspec.json

**Comment by annathomasQB** [comment]
> > `SalesforceNetwork` was rolled into `SalesforceSDKCore`. Please remove `SalesforceNetwork` from your pod specs. The best way to ensure you have the right pod specs is to re-generate an app using `forceios` and plug in your current app into that shell.
> 
> Hi,
> 
> I'm facing the same issue - I tried removing SalesforceNetwork from Pod, but on pod update/pod install, I can see the SalesforceNetwork is again getting installed.
> 
> This is my podfile :
> 
> source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git'
> source 'https://github.com/CocoaPods/Specs.git'
> 
> ```
> pod 'SalesforceSDKCore'
> pod 'SalesforceRestAPI'
> pod 'SmartStore'
> pod 'SmartSync'
> pod 'NSData+Base64'
> ```
> Pod update shows the following :
> 
> Installing CocoaLumberjack (2.4.0)
> Installing FMDB (2.7.5)
> Installing NSData+Base64 (1.0.0)
> Installing SQLCipher (3.4.2)
> Installing SalesforceAnalytics (5.3.1)
> Installing SalesforceNetwork (4.3.1)
> Installing SalesforceRestAPI (4.3.1)
> Installing SalesforceSDKCore (5.3.1)
> Installing SmartStore (5.3.1)
> Installing SmartSync (5.3.1)
> Generating Pods project
> Integrating client project
> Sending stats
> 
> [!] Found multiple specifications for `SalesforceAnalytics (6.2.0)`:
> 
> * /Users/annathomas/.cocoapods/repos/forcedotcom/SalesforceAnalytics/6.2.0/SalesforceAnalytics.podspec
> * /Users/annathomas/.cocoapods/repos/master/Specs/6/e/3/SalesforceAnalytics/6.2.0/SalesforceAnalytics.podspec.json

![screen shot 2018-10-23 at 6 35 58 pm](https://user-images.githubusercontent.com/2297073/47362723-b4e2eb00-d6f2-11e8-9ec0-486156a685b8.png)

**Comment by wmathurin** [comment]
Remove `pod 'SalesforceRestAPI'` from your podfile.
The Rest API wrappers are now part of SalesforceSDKCore.

**Comment by annathomasQB** [comment]
Thanks!! It works now :) 👍
