### ISSUE TITLE
pod install error: Unable to checkout 'ebe577be9afc4680b7125199e02617678bcf9ef5' in submodule path 'external/react-native'

### ISSUE THREAD

**Issue by ariyandiwidarto** [forcedotcom/SalesforceMobileSDK-iOS#2106]
Please fill out the following details:

1. Version of Mobile SDK Used: **5.1.0**

2. Issue found in Native App or Hybrid App: **Native App**

3. OS Version: -
4. Device: -

5. Steps to reproduce:
- Try to install the SDK via Cocoapods based on Mobile SDK v5.1.0 documentation
- Add this line: `source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git' # needs to be first`
- And this line: `pod 'SalesforceSDKCore', '5.1.0'`
- Run `pod install`

6. Actual behavior:
The `pod install` does not completed with error

7. Expected Behavior:
The `pod install` should be completed without error

8. Error Log:
```
[!] Error installing SalesforceAnalytics
[!] /usr/local/bin/git -C /var/folders/vz/dmzrmc055kq_kxjlx835dbt40000gn/T/d20170629-34111-1o81077 submodule update --init --recursive

Submodule 'external/CocoaLumberjack' (https://github.com/forcedotcom/CocoaLumberjack.git) registered for path 'external/CocoaLumberjack'
Submodule 'external/cordova-ios/cordova-ios' (https://github.com/apache/cordova-ios.git) registered for path 'external/cordova-ios/cordova-ios'
Submodule 'external/cordova-plugin-wkwebview-engine' (https://github.com/apache/cordova-plugin-wkwebview-engine) registered for path 'external/cordova-plugin-wkwebview-engine'
Submodule 'external/fmdb' (https://github.com/forcedotcom/fmdb) registered for path 'external/fmdb'
Submodule 'external/ocmock' (https://github.com/erikdoe/ocmock.git) registered for path 'external/ocmock'
Submodule 'external/react-native' (https://github.com/forcedotcom/react-native.git) registered for path 'external/react-native'
Submodule 'external/shared' (https://github.com/forcedotcom/SalesforceMobileSDK-Shared.git) registered for path 'external/shared'
Submodule 'external/wypopovercontroller' (https://github.com/sammcewan/WYPopoverController) registered for path 'external/wypopovercontroller'
Submodule path 'external/CocoaLumberjack': checked out 'd59269af0ca8366970b7edcf4dcae4cc23e1ea39'
Submodule path 'external/cordova-ios/cordova-ios': checked out 'a59101beb15f11f52e0bf15d76be909209b3925e'
Submodule path 'external/cordova-plugin-wkwebview-engine': checked out '6a3e6a3af1ae843b838350d18f7a37fdeb178b0b'
Submodule path 'external/fmdb': checked out '4dfdb03a63d3d00885256bf5e528d091c8f8f9b0'
Submodule path 'external/ocmock': checked out 'c4affdcdad1401ea4d331f457cd60523e0bb425a'
Submodule path 'external/shared': checked out '3c5b5a5db21126c2207ee56d66a895dd35e4f451'
Submodule path 'external/wypopovercontroller': checked out '0b3fad3e6fd57d3ebdf27a8b96332fb3589f1756'
Cloning into 'external/CocoaLumberjack'...
Cloning into 'external/cordova-ios/cordova-ios'...
Cloning into 'external/cordova-plugin-wkwebview-engine'...
Cloning into 'external/fmdb'...
Cloning into 'external/ocmock'...
Cloning into 'external/react-native'...
fatal: reference is not a tree: ebe577be9afc4680b7125199e02617678bcf9ef5
Cloning into 'external/shared'...
Cloning into 'external/wypopovercontroller'...
Unable to checkout 'ebe577be9afc4680b7125199e02617678bcf9ef5' in submodule path 'external/react-native'
```

More information: I tried this about a month ago and it was successful without any error

Thank you in advance,
Ariyandi

**Comment by booker-laputa** [comment]
I have the same issue creating react-native app

Please help

**Comment by lnpquang** [comment]
Dear,
I have the same issue, please help to check again.
Log:

WithNewModule SalesforceMobileSDK-Android@5.1.0 checking installable status
error git submodule -q update --init --recursive: error: no such remote ref ebe577be9afc4680b7125199e02617678bcf9ef5
error git submodule -q update --init --recursive: Fetched in submodule path 'external/react-native', but it did not contain ebe577be9afc4680b7125199e02617678bcf9ef5. Direct fetching of that commit failed.
silly fetchPackageMetaData Error: Command failed: git submodule -q update --init --recursive
silly fetchPackageMetaData error: no such remote ref ebe577be9afc4680b7125199e02617678bcf9ef5
silly fetchPackageMetaData Fetched in submodule path 'external/react-native', but it did not contain ebe577be9afc4680b7125199e02617678bcf9ef5. Direct fetching of that commit failed.
.....
silly fetchPackageMetaData error for salesforcemobilesdk-ios@git+https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#v5.1.0 { Error: Command failed: git submodule -q update --init --recursive
silly fetchPackageMetaData error: no such remote ref ebe577be9afc4680b7125199e02617678bcf9ef5
silly fetchPackageMetaData Fetched in submodule path 'external/react-native', but it did not contain ebe577be9afc4680b7125199e02617678bcf9ef5. Direct fetching of that commit failed.
......

Thanks.
Best regards,
LNPQuang

**Comment by wmathurin** [comment]
We are looking into it. Thanks.
Also in the next release, we will make sure that we do a shallow git clone (it will speed up app creation).

**Comment by wmathurin** [comment]
Please try again, it should work now.

**Comment by lnpquang** [comment]
Thanks for your help!
I checked and i works properly now.

Best regards.
LNPQuang

**Comment by ariyandiwidarto** [comment]
Thank you for your help!

Best,
Ariyandi

**Comment by lnpquang** [comment]
Dear,
I think it happens again:

Command failed: git submodule -q update --init --recursive
npm ERR! error: Server does not allow request for unadvertised object ebe577be9afc4680b7125199e02617678bcf9ef5
npm ERR! Fetched in submodule path 'external/react-native', but it did not contain ebe577be9afc4680b7125199e02617678bcf9ef5. Direct fetching of that commit failed.

Please help to take a look

Thanks.
Best regards,
LNPQuang

**Comment by bhariharan** [comment]
@lnpquang That commit exists [here](https://github.com/forcedotcom/react-native/tree/ebe577be9afc4680b7125199e02617678bcf9ef5).

**Comment by wmathurin** [comment]
Try again. It should work now.

**Comment by lnpquang** [comment]
Dear,
Thank you so much! It works now.

Best regards,
LNPQuang
