### ISSUE TITLE
Passing session from one app to another app

### ISSUE THREAD

**Issue by Manish-Kr09** [forcedotcom/SalesforceMobileSDK-iOS#2111]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.1
2. Issue found in Native App or Hybrid App: Hybrid app
3. OS Version:10+
4. Device: iPhone/iPad
5. Steps to reproduce: NA
6. Actual behaviour: BehaviorNA
7. EBehaviour: NA
8. Error Log: NA

Hi All, 

We are looking to make Salesforce Mobile SDK based app authentication using session of another app. I am having 2 cases 

CASE - 1. 
Here is the scenario. 

There are two app A and B(Salesforce SDK based hybrid App), App A is having an active session from an identity provider. App A launches app B by calling its URL scheme. The URL scheme which used to call app B may contain a token/certificate. App B will use this certificate/token and get the session from Salesforce. This all would be behind the screen and when app B launches will show it's after authentication screen with all of its functions. 

Is it possible?

If yes, please provide me with a direction to achieve it. 

Do we have any other alternative where we can launch the app and get the session from another app?
![image](https://user-images.githubusercontent.com/2398709/27820065-9a47e5ca-60ba-11e7-8d71-d107a712995d.png)

CASE 2. 

There are two app A and B(Salesforce SDK based hybrid App). Both apps is running in VPN. Is it possible for an app to bypass the authentication screen if it is using VPN? i.e., App will be automatically logged in using network authentication

@bhariharan 

Let me know for any further clarification

Regards,
Manish Kumar

**Comment by bhariharan** [comment]
@manish-metacube We don't support this flow currently, but we are working on providing a way to perform shared authentication between apps. This will be in a future release. #safeharbor

**Comment by manish-metacube** [comment]
@bhariharan 
Is there any timeline for this feature to be available in the framework so that we can drive the discussion over the functionality of the application with our client?

**Comment by bhariharan** [comment]
It's too early to tell at this time, unfortunately. We're in the design phase currently.

**Comment by urthakkar** [comment]
@manish-metacube - glad to see you are thinking about this too.  As @bhariharan mentioned, we are working on enabling Case #1  as this could help reduce the login friction where the orgs have more than one apps.  However, the design and the flow (details) might be little different than how you have laid out but it is close enough.  Stay tuned.

Case #2 - I don't think is needed if we solve case #1. Also, I don't think its a good idea to bypass authentication completely just because the user is in the same network/VPN

**Comment by Manish-Kr09** [comment]
Isn't it possible to have username-password flow for OAuth in mobile-SDK? I know it's not recommended but should be there if one wants to use this flow as it's still a standard of OAuth.

**Comment by bhariharan** [comment]
@Manish-Kr09 Username-password flow is unsupported in `Mobile SDK` due to server side security restrictions. The only options are `WebView` or browser based login (user agent flow).

**Comment by wmathurin** [comment]
The IDP support coming to the Mobile SDK is covered in the [Dreamforce session](https://success.salesforce.com/Sessions#/session/a2q3A000001ytBVQAY) (starting at 23:25).
