### ISSUE TITLE
No podspec found for `SalesforceAnalytics`

### ISSUE THREAD

**Issue by GoliathDeveloper** [forcedotcom/SalesforceMobileSDK-iOS#2112]
![image](https://user-images.githubusercontent.com/2816987/27866542-b28f54ae-618e-11e7-875c-52388656883c.png)

**Comment by wmathurin** [comment]
This issue was already reported [here](https://github.com/forcedotcom/SalesforceMobileSDK-Package/issues/41).
There is a bug with npm 5 (see [here](https://github.com/npm/npm/issues/16834)).
Until it get resolved, we recommend you downgrade to npm 4.

**Comment by wmathurin** [comment]
In 5.2, we are fetching the mobile sdk dependencies with git directly. As a result, things are faster and more importantly you can use npm 5.x without any problems.

**Comment by rashidalii** [comment]
i try the above solution still getting this error 
[!] No podspec found for `MobileSync` in `mobile_sdk/SalesforceMobileSDK-iOS`
