### ISSUE TITLE
Custom apex rest resource crashes app if not returning an object

### ISSUE THREAD

**Issue by mcekol** [forcedotcom/SalesforceMobileSDK-iOS#2118]
1. Version of Mobile SDK Used: 
5.1.0

2. Issue found in Native App or Hybrid App:
Hybrid App

3. OS Version:
IOS 10.3.1

4. Device:
IOS Simulator

5. Steps to reproduce:
Create a custom RestResource with a simple function which returns a string (or an integer).
example:
@RestResource(urlMapping='/stringtesting')
global without sharing class StringTesting {
global static String returnSomeVal() {
return 'testString';
}
}

Perform a query against the set-up resource.

6. Actual behavior:
Simulator app crashes.

7. Expected Behavior:
String value is returned.

8. Error Log:
2017-07-10 09:41:56.305 [53357:1187718] A background URLSession with identifier com.salesforce.network already exists!
2017-07-10 09:41:58.961 [53357:1187811] -[__NSCFString bytes]: unrecognized selector sent to instance 0x6000000372e0
2017-07-10 09:41:58.971 [53357:1187811] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString bytes]: unrecognized selector sent to instance 0x6000000372e0'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000113b21b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000011355d141 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000113b91134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000113aa8840 ___forwarding___ + 1024
	4   CoreFoundation                      0x0000000113aa83b8 _CF_forwarding_prep_0 + 120
	5   CoreFoundation                      0x0000000113ab270c CFStringCreateFromExternalRepresentation + 28
	6   Foundation                          0x0000000110be6ad8 -[NSPlaceholderString initWithData:encoding:] + 115
	7   MyTestApp                           0x000000010ecdeb05 -[NSArray(CDVJSONSerializingPrivate) cdv_JSONString] + 581
	8   MyTestApp                           0x000000010ece921f -[CDVPluginResult argumentsAsJSON] + 335
	9   MyTestApp                           0x000000010ecde39d -[CDVCommandDelegateImpl sendPluginResult:callbackId:] + 365
	10  MyTestApp                           0x000000010eebbad2 __33-[SFNetworkPlugin pgSendRequest:]_block_invoke.79 + 466
	11  MyTestApp                           0x000000010ed650a4 -[SFRestAPI(Blocks) sendActionForRequest:success:withObject:] + 96
	12  MyTestApp                           0x000000010ed65283 -[SFRestAPI(Blocks) request:didLoadResponse:] + 55
	13  MyTestApp                           0x000000010ed671ff -[SFRestAPI replayRequestIfRequired:response:error:request:delegate:] + 1076
	14  MyTestApp                           0x000000010ed66d2d __37-[SFRestAPI enqueueRequest:delegate:]_block_invoke + 404
	15  MyTestApp                           0x000000010ed2ff71 __43-[SFNetwork sendRequest:dataResponseBlock:]_block_invoke + 70
	16  CFNetwork                           0x000000011530187b __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 19
	17  CFNetwork                           0x0000000115301095 __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 143
	18  Foundation                          0x0000000110c0e3b7 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	19  Foundation                          0x0000000110c0e0bb -[NSBlockOperation main] + 101
	20  Foundation                          0x0000000110c0c877 -[__NSOperationInternal _start:] + 627
	21  Foundation                          0x0000000110c085fc __NSOQSchedule_f + 198
	22  libdispatch.dylib                   0x000000011423a05c _dispatch_client_callout + 8
	23  libdispatch.dylib                   0x000000011421894f _dispatch_queue_serial_drain + 221
	24  libdispatch.dylib                   0x0000000114219669 _dispatch_queue_invoke + 1084
	25  libdispatch.dylib                   0x000000011421bec4 _dispatch_root_queue_drain + 634
	26  libdispatch.dylib                   0x000000011421bbef _dispatch_worker_thread3 + 123
	27  libsystem_pthread.dylib             0x00000001146a75a2 _pthread_wqthread + 1299
	28  libsystem_pthread.dylib             0x00000001146a707d start_wqthread + 13
)

**Comment by bhariharan** [comment]
We have fixed this in the `dev` branch and will be a part of our upcoming `5.2` release, which is slated for this week. #safeharbor

**Comment by mcekol** [comment]
That's great, thanks!

**Comment by mcekol** [comment]
@bhariharan I've just installed 5.2.0 and although the request goes through and does not crash my (hybrid) app the returned value is null instead of the string value. The same is true for integer values as well.
