### ISSUE TITLE
How to properly paginate calls to SOQL

### ISSUE THREAD

**Issue by helloniklas** [forcedotcom/SalesforceMobileSDK-iOS#2119]
It seems the performSOQLQuery will support limit and offset, but since this only goes up to 2000 items the docs says to use the SOAP API queryMore() that gives a cursor.

Is there a way of using this form the current iOS SDK?

**Comment by bhariharan** [comment]
We don't have convenience wrappers for SOAP APIs in the Mobile SDK, but you should be able to use the access token once you've authenticated to create your own API request and send it. Please use [our community](https://plus.google.com/u/1/communities/114225252149514546445) for queries or discussions. This forum is reserved for bugs/issues in our code.

**Comment by wmathurin** [comment]
What don't you use our REST API wrappers?
To see how to paginate calls through SOQL check out https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SmartSync/SmartSync/Classes/Target/SFSoqlSyncDownTarget.m#L104
