### ISSUE TITLE
Unable to install the SDK

### ISSUE THREAD

**Issue by mitesheri** [forcedotcom/SalesforceMobileSDK-iOS#2124]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.1.0
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: 
4. Device: 
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

When try to run "npm install salesforcemobilesdk-ios", below error is shown:

npm ERR! code 1
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! warning: templates not found /var/folders/q5/1sb3r_nd2gn3zn65n9qnw54c0000gn/T/pacote-git-template-tmp/git-clone-92148b8f
npm ERR! warning: templates not found /var/folders/q5/1sb3r_nd2gn3zn65n9qnw54c0000gn/T/pacote-git-template-tmp/git-clone-92148b8f
npm ERR! warning: templates not found /var/folders/q5/1sb3r_nd2gn3zn65n9qnw54c0000gn/T/pacote-git-template-tmp/git-clone-92148b8f
npm ERR! warning: templates not found /var/folders/q5/1sb3r_nd2gn3zn65n9qnw54c0000gn/T/pacote-git-template-tmp/git-clone-92148b8f
npm ERR! warning: templates not found /var/folders/q5/1sb3r_nd2gn3zn65n9qnw54c0000gn/T/pacote-git-template-tmp/git-clone-92148b8f
npm ERR! warning: templates not found /var/folders/q5/1sb3r_nd2gn3zn65n9qnw54c0000gn/T/pacote-git-template-tmp/git-clone-92148b8f
npm ERR! warning: templates not found /var/folders/q5/1sb3r_nd2gn3zn65n9qnw54c0000gn/T/pacote-git-template-tmp/git-clone-92148b8f
npm ERR! warning: templates not found /var/folders/q5/1sb3r_nd2gn3zn65n9qnw54c0000gn/T/pacote-git-template-tmp/git-clone-92148b8f
npm ERR! error: no such remote ref ebe577be9afc4680b7125199e02617678bcf9ef5
npm ERR! Fetched in submodule path 'external/react-native', but it did not contain ebe577be9afc4680b7125199e02617678bcf9ef5. Direct fetching of
that commit failed.
npm ERR!

**Comment by wmathurin** [comment]
This is not how you install the SDK. 
Please follow the steps [here](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/ios_quickstart.htm).
