### ISSUE TITLE
React Native build error

### ISSUE THREAD

**Issue by lnpquang** [forcedotcom/SalesforceMobileSDK-iOS#2133]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.1
2. Issue found in Native App or Hybrid App: React Native
3. OS Version: MacOS 10.12.5 (16F73)
4. Device: 
5. Steps to reproduce: react-native-cli run-ios "--simulator=iPhone 7"
6. Actual behavior:
** BUILD FAILED **

7. Expected Behavior:

** BUILD SUCCESSED **

8. Error Log:
.....
/node_modules/SalesforceMobileSDK-iOS/libs/SalesforceAnalytics/SalesforceAnalytics/Classes/Util/SFSDKDatasharingHelper.m:90:10: error: use of undeclared identifier 'SFSDKAnalyticsLogger'
        [SFSDKAnalyticsLogger w:[self class] format:@"Ensure that you have enabled app-groups for your app in the entitlements for your app."];
.....
/node_modules/SalesforceMobileSDK-iOS/libs/SalesforceAnalytics/SalesforceAnalytics/Classes/Model/SFSDKInstrumentationEventBuilder.m:71:10: error: unknown receiver 'SFSDKAnalyticsLogger'; did you mean 'SFSDKAnalyticsManager'?
        [SFSDKAnalyticsLogger w:[self class] format:@"WARNING: Building event failed! REASON: %@", errorMessage];
         ^~~~~~~~~~~~~~~~~~~~
         SFSDKAnalyticsManager

/node_modules/SalesforceMobileSDK-iOS/libs/SalesforceAnalytics/SalesforceAnalytics/Classes/Manager/SFSDKAnalyticsManager.h:32:12: note: 'SFSDKAnalyticsManager' declared here
@interface SFSDKAnalyticsManager : NSObject
           ^
/node_modules/SalesforceMobileSDK-iOS/libs/SalesforceAnalytics/SalesforceAnalytics/Classes/Model/SFSDKInstrumentationEventBuilder.m:71:31: error: no known class method for selector 'w:format:'
        [SFSDKAnalyticsLogger w:[self class] format:@"WARNING: Building event failed! REASON: %@", errorMessage];
                              ^~~~~~~~~~~~~~~~~~~~~
2 errors generated.
...

**Comment by lnpquang** [comment]
Incorrect configuration in xcode project.

**Comment by workholyface** [comment]
Hi, I have same problem of this..
Will you let me know how did you fix it?
Hope you remember .. :)
