### ISSUE TITLE
Are CustomLabel of salesforce accessable to the IOS SDK via the REST API

### ISSUE THREAD

**Issue by piyushprabhakar** [forcedotcom/SalesforceMobileSDK-iOS#2142]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.0
2. Issue found in Native App or Hybrid App: iOS Native App
3. OS Version: 
4. Device:
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

I have been trying to access Custom label of Salesforce from Metadata API/ REST API but it seems it is not accessible. Could you suggest how to access it using this SDK.

**Comment by bhariharan** [comment]
If custom labels are available via REST API, then it is possible to build an API request and retrieve the results using Mobile SDK. Please use [our community](https://plus.google.com/u/1/communities/114225252149514546445?cfem=1) for queries and discussions. This forum is reserved for bugs or issues with our code.
