### ISSUE TITLE
SwiftlySalesforceSDK and FMDatabaseVariadic.swift

### ISSUE THREAD

**Issue by tysun** [forcedotcom/SalesforceMobileSDK-iOS#2150]
I am using [SwiftlySalesforce](https://github.com/mike4aday/SwiftlySalesforce) + FMDB, Locksmith, MBProgressHUD, SQLCipher, PromiseKit dependencies. Not using the **SalesforceMobileSDK-iOS**. 

I am using [SwiftlySalesforce](https://github.com/mike4aday/SwiftlySalesforce) and therefore am getting the same `'SalesforceSDKCore/SFLogger.h' file not found` error in the **FMDatabase.m** file because I am not using the Obj-C framework **SFLogger.h**. 

Documentation says if you want to use Swift to import **#import "FMDB.h"** or copy the **FMDatabaseVariadic.swift** from the **_"src/extra/Swift Extensions"_** folder. 

I cannot find this **_src/_** folder. I'm assuming **FMDatabaseVariadic.swift** is included in one of the other optional dependencies? Is it in **FMDB/standalone/FTS**? Also which is the recommended of the two methods? Using **FMDatabaseVariadic.swift**?

Or do you recommend I simply clone the repo for **SalesforceMobileSDK-iOS**?

Thanks.

**Comment by bhariharan** [comment]
`FMDB` doesn't depend on `SFLogger` directly. Our fork of `FMDB` does. I recommend that you use `FMDB` directly from their source instead of from our fork.

**Comment by tysun** [comment]
I did use it directly from [FMDB](https://github.com/ccgus/fmdb). And FMDatabase.m is trying to import SFLogger.h. 

![screen](https://user-images.githubusercontent.com/11150198/28484320-807bc480-6e26-11e7-8f9e-c111faf9676d.png)

**Comment by bhariharan** [comment]
No it does not. The stock version of `FMDatabase.m` has nothing to do with `SFLogger` -> see [here](https://github.com/ccgus/fmdb/blob/master/src/fmdb/FMDatabase.m).

**Comment by tysun** [comment]
I see that. So why then does my installed version of FMDatabase.m required it? Very mysterious.
<img width="296" alt="screen shot 2017-07-21 at 3 16 55 pm" src="https://user-images.githubusercontent.com/11150198/28484521-bfaa9112-6e27-11e7-88e7-429684cdc3ba.png">

<img width="219" alt="screen shot 2017-07-21 at 3 19 05 pm" src="https://user-images.githubusercontent.com/11150198/28484575-fbaad726-6e27-11e7-8a14-63d5044e2a35.png">

**Comment by tysun** [comment]
<img width="276" alt="screen shot 2017-07-21 at 3 21 08 pm" src="https://user-images.githubusercontent.com/11150198/28484648-5939497c-6e28-11e7-920f-fe64408709b4.png">
<img width="386" alt="screen shot 2017-07-21 at 3 21 20 pm" src="https://user-images.githubusercontent.com/11150198/28484647-592bf506-6e28-11e7-9c84-cffba7177748.png">

**Comment by bhariharan** [comment]
Looks like your pod specs are pulling from our fork instead of the official FMDB pod specs.
