### ISSUE TITLE
SmartSyncExplorer not syncing contacts which i have added.

### ISSUE THREAD

**Issue by jvashisht** [forcedotcom/SalesforceMobileSDK-iOS#2154]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.2
2. Issue found in Native App or Hybrid App: Native
3. OS Version:10.12.5
4. Device: simulator
5. Steps to reproduce: 1. login into the salesforce. 2. add contacts , try to sync contacts message appear syncing failed.
6. Actual behavior:
7. Expected Behavior:
8. Error Log:
https://ap5.salesforce.com/services/data/v39.0/sobjects/Contact Code=403 "(null)"

**Comment by bhariharan** [comment]
@jvashisht Verified that the app is working fine. `403` is `Forbidden` which could mean that API access for that user is not setup correctly on your org.

**Comment by jvashisht** [comment]
Thanks for the Reply.
