### ISSUE TITLE
Can Smartstore be encrypted with SQLCipher or using any other techniques?

### ISSUE THREAD

**Issue by rajasanka** [forcedotcom/SalesforceMobileSDK-iOS#2157]
Please fill out the following details:

1. Version of Mobile SDK Used: 
2. Issue found in Native App or Hybrid App:
3. OS Version:
4. Device:
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

**Comment by bhariharan** [comment]
@rajasanka This forum is for bugs/issues in the Mobile SDK. Please use our [Google+ community](https://plus.google.com/u/1/communities/114225252149514546445) for discussions or feature queries.
