### ISSUE TITLE
performSOSLSearch : Terminating due to uncaught Exception

### ISSUE THREAD

**Issue by nzsrini** [forcedotcom/SalesforceMobileSDK-iOS#2158]
Please fill out the following details:

1. Version of Mobile SDK Used:  v5.1.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 10.3
4. Device: Ipad
5. Steps to reproduce: performSOSLSearch
6. Actual behavior:  SFRestAPI.sharedInstance().performSOSLSearch is terminating due to uncaught exception.
7. Expected Behavior: Return result set.
8. Error Log:

 -[__NSSingleEntryDictionaryI objectAtIndex: unrecognized selector sent to instance 0x618000037660
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSSingleEntryDictionaryI objectAtIndex: unrecognized selector sent to instance 0x618000037660'
 *** First throw call stack:
(
	0   CoreFoundation                      0x00000001058cab0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010532f141 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010593a134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000105851840 _forwarding_ + 1024
	4   CoreFoundation                      0x00000001058513b8 _CF_forwarding_prep_0 + 120
	5   libswiftCore.dylib                  0x0000000108002abb TFVs12_ArrayBuffer19_getElementSlowPathfSiPs9AnyObject + 171
	6   libswiftCore.dylib                  0x0000000108002973 _TFVs12_ArrayBuffer10getElementfTSi20wasNativeTypeCheckedSb_x + 147
	7   libswiftCore.dylib                  0x0000000108014e6a _TFSag9subscriptFSix + 138
	8   libswiftCore.dylib                  0x00000001080160a8 TTWurGSax_s10CollectionsFS_g9subscriptFwx5IndexWx8Iterator7Element + 24
	9   libswiftFoundation.dylib            0x00000001085f23fc TFEsPs10Collection3mapurfzFzWx8Iterator7Element_qd__GSaqd__ + 780
	10  libswiftFoundation.dylib            0x000000010860b153 TFs15_arrayForceCastu0_rFGSax_GSaq_ + 227
	11  libswiftFoundation.dylib            0x00000001085cf4e9 TZFE10FoundationSa36_unconditionallyBridgeFromObjectiveCfGSqCSo7NSArray_GSax + 217
	12  TimeSheet                           0x0000000104194dc4 TTRXFo_oGSqGSaP_____XFdCb_dGSqCSo7NSArray__ + 84
	13  SalesforceSDKCore                   0x0000000104b1c136 -[SFRestAPI(Blocks) sendActionForRequest:success:withObject:] + 166
	14  SalesforceSDKCore                   0x0000000104b1c470 -[SFRestAPI(Blocks) request:didLoadResponse:] + 96
	15  SalesforceSDKCore                   0x0000000104b20f7d -[SFRestAPI replayRequestIfRequired:response:error:request:delegate:shouldRetry:] + 1997
	16  SalesforceSDKCore                   0x0000000104b205f1 __49-[SFRestAPI enqueueRequest:delegate:shouldRetry:]_block_invoke + 545
	17  SalesforceSDKCore                   0x0000000104af6ce1 __43-[SFNetwork sendRequest:dataResponseBlock:]_block_invoke + 177
	18  CFNetwork                           0x0000000108f2f87b __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 19
	19  CFNetwork                           0x0000000108f2f095 _49-[__NSCFLocalSessionTask task_onqueue_didFinish]_block_invoke + 143
	20  Foundation                          0x0000000104e393b7 NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK + 7
	21  Foundation                          0x0000000104e390bb -[NSBlockOperation main] + 101
	22  Foundation                          0x0000000104e37877 -[__NSOperationInternal _start:] + 627
	23  Foundation                          0x0000000104e335fc __NSOQSchedule_f + 198
	24  libdispatch.dylib                   0x000000010993005c _dispatch_client_callout + 8
	25  libdispatch.dylib                   0x000000010990e94f _dispatch_queue_serial_drain + 221
	26  libdispatch.dylib                   0x000000010990f669 _dispatch_queue_invoke + 1084
	27  libdispatch.dylib                   0x0000000109911ec4 _dispatch_root_queue_drain + 634
	28  libdispatch.dylib                   0x0000000109911bef _dispatch_worker_thread3 + 123
	29  libsystem_pthread.dylib             0x0000000109cc7616 _pthread_wqthread + 1299
	30  libsystem_pthread.dylib             0x0000000109cc70f1 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

 func retriveSearchData<T: SFObjectData>(object: T.Type, searchDict:[String:String],searchString:String?,completion:@escaping ResponseBlock) -> SFRestRequest? {
        var sfrequest : SFRestRequest? = nil
        let failBlock: SFRestFailBlock = { (error) in
            //print(error.debugDescription)
            completion(nil,error)
        }
        let sucessFullBlock: SFRestArrayResponseBlock = {
            [weak self](responseData: [Any]?) in
            guard let weakSelf = self else {
                return
            }
            var objectDataAray:[Any]? = nil
            if let l_responseData = responseData {
                objectDataAray = weakSelf.parseData(datas: l_responseData, object: object)
            }
            completion(objectDataAray,nil)
        }
        var l_searchString = searchString ?? "aa"
        l_searchString += String.init("*".unicodeScalars)
      let queryString =  SFRestAPI.soslSearch(withSearchTerm: l_searchString, fieldScope: "IN ALL FIELDS", objectScope: searchDict, limit: 10)?.replacingOccurrences(of: "\\", with: "")
        
        if let l_queryString = queryString {
            sfrequest = SFRestAPI.sharedInstance().performSOSLSearch(l_queryString, fail: failBlock, complete: sucessFullBlock)
        }
        
        return sfrequest
    }

**Comment by bhariharan** [comment]
This should be fixed in `Mobile SDK 5.2`. Please try with `5.2` or the latest from our `dev` branch and reopen if you still see this issue.
