### ISSUE TITLE
SalesforceMobileSDK-iOS login

### ISSUE THREAD

**Issue by jvashisht** [forcedotcom/SalesforceMobileSDK-iOS#2162]
Please fill out the following details:

Version of Mobile SDK Used: 5.2
Issue found in Native App or Hybrid App: Native
OS Version:10.12.5
Device: simulator
Steps to reproduce: I want to login without going to webview or safari in the app. is it possible to do login directly with username and password please reply ASAP i really need to integrate salesforce but without going to webview or safari.
Actual behavior:
Expected Behavior:
Error Log: no log

**Comment by bhariharan** [comment]
@jvashisht No - the only way to authenticate is using `WebView` or `Safari`, due to security requirements. This forum is reserved for issues with our code. Please post other queries in our community [here](https://plus.google.com/u/1/communities/114225252149514546445?cfem=1).
