### ISSUE TITLE
SFAuthenticationManager.shared().idCoordinator.idData is nil when app is launched next time after the user login.

### ISSUE THREAD

**Issue by abinaya001** [forcedotcom/SalesforceMobileSDK-iOS#2163]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.2.1.  The issue wasn't observed with the SDK version 5.0.1.
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 10.3.2
4. Device: iPhone 7
5. Steps to reproduce: 
 1.Login the iOS app with the user credentials.(after the successful login, SFAuthenticationManager.shared().idCoordinator.idData is not nil)
2. Remove the app from background.
3. Launch the app again.  It will crash(Reason: SFAuthenticationManager.shared().idCoordinator.idData = nil)
6. Actual behavior:  SFAuthenticationManager.shared().idCoordinator.idData should not be nil as long as the user is logged in.
7. Expected Behavior:
8. Error Log:
Unexpectedly found nil while unwrapping the optional value.(SFAuthenticationManager.shared().idCoordinator.idData = nil)

**Comment by bhariharan** [comment]
@abinaya001 Which API are you using to login? How did you generate your app - did you use `forceios@5.2.1`?

**Comment by abinaya001** [comment]
I have used forceios - 5.2.1. SalesforceSDKManager API used to login.  Please find the below steps that  followed to login/bypass the auth flow if user is already logged in.

1. I added the below line in didfinishLaunchingWithOptions method of AppDelegate class:

SalesforceSDKManager.shared().launch()

2. I put the below lines of code in the init method of AppDelegate.swift

{
        super.init()
        SFLogger.shared().logLevel = .debug
       
        SFFileProtectionHelper.sharedInstance().defaultNSFileProtectionMode = FileProtectionType.completeUntilFirstUserAuthentication.rawValue
        SFKeychainItemWrapper.setAccessibleAttribute(kSecAttrAccessibleAfterFirstUnlock);
        
        SalesforceSDKManager.setInstanceClass(SalesforceSDKManagerWithSmartStore.self)
        SalesforceSDKManager.shared().connectedAppId = "clientId"
        SalesforceSDKManager.shared().connectedAppCallbackUri = "callbackURL"
        SalesforceSDKManager.shared().authScopes = ["web","api","full","refresh_token"]
        SalesforceSDKManager.shared().postLaunchAction = {
            [unowned self] (launchActionList: SFSDKLaunchAction) in
//            let launchActionString = SalesforceSDKManager.launchActionsStringRepresentation(launchActionList)
            //self.log(.info, msg:"Post-launch: launch actions taken: \(launchActionString)");
            self.print("Current Account:::\(String(describing: SFUserAccountManager.sharedInstance().currentUser))")
            self.print("Current User email::\(SFAuthenticationManager.shared().idCoordinator.idData.email)") // Here idData has user data only when user log in the app.  
            self.setupRootViewController();
        }
        SalesforceSDKManager.shared().launchErrorAction = {
            [unowned self] (error:Error?, launchActionList: SFSDKLaunchAction) in
            if let actualError = error {
                self.log(.error, msg:"Error during SDK launch: \(actualError.localizedDescription)")
            } else {
                self.log(.error, msg:"Unknown error during SDK launch.")
            }
            self.initializeAppViewState()
            SalesforceSDKManager.shared().launch()
        }
        SalesforceSDKManager.shared().postLogoutAction = {
            [unowned self] in
            self.handleSdkManagerLogout()
        }
        SalesforceSDKManager.shared().switchUserAction = {
            [unowned self] (fromUser: SFUserAccount?, toUser: SFUserAccount?) -> () in
            self.handleUserSwitch(fromUser, toUser: toUser)
        }
    }

Next time after the successful login, when user login the app authflow will be bypassed and postLaunchAction will be called.  Inside the postLaunchAction call back, the value SFAuthenticationManager.shared().idCoordinator.idData.email is nil.

**Comment by abinaya001** [comment]
Following are the error logs received when already logged in app is launched upon accessing the API 
SFAuthenticationManager.shared().idCoordinator.idData.

2017/08/01 16:59:44.798 TestApp[95867:5203] INFO com.salesforce < TestApp.AppDelegate>: Post-launch: launch actions taken: SFSDKLaunchActionPasscodeVerified|SFSDKLaunchActionAlreadyAuthenticated
fatal error: unexpectedly found nil while unwrapping an Optional value
2017-08-01 22:29:44.801573+0530 TestApp[95867:2946156] fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by khawkins** [comment]
These `SFAuthenticationManager` properties have an unfortunate API visibility—they should not be public, as they're strictly used for internal routing of the authentication process.

Identity data is ultimately tied to a user account.  You should be accessing a user's identity data directly, via `SFUserAccount.idData`.

**Comment by abinaya001** [comment]
Thank you for the solution.  Much appreciated..!!
