### ISSUE TITLE
[[SFRestAPI sharedInstance]performSOQLQuery] not returning any response after Oauth Expiry, even after first re-login

### ISSUE THREAD

**Issue by SrinivasGit049** [forcedotcom/SalesforceMobileSDK-iOS#2164]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.1.0
2. Issue found in Native App or Hybrid App:Native app
3. OS Version: iOS 10.3
4. Device: iPad Simulator
5. Steps to reproduce:
Revoke Oauth just before executing [SFRestAPI sharedInstance]performSOQLQuery](This also continues after first successful login of Oauth expiry and executing performSOQLQuery without killing the app)
6. Actual behavior:
failure block not called after Oauth expiry or even after first successful login of Oauth expir without killing the app)
7. Expected Behavior: failure block should be called
8. Error Log:

**Comment by bhariharan** [comment]
@SrinivasGit049 We have fixed a few bugs in this area, including invoking the delegate callback on canceled requests in our `dev` branch. This will be in our `6.0` release. Please try with the latest from `dev` branch. Feel free to reopen this issue if it still exists.
