### ISSUE TITLE
refresh credentials requesting login.salesforce.com instead of custom domain

### ISSUE THREAD

**Issue by joaomvfsantos** [forcedotcom/SalesforceMobileSDK-iOS#2178]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.2.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 10
4. Device: iPhone 6S
5. Steps to reproduce: After login call [SFAuthenticationManager refreshCredentials:]
6. Actual behavior: POST to https://login.salesforce.com/services/oauth2/token
7. Expected Behavior: Should POST https://\<custom-domain\>/services/oauth2/token
8. Error Log: Since the request is done to the wrong domain the request fails with: ```WARNING com.salesforce: OAuth refresh failed due to invalid grant.  Error code: 672```

**Further Information:**
 Login was done via the the webpage loaded in the SFLoginViewController, then selecting the "Use Custom Domain" link. Custom domain used was: "test.salesforce.com".

Please also note that the credentials property (SFOAuthCredentials) in the [SFUserAccountManager currentUser] object has the  domain property set to "login.salesforce.com" instead of the custom domain, so I think the error originates from here.

If I manually do the same request to the (correct) custom domain the request is successful.

EDIT: I also recognized the same happens for the GET /services/oauth2/revoke triggered on the [SFAuthenticationManager logout] call, response is a 404 Not Found with body "Bad_Id", which is expected since the request is being done to the wrong domain.

**Comment by bhariharan** [comment]
@joaomvfsantos `Use Custom Domain` should not be used within the web page, since the container has no knowledge of this. Use the gear icon to select `Sandbox` instead for `test.salesforce.com`.

**Comment by joaomvfsantos** [comment]
@bhariharan Thank you for your quick response.

I would use the gear icon, but i can't seem to make that work either. Maybe I'm doing something really wrong here. When I click the gear icon and select sandbox, the modal view closes but production is always selected, never changing to sandbox. Any ideais of what I could be doing wrong (code side) for this to happen?

**Comment by bhariharan** [comment]
No worries. Glad you got it working.
