### ISSUE TITLE
Leaks in SDK

### ISSUE THREAD

**Issue by helloniklas** [forcedotcom/SalesforceMobileSDK-iOS#2181]
Please fill out the following details:
1. Version of Mobile SDK Used: 
v5.2.0

2. Issue found in Native App or Hybrid App:
Native

3. OS Version:
10

I keep getting a lot of leaks when using the SDK. If I make call with SFRestAPI.sharedInstance().performSOQLQuery() I instantly get over 50 leaks originating in SFRestAPI, SFNetworking and so on.

**Comment by wmathurin** [comment]
We will investigate. Thanks.

**Comment by imanmk** [comment]
I'm experiencing the same issue. According to Instruments, there are thousands of memory leaks in SalesforceSDKCore and SmartStore.

**Comment by mcekol** [comment]
Any update regarding the memory leaks in SmartStore? 

I'm getting a lot of leaks when using SmartStore in a hybrid app - eventually the app crashes due to memory issues.

**Comment by fobin** [comment]
Anything on this?

**Comment by wmathurin** [comment]
We have internal apps that are heavy users of SalesforceSDKCore and SmartStore and we have not observed the level of leaking (crash inducing) that you reporting.
We will look at it for the next release.

**Comment by helloniklas** [comment]
Install Xcode 9. Run in profiler for leaks. Watch the graphs go up. Happens every time.

**Comment by trooper2013** [comment]
@helloniklas Im currently looking into this issue. Could you provide us with a trace log? Would help me compare result also determine if there are other areas for leaks that I haven't found yet.

**Comment by bhariharan** [comment]
We have fixed most of these issues [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2364). This will be a part of our next release.
