### ISSUE TITLE
Iframe content not loading in lightning within mobile container

### ISSUE THREAD

**Issue by Manish-Kr09** [forcedotcom/SalesforceMobileSDK-iOS#2182]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.0/5.1/5.2
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version:10+
4. Device: Any
5. Steps to reproduce: Create a lighting app, place an iframe in its source and load the component using mobile container
6. Actual behaviour: It's not loading the iframe contents, though it is working fine with older SDK 4.1.0
7. Expected Behavior:  It should load the component
8. Error Log: Not getting any errors. 

Hi all, 

I am getting a strange error, some of my lightning components had stopped working after upgrading my SDK. These are specific lightning components which use an iframe in it. 

While looking at logs I didn't find any error. 

Can someone help me in debugging the issue? 

screenshots of iframe loading structure in both SDK. 
With SDK 4.1
<img width="687" alt="lightning iframe with sdk 4 1 0" src="https://user-images.githubusercontent.com/2398709/29756463-d754d428-8bc1-11e7-9d0c-107cc2af2d2f.png">
With latest SDK
<img width="643" alt="lightning iframe with sdk 5" src="https://user-images.githubusercontent.com/2398709/29756469-e4c276d8-8bc1-11e7-9688-2261cccf977a.png">

Note - I am using UIWebView for my application.

Regards,
Manish Kumar

**Comment by Manish-Kr09** [comment]
Hi guys, 

I have resolved the issue  :)
 It requires following additional entries in config.xml file 

    <access origin="*" />
    <allow-navigation href="*.somedomain.com" />
    <allow-intent href="*.somedomain.com" />

Thanks
Manish Kumar

**Comment by bhariharan** [comment]
`Cordova` requires whitelisting of domains accessed by the components. Also, `Lightning` components are not supported within the Mobile SDK container.
