### ISSUE TITLE
iOS 11 app icon doesn't appear using SmartSync

### ISSUE THREAD

**Issue by puckdevteam** [forcedotcom/SalesforceMobileSDK-iOS#2183]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.2 and 6.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Xcode 9.0 Beta 6
4. Device: iPhone, iPad, Simulator
5. Steps to reproduce: Add SmartSync to a project using Cocoapods
6. Actual behavior: The icon of the app disappears and it's used the standard iOS one instead.
7. Expected Behavior: Have the icon of the app.
8. Error Log: -
[Icon-Test.zip](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/1263222/Icon-Test.zip)

**Comment by wmathurin** [comment]
I tried the code you attached, and I don't see the issue.

![screen shot 2017-09-14 at 4 11 14 pm](https://user-images.githubusercontent.com/1012459/30459739-5e44e740-9967-11e7-82f4-77e92641c792.png)

**Comment by davidpuck** [comment]
You could not see the issue because you were running the project in the iOS 10 simulator, not iOS 11.
Nevertheless, it was a Cocoapods issue https://github.com/CocoaPods/CocoaPods/issues/7003 .
For some reason, in our case only happened when adding the SmartSync project.
