### ISSUE TITLE
App developed with latest SDK doesn't connect to client VPN environment

### ISSUE THREAD

**Issue by Manish-Kr09** [forcedotcom/SalesforceMobileSDK-iOS#2184]
Please fill out the following details:

1. Version of Mobile SDK Used: 5+
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: 9+
4. Device: Any
5. Steps to reproduce: Login and launch SSO URL, Idp is accessible via VPN only. 
6. Actual behavior: App doesn't connect to SSO URL with SDK 5+
7. Expected Behavior: App should connect to SSO URL
8. Error Log: NA

Hi All, 
We have a hybrid app created with Salesforce Mobile SDK and wrapped with Airwatch MDM. When running app, it doesn't get connected to client's VPN, though app developed with earlier SDK (3.3.3 and 4.1.0) works fine. 

Here is our observation
A) App built with MobileSDK version 3.3 and Cordova-ios v3.9.2 - works, shows correct IP address in Salesforce login history 
B) App built with MobileSDK version 5.0 and Cordova-ios v4.3.0 - never connect to Idp, shows incorrect IP address
C) Salesforce Mobile SDK Sample app built with MobileSDK version 5.2 and Cordova-ios v4.4.0 - never connect to Idp, shows incorrect IP address

These apps wrapped with Airwatch MDM should get our Client's IP address (IP assigned using VMware Tunnel configuration in Airwatch), but somehow the app with older SDK gets the IP but not with the newer SDK. 
which is a sample app with no custom code does not work, issues seems to lie in Airwatch, Salesforce or the integration between them.

Can someone help to resolve this issue? 
@bhariharan

Let me know for any further clarification

Regards,
Manish Kumar

**Comment by urthakkar** [comment]
lets discuss on the Google community as this is not a bug
