### ISSUE TITLE
I can´t "install" SalesforceSDKCore

### ISSUE THREAD

**Issue by CesarRN** [forcedotcom/SalesforceMobileSDK-iOS#2185]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.2 / Last
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 9 / iOS 11
4. Device: iPad
5. Steps to reproduce: pod update (pod 'SalesforceSDKCore' / pod 'SalesforceSDKCore', :path => 'node_modules/SalesforceMobileSDK-iOS')
6. Actual behavior: Error
7. Expected Behavior: Install library
8. Error Log:
[!] Unable to find a specification for `SalesforceSDKCore`
[!] No podspec found for `SalesforceSDKCore` in `node_modules/SalesforceMobileSDK-iOS`

Hello,

I create a project with Xcode from zero.
I add a empty pod file.
In the pod file, I added this lines:

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'SalesforceNetwork'
    pod 'SalesforceRestAPI'

   #pod 'SalesforceAnalytics', :path => 'node_modules/SalesforceMobileSDK-iOS'
    pod 'SalesforceSDKCore', :path => 'node_modules/SalesforceMobileSDK-iOS'
    pod 'SmartStore', :path => 'node_modules/SalesforceMobileSDK-iOS'
    pod 'SmartSync', :path => 'node_modules/SalesforceMobileSDK-iOS'

  # Pods for myProject

end

The command "pod update" fails with 

pod 'SalesforceSDKCore'      and with 
pod 'SalesforceSDKCore', :path => 'node_modules/SalesforceMobileSDK-iOS'

How can I solve this issue?

Thanks!!

**Comment by wmathurin** [comment]
Could you run forceios version and make sure it is indeed 5.2?

**Comment by CesarRN** [comment]
My forceios version is 5.2

Thanks

**Comment by wmathurin** [comment]
If you are using 5.2, the pod file in the generated app should look like
```
platform :ios, '9.0'

project 'iOSNativeTemplate.xcodeproj'
target 'iOSNativeTemplate' do

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

pod 'SalesforceAnalytics', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SalesforceSDKCore', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SmartStore', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SmartSync', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'

end
```
(see https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/v5.2.0/iOSNativeTemplate/Podfile)

**Comment by wmathurin** [comment]
We don't see any issues here - please re-open if you are still having trouble.
