### ISSUE TITLE
Cannot resync after app restart

### ISSUE THREAD

**Issue by booker-laputa** [forcedotcom/SalesforceMobileSDK-iOS#2189]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.2.0
2. Issue found in Native App or Hybrid App: ReactNative
3. OS Version: iOS 9.3.3
4. Device: iPhone 6 simulator
5. Steps to reproduce:
- Sync down data to a soup
- Store the _soupEntryId return from sync down
- Restart the app
- Use the saved _soupEntryId to perform reSync
6. Actual behavior: Sync failed
7. Expected Behavior: Resync data based on the last sync
8. Error Log:

Is there any proper way to do the resync?
I have many data to sync down and I have to update every time the user restart the app.
I just want to update the database with the newly created/updated record instead of download ing all records

**Comment by wmathurin** [comment]
The sample app does a resync (see https://github.com/forcedotcom/SmartSyncExplorerReactNative/blob/master/js/StoreMgr.js#L71).
It keeps the sync id in memory but would work just the same if the sync id was stored in SmartStore.
Where did you store the _soupEntryId from the sync down?

**Comment by booker-laputa** [comment]
I test it by sync down and get the soupEntryId
And I hardcode it to in a line to do the resync

**Comment by booker-laputa** [comment]
I have tired to store it in smartstore and retrieve it after app restart 
Still the resync not work on iOS but Android

**Comment by booker-laputa** [comment]
Problem found, the LastModifiedDate in iOS is not in correct format

> Server call for sync down failed errorError Domain=https://*************.salesforce.com/services/data/v39.0/query?q=SELECT%20LastModifiedDate,%20Id,Name%20FROM%20contact%20where%20LastModifiedDate%20%3E%202017-09-08T11:32:12.000+0800%20LIMIT%2010000 Code=400 "(null)" UserInfo={error=<CFArray 0x7fd96882cde0 [0x10c653a40]>{type = immutable, count = 1, values = (
	0 : <CFBasicHash 0x7fd968836f20 [0x10c653a40]>{type = immutable dict, count = 2,
entries =>
	0 : message = <CFString 0x7fd966485b10 [0x10c653a40]>{contents = "
LastModifiedDate > 2017-09-08T11:32:12.000 0800 LIMIT 10000
                                         ^
ERROR at Row:1:Column:94
line 1:94 no viable alternative at character ' '"}
	2 : errorCode = <CFString 0x7fd968858350 [0x10c653a40]>{contents = "MALFORMED_QUERY"}
}

)}}

**Comment by wmathurin** [comment]
Looks like something is off with the url encoding of the soql query (the + before the time stamp didn't get url encoded). We will look into it. Thanks.

**Comment by wmathurin** [comment]
Could you double check that you are indeed using forceios 5.2.
Because that issue was fixed for 5.2 see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2081/files

**Comment by booker-laputa** [comment]
Cool, it is fixed.

I just found that my mobile SDK is not updated successfully before

**Comment by NeliHarbuzava** [comment]
Hi! I got a similar error

I am using RN mobile SDK. The same code for Android works fine, but for iOS it a strange error after syncing down:
```
"{
    error =     (
                {
            errorCode = "MALFORMED_QUERY";
            message = "\n2020-08-25T11:06:27.000+0000 group by 0 order by LastModifiedDate DESC\n                                     ^\nERROR at Row:1:Column:144\nunexpected token: '0'";
        }
    );
}"
```
