### ISSUE TITLE
How to use FMDB from SmartStore outside SmartStore ?

### ISSUE THREAD

**Issue by CesarRN** [forcedotcom/SalesforceMobileSDK-iOS#2190]
Hello all.

I am using Salesforce SDK and for other reasons I need FMDB

Salesforce SDK uses FMDB.

I would like to use the FMDB´s classes that come with Salesforce SDK but I can´t import the FMDB´s classes, by example "FMDBDatabase.h"

Why I can´t import this classes? There are private or something like that?

Thanks!

**Comment by wmathurin** [comment]
In our next release, apps generated with forceios will consume FMDB through cocoapod.
For more information, see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2136
