### ISSUE TITLE
Pre login non secure pages does not respond to Cordova plugin requests

### ISSUE THREAD

**Issue by mlzur** [forcedotcom/SalesforceMobileSDK-iOS#2191]
Please fill out the following details:

1. Version of Mobile SDK Used:  5.1.0
2. Issue found in Native App or Hybrid App: Hybrid remote
3. OS Version: iOS 9.0-10.1,  this issue also applies to Android devices
4. Device: iPhone 5/6/7, iPad, Samsung Galaxy
5. Steps to reproduce:

- First create a remote hybrid app with the start page set to a secure Salesforce community start page (/Wrapper#Mob_Notifications). Connected app configured as part of the process.  bootconfig.json have these properties set:

"remoteAccessConsumerKey" : xxxxxxxxxxxxxxxxxxxxx,
"oauthRedirectURI" : "dev://auth/success",
"oauthScopes" : ["web", "api", "refresh_token", "offline_access"],
"isLocal" : false,
"startPage" : "/Wrapper#Mob_Notifications/",
"errorPage" : "error.html",
"shouldAuthenticate" :  true,
"attemptOfflineLoad" : false

- The Salesforce community has a controller that checks to see if user is authenticated, if user is logged in and authenticated then they are directed to the secure post-login page (/Wrapper#Mob_Notifications), otherwise user will be taken to the non-secure pre-login page (/Landing).

- Both pages  (/Wrapper#Mob_Notifications) and  (/Landing) import the following code for cordova.js

        <apex:outputPanel layout="none" rendered="{!IF(IsIphoneMobileApp,true,false)}"> 
            <apex:includeScript value="/resource/IosCordova/cordova.js"/>
        </apex:outputPanel>
        <apex:outputPanel layout="none" rendered="{!IF(IsAndroidMobileApp,true,false)}"> 
            <apex:includeScript value="/resource/AndroidCordova/www/cordova.js"/>
        </apex:outputPanel>

- Both pages have these cordova inappbrowser commands to open pdfs on external browsers:

        $('document').ready( function() {
            document.addEventListener("deviceready", function(){

                    //pdf forms & presentation files
                    $('body').on('click tap', '.requirement-download, .presentation-files, .pdf-download', 
                    function() {
                        if ($(this).hasClass('presentation-files')) {
                            var prefix = '{!communityPrefix}';
                            var url = 'https://' + prefix + '/' + $(this).attr('data-link');
                        }
                        else {
                            var url = $(this).attr('data-link');
                        }
                        //ios
                        if ({!IsIphoneMobileApp}) {
                            cordova.InAppBrowser.open(url, '_system');
                        }
                        //android
                        else {
                            navigator.app.loadUrl(url, {openExternal : true});
                        }
                    });
             }
        });

- The cordova inappbrowser plugin worked in the post-login secure page  (/Wrapper#Mob_Notifications), pdfs are opening externally in browser. The pre-login non secure (/Landing)  page have exactly the same code but does not respond to any cordova plugin command and not opening the pdfs in browser.

- Could this be a bug in the mobile sdk or is there are a setting that i'm missing?

6. Actual behavior:  The cordova plugins worked in the post-login secure pages  but NOT the pre-login non secure pages.

7. Expected Behavior: Pre login and post login pages defining the same Cordova plugin should work.

8. Error Log:

**Comment by wmathurin** [comment]
I'm not sure I follow.
With `shouldAuthenticate=true`, app should authenticate before loading the webview, so I don't follow how you end up in the /landing page. 

Anyway, I recommend you debug by attaching a browser (see https://cordova.apache.org/docs/en/latest/guide/next/#debugging-cordova-apps).
Typically, no cordova plugins work, it means cordova was not properly loaded.

I'm going to close this issue since it looks more like a 'how do I do ...?' question than an actual bug.
Please resume this discussion on our [google + community](https://plus.google.com/communities/114225252149514546445).
