### ISSUE TITLE
Issue with logout now option for salesforce app in iOS settings

### ISSUE THREAD

**Issue by jilumj** [forcedotcom/SalesforceMobileSDK-iOS#2192]
Please fill out the following details:

1. Version of Mobile SDK Used: Salesforce SDK 4.2
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 10.3
4. Device: iPad Air
5. Steps to reproduce:
 I am not able to logout from Salesforce app by switching on Logout Now option in 
iPhone settings app. The main problem that is i am not getting any notification on logging out from iPhone settings. We are using SmartStore for offline sync in app. Can anyone help me in this fix?

6. Actual behavior:

The app shows the screen in logged state.
7. Expected Behavior:

The app is expected to show Salesforce login screen

8. Error Log:

**Comment by bhariharan** [comment]
@jilumj This flow is no longer supported. Please upgrade to the latest Mobile SDK (`5.2`), where we have removed the `Settings` bundle.
