### ISSUE TITLE
5.2.0 getting credentials pushing the login screen

### ISSUE THREAD

**Issue by rgoldiez** [forcedotcom/SalesforceMobileSDK-iOS#2193]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.2.0
2. Issue found in Native App or Hybrid App: React Native
3. OS Version: iOS 11
4. Device: iPhone 7 Simulator
5. Steps to reproduce: Upgrading from 5.0.1 to 5.2.0 and checking credentials to decide whether to show login screen or splash screen (new users) has different behavior.
6. Actual behavior: Checking credentials launches login screen.
7. Expected Behavior: Checking credentials does **not** launch login screen.
8. Error Log: n/a

I've been using this SDK since the 4.x days for our React Native app (posting here because this issue does not appear to be react native related).  When our app is launched, we're checking (in react native) to see if the SDK has credentials to salesforce and if it does, we take the user into the app.  If no credentials are returned, the user is shown some splash screens with a button to login.

We're testing an upgrade from SDK 5.0.1 to 5.2.0 and the getCredentials method does not behave as it use to.  Now, simply calling the getCredentials method launches the login screen.

The very top of our react native app's componentWillMount:
```
    oauth.getAuthCredentials(
      (resp) => {
        // take user into app
      },
      (err) => {
        // show user splash screen
      }
    );

```

**My question**: Is this the new behavior that I need to design around?  Or is this a bug with 5.2.0?

**Comment by wmathurin** [comment]
There are four implementations of getAuthCredentials:
- the iOS implementation for ReactNative, the iOS implementation for Cordova,
- the Android implementation for ReactNative, the Android implementation for Cordova.

They were not consistent: some acting like a pure getter - others doing a login if there was no credentials to return.

In 5.2 with https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1990, we changed it to trigger a login but in 6.0, with https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2167, we went back to the original behavior (realizing that getter doing login was not behavior on cordova for instance). In 6.0, all four implementations should finally behave the same.

So you could call that a regression.

You can cherry pick the PR from dev if you want the 5.0 behavior on the more recent code.

**Comment by rgoldiez** [comment]
Thanks @wmathurin!

**Comment by wmathurin** [comment]
In 5.0
<pre>
iOS - react native: just getter
iOS - cordova: *does login*
Android - react native: just getter
Android - cordova: just getter
</pre>

In 5.2 - ios implementations consistent with each other - but not with android!
the PR: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1990
<pre>
iOS - react native: *does login*
iOS - cordova: *does login*
Android - react native: just getter
Android - cordova: just getter
</pre>

In 6.0 - all implementations consistent
the PRs: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2166 and https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2167
<pre>
iOS - react native: just getter
iOS - cordova: just getter
Android - react native: just getter
Android - cordova: just getter
</pre>
