### ISSUE TITLE
pod install failed while SQLCipher(3.4.1)

### ISSUE THREAD

**Issue by AdityaKotamraju** [forcedotcom/SalesforceMobileSDK-iOS#2194]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.2.0
2. Issue found in Native App or Hybrid App: native_swift
3. OS Version: IOS 10.3+
4. Device: iPhone / iPad
5. Steps to reproduce: Create a new forceios project or pod update
6. Actual behavior: forceios create failed /  pod install error
7. Expected Behavior: project should be created / forceios create should not failed
8. Error Log: 
![screen shot 2017-09-17 at 6 28 20 pm](https://user-images.githubusercontent.com/4414368/30521026-146c216c-9bd6-11e7-96c0-7956e77f5669.png)

**Comment by wmathurin** [comment]
From the error you copied, it looks like the compiler (gcc) is not working.
Look at config.log for more details.
