### ISSUE TITLE
Compile Time Issues in SmartStore -  Xcode 9.0

### ISSUE THREAD

**Issue by imanmk** [forcedotcom/SalesforceMobileSDK-iOS#2205]
1. Versions of Mobile SDK Used:
- 5.2.0 & 5.0.2
 
2. Issues found in Native App or Hybrid App:
- Native iOS

3. OS Version:
- iOS 11.0

4. Device:
- iPad Air 2

5. Steps to reproduce:
a- Build your app that has SmartStore library in Xcode 9.0
b - See compiler issues 

6. Actual behavior:
- SmartStore code does not compile.

7. Expected Behavior:
- SmartStore is expected to compile. 

8. Error Log:
- FMDatabase.m:
- Implicit redeclaration of function sqlite_rekey
- Too many arguments passed to function: sqlite3_reset

**Comment by wmathurin** [comment]
Please upgrade to Mobile SDK 5.3.
We just released Mobile SDK 5.3 (yesterday) and it has XCode 9 support.

**Comment by imanmk** [comment]
Just updated to 5.3.0. Same issues still exist.

**Comment by wmathurin** [comment]
Did you regenerate your application with forceios, or did you just update your podfile?
If you did the latter, you need to add
```ruby
pod 'FMDB', :git => 'https://github.com/forcedotcom/fmdb', :branch => '2.7.2_xcode9' 
```
because, an issue with FMDB on XCode 9 (see https://github.com/ccgus/fmdb/issues/591) which we fixed in our FMDB fork.

**Comment by mezhevikin** [comment]
@wmathurin Hello. Thank you for the fork, but it does not working for FMDB/SQLCipher.

`pod 'FMDB/SQLCipher', :git => 'https://github.com/forcedotcom/fmdb', :branch => '2.7.2_xcode9'`

I get error in setKey(key) method.

`libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by wmathurin** [comment]
It's 
```ruby
pod 'FMDB', :git ...
```
Not
```ruby
pod 'FMDB/SQLCipher', :git ...
```
(See my comment above).

**Comment by mezhevikin** [comment]
@wmathurin yes, i know. But i need FMDB/SQLCipher. 
I just thought you know how fix it.
Anyway, thk!

**Comment by wmathurin** [comment]
SmartStore depends on FMDB/SQLCipher (see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/SmartStore.podspec#L23).
All you need in your podfile, is to make sure to use our forked version of FMDB (the one with the fix for XCode 9). That's why you need the 
```ruby
pod 'FMDB', :git => 'https://github.com/forcedotcom/fmdb', :branch => '2.7.2_xcode9' 
```

Anyway, you can never do:
```ruby
pod 'SomePod/SubSpec', :git => 'url'
```
When you specify `:git =>` or `:path =>`, it is for the whole pod.

**Comment by joaomvfsantos** [comment]
@wmathurin Could you add this as a note in the Readme? Would spare people from having to dig into the closed issues like this one.

**Comment by wmathurin** [comment]
@rwhitley Where did we document that bit?

**Comment by srinivasbillav** [comment]
source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git' 
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

pod 'SalesforceAnalytics','=5.3.0'
pod 'SmartStore','=5.3.0'
pod 'SalesforceSDKCore','=5.3.0'
pod 'FMDB', :git => 'https://github.com/forcedotcom/fmdb', :branch => '2.7.2_xcode9'
