### ISSUE TITLE
SSO

### ISSUE THREAD

**Issue by mopi1402** [forcedotcom/SalesforceMobileSDK-iOS#2207]
This is not an error.

I just want to know if it's possible to automatically open the Salesforce Mobile SDK authentification page on the SSO (actually, there is a link to go to the SSO page)

Thanks

**Comment by bhariharan** [comment]
@mopi1402 This forum is reserved for issues with our code. Please use our Google+ community [here](https://plus.google.com/u/1/communities/114225252149514546445?cfem=1) for queries or anything else.
