### ISSUE TITLE
SDK asking to login again after login was previously succesful

### ISSUE THREAD

**Issue by oolufemi** [forcedotcom/SalesforceMobileSDK-iOS#2212]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.3.0 (updated from 4.3.1)
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 11
4. Device: Simulator
5. Steps to reproduce: 1) Login, 2) Click Allow - It asks you to login again OR  ) Login, 2) Click Allow - Works fine, 3) Try doing another activity - it asks you to login again.
6. Actual behavior:
7. Expected Behavior: It Shouldn't ask you to login again, it should be persisted, this is how it was in previous versions
8. Error Log: 
Kimble[15661:b52b] DEBUG com.salesforce: SFOAuthCoordinator:didFailLoadWithError: error code: -999, description: The operation couldn’t be completed. (NSURLErrorDomain error -999.), URL: https://login.salesforce.com/setup/secur/RemoteAccessAuthorizationPage.apexp
2017/09/22 09:57:14.867 Kimble[15661:b463] INFO com.salesforce: webView:didStartProvisionalNavigation: host=login.salesforce.com : path=/

**Comment by wmathurin** [comment]
We don't see that behavior at all in our sample apps.
Could you provide more details? How is you connected app configured?

**Comment by oolufemi** [comment]
The app is configured as follows (I'm putting the areas I think are related):
1) The project is a mixture of objective c and swift
2) Configured not to login at start up using - [SalesforceSDKManager sharedManager].authenticateAtLaunch = NO
3) Example of an operation  
`
let successfulLogin:(SFOAuthInfo,SFUserAccount) -> Void = { (info1,account) -> Void in
            self.serialQueue.async {
               // Calling a OperationQueue of SFRestRequest in here
            }
        }
        let failedLogin:(SFOAuthInfo,Error) -> Void = { (info1, e) -> Void in
            SFAuthenticationManager.shared().logout()
            DispatchQueue.main.async {
                 //Start whole process again
            }
        }
        //The problem seems to happen somewhere in login method
        SFAuthenticationManager.shared().login( completion: successfulLogin, failure: failedLogin)

`

That's the idea in a nutshell. My thinking is something have changed in the recent versions and I need something extra. Remember it worked in 4.3.1. I had this problem when I tried updating to 5.1 as well sometimes back.

**Comment by oolufemi** [comment]
@wmathurin 

I think I might have figured out what I'm doing wrong but I thought I should confirm if this is the case.

I just discovered there is a method called refreshCredentials. Currently, I call loginWithCompletion all the time. Am I suppose to be calling loginWithCompletion only the first time and refreshCredentials subsequently? 

Cheers

**Comment by oolufemi** [comment]
I have now been able to make this work. Is this usage right?
Code is now something like this:
         
        
        let successfulLogin:(SFOAuthInfo,SFUserAccount) -> Void = { (info1,account) -> Void in
                   self.serialQueue.async {
                        // Calling a OperationQueue of SFRestRequest in here
                   }
                   SFUserAccountManager.sharedInstance().currentUser = account
        }
        
        
        let failedLogin:(SFOAuthInfo,Error) -> Void = { (info1, e) -> Void in
          //Note it doesn't get here at all when this issue occurs
         SFAuthenticationManager.shared().logout()
                 DispatchQueue.main.async {
                        //Start whole process again
                  }
          }
       
        let credentials =   SFUserAccountManager.sharedInstance().currentUser?.credentials
        
        if (credentials != nil)
        {
            SFAuthenticationManager.shared().refreshCredentials(credentials!, completion: successfulLogin, failure: failedLogin)
        }
        else
        {
            SFAuthenticationManager.shared().login( completion: successfulLogin, failure: failedLogin)
        }

**Comment by wmathurin** [comment]
In the `if (credentials != nil)` case, you don't need to refresh, when you use our networking code, when the access token is expired, a refresh is automatically done and the request retried.

**Comment by trooper2013** [comment]
@oolufemi  Part of the problem is that the current user isn't getting set before your rest APi call. You should set  the current user  before call SFRestClient

```
 let successfulLogin:(SFOAuthInfo,SFUserAccount) -> Void = { (info1,account) -> Void in
              SFUserAccountManager.sharedInstance().currentUser = account
               self.serialQueue.async {
                    // Calling a OperationQueue of SFRestRequest in here
               }
            
    }
```

**Comment by oolufemi** [comment]
Thanks guys, I now I have it as this:

      


       let successfulLogin:(SFOAuthInfo,SFUserAccount) -> Void = { (info1,account) -> Void in
            SFUserAccountManager.sharedInstance().currentUser = account
            self.doAction()
        }
        
        
        let failedLogin:(SFOAuthInfo,Error) -> Void = { (info1, error) -> Void in
            SFAuthenticationManager.shared().logout()
            DispatchQueue.main.async {
                //Start whole process again
            }
        }
        
        
        let currentUser =   SFUserAccountManager.sharedInstance().currentUser
        if (currentUser != nil)
        {
            self.doAction()
        }
        else
        {
            SFAuthenticationManager.shared().login( completion: successfulLogin, failure: failedLogin)
        }

       func doAction()
      {
         //Calling a OperationQueue of SFRestRequest in here
      }


This seems to work fine. I will keep testing it out. I think we can close this ticket. Thanks again.
