### ISSUE TITLE
Issues with Encoding Request's queryParams in 5.3.0

### ISSUE THREAD

**Issue by imanmk** [forcedotcom/SalesforceMobileSDK-iOS#2214]
1. Version of Mobile SDK Used: 
- 5.3.0 

2. Issue found in Native App or Hybrid App:
- Native iOS 

3. iOS Version:
- 11.0

4. Device:
- iPad Air 2

5. Steps to reproduce:
- Have your request's `queryParms` to be of type  `[String: NSObject]` as in SDK v5.0.1. The values of this dictionary could be either `[String: Any]` or `[[String: Any]]`. Pass in the request to `SFRestAPI.sharedInstance().send(request, . . . )`

6. Actual behavior:
-  The app crashes because it attempts to call  `stringByURLEncoding` (expects a String) in `toQueryString` function (SFRestAPI.m) on the values of the queryParams, which as mentioned above could be either `[ String: Any ]` or `[ [ String: Any ] ]`.  I had no issues in 5.0.1 as the SDK took care of the above format.

7. Expected Behavior:
- 5.3.0 is expected to encode and handle queryParams correctly as in 5.0.1

8. Error Log:
- Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[Swift._EmptyArrayStorage stringByURLEncoding]: unrecognized selector sent to instance

**Comment by DavidSwift7** [comment]
I'm experiencing the same problem...

**Comment by imanmk** [comment]
Any updates on this? @wmathurin

**Comment by wmathurin** [comment]
You are right, the code expects strings in 5.3 (and 5.2). See [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/RestAPI/SFRestRequest.m#L293).
We take care of URL encoding, but you should make sure to pass a dictionary of strings to strings.

**Comment by imanmk** [comment]
@wmathurin This means I have to encode my dictionary values which are dictionaries or an array of dictionaries so at the end I would have a [String: String]. As a workaround I encoded them the same way as `toQueryString` but `SFRestAPI.sharedInstance().send` fails at the end:

```Error calling {our path}: Error Domain={ our url }/{ the path }?{key1}={value1}&{key2}={value2}& { etc }```

I did not see any release notes regarding this change. I was wondering if this is documented anywhere. Also, I'm curious of why` queryParams` allowed formats in 5.0.1 are not supported in the later versions.

**Comment by wmathurin** [comment]
queryParams is just for the name = value pairs that go into the URL for the request.
For the body, you should use one of the setCustomBody* methods.
See [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/RestAPI/SFRestRequest.h#L183).

**Comment by wmathurin** [comment]
For an example of a query with a json body, see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/RestAPI/SFRestAPI.m#L549

**Comment by wmathurin** [comment]
I'm going to close this issue.
We should document better the fact that queryParams is just that (the query params of the request URL) and that the setCustomBody* methods should be used for the actual body of the request.

**Comment by piyushprabhakar** [comment]
Hi @wmathurin , I am facing similar issue With Chatter implementation, My question is how i will convert a dictionary of type [String:Any] to [String:String] for nested dictionary like
```
{ 
   "body" : {
      "messageSegments" : [
         {
            "type" : "Text",
            "text" : "When should we meet for release planning? "
         },
         {   
            "type" : "Mention",
            "id" : "005D00000016Qxp"
         }]
       },
   "capabilities" : {
      "feedEntityShare" : {
         "feedEntityId" : "0D5B000000Py41t"
         }
      },
   "feedElementType" : "FeedItem",
   "subjectId" : "0F9B000000000W2"
}
```
https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/quickreference_share_feed_item.htm?search_text=Request%20parameter%20example

**Comment by wmathurin** [comment]
Please see the link I posted above ([link](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/RestAPI/SFRestAPI.m#L549)).

The queryParams is what goes on the url, it should only be name/value pairs so a string to string dictionary.
Use `addBodyForPostRequest:request:` to set the body.
```objective-c
SFRestRequest *request = [SFRestRequest requestWithMethod:SFRestMethodPOST path:path queryParams:nil];
[self addBodyForPostRequest:myJsonBody request:request];
```

**Comment by piyushprabhakar** [comment]
Hi @wmathurin ,
Thank you for providing quick solution, Its worked for me.
