### ISSUE TITLE
Logical and Memory Issues Reported by Xcode's Static Analyzer 

### ISSUE THREAD

**Issue by imanmk** [forcedotcom/SalesforceMobileSDK-iOS#2225]
1. Version of iOS SDK Used: 
- 5.3.0

2. Issue found in Native App or Hybrid App:
- Native iOS

3. iOS Version:
- 11.0.1

4. Device:
- iPad Air 2

5. Steps to reproduce:
- Create a project that uses `SalesforceSDKCore`, `SalesforceAnalytics`, `SmartStore` and `SmartSync`. Open the project via Xcode 9. 
- Analyze the project: `Product -> Analyze`
- Refer to the issues reported in the Issues Navigator.

6. Actual behavior:
- The Static Analyzer reports 104 issues including memory and logical errors.

7. Expected Behavior:
- The SDK is expected not to have any memory flaws or logical errors (at least not as many as Xcode reports).

8. Error Log:
- For instance, one memory error is:
`nil passed to a callee that requires a non-null 2nd parameter.` in `SFSmartStore.m`:
`FMResultSet* frs = [db executeQuery:explainSql withArgumentsInArray:arguments]`

**Comment by trooper2013** [comment]
@imanmk  Thanks for reporting. We are looking into some of these issues and will clean them up soon. Important to note that a lot the these warnings are pertaining to nullability constraints for Swift interoperability and others from the dependencies.

**Comment by bhariharan** [comment]
We have fixed most of these issues in our `dev` branch and will be a part of our upcoming release.
