### ISSUE TITLE
Crash in iPad Air with iOS 11

### ISSUE THREAD

**Issue by kgurijala** [forcedotcom/SalesforceMobileSDK-iOS#2238]
We see a crash in our iPad application, when tapping on the icon to switch the environments on login screen.

**1. Version of Mobile SDK Used:** 5.0.1 (I thought upgrade would solve the issue and so upgraded to 5.3.0 but it didn't)
**2. Issue found in Native App or Hybrid App:** Native
**3. OS Version:** iOS 11
**4. Device:** iPad Air
**5. Steps to reproduce:** On the login screen, tap on the icon to change the environments.
**6. Actual behavior:** Crashing when tapping on the icon to change the environments.
**7. Expected Behavior:** Should the show the list of environments like in iOS 10.3
**8. Error Log:** *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'unable to dequeue a cell with identifier SFDCLoginHostListCellIdentifier - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001143f61cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000113811f41 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001143fb362 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00000001132b6089 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   UIKit                               0x0000000110fd2968 -[UITableView _dequeueReusableCellWithIdentifier:forIndexPath:usingPresentationValues:] + 890
	5   UIKit                               0x0000000110fd25ba -[UITableView dequeueReusableCellWithIdentifier:forIndexPath:] + 89
	6   SalesforceSDKCore                   0x00000001108337a0 -[SFSDKLoginHostListViewController tableView:cellForRowAtIndexPath:] + 82
	7   UIKit                               0x000000011136041b -[_UIFilteredDataSource tableView:cellForRowAtIndexPath:] + 98
	8   UIKit                               0x0000000110fedef0 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 727
	9   UIKit                               0x0000000110fee51a -[UITableView _createPreparedCellForRowAtIndexPath:willDisplay:] + 81
	10  UIKit                               0x0000000110ffc137 -[UITableView _heightForRowAtIndexPath:] + 208
	11  UIKit                               0x00000001112a5939 -[UISectionRowData heightForRow:inSection:canGuess:] + 259
	12  UIKit                               0x00000001112abc1a -[UITableViewRowData heightForRow:inSection:canGuess:adjustForReorderedRow:] + 277
	13  UIKit                               0x00000001112adc21 -[UITableViewRowData rectForRow:inSection:heightCanBeGuessed:] + 1050
	14  UIKit                               0x0000000110fc9536 -[UITableView _rectForRowAtIndexPath:canGuess:] + 150
	15  UIKit                               0x0000000110fc942f -[UITableView _rectForRowAtIndexPath:usingPresentationValues:] + 226
	16  UIKit                               0x0000000110fcaaef -[UITableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:usingPresentationValues:] + 1214
	17  UIKit                               0x0000000110fcbb8f -[UITableView _scrollToRowAtIndexPath:atScrollPosition:animated:usingPresentationValues:] + 146
	18  UIKit                               0x0000000110fcba11 -[UITableView scrollToRowAtIndexPath:atScrollPosition:animated:] + 123
	19  SalesforceSDKCore                   0x000000011083283b -[SFSDKLoginHostListViewController makeLoginHostVisibleAtIndex:] + 99
	20  SalesforceSDKCore                   0x0000000110832fd6 -[SFSDKLoginHostListViewController viewDidLoad] + 748
	21  UIKit                               0x0000000111032d51 -[UIViewController loadViewIfRequired] + 1235
	22  UIKit                               0x000000011103319e -[UIViewController view] + 27
	23  UIKit                               0x00000001110888b7 -[UINavigationController preferredContentSize] + 197
	24  UIKit                               0x000000011100971c -[UIPresentationController preferredContentSizeDidChangeForChildContentContainer:] + 64
	25  UIKit                               0x00000001110054ae __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 109
	26  UIKit                               0x0000000110ea0c61 _runAfterCACommitDeferredBlocks + 318
	27  UIKit                               0x0000000110e8f30d _cleanUpAfterCAFlushAndRunDeferredBlocks + 280
	28  UIKit                               0x0000000110ebf600 _afterCACommitHandler + 137
	29  CoreFoundation                      0x0000000114398db7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	30  CoreFoundation                      0x0000000114398d0e __CFRunLoopDoObservers + 430
	31  CoreFoundation                      0x000000011437d324 __CFRunLoopRun + 1572
	32  CoreFoundation                      0x000000011437ca89 CFRunLoopRunSpecific + 409
	33  GraphicsServices                    0x00000001197ca9c6 GSEventRunModal + 62
	34  UIKit                               0x0000000110e94d30 UIApplicationMain + 159
	35  Insight                             0x000000010ecdc31a main + 362
	36  libdyld.dylib                       0x0000000116344d81 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by wmathurin** [comment]
It was fixed with [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2174).
I'm assuming you use Cocoapod, could you `SFSDKLoginHostListViewController.m` and make sure you see the fix (from the PR above).
What steps did you follow to upgrade?

**Comment by wmathurin** [comment]
Please re-open if you are still seeing the issues after doing a clean reinstall of 5.3.
