### ISSUE TITLE
WKWebview user agent malformed permanently after login, breaks other libraries

### ISSUE THREAD

**Issue by plummer** [forcedotcom/SalesforceMobileSDK-iOS#2240]
1. Version of Mobile SDK Used: 
5.3.0

2. Issue found in Native App or Hybrid App:
Hybrid

3. OS Version:
11

4. Device:
All iOS

5. Steps to reproduce:
a) Create an app that uses the web salesforce login view
b) After login with the view, instantiate a fresh WKWebview separately.

6. Actual behavior:
c) The user agent for the new WKWebview is now incorrectly a custom SalesForce user agent.

7. Expected Behavior:
c) The user agent for the new WKWebview is the original iOS user agent.

8. Error Log:
N/A

9. Code:

I believe the user agent is malformed here:
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/0dcd036ba365affd255d5054a06554f112101891/libs/SalesforceHybridSDK/SalesforceHybridSDK/Classes/SFHybridViewController.m#L294

I believe being set to this here:
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/0dcd036ba365affd255d5054a06554f112101891/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Common/SalesforceSDKManager.m#L687

10. Workaround

1) Create a clean WKWebview before login and store original user agent
2) After login, manually reset the user agent to the clean WKWebview's user agent

11. Impact

Many apps use the user agent for various things so it should not be modified at all. If it must be it should be returned to it's original version after use. This current behaviour breaks other apps that rely on it, I discovered it because it broke Braintree payment integration.

**Comment by bhariharan** [comment]
The use of a custom user agent in `Mobile SDK` is intentional. We have had this since the first version of our product. See [this issue](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1902) for more details and a workaround to use vanilla user agent.

**Comment by plummer** [comment]
@bhariharan This is a bizarre thing to just immediately close without discussing further. You modify an important system level property at a part of an application lifecycle, knowing that it will break integrate with an unknown (but large number) of other apps using completely cleaning instantiated WKWebviews, and even documenting the login method signature is not up for discussion? I can only imagine how much time this has wasted. This is as an extension to the fact there is no reasonable requirement to hack a user agent where another non-invasive system would work fine.

**Comment by wmathurin** [comment]
@plummer Are you saying that our user agent ends up in non-mobile sdk apps using WKWebView?

**Comment by plummer** [comment]
@wmathurin No, just that it leaks to other WKWebviews within the same app. So you might use a modal controller to display other external content aas in Facebook or Twitter app external links, and this would leak to that context.

**Comment by bhariharan** [comment]
The web user agent has been added back to our user agent in our dev branch [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2263). This will be a part of our upcoming release (`6.0`).

**Comment by plummer** [comment]
Hi, thanks for looking into this, this is a great improvement to the library.

Because UIWebViews and WKWebViews have different user agents, I don't think a fix that users a UIWebView will work in many situations (as you note, they have different behaviour, precisely why vendors would target them differently).

Since you are already calling dispatch_once_on_main_thread to perform this operation, could you not use the block syntax to set the property once?

```
// Get salesforce 
  navigatorWebview = WKWebView(frame: .zero, configuration: WKWebViewConfiguration())
  navigatorWebview?.loadHTMLString("<html></html>", baseURL: nil)
  navigatorWebview?.evaluateJavaScript("navigator.userAgent") { (defaultUserAgent, error) in
            
  // Capture a non-salesforce user agent before it is modified
  if let _defaultUserAgent = defaultUserAgent as? String {
    // Use _defaultUserAgent
  }

}
```
Thanks.
