### ISSUE TITLE
Duplicate interface definition for SFSDKSMartStoreLogger when building AccountEditor

### ISSUE THREAD

**Issue by curtisshipley** [forcedotcom/SalesforceMobileSDK-iOS#2245]
Please fill out the following details:

1. Version of Mobile SDK Used:   5.3 (github clone on 10/23/2017), XCode 9.0.1
2. Issue found in Native App or Hybrid App:   Can't build the AccountEditor Sample.
3. OS Version:   iOS - didn't get it to build.
4. Device:   Didn't get that far.
5. Steps to reproduce:
   a) Clone SalesforceMobileSDK-iOS Repo
   b) Run ./install.sh 
   c) Open SalesforceMobileSDK.xcworkspace in XCode
   d) Select AccountEditor in Target Dropdown.
   e) Select Product menu -> Build

6. Actual behavior:

Build fails with error message:

In file included from /Users/curtis/work/Schnitzer/SalesForceiOS/libs/SmartStore/SmartStore/Classes/SFSDKSmartStoreLogger.m:30:
/Users/curtis/work/Schnitzer/SalesForceiOS/libs/SmartStore/SmartStore/Classes/SFSDKSmartStoreLogger.h:32:1: error: duplicate interface definition for class 'SFSDKSmartStoreLogger'
@interface SFSDKSmartStoreLogger : NSObject
^
In file included from /Users/curtis/work/Schnitzer/SalesForceiOS/libs/SmartStore/SmartStore/Classes/SFSDKSmartStoreLogger.m:1:
In file included from /Users/curtis/work/Schnitzer/SalesForceiOS/libs/SmartStore/SmartStore/SmartStore-Prefix.pch:10:
/Users/curtis/Library/Developer/Xcode/DerivedData/SalesforceMobileSDK-ebtdlyzplpzllbbdvdpaewnxuijs/Build/Products/Debug-iphonesimulator/Headers/SmartStore/SFSDKSmartStoreLogger.h:32:12: note: previous definition is here
@interface SFSDKSmartStoreLogger : NSObject
           ^
1 error generated.

7. Expected Behavior:

To have the sample app build correctly.

8. Error Log:

See build error above.

**Comment by bhariharan** [comment]
Could you try blowing away your `DerivedData` folder and building?

**Comment by tonetip** [comment]
D'oh! Bitten by DerivedData again.  That worked. Thanks!

**Comment by curtisshipley** [comment]
That worked. Thank you.
