### ISSUE TITLE
.plist configuration on SDK 5.3 based hybrid application not working

### ISSUE THREAD

**Issue by Manish-Kr09** [forcedotcom/SalesforceMobileSDK-iOS#2261]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.3
2. Issue found in Native App or Hybrid App:  Hybrid App
3. OS Version: iOS 10+
4. Device: Any
5. Steps to reproduce: Given in description 
6. Actual behaviour: Given in description 
7. Expected Behavior: Given in description 
8. Error Log: NA

Hi all, 

I am adding this issue here as I do not receive any feedback or input on my google plus query. 
https://plus.google.com/+ManishKumarRocks4ever/posts/TPh2wwjeYVp

We have created an application using salesforce mobile SDK 5.3. This app was deployed to customer environment using MobileIron. 

As per the documentation 
https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/oauth_mdm.htm 

This app should support .plist configuration,  but when trying it was not. App only shows default configured URLs. 

@bhariharan any input?

Regards,
Manish Kumar

**Comment by bhariharan** [comment]
I have responded on the Google+ community post. Let's continue this discussion there. This forum is reserved for issues with our code.
