### ISSUE TITLE
Dealing with Ghost Records and Records User No Longer has Access to

### ISSUE THREAD

**Issue by lpt-joshua** [forcedotcom/SalesforceMobileSDK-iOS#2285]
Hi,

I'd like to know if it is possible to remove locally synced files that the user no longer has access to (via access/sharing rule changes)?

I know there is a `smartsync.cleanResyncGhosts()` function but as the notice in the documentation stated it is an expensive operation to run. Is it possible for the mobile app to recognise records that are no longer queryable or is a full sync down required.

Thank you for your time and help.

**Comment by wmathurin** [comment]
You

**Comment by wmathurin** [comment]
`smartsync.cleanResyncGhosts()` is expensive but it is less expensive than doing a full sync down.
Like a full sync down, it goes to the server to get all records - but only asks for the record ids however.
The ids are then compared to the one in the database, and the ones found locally that were not returned from the server are deleted.

**Comment by wmathurin** [comment]
There is no better way unless you write a lot of server side code (apex) to capture the state of your clients and compute the diff on the server.
