### ISSUE TITLE
How to get more than 2000 records in REST Get call; from salesforce to jQuery

### ISSUE THREAD

**Issue by rshyam36** [forcedotcom/SalesforceMobileSDK-iOS#2288]
I am having issue in jQuery Code to fetching the records from SFDC.
Can you guys help me to use this **nextRecordsUrl** keyword in jQuery?
Here is my code.
`** var soqlquery_kld = 'select+id,Name+from+Account' ;**  -It is returning only 2000 records, but actually totalSize from json response is 25000+ 

api.callRestApi('/query?q=' + soqlquery_kld, 'GET')
                   .then(function(response){
                       $scope.isLoading = false;
                       $scope.myOrganization = response.data.records;
                       Soql_filter_Records = response.data.records;
                       
                       $scope.isSpinShow = false;
                       $scope.NoofRecords123 = false;
                       $scope.OnlyOneRecord = false;
                       if (response.statusText == 'OK') {
                           $scope.isResponseOk = true;
                       } 
                       $scope.TotalNumberOfRecords = response.data.totalSize;

                       if ($scope.isResponseOk == true) {
                           if($scope.TotalNumberOfRecords == 0){
                           $scope.NoofRecords123 = true;
                           }

                       if($scope.TotalNumberOfRecords == 1){
                       $scope.OnlyOneRecord = true;
                       }
                       }
                       JSONToCSVConertor(response.data.records,'All_Data_Soql',true);

                   }, function(err){
                       $scope.myOrganization = $scope.err;
                       $scope.isLoading = false;
                       $scope.errorMessage = $scope.err;
                       $scope.isSpinShow = false;
                       $scope.IsError = true;
                   })`

Please help.

**Comment by bhariharan** [comment]
@rshyam36 This forum is reserved for bugs/issues with our source code. Please post queries on our Google+ community [here](https://plus.google.com/u/1/communities/114225252149514546445?cfem=1).
