### ISSUE TITLE
SFLoginViewController Fails to Navigate Back

### ISSUE THREAD

**Issue by hikui** [forcedotcom/SalesforceMobileSDK-iOS#2298]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.3
2. Issue found in Native App or Hybrid App: Native iOS App
3. OS Version: 11.2
4. Device: iPad
5. Steps to reproduce:

	The bug exists in `RestAPIExplorer` as well.
	
	There are two situations that can trigger this problem.
	
	Situation 1:
   
   1. Log in as a user.
   2. Force close the app
   3. Open the app again, tap **Switch User > New User** and enter the SFLoginViewController.
   4. Now the back button is shown but doesn't respond to user's action.
   
	Situation 2:
   
   1. Enter SFLoginViewController by tapping **Switch User > New User**
   2. Close the app
   3. Re-open the app
   4. Now the SFLoginViewController will pop up automatically as the first screen with back button shown. But the back button doesn't respond to user's action.

6. Actual behavior:
	The back button not responding
7. Expected Behavior:
	Tapping the back button should switch back to the previous user.
8. Error Log:

	`self.previousUserAccount` in `SFLoginViewController.m` is `nil` in these situations. Thus it cannot navigate back.

**Comment by brandonpage** [comment]
Hi @hikui, thank you for creating this issue.  I was able to reproduce the bug in version 5.3 of the Mobile SDK and it has already been fixed in dev branch.  You should see the fix in the next release #safeharbor.
