### ISSUE TITLE
iTunesConnect issue - SDK 5.3.0 contains LLVM instrumentation

### ISSUE THREAD

**Issue by quidcomobile** [forcedotcom/SalesforceMobileSDK-iOS#2299]
Please fill out the following details:

1. Version of Mobile SDK Used:  iOS 5.3.0

2. Issue found in Native App or Hybrid App: Native iOS app

3. OS Version: 10.x+

4. Device: All devices compatible

5. Steps to reproduce: 

Submit the app to iTunesConnect.

6. Actual behavior:

iTunesConnect rejected our app - which embeds iOS SDK 5.3.0 - because of LLVM Instrumentation in the following sub-frameworks:

- ServiceChat
- ServiceCore
- ServiceCases  

We cannot rebuild ServiceChat because it is not open-source. 

Resolving App Rejections for GCC and LLVM Instrumentation

- https://developer.apple.com/library/content/qa/qa1964/_index.html#//apple_ref/doc/uid/DTS40017675-CH1-INSPECT

7. Expected Behavior:

iTunesConnect should not reject the app.

8. Error Log:

We inspected the app package, and found out that ServiceChat.framework contains LLVM instrumentation.

**Comment by urvint** [comment]
@quidcomobile this is unfortunately not the right group/repo that supports the Chat sdk.  Please reach out to your AE and/or support team and they would be able to help

**Comment by bhariharan** [comment]
@quidcomobile Please post questions about `SnapIns` on their [Google+ community](https://plus.google.com/u/0/communities/104189600084591024148).
