### ISSUE TITLE
Incomplete documentation for Passcode security feature

### ISSUE THREAD

**Issue by booker-laputa** [forcedotcom/SalesforceMobileSDK-iOS#2301]
I cannot find the documentation for enabling passcode feature for iOS

Is there any documentation for this feature?

**Comment by bhariharan** [comment]
@booker-laputa You need to enable it on your connected app. [Here](https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/connected_apps_security_pin.htm) is our doc.
