### ISSUE TITLE
How to get all the result in a query with more than 2000 records

### ISSUE THREAD

**Issue by asueroaltimetrik** [forcedotcom/SalesforceMobileSDK-iOS#231]
How to get all the result in a query with more than 2000 records?

I have a class that implements SFRestDelegate, I send a query with a request like this:
-[SFRestAPIDelegate request:didLoadResponse:] request = <SFRestRequest 0xa0dd700 
endpoint: /services/data 
method: GET 
path: /v23.0/query 
queryParams: {
  "q" : "SELECT Id FROM ACR_SubArea_Label__c WHERE Account__r.ACR_iPad__c = TRUE"
} 

And I get a big response, with 2000 records, done in 0 and totalSize = 5989.
Doing the same SOQL, with a count() I get that yes, the total of objects that I must be getting is totalSize:
1) but why I only get 2000(SF limit I presume)?, 
2) how do I get the other 3989 records that I'm not getting?, 
3) Does done mean that I'm not getting all the records for the query?

Thanks a lot,
Andrés Suero.

**Comment by brad36** [comment]
Hi @khawkins, thanks for posting the above code, very helpful! Is it still the recommended approach?

**Comment by khawkins** [comment]
It should still work, or you could use more of a blocks-based approach if you do your requests like that.  I think this would still be the general way to go.

**Comment by rshyam36** [comment]
I am having issue in jQuery Code.
Can you guys help me to use this **nextRecordsUrl** keyword in jQuery?
Here is my code.
** var soqlquery_kld = 'select+id,Name+from+Account' ;**  -It is returning only 2000 records, but actually totalSize from json response is 25000+ 

api.callRestApi('/query?q=' + soqlquery_kld, 'GET')
                   .then(function(response){
                       $scope.isLoading = false;
                       $scope.myOrganization = response.data.records;
                       Soql_filter_Records = response.data.records;
                       
                       $scope.isSpinShow = false;
                       $scope.NoofRecords123 = false;
                       $scope.OnlyOneRecord = false;
                       if (response.statusText == 'OK') {
                           $scope.isResponseOk = true;
                       } 
                       $scope.TotalNumberOfRecords = response.data.totalSize;

                       if ($scope.isResponseOk == true) {
                           if($scope.TotalNumberOfRecords == 0){
                           $scope.NoofRecords123 = true;
                           }

                       if($scope.TotalNumberOfRecords == 1){
                       $scope.OnlyOneRecord = true;
                       }
                       }
                       JSONToCSVConertor(response.data.records,'All_Data_Soql',true);

                   }, function(err){
                       $scope.myOrganization = $scope.err;
                       $scope.isLoading = false;
                       $scope.errorMessage = $scope.err;
                       $scope.isSpinShow = false;
                       $scope.IsError = true;
                   })

Please help.
