### ISSUE TITLE
Smart store not opening After logout and Login with another user 

### ISSUE THREAD

**Issue by piyushprabhakar** [forcedotcom/SalesforceMobileSDK-iOS#2327]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.3.1
2. Issue found in Native App or Hybrid App: Native ios App
3. OS Version: 11.1
4. Device: iPhone
5. Steps to reproduce: 

Logout form app and Login with another user. After that smart store become corrupted and and in log it gives error "FMDatabaseQueue could not reopen database for path"

6. Actual behavior:
once user Logout form app and Login with another user. Smart store become corrupted and and in log it gives error "FMDatabaseQueue could not reopen database for path". And after that sync down does not work. The app will start working if you quit and restart app from suspended state.

7. Expected Behavior:
It should be able to open smart store.
8. Error Log:

2017-12-13 00:47:02.049661+0530 AppName-DEV[36410:412916] **FMDatabaseQueue could not reopen database for path /Users/piyush/Library/Developer/CoreSimulator/Devices/DDAAD1C0-9196-4D82-91AA-1800223F7FD3/data/Containers/Data/Application/78AF0A54-4635-4439-BA8E-FCF7117867DF/Documents/com.abc.dev/00D3E0000000XW0UAM/0053E0000018xGG/internal/stores/defaultStore/store.sqlite**
2017-12-13 00:47:02.050258+0530 **AppName-DEV[36410:412824] error opening!: 14**

**Comment by wmathurin** [comment]
We need more information. We have plenty of apps that logout/login and use smartstore without issues. Are you holding on to a SFSmartStore instance during the logout/login?

**Comment by piyushprabhakar** [comment]
i have initialise Smart store like below in a common class.
    `static var sharedStore = SFSmartStore.sharedStore(withName: kDefaultSmartStoreName) as? SFSmartStore`
Once i call logout then in document directory i can see **store.sqlite** file getting deleted.

**Comment by wmathurin** [comment]
This is not a bug. This is by design for data security. User data is deleted when the user logs out (or when the admin revokes the user refresh token - therefore logging him/her out).
If you have data that is not tied to the user and that needs to be persisted, you should use a global smartstore. See https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/offline_global_smartstore.htm

**Comment by piyushprabhakar** [comment]
I am aware of it, deletion of data is absolutely fine but when i log out of the application and log in with another user then, i can see in document directory for logged in the user the store.sqlite file is getting created but when i try to access it it shows error "FMDatabaseQueue could not reopen database for path /Users/piyush/Library/Dev.....". And after that sync down on this sqlite file dosent work. But sync down start working as soon as i quit the app and restart the app.

**Comment by wmathurin** [comment]
Don't hold on to a SFSmartStore instance or it won't work.
Instead, instead call `SFSmartStore.sharedStore(...)` when you need a handle to the SFSmartStore.
You can add a helper method in your common class:
```swift
func getSmartStore() -> SFSmartStore {
    return SFSmartStore.sharedStore(withName: kDefaultSmartStoreName) as? SFSmartStore;
}
```

**Comment by piyushprabhakar** [comment]
I tried this, but it is not working, its giving same error. Below things is happening
1) If i logout and login from same profile, then its working.
2) If i logout from and login from different profile, its giving error "FMDatabaseQueue could not reopen database for path /Users/piyush/Library/Dev" 
3) After logout if i Quit application and restart it again, and then i log in with another profile then it works.
Could you suggest what could be the issue?

**Comment by wmathurin** [comment]
Are you always calling ` SFSmartStore.sharedStore(...)` after login completed or is there any time where you might be use a SFSmartStore instance obtained earlier?

**Comment by piyushprabhakar** [comment]
I have removed all instance of  `static var sharedStore = SFSmartStore.sharedStore(withName: kDefaultSmartStoreName) as? SFSmartStore` Now i am using 
```
func getSmartStore() -> SFSmartStore {
    return SFSmartStore.sharedStore(withName: kDefaultSmartStoreName) as? SFSmartStore;
}
```
After login first i create soup then i call sync down, In smart store inspector i can see the indices is getting created 
<img width="308" alt="screenshot1" src="https://user-images.githubusercontent.com/14050203/33975682-205dacd2-e0b6-11e7-9e0a-f3d896c8e33a.png">, But when i query soup count it says "Query failed, no row returns "
I get  below error log right after login, when i create soup and call sync down

```
2017/12/14 04:22:13.867 AppName-DEV[89639:6f57] DEBUG com.salesforce: createIndexStmt: CREATE INDEX IF NOT EXISTS TABLE_55_14_idx ON TABLE_55 ( TABLE_55_14 )

2017-12-14 09:52:13.875484+0530 AppName-DEV[89639:2967042] Unknown error calling sqlite3_step (10: disk I/O error) eu
2017-12-14 09:52:13.875796+0530 AppName-DEV[89639:2967042] DB Query: begin exclusive transaction
2017-12-14 09:52:13.876382+0530 AppName-DEV[89639:2967042] Unknown error finalizing or resetting statement (10: disk I/O error)
2017-12-14 09:52:13.876771+0530 AppName-DEV[89639:2967042] DB Query: begin exclusive transaction
2017-12-14 09:52:13.878706+0530 AppName-DEV[89639:2967042] Unknown error calling sqlite3_step (10: disk I/O error) rs
2017-12-14 09:52:13.878940+0530 AppName-DEV[89639:2967042] Error calling sqlite3_step (1: cannot commit - no transaction is active) SQLITE_ERROR
2017-12-14 09:52:13.879157+0530 AppName-DEV[89639:2967042] DB Query: commit transaction
2017-12-14 09:52:13.879365+0530 AppName-DEV[89639:2967042] Unknown error finalizing or resetting statement (1: cannot commit - no transaction is active)
2017-12-14 09:52:13.879622+0530 AppName-DEV[89639:2967042] DB Query: commit transaction
2017/12/14 04:22:13.880 AppName-DEV[89639:6f57] DEBUG com.salesforce: syncDown:{
  "status" : "FAILED",
  "target" : {
    "idFieldName" : "Id",
    "modificationDateFieldName" : "LastModifiedDate",
    "iOSImpl" : "SFSyncUpTarget",
    "type" : "rest"
  },
  "_soupEntryId" : 0,
  "endTime" : 0,
  "maxTimeStamp" : 0,
  "totalSize" : 0,
  "type" : "syncUp",
  "progress" : 0,
  "startTime" : 0
}
```

**Comment by piyushprabhakar** [comment]
While debugging I also found that the Smart store creation in failing in the above-mentioned scenario.

        ```
do {
            let smartStoreObj = SharedSmartStore()

            try smartStoreObj.getSmartStore()?.registerSoup(soupName, withIndexSpecs: accountIndexSpecs, error: ())
            
            
        } catch let error as NSError {
            print("Can not crate soup \(error.localizedDescription)")
        }

```
this function is returning error : **disk I/O error**
