### ISSUE TITLE
Duplicate interface definition for class 'CSFAuthRefresh'

### ISSUE THREAD

**Issue by Sudalaiyandi** [forcedotcom/SalesforceMobileSDK-iOS#2347]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.3.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 11.0
4. Device: iPhone 6
5. Steps to reproduce: Upgrading SDK from 4.3.1 to 5.3.1 using pods 
6. Actual behavior:
7. Expected Behavior:
8. Error Log:Duplicate interface definition for class 'CSFAuthRefresh'

<img width="1069" alt="screen shot 2017-12-19 at 12 49 30 pm" src="https://user-images.githubusercontent.com/24268120/34145245-2213b612-e4bb-11e7-8c9d-0bf3d684f49a.png">

**Comment by bhariharan** [comment]
@Sudalaiyandi This issue typically goes away by wiping `DerivedData` and performing a fresh build. Also, `CSFAuthRefresh` and all other classes from the erstwhile `NetworkSDK` have been removed from `Mobile SDK 6.0` which released earlier today and will no longer be supported. Please migrate to `SFRestAPI` instead.

**Comment by Sudalaiyandi** [comment]
@bhariharan I used 4.3.1 in my application, how to upgrade from 4.3.1 to 6.0.Kindly give idea about it. I used pod file for upgrading.
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ChaseOpps' do
source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git' # need to be first 
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
pod 'CocoaLumberjack'
pod 'SalesforceSDKCore', 
pod 'SalesforceNetwork'
pod 'SalesforceRestAPI'
pod 'FMDB'
pod 'SmartStore', 
pod 'SmartSync', 
end

**Comment by bhariharan** [comment]
@Sudalaiyandi Read our upgrade steps in our developer guide. Since you're upgrading from a really old version, I recommend regenerating your app from our latest template using `forceios` and moving your assets to the newly generated template app.
