### ISSUE TITLE
'SalesforceSDKCore/SFLogger.h' file not found

### ISSUE THREAD

**Issue by Sudalaiyandi** [forcedotcom/SalesforceMobileSDK-iOS#2348]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.0.0
2. Issue found in Native App or Hybrid App:Native
3. OS Version:iOS 11.0
4. Device:iPhone 6
5. Steps to reproduce:Create New application using pod file
6. Actual behavior:Application show error as 
> 'SalesforceSDKCore/SFLogger.h' file not found
7. Expected Behavior:
8. Error Log:'SalesforceSDKCore/SFLogger.h' file not found
I used pod file like this 

 Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'salesforceApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git' # need to be first 
source 'https://github.com/CocoaPods/Specs.git'
  # use_frameworks!
pod 'CocoaLumberjack'
pod 'SalesforceSDKCore'
pod 'SalesforceNetwork'
pod 'SalesforceRestAPI'
pod 'FMDB'
pod 'SmartStore'
pod 'SmartSync'
  # Pods for salesforceApp

  target 'salesforceAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'salesforceAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

**Comment by bhariharan** [comment]
@Sudalaiyandi `SFLogger` was marked deprecated in `Mobile SDK 5.3` to be removed in `Mobile SDK 6.0`. Please read our release notes from `5.3` [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/v5.3.0/readme.md#whats-new-in-53). You need to replace that with `SFSDKLogger`. Do read our release notes from `6.0` as well.

**Comment by Sudalaiyandi** [comment]
Thanks @bhariharan for your quick reply.I solved this issue.
