### ISSUE TITLE
The value retrieved via iOS SDK Rest API is different from the web part.

### ISSUE THREAD

**Issue by phoenixruyi** [forcedotcom/SalesforceMobileSDK-iOS#2356]
Please fill out the following details:

1. Version of Mobile SDK Used: 
V23.0

2. Issue found in Native App or Hybrid App:
Native App

3. OS Version:
iOS 9.0

4. Device:
iPad

5. Issue:
[Background]
Our system contains 2 parts(Web Part and Mobile Part). And the mobile part is implemented with SFDC iOS SDK.

[Issue]
Recently, user reported that some data in iPad was different from the web part.
We checked, the data is retrieved via iOS SDK Rest API and the value was changed.
For example: 
The "Base_Price__c"  is 74.10000 in Web. But the we got 74.09999999999999 via iOS SDK Rest API.
Why is the field of data type number storing more numbers in decimal places than defined?

[Additional information]
1. It works well in the past.
2. We tried to reset the value in Web Part, the issue still is existed.
3. We tried with Rest API of Workbench, no issue.
4. We tried to get the data with data loader, no issue.
5. Field: Base_Price__c  
    Data Type: Number (Number Options: Length 13 Decimal Places 5)
    SFDC iOS SDK ："v23.0"
6. iOS Source
NSString * soql = select Id,.....,Base_Price__c,...... from Product__c
- (SFRestRequest *)requestForQuery:(NSString *)soql;

**Comment by bhariharan** [comment]
@phoenixruyi As I mentioned in your post on our `Google+ community`, we are simply providing a wrapper for available REST APIs. We don't modify the data received from the server, we pass it along to the application. The web layer might have additional logic at the presentation layer to truncate number of decimal places. Besides, from your post it sounds like the client code hasn't been changed, which indicates that it's not an SDK issue.
