### ISSUE TITLE
Dynamic community URL

### ISSUE THREAD

**Issue by kSakthiraj** [forcedotcom/SalesforceMobileSDK-iOS#2360]
Please fill out the following details:

1. Version of Mobile SDK Used:  4.3.1
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: All
4. Device: All
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

In Our mobile app, we want to store the multiple community URL for the quick domain select. In Android, we can able to do this by updating "LoginManager.JAVA". But in iOS can't do that, Please help me on this.

**Comment by trooper2013** [comment]
@kSakthiraj You should consider upgrading the mobile SDK (v4.3.1 is old). If you are looking for a way to add more domains/hosts to the list in the LoginView, standard way is to use the settings icon in the LoginView screen. Is your question pertaining to adding additional hosts/domains to this list programmatically?  try this

```
SFSDKLoginHost *host = [SFSDKLoginHost hostWithName:@"anId" host:@"login.salesforce.com" deletable:YES];
[[SFSDKLoginHostStorage sharedInstance] addLoginHost:host];

```

**Comment by kSakthiraj** [comment]
I have identified the above mentioned SFSDKLoginHostStorage code in "SFSDKLoginHostListViewController.m". But we are leveraging mobile SDK. So I'm not able to access the ".m" file in my project directory.  I've tried to access SFSDKLoginHostStorage in "AppDelegate+SalesforceHybridSDK.m" and "UIApplication+SalesforceHybridSDK.m" files, which is also not possible. Can you suggest SFSDKLoginHostStorage in mobile SDK?

**Comment by bhariharan** [comment]
@kSakthiraj `SFSDKLoginHostStorage` and `SFSDKLoginHost` are public headers in `Mobile SDK 6.0`. Please upgrade to `Mobile SDK 6.0` by generating a new hybrid app using [forcehybrid](https://www.npmjs.com/package/forcehybrid) and use the code snippet above to add a custom host. As a side note, updating `LoginManager.java` is not the correct way to add more hosts on `Android`. The correct way to do this is to override `servers.xml` in your app and provide your own `servers.xml` with a list of hosts. Take a look at our documentation on this.
