### ISSUE TITLE
Salesforce SDK Security Scan using Checkmarx

### ISSUE THREAD

**Issue by ankitaporwal** [forcedotcom/SalesforceMobileSDK-iOS#2362]
Please fill out the following details:

1. Version of Mobile SDK Used: 
    **Latest**
2. Issue found in Native App or Hybrid App:
     Android SDK
3. OS Version:
4. Device:
5. Steps to reproduce:
     San using checkmarx
6. Actual behavior:
     Many issues reported by Checkmarx under Critical
7. Expected Behavior:
    Should pass security scan
8. Error Log:
    - 

Hi, 

I am using salesforce android sdk in my android application, as a part of security scan of my application using checkmarx i performed scan on salesforce sdk as its handling all the session and data for my app. There are many critical issues listed by them. Please have a look at them and let me know your views on it
[SalesforceAndroidSDK.pdf](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/1634877/SalesforceAndroidSDK.pdf)
[SalesforceSDK2.pdf](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/1634878/SalesforceSDK2.pdf)

. 

Looking forward for your response!

Thanks,
AP

**Comment by bhariharan** [comment]
@ankitaporwal This forum is for bugs/issues identified with our code. Our code has been reviewed thoroughly by our product security team and certified secure. Most of the issues in that report seem to be incorrect. For example, I saw the following snippet in there:
```
Method reEncryptAccountInfo at line 204 of /SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKUpgradeManager.java
defines additionalOauthKeys, which is designated to contain user passwords. However, while plaintext passwords are later assigned to additionalOauthKeys, this variable is never cleared from memory.
```
The above comment is inaccurate since `additionalOauthKeys` has nothing to do with passwords and does not store any sensitive information.

**Comment by ankitaporwal** [comment]
Hi @bhariharan , 

Since the issues provided by checkmarx are not incorrect, can you suggest some good tool for the same ? We have created a native iOS and android mobile app using the salesforce sdk, and we need to check the code with respect to security issues. Do you have any idea of the tool that can pass the salesforce sdk in terms of security checks. 

Thanks,
AP

**Comment by bhariharan** [comment]
@ankitaporwal Unfortunately I have no recommendations. Our SDK is thoroughly reviewed by product security before we release though. If there are specific concerns, we can discuss them. Please reach out to me over e-mail if there are specific concerns.
