### ISSUE TITLE
Unable to find SalesforceSwiftSDK via cocoa pods

### ISSUE THREAD

**Issue by ankitaporwal** [forcedotcom/SalesforceMobileSDK-iOS#2363]
Please fill out the following details:

1. Version of Mobile SDK Used: 
    **6.0**
2. Issue found in Native App or Hybrid App:
    **Native**
3. OS Version:
    N/A
4. Device:
     N/A
5. Steps to reproduce:
    run pod install on this sample after downloading
6. Actual behavior:
   Error while installing pods
7. Expected Behavior:
   Pods should install 
8. Error Log:
 Ankita-Porwal:iOSIDPTemplate ankita$ pod install
Analyzing dependencies
Pre-downloading: `PromiseKit` from `https://github.com/mxcl/PromiseKit`, tag `5.0.3`
Pre-downloading: `SwipeCellKit` from `https://github.com/SwipeCellKit/SwipeCellKit.git`, tag `2.0.0`
Pre-downloading: `WYPopoverController` from `https://github.com/sammcewan/WYPopoverController`, tag `0.3.8`
[!] Unable to find a specification for `SalesforceAnalytics`

Hi,

I also checked the pod here - https://cocoapods.org/?q=SalesforceSwiftSDK and it says pod not found. 

I am currently using sdk 5 in my iOS app and looking forwarded to upgrade it to 6. Any suggestions for solving this issue at my end. I am running latest cocoa pods in my mac.

Looking forward to your response!

Thanks,
AP

**Comment by bhariharan** [comment]
@ankitaporwal Our pod specs are present [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs), they're not published to `cocoapods.org`. Please use `forceios` from [here](https://www.npmjs.com/package/forceios) and generate a `native_swift` app to use `SalesforceSwiftSDK`. You can also take a look at our template [here](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/tree/master/iOSNativeSwiftTemplate) that uses `SalesforceSwiftSDK`.
