### ISSUE TITLE
SFOAuthSessionRefresher not call completion block

### ISSUE THREAD

**Issue by milczi** [forcedotcom/SalesforceMobileSDK-iOS#2395]
Please fill out the following details:

1. IOS SDK 5.2.0 - 5.3.1
2. Issue found in Native App App:
3. iOS Version: 10, 11
4. Device: Ipad air 2
5. Steps to reproduce: 
Make object SFOAuthSessionRefresher
Run two times method
` refresher.refreshSession(completion: { [unowned self] credentials in
        }, error: { [unowned self] error in   })
` 
The second time should be called before first completion/error will return.
It also does not work when you create 2 SFOAuthSessionRefresher objects.
6. Actual behavior:  One of callback(tested on error callback) will never return
7. Expected Behavior: Refresher should always call some of his closures
8. Error Log:

**Comment by bhariharan** [comment]
@milczi We fixed an issue with multiple requests originating from `SFRestAPI` attempting to refresh credentials simultaneously in `Mobile SDK 6.0`. Could you try with `Mobile SDK 6.0`? Why are you attempting to call `SFOAuthSessionRefresher` directly anyway? Session management is typically handled by `Mobile SDK` internally. Also, why call it twice? What's your use case?

**Comment by milczi** [comment]
OK so maybe my flow is not correct. 
Base assumption is after first login user should not see login screen again. Even if application is killed by a user.
When user do not use application for a while I send this `refreshSession` request. In other case our REST/SOAP request returns with invalid session message.
Can you tell me the proper flow? How session management works in Mobile SDK internally (5.2.0)?

We can't change Xcode to 9.0 yet which is required for SDK 6.0
Thanks, Paweł

**Comment by bhariharan** [comment]
@milczi If you're getting logged out while making requests and/or getting an `INVALID SESSION` message back from the server when you call `refreshSession`, this indicates that your refresh token has expired and/or is invalid. In this case, the user getting logged out is expected. I would recommend looking at your org's session management settings on the server - it's likely that the org's settings revoke the refresh token after a certain amount of time. The client simply honors the server side settings. If you use `SFRestAPI` to make your requests, session management is handled internally by the SDK. Calling `refreshSession` won't work with an expired refresh token and shouldn't be called within the app for this use case. Either way, this appears to be an org session timeout configuration issue.

**Comment by milczi** [comment]
Could you at least point me a PR where it is fixed (`refresher.refreshSession`). We don't use `SFRestAPI`. We use standard network requests to web services which requires from us sessionId.

**Comment by bhariharan** [comment]
@milczi The queue that serializes refresh requests is in `SFRestAPI`. For now, what I recommend for your app is to build a simple gating wrapper that makes one refresh request at a time using `SFOAuthRefresher`. If an in-flight refresh request exists, gate the other refresh requests and simply use the new token once the first one comes back. There shouldn't be multiple parallel refresh requests, only 1 is required.
