### ISSUE TITLE
SmartSync: SyncUp multiple records in one request

### ISSUE THREAD

**Issue by sysmei** [forcedotcom/SalesforceMobileSDK-iOS#2420]
Please fill out the following details:

 Version of Mobile SDK Used: 5.0
 Issue found in Native App or Hybrid App: Hybrid
 OS Version: Android 7.0
 Device: Galaxy S6
 Steps to reproduce: SyncUp records (with SmartSync)
 Actual behavior: Slow performance
 Expected Behavior: Is there option to sync multiple records

Hi!

I am using SmartSync/Smartstore to synchronize offline data with Salesforce.
I am noticing that all modified records are passed to SF with method syncUpOneRecord (in java code). That means one request to SF for each modified record.

Is there option to sync multiple records in one request?

**Comment by zaitsman** [comment]
Did you ever find a solution?

**Comment by wmathurin** [comment]
Currently sync up doesn't use batch.

**Comment by sysmei** [comment]
nope

**Comment by wmathurin** [comment]
Batching sync up now supported in dev (see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2783) - will be in the next version of Mobile SDK (7.1).
