### ISSUE TITLE
Hybrid Remote App - authenticate does not refresh VisualForce session using documented session refresh technique

### ISSUE THREAD

**Issue by alsocalledchris** [forcedotcom/SalesforceMobileSDK-iOS#2424]
1. Version of Mobile SDK Used: 6
2. Issue found in Native App or Hybrid App: Hybrid Remote
3. OS Version: iOS 10/11
4. Device: iPhone 6 Plus
5. Steps to reproduce: 

Have a session that has expired (delete sessions via session manager in Salesforce setup/admin screens.) Call cordova.require("com.salesforce.plugin.oauth").authenticate via JS code and then set the src for the iFrame to be the blank page in the success callback function.

6. Actual behavior: Only OAuth session is refreshed, VisualForce session/cookie is not

Can see the successful request for the OAuth token via /services/oauth2/token and then the request to get the user's details via login.salesforce.com/id/...(so the OAuth2 token is refreshed OK) - however the call to the blank page via the iFrame returns a 302 and the request is taken to /visualforce/session?url={url of blank page}

7. Expected Behavior: User's session is refreshed - both OAuth2 and VisualForce and page is not reloaded - as per guidance in https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/hybrid_managing_sessions.htm
8. Error Log: NA

Note: 

1) This works fine in Android
2) Sometimes you get a full page refresh - possibly when the session has not expired and you call authenticate... needs some more investigation - have seen it sometimes doing a full page refresh
3) Subsequent calls to the authenticate function never call the passed in success function and a 'WARN timer already exists' warning is displayed in Safari debug console - so you can only do it once.

**Comment by bhariharan** [comment]
[This PR](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2438) fixes this issue and will be a part of our upcoming release (`Mobile SDK 6.1`). Detailed explanation of the bug and the fix is [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2438#discussion_r171980517).
