### ISSUE TITLE
Hybrid Remote App: Full Page session refresh does not work

### ISSUE THREAD

**Issue by alsocalledchris** [forcedotcom/SalesforceMobileSDK-iOS#2428]
Please fill out the following details:

1. Version of Mobile SDK Used: 6
2. Issue found in Native App or Hybrid App: Hybrid
3. OS Version: iOS 10
4. Device: iPhone 6 plus
5. Steps to reproduce: Have an open App, delete all the sessions, handle the session timeout error by refreshing the page as per SDK docs - using window.location.reload()
6. Actual behavior: 

Page is refreshed but user is taken to a 'null' page
You can see the GET /secur/frontdoor.jsp triggered by the page refresh being called with a null return URL (...&retURL=(null)..) after a successful calls to services/oauth2/token and id/{id}/{id}

7. Expected Behavior: Page is refreshed and user is taken back to the page they were on
8. Error Log: NA

Works fine in Android

**Comment by alsocalledchris** [comment]
Android seems fine - iOS consistently breaks (although sometimes does actually work- feels like a race condition?). Not a Lightning page. What do you mean by the platform to return a valid retUrl? - the /visualforce/session?url={https://absolute url of where we were} has the right URL, the OAuth requests kick in and are requested OK then the next request is to the frontdoor.jsp request with the null retUrl - that's coming from the SDK IMO.

**Comment by bhariharan** [comment]
The code that computes the value of `retUrl` is [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceHybridSDK/SalesforceHybridSDK/Classes/SFHybridViewController.m#L417) and it's based on the `URL` that's passed in during the refresh call, i.e., the page that's currently being displayed.

**Comment by alsocalledchris** [comment]
Thanks for your response. The logs from XCode are (I have added the {..} to remove sensitive details):

2018-02-27 09:47:48:673 AppName[7647:593925] Authentication complete. Redirecting to '%252Fvisualforce%252Fsession%253Furl%253Dhttps%25253A%25252F%25252F{subdomain}.eu15.visual.force.com%25252Fapex%25252Ff{namespace}__{pageUrl}' through frontdoor.
2018-02-27 09:47:48:684 AppName[7647:593925] webView:decidePolicyForNavigationAction:decisionHandler: Loading URL 'https://eu15.salesforce.com/secur/frontdoor.jsp?sid=[redacted]&retURL=(null)&display=touch'

Notice the retUrl=(null). Is something in SFHybridViewController.m authenticationCompletion messing it up? - lines [852/853](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/50f80b62b263944805e021f496ee86d35393a313/libs/SalesforceHybridSDK/SalesforceHybridSDK/Classes/SFHybridViewController.m#L853)?:

NSURL *returnUrlAfterAuth = [self frontDoorUrlWithReturnUrl:originalUrl returnUrlIsEncoded:YES createAbsUrl:createAbsUrl];
        NSURLRequest *newRequest = [NSURLRequest requestWithURL:returnUrlAfterAuth];

as that changes the URL between the two debug log entries.

**Comment by alsocalledchris** [comment]
Further investigation - debugging the SDK with our App in Xcode I can see the code is failing [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/50f80b62b263944805e021f496ee86d35393a313/libs/SalesforceHybridSDK/SalesforceHybridSDK/Classes/SFHybridViewController.m#L432) if the URL it is given is %252Fvisualforce%252Fsession%253Furl%253Dhttps%25253A%25252F%25252F{subdomain}.eu15.visual.force.com%25252Fapex%25252Ff{namespace}__{pageUrl}' - this is when the null is returned.

When the code works the returnUrlString is an absolute URL and not the relative URL pointing to the visualforce session page. Although this code is causing the null error of the return URL I think that the fact that the URL has the relative URL with the 'visualforce/session' is wrong - it shouldn't have this URL (this visualforce/session URL is also breaking the silent refresh as mentioned in https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2424)

@bhariharan any help with this appreciated - this is causing a lot of issues and I'm not the only one affected. Many thanks.

**Comment by alsocalledchris** [comment]
@bhariharan I've created a pull request with a fix that I've tested that works:
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2434. Let me know what you think. Thanks

**Comment by bhariharan** [comment]
[This PR](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2438) fixes this issue and will be a part of our upcoming release (`Mobile SDK 6.1`). Detailed explanation of the bug and the fix is [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2438#discussion_r171980517).
