### ISSUE TITLE
UIStatusBarStyle overridden by the framework

### ISSUE THREAD

**Issue by davidnuvolar** [forcedotcom/SalesforceMobileSDK-iOS#2436]
Please fill out the following details:
In a project that uses status bar appearance based on every view controller, the status bar appearance is overridden by the Salesforce SDK (SFSDKRootViewController.m, method preferredStatusBarStyle gets called even when any SF SDK view is present). The issue can be reproduced easily with the sample app "RestAPIExplorer" included in the SDK.

1. Version of Mobile SDK Used: 6.0.0
2. Issue found in Native App or Hybrid App: Native App (Objective C)
3. OS Version: iOS 11.2
4. Device: All
5. Steps to reproduce:
Launch in Xcode the sample app RestAPIExplorer
Open the RestAPIExplorer-Info.plist file and add the key "View controller-based status bar appearance" (UIViewControllerBasedStatusBarAppearance) and set it to YES.
Open the InitialViewController.m file and add the following method:
```
- (UIStatusBarStyle)preferredStatusBarStyle
{
    return UIStatusBarStyleLightContent;
}
```
Run the application.
Log in to salesforce.

6. Actual behavior:
After log in the app and be presented with the InitialViewController screen, status bar text is dark

7. Expected Behavior:
After log in the app and be presented with the InitialViewController screen, status bar text should become white as per "UIStatusBarStyleLightContent"

8. Error Log:
N/A

Here I attach the only two files that I modified in the RestAPIExplorer project in order to prove the bug.
[ModifiedFiles.zip](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/1770753/ModifiedFiles.zip)

**Comment by trooper2013** [comment]
@davidnuvolar Thanks for reporting this issue. We are aware of the problem and are looking into possible fixes. In the mobilesdk we do use additional UIWindows for authentication & passcode  purposes and we've found that UIKit doesn't handle presence of multiple UIWindows gracefully for certain functions.

**Comment by bhariharan** [comment]
[This PR](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2503) should address this issue.
