### ISSUE TITLE
Can not see login screen when using application on device.  

### ISSUE THREAD

**Issue by jeffreyjackson** [forcedotcom/SalesforceMobileSDK-iOS#2437]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 11.2
4. Device: Simulator and Device
5. Steps to reproduce: launch app
6. Actual behavior: shows screenshot below on device
7. Expected Behavior: works on device
8. Error Log: there is no error other than the one show on screen

![img_1915](https://user-images.githubusercontent.com/867999/36854745-b6423e6e-1d3f-11e8-912b-90150b1c102d.PNG)

**Comment by jeffreyjackson** [comment]
I get the screenshot above when trying to run the application on device.  However, everything works as intended when on a simulator.

**Comment by brandonpage** [comment]
@jeffreyjackson The error in the screenshot indicates that the consumer key/redirect uri combination is incorrect.  If the consumer key, redirect uri and connection connection url are all identical for the build on simulator and on device then it may be a network issue.  Are your computer and mobile device on the same network?  Can you hit the connection url in the browser of your mobile device?

**Comment by brandonpage** [comment]
@jeffreyjackson Did you resolve the issue?

**Comment by brandonpage** [comment]
@jeffreyjackson Please reopen this issue if the problem still exists.  Thanks!
