### ISSUE TITLE
Application crashes at login or logout if there is no network connection

### ISSUE THREAD

**Issue by davidnuvolar** [forcedotcom/SalesforceMobileSDK-iOS#2449]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.0.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 11.2
4. Device: any
5. Steps to reproduce:
Ensure you have a fresh install of the sample application SmartSyncExplorer (no previously logged in user) provided by the SDK itself
Turn on airplane mode in the device so that there is no network connection available. If running from a simulator, turn off the network (wifi and/or wired) of the computer
Launch the application.
6. Actual behavior:
The application crashes
7. Expected Behavior:
An error is presented to the user stating that there is no network connection.
8. Error Log:
Check screenshot for the stack trace:
![screen shot 2018-03-15 at 13 29 57](https://user-images.githubusercontent.com/20855201/37463489-a84a5d3e-2855-11e8-8150-fe9361042a11.png)

Extra notes:
The same happens if you are logged in and tap the log out button when the device does not have network connection. We can reproduce this issue every single time.

**Comment by trooper2013** [comment]
@davidnuvolar  With 6.1 version of the  SDK you should be able configure error handling in the AppDelegate to avoid the crash.  Nevertheless by default a crash should not occur. I will mark it as a bug. 

```
@implementation AppDelegate <SFUserAccountManagerDelegate>

@synthesize window = _window;

- (id)init
{
  ...  
       [[SFUserAccountManager sharedInstance] addDelegate:self];
....
}


- (BOOL)userAccountManager:(SFUserAccountManager *)userAccountManager error:(NSError *)error info:(SFOAuthInfo *)info {
    //...
    //  check error, if offline handle accordingly
    //  if handled  
   //        return YES;
    
    ...
    return NO;
}

```

**Comment by trooper2013** [comment]
@davidnuvolar You can take a look at PR #2481

**Comment by bhariharan** [comment]
Fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2481) and will be a part of our next release.
