### ISSUE TITLE
Excessive thread creation does the app gets frozen

### ISSUE THREAD

**Issue by nuvolarmobileteam** [forcedotcom/SalesforceMobileSDK-iOS#2454]
Please fill out the following details:

We faced this issue after updating the SDK to version 6 for our app. It does weird stuff until the app gets frozen and we have to kill it. It didn't happen before updating Salesforce SDK. 

1. Version of Mobile SDK Used: 6.0.0
2. Issue found in Native App or Hybrid App: Native App (Objective C)
3. OS Version: iOS 11.2
4. Device: All
5. Steps to reproduce:
 1. Run attached project on a device. It is SmartSyncExplorer sample project with a small piece of code which triggers a few requests after the app enters foreground coming from background.
 2. Send the app to background and open it back. Repeat the process several times. 
 3. Pay attention to thread creation every time the app comes from background.  

6. Actual behavior:
Described process produces thread creation spirals out of control, which ends up getting the app frozen. 

7. Expected Behavior:
Control thread creation due to NSURLSession, not to create threads unnecessarily. 

8. Error Log:
We attach the sample project and 2 videos with described issue. 
We spotted that changing line 53 of file SFNetwork the app behaves much better, like before. 
`NSString *identifier = [NSString stringWithFormat:@"com.salesforce.network"];`

The project and videos are in next link:
https://www.dropbox.com/s/epur0m8ju7uksdr/SalesforceSDK-Issue-Sample.zip?dl=0

**Comment by wmathurin** [comment]
Thanks, we will have a look.

**Comment by bhariharan** [comment]
Fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2550).

**Comment by bhariharan** [comment]
This will be a part of our next release.
