### ISSUE TITLE
Remote Hybrid cannot refresh user's session silently

### ISSUE THREAD

**Issue by alsocalledchris** [forcedotcom/SalesforceMobileSDK-iOS#2466]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.1
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: iOS 10/11
4. Device: iPhone 8
5. Steps to reproduce:

Handle session expiry (or just manually try and refresh the user's session) via documented advanced approach using cordova.require("com.salesforce.plugin.oauth").authenticate and an iFrame: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/hybrid_managing_sessions.htm

// Refresh oauth token
cordova.require("com.salesforce.plugin.oauth").authenticate(
    function(creds) {
        // Reload hidden iframe that points to a blank page to
        // to refresh Visualforce domain cookies
        var iframe = document.getElementById("blankIframeId");
        iframe.src = src;

        // Refresh CSRF cookie
        // Get the provider array
        var providers = Visualforce.remoting.Manager.providers;
        // Get the last provider in the arrays (usually only one)
        var provider = Visualforce.remoting.last;
        provider.refresh(function() {
            //Retry call for a seamless user experience
        });
	
    }, 
    function(error) {
        console.log("Refresh failed");
    }
);

6. Actual behavior: Mobile App is taken to the blank page requested by the iFrame taking the user away from the App's page. Session is refreshed successfully though.
7. Expected Behavior: Mobile App stays on current page, session is refreshed succesfully
8. Error Log: NA

@bhariharan please can you look at this? - as suspected last week, 6.1 has not fixed this issue correctly see for the original issue (results has now changed a bit) https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2424. We are relying on this functionality for our App to be successful. Many thanks

**Comment by alsocalledchris** [comment]
Using UI Web view does not work either - the App crashes with the error:

bool _WebTryThreadLock(bool), 0x60c00001ed40: Tried to obtain the web lock from a thread other than the main thread or the web thread. This may be a result of calling to UIKit from a secondary thread. Crashing now...

**Comment by bhariharan** [comment]
@alsocalledchris Does [this fix](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2468) prevent the app from crashing?

**Comment by alsocalledchris** [comment]
Thanks, will check shortly - not sure if that fix will stop the app going to the iframe src though? (I don't want to use UI web view if possible.)

**Comment by bhariharan** [comment]
The `iframe` issue is likely something else. I'll take a look.

**Comment by alsocalledchris** [comment]
@bhariharan we have checked this and the App still goes to the iframe's requested src instead of staying on the current page with the dev branch latest code.

**Comment by wmathurin** [comment]
Looking at https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/hybrid_managing_sessions.htm

It says:
JavaScript Remoting in Visualforce => Refresh session and CSRF token from JavaScript => Catch the session timeout event, and then **either reload the page or load a new iFrame**. 

The sample code later only shows how to **reload the page**:
```javascript
<Controller>.<Method>(
    <params>,
    function(result, event) {
        if (hasSessionExpired(event)) {
            // Reload will try to redirect to login page
            // Container will intercept the redirect and 
            // refresh the session before reloading the 
            // origin page
            window.location.reload();
        } else {
            // Everything is OK. 
            // Go ahead and use the result.
            // ...
        },
    {escape: true}
);
```

In your case, you should replace:
```javascript
window.location.reload();
```
with
```javascript
document.getElementById('iframeid').src = document.getElementById('iframeid').src
```

**Comment by wmathurin** [comment]
Let me know if my suggestion above helped.
Please re-open if you are still having an issue.

**Comment by alsocalledchris** [comment]
@wmathurin please see my initial post which already uses the iframe, your comment does not help and the issue still stands.

**Comment by alsocalledchris** [comment]
@wmathurin I don't seem to be able to reopen, please can you? Thanks.

**Comment by wmathurin** [comment]
This issue is almost 4 years old. The code has changed a lot since then. 
Please open a new issue if you think it is still relevant today.
