### ISSUE TITLE
build.md shows 404

### ISSUE THREAD

**Issue by anilabsinc-ajay** [forcedotcom/SalesforceMobileSDK-iOS#2475]
Please fill out the following details:

1. Version of Mobile SDK Used: 
2. Issue found in Native App or Hybrid App:
3. OS Version:
4. Device:
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

**Comment by bhariharan** [comment]
It was intentionally removed [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2381), since it contained outdated instructions.
