### ISSUE TITLE
Not able to relauch the authication view after pressing back button on the login screen of SFloginView Controller

### ISSUE THREAD

**Issue by anilabsinc-ajay** [forcedotcom/SalesforceMobileSDK-iOS#2476]
Please fill out the following details:

1. Version of Mobile SDK Used: 
6.1
2. Issue found in Native App or Hybrid App:
Native
3. OS Version:
11
4. Device:
Simulator
 Error : already in progress

**Comment by trooper2013** [comment]
@anilabsinc-ajay Can you provide more details?

**Comment by fobin** [comment]
I think this might be the same issue you can see if you do this: 

1. Go to login window
2. Exit app -> wait 10 mins 
3. Go back and try to login
4. You get auth error (the login session timed out or something similar).

There is no way of going back from this state. User has to kill the app before can login again.
