### ISSUE TITLE
Empty navigation bar still present after specifying to not show nav bar on login screen

### ISSUE THREAD

**Issue by dancuconati** [forcedotcom/SalesforceMobileSDK-iOS#2477]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.1
2. Issue found in Native App or Hybrid App: Hybrid
3. OS Version: 11
4. Device: iPhone 8
5. Steps to reproduce: 
In 6.0.0, when dismissing the navbar on the login page, it also removed the nav controller. In 6.1, using the same code, a gray nav controller and bar is now present at the top.

Here is the code we are using in AppDelegate+SalesforceHybridSDK.m 's didFinishLaunchingwithOptions method:

SFSDKLoginViewControllerConfig *loginViewConfig = [[SFSDKLoginViewControllerConfig  alloc] init];
loginViewConfig.showSettingsIcon = NO;
loginViewConfig.showNavbar = NO;
[SFUserAccountManager sharedInstance].loginViewControllerConfig = loginViewConfig;

6. Actual behavior: Gray Nav controller is visible
7. Expected Behavior:
8. Error Log: N/A

Here you can see the navbar still present:
![simulator screen shot - iphone 8 - 2018-03-27 at 14 09 51](https://user-images.githubusercontent.com/20344292/37986191-d37642bc-31c8-11e8-81f1-05b56e27a0f8.png)

![screen shot 2018-03-27 at 2 16 36 pm](https://user-images.githubusercontent.com/20344292/37986527-afe9d3f8-31c9-11e8-8c95-bc40dbb2002a.png)

**Comment by trooper2013** [comment]
@dancuconati Please check the PR  https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2478

**Comment by dancuconati** [comment]
@trooper2013 Thanks! Do you have an ETA on when a new version is scheduled to be released?

**Comment by trooper2013** [comment]
@dancuconati  6.2 will be released tentatively around June/July. But in the interim here is another way to solve the problem. 
1. Create your own LoginViewController which extends SFLoginViewController and override the viewDidLoad. 
2. Set the factory block in the loginConfig to use the extended SFLoginViewController within the app delegate.

```objective-c
#import <UIKit/UIKit.h>
#import "SFLoginViewController.h"
@interface MyLoginViewController : SFLoginViewController
@end

#import "MyLoginViewController.h"
@implementation MyLoginViewController
- (void) viewDidLoad {
    [super viewDidLoad];
    if (![self showNavbar]) {
        self.navigationController.navigationBarHidden = YES;
    }
}
@end
```
In the app delegate add the following lines.
```objective-c
[SFUserAccountManager sharedInstance].loginViewControllerConfig.showNavbar = NO;
[SFUserAccountManager sharedInstance].loginViewControllerConfig.loginViewControllerCreationBlock = ^SFLoginViewController * _Nonnull{
        return [[MyLoginViewController alloc] init];
    };
```

**Comment by dancuconati** [comment]
@trooper2013 Thank you!

**Comment by Yossud** [comment]
Thanks @trooper2013 for your help.

But the status bar is shown after the fix: 
![image](https://user-images.githubusercontent.com/31250418/41506372-4ed70dbe-7225-11e8-9bba-a1bde2b9d181.png)

![image](https://user-images.githubusercontent.com/31250418/41506389-7c13ce84-7225-11e8-811d-f736099042b9.png)
