### ISSUE TITLE
The project has a lot of warnings

### ISSUE THREAD

**Issue by freegor** [forcedotcom/SalesforceMobileSDK-iOS#2483]
Please fill out the following details:

1. Version of Mobile SDK Used: **6.1**
2. Issue found in Native App or Hybrid App: **Native App**
3. OS Version: **11**
4. Device: **all**
5. Steps to reproduce: **just compile and build the project**
6. Actual behavior: **a lot of warnings, old version of external frameworks**
7. Expected Behavior: **no warnings, up-to-date version of external frameworks**
8. Error Log: --

**Comment by wmathurin** [comment]
Thanks @freegor, we'll try and reduce the number of warnings in a future release.

**Comment by wmathurin** [comment]
Just did another pass (see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2555).
Most warnings are in 3rd party libraries. I fixed the ones I could.
