### ISSUE TITLE
- Switch user:- Back button is missing.

### ISSUE THREAD

**Issue by rohithksuvarna** [forcedotcom/SalesforceMobileSDK-iOS#2490]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.1.0
2. Issue found in Native App or Hybrid App: Native iOS app
3. OS Version: 10.13
4. Device: iPad
5. Steps to reproduce:  call switchToNewUser after login, back button is not visible.
6. Actual behavior: back button is not visible.
7. Expected Behavior: back button should be visible if the allUserCount > 0 which was fine in version 5.* but not in latest SDK.

**Comment by brandonpage** [comment]
@rohithksuvarna Sorry for the slow response.  Can you please elaborate on this issue?  What version of iOS?  I see the back arrow when switching users in our native iOS sample apps.  Does the back button display if you switch users via the dev menu?  You can activate the dev menu with the shake gesture on physical device or control + command + z on simulator.

**Comment by brandonpage** [comment]
I hope the lack of response means the issue has been resolved.  Please reopen if this is still an issue.
