### ISSUE TITLE
Status Bar Bug

### ISSUE THREAD

**Issue by Yossud** [forcedotcom/SalesforceMobileSDK-iOS#2494]
1. Version of Mobile SDK: 5.3.1
2. Issue found in Native App
3. OS Version: 11.1
5. Steps to reproduce:
Custom login page from VF page don't shown on the status bar after upgrade the sdk and upgrade Xcode to Xcode 9:
![screen shot 2018-04-15 at 16 34 48](https://user-images.githubusercontent.com/31250418/38779003-ccce0772-40ca-11e8-8a91-43421325c466.png)

In iPhone x it's more horrible:
![screen shot 2018-04-15 at 17 07 27](https://user-images.githubusercontent.com/31250418/38779327-5aad7538-40cf-11e8-97ed-bd975cb86790.png)

7. Expected Behavior from the old version: status bar in the same color like all vf page.
![screen shot 2018-04-15 at 16 48 05](https://user-images.githubusercontent.com/31250418/38779131-aa4bf748-40cc-11e8-9608-01619e99b6fc.png)

**Comment by bhariharan** [comment]
`Xcode 9` is only supported with Mobile SDK 6+. Please upgrade to the latest (Mobile SDK 6.1).

**Comment by Yossud** [comment]
The bug still exist on SDK 6.1 after removing navigation bar with [https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2477](url) workaround
