### ISSUE TITLE
App crashes in FMDB

### ISSUE THREAD

**Issue by srinivasbillav** [forcedotcom/SalesforceMobileSDK-iOS#2498]
Please fill out the following details:

1. Version of Mobile SDK Used:  6.1.0
2. Issue found in Native App or Hybrid App:  Native App
pod Used
    source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git'
    source 'https://github.com/CocoaPods/Specs.git'
    
    use_frameworks!
    pod 'SalesforceAnalytics'
    pod 'SalesforceSDKCore'
    pod 'SmartStore'
    pod 'SmartSync'
    pod 'FMDB', :git => 'https://github.com/forcedotcom/fmdb', :branch => '2.7.2_xcode9'

3. OS Version: 10.3.1
4. Device: iPad Air
5. Steps to reproduce:
Run app in simulator 10.3.1 using xcode 9.2 
App Crash's in FMdatabase.m file

6. Actual behavior: Nothing Happans
7. Expected Behavior: App should work properly
8. Error Log: 

- (BOOL)setKey:(NSString*)key {
    NSData *keyData = [NSData dataWithBytes:[key UTF8String] length:(NSUInteger)strlen([key UTF8String])];
    return [self setKeyWithData:keyData];
}
FMDatabase.m line number 420

**Comment by bhariharan** [comment]
@srinivasbillav Which version of `Cocoapods` are you using? Could you generate your app with [forceios](https://www.npmjs.com/package/forceios) and verify that the generated app works fine?

**Comment by wmathurin** [comment]
Make sure you use cocoapod 1.4.0.
Also don't use the forcedotcom fork of fmdb, instead add the following at the end of your podfile
```ruby
# Fix for xcode9/fmdb/sqlcipher/cocoapod issue - see https://discuss.zetetic.net/t/ios-11-xcode-issue-implicit-declaration-of-function-sqlite3-key-is-invalid-in-c99/2198/27
post_install do | installer |
  print "SQLCipher: link Pods/Headers/sqlite3.h"
  system "mkdir -p Pods/Headers/Private && ln -s ../../SQLCipher/sqlite3.h Pods/Headers/Private"
end
```

**Comment by wmathurin** [comment]
Please re-open if you are still having an issue.
