### ISSUE TITLE
Application fails to be archived as iOS if installing SDK with cocoapods 1.5.0

### ISSUE THREAD

**Issue by davidnuvolar** [forcedotcom/SalesforceMobileSDK-iOS#2504]
Please fill out the following details:

1. Version of Mobile SDK Used: 
6.1
2. Issue found in Native App or Hybrid App:
Native
3. OS Version:
N/A
4. Device:
N/A
5. Steps to reproduce:
Update Cocoapods to 1.5.0
run pod install
Archive your iOS app
6. Actual behavior:
Xcode generates a Generic Xcode Archive
7. Expected Behavior:
Xcode generates an iOS App Archive
8. Error Log:
N/A

I can confirm that with Cocoapods 1.4.0 this works.

I attach to sample projects. One with some random Pod installed (Cocoapods DemoOK.zip) and another one with Salesforce SDK pod installed (Cocoapods DemoKO.zip)
Also, check the following screenshot:
![snapshot](https://user-images.githubusercontent.com/20855201/39295371-86af95f4-493e-11e8-83bf-aa4685add99e.png)
[Cocoapods DemoKO.zip](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/1950370/Cocoapods.DemoKO.zip)
[Cocoapods DemoOK.zip](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/1950371/Cocoapods.DemoOK.zip)

**Comment by bhariharan** [comment]
A known issue exists with `Cocoapods 1.5.0` and `SQLCipher`. Until that's resolved, we don't support `Cocoapods 1.5.0`. I'll leave this issue open for tracking purposes and will post back here when the issue is resolved.

**Comment by JimBTek** [comment]
i was able to build fine with pod version 1.5.0 and run the Account Editor Hybrid Sample just fine.

**Comment by wmathurin** [comment]
Cocoapod 1.5.0 uses modular (stricter) header search paths (see https://github.com/CocoaPods/CocoaPods/pull/7412). 

To get the old behavior, make the following change to your `Podfile`
Replace
```ruby
use_frameworks!
```
with
```ruby
use_frameworks!(false)
```

**Comment by jayuso** [comment]
Hello, I have a similar issue trying to integrate the ServiceSDK using cocoapods 1.4.0

The error I get is: Invalid Signature. Code object is not signed at all. The file at path [MyAXA_HK.app/Frameworks/ServiceCore.framework/prepare-framework] is not properly signed. 

Using ServiceSDK (212.0.2)

Can someone help me?

thanks
Javier

**Comment by bhariharan** [comment]
@jayuso This is not the right forum for ServiceSDK issues. Please post on their GitHub forum.

**Comment by urthakkar** [comment]
Here is link to ServiceSDK repo where you can post - https://github.com/forcedotcom/ServiceSDK-iOS/issues

**Comment by DanFerro** [comment]
@bhariharan is there an issue we call follow for SQLCipher?

**Comment by wmathurin** [comment]
There has been issues with SQLCipher since XCode 9.
They published a "fix" here: https://discuss.zetetic.net/t/important-advisory-sqlcipher-with-xcode-9-and-new-sdks/2371
Unfortunately, it no longer works with Cocoapod 1.5.

**Comment by wmathurin** [comment]
FMDB finally fixed the issue in version (2.7.5) see [here](https://github.com/ccgus/fmdb/pull/672), this [workaround](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/169/) will no longer be needed in Mobile SDK. Also Cocoapod 1.5 or 1.6 will work fine in Mobile SDK 7.0.

**Comment by FabrizioSposetti-U** [comment]
> Hello, I have a similar issue trying to integrate the ServiceSDK using cocoapods 1.4.0
> 
> The error I get is: Invalid Signature. Code object is not signed at all. The file at path [MyAXA_HK.app/Frameworks/ServiceCore.framework/prepare-framework] is not properly signed.
> 
> Using ServiceSDK (212.0.2)
> 
> Can someone help me?
> 
> thanks
> Javier

I know that is not the correct place. But, Did you find an answer to this problem? Becase I have the same one.

**Comment by ivasilev-pe** [comment]
@FabrizioSposetti-U  for me what helped is switching from CocoaPods to SP version of the library
