### ISSUE TITLE
Unable to build iOS native app with Xcode 9.3 and Salesforce sdk 6.1

### ISSUE THREAD

**Issue by samikshatoshniwal** [forcedotcom/SalesforceMobileSDK-iOS#2512]
Please fill out the following details:

1. Version of Mobile SDK Used:  Salesforce Native Swift SDK 6.1

2. Issue found in Native App or Hybrid App:  Native iOS swift app
    FMDatabase class do not compile with error - 
           - Implicit declaration of function 'sqlite3_rekey' is invalid in C99
           - 'sqlite3_reset' declared here

3. OS Version: Mac OS High Sierra 10.13.4
4. Device: N/A

5. Steps to reproduce: 
          - Download the Node.js installer from www.nodejs.org. 
          - Go to https://git-scm.com/ to download and install the latest Git package for your system.
          - Run `sudo npm install -g forceios` in terminal
          - Run `forceios create` in terminal
          - Open the created projected and press ⌘+B

6. Actual behavior: Compile time error

7. Expected Behavior: It should build successfully

8. Error Log: N/A

I've updated my system and xcode and then I ran into this issue; to be sure I upgraded salesforce sdk to 6.1 too but it didn't help me out. I've a native swift application with salesforce sdk 5.x in app store and I've to provide a new release with bug fixes in my app as soon as possible. But I am unable to proceed as I can't build my project due to this error. Please provide me a solution for this issue.

**Comment by anilabsinc-ajay** [comment]
Please check your pod version, If it is 1.5.0 than downgrade it to 1.4.0 and than run the pod install command. it will compile successsfully

**Comment by wmathurin** [comment]
Cocoapod 1.5.0 uses modular (stricter) header search paths (see https://github.com/CocoaPods/CocoaPods/pull/7412). 

To get the old behavior, make the following change to your `Podfile`
Replace
```ruby
use_frameworks!
```
with
```ruby
use_frameworks!(false)
```

**Comment by samikshatoshniwal** [comment]
Thanks, downgrading to `Cocoapods 1.4.0` resolved my issue.

**Comment by anilabsinc-ajay** [comment]
@bhariharan `Cocoapods 1.5.2` is now available for use, is there is any update when you are going to support the newer version of `Cocoapods`

**Comment by wmathurin** [comment]
The problem is not really with Mobile SDK but with FMDB and/or SQLCipher.
It's started with XCode 9.
SQLCipher blog posted a "work around" (https://discuss.zetetic.net/t/important-advisory-sqlcipher-with-xcode-9-and-new-sdks/2371) which we are using in our template. Unfortunately, it no longer works with cocoapod 1.5.
We are waiting for them to come up with a fix. As a last resort, we might fork FMDB or SQLCipher and try to fix the issue there.
