### ISSUE TITLE
Push notification issues

### ISSUE THREAD

**Issue by ankitaporwal** [forcedotcom/SalesforceMobileSDK-iOS#2520]
Please fill out the following details:

1. Version of Mobile SDK Used:  6.1
2. Issue found in Native App or Hybrid App: Native swift app
3. OS Version: 11
4. Device: All 
5. Steps to reproduce: Login with one user, logout and login with another user, push notification of both users will be received to current user. 
6. Actual behavior: push notification of both users will be received to current user. 
7. Expected Behavior: Push notification of current user should be received only in device and not the one who has already logged out
8. Error Log: Nil

I am on iOS sdk version 6.1 and using swift sdk. There is some issue i found with logout and deregister method i.e the user is deleted on logout and then deregister api is called which doesn't find any user and hence the token remains valid after logout as well. 
There are some more things i've noticed with push notifications - 

Push Notification Findings

1. Login for the first time
    1. Method to register user is called on launch. since the user isn’t signed in the deice doesn’t registers with any user.
    2. After login Salesforce SDK automatically calls the register device for user after around 10-15 mins. So if user is supped to get a push notification within this timeframe then it doesn’t come. 
2. Salesforce doesn’t guarantee the delivery of each notification
    1. Could you please provide me scenarios when the push notification is not guaranteed. I found that i receive some notification and some not although are sent from salesforce end but the connection is broken somehow and device doesn’t receive any push notifications. 
    2. : http://resources.docs.salesforce.com/212/9/en-us/sfdc/pdf/salesforce_mobile_push_notifications_implementation.pdf.
3. User needs to relaunch the app to get notifications after a certain time period to get notification as SDK automatically deregisters the device: http://resources.docs.salesforce.com/212/9/en-us/sfdc/pdf/salesforce_mobile_push_notifications_implementation.pdf
4. For User receiving notifications for both customer and vendor
    1. If we delete app without logout and then reinstall it, the device token isn’t cleared from the salesforce user list. Hence the notification is received on other devices also.
    2. If we logout from the app -> SDK deletes the user first and then call the API for unregisterForSalesforceNotification -> thus the call always fail and the deice token is never deleted for the user

Alongwith this if I delete app and install it and perform the same 3 times then I received three same push notifications in device. If a new token is registered for a device then older token should be cleared from salesforce. I can see multiple token in salesforce for same user for same device. 

My app is already on app store and I am waiting for this fix since long time. I tried contacting on community too but there my post has been disabled for some reason that I can't comment on it somehow. 

Looking forward for your response on this. 

Thanks,
AP

**Comment by wmathurin** [comment]
Fixed here: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2445
