### ISSUE TITLE
usersyncs.json SyncUp attributes.type is null

### ISSUE THREAD

**Issue by fitzglitz** [forcedotcom/SalesforceMobileSDK-iOS#2542]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 11.4
4. Device: All
5. Steps to reproduce: Using usersyncs.json file to define the process for syncDown and SyncUp. 
```javascript
              "syncName": "syncDownCallReports",
              "syncType": "syncDown",
              "soupName": "ib_callreports",
              "target": {"type":"soql", "query":"SELECT Id, Name, Company__c, Company__r.Name, Originator__c, Originator__r.Name, CallReport_Subject__c, Interaction_Type__c, GB__c, M_A__c, Equity__c, DCM__c, Credit__c, FICD__c, Cash_Management__c, Private_Banking__c, Asset_Management__c, Other__c, General__c, Formal_Pitch_Report__c, Call_Pitch_Date__c, Call_Notes__c, Published__c, Draft__c, Memo_To_File__c, saveandsend__c, Directors_Initiative__c, Private_Capital_Group__c, CreatedDate, CreatedBy.Name, LastModifiedDate, LastModifiedBy.Name FROM IB_CCP_Call_Report__c"},
              "options": {"mergeMode":"OVERWRITE"}
              },
              {
              "syncName": "syncUpCallReports",
              "syncType": "syncUp",
              "soupName": "ib_callreports",
              "target": {"sObjectType":"IB_CCP_Call_Report__c", "createFieldlist":["Name", "CallReport_Subject__c"]},
              "options": {"fieldlist":["Id", "Name", "CallReport_Subject__c"], "mergeMode":"OVERWRITE"}
              }
```

6. Actual behavior: SyncDown works fine, but SyncUp is failing due to sObject type is not being set us url used to put to Salesforce API.
7. Expected Behavior: SyncUp is expected to work.
8. Error Log:
```
2018-06-07 10:04:13:077 CallReportsSimulation[62439:9204980] sendRequestWithSmartSyncUserAgent:request:<SFRestRequest 0x6040002ca800 
endpoint: /services/data 
method: PATCH 
path: /v42.0/sobjects/(null)/a3Z0v000000179oEAA 
queryParams: [] 
> 
2018-06-07 10:04:13.079034-0700 CallReportsSimulation[62439:9204980]         NET    NSURLS        NSURLSessionConfiguration:backgroundSessionConfigurationWithIdentifier:: - use of backgroundSession is disabled
2018-06-07 10:04:13.253029-0700 CallReportsSimulation[62439:9202026]   0x7f916380a600 NET    HTTP   a0009       http response code:404 Not Found, curl code:0
2018-06-07 10:04:13.253297-0700 CallReportsSimulation[62439:9202026] UTIL::MBD::SerialExecutor::enqueueMsg count=1
2018-06-07 10:04:13:254 CallReportsSimulation[62439:9204979] sendRequestWithSmartSyncUserAgent:error:404:https://cibcwbcrm--devpartial.cs66.my.salesforce.com/services/data/v42.0/sobjects/(null)/a3Z0v000000179oEAA
2018-06-07 10:04:13:254 CallReportsSimulation[62439:9204979] sendRequestWithSmartSyncUserAgent:request:<SFRestRequest 0x6000002cfea0 
endpoint: /services/data 
method: POST 
path: /v42.0/sobjects/(null) 
queryParams: [] 
```

**Comment by wmathurin** [comment]
Make sure the records you sync up have an attributes field with the sobject type.
Like we do in our sample app [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/native/SampleApps/SmartSyncExplorer/SmartSyncExplorerCommon/SObjectData.m#L45).

```json
{
   "Id": "xxx",
   "Name": "yyy",
   "attributes": {
       "type": "IB_CCP_Call_Report__c"
   }
}
```

**Comment by davidfekke** [comment]
Hey Wolfgang, Can you open this one back up?

Your example works fine if you manually create a Spec file, but fitzglitz is using a usersyncs.json file to define the sync model. Does this mean we can't use the usersyncs.json file to 'syncUp' to Salesforce. There does not appear to be anyway to add "attributes.type" to the 'syncUp' syncType.

**Comment by wmathurin** [comment]
The config file takes care of defining the sync down or sync up.

What I described above applies to the actual records you save to SmartStore that you want synced up.
If you sync down a record, it will have the attributes field already. 
However, if you create a record offline, you need to provide that field yourself. Otherwise the sync engine won't know the sobject type of the record and will not be able to compute the correct URI when doing the REST call (as you noted above).

**Comment by davidfekke** [comment]
Wolfgang,

Is there an example on github of the usersyncs.json configured to sync down and sync up using the attributes.type? In an app I am building right now, we are not able to sync up. I can see that the attributes.type is being stored in the smartstore, but it is not syncing up. Maybe I am not defining the createFieldlist or the fieldlist correctly to include the attributes.type.

**Comment by wmathurin** [comment]
Look at the SmartSyncExplorer in the SalesforceMobileSDK workspace (in forcedotcom/SalesforceMobileSDK-iOS). It uses config files to setup its store and syncs. But it also make sure to add the attributes field to record.

**Comment by davidfekke** [comment]
I think we found the issue. When we were doing our updates on the object in the SmartStore, we were recreating the object from scratch instead of making a copy of the original object and just modifying the fields that needed to be modified. We also were not setting the `__local__` field on the object to "true".
