### ISSUE TITLE
Switch user method fails to switch the user  when the id’s of users are same (Case Insensitive)

### ISSUE THREAD

**Issue by nzsrini** [forcedotcom/SalesforceMobileSDK-iOS#2544]
Version of Mobile SDK Used: 6.1.0

Issue found in Native App or Hybrid App: Native iOS app
OS Version: 11.3.0
Device: iPad

Assume we have userid's from salesforce which 15 digit number( Case senstive not same).
005300000040EVc
005300000040EvC

(We have this case scenario).
005300000040EVc: UserA :user_id
005300000040EvC: UserB:user_id

As the users are from the same organization. The SDK below code returns true for the above condition even though both users are different.

if ([self.currentUser.accountIdentity isEqual:newCurrentUser.accountIdentity]) {
[SFSDKCoreLogger w:[self class] format:@"%@ new user identity is the same as the current user. No action taken.", NSStringFromSelector(_cmd)];

SFUserAccountIdentity.m : compares ca

BOOL userIdsEqual = [objectToCompare.userId isEqualToEntityId:self.userId];
BOOL orgIdsEqual = [objectToCompare.orgId isEqualToEntityId:self.orgId];
return userIdsEqual && orgIdsEqual;

==== isEqultoEntitiyId isn't comparing case sensitive so it is returning it as same user
code in NSString + SFAdditions.mp
if ([self caseInsensitiveCompare:entityId] == NSOrderedSame) return YES; /

Please can you look into it .

**Comment by nzsrini** [comment]
any update on this Please, we need to fix the issue pretty urgently

**Comment by trooper2013** [comment]
@nzsrini the 15 digit User Id's are case sensitive and cannot be compared as you suggest. You should look into why the case of the identifier has changed.

**Comment by nzsrini** [comment]
@trooper2013  Hi Rao,

What we are saying is the SDK class (SFUserAccountManager.m) --switchToUser is comparing with 15 digit userid rather than 18 digit and not switching the USer, And logging the below message.
    [SFSDKCoreLogger w:[self class] format:@"%@ new user identity is the same as the current user.  No action taken.", NSStringFromSelector(_cmd)];
====== Function=========================
(void)switchToUser:(SFUserAccount *)newCurrentUser {
    if ([self.currentUser.accountIdentity isEqual:newCurrentUser.accountIdentity]) {
        [SFSDKCoreLogger w:[self class] format:@"%@ new user identity is the same as the current user.  No action taken.", NSStringFromSelector(_cmd)];
=====

Please can you look into it.

**Comment by trooper2013** [comment]
@nzsrini  I misread. Im marking this as a bug. Look for a PR soon that fixes the above issue.

**Comment by wmathurin** [comment]
The fix is here: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2556
It will be in our next release (6.2).
If you don't want to upgrade or wait for the release, simply cherry pick the change.
Thanks for catching this bug.

**Comment by nzsrini** [comment]
Thanks for fixing, 
But still having the issue with switchToUser method. Please check the flow as detailed below.

Case Scenario 
005300000040EVc: UserA :user_id
005300000040EvC: UserB:user_id


- (void)switchToUser:(SFUserAccount *)newCurrentUser {
    if (**[self.currentUser.accountIdentity isEqual:newCurrentUser.accountIdentity**]) {
        ** FOr the above Case scenario, always satisfies this if condition and not switching the users.**

> [SFSDKCoreLogger w:[self class] format:@"%@ new user identity is the same as the current user.  No action taken.", NSStringFromSelector(_cmd)];

**
}

============ Please check the flow=========== 
### Step1)  isEqual method of  SFUserAccountIdentity class is invoked.

Still, it is comparing 15 char digit id  in SFUserAccountIdentity{
- (BOOL)isEqual:(id)object
{
    if (object == nil)
        return NO;
    if (self == object)
        return YES;
    
    if (![object isKindOfClass:[SFUserAccountIdentity class]])
        return NO;
    
    SFUserAccountIdentity objectToCompare = (SFUserAccountIdentity )object;
    **///  check the flow here  data : self.userId=== 15 digit////**
    **BOOL userIdsEqual = [objectToCompare.userId isEqualToEntityId:self.userId];**

    BOOL orgIdsEqual = [objectToCompare.orgId isEqualToEntityId:self.orgId];
    return userIdsEqual && orgIdsEqual;
}
}

**Step2: Below code is invoked from the isEqual method in SFUserAccountIdentity and it is returning as same users even they are different users.**

- (BOOL)isEqualToEntityId:(NSString*)entityId {
/// failing the condition here : when you call from switch user method///
    **if ([self caseInsensitiveCompare:entityId] == NSOrderedSame) return YES;** // for entityId like `me`
    
    if (![entityId length]) return NO;
    if (!IsValidEntityId(self) || !IsValidEntityId(entityId)) return NO;
    
    NSString *id18self = ([self length] == SFEntityIdLength18) ? self : [self entityId18];
    NSString *id18other = ([entityId length] == SFEntityIdLength18) ? entityId : [entityId entityId18];
    if (nil == id18other) return NO; // because caseInsensitiveCompare doesn't allow a nil argument
    return ([id18self caseInsensitiveCompare:id18other] == NSOrderedSame);
}

**Comment by wmathurin** [comment]
Did you cherry pick my change? It doesn’t look like it from your comment.

**Comment by nzsrini** [comment]
Thanks for the fix. It's fixed.
