### ISSUE TITLE
Touch ID Problem

### ISSUE THREAD

**Issue by dancuconati** [forcedotcom/SalesforceMobileSDK-iOS#2547]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.1 
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: iOS 11

Hi,

I am having an issue implementing touchID and have a few questions.

We have a hybrid app that a user can choose to use TouchID with. If they don't enable touchID, when the user foregrounds the app from background, no passkey dialog is shown. If the user enables touchID, then every time the app is foregrounded from background, the touchID dialog is shown. However, if touchID is then disabled again, and the app is brought to the foreground from the background, the passkey dialog is still shown. We believe it is because of the keychain access.

In the SFKeychainItemWrapper.m class, there is an init function that sets the security of the keychain access. Is there any way or workaround to modify this to to be changed to a less restrictive option?

Thanks,
Dan

`SFKeychainItemWrapper.m`
```
(void)initialize {
if (self == [SFKeychainItemWrapper class]) {
sKeychainItemWrapperMap = [[NSMutableDictionary alloc] init];

  /// Initialize using the most restricted access
  sKeychainAccessibleAttribute = kSecAttrAccessibleWhenUnlockedThisDeviceOnly;
}
}
```

**Comment by wmathurin** [comment]
When you say enabling/disabling touch id, do you mean the connected app setting ?

**Comment by dancuconati** [comment]
We aren't using the SalesforceSDK touchID functionality because that requires a user to input a passcode. We are using a Cordova plugin to turn on & off the touch ID functionality. However, after turned off, when SalesforceSDK goes to access the keychain, it requires a passcode, where it didn't previously.

Basically, the keychain access that I'm referencing is dealing with authentication and the authentication token, etc.

**Comment by wmathurin** [comment]
What is the touch id plugin you are using?
Also when you say turn off touch id, do you mean make a call to your plugin so that touch id is no longer required when opening/foregrounding the app or disable touch id on the device?

**Comment by wmathurin** [comment]
The code above means that the key chain entries won't be accessible when the device is locked.
It should not trigger any touch id to be shown. I believe the plugin your are using is doing that.
Could you check with them (post an issue on their github repo)?
Please re-open, if you think it is truly a mobile sdk bug.
