### ISSUE TITLE
User-Agent Not Includes UID On First Login

### ISSUE THREAD

**Issue by Yossud** [forcedotcom/SalesforceMobileSDK-iOS#2557]
1. Version of Mobile SDK Used: 6.1
2. Issue found in Native App or Hybrid App: native
3. OS Version: 11.3
4. Device: Simulator
5. Steps to reproduce:
       a. Create custom community login page (VF Page).
       b. Show User-Agent header.
6. Actual behavior: The User-Agent not contains uid of the app
7. Expected Behavior: User-Agent included uid pf the app.
(If I'm logging out from the app with code. `SFUserAccountManager.sharedInstance().logout()` the uid exist )
8. Error Log:

**Comment by wmathurin** [comment]
Thanks for reporting this issue. We will take a look.

**Comment by wmathurin** [comment]
A fix will be in a the next release. See https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2563
