### ISSUE TITLE
PIN Protect On Community Login

### ISSUE THREAD

**Issue by Yossud** [forcedotcom/SalesforceMobileSDK-iOS#2559]
1. Version of Mobile SDK Used: 6.1
2. Issue found in Native App.
3. OS Version: 11.3
4. Device: Simulator
5. Steps to reproduce:
       a. Create custom community login page (VF Page).
       b. Check the PIN protect on connected app.
6. Actual behavior: After login page there is not passcode display.
7. Expected Behavior: After login page showing the passcode screen.
8. Error Log:
In my research to found the problem I came to the conclusion that the problem in `dictRepresentation` property in `SFIdentityData`.
When I logged in with System Admin user I can see mobile policy attribute that includes PIN length and screen lock time.
But with Community user I can't see the mobile policy attribute at all.

Maybe it's on purpose but It's seems to me like a bug.

Thanks.

**Comment by bhariharan** [comment]
@Yossud When you login as community user, is your `loginURL` configured to the custom community login page that you created or the standard production `loginURL`? When you say the mobile policy attribute is missing, are you referring to what's returned from the service or locally in the SDK?

**Comment by wmathurin** [comment]
Are you logging into the same org with your community user and your system admin?
Is the connected app installed in that org?

**Comment by bhariharan** [comment]
@Yossud 

> Yes. but with different login url.

Could you try logging in with the system admin user against the community login URL as well? It's not surprising that logging into different login URLs yield different results (one will retrieve the org's settings and the other will retrieve the community's settings).

**Comment by Yossud** [comment]
@bhariharan 
You're right. When I logged in with system admin to community login url I don't see the mobile policy and PIN protect flow not happening. 
Is it a bug or is it intended?

**Comment by bhariharan** [comment]
@Yossud Communities have their own settings. My guess is you'll need to configure the policies within the community somehow. Check out our server side documentation on how to do this. Either way, this is outside the control of the client.
