### ISSUE TITLE
Error -1002 using standard method for SOQL request

### ISSUE THREAD

**Issue by Codinger386** [forcedotcom/SalesforceMobileSDK-iOS#2569]
1. Version of Mobile SDK Used: 6.1.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 11
4. Device: iPhone/ iPad
5. Steps to reproduce: 
First, authenticate using SalesforceSDK, then try to make a SOQL request using 
`SFRestAPI.sharedInstance().performSOQLQuery(...)`
using any query.

6. Actual behavior: Error

7. Expected Behavior: Get a valid result

8. Error Log:

From SDK: 
`REST request failed with error: Error Code: -1002, Description: unsupported URL, URL: (null)`

Printed error:
`Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSUnderlyingError=0x60c000643d50 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}}`

Comment:
The method returns a SFRequest that has no baseURL set. Setting it after the call to `performSOQLQuery`  makes no sense, since the request has already been sent. Looking into
`SFRestAPI.sharedInstance().performSOQLQuery(...).user.apiURL`
returns the correct baseURL. I would have expected that it is implicitely set in the request by the SDK. Maybe there is some important configuration missing?

**Comment by bhariharan** [comment]
@Codinger386 Thanks for your feedback. `unsupported URL, URL: (null)` in the error message is the final URL computed based on the path segments. We will look into improving that log line.
