### ISSUE TITLE
Upgrading app causes existing data to become hidden (iOS / React)

### ISSUE THREAD

**Issue by JimBTek** [forcedotcom/SalesforceMobileSDK-iOS#2601]
It might be a problem with our code, but documenting it here in case you guys would see a cause with the parent-child sync targets. 

1. Version of Mobile SDK Used: 
"SalesforceMobileSDK-iOS": "https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#v6.1.0"

1. Issue found in Native App or Hybrid App: React Native
2. OS Version:  11.2
3. Device: iPad Air
4. Steps to reproduce:

this is using the storemgr for offline access

- sync Down from Salesforce a parent object and a child object (master Detail, there are actually 2 child objects on the same parent) 
- change some JS code
- create a new .IPA file and push to device
- re-open app on device
- user is still logged in, new features are present
- device does sync down

result: no missing records, except child object, all child records that were never edited on the device are hidden/missing.  

Forcing a new sync down does not pull them down because the app believes they are already on the device, but they do not render. 

6. Actual behavior:

pre-existing child records in master-detail object fail to be found and rendered after .IPA update pushed to users. The problem is fully fixed, by deleting the app, then installing the new version, vs. updating the app.

7. Expected Behavior:

be able to push an updated version of the app without data disappearing 

8. Error Log: no errors encountered

**Comment by wmathurin** [comment]
I don't understand the "hidden/missing" part. Were the records in the database before the app update and gone after?

To see the content of the database, use the smartstore inspector from the developement menu. For more information, see: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/tools_dev_support.htm

**Comment by JimBTek** [comment]
Hey @wmathurin  

Yeah, so on version say 2.0.1 of our app, user logs in and downloads a bunch of records.  Everything looks good.  We push a new .IPA for 2.0.2 over the existing app. Some child records end up not rendering in the UI anymore, but when forcing a differential sync down (we have a button) the sync manager sees no new records to sync down.  So it seems like they get lost in the soup somehow.  We have only been able to reproduce it on physical hardware when deploying an .IPA over an existing copy, so we can't use the Inspector to query the soup.

Sorry for being vague. We are looking at using Sentry or MS App Center to get both Obj-C and React Native crash logs and trying to determine ways to expose sync failures on hardware, by either logging them to the device in a log file, or reporting them to App Center or another tool.  Sentry and App Center both seem to have some conflicts with the Salesforce SDK however, which is another issue we are investigating.

**Comment by wmathurin** [comment]
You can enable the development menu in a release build by adding the following line in your AppDelegate.m.
```objective-c
[SalesforceSDKManager sharedManager].isDevSupportEnabled = YES;
```
You can bring up the development menu on a physical device by shaking it.

If that's an option, could you try the above to inspect the database before and after the update?

**Comment by JimBTek** [comment]
@wmathurin  OK will do. we have a new release build today or tomorrow.

**Comment by wmathurin** [comment]
We can't help without more info. Closing for now.

**Comment by JimBTek** [comment]
@wmathurin sorry for the lack of update. we have been working on other issues and I will try and test this more on our next release.
