### ISSUE TITLE
Crash when the user subscribes to haveValidSession changes (KVO) on SFUserAccountManager

### ISSUE THREAD

**Issue by jakub-niscior** [forcedotcom/SalesforceMobileSDK-iOS#2603]
1. Version of Mobile SDK Used: 6.2
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 11.4 (doesn't matter)
4. Device: iPhone X (doesn't matter)
5. Steps to reproduce:

Subscribe to notifications about changes (KVO) to the property haveValidSession on SFUserAccountManager.

`[[SFUserAccountManager sharedInstance] addObserver:self forKeyPath:@"haveValidSession" options:NSKeyValueObservingOptionNew | NSKeyValueObservingOptionOld context:nil];`

Login using loginWithCompletion on SFUserAccountManager.

6. Actual behavior: Crash
7. Expected Behavior: No crash, I guess it shouldn't work either because there is no such property on the SFUserAccountManager. This was discovered when migrating from 5.3.1 and changing the references to SFAuthenticationManager to SFUserAccountManager. (due to deprecation)

The crash is caused due to copy pasted code inside SFUserAccountManager that should absolutely not be there. Please see the class, specifically the lines

```
        [self willChangeValueForKey:@"haveValidSession"];
        [self didChangeValueForKey:@"haveValidSession"];
```

In the `finalizeAuthCompletion:` method. The SFUserAccountManager does not have such a property yet attempts to notify about a change which causes a crash if the user subscribes to the changes using KVO. 

Solution is to either add such a property or better: remove attempts to notify about changes to the property which does not exist.

8. Error Log: 
```
2018-07-24 13:22:41.645673+0200 CARFAX[1586:1206506] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<SFUserAccountManager 0x1d012d840> valueForUndefinedKey:]: this class is not key value coding-compliant for the key haveValidSession.'
*** First throw call stack:
(0x182aa2d8c 0x181c5c5ec 0x182aa29f0 0x1834aa2b0 0x1833de964 0x183430b34 0x183430710 0x1834b5b50 0x10315bf34 0x10315b470 0x103142018 0x10313f0bc 0x10315b34c 0x10315ade4 0x10311b59c 0x1030ab0c4 0x103d45260 0x103d45220 0x103d49db0 0x182a4b070 0x182a48bc8 0x182968da8 0x18494b020 0x18c94978c 0x1023dc248 0x1823f9fc0)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by wmathurin** [comment]
This is fixed in dev and will be part of our next release. (see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2596).
