### ISSUE TITLE
Sync Down Process getting stopped when application is in background.

### ISSUE THREAD

**Issue by piyushprabhakar** [forcedotcom/SalesforceMobileSDK-iOS#2608]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.3
2. Issue found in Native App or Hybrid App: Native iOS App
3. OS Version: 11.4
4. Device: iPhone 6 and Higher model 
5. Steps to reproduce: Start sync down process and put application in background
6. Actual behavior: I have started the sync down process and i have put application in background mode after this the downloading record got stopped and it again resumed when i put the application in the foreground mode. Is this Expected behaviour? I am doing sync down operation on background thread.
7. Expected Behavior: Download should continue even if the app is in background
8. Error Log:

**Comment by bhariharan** [comment]
@piyushprabhakar Long running background operations on `iOS` require the app to register itself as a special type of application. A standard sync operation using `SmartSync` doesn't run on the background out of the box. If you want to run a sync operation on the background, follow the steps in [this article](https://developer.apple.com/documentation/uikit/core_app/managing_your_app_s_life_cycle/preparing_your_app_to_run_in_the_background/extending_your_app_s_background_execution_time) to kick it off at the right time. There might be other steps required to get it working.
