### ISSUE TITLE
Mobile sdk ios issue

### ISSUE THREAD

**Issue by archita6** [forcedotcom/SalesforceMobileSDK-iOS#2609]
Please fill out the following details:

1. Version of Mobile SDK Used:  Mobile SDK 6.2
2. Issue found in Native App or Hybrid App: Hybrid
3. OS Version: ios 11
4. Device: iPhone 7s Plus
5. Steps to reproduce:
  a) Create a hybrid App.
   b) Install the Cordova Camera Plugin using the following command 
    cordova plugin add cordova-plugin-camera
    cordova plugin remove com.salesforce
     cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin --force
  c) App code when you click a section the phone camera should be accessible to take picture.
   d) When I try to access the camera getting error logged un the console.
Camera.getPicture: source type 1 not available. 
6. Actual behavior: 
7. Expected Behavior: The Camera should be accessible from the app.
8. Error Log:
Camera.getPicture: source type 1 not available.

The same application works well in android.

**Comment by bhariharan** [comment]
@archita6 This has nothing to do with the Mobile SDK. Please file an issue on `cordova-plugin-camera`.
