### ISSUE TITLE
Smartsync 6.2.0 -(SFSyncState) sync.hasFailed() always returns false, Even if sync error exists

### ISSUE THREAD

**Issue by SunilCodecraft123** [forcedotcom/SalesforceMobileSDK-iOS#2612]
**Version of Mobile SDK Used**: 6.2.0
  
 **Issue found in Native App or Hybrid App: Native App** - Swift
  
 **OS Version**: 11.4

 **Device**: All

**Issue**:-  
**syncMgr.syncUp will return - (sync.hasFailed() = false and sync.isDone() = true) even if there is a sync error**

But we can clearly see the sync error in SFSDKSmartSyncLogger and console

**Steps to reproduce**: 

**Create one sync error - it will Display following Description in SFSDKSmartSyncLogger and in console**

Example 

syncUpOneRecord:{
    "Activity__c" = test;
    "Business_Unit__c" = a07c000000AsEWTAA3;
    "Data_Source_Version__c" = 000;
    "Date__c" = "2018-08-03";
    "External_Id__c" = "005c0000003Hg4v_176449F4-19E7-4823-8FAF-BB19A841EF89_1533295125_78803982b75dd1082e626e91bebbbb65";
    "Foreman__c" = "<null>";
    Id = "<null>";
    "Job_Number__c" = a1Hc0000001UGM2EAO;
    "Location__c" = "<null>";
    Name = "<null>";
    RecordTypeId = "<null>";
    "Site_Location__c" = test;
    "Source__c" = Test;
    "Status__c" = "Un-Submitted";
    "__last_error__" = "Error Domain=(we removed it) Code=400 \"(null)\" UserInfo={error=(\n        {\n        errorCode = \"INVALID_CROSS_REFERENCE_KEY\";\n        fields =         (\n            RecordTypeId\n        );\n        message = \"Record Type ID: this ID value isn't valid for the user: \";\n    }\n)}";
    "__local__" = 1;
    "__locally_created__" = 1;
    "_soupEntryId" = 13;
    "_soupLastModifiedDate" = 1533296737585;
    attributes =     {
        type = "Daily_Job_Record__c";
    };
}

But syncing fails its will return but response status as

sync.isDone() = true
sync.hasFailed() = false 

**Code used to Sync records**
--------------------------------------
  func updateRemoteData(_ completionBlock: @escaping SFSyncSyncManagerUpdateBlock) {
    guard let syncMgr = self.syncMgr else { return }
    let updateBlock: SmartSync.SFSyncSyncManagerUpdateBlock = {
      [weak self] (sync) -> Void in
      guard let _ = self else {
        return
      }
        if sync.isDone() || sync.hasFailed() {
          completionBlock(sync)
        }
    }

    let syncOptions = SFSyncOptions.newSyncOptions(forSyncUp: self.dataSpec.uploadFieldNames, mergeMode: SFSyncStateMergeMode.leaveIfChanged)
    syncMgr.syncUp(with: syncOptions, soupName: self.dataSpec.soupName, update: updateBlock)
  }

**Even we used promisekit then also same result**

   func updateRemoteData(_ completionBlock: @escaping SFSyncComplition) {
       guard let syncMgr = self.syncMgr else {
         completionBlock(nil,nil)
         return
       }
       let syncOptions = SFSyncOptions.newSyncOptions(forSyncUp: self.dataSpec.uploadFieldNames, mergeMode: SFSyncStateMergeMode.leaveIfChanged)
       syncMgr.Promises.syncUp(options: syncOptions, soupName: self.dataSpec.soupName)
         .then { syncState -> Promise<Void> in
          completionBlock(syncState,nil)
           return Promise()
         }
         .catch { (error) in
          completionBlock(nil,error)
         }
     }

**But if we fetch and check the data from the local soup , in   "__last_error__"  field of local database we can clearly see the error**

**Comment by trooper2013** [comment]
@SunilCodecraft123 This problem should be fixed by PR #2528

**Comment by SunilCodecraft123** [comment]
@trooper2013  Thanks for the response. Got it.

But is there any way we can find 'sync error' in the  **syncMgr.syncUp** method completion block (SFSyncState),  instead of checking it in the SFSDKSmartSyncLogger or in local soup.

**Comment by wmathurin** [comment]
The sync operation is not marked as failed if some of the records fail to be save on the server.
It is only marked as failed if there are network failures (or the server is unavailable).
With https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2528, we are now capturing the reasons particular records could not be saved on the server.
After running the sync, you could run a SmartStore query to see if there are still "dirty" records (i.e. with `__local__` marked as true) and then look at their `__last_error__` field.
