### ISSUE TITLE
Syncing Related Records - App crashes when Syncup using SFParentChildrenSyncUpTarget

### ISSUE THREAD

**Issue by SunilS123** [forcedotcom/SalesforceMobileSDK-iOS#2615]
1. Version of Mobile SDK Used:  6.2.0
2. Issue found in Native App or Hybrid App: Native App- swift
3. OS Version: IOS 11.4
4. Device: All
5. Steps to reproduce: 

Create ParentChildrenSyncUpTarget and try to sync the parent and child soup records.

Senario:-

We have parent soup "AccounSoup" and child soup "ContactSoup"

Child soup "ContactSoup" has field called "AccountId"(In AccounSoup its sfid - Id) MasterDetail Relationship.

"AccounSoup"  (parent) soup syncup works fine, can see the records in sf database.  

but child soup "ContactSoup" crashes inside SF SDK while syncing.  

**Structure of the "SFParentChildrenSyncUpTarget" of child soup  (SFSDKLogger console log)**:-

 **Error Log:**

 *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000101c191e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x00000001012ae031 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000101c590bc _CFThrowFormattedException + 194
	3   CoreFoundation                      0x0000000101c4a796 -[__NSArrayM objectAtIndexedSubscript:] + 150
	4   SmartSync                           0x0000000100c27cf2 -[SFSyncTarget getFromLocalStore:soupName:storeId:] + 274
	5   SmartSync                           0x0000000100c19bad -[SFSmartSyncSyncManager syncUpOneEntry:recordIds:index:updateSync:failBlock:] + 493
	6   SmartSync                           0x0000000100c18810 -[SFSmartSyncSyncManager syncUp:updateSync:failSync:] + 480
	7   SmartSync                           0x0000000100c15ca5 __46-[SFSmartSyncSyncManager runSync:updateBlock:]_block_invoke.165 + 197
	8   libdispatch.dylib                   0x00000001067da7ab _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x00000001067db7ec _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x00000001067e3be5 _dispatch_queue_serial_drain + 1305
	11  libdispatch.dylib                   0x00000001067e44fa _dispatch_queue_invoke + 328
	12  libdispatch.dylib                   0x00000001067e0344 _dispatch_queue_override_invoke + 726
	13  libdispatch.dylib                   0x00000001067e736c _dispatch_root_queue_drain + 664
	14  libdispatch.dylib                   0x00000001067e7076 _dispatch_worker_thread3 + 132
	15  libsystem_pthread.dylib             0x0000000106cff169 _pthread_wqthread + 1387
	16  libsystem_pthread.dylib             0x0000000106cfebe9 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Have you implemented syncing Related Records  logic in your demo apps?**

If its implemented could you provide more details on syncing Related Record (parent-child relationship) or an demo project link (we referred this documentation link - https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/entity_framework_sync_related.htm)

**Comment by wmathurin** [comment]
We have tests for every supported permutation: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SmartSync/SmartSyncTests/ParentChildrenSyncTests.m

Please have a look and let me know if it helps.

**Comment by wmathurin** [comment]
1. / 2. No. Parent children sync targets currently only supports dealing with a single relationship at a time.
3. Yes - but only for children of the same types, for the account-contact example, we can sync down/up an account with all its associated contacts. 
4. You should not use an external id field. Instead populate the id field on the parent record with some locally computed id (something like https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SmartSync/SmartSyncTests/SyncManagerTestCase.m#L114) , and make sure to use that same id in the foreign key field of the children. The sync operation will take care of replacing the local id with the server id in both the parent and children records. Not having any values in the Id field is what is causing the sync to fail.

**Comment by SunilS123** [comment]
@wmathurin  Thanks for details

But still we are getting issue and crash (parent id locally computed- **local_69711014** and parent id locally computed- **local_79686172**) 

Now created this way

**Example:-**

     AccountSoup (Not synced yet - Created in locally) {
      Id = local_69711014
      AccountName = xyzzy
     Descr : XYZ   
     ExternalId = Account001
     }

  ContactSoup (Not synced yet - Created in locally) {
      Id = local_79686172
      ContactName = A
     AccountId = local_69711014
     ExternalId = Contact001
     }

**For Above case we are getting this error**

**sendRequestWithSmartSyncUserAgent:response:{
    compositeResponse =     (
                {
            body =             (
                                {
                    errorCode = "NOT_FOUND";
                    message = "The requested resource does not exist";
                }
            );
            httpHeaders =             {
            };
            httpStatusCode = 404;
            referenceId = "local_69711014";
        },
                {
            body =             (
                                {
                    errorCode = "PROCESSING_HALTED";
                    message = "Invalid reference specified. No value for local_69711014.id found in local_69711014";
                }
            );
            httpHeaders =             {
            };
            httpStatusCode = 400;
            referenceId = "local_79686172";
        }
    );
}**

**And going through point 3, we have a query**
**Example:-**

Here **AccountSoup** is parent for **ContactSoup & ProfileSoup**

   1)  AccountSoup (Not synced yet - Created in locally) {
      Id = local_69711014
      AccountName = xyzzy
     Descr : XYZ   
     ExternalId = Account001
     }

 2)  ContactSoup (Not synced yet - Created in locally) {
      Id = local_79686172
      ContactName = A
     AccountId = local_69711014
     ExternalId = Contact001
     }

3) ProfileSoup (Not synced yet - Created in locally) {
     Id = local_79686185
      ProfileName = AC
     AccountId = local_69711014
     ExternalId = Profile001
 }

In this scenario while syncing Account & Contact soup in ParentChildrenSyncUp target, Account's id gets updated. 

Then how how it will Identify profilesoup as a child object.

**Comment by wmathurin** [comment]
Parent children sync only supports a pair of object types. Because you have three object types, you need to do some "manual" work:
- you need to query SmartStore to build maps from with soup entry id to account id before and after running the account-contacts sync up.
- from those maps, you should build a local account id to server id map.
- using that map you should fix the account id fields in the profile soup (using a method like https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SmartSync/SmartSync/Classes/Target/SFParentChildrenSyncUpTarget.m#L596).
- once that's done, you should be able to sync up the profiles.

**Comment by SunilS123** [comment]
@wmathurin Thank you for the response. Got the Scenario.

![screen shot 2018-08-10 at 6 24 51 pm](https://user-images.githubusercontent.com/17869039/43958944-b596779a-9cca-11e8-8e45-56cb08f07735.png)

would you let us know whether we can sync the soups marked in red(i.e AccountSoup, ContactSoup & subchild1) in a single operation or we have to make a parent - child relationship sync target 2 times(query SmartStore as mentioned above) ?

**Comment by wmathurin** [comment]
1. Not currently possible in one sync call.
2. Correct.
3. Maybe you could probably add a field on Account to capture the local id. Before sync, it would duplicate the value already in the Id field, and after a sync, it would allow you to build a map from local id to server id when fixing references in children records. That way it would work even if there is a crash.

**Comment by SunilS123** [comment]
@wmathurin  Can we run multiple (perentchild) syncdown operations simultaneously in above account soup example.

**Comment by wmathurin** [comment]
1. Don't include the extra fields in the fields to sync up. You don't need that field on the server.
2. Once you have fixed all the foreign key references, it shouldn't be a problem to run all the syncs at once.

**Comment by wmathurin** [comment]
I'm going to close an issue since the crashes were due to fields not being properly populated rather than a bug in the Mobile SDK.
To get further help syncing related records, I recommend you post your questions on our [G+ community](https://plus.google.com/communities/114225252149514546445).

**Comment by wmathurin** [comment]
Maybe you should look into creating a custom sync target for your use case.
It would take care of the entire tree at once using a composite request like we do [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SmartSync/SmartSync/Classes/Target/SFParentChildrenSyncUpTarget.m#L252).

Maybe one day we will enhance our related records sync support to go beyond just a parent and its children. We don't however have specific plans at this point.
