### ISSUE TITLE
Mobile Iron Conflict

### ISSUE THREAD

**Issue by TylerBranch** [forcedotcom/SalesforceMobileSDK-iOS#2618]
Please fill out the following details:

1. Version of Mobile SDK Used: 
4.1.2
 
2. Issue found in Native App or Hybrid App:

Native

3. OS Version:

11.4

4. Device:

iPad air

5. Steps to reproduce:

Use Mobile Iron MDM, an application using the SDK will require relogin every 24 hours or less.

6. Actual behavior

relogin every 24 hours or less.

7. Expected Behavior:

No relogin

8. Error Log:

**Comment by bhariharan** [comment]
We don't have any special behavior for MDM/EMM providers. Please reach out to `MobileIron` for compatibility issues.
