### ISSUE TITLE
Encryption key is regenerated due to launching of app again and again

### ISSUE THREAD

**Issue by sumitsanchit** [forcedotcom/SalesforceMobileSDK-iOS#2625]
Please fill out the following details:

1. Version of Mobile SDK Used: 4.3.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 11.3
4. Device: iPad
5. Steps to reproduce: Launch app multiple times
6. Actual behavior: Sometimes encryption key is regenrated due to which account details are not decrypted resulting in opening Login screen again and all unsaved data gets removed
7. Expected Behavior: Encryption key should never be regenerated unless user is relogin.
8. Error Log:

**Comment by brandonpage** [comment]
Hi @sumitsanchit,  version 4.3.1 is over two years old and does not even support iOS 11.  Please upgrade to the newest version of the Mobile SDK and let us know if the issue persists; we have likely already fixed it.  Thanks.
