### ISSUE TITLE
Blocking Window after Login or Cancel Auth Flow  

### ISSUE THREAD

**Issue by ios3** [forcedotcom/SalesforceMobileSDK-iOS#2627]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.2.0
2. Issue found in Native App or Hybrid App: Native Swift
3. OS Version: iOS 11.4
4. Device: iPhone SE, 8
5. Steps to reproduce: follow the below code
6. Actual behavior: Blocking app window after auth screen
7. Expected Behavior: After cancel or success i can able to use application
8. Error Log:

Code : 
SFSDKLogger.sharedInstance().logLevel = .error
        SalesforceSDKManager.shared().appConfig?.remoteAccessConsumerKey = "XXXXX"
        SalesforceSDKManager.shared().appConfig?.oauthRedirectURI = "https://login.salesforce.com/services/oauth2/success"
        SalesforceSDKManager.shared().appConfig?.oauthScopes = ["web","api"]
SFUserAccountManager.sharedInstance().loginViewControllerConfig.showSettingsIcon = false
SalesforceSDKManager.shared().launch()

**Comment by wmathurin** [comment]
Could you try with a oauthRedirectURI that doesn't use the https scheme?
For an example look at https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/master/iOSNativeSwiftTemplate/iOSNativeSwiftTemplate/AppDelegate.swift#L32

**Comment by wmathurin** [comment]
Closing since we never heard back when asking for more info.
