### ISSUE TITLE
Remember me not working

### ISSUE THREAD

**Issue by AvikImperial** [forcedotcom/SalesforceMobileSDK-iOS#2629]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.2.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 11.4
4. Device: iPad (5th Generation)
5. Steps to reproduce: 
Remember me is not working. Steps as follows : 
     1. Login keeping Remember Me checked
     2. on successful login close the application
     3. Remove the application from background
     4. Reopen the application, it is getting correct logged in user id but still if you try to continue it is taking to the login page again.
6. Expected behavior:
    1. Login keeping Remember Me checked
     2. on successful login close the application
     3. Remove the application from background
     4. Reopen the application, it should complete the login with saved user details and take you to application home page directly
8. Error Log:
[log.zip](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/2331345/log.zip)

**Comment by bhariharan** [comment]
@AvikImperial The `Remember Me` button isn't meant to function the way you describe it. It's supposed to remember the username. This works on a mobile browser. However, within the mobile container, we have to clear cookies between sessions for a clean authentication experience since we support a matrix of types of authentication. As a result, the username will not be saved within the mobile container once you log out. This is by design.

**Comment by AvikImperial** [comment]
Here is the error we are receiving while try to relogin after login first
time with remember-me checked in

{"error":"invalid_grant","error_description":"expired access/refresh token"}

The method we are using for login and relogin in both cases is -

 return [self.authManager loginWithCompletion:^(SFOAuthInfo *info,
SFUserAccount *userAccount){

            [SFUserAccountManager sharedInstance].currentUser = userAccount;



            if(completionBlock){

                completionBlock(info, userAccount);

            }

        } failure:failureBlock];

 So need to know if we are doing it right or something is missing?
Do we need to use any other method for re-login in case of remember me

**Comment by bhariharan** [comment]
@AvikImperial `Remember Me` is within the login webview. The native container has no knowledge of this checkbox. Use the APIs in `SFUserAccountManager` to perform user related functionality such as logging in, switching users, logging out, etc. I recommend generating an app using `forceios` and following the code patterns in the generated app for best practices.
