### ISSUE TITLE
CustomSyncUp Target is creating duplicate records

### ISSUE THREAD

**Issue by srinivasbillav** [forcedotcom/SalesforceMobileSDK-iOS#2632]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.2.0
2. Issue found in Native App or Hybrid App: Native- Swift
3. OS Version: 10.13.6
4. Device: 11.4 - Xcode 9.4
5. Steps to reproduce:

Insert a record to local soup and try to sync up using customsynctarget as mentioned below  which will create two record (with one record synced, another duplicate record (with sync error))

Insert 4 records to local table, after syncup completes , custom syncup target will create 8 records  

Use below code:
   
   -  create custom sync up target as below
![screen shot 2018-08-31 at 3 20 09 pm](https://user-images.githubusercontent.com/30919541/44906003-6ab43d80-ad31-11e8-8944-8dcd886e5aea.png)

Try to sync up using below code

 
      let syncOptions = SFSyncOptions.newSyncOptions(forSyncUp: self.dataSpec.uploadFieldNames, mergeMode: SFSyncStateMergeMode.leaveIfChanged)
      let syncTar = CustomSyncUpTarget(createFieldlist: self.dataSpec.createFieldNames, updateFieldlist: self.dataSpec.updatebleFieldNames)
      syncMgr.syncUp(with: syncTar, options: syncOptions, soupName: SObjectDataSpec.sObjectType(), update: updateBlock)

OR

 let syncOptions = SFSyncOptions.newSyncOptions(forSyncUp: self.dataSpec.uploadFieldNames, mergeMode: SFSyncStateMergeMode.leaveIfChanged)
      let syncTar = CustomSyncUpTarget(createFieldlist: self.dataSpec.createFieldNames, updateFieldlist: self.dataSpec.updatebleFieldNames)
      let syncState = SFSyncState.newSyncUp(with: syncOptions, target: syncTar, soupName: self.dataSpec.soupName, name: nil, store: self.store!)
      // SFSyncUpdateCallbackQueue in testcases
      var queue = SFSyncUpdateCallbackQueue()
      queue.runSync(syncState, syncManager: self.syncMgr!)

6. Actual behavior:  creates duplicate records , even tested with single record in local table

**Comment by SunilS123** [comment]
> Even if we call CustomSyncUpTarget more than once by mistake, it will create duplicate Records .
> if we cancel current CustomSyncUpTarget and recall it (for same), that will create duplicate records.

**Comment by trooper2013** [comment]
Closing since issue has been resolved. See #2643
