### ISSUE TITLE
Crash in SFRestAPI.m line 379 -[SFRestAPI sendPendingRequests] in SF MobileSDK version6

### ISSUE THREAD

**Issue by sumanthness** [forcedotcom/SalesforceMobileSDK-iOS#2633]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.0.0
[com.iqvia.oce.primus_issue_25_crash_4be64fa09e1f484f81c43c7433680ca3_DNE_0_v2.txt](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/2339876/com.iqvia.oce.primus_issue_25_crash_4be64fa09e1f484f81c43c7433680ca3_DNE_0_v2.txt)

2. Issue found in Native App or Hybrid App: Native app
3. OS Version: 11.4.1
4. Device: iPad 5
5. Steps to reproduce: When sending the pending requests and sendPendingRequests or flushPendingRequestQueue is called 
8. Error Log: Attached
[com.iqvia.oce.primus_issue_25_crash_4be64fa09e1f484f81c43c7433680ca3_DNE_0_v2.txt](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/2339879/com.iqvia.oce.primus_issue_25_crash_4be64fa09e1f484f81c43c7433680ca3_DNE_0_v2.txt)

**Comment by bhariharan** [comment]
@sumanthness We have fixed quite a few issues in newer versions of the Mobile SDK. Could you upgrade to the latest (`6.2.0`) and let us know if you still see the issue?

**Comment by sumanthness** [comment]
@bhariharan Thank u very much for the quick response, we will upgrade to latest 6.2.0. And update you if we face the same issue again.

**Comment by wmathurin** [comment]
Re-open if you see the issue again. Thanks.
