### ISSUE TITLE
Salesforce login page renders in portrait only

### ISSUE THREAD

**Issue by vsvikram** [forcedotcom/SalesforceMobileSDK-iOS#2635]
1. Version of Mobile SDK Used: v6.2

2. Issue found in Native App or Hybrid App: Hybrid App

3. OS Version: 11.4.1

4. Device: iPad mini

5. Steps to reproduce: I just upgraded the SDK from v6.1 to v6.2 using forcehybrid. After running, salesforce login page renders in portrait only but after login, the app works in both on rotating the device.
6. Actual behavior: 
![img_0039](https://user-images.githubusercontent.com/17747628/45075300-50e57280-b104-11e8-8de7-fddfa7c05e3b.PNG)

7. Expected Behavior:
![img_0040](https://user-images.githubusercontent.com/17747628/45075323-65296f80-b104-11e8-9469-e0a29b2e39d3.PNG)

8. Error Log: Device orientation settings under target for iOS are selected Landscape only for iPad but 
the SF login page renders only in portrait.

**Comment by bhariharan** [comment]
This is by design. We locked the login page to portrait mode on all devices.

**Comment by vsvikram** [comment]
any specific reason for adopting only one orientation in 6.2?

**Comment by bhariharan** [comment]
We ran into windowing issues caused by rotation. You can override this setting in your subclass of login view controller.

**Comment by coulCod** [comment]
Hello, salesforce developers. I have faced with the same error in 7.0 version. My application works in landscape mode only.
 But in sfsdk Portrait orientation hardcoded in SFLoginViewController, SFSDKAppLockViewController and SFSDKRootController. Can you describe how can I override that view controllers from my project.
 It would be convenient if the information about this was in the readme file.

**Comment by jeffreyjackson** [comment]
@coulCod Any luck? We are experiencing the same issue.

**Comment by trooper2013** [comment]
@jeffreyjackson  Do this. 

```
#import <UIKit/UIKit.h>
#import "SFLoginViewController.h"
@interface MyLoginViewController : SFLoginViewController
@end

#import "MyLoginViewController.h"
@implementation MyLoginViewController

...
@end
```
In the AppDelegate do this.
```
[SFUserAccountManager sharedInstance].loginViewControllerConfig.loginViewControllerCreationBlock = ^SFLoginViewController * _Nonnull{
        return [[MyLoginViewController alloc] init];
 };

```

**Comment by Manish-Kr09** [comment]
@bhariharan Is there any way to fix this issue? I have tried with the latest SDK 8.0 and the issue still persists.

What was the actual issue that requires this fix? Can you provide more details on that?

I have tried the workaround by inheriting SFLoginViewController. Still, the app shows multiple blinks when launching in landscape. 
![Login_windowing](https://user-images.githubusercontent.com/2398709/72430472-72ef0a80-37b8-11ea-99aa-1b3993e86f84.gif)

To fully fix the issue, I have identified following solution
Need to override following methods 

`- (BOOL)extended_shouldAutorotate;`
`- (UIInterfaceOrientationMask)extended_supportedInterfaceOrientations;`

of **SFLoginViewController**, **SFSDKAppLockViewController** and **SFSDKRootController**.  

If I somehow override SFSDKRootController then the above issue got resolved, but not sure how to do that as SFSDKRootController is not accessible outside the package. 

Can you provide any workaround? 

I am using hybrid application. 

Thanks
Manish Kumar

**Comment by VenkataramanK** [comment]
Hi @trooper2013 , 

Thanks for your code. I applied and it's working fine in Login Screen.

But for SFSDKAppLockViewController, we don't find appLockControllerCreationBlock in the SDK. Could you please share the code how to override SFSDKAppLockViewController.

Many Thanks,
Venkat.

**Comment by VenkataramanK** [comment]
> @bhariharan Is there any way to fix this issue? I have tried with the latest SDK 8.0 and the issue still persists.
> 
> What was the actual issue that requires this fix? Can you provide more details on that?
> 
> I have tried the workaround by inheriting SFLoginViewController. Still, the app shows multiple blinks when launching in landscape.
> ![Login_windowing](https://user-images.githubusercontent.com/2398709/72430472-72ef0a80-37b8-11ea-99aa-1b3993e86f84.gif)
> 
> To fully fix the issue, I have identified following solution
> Need to override following methods
> 
> `- (BOOL)extended_shouldAutorotate;`
> `- (UIInterfaceOrientationMask)extended_supportedInterfaceOrientations;`
> 
> of **SFLoginViewController**, **SFSDKAppLockViewController** and **SFSDKRootController**.
> 
> If I override SFSDKRootController then the above issue got resolved, but not sure where to define MySFSDKRootController to take impact.
> 
> Can you provide any workaround?
> 
> I am using hybrid application.
> 
> Thanks
> Manish Kumar

Hi Manish,

Did u find anyway for SFSDKAppLockViewController class override? I am also using SFDC Hybrid Remote iOS App.

Thanks,
Venkat.

**Comment by VenkataramanK** [comment]
Hi Guys,

I found a way to override SFSDKAppLockViewController class.

`[SFSecurityLockout setPasscodeViewControllerCreationBlock:^UIViewController *(SFAppLockControllerMode mode, SFSDKAppLockViewConfig *viewConfig) {
        MyAppLockViewController *myAppLockViewController = [[MyAppLockViewController alloc] initWithMode:mode andViewConfig:viewConfig];
               return myAppLockViewController;
           }];`

Thanks,
Venkat.
