### ISSUE TITLE
Unable update records in ParentChildSyncUp Target 

### ISSUE THREAD

**Issue by srinivasbillav** [forcedotcom/SalesforceMobileSDK-iOS#2637]
1. Version of Mobile SDK Used: 6.2.0
2. Issue found in Native App or Hybrid App: Native - Swift
3. OS Version: 11.4.1
4. Device: All Ipad
5. Steps to reproduce:

we are getting following error & unable to update records, if syncup merge mode is leaveifchanged.

**Record not synced since client does not have the latest from server:**
 
This issue can be reproduced with many scenarios,

ex :  

![screen shot 2018-09-10 at 4 12 01 pm](https://user-images.githubusercontent.com/30919541/45292948-67306b80-b514-11e8-988d-e6da85599991.png)

1. create a custom target for "Account" (Parent soup)  and syncup account first, then try to syncup parentchild soups (account-contact,account-profile,account-user), then we will get the following issue.

**Record not synced since client does not have the latest from server:**

2. Add a Contactchild to contact and now update a field in same contact record, now try to sync up parentchild (Account-Contact , Contact-Contactchild), then we will get the following issue 

**Record not synced since client does not have the latest from server:**

**Comment by wmathurin** [comment]
What merge mode did you use?

**Comment by srinivasbillav** [comment]
merge mode : SFSyncStateMergeModeLeaveIfChanged

**Comment by wmathurin** [comment]
We don't have a out of the box sync target for dealing with three levels.
In those cases we recommend you run a regular sync for each level alone and patch reference ids manually between syncs.
Using an external id for the sync up (see https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/entity_framework_native_sync_up_external_id.htm) can make the whole approach easier.
