### ISSUE TITLE
ParentChildSyncupTarget Update fails 

### ISSUE THREAD

**Issue by srinivasbillav** [forcedotcom/SalesforceMobileSDK-iOS#2638]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.2.0
2. Issue found in Native App or Hybrid App: Native - Swift
3. OS Version: 11.4.1
4. Device: All Ipad
5. Steps to reproduce: 

we are getting below error, when trying to update a record.

compositeResponse =     (
                {
            body =             (
                                {
                    errorCode = "INVALID_FIELD_FOR_INSERT_UPDATE";
                    fields =                     (
                        "AccountId"
                    );
                    message = "Unable to create/update fields: AccountId. Please check the security settings of this field and verify that it is read/write for your profile or permission set.";
                }
            );

Ex:- 
![screen shot 2018-09-10 at 5 10 33 pm](https://user-images.githubusercontent.com/30919541/45295580-cc885a80-b51c-11e8-9a16-c00456bfbb53.png)

create a ParentChildSyncupTarget like above.

create a contact record and now syncup parent-child (account - contact) works fine. now try to update a "contactNewField" in a contact then we will get a below error. 

"Unable to create/update fields: AccountId. Please check the security settings of this field and verify that it is read/write for your profile or permission set.";

Double checked that parentchildsync target  "childrenUpdateFieldlist" in contact , doesn't contain  "AccountId"

Only able to fix that issue  if we "allow reparenting" in salesforce

![2018-09-10](https://user-images.githubusercontent.com/30919541/45295322-e7a69a80-b51b-11e8-9579-e442dcb26b89.png)

**Comment by wmathurin** [comment]
The current code includes the foreign key (reference) fields in the list of fields sent to the server without checking if they did indeed change. We don't track field level changes and we don't download the current value from the server during sync up, so fixing that behavior won't be trivial.
Is your work around acceptable?

**Comment by wmathurin** [comment]
Closing issue since there is a workaround.
