### ISSUE TITLE
Custom loginHost - sdk appends "/services/oauth2/authorize" to the host and hence the page is not loading 

### ISSUE THREAD

**Issue by milfar** [forcedotcom/SalesforceMobileSDK-iOS#2639]
Please fill out the following details:

1. Version of Mobile SDK Used: v6.2.0
2. Issue found in Native App or Hybrid App:Native App
3. OS Version:
4. Device:iPhone X
5. Steps to reproduce: change the login host to a custom url instead of "login.salesforce.com" - [SFUserAccountManager sharedInstance].loginHost = @"mydomain.force.com/abc/def";
6. Actual behavior: Authentication page Page doesn't load
7. Expected Behavior: 
8. Error Log: 2018-09-10 17:56:01.077002-0500 RRFrameworkiOSClient[45197:7536683] ERROR|SalesforceSDKManager|Authentication (User Agent) failed: The following required parameters for the identity service were missing: access token, identity URL.

actual approval url - 
https://mydomain.force.com/abc/def/**services/oauth2/authorize**?client_id=XXXXXXXXXXXXXXXXXXXXXX&redirect_uri=https://mydomain.force.com/abc/def&display=touch&response_type=token&scope=api%20refresh_token

If I copy the url in the browser it works when I remove **services/oauth2/authorize** from the URL

**Comment by wmathurin** [comment]
You should do the following
```objective-c
[SFUserAccountManager sharedInstance].loginHost = @"mydomain.force.com";
[SFUserAccountManager sharedInstance].brandLoginPath = @"/abc/def/";
```
