### ISSUE TITLE
Last Error parsing fails

### ISSUE THREAD

**Issue by srinivasbillav** [forcedotcom/SalesforceMobileSDK-iOS#2640]
1. Version of Mobile SDK Used: 6.2
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 11.4
4. Device: iPad
5. Steps to reproduce:
When we try to parse soup's lastError field  String to  JSON, it fails. 
Even if you use SfJsonUtils    +(nullable id)objectFromJSONString:(NSString *)jsonString function.
We are getting below error.
**Error Domain=NSCocoaErrorDomain Code=3840 "No string key for value in object around character 6." UserInfo={NSDebugDescription=No string key for value in object around character 6.}**

Example for lastError:
"{\n    body =     (\n                {\n            errorCode = \"MALFORMED_ID\";\n            fields =             (\n                \"name\"\n            );\n            message = \"name: id value of incorrect type: XXXXXX\";\n        }\n    );\n    httpHeaders =     {\n    };\n    httpStatusCode = 400;\n    referenceId = \"local_89965953153664992196\";\n}"

**Comment by wmathurin** [comment]
It's not JSON currently.
Right now the error captured in the field is the description of the NSError returned by the network call.
See https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SmartSync/SmartSync/Classes/Target/SFSyncUpTarget.m#L229
We need to enhance the network library to bubble up the raw error returned by the server and then we will be able to capture it in the last error field of the sync.

**Comment by az-oolloow** [comment]
@wmathurin yes, this could be very handy, because then the app could actually present a nicer, more human-readable error messages (atm e.g. we throw up the entire `lastError` field, which is not very pretty).

**Comment by bbirman** [comment]
Moved to serialized error in #3228, this will be in the upcoming 8.2 release
