### ISSUE TITLE
Use of undeclared identifier 'MD5_DIGEST_LENGTH' when running a brand new project on iOS from  `forcereact create` output.

### ISSUE THREAD

**Issue by robertovg** [forcedotcom/SalesforceMobileSDK-iOS#2651]
Please fill out the following details:

1. Version of Mobile SDK Used: 
2. Issue found in Native App or Hybrid App:
3. OS Version:
4. Device:
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:
Version of Mobile SDK Used: 6.2.0
Issue found in Native App or Hybrid App: Native app (React Native iOS project ios/myProject.xcworkspace)
OS Version: 12.0
Device: iPad and iPhone
Steps to reproduce: Just trying to run the simulator with the output of `forcereact create` on ios12
Actual behavior: Got error on `mobile_sdk/SalesforceMobileSDK-iOS/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Common/NSData+SFAdditions.m` saying `Use of undeclared identifier 'MD5_DIGEST_LENGTH'`
Expected Behavior: To run the application on iOS as it was happening with ios11
Error Log: `Use of undeclared identifier 'MD5_DIGEST_LENGTH'`

I was able to run it with no problems just defining this variable in the same file. 

So adding `#define MD5_DIGEST_LENGTH 16` in the line 34 of `mobile_sdk/SalesforceMobileSDK-iOS/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Common/NSData+SFAdditions.m`makes it run correctly.

Can you please have a new version so when we run this project, the version loaded from the Pod dependency works correctly?

I hope it's clear.

**Comment by sgoldberg-sfdc** [comment]
Sounds like you are using Xcode 10. MD5_DIGEST_LENGTH has been removed, but was always an Alias to CC_MD5_DIGEST_LENGTH. See this PR: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2641

**Comment by bhariharan** [comment]
This is fixed in our Dev branch and will be a part of our next release.

**Comment by wmathurin** [comment]
We just released 7.0.0-rc which provides XCode 10 / iOS 12 support among other things.
We don't expect any code changes between 7.0.0-rc and 7.0.0 (7.0.0 will be released when doc/trails etc are ready).

**Comment by bazik123** [comment]
what's the proposed solution for apps that can't drop ios10 support yet?

**Comment by wmathurin** [comment]
@bazik123 Keep using SDK 6.2 - and cherry pick https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2641 if you want to use Xcode 10.
