### ISSUE TITLE
Unable to install SalesforceSwiftSDK with CocoaPods

### ISSUE THREAD

**Issue by PSchu** [forcedotcom/SalesforceMobileSDK-iOS#2653]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.2
2. Issue found in Native App or Hybrid App: Native
3. OS Version: all
4. Device: all
5. Steps to reproduce: 
add `pod 'SalesforceSwiftSDK'` to Podfile
run `pod install`
6. Actual behavior:
Pod install throws error:

7. Expected Behavior:
Pod install runs without error
8. Error Log:
```
[!] CocoaPods could not find compatible versions for pod "PromiseKit":
  In Podfile:
    SalesforceSwiftSDK was resolved to 6.0.0, which depends on
      SalesforceSwiftSDK/SalesforceSwiftSDK (= 6.0.0) was resolved to 6.0.0, which depends on
        PromiseKit (~> 5.0)

None of your spec sources contain a spec satisfying the dependency: `PromiseKit (~> 5.0)`.
```

PromiseKit 5.0 was removed from the CocoaPods Master PodSpec Repo.

A "Fix" is to use: 
`pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit.git', :tag => '5.0.3'`
But this will force us to use a 1 year old Version that very quickly get a new major version.

**Comment by wmathurin** [comment]
I'm not sure what you expect from us.

1) Like you stated, PromiseKit 5.0 was removed from the CocoaPods master spec repo.
PromiseKit is not a Salesforce library.
Therefore the only way to make it work is to point to their github repo in your pod file, like you mentioned above.
It's also what we do in our iOS swift template see https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/master/iOSNativeSwiftTemplate/Podfile#L15

2) As for the version of PromiseKit we use (5.0.3), it's the version we tested Mobile SDK 6.2 against and therefore it's the version it depends on.
