### ISSUE TITLE
Help With Files

### ISSUE THREAD

**Issue by nzsrini** [forcedotcom/SalesforceMobileSDK-iOS#2656]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.2
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 12
4. Device:
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

Hi Team,
We need some help on Files.

Files(Content Document Link) support iOS Salesforce SDK.

We are using Files concept for saving image attachments but facing some issues to get the version data which is received as URL instead of base64 string.
 
We have used the below query to fetch the content document related info initially and its stored in the smart store.
select ContentDocument.title, ContentDocument.LatestPublishedVersionId, LinkedEntityId, ContentDocumentId from ContentDocumentLink where LinkedEntityId in (SELECT id FROM Object__c )

Based on the contentDocument id we get again content version data using the following query:-
SELECT VersionData, ContentDocumentId FROM ContentVersion WHERE ContentDocumentId = ‘xxxxxxxxxxxxxxxxx’

In the response we get the versionData in the format of URL (“/services/data/v44.0/sobjects/ContentVersion/068c0000000ZtnkAAC/VersionData”). But in the documentation its mentioned as of type base64 string. 

Are there any SDK methods , so that we get the version data directly which will be base64 format instead making SFRest API call to fetch the data using the above URL.

**Comment by wmathurin** [comment]
SOQL does not return the binary data, only URLs (see https://developer.salesforce.com/forums/?id=9060G000000Xj0HQAS).

To get the binary data, either do a get against one of those URLs or use https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/RestAPI/SFRestAPI%2BFiles.h#L103

**Comment by iandrosov** [comment]
That is exactly what I try to use that did not return the file data instead I got NULLs.
URL returned by SOQL seem to be requiring a new RAW REST call for data with an authenticated session need to construct that raw request yet another complexity to get the session from iOS SDK (that can be done)

The api requestForFileContents is one example I tested that did not respond with file data.

@wmathurin
