### ISSUE TITLE
Use of undeclared identifier 'MD5_DIGEST_LENGTH'

### ISSUE THREAD

**Issue by arupsarkar** [forcedotcom/SalesforceMobileSDK-iOS#2661]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.2
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: macOS High Sierra
4. Device: iPhone
5. Steps to reproduce: 
I already built out a iPhone app in swift, I was incorporating salesforce's mobile SDK in my project via pod install, I am getting the error
`Use of undeclared identifier 'MD5_DIGEST_LENGTH'`
when building my project. My pod file looks like the following
`platform :ios, '12.0'`
`target 'FoodTracker' do`
  `use_frameworks!`
`source 'https://github.com/CocoaPods/Specs.git'
  pod 'SalesforceSDKCore', :path => '/Users/arup.sarkar/projects/iOS/SalesforceMobileSDK-iOS/'
  pod 'SalesforceAnalytics', :path => '/Users/arup.sarkar/projects/iOS/SalesforceMobileSDK-iOS/'
  pod 'SmartStore', :path => '/Users/arup.sarkar/projects/iOS/SalesforceMobileSDK-iOS/'
  pod 'SmartSync', :path => '/Users/arup.sarkar/projects/iOS/SalesforceMobileSDK-iOS/'
  pod 'SalesforceSwiftSDK', :path => '/Users/arup.sarkar/projects/iOS/SalesforceMobileSDK-iOS'
  pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit', :tag => '5.0.3'
end`

Not sure how to resolve the MD5 error. Am I missing any imports ?

6. Actual behavior:
7. Expected Behavior:
8. Error Log:

**Comment by arupsarkar** [comment]
Pulled dev branch from github v7.0, compiled successfully.  One thing I noticed is that 
`pod 'SalesforceSwiftSDK', :path => '/Users/arup.sarkar/projects/iOS/SalesforceMobileSDK-iOS/`

was not found, is it merged with SalesforceSDKCore ?

**Comment by bhariharan** [comment]
@arupsarkar This is fixed on the `dev` branch. `SalesforceSwiftSDK` has been moved to a different location. Stay tuned for more details.
