### ISSUE TITLE
iOS Login Screen - Unable to "Re-coop" space Real-estate when Navbar is hidden

### ISSUE THREAD

**Issue by leoehart** [forcedotcom/SalesforceMobileSDK-iOS#2664]
Is there a way to re-coop the space occupied by the Salesforce Navbar when "showNavbar = No"?

I have set "showNavbar = No" and the space occupied by what was the Navbar is still occupied, pushing content within the app down (requiring users to scroll to see buttons that otherwise displayed in versions prior to 6.0

1. Version of Mobile SDK Used: Ver 6.2
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: iOS11
4. Device: iPhone 7
5. Steps to reproduce: 
- Implement latest Salesforce Mobile iOS SDK
- Update iOS Login class to contain "showNavbar = No"
6. Actual behavior:
- Navigation Bar remains visible
7. Expected Behavior:
- It sounds like this was the way Salesforce intended "showNavbar = No" to function. Is there a way to recoop the space where the Navbar displays?

![loginpage](https://user-images.githubusercontent.com/25070986/47059081-5915e080-d18d-11e8-8e84-badfa4a972b1.png)

**Comment by trooper2013** [comment]
@leoehart Add to the following code to your AppDelegate  to turn it off. 
[SFUserAccountManager sharedInstance].loginViewControllerConfig.showNavbar = NO;
