### ISSUE TITLE
Unable to re-launch SalesforceSDK Manager

### ISSUE THREAD

**Issue by nuvolarmobileteam** [forcedotcom/SalesforceMobileSDK-iOS#2666]
1. Version of Mobile SDK Used: 
6.1

2. Issue found in Native App or Hybrid App:
Native

3. OS Version:
any OS

4. Device:
any device / simulator

5. Steps to reproduce:
- Launch SDK manager. When the web view for credentials is presented wait for 15 minutes and
populate user and password and log in.
- The web view will present a page with the following message 'You didn't complete the approval process before it expired. Please try again'

6. Actual behavior:
At this point you get no callback so there is nothing you can do a part from killing the app.
In other to fix this issue we tried to reload the web view every x minutes so when the user finally does the login the session is not expired but for this to happen we are calling `[[SalesforceSDKManager sharedManager] launch]` again. When we do so the internal _isLaunching BOOL is set to true and the system does not proceed.

7. Expected Behavior:
We are able to relaunch the SDKManager either every X minutes or when we get a callback announcing this error happened. 

Many thanks in advance

**Comment by nuvolarmobileteam** [comment]
Hi @trooper2013 ,

We are calling launch periodically every 5 minutes if the user did not complete the login. As mentioned in the original question this is to avoid the situation where after 10 minutes in the login screen the system does not allow to complete the process even if the user and password are correct.

**Comment by trooper2013** [comment]
@nuvolarmobileteam You can set shouldAuthenticate in the SFSDKAppConfig to NO. This avoids auth during launch.  Then use SFUserAccountManager:authenticateWithCompletion instead.

**Comment by nuvolarmobileteam** [comment]
We will give it a try. Thank you @trooper2013 !
