### ISSUE TITLE
Additional Connection/SSO screen does not support NTLM authentication

### ISSUE THREAD

**Issue by alsocalledchris** [forcedotcom/SalesforceMobileSDK-iOS#2670]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.2
2. Issue found in Native App or Hybrid App: Hybrid
3. OS Version: iOS 12
4. Device: iPhone 8 plus/X
5. Steps to reproduce:
Setup a SSO that shows the credentials request via NTLM

6. Actual behavior:
The App does not allow the user to enter a username and password and a 401 is immediately returned from the server

7. Expected Behavior:
The App allows the user to enter a username and password to authenticate.
Using iOS Safari shows the credential challenge box fine (as does Android).

8. Error Log:
NA

**Comment by trooper2013** [comment]
@alsocalledchris Can you try to setup the the domain to use Advanced Authentication Mode and give it a go?

**Comment by alsocalledchris** [comment]
@trooper2013  - tried that, did not work either - same problem on iOS (for reference followed this article: https://releasenotes.docs.salesforce.com/en-us/summer16/release-notes/rn_security_auth_mobile_browser.htm)

**Comment by trooper2013** [comment]
In the advanced mode, the app will open up SafariViewController. Could you post a screen shot of the login screen and error?

**Comment by alsocalledchris** [comment]
@trooper2013  thanks - if it's using the SafariViewController is working it is still just showing in the App (which is different to Android which pops-out to Chrome) and just shows a blank white screen and no error - just the returned 401.

**Comment by alsocalledchris** [comment]
any ideas anyone?

**Comment by wmathurin** [comment]
In our next release (which should come out at the end of the month #safeharbor), we are using SFAuthenticationSession instead of SFSafariViewController. Could you give it a try to see if it makes a difference? We are not setup here to duplicate your setup (NTLM) and therefore are unable to reproduce your issue.

**Comment by alsocalledchris** [comment]
@wmathurin thanks - is this in SDK 7.0? If so we can try with it- otherwise what version should I point at?

**Comment by brandonpage** [comment]
@alsocalledchris Yes, the 7.0 RC does include the shift from SFSafariViewController to SFAuthenticationSession.

**Comment by trooper2013** [comment]
@alsocalledchris If advanced auth does not work, you can additionally try to add an ATS exception for your domain only (set NSAllowsArbitraryLoads to  YES) and see if that fixes the problem. There maybe a cert problem or something else on the server side resulting in this failure.

**Comment by alsocalledchris** [comment]
@brandonpage @wmathurin SDK 7 RC is looking promising for NTLM support - it shows the dialog to enter username/password which is better than before 👍 - when is the final version being delivered and the RC is being dropped? thanks

**Comment by wmathurin** [comment]
FYI, 7.0 was released last night. 
When you said "better than before", did you mean that you no longer have an issue?

**Comment by alsocalledchris** [comment]
@wmathurin not 100% sure as I only got as far as it showing a login box - which was better than no box as before. Can we run Xcode 9 with target 11 for SDK 7 - it seems to compile OK but in the release notes it suggests minimum Xcode 10 and base SDK iOS 12. We can't use XCode 10 as there is a cordova bug that currently exists which stops remote hybrid working correctly (https://github.com/apache/cordova-ios/issues/417)

**Comment by wmathurin** [comment]
I believe it should work.

**Comment by alsocalledchris** [comment]
@wmathurin so after more investigation, SDK7 did not fix the App showing the NTLM authentication box within the App - however when using the advanced authentication and using 'native browse' for user authentication it does now show there. However after authentication has happened, the loading screen just shows within the app and nothing happens - the bug #2768

**Comment by trooper2013** [comment]
@alsocalledchris Could you follow the steps required for Adv. Auth in #2768? Have you also tried the alternative by adding the ATS Exception as I suggested on this thread?

**Comment by wmathurin** [comment]
This issue is almost 4 years old. The code has changed a lot since then. 
Please open a new issue if you think it is still relevant today.
