### ISSUE TITLE
Live Agent Timeout Notification

### ISSUE THREAD

**Issue by JinTiloganart** [forcedotcom/SalesforceMobileSDK-iOS#2675]
1. Version of Mobile SDK Used: SDK version 214.0.4, Live agent chat version: 1.6.2
2. Issue found in Native App or Hybrid App: Native app
3. OS Version: 12.0.1
4. Device: iPhone 6S plus
5. Steps to reproduce:
1) In 'Chat Buttons and Automated Invitations' ,configure 'Customer Time-Out (seconds)' to 90 seconds
2) Initiate chat on iOS device
3) Chat got routed to agent
4) Agent send message to customer
5) Customer leave the app open in the foreground for 5 mins
6) leave the app in the background for 5 mins
 
6. Actual behavior: Chat session is not terminated after 5 mins of inactivity
7. Expected Behavior: Chat session is terminated after customer is inactive for 90 secs from Agent's last reply.
8. Error Log:

**Comment by bhariharan** [comment]
This is not the right forum to post issues with the SnapIns SDK. Mobile SDK is a different product.
