### ISSUE TITLE
Do you have plan to support SalesforceSwiftSDK in version7?

### ISSUE THREAD

**Issue by hmuronaka** [forcedotcom/SalesforceMobileSDK-iOS#2689]
Hi,
I couldn't find SalesforceSwiftSDK in preview-version7 sourcecodes.
Which are you going to support SalesforceSwiftSDK or not in ver7?

1. Version of Mobile SDK Used: 
branch: dev70preview

**Comment by wmathurin** [comment]
In 7.0, we made our APIs a lot more Swift friendly (using NS_SWIFT_NAME etc) and therefore there is no need for the SalesforceSwiftSDK anymore. At this point, we might want to hold off for the actual release, since it should be out by the end of the month. #safeharbor
