### ISSUE TITLE
Compliance 

### ISSUE THREAD

**Issue by kSakthiraj** [forcedotcom/SalesforceMobileSDK-iOS#2710]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.2.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: any
4. Device: any
5. Steps to reproduce: 
     • Connect via SSH to the mobile device.
     • Run the command “otool –v –I ExAM4Inspections | grep MD5” 
     • Observe MD5
6. Actual behavior:
7. Expected Behavior:
8. Error Log: Do not use weak algorithms, such as MD5 / SHA1. Favor safer alternatives, such as SHA-256 or better.

Reference: https://www.owasp.org/index.php/Mobile_Top_10_2016-M5-Insufficient_Cryptography

**Comment by wmathurin** [comment]
The tool won't tell you what MD5 is used. We don't use it when dealing with sensible data.

I recommend you look at the code or check out our security guide: https://resources.docs.salesforce.com/sfdc/pdf/salesforce1_mobile_security.pdf.

There you will see that we are following strong encryption standards when encrypting sensible data.
