### ISSUE TITLE
Error code 1005

### ISSUE THREAD

**Issue by avikroy** [forcedotcom/SalesforceMobileSDK-iOS#2714]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.2
2. Issue found in Native App or Hybrid App: Native app
3. OS Version: iOS 12
4. Device: iPad

Hi Team
Earlier we were using SDK 5. Now after upgrading from 5 to 6.2 we found that we are getting one error code with 1005 with error domain as NULL.
Can you please let us know what does 1005 signifies? what is the resolution to work on such behaviour?

Thanks in Advance

**Comment by wmathurin** [comment]
This is where that error originates from: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Security/SFUserAccountManager.m#L1384

Could you give us more details? What are the repro steps? What exact version of Mobile SDK were you using before.

**Comment by wmathurin** [comment]
Closing the issue until more details are provided.
