### ISSUE TITLE
Xcode 10 and iOS 12

### ISSUE THREAD

**Issue by btxsqdr** [forcedotcom/SalesforceMobileSDK-iOS#2719]
Hey guys

When is the Salesforce Mobile SDK available for Xcode 10?

I'm referring to the timelines mentioned here https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2614

Also, could you perhaps fire your product manager responsible for this? Bear in mind that other frameworks that are bigger and more complex than SF mobile, provided an update to the newest Xcode version in Oct/Nov already, thanks to the preview releases provided by Apple. It is rather unprofessional and disturbing how SF is handling such an important update, especially considering that it is for iOS. Why did your product manager or lead (etc) did not consider this? After all, SF is used in real environments with real devices for the generation of real money revenue.

Because of your delays projects cannot be upgraded to Xcode 10 which in turns means that all other dependencies cannot be upgraded for months, only because of you guys. 

With best regards

**Comment by davidmdavis** [comment]
Yeah, this is becoming a real issue for us. We can't even build (run from Xcode) for some of the new Apple devices that use the arm64e architecture.

**Comment by trisco2001** [comment]
This became a real issue for us a long time ago. We cannot debug our app on our devices. Our team is missing out on improvements from Xcode 10. We're considering migrating our app away from Salesforce entirely.

**Comment by wmathurin** [comment]
We just released 7.0.0-rc which provides XCode 10 / iOS 12 support among other things.
We don't expect any code changes between 7.0.0-rc and 7.0.0 (7.0.0 will be released when doc/trails etc are ready).
