### ISSUE TITLE
Bug in SDK V7.0.0 Preview

### ISSUE THREAD

**Issue by SunilS123** [forcedotcom/SalesforceMobileSDK-iOS#2720]
Please fill out the following details:

Version of Mobile SDK Used:  7.0.0 Preview
Issue found in Native App or Hybrid App: Native App

Please check the SFRestApi+Blocks.h
![screen shot 2018-12-07 at 4 37 16 pm](https://user-images.githubusercontent.com/17869039/49685019-37d4cf00-fb02-11e8-87ad-d3eda98e72a5.png)
 
Here function name and parameters are same for both.

**Comment by wmathurin** [comment]
This is fixed in dev (in will be in our soon to be released 7.0).

**Comment by wmathurin** [comment]
We just released 7.0.0-rc which provides XCode 10 / iOS 12 support among other things.
We don't expect any code changes between 7.0.0-rc and 7.0.0 (7.0.0 will be released when doc/trails etc are ready).
