### ISSUE TITLE
unable to compile SmartSyncExplorerSwift SDK 7.0 Developer Preview

### ISSUE THREAD

**Issue by SunilS123** [forcedotcom/SalesforceMobileSDK-iOS#2721]
**Use following command in terminal :-**

forceios createwithtemplate --templaterepouri=https://github.com/forcedotcom/SalesforceMobileSDK-Templates/SmartSyncExplorerSwift#dev70preview

![screen shot 2018-12-10 at 2 50 14 pm](https://user-images.githubusercontent.com/17869039/49722526-ffacc800-fc8a-11e8-86df-7f7e2fb70a88.png)

Please check the above issue.

**Comment by wmathurin** [comment]
There is no SalesforceSwiftSDK in 7.0 anymore. Instead we used a lot NS_SWIFT_NAME across the code base to make the APIs more Swift friendly.
