### ISSUE TITLE
UIApplicationInvalidInterfaceOrientation crash

### ISSUE THREAD

**Issue by avikroy** [forcedotcom/SalesforceMobileSDK-iOS#2723]
Please fill out the following details:

1. Version of Mobile SDK Used: SDK 6.2
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 12
4. Device: iPad
5. Error Log:
Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [UIAlertController shouldAutorotate] is returning YES'
main.m, line 33

Here in our iPad add we are allowing only landscape mode. But Salesforce SDK is allowing all rotation and possibly this is causing a crash due to invalid orientation.

So is there any fix for this?

**Comment by trooper2013** [comment]
@avikroy Could you provide more details. Type of iPad, how are you handling rotations and restricting rotations?

**Comment by Zaquan59** [comment]
I TRY it

**Comment by trooper2013** [comment]
Not enough information. Closing issue
