### ISSUE TITLE
7.0RC with cocoapods

### ISSUE THREAD

**Issue by jeffreyjackson** [forcedotcom/SalesforceMobileSDK-iOS#2731]
Is this supported yet?  Cocoapods shows that a new version (7.0 RC) is available but can not update because versions are fixed in the Podfile.  The only pods I'm using are Core and Analytics.

**Comment by wmathurin** [comment]
Could you explain what you mean by "can not update because versions are fixed in the Podfile" ?

**Comment by jeffreyjackson** [comment]
![image](https://user-images.githubusercontent.com/867999/50020960-815f6700-ffa5-11e8-80d9-ae418dcc5356.png)

**Comment by jeffreyjackson** [comment]
@wmathurin my apologies on the confusion in the first message.  the Podfile I have doesn't have any versions locked, so it should update.

**Comment by wmathurin** [comment]
So it's working for you?

**Comment by wmathurin** [comment]
7.0.0-rc is fully released now (podspecs / forceios etc). 
We don't expect any code changes between 7.0.0-rc and 7.0.0 (7.0.0 will be released when doc/trails etc are ready).

Let us know if you run into any issues.
