### ISSUE TITLE
SDK Version 216.0.0 is causing our mobile app to crash in Production

### ISSUE THREAD

**Issue by shanecinense1994** [forcedotcom/SalesforceMobileSDK-iOS#2733]
Issue: The iOS version of the Mobile SDK is causing our app to crash(authentication not working) when the SDK is pointed in Production but once it is pointed to a lower environment (Staging), it is successfully authenticating.

1. Version of Mobile SDK Used: 210.0.0 is the current SDK Version being used that is working. 216 is the version that is causing the app to crash.

2. Issue found in Native App or Hybrid App: Native App

3. OS Version: iOS 10 and above

4. Device: All devices

5. Steps to reproduce:

Below is the code to reproduce the issue:
https://drive.google.com/open?id=1JG3YBS9Avfvw8pgGmjNytUA_jBmE9cWQ

Kindly send us an email so we can send you the password on the zip file
My email is sharmaine.a.cinense@accenture.com

How to use the code to reproduce the issue:

Open TestSalesForce.xcodeproj using Xcode 10
Build and run the code, on the first screen, click 'Login' button

6. Actual behavior: the screen show nothing
7. Expected Behavior: See the detail messages for that case
8. Error Log: N/A

**Comment by wmathurin** [comment]
I don't recognize the versions you are mentioning.
Mobile SDK latest is 7.0.0-rc, previous one was 6.2. 
You need to use 7.0.0-rc for Xcode 10 / iOS 12 support.

**Comment by shanecinense1994** [comment]
We are trying to get hold on our stakeholder. May we ask to schedule a conference call with you to set things easily and clear? Preferably this week or next week.

**Comment by shanecinense1994** [comment]
The mobile SDK version we are using that is working in Staging environment and not working in Production environment is version 6.2.

Regarding a call, here are some possible times:
Today: Between 12:30pm – 2pm
Tomorrow (19/12): Between 9am – 11am
Tomorrow (19/12) Between 1pm – 2pm
Tomorrow (19/12) Between 3pm – 5pm
Thursday (20/12) Between 12:30 – 4:30pm

Can you pick one of the above timings so we can send you a meeting invite.
Thank you

**Comment by shanecinense1994** [comment]
Hi,

Good day.
The mobile SDK version we are using that is working in lower environment and not working in Production environment is version 6.2.
To clear things up and make this easier, can we schedule a conference call? Kindly pick one on the below timings which you are available.
Today: Between 12:30pm – 2pm
Tomorrow (19/12): Between 9am – 11am
Tomorrow (19/12) Between 1pm – 2pm
Tomorrow (19/12) Between 3pm – 5pm
Thursday (20/12) Between 12:30 – 4:30pm
Thank you


Regards,
Sharmaine Shane A. Cinense
Cloud First Applications – Managed Services
GDN for Technology in the Philippines
Uptown Tower 3, Bonifacio Global City, Taguig
Email: sharmaine.a.cinense@accenture.com
[1511491842797_accenture-technology.png]

**Comment by bhariharan** [comment]
@shanecinense1994 Looking at your project, it appears that you're using the `SnapIns SDK`, which indirectly uses the `Mobile SDK`. They will need to support the newer version of `Mobile SDK` and make it interoperable with their `Service SDK`. Please file an issue and follow up with the `Service SDK` team on [their GitHub repo](https://github.com/forcedotcom/ServiceSDK-iOS). There is little we can do.
