### ISSUE TITLE
SDK 7.0 Multiple Bootconfig

### ISSUE THREAD

**Issue by ElieBuff10** [forcedotcom/SalesforceMobileSDK-iOS#2750]
I'm using the new SDK 7.0.

I have a mobile application with multiple scheme.
One scheme is connected to my SF Sandbox, the other one is connected to my Production org.

I need to have multiple bootconfig.plist in order to connect to the different Connected Apps.

We saw the function Bootconfig.Init, but couldn't figure it out how to use it.

Thanks.

**Comment by wmathurin** [comment]
May we ask, why do you need multiple connected apps? When you define a connected app, it's available in all orgs (across sandbox and production instances).

**Comment by ElieBuff10** [comment]
If I'm creating the Connected App in the production org, I'm not sure I
will be able to use it in the Sandbox in order to get Push Notifications
from SF.

I will be able to connect, but I won't receive the Push Notification from
SF.

Am I right?

*Elie Buff*| Mobile Applications Team Leader

Office : +972 (0)73 705 14 12  |  Fax: +972 (0)77 450 60 73 | www.balink.net

**Comment by wmathurin** [comment]
Couldn't you have two builds of the app: one for sandbox and one for production?

**Comment by trooper2013** [comment]
Not a bug.
