### ISSUE TITLE
In-App developer support screen always seems to be available to be shown

### ISSUE THREAD

**Issue by alsocalledchris** [forcedotcom/SalesforceMobileSDK-iOS#2761]
Please fill out the following details:

1. Version of Mobile SDK Used: 7
2. Issue found in Native App or Hybrid App: Hybrid
3. OS Version: iOS 12
4. Device: iPhone 8 Plus
5. Steps to reproduce:
Create a release build, either for TestFlight or local install
Install App on phone via TestFlight or side-loading

6. Actual behavior:
In-App developer support screen shown even if release build configuration used

7. Expected Behavior:
In-App developer support screen not shown

8. Error Log: NA

The build is a release build - is this still happening as the device is also enrolled in the dev testing so we can side-load the App onto the Phone? Documentation suggests the screen should only show on debug builds and not release builds: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/tools_dev_support.htm (we haven't done anything to change this logic)

**Comment by rwhitley** [comment]
Have you tried adding these calls explicitly in the native wrapper apps?

iOS (in AppDelegate+SalesforceHybridSDK.m):
// To disable
[SalesforceHybridSDKManager sharedManager].isDevSupportEnabled = NO;

Android (in HybridApp.java):
// To disable
SalesforceHybridSDKManager.getInstance().setDevSupportEnabled(false);

**Comment by bhariharan** [comment]
@alsocalledchris I'm guessing this happens on our hybrid apps because the library binaries we generate aren't signed. You can explicitly turn off the dev support screen in your app for release builds.

**Comment by wmathurin** [comment]
See my comment [here](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/419#issuecomment-434394729)

I guess we could add a few lines in AppDelegate+SalesforceHybridSDK.h to do that based on the build type - so that hybrid developers don't all have to do the same thing. We will do that in our next release, for now, you can do that in your app.

**Comment by wmathurin** [comment]
In the next version of the SDK, you won't need to add code to your AppDelegate thanks to https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Hybrid/pull/29.

**Comment by alsocalledchris** [comment]
OK thanks all, is this code correct, it seems to do the job:

- (AppDelegate *)init
{
    self = [super init];
    [SalesforceSDKManager sharedManager].isDevSupportEnabled = NO;
    return self;
}

**Comment by wmathurin** [comment]
That looks correct.
