### ISSUE TITLE
SFKeychainItemWrapper.m line 161

### ISSUE THREAD

**Issue by amiramelzam** [forcedotcom/SalesforceMobileSDK-iOS#2762]
Please fill out the following details:

1. Version of Mobile SDK Used: 6
2. Issue found in Native App or Hybrid App: IOS native
3. OS Version: 12
4. Device: all Iphones
5. Steps to reproduce: NA found on crashlytics
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

Fatal Exception: com.salesforce.security.keychainExceptionwriteToKeychain: Error adding keychain item: errSecInteractionNotAllowed. Raw Text
--
0 | CoreFoundation | __exceptionPreprocess
1 | libobjc.A.dylib | objc_exception_throw
2 | SalesforceSDKCore | SFKeychainItemWrapper.m line 161-[SFKeychainItemWrapper accessibleAttribute]
3 | SalesforceSDKCore | SFKeychainItemWrapper.m line 374-[SFKeychainItemWrapper writeToKeychain]
4 | SalesforceSDKCore | SFKeychainItemWrapper.m line 264-[SFKeychainItemWrapper setObject:forKey:]
5 | SalesforceSDKCore | SFKeychainItemWrapper.m line 418-[SFKeychainItemWrapper setValueData:]
6 | SalesforceSDKCore | SFOAuthKeychainCredentials.m line 250-[SFOAuthKeychainCredentials updateKeychainWithTokenData:forService:]
7 | SalesforceSDKCore | SFOAuthKeychainCredentials.m line 138-[SFOAuthKeychainCredentials setAccessToken:withSFEncryptionKey:]
8 | SalesforceSDKCore | SFOAuthKeychainCredentials.m line 66-[SFOAuthKeychainCredentials setAccessToken:]
9 | Foundation | -[NSObject(NSKeyValueCoding) setValue:forKey:]
10 | SalesforceSDKCore | SFOAuthCredentials.m line 311-[SFOAuthCredentials setPropertyForKey:withValue:]
11 | SalesforceSDKCore | SFOAuthCoordinator.m line 845-[SFOAuthCoordinator updateCredentials:]
12 | SalesforceSDKCore | SFOAuthCoordinator.m line 679-[SFOAuthCoordinator handleTokenEndpointResponse:]
13 | SalesforceSDKCore | SFOAuthCoordinator.m line 645__45-[SFOAuthCoordinator beginTokenEndpointFlow:]_block_invoke

**Comment by trooper2013** [comment]
@amiramelzam It seems like the keychain items are not accessible during the auth flow ? Can you shed some light on what your app is attempting to do at the  time that the crash has occurred?

**Comment by amiramelzam** [comment]
I use the SDK only for the Login. SDK display web view with login and password and we don't have an access to the flow.

**Comment by trooper2013** [comment]
@amiramelzam Is this happening in an existing app that you have upgraded or does this occur on a new app that you have created using forceios?

**Comment by trooper2013** [comment]
Not enough information. Closing issue
