### ISSUE TITLE
FaceId either crashes or shows error on authentication

### ISSUE THREAD

**Issue by alsocalledchris** [forcedotcom/SalesforceMobileSDK-iOS#2764]
Please fill out the following details:

1. Version of Mobile SDK Used: 7
2. Issue found in Native App or Hybrid App: Hybrid
3. OS Version: 12.1.3
4. Device: iPhone X

5. Steps to reproduce: 
Setup app with PIN and login as usual
Close App
Open App and use FaceID to authenticate (FaceId authenticates OK)

6. Actual behavior:
App either hangs with a white screen (if installed from fresh) or shows a error message (if installed over an older 6.X app) "Bootstrap error page: Your app specifies authentication at startup, but there are no credentials. Did you run [[SalesforceSDKManager sharedManager] launch]? Error context: AppLoading"

7. Expected Behavior: 
Should log in fine

8. Error Log: NA

**Comment by trooper2013** [comment]
@alsocalledchris  if started from a sample app created  with  forceios please ensure that you add the required entry in the apps plist for FaceId (NSFaceIDUsageDescription) and try. If upgrading your app from 6.x  to 7.x there will be a few changes required for launching your app. Please get a template from forcehybrid and proceed.

**Comment by alsocalledchris** [comment]
@trooper2013  thanks - we did this and it worked. Please could you point me at the documentation that mentions the required entry to ensure we have not missed anything else. Thanks

**Comment by trooper2013** [comment]
@alsocalledchris This is a requirement by Apple for enabling biometric capability for any given app.
