### ISSUE TITLE
xcode 10.1 SalesforceSDKAssets.xcassets inaccessible after second build

### ISSUE THREAD

**Issue by coulCod** [forcedotcom/SalesforceMobileSDK-iOS#2767]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Mac OS 10.13.6, iOS 11.4, xCode 10.1
4. Device: iPad Air 2
5. Steps to reproduce:
- Build project;
- Then build it again. Images are not loaded only after rebuilding the project.
6. Actual behavior: login-window-gear not displayed
7. Expected Behavior: login-window-gear should be displayed
8. Error Log:

That bug is not exist when build project with xCode 9.4
Here is how it looks when I put breakpoints at the `SFSDKResourceUtils imageNamed:` method with xCode 9.4
![screen shot 2019-02-05 at 1 50 00 pm](https://user-images.githubusercontent.com/15382299/52271721-2adf2b00-294d-11e9-8089-351bf847cff6.png)

And how looks the same action when project builds with xCode 10.1
First build
![screen shot 2019-02-05 at 2 07 22 pm](https://user-images.githubusercontent.com/15382299/52272424-71358980-294f-11e9-83fc-3a26193408c4.png)
Second build
![screen shot 2019-02-05 at 2 08 37 pm](https://user-images.githubusercontent.com/15382299/52272465-91fddf00-294f-11e9-8c11-66b367f574ef.png)

Take a look at the value of image variable, it is nil.

**Comment by trooper2013** [comment]
@coulCod  Could you use the `forceios` cli tool and create a sample app, then try the same test and see if you can reproduce problem?

**Comment by coulCod** [comment]
@trooper2013 Yes. I just have reproduce that bug with force ios cli tool too.
Steps to reproduce:
1. From console: `node_modules/.bin/forceios create --apptype=native --appname=sfsdktest --packagename=com.sfsdktest`
2. Enter all the information that will be requested from the console.
3. In created sample project modify Podfile to:
```
platform :ios, '11.0'

target 'sfsdktest' do

source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

pod 'SalesforceSDKCore', '7.0'
pod 'SalesforceAnalytics', '7.0'

end
```
4. Remove next lines of code from AppDelegate.m:
```
#import <SmartSync/SmartSyncSDKManager.h>
#import <SmartSync/SFSDKSmartSyncLogger.h>
```
` [SmartSyncSDKManager initializeSDK];`

5. run command from console:
`pod install`
6. build project with Xcode 10.1 with simulator iPad Air 2 iOS 12.1
login screen should looks like here:
![screen shot 2019-02-07 at 10 32 17 am](https://user-images.githubusercontent.com/15382299/52399036-ae228d00-2ac3-11e9-84e2-93f0253665f0.png)

7. build project second time:
![screen shot 2019-02-07 at 10 33 24 am](https://user-images.githubusercontent.com/15382299/52399102-d90ce100-2ac3-11e9-81a1-69cead8222c0.png)

**Comment by trooper2013** [comment]
@coulCod Thanks for reporting. We are looking into it.

**Comment by trooper2013** [comment]
@coulCod Looking at the repro steps you provided. 

why is the pod file different?  Aren't you building frameworks?

It's missing the required dependency.   
`pod 'SalesforceSDKCommon', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'`

and why did you remove the initializeSDK statement?

**Comment by coulCod** [comment]
> why is the pod file different?
I am made a pod file in the sample to be the same with in my project.

> Aren't you building frameworks?
In my project I am not use swift. So that line is not necessary for me.

> It's missing the required dependency.
`pod 'SalesforceSDKCommon', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'`
As you describe in your documentation here https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/ios_cocoapods.htm
That is the minimal pod configuration:
![screen shot 2019-02-08 at 5 42 20 pm](https://user-images.githubusercontent.com/15382299/52488624-e8298700-2bc8-11e9-9350-4479602ac812.png)
So it is not required to specify pod SalesforceSDKCommon.

> and why did you remove the initializeSDK statement?
I did remove initializeSDK because I did not use SmartSync library.

@trooper2013 Are you sure that pod config should be related to that kind of bug?

**Comment by trooper2013** [comment]
@coulCodSo FYI you should have the Common dependency. The documentation does show the component in the dependency tree.  I don't see how your app is going to work without it. Secondly you must initialize the SDK. If not are you using launch for sdk manager instead?  

I don't see this problem that you are reporting while building frameworks. I'd like to caution you that there will be little or no support for static libs in the future.  The crux of the problem probably stems  from the fact that resources ( SalesforceSDKAssets.xcassets) are not being copied during build? You can create a hybrid sample app using  using `forcehybrid`. We employ the use of static sdk libs here. You could check the build phases and see whats missing for your targets.
