### ISSUE TITLE
Unable to login using Advanced Authentication on iOS

### ISSUE THREAD

**Issue by Jas05** [forcedotcom/SalesforceMobileSDK-iOS#2768]
Please fill out the following details:

1. Version of Mobile SDK Used:  Salesforce Mobile SDK 7.0

2. Issue found in Native App or Hybrid App: Hybrid
3. OS Version: iOS SDK 11/12
4. Device: iPhone 8 Plus
5. Steps to reproduce: Using Salesforce Mobile Sdk 7.0- login to custom domain 
 
- Set the UrlTypes in the app plist file.
- Enable "Use the native browser for user authentication on iOS" in Org 
- Login to custom domain 
- Clicking continue on Dialog: "Want to Use 'Salesforce.com' to Sign in"
- Enter your credentials 
- Click Login

6. Actual behavior:
- Getting an error "invalid client credentials" in debug window in xCode. 
  And App is stuck on Loading... message

Its works fine if i disable "Use the native browser for user authentication on iOS" in Org 

7. Expected Behavior:
   - It should log the user in.

8. Error Log:

[SalesforceSDKCore] CLASS: SFSDKOAuthClient oauthCoordinator:didFailWithError: Error Domain=com.salesforce.OAuth.ErrorDomain Code=671 "invalid client credentials" UserInfo={error=invalid_client, NSLocalizedDescription=invalid client credentials}, authInfo: <SFOAuthInfo: xxxxx, authType=SFOAuthTypeUserAgent>

[SalesforceSDKCore] CLASS: SFOAuthKeychainCredentials SFOAuthKeychainCredentials:setIdentityUrl: invalid or nil identityUrl: (null)
2019-02-05 14:49:46.394002+0000 [SalesforceSDKCore] CLASS: SFOAuthKeychainCredentials SFOAuthKeychainCredentials:setIdentityUrl: invalid or nil identityUrl: (null)

**Comment by wmathurin** [comment]
Have you followed all the steps described in the [documentation](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/auth_ios_advanced.htm)?

For an example of an application using advanced authentication, please checkout the RestAPIExplorer in our [main repo](https://github.com/forcedotcom/SalesforceMobileSDK-iOS). The key configurations are the [info.plist](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/native/SampleApps/RestAPIExplorer/RestAPIExplorer/Info.plist) and the bootconfig file.

**Comment by Jas05** [comment]
i got bootconfig.json set correctly and placed inside www. my app works fine if I untick "Use the native browser for user authentication on iOS".

**Comment by trooper2013** [comment]
@Jas05 to use native Browser Authentication, you have to configure this in your org. To do so setup a domain and enable "Use the native browser for user authentication on iOS"  We do not allow for you to set it up from the client app anymore.

**Comment by jasmeetbhatiasagecom** [comment]
Hello @trooper2013, @wmathurin   
that is what we are doing, we created a custom domain in our Org and enabled Use the native browser for user authentication on iOS (To Enable advanced Authentication see [here](https://releasenotes.docs.salesforce.com/en-us/summer16/release-notes/rn_security_auth_mobile_browser.htm)). We are not doing any setup in client. After doing we added Url Types and we match the url scheme to "oauthRedirectURI" on bootconfig.json. but we are still getting exception "Invalid client credentials" are we missing any thing?

Can you please reopen the issue?

**Comment by Jas05** [comment]
Hello @trooper2013, @wmathurin
that is what we are doing, we created a custom domain in our Org and enabled Use the native browser for user authentication on iOS (To Enable advanced Authentication see [here](https://releasenotes.docs.salesforce.com/en-us/summer16/release-notes/rn_security_auth_mobile_browser.htm)). We are not doing any setup in client. After doing we added Url Types and we match the url scheme to "oauthRedirectURI" on bootconfig.json. but we are still getting exception "Invalid client credentials" are we missing any thing?

Can you please reopen the issue?

**Comment by trooper2013** [comment]
@Jas05  I just tried this very same scenario with an app created using forcehybrid. Pointed to a  domain that was configured for Advanced Auth. It works for me. 
- Make sure the connected app has a setting "Require Secret for Web Server Flow" is **checked off**.  Also ensure that a Domain is configured for Advanced Authentication.  
- Add the credentials uri scheme to your apps main plist in "URL Types -> URL Scheme".
- Add the credentials to the bootconfig.json (observe logs) and ensure that the correct client_id and redirect url are getting passed to auth endpoints.  
- Run app. Add the domain to the list using the gear icon on the loginview. You should now now see an alert that indicates that the app will use a "salesforece.com"  to authenticate.

**Comment by Jas05** [comment]
Hello @trooper2013, @wmathurin 
Thanks for your response

I am really puzzled here,
I am doing every thing you describe above. Let me break it down

**In Org:**
- We have setup a custom domain which works as expected. We are not using "Require Secret for Web Server Flow".
- Enabled "Use the native browser for user authentication on iOS" in Domain-Authentication Configuration.

**Hybrid App:**
Added "oauthRedirectURI" with value schema://success in bootconfig.json
Added UrlTypes section inside App info.plist:
```
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>schema</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>schema</string>
			</array>
		</dict>
	</array>
```
	
So when i run the app: 
It shows message "App" wants to use "salesforce.com" to sign - I click continue
I am shown with SalesForce login page where I enter my credentials.
In xcode logs it looks like it authenticated successfully.
But then it stuck on Loading screen. I can see an "invalid client crendentials" error on xcode logs.

Did I miss anything?

**Comment by trooper2013** [comment]
@Jas05 I am quite certain that this is probably something to do with the connected app configuration.  You may have set  **Require Secret for Web Server Flow" set to ON** or there could be some  missing access scopes. Have you used the same credentials successfully before?  

Try these steps but I believe it will yield the same result. 

1. Create a simple hybrid app using `forcehybrid`. 
2.  In `AppDelegate+SalesforceHybridSDK.m`. Setup the logger level to **debug** in the `sfsdk_swizzled_init` method.  
``[SFSDKHybridLogger setLogLevel:SFLogLevelDebug];``
3. Follow steps for advanced auth. i.e. setup bootconfig.json, url types..  
4. Run the app.
5. Look for log line "Initiating native browser flow with URL". 
6. You should see another Log line "beginTokenEndpointFlow"  Check the log to see that the **client_id and redirect url**  being used, are the ones you added.

You could try creating another Connected App and when you do so, please ensure that the   **Require Secret for Web Server Flow** set to **OFF** and the access scopes are setup correctly.

**Comment by Jas05** [comment]
Apologies @trooper2013, it turned out we had  **Require Secret for Web Server Flow**  checked on our ios connected app. Now i turned it off and everything is working as expected.
Many thanks for your help. Really appreciate.
