### ISSUE TITLE
7.0.0 SFJsonUtils WARNING error parsing json

### ISSUE THREAD

**Issue by XxScorpioxX** [forcedotcom/SalesforceMobileSDK-iOS#2770]
Please fill out the following details:

1. Version of Mobile SDK Used: 
**7.0.0**

2. Issue found in Native App or Hybrid App: 
**Native**

3. OS Version: 
**12.1.1**

4. Device: 
**iPad Air 2**

5. Steps to reproduce: 
**Doing any smart store query on a soup which has any row containing a field that is empty will cause the JSON parsing error. For example, result from line 1613 in SFSmartStore.m yielding a result string like "[["Jackson","William Jackson",,,,,"(404) 4444444",]]". This is a more egregious case with a row missing most of the data, but if there is even one empty field, the JSON parsing fails. Seems that the queryAsString function is not handling nil field values well.**

6. Actual behavior:
**queryWithQuerySpec function should returns back nil**

7. Expected Behavior: 
**queryWithQuerySpec function should return back a dictionary of results**

8. Error Log: 
**[SFSDK] CLASS: SFJsonUtils WARNING error parsing json: Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 2." UserInfo={NSDebugDescription=Invalid value around character 2.}**

**Comment by trooper2013** [comment]
@XxScorpioxX how are the values getting written. NSJSONSerialization will fail if it finds empty values that are not nil `e.g. [["Jackson","William Jackson",null,null,null,null,"(404) 4444444"]]` something like this would work but result in 7 records.

**Comment by XxScorpioxX** [comment]
@trooper2013 in 6.2, I believe the null indeed shows, but with 7.0 it is just empty, as in ",," two or more commas, no idea why the change.

**Comment by wmathurin** [comment]
Thanks for reporting this regression.
It's getting fixed in dev and will be part of the next release.
See https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2771

**Comment by XxScorpioxX** [comment]
Thanks for the info @wmathurin!
