### ISSUE TITLE
Time out Alert not working on Native IOS SDK

### ISSUE THREAD

**Issue by kravuri1987** [forcedotcom/SalesforceMobileSDK-iOS#2772]
1. Version of Mobile SDK Used: SDK version 216
2. Issue found in Native App or Hybrid App: Native app
3. OS Version: 12.0.1
4. Device: iPhone 8
5. Steps to reproduce:

1. In 'Chat Buttons and Automated Invitations' ,configure 'Customer Time-Out (seconds)' to 90 seconds
2. Initiate chat on iOS device
3. Chat got routed to agent
4. Agent send message to customer
5. Customer leave the app open in the foreground for 5 mins
6. leave the app in the background for 5 mins

1. Actual behavior: Chat session is not terminated after 5 mins of inactivity
2. Expected Behavior: Chat session is termination alert after customer is inactive for 60 secs from Agent's last reply  and terminate the chat after 90secs.
3. Error Log:

**Comment by trooper2013** [comment]
@kravuri1987 This is not the right forum to post issues with the SnapIns SDK. Mobile SDK is a different product.
