### ISSUE TITLE
Dismissing logout screen if displayed.

### ISSUE THREAD

**Issue by mkambale** [forcedotcom/SalesforceMobileSDK-iOS#2780]
Please fill out the following details:

1. Version of Mobile SDK Used:  7.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 11.0 and 12.0
4. Device: iPhone

In our app, after user decides to logout, we used to handle the logout call back and land the user to custom viewcontroller where we have some info and login button.

postLogout {
                //Take user to custom viewcontroller
            }
This worked well till SDK 6.4.

With SDK 7.0, we dont have above option and on logout, user lands on SF login page, which we dont want to happen. Can some on help us to have the control over landing the user to custom view controller instead of login page??

**Comment by trooper2013** [comment]
@mkambale You can do the same by using one of the following methods 
1. Registering   a block to be executed in the following to listen in for User Notifications (logout or user switch) 
```
AuthHelper.registerBlock(forCurrentUserChangeNotifications: {
               // handle logout or user switch scenarios here 
        })
```
2. Listen in for only Logout Notifications 
```
AuthHelper.registerBlock(forLogoutNotifications: {
            // handle logout Notifications
  })
```

**Comment by mkambale** [comment]
Thanks @trooper2013 for helping me out.
I am also curious to know if we have any replacement for dismissAuthViewControllerIfPresent() API?
OR any other way to achive same functionality?

**Comment by trooper2013** [comment]
try 
```
SFSDKWindowManager.shared().authWindow.dismissWindow(animated: false) {
            // called when dismiss is complete. Make the  application window active.
}
```
