### ISSUE TITLE
Salesforce SDK issue - Apple is rejecting app store submission due to 2 permissions required in SF SDK

### ISSUE THREAD

**Issue by geekandt** [forcedotcom/SalesforceMobileSDK-iOS#2792]
Please fill out the following details:

1. Version of Mobile SDK Used: 
ServiceSDK (210.0.0)

2. Issue found in Native App or Hybrid App: 
Hybrid App

3. OS Version: 
iOS 10 and above

4. Device:
All devices

5. Steps to reproduce:
We have a Salesforce SDK issue, which we need assistance.

In short, our main issue is that Apple has rejected our app store submission due to 2 permissions required in SF SDK. This will prevent us from incorporating the most recent versions of the Salesforce ServiceSDK. It held up our release schedule yesterday, but to get around this, we had to revert back to a lower SDK version.

Below are the detailed notes on the issue.

The latest SalesForce ServiceSDK (218.0.0) requires 2 permissions from users:

* The permission to use the microphone on the device

* In particular: the ServiceCore framework is using AVAudioSession

* The permission to use Speech recognizer feature of the phone

* In particular: the ServiceCore framework is using SFSpeechRecognizer
  Currently, our app does not use these permissions for any functionalities in the app, and our build got rejected by Apple because in order to have these permissions. We have to deliberately ask users to grant the app the permits.

Our previous build did not encounter this issue because the old ServiceSDK (210.0.0) did not require these permissions.

So our question is: Is it possible to exclude the functionalities which require those permissions out of the latest ServiceSDK (218.0.0) or ServiceCore framework in particular?
We're not using those functionalities anywhere in our app and want to avoid prompting a user for these permissions.

6. Actual behavior:
Our app is rejected.

7. Expected Behavior:
Our app is approved.

8. Error Log:
N/A

Email: loregge.m.kandt@accenture.com

**Comment by brandonpage** [comment]
Hello, please create an issue for this on the Service SDK's page here: https://github.com/forcedotcom/ServiceSDK-iOS

Thanks
