### ISSUE TITLE
Possible vulnerability flagged by security scanner: const_key

### ISSUE THREAD

**Issue by IshwarKaushik** [forcedotcom/SalesforceMobileSDK-iOS#2799]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.0.0
2. Issue found in Native App or Hybrid App: Both
3. OS Version: iOS
4. Device: NA
5. Steps to reproduce: NA
6. Actual behavior: NA
7. Expected Behavior: NA
8. Error Log: NA

We use Salesforce SDK iOS for our development needs. During our routine security scan on our codebase, our security scanner highlighted the below piece of code within Salesforce SDK as a possible security issue under category "Cryptographic Key Replacement - High".

Code\Pods\SmartStore\libs\SmartStore\SmartStore\Classes\SFSmartStoreUpgrade.m, line 38
static const char *const_key = "H347xxxxxxxxxxxxxxxxxxxxxxx";   (*note: actual key is masked in this posting for security reasons).

Please let me know about possible remediation of this issue and if anything needs to be done from my side.

Thank you so much for reading.

**Comment by wmathurin** [comment]
That key was used in early version of the Mobile SDK (5+ years ago). The code is there for facilitate migration. For an overview of security in the Mobile SDK / Salesforce App - see https://resources.docs.salesforce.com/sfdc/pdf/salesforce1_mobile_security.pdf.
