### ISSUE TITLE
How to find out that syncUp records failed

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#2831]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.0.0.
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 12.2
4. Device: iOS Simulator
5. Steps to reproduce: Sync up a record that fails a validation rule in SF
6. Actual behavior: Sync succeeds with status `DONE`; the `syncState.error` is empty
7. Expected Behavior: There is some way to know that certain records failed
8. Error Log: N/A

I have created a `SyncUpTarget`. I then try to sync a soup entry that has some invalid data.
The server responds with error 400, and the `SFSmartSyncSyncManager` updated the `__last_error__` in my  soup in `resumeSyncUpOneEntry:` method.

However, the `updateBlock:` of `syncUpWithTarget:` does not contain any info about some records failing.

How can i be notified that the sync has actually failed without having to go and query the soup myself? it seems redundant to have to do this (especially consider the case where i have some entities in the soup locally and now i am syncing them later on... what should the user do when they are many screens away?)

**Comment by wmathurin** [comment]
It's by design. There could be many records that failed and we wanted to keep the sync updates more or less constant in sizes. A typical app has some search/list/detail screens, those are better places to surface the errors encountered (especially if fixing the error involves further editing the record).
