### ISSUE TITLE
Multi-level lookup sync up target

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#2835]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.0.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 12.2
4. Device: iOS Simulator, iPad mini
5. Steps to reproduce: N/A
6. Actual behavior: N/A
7. Expected Behavior: N/A
8. Error Log: N/A

I read the SDK documentation and it specifically states on page 290:
`Salesforce supports up to 25 lookup fields per object. Lookup relationships can be multiple layers deep.`

I am using a scenario where the user wants to create multiple related records fully offline and then sync them up to the server.

Now i have a setup like so with standard `Account` and `Contact` objects:

1. `Account` - `Id` (standard)
2. `Contact` - `AccountId` (standard)
3. `Contact` - `customRelatedContact__c` (a lookup from one contact to the other)

how can i create the `ParentChildrenSyncDownTarget` in such a way that SmartSync figures out that it need to sync objects in order 1-2-3?

Additionally, i have a similar setup with another object where a tree would:

1. `Account` - `Id` (standard)
2. `Contact` - `AccountId` (standard)
3. `Contact` - `customRelatedContact__c`
4. `Task` - `WhatId` (Account-Id) - `WhoId` (Contact-Id)

In this case i need the sync to be in the order as above and all local ids to be replaced and linked on the server.

**Comment by wmathurin** [comment]
ParentChildrenSyncDownTarget does not support that scenario. You could however create your own custom sync down target (maybe subclassing ParentChildrenSyncDownTarget) to support that scenario.

**Comment by az-oolloow** [comment]
In Case somebody hits this issue, this is how I solved it:

Since `Id` is not synced up when `kSyncTargetCreated` is `1`, i create all local records with an id that is a datetime stamp and a prefix, e.g. `local_<<DateTimeHere>>`. (note: i suggest using a GUID or sth instead of the word `local`)
Thus, if my record depends on something not yet synced up, there would be multiple `local_` strings in the body. I then subclass the `SyncUpTarget`:
1) in `getDirtyRecordIds` i specify that we only sync records matching soupname where `kSyncTargetLocal = 1` AND those that have just one `local_` in the `soup` column (can use sqlite for that)
2) In `createOnServer` i set the original id to the record being created on the server now
3) Then in BOTH `saveRecordToLocalStoreWithLastError` and `cleanAndSaveInLocalStore` i gotta update dependent records - the way i do it is query all soups matching the original id, and just replacing the matching values in all values in the `NSDictionary` returned by `retrieveEntries`. 

Lastly, when i decide what to sync up first, i go through all soups finding the one where the target returns records with just one `local_` in the `soup` column. Then i repeat this process until no soups contain `kSyncTargetLocal = 1`. 

This process is not amazingly performant if a user creates hundreds of records, but it guarantees that we always resolve the entire chain, no matter if there are 1, 2 or 100 interdependent records created locally. And we don't even need to know in our code that they are related (which is what i disliked about the concept of `ParentChildrenSyncDownTarget`)

**Comment by wmathurin** [comment]
We will probably not build a generic solution for that. However like you described above, it is possible to write a custom target to link together locally created dependent objects.
