### ISSUE TITLE
Bug - FMResultSet is not closed if soup is NULL

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#2837]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.0.0
2. Issue found in Native App or Hybrid App: Native APP
3. OS Version:12.2
4. Device: iPad mini
5. Steps to reproduce:
Using Swift, create a dictionary with an object not representable using `SFJsonUtils`, e.g.

```
struct MyStruct {
 var prop: String?
}

var entry = Dictionary<String, Any>()
var attrs = Dictionary<String, String>()
attrs["type"] = "Account"
 entry["attributes"] = attrs
entry["MyProp"] = MyStruct()
SmartStore.shared(withName: SmartStore.defaultStoreName)?.upsert(entries: [entry], forSoupNamed: "Account")

// After this the soup is NULL in the db ( i would argue even this is wrong but whatever)

// Now try to retrieve the entity by soup id, e.g. like so
SmartStore.shared(withName: SmartStore.defaultStoreName)?.retrieve(usingSoupEntryIds: [id], fromSoupNamed: "Account")
```

Here, there is actually an error being thrown but it is silently ignored on this line:
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SmartStore/SmartStore/Classes/SFSmartStore.m#L1773

(which IMO is also wrong), the error says
```
*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil 
```

This is thrown from here:
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SmartStore/SmartStore/Classes/SFSmartStore.m#L1809

Now because there is no `@try..@catch` implementation, the `[frs close];` is never hit.

So if we fetch our records with empty soups a few times, we get quite a lot of empty results set lingering, and FMDatabase complains like so:
Warning: there is at least one open result set around after performing [FMDatabaseQueue inDatabase:]

6. Actual behavior:
FMDB logs errors, result sets leak
7. Expected Behavior:
* Errors are logged
* Null soup is never saved to the DB
* If null soup is found on read, we do not try to insert nils into result array

8. Error Log:
Out of the box, the only thing you would see is:
```
[SmartStore] CLASS: SF_FMDatabaseQueue Warning: there is at least one open result set around after performing [FMDatabaseQueue inDatabase:]
```

I ended up just forking the SDK because there are a couple of issues apart from this one, but i think this is important enough to address in the base.

Let me know if you have any questions, happy to help!

**Comment by az-oolloow** [comment]
A side effect of this is that SyncTarget crashes because on this line here:
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SmartSync/SmartSync/Classes/Target/SFSyncTarget.m#L122

The code expects there to be exactly one entry in the dictionary.

**Comment by trooper2013** [comment]
@az-oolloow The soup should be first registered using registerSoup. You should decide what your  indexes should  be e.g. 
```  
var soupIndex = ["path": "MyProp", "type": "string"] 
SmartStore.shared(withName: SmartStore.defaultStoreName)?.registerSoup(withName: "Account", withIndices:  SoupIndex.asArraySoupIndexes([soupIndex]))

```
 
 Fundamentally the issue arises from the fact that you are trying to serialize a struct 
```
struct MyStruct {
 var prop: String?
}
```
The entries for SmartStore can be basic primitive types or nested name:value pairs as 

```
entry["type"] = "Account"
entry["attribute"] = ["a":"a","b":"b","c":["z":"z"]]
entry["MyProp"] = "Hello"
```

**Comment by az-oolloow** [comment]
@trooper2013 i am sorry, why is this closed?

Of course i registered the soup, i thought that was obvious.

The reason i am adding the struct is because that is what SmartSync does essentially - if you try to sync down a nested object, for example:

`SELECT ShippingAddress, Owner.Name FROM Account` - in this case the `soup` property contains 2 nested properties.

Now there is no way to create an index for it (at least i didnt find one), so i simply select it using `json_extract` from `soup` column when i display it on the device.

Now i need to create a local entry but it should also work in the SAME display code. Of course i need to put a nested object in! I did so using an NSDictionary once i realised the `struct` and `class` don't work.

But none of this is really documented and i would argue that the fact that the error is not even logged and `nil` is passed in it's place is definitely a bug? @wmathurin
