### ISSUE TITLE
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]

### ISSUE THREAD

**Issue by weitieda** [forcedotcom/SalesforceMobileSDK-iOS#2840]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.0.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 12.2
4. Device: iPhone Xr
5. Steps to reproduce: Every time launch the app
6. Actual behavior:
7. Expected Behavior:
8. Error Log:
2019-04-25 17:31:26.809913-0400 <PROJECT_NNAME>[35108:6436930] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 35108, TID: 6436930, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   libobjc.A.dylib                     0x00000001873236f4 <redacted> + 56
5   CoreMotion                          0x000000018da6d638 CoreMotion + 292408
6   CoreMotion                          0x000000018da6db68 CoreMotion + 293736
7   CoreMotion                          0x000000018da6da78 CoreMotion + 293496
8   CoreMotion                          0x000000018da9b8a8 CoreMotion + 481448
9   CoreMotion                          0x000000018da9b8ec CoreMotion + 481516
10  CoreFoundation                      0x00000001880af78c <redacted> + 28
11  CoreFoundation                      0x00000001880af074 <redacted> + 276
12  CoreFoundation                      0x00000001880aa368 <redacted> + 2276
13  CoreFoundation                      0x00000001880a9764 CFRunLoopRunSpecific + 452
14  CoreFoundation                      0x00000001880aa498 CFRunLoopRun + 84
15  CoreMotion                          0x000000018da9b280 CoreMotion + 479872
16  libsystem_pthread.dylib             0x0000000187d29920 <redacted> + 132
17  libsystem_pthread.dylib             0x0000000187d2987c _pthread_start + 48
18  libsystem_pthread.dylib             0x0000000187d31dcc thread_start + 4

Hi,

I'm having a thread warning every time launch my app build on top of SalesForce Mobile SDK.

The app will still run but will get stuck on the launching screen for few more seconds.

**Comment by wmathurin** [comment]
I think the problem is in your application code.
Make sure to call that make UI changes are invoked from the main thread by wrapping them in:
```
DispatchQueue.main.async {
    //Do UI Code here. 
}
```
