### ISSUE TITLE
Public API for clearing cache

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#2852]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 12.2
4. Device: iPhone X
5. Steps to reproduce: Try to run a few hundred thousand queries on smartStore
6. Actual behavior: Memory usage grows
7. Expected Behavior: There is an API to clear the cache
8. Error Log: N/A

Internal header for SFSmartStore has a method `- (void)removeFromCache:(NSString*) soupName`

Firstly, the method is a bit misleading in the naming (if you're using SmartQuery sql specs with JOINs all queries with this soup name for another soup are removed)

However, and more importantly, i have an app that is meant to be running for long periods of time. The queries run contain unique ids for data that users operate on, so the caching mechanism treats those as unique queries. Eventually i end up with lots of strings sitting in this 'cache' that will never be used :(

Is it possible at all for this method or some equivalent to be exposed in the official distribution? Or maybe i can just disable this caching mechanism?

**Comment by wmathurin** [comment]
Thank you for your enhancement request. We should probably revisit those caches, not have them grow indefinitely but instead have them drop least recent used items.

**Comment by wmathurin** [comment]
Issue being addressed with: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2909
