### ISSUE TITLE
Get notified when an automatic log out occurrs

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#2855]
When there is an issue refreshing the token, the SDK logs the user out with `Invalid grant error received, triggering logout` log (see here: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/v7.0.0/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/RestAPI/SFRestAPI.m#L374)

Is there any way for the consuming app to get notified that this occurred? e.g. NSNotification being sent or something so that the entire app state can be updated?

**Comment by trooper2013** [comment]
@az-oolloow We do fire logout notifications. 
```
NSNotificationName kSFNotificationUserWillLogout = @"SFNotificationUserWillLogout";
NSNotificationName kSFNotificationUserDidLogout  = @"SFNotificationUserDidLogout";
```
You could add a listener to handle these notifications with the NotificationCenter. The UserInfo object will have some data w.r.t the logout. 

Alternatively you could also register a block to with AuthHelper if you do not care about the UserInfo object 

```
       // FOR any changes related to user, switch user or logout 
        AuthHelper.registerBlock(forCurrentUserChangeNotifications: {
             
        })
        
        // OR only for  logout 
        AuthHelper.registerBlock(forLogoutNotifications: {
            
        })
```

**Comment by az-oolloow** [comment]
Thank you @trooper2013 this is, indeed, sent!
