### ISSUE TITLE
SF push notification is not working for auto responses when a case is created or a case is closed 

### ISSUE THREAD

**Issue by geekandt** [forcedotcom/SalesforceMobileSDK-iOS#2856]
Please fill out the following details:

1. Version of Mobile SDK Used: 
ServiceSDK (218.0.0)
2. Issue found in Native App or Hybrid App:
Hybrid App
3. OS Version:
iOS 10 and above
4. Device:
All Devices
5. Steps to reproduce:
Create Case through the app.
6. Actual behavior:
Push notifications is not working on the auto responses when a case is created/closed.
It is only working when there is an adhoc reply from Salesforce to the app.

7. Expected Behavior:
Push notifications is working on the auto responses when a case is created/closed and when there is an adhoc reply from Salesforce to the app.

8. Error Log:
no error logs

When a case is created using our app, there is an auto response that will be sent to the user in the app. This auto response must also have a push notification.
But the push notification is not working for the auto response.

Though the adhoc reply from Salesforce to app has push notifications.

Email: loregge.m.kandt@accenture.com

**Comment by trooper2013** [comment]
Report  the issue for this on the Service SDK.  https://github.com/forcedotcom/ServiceSDK-iOS
