### ISSUE TITLE
Cleanup resync ghosts improvement question

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#2857]
Currently cleaning resync ghosts runs the same query again, fetching only ID, and then removes local entries not present in the server response. Once the server table reaches a few thousand records this becomes prohibitively slow.

Instead, we can call the `queryAll` api (https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_queryall.htm) providing `IsDeleted` or `IsArchived` flags and the rest of the original Soql, and then delete all records with ids matching returned. This means that we are not pulling down ALL of the records.

I wanted to ask if there is something i am missing as to why the SDK does not implement the above approach?

Based on my testing, this api also supports `LastModifiedDate` meaning we can get exactly what has been deleted since the last sync?

**Comment by wmathurin** [comment]
That approach won't cover all cases:
- isDeleted only returns deleted record that are in the recycle bin, once they have been "hard" deleted, they won't be returned anymore.
- some "ghosts" could be be record that still exist but no longer match the critieria of your sync down query or maybe are no longer visible to the users.
To cover all cases, without further server support, you either have to run a full sync or run our clean ghosts method (which basically does a full sync but only fetches the id field).
