### ISSUE TITLE
SmartSync - floating point precision values sent to the server when decimals stored in the soup

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#2864]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.0.0
2. Issue found in Native App or Hybrid App: Native app
3. OS Version: 12.2
4. Device: iPad Pro 11"
5. Steps to reproduce: 
* Place a Swift Decimal (or NSDecimalNumber) into the soup dictionary and upsert
* Perform a sync up
6. Actual behavior:
In the soup (using the inspector) we can clearly see the decimal values are stored, e.g. 5.1:
![Screen Shot 2019-05-15 at 2 12 00 pm](https://user-images.githubusercontent.com/47766072/57748250-7a877c80-771c-11e9-8a35-935e43fec084.png)

In the payload being sent to the server it seems some kind of floating point precision is used resulting in incorrect data being posted up:
![Screen Shot 2019-05-15 at 2 13 24 pm](https://user-images.githubusercontent.com/47766072/57748259-82472100-771c-11e9-9df8-41558793dfa3.png)

7. Expected Behavior: The values stored in the soup are sent up. That is, if the user stored FP data -> FP data should be sent up, and if the user stored Decimal -> that should be sent up.

8. Error Log:
N/A

**Comment by trooper2013** [comment]
@az-oolloow We will look into this. I think it is caused by NSJSONSerialization that is serializing floats to doubles.

**Comment by az-oolloow** [comment]
@trooper2013 this may help: https://stackoverflow.com/questions/45420375/specify-number-of-decimals-when-serializing-currencies-with-jsonserialization

**Comment by az-oolloow** [comment]
Any updates on this? Unfortunately it is affecting us. I traced it down to `setCustomRequestBodyDictionary` method. Using the link i provided above i can get my custom payload looking correct, however i'd need to then re-implement that logic in the SF SDK and i'd like to avoid that, if possible.

**Comment by JimBTek** [comment]
FWIW, We are not experiencing this with the standard sync up targets in iOS with React Native. We send a lot of decimals out to 6 places.

**Comment by wmathurin** [comment]
The problem comes from the way JSONDecoder handles decimal numbers.
For more information: https://blog.skagedal.tech/2017/12/30/decimal-decoding.html
Their recommendation: "You might prefer to use a Double rather than a Decimal as the decoded type even if you want the end result to be a Decimal, and do the conversion yourself, possibly via a String".

**Comment by az-oolloow** [comment]
@wmathurin so what is the recommendation for using the SF SDK? 
I am not using JSONDecoder() here, i am just creating a `NSMutableDictionary` and adding a Swift `Decimal` into it, and then calling SmartStore methods to upsert it, and then SmartSync to sync up.

**Comment by wmathurin** [comment]
No but SmartStore is using it.

**Comment by az-oolloow** [comment]
@wmathurin Ok, so are you saying we should only put `Double` into the dictionary before `upsert`?

**Comment by wmathurin** [comment]
Yep.
