### ISSUE TITLE
SmartSync/SFRestClient - timeout interval

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#2869]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.0.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: iOS 12.2
4. Device: iPad mini
5. Steps to reproduce: 
Have requests take longer than 60 seconds on the SF server side
6. Actual behavior:
SmartSync timeouts
7. Expected Behavior:
Developers can configure the timeout interval
8. Error Log: N/A

Not sure why, probably due to the recent outages, today our SF instance is painfully slow when communicating with the rest API. Because of that, i get a lot of timeouts trying to sync.

It seems that underneath it all, the requests are simple `NSURLRequest`, so it would be nice if the timeout was exposed both in SFRequest classes and in SyncTarget ones.

**Comment by trooper2013** [comment]
@az-oolloow  You should be able to change the timeout setting for the NSURLSession using the [SFNetwork](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/dev/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/RestAPI/SFNetwork.h).  You can even customize the creation of NSURLSessions if you were to implement the SFNetworkManaging protocol. However this change will apply for all requests. We are planning on adding the ability to change timeout settings in the SFRestRequest in the future releases of the SDK.

**Comment by wmathurin** [comment]
Closing issue since a work around was provided.
