### ISSUE TITLE
Execute insert from select sqlite

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#2873]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.0.0
2. Issue found in Native App or Hybrid App: Native app
3. OS Version: 12.2
4. Device: iPad mini
5. Steps to reproduce: N/A
6. Actual behavior: N/A
7. Expected Behavior: N/A
8. Error Log: N/A

My use case is that i have some entities in SF that are then applicable to the entire account hierarchy. Meaning that from just 5-6 records on the server i need to then run a nested lookup to find parents of parents of parents etc. which results in hundreds of thousands of records.

With the current design of the SDK, i can do it locally in a select statement, but that select runs for some 6-7 seconds. Instead of doing that, i want to run this select AFTER the sync and then insert the rows into another soup so i can query them on demand as required. The problem is, the only way to insert things is to select them first and then run upsert which all goes through JSON serialization and ends up using huge amounts of RAM.

For the time being i forked the SDK and exposed the necessary methods, but it would be ideal if there was a way to run `INSERT INTO... SELECT` statements with the SDK.

**Comment by wmathurin** [comment]
We have a story in our backlog to make patching an entry in SmartStore a lot cheaper (basically avoiding having to fetch / save back the entire entry). Stay tuned for updates.

**Comment by az-oolloow** [comment]
@wmathurin now that it's been a year since this was raised, are there any updates? i couldn't find anything relevant in 8.0/8.1 release notes

**Comment by wmathurin** [comment]
Nothing has been done on that front yet / no plans to do anything in the foreseeable future.

**Comment by wmathurin** [comment]
We do not plan to build that capability: insertions require java/objective-c code to run in most cases. So the implementation of that capability would probably not run any faster than the manual approach you currently use. It would however require parsing SQL which we currently avoid (SmartSQL queries are simply converted to SQL using some regular expressions).

**Comment by az-oolloow** [comment]
@wmathurin Just to give you an idea, the way we do it now was to fork the SDK, expose the FMDB, and remove the limitations on only parsing `SELECT` SmartSQL so that we can run a `UPDATE {Soup1} FROM (SELECT {Soup2)`. 

The scenarios where we use this include downloading some entities from SF, and then mixing them together, at scale (think 50-100K rows) which is just too slow to do in a simple `JOIN` query, so we have a 'preparing data' phase for the user where they can wait just once and get the full set in a third table.

Official support from SF SDK would mean we (and others needing similar capability) could stop using SDK forks, as this slows down new version adoption, that's all.

I understand that you might not be interested in doing this, but it is as simple as removing the `SELECT only` checks in the `convertSmartSql` method and then putting some fat disclaimer of 'you're doing this at your own risk' somewhere...
