### ISSUE TITLE
Is version 7.1 GA or preview?

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#2874]
According to documentation linked in Readme.MD, e.g. here:

we read: https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/migration_all_70_71.htm

```
Note: This release is in preview. 
Features described here don’t become generally available until the latest general availability date that Salesforce announces for this release. 
Before then, and where features are noted as beta, pilot, or developer preview, we can’t guarantee general availability within any particular time frame or at all. 
Make your purchase decisions only on the basis of generally available products and features.
```

Is version 7.1 now officially released or still preview?

**Comment by wmathurin** [comment]
It's GA.
The "Note: This release is in preview." is appearing on every page of documentation because of an issue with the document publishing process and should be fixed soon.
