### ISSUE TITLE
Bug in the new SOQL mutation in 7.1 - order_by token inserted into SOQL

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#2875]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 12.2
4. Device: iPad mini
5. Steps to reproduce:

Create and execute a soqlsyncdowntarget like so:
```
let target = SoqlSyncDownTarget(dict: [kSFSyncTargetIdFieldNameKey: kId,
                                                 kSFSyncTargetModificationDateFieldNameKey: kLastModifiedDate,
                                                 "query": "select LastModifiedDate,Id, OwnerId, WhatId, Status, Subject, Priority, Description, ActivityDate, WhoId from Task where (OwnerId = '<<<UserIDHERE>>>' OR (What.Type = 'Account' AND (Account.OwnerId = '<<<UserIDHERE>>>' OR Account.Owner.ManagerId = '<<<UserIDHERE>>>'))) AND (LastModifiedDate > 2019-05-15T07:52:27.000Z )"])
```
When sync down runs, the request contains the following trail:
` order_by LastModifiedDate order by LastModifiedDate`

In 7.0 this worked just fine.

6. Actual behavior:
When sync down runs, the request contains the following trail:
` order_by LastModifiedDate order by LastModifiedDate`
7. Expected Behavior:
`order_by` is not added. this seems to be an issue in the new `SFSDKSoqlMutator`
8. Error Log:
```
[{"message":"\n(LastModifiedDate > 2019-05-15T07:52:27.000Z ) order_by LastModifiedDate order\n                                               ^\nERROR at Row:1:Column:328\nunexpected token: 'order_by'","errorCode":"MALFORMED_QUERY"}]
```

Also, it is really unclear why there needs to always be an `order by` in the sync. why can't we disable it? or just have a query unordered? why does it matter?

**Comment by az-oolloow** [comment]
I tried adding the Order by at the end myself, but it could be a regex issue in the mutator. for now i will just remove that chunk that adds mandatory order by from sync down target in my fork, but it seems important enough to address. Also, looking at UTs written for the class they seem to err on the side of being pretty simple queries.

**Comment by wmathurin** [comment]
Thanks for bringing up the issue. The SOQL mutator is brittle and needs to be improved and you are right that if you don't put the order by, then you will end up with the query you want.

**Comment by wmathurin** [comment]
The bug is getting fixed with:
https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1927
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2895

**Comment by araujoraphael** [comment]
Thanks for taking a look into this. Was this fix released already?

**Comment by wmathurin** [comment]
Yes it's in 7.1.2 (released a month ago).

**Comment by araujoraphael** [comment]
Oh, thanks @wmathurin !
