### ISSUE TITLE
Run unit tests in 7.1

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#2876]
I tried running unit tests in SDK 7.1 and i get an error saying this file is missing
```
/Users/myUserName/wherever/SalesforceMobileSDK-iOS/shared/test/test_credentials.json:
```

What is the structure of this file so i can add my own to run unit tests?

**Comment by wmathurin** [comment]
Look at https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/shared/test/test_credentials.json.sample to see the expected fields.
An easy way to generate it, is to run RestAPIExplorer, log in, click on the top right icon, scroll down, choose export credentials. Then paste to your test_credentials.json file.
