### ISSUE TITLE
Live chat notifications received when app in background but live chat even not started chat

### ISSUE THREAD

**Issue by AndyKD** [forcedotcom/SalesforceMobileSDK-iOS#2879]
. Version of Mobile SDK Used: 1.21.0(#1)
2. Issue found in Native App or Hybrid App: - Native App
3. OS Version:
4. Device: Iphone 7
5. Steps to reproduce:
1.Launch app.

2.Login with valid credentials.

3.Go to Menu bar.

4.Go to "Support" tab.

5.Register product.

6.Put the app in background.

6. Actual behavior: - After sometime , Live Chat notification comes when user return to the app , Chat support was disabled.
 
7. Expected Behavior: -  Live notification should come only when Chat gent is online.
8. Error Log: 

![LiveChat](https://user-images.githubusercontent.com/6467643/58420376-bde1d380-80aa-11e9-86b5-4b7374cbdb34.png)

**Comment by bhariharan** [comment]
@AndyKD This is the not the right forum to report issues for the `SnapIns` product. Please report them [here](https://github.com/forcedotcom/ServiceSDK-iOS).
