### ISSUE TITLE
The number of instances of RootViewController keeps increasing every time a user logs in.

### ISSUE THREAD

**Issue by hmuronaka** [forcedotcom/SalesforceMobileSDK-iOS#2883]
Please fill out the following details:
1. Version of Mobile SDK Used:  7.1.0
2. Issue found in Native App or Hybrid App:  Native
3. OS Version:   iOS 12.2
4. Device:  iPhone
5. Steps to reproduce:

- 1. A user logs into the RestExplore app.
- 2. The app shows RootViewController.(the number of RootViewController instance is 1, I 
  checked by memory graph of Xcode.)
- 3. The user logs out the app.
- 4. The app shows the login screen.
- 5. The user logs into RestExplore again.
- 6. The app shows RootViewController.(the number of RootViewControllers instance is 2)
- 7. The number of instances of RootViewController keeps increasing every time the user logs in.

6. Actual behavior:
The number of instances of RootViewController keeps increasing every time a user logs in.

7. Expected Behavior:
an instance of RootViewController is destroyed when a user logs out.

I implemented login-flow of my app by reference to the RestExplorer in SalesforceMobileSDK.
But an instance of my app RootViewController isn’t  destroyed when a user logs in. The instance of RestExplorer isn't destroyed either.
(I confirmed this with SFSDKWindowContainer by checking the related RootViewController with the memory graph tool in Xcode.)

How do I  fix it in RestExplorer?

Now, to avoid the problem, I changed RestExplorer’s code like below.

    func setupRootViewController()
    {
        SFSDKWindowManager.shared().mainWindow.viewController = nil // inserted this line.
        let rootVC = RootViewController(nibName: nil, bundle: nil)
        let navVC = UINavigationController(rootViewController: rootVC)
        self.window!.rootViewController = navVC
    }

Or  is the intended behavior to reuse SFSDKWindowManager.shared().mainWindow.viewController when a user logs back in?

**Comment by wmathurin** [comment]
We will take a look thanks.

**Comment by wmathurin** [comment]
Fixed with https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2940
