### ISSUE TITLE
Calling cleanResyncGhosts causes subseqent SyncAlreadyRunningError

### ISSUE THREAD

**Issue by TerryBrett** [forcedotcom/SalesforceMobileSDK-iOS#2884]
1. Version of Mobile SDK Used: **7.1.0**
2. Issue found in Native App or Hybrid App: **Native**
3. OS Version: **iOS 12.2**
4. Device: **iPad**

5. Steps to reproduce:
- Call SyncManager.reSync(named: "MySyncDown")
- On completion, call SyncManager.cleanResyncGhosts(forName: "MySyncDown")
- On completion, call SyncManager.reSync(named: "MySyncDown") (***error**)

6. Actual behavior:
First reSync and cleanResyncGhosts succeeds.
Second reSync fails with error

7. Expected Behavior:
8. Error Log:
SFSmartSyncSyncManager SyncAlreadyRunningError: sync 1 is still running

**NOTE:**
It appears that the SFSyncTask init() method calls 
        [self.syncManager addToActiveSyncs:self];
and that in it's updateSync() method it calls
        [self.syncManager removeFromActiveSyncs:self];
which is the only two calls that change the active syncs list.

However, the SFCleanSyncGhostsTask overrides updateSync() and the removeFromActiveSyncs() call is never made.

**Comment by wmathurin** [comment]
Thanks for reporting the issue. The fix is on this PR: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2887
