### ISSUE TITLE
TDX19 - ContentVersion does not return binary data for image files or any content file

### ISSUE THREAD

**Issue by iandrosov** [forcedotcom/SalesforceMobileSDK-iOS#2885]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.1
2. Issue found in Native App or Hybrid App: Native Swift App
3. OS Version: MacOS 10.14.5
4. Device: iPhone X iOS 
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log: Null exception unwrapping data in response (no data return in ContentVersion

Hello
At TDX19 this week I attempted use 7.1 SDK to get a File stored in Salesforce ContentVersion with all the methods I used before in prior to Summer19 release that used to work no longer working.
Here is how I try to get/download Files data for image or PDF file and always got null data in responses.
1. I locate related file IDs linked to Contact or Account record using this SOQL:
SELECT Id,ContentDocumentId,LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId='0034P00002TPrwAQAT'

2. Ince I get Document id this SOQL should return data in VersionData: SELECT Id, VersionData, ContentDocumentId, ContentUrl,
         CreatedDate,CreatedById,LastModifiedDate,Description,
        FileExtension,FileType,IsLatest,IsMajorVersion,PublishStatus,
        ContentSize,TagCsv,Title,VersionNumber
        FROM ContentVersion
        WHERE ContentDocumentId =: documentId
        AND IsLatest = TRUE
This in Mobile SDK does . not seem to work, the metadata is OK from REST call . but binary data seem not usable cannot convert it to Image or any useful data.

NOw my attempts to actually get ContentVersion data to downlload local on my iPhone and display as images of PDF files. (Note I have done this before in 2014-2016 time on real production app but now version differ)

1. Using sheperd undocumented URL returns response but no binary data anymore: https://na132.salesforce.com/sfc/servlet.shepherd/version/download/c0684P0000075lmHQAQ

2. TRy to query as data by URL also data resoponse is null data: https://na132.lightning.force.com/services/data/v45.0/sobjects/ContentVersion/0684P0000075lmHQAQ/VersionData

3. Manually shared this file doc as public with URL: https://na132.salesforce.com/sfc/p/4P000000hVnY/a/4P0000004cgd/CZJqiuvzXnMyB5MGVVYuCBx6toWiVr9UfQvQZ3zhTUg
This only works on Salesforce inside of the browser web app and actual page show preview with control to download file data no direct data download

Using this code did not work:
let strURL = "https://na132.salesforce.com/sfc/p/4P000000hVnY/a/4P0000004cgd/CZJqiuvzXnMyB5MGVVYuCBx6toWiVr9UfQvQZ3zhTUg"
        let url = URL(string: strURL)
        let data = try? Data(contentsOf: url!) 
        TestImage.image = UIImage(data: data!)

4. try ASDK Swift method that did not return data still null with correct ContentVersion ID
let req = RestClient.shared.requestForFile(forContentVersionID: contentVersionID)

Please provide some documentation and examples of how to download binary files like image, PDF or EXCel from Files linked to a record for iOS devices like iPad as it is common use for offline data files.

Igor

**Comment by wmathurin** [comment]
If you open https://na132.salesforce.com/sfc/p/4P000000hVnY/a/4P0000004cgd/CZJqiuvzXnMyB5MGVVYuCBx6toWiVr9UfQvQZ3zhTUg in a browser, and bring up the dev tools, you will see that a lot is going on:

![Screen Shot 2019-06-13 at 3 49 11 PM](https://user-images.githubusercontent.com/1012459/59472322-d82de800-8df2-11e9-95e7-57efbb7ad9e7.png)

However, the last fetch is the actual image:
https://c.na132.content.force.com/sfc/dist/version/renditionDownload?rendition=ORIGINAL_Png&versionId=0684P0000075llY&operationContext=DELIVERY&contentId=05T4P00000VaExX&page=0&d=/a/4P0000004cgd/CZJqiuvzXnMyB5MGVVYuCBx6toWiVr9UfQvQZ3zhTUg&oid=00D4P000000hVnY&dpt=null&viewId=

You should be able to put together that URL programmatically. You should build your UIImage from the data at that URL.
