### ISSUE TITLE
Push notification

### ISSUE THREAD

**Issue by jeevanandhamr** [forcedotcom/SalesforceMobileSDK-iOS#2898]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.0
2. Issue found in Native App or Hybrid App: Native app
3. OS Version: 12.x
4. Device: iPhone
5. Steps to reproduce: I am developing a Salesforce mobile application for iOS devices. I have created connect app in Salesforce and uploaded the p12 certificate for receiving push notification. There is no issue in Connected app settings and p12 certificates.
6. Actual behavior: Push notification not working
7. Expected Behavior: Application should receive the push notification from Salesforce
8. Error Log:

The following method returns error always.

SFPushNotificationManager.sharedInstance().registerSalesforceNotifications(completionBlock:

**Comment by wmathurin** [comment]
What error are you getting?
Make sure to follow all the steps described [here](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/push_using_ios.htm).
Our internal apps (and a number of external customers) are using push notification through Mobile SDK without any issues.

**Comment by wmathurin** [comment]
Re-open when you can provide more details.
