### ISSUE TITLE
__locally_created__ = 1 appears to always do an Insert vs Upsert despite External ID

### ISSUE THREAD

**Issue by JimBTek** [forcedotcom/SalesforceMobileSDK-iOS#2900]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.0.0
2. Issue found in Native App or Hybrid App: React Native iOS 
3. OS Version: iOS 12.3.1
4. Device: ipad mini 5th gen
5. Steps to reproduce:
If you are on a poor cellular connection, you can easily commit records to Salesforce, but fail to get the success response, and therefore fail to update your locally created records to now have a Salesforce ID, and also not be considered `__local__` or `__locally_created__`

This should not matter if the Sync Up is doing an Upsert, as it will just catch it next time.
However, it appears that possibly the SDK does an Insert instead of an Upsert

- use the Sync Up framework: https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/entity_framework_sync_related.htm
- Create a record in Salesforce with an External ID
- Create a duplicate record in the iPad app with the same External ID
- Sync Up

6. Actual behavior:
the record fails to update in Salesforce and in the app Inspector you can see the record is updated with:
errorCode= DUPLICATE_VALUE External_ID__c duplicates value on record with id: _____

we tried changing the idFieldName to our external ID, but that failed entirely. 

Any advice is greatly appreciated!  If this is indeed a bug / unsupported feature, is it best to just hit the rest api with https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/ios_rest_apis_supported.htm?search_text=api%20version

7. Expected Behavior:
If you are using an External ID, and the SDK see's a `__local__` record it should still UPSERT and try to find a match.

8. Error Log:

2019-06-13 19:03:13.915093-0400 app[987:318042] [SmartStore] CLASS: SFSmartStore convertSmartSQl:SELECT {measurements:_soupEntryId} FROM {measurements} WHERE {measurements:__local__} = '1' ORDER BY {measurements:_soupEntryId} ASC
2019-06-13 19:03:14.436310-0400 app[987:317878] [SmartSync] CLASS: SFSmartSyncNetworkUtils sendRequestWithSmartSyncUserAgent:error:400:https://uat.cs20.my.salesforce.com/services/data/v42.0/sobjects/Measurement__c
2019-06-13 19:03:14.470320-0400 app[987:318042] [SmartStore] CLASS: SFSmartStore convertSmartSQl:SELECT {measurements:_soupEntryId} FROM {measurements} WHERE {measurements:__local__} = '1' ORDER BY {measurements:_soupEntryId} ASC
2019-06-13 19:03:14.826775-0400 app[987:318042] [SmartSync] CLASS: SFSmartSyncNetworkUtils sendRequestWithSmartSyncUserAgent:error:400:https://uat.cs20.my.salesforce.com/services/data/v42.0/sobjects/Measurement__c

**Comment by wmathurin** [comment]
We will take a look thanks.

**Comment by JimBTek** [comment]
OK thanks.  I could not think of a better way to force the reproduction of it.  But perhaps the Salesforce record being modified more recently could also cause a rejection. 

We upgraded to 7.1.2 today and are testing to see if we still encounter it. I will report back. 

We have ~20 users in poor cell areas and we are experiencing this on 6+ and we have a new version of the app on 7 and still seeing it in our pre-release testing. We did not see this happen until we were on cell connection. It was generating duplicates in Salesforce before we added an external ID. Now the device just always thinks it has extra copies of the same record. Even if you simulate a slow 3G connection in Xcode you won't see it, unless you use our reproduction steps to force it to happen.

**Comment by JimBTek** [comment]
It appears to behave the same in 7.1.2 if you use the steps to reproduce.

**Comment by az-oolloow** [comment]
> This should not matter if the Sync Up is doing an Upsert, as it will just catch it next time.

Do you have an example of an API operation that would be an 'upsert'? Or is it just a `PATCH` call that you're referring to? (i always thought those required Id regardless of external id)

**Comment by JimBTek** [comment]
https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_upsert.htm

**Comment by wmathurin** [comment]
In Mobile SDK 8.0, sync up target can be given a externalIdFieldName. During sync up,  locally created record with a provided external id will get upserted by external id instead of being created on the server.

See https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3093
