### ISSUE TITLE
SaleforceSDKComment and os/log.h  on case sensitive volume

### ISSUE THREAD

**Issue by david-spaeth** [forcedotcom/SalesforceMobileSDK-iOS#2902]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.1.2
2. Issue found in Native App or Hybrid App: Native
3. OS Version: IOS 11
4. Device: All
5. Steps to reproduce: run Xcode on case sensitive volume
6. Actual behavior: Compile fail
7. Expected Behavior: compile success
8. Error Log:  'OS/log.h' file not found

Hi,

Can your change OS/log import to correct case  ?

`#import <OS/log.h>` must be `#import <os/log.h>` 

Thanks

**Comment by wmathurin** [comment]
Thanks for reporting the issue. Getting fixed with https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2903
