### ISSUE TITLE
Crash in SFKeychainItemWrapper

### ISSUE THREAD

**Issue by Nehora** [forcedotcom/SalesforceMobileSDK-iOS#2905]
Version of Mobile SDK Used: 7.0.0
Device: iphone
Steps to reproduce: crashlytics error on production, can't reproducing

The error tells me the parameter `request` in `sendRequest` method doesn't has data and because of that the user has an application crash.
It happens on the line `RestClient.shared.send(request: request...`
The documentation says `RestClient.shared.requestForCreate` should retrieve a `RestRequest` type.
Why does it happen? 
How I can avoid that crash?
Maybe it happens because for some case the user doesn't has access_token?
I saw you improved REST Requests in SDK7.1, is it a fix for that case?

    static func insert(objectName:String, fields:[String: Any]) -> Promise<Any?>{
        let request = RestClient.shared.requestForCreate(withObjectType: objectName, fields: fields)
        return sendRequest(request: request)
    }

    static func sendRequest(request: RestRequest) -> Promise<Any?>{
        return Promise{ seal in
            if let err = checkWSCallValidity(){
                seal.reject(err)
            }
            RestClient.shared.send(request: request, onFailure: { (error, urlResponse) in
                let err = CustomError(localizedTitle: "Error".localized(), localizedDescription: getErrorDescription(err: error), code: 1)
                UIApplication.topViewController()?.checkWSError(error: (title: err.localizedTitle, description: err.localizedDescription))
                seal.reject(err)
            }) { response, responseUrl  in
                seal.fulfill(response)
            }
        }
    }

**Comment by wmathurin** [comment]
`requestForCreate` is a simple factory method that builds a RestRequest for creating a s-object.
Is the user logged in? Do you have more details from the crash?

**Comment by Nehora** [comment]
Is it connected to the issue if the user is connected or not?
I expect the user to be connected but we have also more salesforce sdk crashes, so i'm not sure about it.
But I expect `requestForCreate` function to retrieve me an object anyway, and not cause me a crash.

This is another crash we have, we have lots of crashes on this crash (more than the one I sent before)
<img width="442" alt="Screen Shot 2019-06-18 at 9 30 44" src="https://user-images.githubusercontent.com/33718538/59658401-299bf580-91ac-11e9-9e6d-afc224250991.png">

**Comment by wmathurin** [comment]
If you get errSecInteractionNotAllowed, it's probably because the app is accessing key chain items from the background while the device is locked (for instance when the access token expires, the SDK automatically refreshes it using the refresh token which is stored securely in the key chain).

By default, we store items in the keychain with the `kSecAttrAccessibleWhenUnlockedThisDeviceOnly ` attribute (see [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Common/SFKeychainItemWrapper.m#L90)).

You could relax the default setting by calling:
`[SFKeychainItemWrapper setAccessibleAttribute:kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly]` (or some other levels that is suitable to your application).

**Comment by Nehora** [comment]
Ok, so how can I avoid these 2 crashes? 
It seems like SF SDK try to set access token while getting `errSecInteractionNotAllowed` even the default `kSecAttrAccessibleWhenUnlockedThisDeviceOnly`
Thanks!

![Screen Shot 2019-07-01 at 16 58 54](https://user-images.githubusercontent.com/33718538/60442682-35fb6600-9c22-11e9-8818-4bcb17f81ffd.png)

**Comment by wmathurin** [comment]
Do you know what devices the crashes are happening on? Do they have passcode or touch id / face id setup?

**Comment by Nehora** [comment]
the application has around 15,000 users, and for sure they have passcode or touch id / face id setup.
In the last 7 days we had 67 crashes for 65 users on Fabric with the error `errSecInteractionNotAllowed`.
I think this crash issue causes more other weird crashes we have.
![Screen Shot 2019-07-02 at 9 07 06](https://user-images.githubusercontent.com/33718538/60487916-2ffc9800-9ca9-11e9-9f5e-052f15205137.png)

**Comment by wmathurin** [comment]
We are investigating. Thanks.

**Comment by Nehora** [comment]
Hello, do you have any answer?

**Comment by Nehora** [comment]
Just to be sure we understand each other,
I ment the users have passcode or touch id / face id setup for the device.
They don't have any lock option for the application.
The application built for a very famous client that important for us and also give us more important clients.
Our client follows fabric crashlytics, so we really need to resolve it.
Thanks!!

**Comment by wmathurin** [comment]
We are investigating the issue . Thanks.

**Comment by trooper2013** [comment]
@Nehora  Are there logs that you are able to  post here?  Are you able to repro the error?

**Comment by Nehora** [comment]
Hi, I hope I understood you correctly.
I added the line to `initWithIdentifier` func at path `Pods/SalesforceSDKCore/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Common/SFKeychainItemWrapper.m`
`[SFKeychainItemWrapper setAccessibleAttribute:kSecAttrAccessibleAfterFirstUnlock];`
Is that ok?

We have release to production next week for part of our users and a week after for all our users.
I will follow fabric crashlytics and will update if we still have this crash in 3 weeks from now.
Thanks!!

**Comment by trooper2013** [comment]
@Nehora You should add this line in your appDelegate's initializer and not in the SFKeychainItemWrapper.m

**Comment by Nehora** [comment]
Ok, thanks!
I can update at 6.8 if we can still see this crash or not.

**Comment by Nehora** [comment]
Hi,
I released the application previous week to pilot users in production.
I still have the error `errSecInteractionNotAllowed`.
In addition, now I have another crashes after I added this line to AppDelegate:
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // some code......
        AuthHelper.loginIfRequired {
             self.handleLogin()
          }   SFKeychainItemWrapper.setAccessibleAttribute(kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly)  
        return true
}
```

Crash description:
![Screen Shot 2019-07-29 at 16 41 31](https://user-images.githubusercontent.com/33718538/62053322-0ab76700-b220-11e9-9ca4-d7f17ed26f00.png)

It crash fall on this line:
`UserAccountManager.shared.currentUserAccountIdentity?.userId`

Thanks

**Comment by az-oolloow** [comment]
@Nehora apologies for off topic - what tool do you use to capture these screenshots of your stack traces? (e.g. how do you collect crash logs)

**Comment by bhariharan** [comment]
The recommendation on this bug is to set the appropriate keychain access level as mentioned above.

**Comment by az-oolloow** [comment]
@umangshuMTX what is the version of iOS you're experiencing this with?
