### ISSUE TITLE
Hybrid Mobile SDK 6.2 App (iOS) - Opens Classic or Lightning Page inside a Login-View Container

### ISSUE THREAD

**Issue by anujanagarkar** [forcedotcom/SalesforceMobileSDK-iOS#2906]
1. Version of Mobile SDK Used: **Hybrid Mobile SDK 6.2**
2. Issue found in Native App or Hybrid App: **Hybrid(iOS)** 
3. OS Version: **Tested and observed on iOS 12.1, iOS 11.1.1**
4. Device: **iPad Air 2, iPad Pro**
5. Steps to reproduce:
i. Launch the app.
ii. Enter username and password.
iii. Tap on Login.
iv. Tap on Allow button of OAuth page.
v. Salesforce web page will be displayed instead of app screen.

6. Actual behavior:
On iOS App when user enters the login credentials, OAuth page is loaded for allowing or denying the access.
Here, upon tapping on ‘Allow’ button, salesforce classic or lightning web page is rendered instead of navigating to the html start page (index.html) defined in the mobile app. 
![AfU26](https://user-images.githubusercontent.com/6368130/59594228-14be5400-9111-11e9-8d77-4a6ac2308cb2.png)
![c1Hso](https://user-images.githubusercontent.com/6368130/59594248-1daf2580-9111-11e9-9c41-2897e61b119c.png)

7. Expected Behavior:
After tapping on ‘Allow’ button of OAuth page, app should get navigated to html start page (index.html) defined in the mobile app. 
8. Error Log:
Not Available

**Comment by wmathurin** [comment]
We need more info:
- how did you generate your application?
- how are you initiating login?
- how is your application configured in bootconfig.json?

**Comment by anujanagarkar** [comment]
Please check the information below:

- how did you generate your application?
  The app uses 'cordova' plugin and was created using **'forcehybrid create'** command

- how are you initiating login?
  We are calling 'launch' method of SalesforceSDKManager i.e  **[[SalesforceSDKManager 
  sharedManager] launch]** in didFinishLaunchingWithOptions of 
  AppDelegate+SalesforceHybridSDK.m

- how is your application configured in bootconfig.json?
 {
    "remoteAccessConsumerKey": "{CONSUMER_KEY_HERE}",
    "oauthRedirectURI": "sfdc://success",
    "oauthScopes": ["web", "api"],
    "isLocal": true,
    "startPage": "index.html",
    "errorPage": "error.html",
    "shouldAuthenticate": true,
    "attemptOfflineLoad": true
 }

**Comment by wmathurin** [comment]
Could you double check that sfdc://success is indeed the call back url you configured for your connected app?

Next could you try with the latest version of the Mobile SDK (7.1.2)?

**Comment by anujanagarkar** [comment]
Hello @wmathurin , Thanks for your quick response. Please check the below details with reference to your ask:

- Could you double check that sfdc://success is indeed the call back url you configured for your connected app?
**Yes, we verified and the callback url configured for our app is sfdc://success. Please check below screenshot of configuration.**
<img width="1151" alt="Screen Shot 2019-06-19 at 11 52 02 AM" src="https://user-images.githubusercontent.com/6368130/59761317-1ecb8880-92b2-11e9-92f6-72dc4549b3a5.png">



- Next could you try with the latest version of the Mobile SDK (7.1.2)?
**We couldn't test by updating the SDK version because our client is using an app on production environment. The app has to go through sandbox, UAT and then the Production stage. Hence, updating the SDK would be a major risk.**

**Comment by wmathurin** [comment]
Right now you have "Token valid for 0 hour". Could you go to Setup > Managed apps > Connected Apps and change the Refresh Token policy for your app to not be "Immediately expire refresh token"?

**Comment by anujanagarkar** [comment]
Hello @wmathurin ,
Currently Refresh Token policy for our connected app is set to **Refresh token is valid until revoked**. Please check screenshot below:
<img width="1017" alt="Screen Shot 2019-06-20 at 2 49 56 PM" src="https://user-images.githubusercontent.com/6368130/59839162-dd98ae80-936d-11e9-8ba1-73b68cc3c9b8.png">

**Comment by anujanagarkar** [comment]
Hello @wmathurin ,
Did you get chance to review the above configuration?
Can you please guide us on  any other alternatives, This is high priority issue for our client.

**Comment by wmathurin** [comment]
We don't patch old versions of the Mobile SDK.
The best approach would be to upgrade to the latest version of the Mobile SDK. If the issue still occurs (we haven't seen the issue on our side), we might then be able to work on a fix in a future patch or point release.
