### ISSUE TITLE
File is not a database

### ISSUE THREAD

**Issue by lucasbordini** [forcedotcom/SalesforceMobileSDK-iOS#2910]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 12.1
4. Device: All
5. Steps to reproduce: Login, use SmartStore, Logout, try to use SmartStore again
6. Actual behavior: SmartStore is not consulted and receive an error
7. Expected Behavior: SmartStore is consulted
8. Error Log: Error Domain=com.salesforce.smartstore.error Code=999 "file is not a database"

**Comment by wmathurin** [comment]
1) You should not hold a reference to a smartstore but instead call [SFSmartStore sharedStoreWithName].
2) If you want a smartstore that survives logout, you need to use a global smartstore.

**Comment by lucasbordini** [comment]
I don't hold any reference, every time I need to use SmartStore I get call a function like this:
func smartStore() -> SmartStore?  {
        return SmartStore.shared(withName: SmartStore.defaultStoreName)
 }

**Comment by trooper2013** [comment]
@lucasbordini   SmartStore.shared should be used within in the context of a logged In user only. When you logout the store is removed.

**Comment by trooper2013** [comment]
@lucasbordini if you are storing data that need  to be accessed  outside of user context use a globalStore instead.

**Comment by lucasbordini** [comment]
@trooper2013 I know this, I didn't trying to use the SmartStore unlogged, the error happens when I do the login again

**Comment by MattSynaptic** [comment]
@lucasbordini We are getting a similar error. Did you ever resolve this?
