### ISSUE TITLE
AuthHelper.loginIfRequired never presents the loginViewController if shouldAuthenticate is set to NO/False

### ISSUE THREAD

**Issue by dppeak** [forcedotcom/SalesforceMobileSDK-iOS#2916]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.1.2
2. Issue found in Native App or Hybrid App: Native Swift App
3. OS Version: 12.4
4. Device: Simulator iPhone XR
5. Steps to reproduce:

Use forceios createwithtemplate with template:
https://github.com/forcedotcom/SalesforceMobileSDK-Templates/iOSNativeSwiftTemplate#v7.1.2

modify bootconfig.plist setting for shouldAuthenticate to NO
run on simulator

6. Actual behavior: LoginViewController never appears
7. Expected Behavior: LoginViewController should be presented to login
8. Error Log:

2019-06-20 13:50:28.014417-0500 temp[73238:40911036] [SalesforceSDKCore] CLASS: SFUserAccountManager Swizzled :: SFUserAccountManager
2019-06-20 13:50:28.112435-0500 temp[73238:40911036] [SalesforceSDKCore] CLASS: SFKeychainItemWrapper setObject:forKey: Value already stored in the keychain. No action taken.
2019-06-20 13:50:28.277380-0500 temp[73238:40911036] [SalesforceSDKCore] CLASS: SFSecurityLockout Skipping 'lock' since not authenticated
2019-06-20 13:50:28.277567-0500 temp[73238:40911036] [SalesforceSDKCore] CLASS: SFKeychainItemWrapper setObject:forKey: Value already stored in the keychain. No action taken.
2019-06-20 13:50:28.277673-0500 temp[73238:40911036] [SalesforceSDKCore] CLASS: SFSDKAuthHelper Passcode verified, or not configured.  Proceeding with authentication validation.
2019-06-20 13:50:28.359879-0500 temp[73238:40911036] [SalesforceSDKCore] CLASS: SmartSyncSDKManager App is resuming active state.

**Comment by wmathurin** [comment]
It's actually by design see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2756

If you want to login call see https://github.com/wmathurin/SalesforceMobileSDK-iOS/blob/9ab39083c72ed608093a8aaeb65983d88dbdd4d3/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Util/SFSDKAuthHelper.m#L49

**Comment by dppeak** [comment]
That's a breaking change from 7.0.0 that was not called out in documentation.  

The way it worked in 7.0.0 was that if you set shouldAuthenticate to True, you would not be able to exit the login flow.  To be able to let the user exit or back out of the login process, you would set the value to false, and the Back arrow would appear in the upper left.

The loginIfRequired is to be used when you want to present the login flow if there was no valid access token.  The loginWithCompletion will always present the login flow even if you have a valid access token.

Please reopen this issue

**Comment by dppeak** [comment]
With the changes, if we set shouldAuthenticate to false, loginIfRequired will never present the login flow even if there is not a valid access token.

**Comment by wmathurin** [comment]
Conversely, the way it was implemented, login would pop up even though one indicated that authentication should not happen (based on the config). 

Some devs complained about the method name being misleading - they understood "required" to mean "required by config and by lack of already being logged in". We decided the 7.0 behavior was not as desired and therefore a bug.

Short of passing an extra parameter, we have to decide whether that method honors the config or not.
To control the behavior yourself you can simply do the following in your code:
```objective-c
if (![SFUserAccountManager sharedInstance].currentUser) {
    [[SFUserAccountManager sharedInstance] loginWithCompletion:successBlock failure:failureBlock];
}
```
Maybe in a future release, we will add a second method to do just that (and name it something not ambiguous).
