### ISSUE TITLE
Open the sqlite database outside of the simulator?

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#2918]
I am developing a very elaborate query and it is quite difficult to do so with the built-in inspector on the device.

Is there an easy way to copy out the store.sqlite so that it can be open on the Mac?

I am developing using 7.1 SDK on a native iOS app.

I did get the code for getting the encryption key out (or at least what i think is an encryption key) but Sqlite browser rejects it.

**Comment by wmathurin** [comment]
1. The store.sqlite file lives in a sub-directory of the `Documents` directory of your application. The assumption here is that you are running the application on a simulator. On device, you can only get to the file if the device is jailbroken. 
Locate it with:
```shell
find ~/Library/Developer/CoreSimulator/Devices -name store.sqlite
```
For instance I ran SmartSyncExplorerSwift application (that lives in the SalesforceMobileSDK-Templates repo), and found store.sqlite file is at:
`./Library/Developer/CoreSimulator/Devices/E920E309-EDE6-43DF-A072-D5C03AB63CEC/data/Containers/Data/Application/F5C604EB-195F-40E4-A294-C2FBC70464DC/Documents/com.salesforce.mobilesdk.SmartSyncExplorerSwift/00DP00000002p6hMAA/005P0000001npvZ/internal/stores/defaultStore/store.sqlite`.

2. Get the encryption key by running in the application in a debugger with a breakpoint [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SmartStore/SmartStore/Classes/SFSmartStoreDatabaseManager.m#L210).

3. Install sqlcipher on your computer by doing 
```shell
brew install sqlcipher
```

4. Open store.sqlite with sqlcipher by doing
```shell
$ sqlcipher store.sqlite 
SQLCipher version 3.27.2 2019-02-25 16:06:06
Enter ".help" for usage hints.
sqlite> PRAGMA cipher_default_compatibility = 3;
sqlite> PRAGMA cipher_default_kdf_iter = 4000;
sqlite> pragma key='--the-key--';
```

5. Finally export it unencrypted by doing
```shell
sqlite> ATTACH DATABASE 'plaintext.db' AS plaintext KEY '';  -- empty key will disable encryption
sqlite> SELECT sqlcipher_export('plaintext'); 
sqlite> DETACH DATABASE plaintext; 
```

**Comment by az-oolloow** [comment]
@wmathurin sadly, this doesn't work.

After i run 
```
ATTACH DATABASE 'plaintext.db' AS plaintext KEY '';
```

I get 

> Error: file is not a database

**Comment by wmathurin** [comment]
Did you successfully make it to the end of step 4?
At the end of step 4, you should be able to query tables. For instance, you should be able to do `.schema` to see the list of tables.
