### ISSUE TITLE
Attachment duplicates getting created in multi user environment.

### ISSUE THREAD

**Issue by rohithksuvarna** [forcedotcom/SalesforceMobileSDK-iOS#2921]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.0.0
2. Issue found in Native App or Hybrid App: iOS native
3. OS Version: latest all iOS versions.
4. Device: iPad

5. Steps to reproduce: 
**Make sure multi user is added**, add some attachment data to the logged in user and while syncing logout and login with other user, now logout and login with first user where you added the attachments. Duplicate attachments are created. 

**Is there any way to handle duplicates in attachments?.**

6. Actual behavior: Duplicate attachments are created by following the above steps.
7. Expected Behavior: No duplicates should be created.
8. Error Log: No errors.

**Comment by wmathurin** [comment]
How are you creating attachments? Why did you mean by syncing? Are you using SmartSync?

**Comment by rohithksuvarna** [comment]
Hi @wmathurin thank you for the quick response, i have updated the answers for the questions which you raised below,

**How are you creating attachments?** 
- Using **SyncUpTarget** i am creating the attachment objects. **createOnServer** method is used to create the records.

**Why did you mean by syncing?** 
- It means sync up. In my use case i am trying to create attachment records.

**Are you using SmartSync?**
- Yes. We are using smart sync.

**Comment by wmathurin** [comment]
Can you reproduce the issue in our simple sample app (SmartSyncExplorerSwift)?

**Comment by wmathurin** [comment]
I believe this enhancement (https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3093) should avoid the issue.

**Comment by rohithksuvarna** [comment]
@wmathurin 

I have this issue only for Attachment and Notes object which are standard objects of salesforce.

The above solution will work only for normal records where we can keep external Id field.

**Is that possible to keep externalId field in Attachment and Notes soup?**
