### ISSUE TITLE
Error: Out of Memory

### ISSUE THREAD

**Issue by rohithksuvarna** [forcedotcom/SalesforceMobileSDK-iOS#2923]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.0
2. Issue found in Native App or Hybrid App: Native iOS app
3. OS Version: iOS 11.0 and above
4. Device: iPad
5. Steps to reproduce: Add 20 photos and try to upload, and in the middle try to query the smart store, above error you will get.
6. Actual behavior: Throwing the above error and screenshot of error is attached below and if i try to query the results from smart store, no callback.
7. Expected Behavior: Results need to returned on querying the smart store.
8. Error Log: Attached the screenshot below.
<img width="784" alt="Screenshot 2019-06-28 at 5 59 10 PM" src="https://user-images.githubusercontent.com/38210810/60342483-2b955e00-99cf-11e9-82ae-9e408b6f866e.png">

Waiting for the quick response.

**Comment by wmathurin** [comment]
Error 26 followed by a OOM happens when the SQLCipher database that SmartStore uses can't be opened (because the wrong key is in use).
Could you tell us what else is going on in your app (e.g. was there a user switch in progress)?

**Comment by rohithksuvarna** [comment]
Thanks @wmathurin for the quick response,

From the app end we add attachment records, in the middle of attachment records upload, we try to **switch between the users**. In this case also same error we get which i posted above in the screenshot.

App also supports offline mode along with multi user switch.

Since our app uses multi user switching feature too provided by the SDK.

**How to handle this scenerio?**

Waiting for the quick response.

**Comment by wmathurin** [comment]
My first recommendation would be to upgrade to the latest Mobile SDK (7.1.2). There have been a number of enhancements with SmartStore / SmartSync.

**Comment by wmathurin** [comment]
Please re-open if you can repro the issue in the latest version of the Mobile SDK.
