### ISSUE TITLE
SmartStore does not support External IDs to prevent duplicates

### ISSUE THREAD

**Issue by JimBTek** [forcedotcom/SalesforceMobileSDK-iOS#2924]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.1.2
2. Issue found in Native App or Hybrid App: iOS React Native
3. OS Version: 12.3.1
4. Device: iPad Mini 5
5. Steps to reproduce:

- Create a Record with an External ID in Salesforce
- Create a duplicate record on the Device with the Same External ID, but no Salesforce ID
- Sync Down from Salesforce, and you will have 2 Duplicates in the SmartStore with the same External ID

6. Actual behavior:
- There are duplicate records in the SmartStore

7. Expected Behavior:

Similar to #2900, the SmartStore and SmartSync should handle connectivity issues that can cause duplicates in either the app or Salesforce. It should allow an External ID to both be honored for Upserting into Salesforce and Upserting into the local Store.

If a field is set as part of the Index or somehow otherwise marked as an External ID (Or even better get the info from salesforce via metadata API), then the SmartStore should perform an Upsert when downloading a duplicate. 

The Real World Scenario is:

- User created a record locally
- The record syncs up but the device fails to get the response
- The Device does a sync down
- Now there are 2 duplicate records on the device with the same External ID, but one has a Salesforce ID
- Also the original local record, is still stuck in __local__ / __locally_modified__ which could cause issues with upserting over it and deciding what data to keep.

We wrote some code in React Native to handle this and essentially as part of clear Ghosts, we look for dupes, and copy the Salesforce ID to the original record, and delete the new duplicate. This doesn't fully solve it, and the device still thinks there is a record to sync up, but it protects us from losing the local data while getting rid of duplicates.

8. Error Log:
No error, but users will see duplicate records in the UI and in the SmartStore

**Comment by wmathurin** [comment]
We will add a story to our backlog. Thanks.

**Comment by az-oolloow** [comment]
@wmathurin it would be VERY beneficial if any behaviour like this could be opted out of.

Specifically, if the org and app do not support nor use External IDs, making extra metadata calls to get those when there are none is wasteful. On cheaper Salesforce plans this could be prohibitively expensive in terms of API call limits.

**Comment by JimBTek** [comment]
@az-oolloow it doesn't seem like that would be an issue, if you just don't identify an External ID in your soup index, and you don't SOQL a field that is an external ID, then there is nothing to try and match against.  BUT there is no way to know if the record successfully was committed to the database or rolled back, so without an External ID you are risking duplicates.  So the SDK should really generate a GUID external ID and push it up so it doesn't cause duplicates.

**Comment by wmathurin** [comment]
In Mobile SDK 8.0, sync up target can be given a externalIdFieldName. During sync up,  locally created record with a provided external id will get upserted by external id instead of being created on the server.

See https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3093
