### ISSUE TITLE
FMDB library not found

### ISSUE THREAD

**Issue by radhika075** [forcedotcom/SalesforceMobileSDK-iOS#2926]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.1.2
2. Issue found in Native App or Hybrid App: ReactNative v 0.59.9
3. OS Version: 11
4. Device: iphone x
5. Steps to reproduce: upgraded my react-native version and salesforcemobile sdk version.
6. Actual behavior: Unable to create ipa
7. Expected Behavior:Should be able to create an ipa
8. Error Log:

❌  ld: library not found for -lFMDB

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **

The following build commands failed:
Ld /Users/abc/Library/Developer/Xcode/DerivedData/MICPSv2-dbdiloqkgxvtxyapdcaufxrcmneq/Build/Intermediates.noindex/ArchiveIntermediates/MICPS(DEV)/IntermediateBuildFilesPath/MICPSv2.build/Release-iphoneos/MICPSv2.build/Objects-normal/armv7/MICPSv2 normal armv7
Ld /Users/abc/Library/Developer/Xcode/DerivedData/MICPSv2-dbdiloqkgxvtxyapdcaufxrcmneq/Build/Intermediates.noindex/ArchiveIntermediates/MICPS(DEV)/IntermediateBuildFilesPath/MICPSv2.build/Release-iphoneos/MICPSv2.build/Objects-normal/arm64/MICPSv2 normal arm64
(2 failures)
[21:43:20]: Exit status: 65

+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.126.0                 |
| sdk         | iPhoneOS12.1.sdk        |
+-------------+-------------------------+

[21:43:20]: ▸ ld: warning: directory not found for option '-L/Users/abc/Library/Developer/Xcode/DerivedData/MICPSv2-dbdiloqkgxvtxyapdcaufxrcmneq/Build/Intermediates.noindex/ArchiveIntermediates/MICPS(DEV)/BuildProductsPath/Release-iphoneos/TouchID'
[21:43:20]: ▸ ld: warning: directory not found for option '-L/Users/abc/Library/Developer/Xcode/DerivedData/MICPSv2-dbdiloqkgxvtxyapdcaufxrcmneq/Build/Intermediates.noindex/ArchiveIntermediates/MICPS(DEV)/BuildProductsPath/Release-iphoneos/react-native-google-maps'
[21:43:20]: ▸ ld: warning: directory not found for option '-L/Users/abc/Library/Developer/Xcode/DerivedData/MICPSv2-dbdiloqkgxvtxyapdcaufxrcmneq/Build/Intermediates.noindex/ArchiveIntermediates/MICPS(DEV)/BuildProductsPath/Release-iphoneos/react-native-maps'
[21:43:20]: ▸ ld: library not found for -lFMDB
[21:43:20]: ▸ clang: error: linker command failed with exit code 1 (use -v to see invocation)
[21:43:20]: 
[21:43:20]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[21:43:20]: 📋  For the complete and more detailed error log, check the full log at:
[21:43:20]: 📋  /Users/abc/Library/Logs/gym/MICPSv2-MICPS(DEV).log
[21:43:20]: 
[21:43:20]: Looks like fastlane ran into a build/archive error with your project
[21:43:20]: It's hard to tell what's causing the error, so we wrote some guides on how
[21:43:20]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[21:43:20]: Before submitting an issue on GitHub, please follow the guide above and make
[21:43:20]: sure your project is set up correctly.
[21:43:20]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[21:43:20]: the full commands printed out in yellow in the above log.
[21:43:20]: Make sure to inspect the output above, as usually you'll find more error information there

**Comment by wmathurin** [comment]
How did you originally create your application? Did you use [forcereact](https://www.npmjs.com/package/forcereact)?

Also note that support for react native 0.59.9 is coming to our next version of the Mobile SDK (7.2) that should be released in the next couple of weeks.

**Comment by radhika075** [comment]
Really Appreciate the quick response :)

It's an existing application. Was working with previous version of react-native 0.55.4 and sf mobile sdk 6.2.
I just upgraded the version and this error started coming.

Is the current sfsdk version compatible with react-native 0.57? i can temporarily downgrade it.

**Comment by wmathurin** [comment]
Mobile SDK 7.1.2 (latest currently out) uses React Native 0.56.1.

**Comment by wmathurin** [comment]
What's in your podfile?

**Comment by radhika075** [comment]
platform :ios, '11.0'

project 'MICPSv2.xcodeproj'
target 'MICPSv2' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

source 'https://github.com/CocoaPods/Specs.git'

pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport',
    'tvOS',
    'cxxreact',
    'CxxBridge',
    'ART',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS'
]
# 'jschelpers',

pod 'SalesforceSDKCommon', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SalesforceAnalytics', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SalesforceSDKCore', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SmartStore', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SmartSync', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SalesforceReact', :path => '../node_modules/react-native-force'

pod 'react-native-maps', path: rn_maps_path
pod 'react-native-google-maps', path: rn_maps_path  # Unomment this line if you want to support GoogleMaps on iOS
pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS
pod 'GooglePlaces'
pod 'GooglePlacePicker'

pod 'RNFS', :path => '../node_modules/react-native-fs'
pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

pod 'TouchID', :path => '../node_modules/react-native-touch-id'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end

# Fix for xcode9/fmdb/sqlcipher/cocoapod issue - see https://discuss.zetetic.net/t/ios-11-xcode-issue-implicit-declaration-of-function-sqlite3-key-is-invalid-in-c99/2198/27
post_install do | installer |
  print "SQLCipher: link Pods/Headers/sqlite3.h"
  system "mkdir -p Pods/Headers/Private && ln -s ../../SQLCipher/sqlite3.h Pods/Headers/Private"
end

**Comment by radhika075** [comment]
parts in bold are actually commented out!

**Comment by wmathurin** [comment]
You don't need that part anymore
```
post_install do | installer |
print "SQLCipher: link Pods/Headers/sqlite3.h"
system "mkdir -p Pods/Headers/Private && ln -s ../../SQLCipher/sqlite3.h Pods/Headers/Private"
end
```
When you upgrade the SDK, it's probably a good idea to run forcereact and either compare your app with the generated app or copy your changes into the newly generated app (whatever is easier).
You could also have a look at the template and compare your app with it. For instance, [here](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/master/ReactNativeTemplate/ios/Podfile) is the template app Podfile.

**Comment by radhika075** [comment]
I tried out both the solutions:
1 - On commenting out the above lines, the same issue continues to occur.
2 - Creating a new project with forcereact builds a project with react native version of 56.x. The version I am looking for is 57 or higher. Actually there's a bug with react-native dictation which gets fixed in 57, hence the upgrade.

When will the new version of sdk with the updated rn version be rolled out? an eta, will help.

**Comment by wmathurin** [comment]
Mobile SDK 7.2 (with support for RN 0.59.9) is scheduled to go out this week #safeharbor.

**Comment by wmathurin** [comment]
Mobile SDK 7.2 is now live. Please try it, and re-open the issue if the problem still happens.
