### ISSUE TITLE
Not Receiving Push Notification

### ISSUE THREAD

**Issue by johndcclm** [forcedotcom/SalesforceMobileSDK-iOS#2929]
Please fill out the following details:

1. Version of Mobile SDK Used: 
2. Issue found in Native App or Hybrid App: It is a custom app which is connected to salesforce
3. OS Version: 12
4. Device: iphone 6s
5. Steps to reproduce:
6. Actual behavior: Does Not receive any push notification
7. Expected Behavior: Upon Raising a case there should be a push notification
8. Error Log:

**Comment by brandonpage** [comment]
Hi johncclm, 

There is no where near enough information provided to help with your specific issue.  We have not received any other reports of push notifications simply not working so this is likely a configuration issue.  [Here is a link to the relevant documentation.](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/push_using_ios.htm)

If you go through the setup and come back with a more specific problem or question I will reopen this issue.
