### ISSUE TITLE
No podspec found

### ISSUE THREAD

**Issue by redroostertech** [forcedotcom/SalesforceMobileSDK-iOS#2930]
Please fill out the following details:

1. Version of Mobile SDK Used: 
- forceios version 7.1.0
2. Issue found in Native App or Hybrid App:
- native ios
3. OS Version:
- 10.14.5
4. Device:
- n/a
5. Steps to reproduce:
- run `pod install`
6. Actual behavior:
`mwestbrook-ltm:ma-ios-lite mwestbrooks$ pod install
Analyzing dependencies
Fetching podspec for `SalesforceAnalytics` from `mobile_sdk/SalesforceMobileSDK-iOS`
[!] No podspec found for `SalesforceAnalytics` in `mobile_sdk/SalesforceMobileSDK-iOS`
`
7. Expected Behavior:
- Pod should install
8. Error Log:
`mwestbrook-ltm:ma-ios-lite mwestbrooks$ pod install
Analyzing dependencies
Fetching podspec for `SalesforceAnalytics` from `mobile_sdk/SalesforceMobileSDK-iOS`
[!] No podspec found for `SalesforceAnalytics` in `mobile_sdk/SalesforceMobileSDK-iOS`
`

**Comment by brandonpage** [comment]
Hi @redroostertech,

What version of cocoapods are you using?  I believe cocoapods introduced some issues with version 1.5 but I am sure 1.4, 1.6 work.

**Comment by redroostertech** [comment]
@brandonpage I am currently on 1.6.0
![Screen Shot 2019-07-05 at 1 11 29 PM](https://user-images.githubusercontent.com/8765750/60736838-77dc2300-9f26-11e9-85b9-e4061ddcda41.png)

**Comment by redroostertech** [comment]
Found issue on my end.

**Comment by brandonpage** [comment]
Thanks!
