### ISSUE TITLE
Crash in SDK 7.0.0 in Smart Sync

### ISSUE THREAD

**Issue by piyushprabhakar** [forcedotcom/SalesforceMobileSDK-iOS#2931]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.0.0
2. Issue found in Native App or Hybrid App: Native iOS App
3. OS Version: 11.0
4. Device: iPhone/iPad
5. Steps to reproduce: Crash got reported on firebase analytics
6. Actual behavior: 

After upgrading SDK to 7.0.0 I could see multiple crashes in smart sync API which got captured on firebase crashlytics. Earlier this was not the case. There is a lot of instance of this kind of crash please refer attached screenshot. Please suggest what could be the reason and how can I prevent it.

7. Expected Behavior: There should not be any crash in SDK
8. Error Log:
![Screenshot 2019-07-08 at 14 23 50](https://user-images.githubusercontent.com/14050203/60797560-1cf83500-a18d-11e9-93de-4801aeda6250.png)
![Screenshot 2019-07-08 at 14 22 01](https://user-images.githubusercontent.com/14050203/60797562-1cf83500-a18d-11e9-85ab-8a1aabd9a47a.png)

**Comment by wmathurin** [comment]
Could you try the latest Mobile SDK (7.1.2). There have been a number of enhancements/fixes with SmartStore / SmartSync.

**Comment by piyushprabhakar** [comment]
Thanks, I will upgrade SDK and let you know about the outcome after a couple of days
