### ISSUE TITLE
iOS Connection Token is not generating on the first app launch

### ISSUE THREAD

**Issue by shanecinense1994** [forcedotcom/SalesforceMobileSDK-iOS#2933]
####Issue description:
The connection token was generated upon user's first login. However, this is only being generated/added on the app side(backend) but not on the SF Mobile Push Registration that's why our push notifications are not working on user's first login.

Connection token was being added in SF Mobile Push Registration on the second log in of user on the app. In this situation, user will never receive the (automated) acknowledgement or the ad hoc reply to their initial problems when their creating a case.

We've already raised this to the ServiceSDK Team but they said that this issue is not their scope and advised us to raise this issue here. Here is the ticket link for your reference:
https://github.com/forcedotcom/ServiceSDK-iOS/issues/97

####Reproduction steps
This is for the authenticated users:

1. Open app
2. Create User
Result: Connection token was generated on the app side but not on the SF Mobile Push Registration

3. Kill the app
4. Open app
5. Log in
Result: Connection token was now added on the SF Mobile Push Registration

####Actual and Expected
Actual: No connection token created on the first app launch.
Expected: There should be a connection token created on the first app launch.

####Device(s) and version(s) of iOS being used
iOS Device: iPhone 6S Plus
iOS Version: 12.1.4

####Screenshots / Videos
Actual
image
![image](https://user-images.githubusercontent.com/45929577/61190553-a4373280-a6d0-11e9-9ea2-45a075dcd242.png)

Expected
image
![image](https://user-images.githubusercontent.com/45929577/61190555-a8635000-a6d0-11e9-9474-af434536b5cf.png)

####Additional Questions:
1. Is there a callback or response from the Mobile SDK, when SF successfully receives and updates the Connection Token?

2. We can try to increase the number of times the app tries to call the SDK to update the Connection Token - for example, app could attempt to do this when the user backgrounds the app, or leaves the Salesforce Case List page to another app screen. However we would like to know if we substantial increase the number of API calls, will this have any adverse impact?

**Comment by trooper2013** [comment]
@shanecinense1994 Please refer to this example in our[ sample app](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/baf6c9e1b63ae7d193c98bd599422c4cdecbb64a/native/SampleApps/SmartSyncExplorer/SmartSyncExplorer/Classes/AppDelegate.m#L119) to ensure that you are making the right calls to SFPushNotificationManager.

**Comment by wmathurin** [comment]
Push notification is successfully used by a number of internal apps so we don't believe it regressed, but instead we think you have it misconfigured. Please re-open this issue if you think you have found a bug (and you can provide more info).

**Comment by shanecinense1994** [comment]
Hi @trooper2013 / @wmathurin ,

We have created a new ticket as our devs have a follow-up question for this. Thank you

https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2943
