### ISSUE TITLE
iOS Connection Token is not generating on the first app launch

### ISSUE THREAD

**Issue by shanecinense1994** [forcedotcom/SalesforceMobileSDK-iOS#2943]
Re-opening our ticket raised regarding this issue. See below for your reference:
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2933

We have already increased the frequency of attempt do perform notification registration (on app background and when we refresh certain app screens) - we hope this will help improve the issue

Is there any SF API that we can call to authenticate users without going through the webpage which is what we're doing now?

**Comment by wmathurin** [comment]
To the question: Is there any SF API that we can call to authenticate users without going through the webpage which is what we're doing now?
There is no API for getting a refresh token that doesn't involve a webview.

You can use the username-password flow to just get an access token (https://help.salesforce.com/articleView?id=remoteaccess_oauth_username_password_flow.htm&type=5) but you will have to manage the token (and its expiration) yourself. Also we advise again storing password on the device, so you might have to prompt the user again.

**Comment by shanecinense1994** [comment]
thank you @wmathurin . We have already relayed this to our devs. We'll get back to you on any updates.

**Comment by shanecinense1994** [comment]
Hi @wmathurin , This issue has been fixed on our. Thank you for all the help.
