### ISSUE TITLE
Using SFRestAPI BatchRequest, SFRestAPI creates incorrect URL

### ISSUE THREAD

**Issue by hmuronaka** [forcedotcom/SalesforceMobileSDK-iOS#2947]
Please fill out the following details:

1. Version of Mobile SDK Used: 
7.1.0
2. Issue found in Native App or Hybrid App:
nativeapp iOS
3. OS Version:
iOS 12
4. Device:
iPhone XR
5. Steps to reproduce:

- when I send HTTP Get-Request with queryParameters using RestAPI's batchRequest
- SFRestAPI create incorrect url(  & wasn't append between query parameter items)

6. Actual behavior:
created URL is instance-url/aaa/bbb/ccc?num=25sort=lastModifiedDesc

7. Expected Behavior:
created URL is instance-url/aaa/bbb/ccc?num=25&sort=lastModifiedDesc

8. Error Log:

For your reference I sent pullrequest  #2948

**Comment by wmathurin** [comment]
Fixed by https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2948. Thanks for reporting and fixing @hmuronaka
