### ISSUE TITLE
Deferred login - Disable token refresh

### ISSUE THREAD

**Issue by timcolla** [forcedotcom/SalesforceMobileSDK-iOS#2949]
Please fill out the following details:

Version of Mobile SDK Used: 7.1
Issue found in Native App or Hybrid App: Native
We have a native client where we use deferred login (calling AuthHelper.loginIfRequired). We have observed that this method will automatically use the refresh token to get a new access token. We would like to know how to prevent it refreshing the token as we want to have control over whether or not the refresh token can be used.

How do we disable the SDK automatically refreshing the access token?

**Comment by bhariharan** [comment]
There's no way to disable automatic token refresh when `RestClient` is being used in the authenticated context - this is a large chunk of the value that `RestClient` offers over building your own REST request and response handler.

It sounds like you're looking for a way to manage requests in the authenticated and unauthenticated scenarios. We have a special `RestClient` instance for guess access which allows you to make requests without the bearer token against unauthenticated REST endpoints. Your app will need to use this instance to make requests in guest mode.
