### ISSUE TITLE
Biometric authentication doesnt work

### ISSUE THREAD

**Issue by yankelandroid** [forcedotcom/SalesforceMobileSDK-iOS#2950]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.1.2
2. Issue found in Native App or Hybrid App: native
3. OS Version: 11.0
4. Device: s7
5. Steps to reproduce: sign in with fingerprint or faceid
6. Actual behavior: do nothing
7. Expected Behavior: call AuthHelper.loginIfRequired declared in didFinishLaunchingWithOptions
8. Error Log: no error

Hi,
I try to implement biometric login but it doesnt work . Salesforce detects my faceId and my fingerprint successfully, but its not enter again into the AuthHelper.loginIfRequired declared in didFinishLaunchingWithOptions.
With the pass code it's work fine 

thank you

**Comment by bhariharan** [comment]
@yankelandroid Biometric is provided only as an alternative to passcode. We don't offer it as a substitute to login at this time. The feature is working as expected.

**Comment by yankelandroid** [comment]
I know that its an alternative .
What i want is to use the fingerprint into the appdelegate and when its success to enter into the AuthHelper.loginIfRequired

**Comment by yankelandroid** [comment]
i talk after doing the login , i close the app and when i open it again it show me fingerprint or passcode 
When i choosse passcode everything is OK, but when i choose fingerprint it detect my finger but nothing happened after ...
