### ISSUE TITLE
Biometric authentication doesnt work well

### ISSUE THREAD

**Issue by yankelandroid** [forcedotcom/SalesforceMobileSDK-iOS#2952]
Please fill out the following details:

Version of Mobile SDK Used: 7.1.2
Issue found in Native App or Hybrid App: native
OS Version: 11.0
Device: s7
Steps to reproduce: sign in with fingerprint or faceid
Actual behavior: do nothing
Expected Behavior: call AuthHelper.loginIfRequired declared in didFinishLaunchingWithOptions
Error Log: no error
Hi,
I try to implement biometric login but it doesnt work . Salesforce detects my faceId and my fingerprint successfully, but its not enter again into the AuthHelper.loginIfRequired declared in didFinishLaunchingWithOptions.
With the pass code it's work fine

What i want is to use the fingerprint into the appdelegate and when its success to enter into the AuthHelper.loginIfRequired

I talk after doing the login , I close the app and when I open it again it show me fingerprint or passcode
When I choosse passcode everything is OK, but when I choose fingerprint it detect my finger but nothing happened after ...

**Comment by trooper2013** [comment]
@yankelandroid  Thats correct.  Works based as per design, our biometric support is coupled with the Passcode support that should be enabled on your connected app.

**Comment by BalazsSzamody** [comment]
@trooper2013 I think what @yankelandroid meant (and what is happening to me as well) is that after successfully logging in, setting up passcode, enabling FaceID and restarting the app. When the app starts the FaceID detection finishes successfully, but the `AuthHelper.loginIfRequired`'s completion block doesn't get called. 

If I don't enable the `FaceID` and I use the passcode only it works perfectly. 

The app uses the Salesforce SDK v8.1.0
OS: iPadOS 14.0
