### ISSUE TITLE
MobileSdk 7.2.0 does not work with phonegap-plugin-push plugin

### ISSUE THREAD

**Issue by Jas05** [forcedotcom/SalesforceMobileSDK-iOS#2959]
Please fill out the following details:

1. Version of Mobile SDK Used: 
7.2.0

2. Issue found in Native App or Hybrid App:
Hybrid

3. OS Version:
IOS

4. Device:
iPhone 6s, 7, 8

5. Steps to reproduce:
Updated the forceHybrid and MobileSdk version to 7.2.0 as it uses cordova-ios 5.0 
I am unable to build the app it is failing to install phonegap-plugin-push plugin

6. Actual behavior:
Unable to built the app

7. Expected Behavior:
App should built properly

8. Error Log:
```
**Installing "phonegap-plugin-push" for ios**
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose
     Cloning into '/var/folders/_5/c3w8vp6j7wlctnk7msmc6h480000gp/T/d20190731-25334-rgnjrq'...
     warning: Could not find remote branch {s.version} to clone.
     fatal: Remote branch {s.version} not found in upstream origin

[!] `<PBXResourcesBuildPhase UUID=`1D60588D0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `6C390C5B1BDE4C538A5EB22C` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] The platform of the target `{AppName}` (iOS 9.0) may not be compatible with `Cordova (5.1.0)` which has a minimum requirement of iOS 11.0.

[!] The platform of the target `{AppName}` (iOS 9.0) may not be compatible with `SalesforceAnalytics (7.2.0)` which has a minimum requirement of iOS 11.0.

[!] The platform of the target `{AppName}` (iOS 9.0) may not be compatible with `SalesforceHybridSDK (7.2.0)` which has a minimum requirement of iOS 11.0.

[!] The platform of the target `{AppName}` (iOS 9.0) may not be compatible with `SalesforceSDKCommon (7.2.0)` which has a minimum requirement of iOS 11.0.

[!] The platform of the target `{AppName}` (iOS 9.0) may not be compatible with `SalesforceSDKCore (7.2.0)` which has a minimum requirement of iOS 11.0.

```
We use this plugin for push notifications. Mobile Sdk version 7.0 works perfectly fine with this plugin.

I think its because MobileSDK now use cordova 5.0 which might not be compaitable with this plugin.

I like to ask you do we actually need this plugin for push notification to work.

For us removing this plugin will built the app but push notification no longer works.

Is there any other plugin or workaround for push notifications? Please suggest

**Comment by wmathurin** [comment]
From your description, you are saying that phone gap push plugin doesn't work with newer version of Cordova. Therefore it's not a Mobile SDK issue. I recommend, you open an issue on the push plugin repo (https://github.com/phonegap/phonegap-plugin-push/issues).
