### ISSUE TITLE
Resync fails if using 12-hour clock

### ISSUE THREAD

**Issue by jlcvp** [forcedotcom/SalesforceMobileSDK-iOS#2964]
Please fill out the following details:

1. Version of Mobile SDK Used: tested from 6.1 to 7.0
2. Issue found in Native App or Hybrid App: Hybrid - ios build. 
3. OS Version: MacOS Mojave. 
4. Device: iPad Pro 2018. 
5. Steps to reproduce: Run a resync with iOS clock format set to 12-hour, language English(UK) and region Ireland.
6. Actual behavior: resync fails because the where clause of `LastModifiedDate > ...` is malformed because the hour part of datetime is only 1 digit-long, despite of the format being set to `yyyy-MM-dd'T'HH:mm:ss.SSSZ` by `SFSmartSyncObjectUtils` constructor. [SFSmartSyncObjectUtils.m#L35](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/9c51f4c89424878ed1acb6405f9d5e2e8784f5fa/libs/SmartSync/SmartSync/Classes/Util/SFSmartSyncObjectUtils.m#L35)
7. Expected Behavior: resync occurs normally
8. Error Log: 
```
Object Name: PriceBookEntry \nWhere LastModifiedDate > 2019-07-16T9:35:21.000-0300 \n^\nERROR at Row:1:Column:268\nline 1:268 no viable alternative at character '9'
```

**Comment by wmathurin** [comment]
Fixed with https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2965 and https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2971
