### ISSUE TITLE
Build Your Own UI with the Chat Core API

### ISSUE THREAD

**Issue by YamibuyJson** [forcedotcom/SalesforceMobileSDK-iOS#2969]
Please fill out the following details:

1. Version of Mobile SDK Used: ServiceSDK-220.1
2. Issue found in Native App or Hybrid App: ios build.
3. OS Version: iOS 12.4
4. Device: iPhone 6s
5. Steps to reproduce:
let config = SCSChatConfiguration(liveAgentPod: "TO_DO_POD_NAME",
                                  // e.g. "d.gla5.gus.salesforce.com"
                                  orgId: "TO_DO_ORG_ID",
                                  // e.g. "00DB00000003Rxz"
                                  deploymentId: "TO_DO_DEPLOYMENT_ID",
                                  // e.g. "573B00000005KXz"
                                  buttonId: "TO_DO_BUTTON_ID")
                                  // e.g. "575C00000004h3m"
ServiceCloud.shared().chatCore.startSession(with: config)
6. Actual behavior:
It also show the default chat ui.
7. Expected Behavior:
The default UI is not show.
8. Error Log:

**Comment by brandonpage** [comment]
Hi @YamibuyJson.  This appears to be a Service SDK issue, can you please post it here for that team to see: https://github.com/forcedotcom/ServiceSDK-iOS

Thanks

**Comment by YamibuyJson** [comment]
Hi @brandonpage How can i post my issue code.

Thanks

**Comment by bhariharan** [comment]
@YamibuyJson Please open an issue in the repo that Brandon has linked above. This is not a Mobile SDK issue.
