### ISSUE TITLE
WKWebView never released in SFOAuthCoordinator after login

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#2979]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.1.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 12.4
4. Device: iPad 6th Gen
5. Steps to reproduce: 
Run `AuthHelper.loginIfRequired {}` and then check Instruments/Memory graph

6. Actual behavior:
As per this screenshot, `SFOAuthCoordinator` forever retains the webview, even though we're done with it and no longer show it in the app, possibly ever.

![image](https://user-images.githubusercontent.com/47766072/63732296-e4382a80-c8b6-11e9-9767-fd8aeaceb911.png)

7. Expected Behavior:
Webview is no longer retained by SFOAuthCoordinator to avoid this leak.

8. Error Log:
N/A

**Comment by wmathurin** [comment]
Thanks for reporting the issue.

**Comment by wmathurin** [comment]
I'm unable to reproduce the issue (with 7.3). Please re-open if you are still seeing the problem.
