### ISSUE TITLE
Apple submission - Export Compliance question

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#2981]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.1.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 12.4
4. Device: iPad
5. Steps to reproduce: N/A
6. Actual behavior: N/A
7. Expected Behavior: N/A
8. Error Log: N/A

When submitting the apps to App Store that are using SmartStore encryption, including encryption for externally stored data ( e.g. `saveSoupEntryExternally` method), do we have to obtain an ERN authorization or is this encryption exempt as of 2019?

**Comment by wmathurin** [comment]
We aren’t attorneys or export control experts. We can't provide legal advice.
SmartStore is built on top of SQLCipher. I recommend their [export requirements for applications using SQLCipher](https://discuss.zetetic.net/t/export-requirements-for-applications-using-sqlcipher/47) page.
