### ISSUE TITLE
Apple sends a warning submitting apps using WebView

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#2983]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.1.0
2. Issue found in Native App or Hybrid App: Native app
3. OS Version: 12.4
4. Device: iPad
5. Steps to reproduce:
Try to submit the app to Apple
6. Actual behavior:
Apple sends you a warning e-mail.
7. Expected Behavior:
UIWebView is not used in the SDK
8. Error Log:
> TMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information. After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

You can see here that the `UIWebView` is used trying to get user agent string:
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/d7de33b8e36dacf1a08b651180b36c9cd4c36a7a/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Common/SalesforceSDKManager.m#L977

**Comment by bhariharan** [comment]
@az-oolloow Thanks for reporting. We retained that API because that's the only way to obtain the user agent synchronously. We will look into replacing it with the equivalent `WKWebView` API, which is asynchronous.

**Comment by mubeenasif01** [comment]
@bhariharan can you update the library as soon as possible.

**Comment by findigital** [comment]
@bhariharan Do you know how long it will take to make this update?

**Comment by wmathurin** [comment]
Should be fixed in our next release (7.3).
See https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2990
