### ISSUE TITLE
How to pass App Store review - identity verification

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#2989]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.1.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: Any
4. Device: Unknown
5. Steps to reproduce: Submit to Apple
6. Actual behavior: Apple rejects the app saying 'we couldn't sign in because we got the validate your identity'
7. Expected Behavior: Apple can sign in
8. Error Log: N/A

We submitted our app to App Store, and even though we tried setting every possible IP address in the Network Access in our org, we received a rejection.

How do people get around this?

**Comment by bhariharan** [comment]
@az-oolloow I don't understand the question. Is it being rejected because the reviewer was unable to login to the app? Either way, this doesn't sound like it's related to the client code in Mobile SDK in any way. Please contact Salesforce support for server side configuration questions.

**Comment by az-oolloow** [comment]
@bhariharan, yes.

When we use the standard Mobile SDK method (`loginIfRequired`),  the user is presented with a webview. That webview may, after successful, authentication, direct the user to 'verify your identity' screen.

Is there any way to disable, bypass or somehow skip this using mechanisms of the mobile SDK?

Or, what did others do when submitting their apps, as i can't imagine this being just our problem?

**Comment by bhariharan** [comment]
@az-oolloow Gotcha. The "Verify your identity" screen that you see is also within the webview. Mobile SDK has no insight into the login flow within the webview - that's configured on the server side. You'll need to tweak the login settings in your org to disable this prompt. [This help article](https://help.salesforce.com/articleView?id=admin_sessions.htm&type=5) might be a good starting point.

**Comment by az-oolloow** [comment]
If anyone comes across this - what worked for us was checking Login History after failed submission, getting IP range from that and adding it in 'Network Access'.
