### ISSUE TITLE
iOS 13 - Login Page not oriented correctly

### ISSUE THREAD

**Issue by luketomlinson** [forcedotcom/SalesforceMobileSDK-iOS#2992]
Please fill out the following details:

1. Version of Mobile SDK Used: 
7.1.2
2. Issue found in Native App or Hybrid App:
Native
3. OS Version:
13.1 beta 7
4. Device:
iPad Pro 10.5"
5. Steps to reproduce:
Attempt to login with the SDK while in landscape mode
6. Actual behavior:
Login page shows in incorrect orientation. 
![IMG_F915AABC6610-1](https://user-images.githubusercontent.com/19689611/64627515-c9d57500-d3bd-11e9-84f7-81c142cd20ec.jpeg)

7. Expected Behavior:
Login page shows normally in correct orientation. 
8. Error Log:

**Comment by bhariharan** [comment]
@luketomlinson This is by design. We have locked down our `LoginViewController` in portrait mode. You can override this in your app if you need to.

**Comment by luketomlinson** [comment]
@bhariharan Looking at this line https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/d7de33b8e36dacf1a08b651180b36c9cd4c36a7a/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Login/SFLoginViewController.m#L245, it doesn't look like that is actually an override point. I think this has to do with the way modals are now presented in iOS 13

**Comment by luketomlinson** [comment]
This also worked for us in landscape prior to iOS 13.

**Comment by bhariharan** [comment]
@luketomlinson Ah yes, we added some fixes for modals on `iOS 13` in our `dev` branch. `iOS 13` support will be in our upcoming release, `Mobile SDK 7.3`.

**Comment by luketomlinson** [comment]
great. thanks @bhariharan

**Comment by az-oolloow** [comment]
@bhariharan when i have the LoginViewController in the SmartSync Explorer, it rotates correctly. but in my app, the status bar rotates, but the UI doesn't...

**Comment by az-oolloow** [comment]
For me, even with SDK 7.3.0 i had to subclass logincontroller and override a couple of properties like so:

```
class MyLoginViewController : SalesforceLoginViewController {
    override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
        return .all
    }
    
    override var shouldAutorotate: Bool {
        return true
    }
}
```

Didn't need to do this before iOS 13 SDK.
