### ISSUE TITLE
Adding cordova-splashscreen plugin causes error: Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SFHybridViewController shouldAutorotateDefaultValue]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by gspei** [forcedotcom/SalesforceMobileSDK-iOS#2996]
Please fill out the following details:

1. Version of Mobile SDK Used: 
com.salesforce 7.1.2 "SalesforceMobileSDK Plugins"

2. Issue found in Native App or Hybrid App:
Hybrid Remote

3. OS Version:
iOS 12.4

4. Device:
iPhone XR (in iOS Simulator)

5. Steps to reproduce:
`$ forcehybrid create --platform=ios,android --apptype=hybrid_remote --appname=myapp --packagename=com.example.myapp --organization='mycorp' --startpage='/s'`

Compile, run, test that it works by logging in to a Community URL. PASS

`$ cordova plugin add cordova-plugin-splashscreen`
`$ cordova prepare`

Compile, run, test that it works by logging in to a Community URL. FAIL 

Note: You have to actually try logging in - the error occurs after a successful login and allowing at the OAuth consent screen. 

6. Actual behavior:
App crashes with error 
`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SFHybridViewController shouldAutorotateDefaultValue]: unrecognized selector sent to instance 0x7fe8a384b400'`

7. Expected Behavior:
App should not break catastrophically when a Cordova plugin is installed

8. Error Log:

`
2019-09-12 22:16:24.033391-0700 myapp[34551:1096331] [SalesforceHybrid] CLASS: SFHybridViewController [SFHybridViewController viewDidLoad]: Initiating web state cleanup strategy before loading start page.
2019-09-12 22:16:24.033521-0700 myapp[34551:1096331] [SalesforceHybrid] CLASS: SFHybridViewController [SFHybridViewController webStateCleanupStrategy]: resetting session cookies.
2019-09-12 22:16:24.034235-0700 myapp[34551:1096331] [SalesforceSDKCore] CLASS: SFSDKWebViewStateManager addSidCookieForDomain: .salesforce.com
2019-09-12 22:16:24.034455-0700 myapp[34551:1096331] [SalesforceSDKCore] CLASS: SFSDKWebViewStateManager addSidCookieForDomain: .force.com
2019-09-12 22:16:24.034554-0700 myapp[34551:1096331] [SalesforceSDKCore] CLASS: SFSDKWebViewStateManager addSidCookieForDomain: .cloudforce.com
2019-09-12 22:16:24.149767-0700 myapp[34551:1096331] [CDVTimer][console] 0.148892ms
2019-09-12 22:16:24.150217-0700 myapp[34551:1096331] [CDVTimer][handleopenurl] 0.278950ms
2019-09-12 22:16:24.154545-0700 myapp[34551:1096331] [CDVTimer][intentandnavigationfilter] 4.197001ms
2019-09-12 22:16:24.154782-0700 myapp[34551:1096331] [CDVTimer][gesturehandler] 0.088930ms
2019-09-12 22:16:24.155120-0700 myapp[34551:1096331] -[SFHybridViewController shouldAutorotateDefaultValue]: unrecognized selector sent to instance 0x7fe8a384b400
2019-09-12 22:16:24.160473-0700 myapp[34551:1096331] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SFHybridViewController shouldAutorotateDefaultValue]: unrecognized selector sent to instance 0x7fe8a384b400'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001110898db __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000110602ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001110a7c94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   UIKitCore                           0x000000011b062235 -[UIResponder doesNotRecognizeSelector:] + 287
	4   CoreFoundation                      0x000000011108e623 ___forwarding___ + 1443
	5   CoreFoundation                      0x0000000111090418 _CF_forwarding_prep_0 + 120
	6   myapp                              0x000000010dc7ca81 -[CDVSplashScreen createViews] + 145
	7   myapp                              0x000000010dc7f570 -[CDVSplashScreen setVisible:andForce:] + 1312
	8   myapp                              0x000000010dc7f03d -[CDVSplashScreen setVisible:] + 61
	9   myapp                              0x000000010dc7c736 -[CDVSplashScreen pluginInitialize] + 150
	10  Cordova                             0x000000010dffc073 -[CDVViewController registerPlugin:withClassName:] + 323
	11  Cordova                             0x000000010dffc5b2 -[CDVViewController getCommandInstance:] + 738
	12  Cordova                             0x000000010dff94ac -[CDVViewController viewDidLoad] + 1420
	13  SalesforceHybridSDK                 0x000000010e82bada -[SFHybridViewController viewDidLoad] + 1594
	14  UIKitCore                           0x000000011aa330f7 -[UIViewController loadViewIfRequired] + 1183
	15  UIKitCore                           0x000000011aa33524 -[UIViewController view] + 27
	16  UIKitCore                           0x000000011b06c22b -[UIWindow addRootViewControllerViewIfPossible] + 122
	17  UIKitCore                           0x000000011b06d1db -[UIWindow setRootViewController:] + 432
	18  myapp                              0x000000010dc7b667 -[AppDelegate(SalesforceHybridSDK) setupRootViewController] + 327
	19  myapp                              0x000000010dc7b06d __93-[AppDelegate(SalesforceHybridSDK) sfsdk_swizzled_application:didFinishLaunchingWithOptions:]_block_invoke + 45
	20  SalesforceSDKCore                   0x000000010e90815b __38+[SFSDKAuthHelper passcodeValidation:]_block_invoke + 107
	21  SalesforceSDKCore                   0x000000010e953fc9 +[SFSecurityLockout unlockSuccessPostProcessing:] + 249
	22  SalesforceSDKCore                   0x000000010e95265d +[SFSecurityLockout lock] + 317
	23  SalesforceSDKCore                   0x000000010e9080c3 +[SFSDKAuthHelper passcodeValidation:] + 275
	24  SalesforceSDKCore                   0x000000010e907db1 +[SFSDKAuthHelper loginIfRequired:] + 705
	25  myapp                              0x000000010dc7af9d -[AppDelegate(SalesforceHybridSDK) sfsdk_swizzled_application:didFinishLaunchingWithOptions:] + 749
	26  UIKitCore                           0x000000011b02d731 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 280
	27  UIKitCore                           0x000000011b02f0cd -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3932
	28  UIKitCore                           0x000000011b0344e6 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1617
	29  UIKitCore                           0x000000011a878a4e __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 904
	30  UIKitCore                           0x000000011a881346 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
	31  UIKitCore                           0x000000011a878664 -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 236
	32  UIKitCore                           0x000000011a878fc0 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 1091
	33  UIKitCore                           0x000000011a877332 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 782
	34  UIKitCore                           0x000000011a876fe9 -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 433
	35  UIKitCore                           0x000000011a87bd2e __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 576
	36  UIKitCore                           0x000000011a87c988 _performActionsWithDelayForTransitionContext + 100
	37  UIKitCore                           0x000000011a87ba95 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 223
	38  UIKitCore                           0x000000011a880a48 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	39  UIKitCore                           0x000000011b032dc8 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 514
	40  UIKitCore                           0x000000011abea02f -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
	41  FrontBoardServices                  0x0000000118734d25 -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 448
	42  FrontBoardServices                  0x000000011873ead6 __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 283
	43  FrontBoardServices                  0x000000011873e300 __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke + 53
	44  libdispatch.dylib                   0x0000000111d65db5 _dispatch_client_callout + 8
	45  libdispatch.dylib                   0x0000000111d692ba _dispatch_block_invoke_direct + 300
	46  FrontBoardServices                  0x00000001187700da __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	47  FrontBoardServices                  0x000000011876fd92 -[FBSSerialQueue _performNext] + 451
	48  FrontBoardServices                  0x0000000118770327 -[FBSSerialQueue _performNextFromRunLoopSource] + 42
	49  CoreFoundation                      0x0000000110ff0db1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	50  CoreFoundation                      0x0000000110ff0633 __CFRunLoopDoSources0 + 243
	51  CoreFoundation                      0x0000000110feacef __CFRunLoopRun + 1231
	52  CoreFoundation                      0x0000000110fea4d2 CFRunLoopRunSpecific + 626
	53  GraphicsServices                    0x00000001173ab2fe GSEventRunModal + 65
	54  UIKitCore                           0x000000011b035fc2 UIApplicationMain + 140
	55  myapp                              0x000000010dc75001 main + 65
	56  libdyld.dylib                       0x0000000111dda541 start + 1
	57  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
`

**Comment by wmathurin** [comment]
When you use Mobile SDK, `SFHybridViewController` is used instead of `CDVViewController`.
It looks like the SplashScreen plugin adds some methods (and does some swizzling) on `CDVViewController` (see https://github.com/apache/cordova-plugin-splashscreen/blob/master/src/ios/CDVViewController%2BSplashScreen.m) which is the reason you get the error above.
To make it work, create a `SFHybridViewController+SplashScreen.m` and `SFHybridViewController+SplashScreen.h` to you application which mirrors `CDVViewControoler+SplashScreen` but extends `SFHybridViewController` instead of `CDVViewController`.

**Comment by gspei** [comment]
Thanks @wmathurin - will give it a try.

**Comment by vsvikram** [comment]
@wmathurin, I'm using splashscreen plugin in my hybrid app with the Salesforce SDK Cordova plugin. It is working with SDK 7.2 but in newly generated project with SDK 7.3, I'm getting the same error -[SFHybridViewController shouldAutorotateDefaultValue]: unrecognized selector sent to instance. 

Can you please confirm if this is an issue and need to use SDK 7.2?

**Comment by wmathurin** [comment]
@vsvikram please look at my earlier post: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2996#issuecomment-534225544

**Comment by vsvikram** [comment]
@wmathurin, Strangely, I have created another forcehybrid project with SDK 7.3 which has splash screen plugin installed as well (latest version 5.0.3) and it is building without any errors.

Also, I've tried using your steps described above. I'm getting below error in Xcode logs:

`[SalesforceSDKCore] CLASS: SFSDKAuthConfigUtil Org config request failed with error: Status Code: 404
2019-11-19 15:33:02.465871+0530 Edge[49423:10486033] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2019-11-19 15:33:02.467484+0530 Edge[49423:10486033] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service`

Can you please help what is wrong here?

**Comment by jake-moritz-trifecta** [comment]
@vsvikram Did you ever find a solution for this?

**Comment by vsvikram** [comment]
@jake-moritz-trifecta , This was resolved for me but in my case, it wasn't an issue with splash screen plugin as the project is building successfully now with splash screen plugin. I had tried creating a new project with forcehybrid and removed `libCordova.a` from the `Targets > [Your Project Name] > Build Phases > Link Binary With Libraries >`.

**Comment by jake-moritz-trifecta** [comment]
@vsvikram This worked for me. How did you come across this solution? Do you know if this leads to any issues?

**Comment by jake-moritz-trifecta** [comment]
In order to automate the above solution, we run the following code in a Node script that runs on Cordova's `after_prepare` hook:

```
const fs = require("fs");
const xcode = require("xcode");
const projectPath = `./platforms/ios/<appname>.xcodeproj/project.pbxproj`;
const myProj = xcode.project(projectPath);

 myProj.parseSync();
 myProj.addToBuildSettings("EXCLUDED_SOURCE_FILE_NAMES", "libCordova.a");
 fs.writeFileSync(projectPath, myProj.writeSync());
```

**Comment by jsitu** [comment]
@vsvikram I still got the same error that you got after I removed `libCordova.a` from `Link Binary With Libraries`, any ideas?

**Comment by MattSynaptic** [comment]
> @jake-moritz-trifecta , This was resolved for me but in my case, it wasn't an issue with splash screen plugin as the project is building successfully now with splash screen plugin. I had tried creating a new project with forcehybrid and removed `libCordova.a` from the `Targets > [Your Project Name] > Build Phases > Link Binary With Libraries >`.

This worked for me.
