### ISSUE TITLE
UIWebView Deprecation Strategy

### ISSUE THREAD

**Issue by gspei** [forcedotcom/SalesforceMobileSDK-iOS#3004]
What is Salesforce's recommended direction with regards to the recent UIWebView deprecation warnings that Apple is now sending out when apps are uploaded to the App Store / Testflight etc.?

https://github.com/apache/cordova-discuss/pull/110 and https://ionicframework.com/blog/understanding-itms-90809-uiwebview-api-deprecation/ for some additional background/context.

----
Please fill out the following details:

1. Version of Mobile SDK Used: 
2. Issue found in Native App or Hybrid App:
Hybrid

3. OS Version:
4. Device:
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

**Comment by az-oolloow** [comment]
Supposedly fixed in the upcoming 7.3 SDK: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2983

**Comment by wmathurin** [comment]
FYI We just released 7.3.

**Comment by bhariharan** [comment]
Yes - `Mobile SDK 7.3.0` is live as of this evening.

**Comment by gspei** [comment]
A potentially stupid question from my side - would 7.3.0 actually help me if I'm building a Hybrid app? I was under the impression that further upstream in Cordova-land they still had references to UIWebView so even if the Salesforce Mobile SDK doesn't contain any references, Hybrid apps would still be affected? Or am I misunderstanding something here? 

@az-oolloow appears to be working with native apps which I presume would omit all the Cordova related references.

**Comment by bhariharan** [comment]
@gspei You're correct - we're evaluating how this affects our hybrid apps. We will be removing `UIWebView` references from our hybrid library in `8.0`. For `Cordova`, we will need to rely on them to remove `UIWebView`. Maybe file an issue [here](https://github.com/apache/cordova-ios) for them to look at?

**Comment by gspei** [comment]
Thanks @bhariharan
