### ISSUE TITLE
Sign In with Apple requirements

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#3005]
There has been a number of reports online saying that Apple will soon require all apps providing SSO to offer a Sign in with Apple support

The developer documentation is available here:
https://developer.apple.com/sign-in-with-apple/get-started/
https://developer.apple.com/documentation/signinwithapplerestapi

How can this be integrated with Salesforce when the App is built as a Native Swift app with Salesforce Mobile SDK?

**Comment by az-oolloow** [comment]
This is the specific Apple Guideline requirement link
https://developer.apple.com/app-store/review/guidelines/#sign-in-with-apple

Looking at it, it may be argued that an app built with SF SDK falls under 
```
Sign in with Apple is not required if:
....
Your app is an education, enterprise, or business app that requires the user to sign in with an existing education or enterprise account.
```

But I guess it'd be good to hear confirmation from SF MobileSDK developers or SFDC directly

**Comment by wmathurin** [comment]
That's our understanding too. But we can't speak for Apple though.
