### ISSUE TITLE
CocoaPods could not find compatible versions for pod "SalesforceSDKCommon": >   In Podfile: >     SalesforceSDKCommon (from `https://github.com/forcedotcom/SalesforceMobileSDK-iOS`, tag `v7.3.0`)

### ISSUE THREAD

**Issue by frankvlocity** [forcedotcom/SalesforceMobileSDK-iOS#3009]
I am building a v7.3 Hybrid project from scratch hoping it is much easier than upgrade for us. But I am running into this issue. Hope you know the answer. 

> [!] CocoaPods could not find compatible versions for pod "SalesforceSDKCommon":
>   In Podfile:
>     SalesforceSDKCommon (from `https://github.com/forcedotcom/SalesforceMobileSDK-iOS`, tag `v7.3.0`)
> 
> Specs satisfying the `SalesforceSDKCommon (from `https://github.com/forcedotcom/SalesforceMobileSDK-iOS`, tag `v7.3.0`)` dependency were found, but they required a higher minimum deployment target.

The command I run:

> forcehybrid create --platform=ios,android --apptype=hybrid_local --appname=vlocity --packagename=com.vlocity.hybrid --organization="Vlocity, Inc." --outputdir=MobileTest

But if I run the same command generate iOS native app, it works - build and run well.

> forceios create --apptype="native_swift" --appname="packagetest" --packagename="com.acme.mobile_apps" --organization="Acme Widgets, Inc." --outputdir="PackageTest"

Please help, Thank you so much!

**Comment by wmathurin** [comment]
I just tried your command and it worked fine on my machine.
Could you check the version of pod you are running? (I'm running 1.7.5).
The force* tools check that you have 1.7 or above but in reality 1.7.2 or above is required?

**Comment by frankvlocity** [comment]
@wmathurin  I got it working now. My pod version is 1.8.0.beta.2. I had to change the Podfile first line from `platform :ios, 'v7.3.0' to ` to `platform :ios, '11.0'` manually, then run pod install.

**Comment by wmathurin** [comment]
We fixed the plugin.xml (see https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/pull/478). So if you generate a new app, you will not get the invalid ios version in the pod file.

**Comment by frankvlocity** [comment]
Thank you for your quick fix!

**Comment by simongt** [comment]
> We fixed the plugin.xml (see [forcedotcom/SalesforceMobileSDK-CordovaPlugin#478](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/pull/478)). So if you generate a new app, you will not get the invalid ios version in the pod file.

Hi @wmathurin. Encountering this same error when spinning up the iOS app from `forcereact` boilerplate for Mobile SDK v9.1.0 (React Native).

```
forcereact createWithTemplate --platform=ios,android --templaterepouri=ReactNativeTypeScriptTemplate --appname=***** --packagename=com.*****.***** --organization="*****" --outputdir='./mobile'
```

Android app spins up fine, but iOS gives this error:

```
[!] CocoaPods could not find compatible versions for pod "SalesforceSDKCommon":
  In snapshot (Podfile.lock):
    SalesforceSDKCommon (from `../mobile_sdk/SalesforceMobileSDK-iOS`)

  In Podfile:
    SalesforceAnalytics (from `../mobile_sdk/SalesforceMobileSDK-iOS`) was resolved to 9.1.0, which depends on
      SalesforceAnalytics/SalesforceAnalytics (= 9.1.0) was resolved to 9.1.0, which depends on
        SalesforceSDKCommon (~> 9.1.0)

    SalesforceReact (from `../node_modules/react-native-force`) was resolved to 9.0.0, which depends on
      SalesforceReact/SalesforceReact (= 9.0.0) was resolved to 9.0.0, which depends on
        SalesforceSDKCommon (~> 9.0.0)

    SalesforceSDKCommon (from `../mobile_sdk/SalesforceMobileSDK-iOS`)
```

Did not encounter this issue in v9.0.0.

**Comment by wmathurin** [comment]
We have not released 9.1 yet (see https://www.npmjs.com/package/forcereact/v/9.0.0).
Did you install/run forcereact from sources?

**Comment by simongt** [comment]
> We have not released 9.1 yet (see https://www.npmjs.com/package/forcereact/v/9.0.0).
> Did you install/run forcereact from sources?

Yes, I installed forcereact via:

```yarn global add forcereact@latest```

**Comment by wmathurin** [comment]
I just tried that, I don't see any 9.1 references:
```
$ yarn global add forcereact@latest
yarn global v1.22.10
warning package.json: No license field
[1/4] 🔍  Resolving packages...
warning forcereact > jsonlint > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "forcereact@9.0.0" with binaries:
      - forcereact
✨  Done in 6.11s.
$ forcereact version
forcereact version 9.0.0
$ forcereact create
Enter the target platform(s) separated by commas (ios, android): ios
Enter your application type (react_native_typescript or react_native, leave empty for react_native_typescript): 
Enter your application name: TestApp
Enter your package name: com.salesforce
Enter your organization name (Acme, Inc.): Acme
Enter output directory for your app (leave empty for the current directory): 

********************************************************************************
*
*   Creating ios react_native application using Salesforce Mobile SDK
*     with app name:        TestApp
*          package name:    com.salesforce
*          organization:    Acme
*   
*     in:                   TestApp
*   
*     from template repo:   https://github.com/forcedotcom/SalesforceMobileSDK-Templates#v9.0.0
*          template path:   ReactNativeTypeScriptTemplate
*
********************************************************************************

(...)
Downloading dependencies
Installing MobileSync (9.0.0)
(...)
Installing SalesforceAnalytics (9.0.0)
Installing SalesforceReact (9.0.0)
Installing SalesforceSDKCommon (9.0.0)
Installing SalesforceSDKCore (9.0.0)
Installing SmartStore (9.0.0)

********************************************************************************
*
*   Next steps for ios:
*   
*   Your application project is ready in TestApp.
*   To use your new application in XCode, do the following:
*      - open TestApp/ios/TestApp.xcworkspace in XCode
*      - build and run
*   Before you ship, make sure to plug your OAuth Client ID and Callback URI,
*   and OAuth Scopes into TestApp/ios/TestApp/bootconfig.plist
*
********************************************************************************

```

**Comment by simongt** [comment]
Thank you for the speedy effort @wmathurin!

I resolved it by cleanly reinstalling forcereact and clearing yarn cache. I had updated to 9.1 directly within the submodules at some point and it must've not cleared from cache even after generating boilerplate for a new project.

**Comment by simongt** [comment]
> Thank you for the speedy effort @wmathurin!
> 
> I resolved it by cleanly reinstalling forcereact and clearing yarn cache. I had updated to 9.1 directly within the submodules at some point and it must've not cleared from cache even after generating boilerplate for a new project.

If it helps, I discovered that my `postinstall` script was the reason for this inadvertent update to 9.1:
```
  "scripts": {
    ...
    "postinstall": "git submodule init && git submodule update",
    ...
  },
```
