### ISSUE TITLE
Upgrade to SDK 7.3.0 causing Build Failure: Expected method to read dictionary element ...

### ISSUE THREAD

**Issue by MichaelWTA** [forcedotcom/SalesforceMobileSDK-iOS#3020]
1. Version of Mobile SDK Used: 7.3.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 12.4
4. Device: iPad Air
5. Steps to reproduce: Attempt to build to simulator
6. Actual behavior: Failure to build
7. Expected Behavior: Succeed to build
8. Error Log: 

2 issues, both as follows:

`Expected method to read dictionary element not found on object of type 'SFSDKSafeMutableDictionary *'`

This occurs in `SFNetwork.m` on lines 75 and 182, both are:
`SFNetwork *sharedInstance = sharedInstances[identifier];`

Using XCode v 10.3

Lemme know if you'd like any extra info.

**Comment by wmathurin** [comment]
We are not seeing the issue. How did you generate your application?

**Comment by MichaelWTA** [comment]
I tried to reproduce and it worked this time.
You're magic, thanks ✨

**Comment by MichaelWTA** [comment]
Seems like the difference this time was I used pod update instead of pod install
