### ISSUE TITLE
Query: Salesforce SDK need notifications to work?

### ISSUE THREAD

**Issue by geekandt** [forcedotcom/SalesforceMobileSDK-iOS#3029]
Please fill out the following details:

1. Version of Mobile SDK Used: MobileSDK 6.2.0
2. Issue found in Native App or Hybrid App: Hybrid App -LinktgoApp
3. OS Version: iOS 10 and above
4. Device: All Devices
Hi Team,
Our devs need to know:

Does Salesforce SDK need notifications to work or is it not compulsory?
If it is compulsory, then in what way is it used?

**Comment by wmathurin** [comment]
Notifications are not required.
For more information see https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/push_intro.htm
