### ISSUE TITLE
User cannot create a SF case in LinktGo(Hybrid App) using iOS 13.0

### ISSUE THREAD

**Issue by geekandt** [forcedotcom/SalesforceMobileSDK-iOS#3031]
Please fill out the following details:

1. Version of Mobile SDK Used: MobileSDK 6.2.0
2. Issue found in Native App or Hybrid App: Hybrid App -LinktgoApp
3. OS Version: iOS 13
4. Device: iPhone X
5. Steps to reproduce:
User cannot create a SF case. User cannot "open" the SF snap-in kit page. The page will immediately close itself, after the case form screen is displayed (for a millisecond). Please see attached MP4 screen recording.

6. Actual behavior:
[iOS 13 - iPhone X - Cannot raise a SF case.zip](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/3684252/iOS.13.-.iPhone.X.-.Cannot.raise.a.SF.case.zip)

7. Expected Behavior:
User can open the SG snap-in kit page and create an SF case.

8. Error Log:

**Comment by brandonpage** [comment]
Hi @geekandt, Cases is a product from another team.  [Here is the correct Github url.](https://github.com/forcedotcom/ServiceSDK-iOS).  However, I no longer see an "issues" page for that product so I will let you know where to submit this issue when they get back to me.  Thanks.

**Comment by geekandt** [comment]
Thanks @brandonpage . I was also wondering why there's no issues section anymore. Looking forward on your update.

Thanks

**Comment by geekandt** [comment]
Hi @brandonpage  , any updates if where can i raise issue to serviceSDK team?

**Comment by rumnat** [comment]
Hey guys. When can we expect SDK release with iOS 13 support?

**Comment by rumnat** [comment]
Sorry, my bad. I was asking about ServiceSDK-iOS. The issues are still closed

**Comment by bhariharan** [comment]
@rumnat We can't answer that question, because `ServiceSDK-iOS` is not a project we own or maintain. Please post your questions about `ServiceSDK-iOS` on [their repo](https://github.com/forcedotcom/ServiceSDK-iOS).

**Comment by geekandt** [comment]
@brandonpage do you have updates on where we can riase issues to ServiceSDK-iOS ?

**Comment by bhariharan** [comment]
@geekandt I just posted the link to their GitHub repo in my comment above. ☝️

**Comment by geekandt** [comment]
@bhariharan yes, but there's no 'Issues' section where we can raise our issues. @brandonpage advised me he will let me know where I can submit issue when ServiceSDK team will get back to him.

**Comment by bhariharan** [comment]
@geekandt I'd recommend posting your question on [Salesforce Stack Exchange](https://salesforce.stackexchange.com/).

**Comment by brandonpage** [comment]
@geekandt I just heard back from the ServiceSDK team.  Unfortunately, now to get official support for that product you will need to go through Salesforce Customer Support.  

If you ever have an issue with the Mobile SDK, we'll be here.  Thanks.

**Comment by rumnat** [comment]
@geekandt check the latest release 
https://github.com/forcedotcom/ServiceSDK-iOS/releases/tag/222.0.1

**Comment by geekandt** [comment]
@brandonpage  @bhariharan  hi guys, is there a way to remove this issue ? I accidentally added the name of the app and removed it. However, I think its still keeps the history and can still be searched. Can you please remove this issue?

**Comment by bhariharan** [comment]
@geekandt Sure, will do.
