### ISSUE TITLE
getApexRest request failing

### ISSUE THREAD

**Issue by jaygauten** [forcedotcom/SalesforceMobileSDK-iOS#3032]
**sdk version**: **7.3**

**issue**: getApexRest is failing if url has parameter in the url ie. `/services/apex/endpoint?pageSize=10`

**cause**: the url is appended by '?' even without `queryParams` were passed to `SFRestRequest` class, example url after `prepareRequestForSend` processed the url: `/services/apex/endpoint?pageSize=10?` causing unwanted behavior specially if the last parameter expects a number

**findings**: in the `prepareRequestForSend` method there is logic where it is processing the `queryParams` and appending it to the url, even if no queryParams is passed to the class it will still process the queryParams and append the unwanted '?' into the url.

the logic is `if (self.queryParams) { ... }`, which i think is checking for the truthy value but queryParams is an NSDictionary type so it will always be truthy which causing the issue.

https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/ffa6ca5c31008ca41756eff2a357c45660bdd94d/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/RestAPI/SFRestRequest.m#L184

**Comment by wmathurin** [comment]
We will take a look. Thanks.

**Comment by wmathurin** [comment]
Fixed with: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3034
