### ISSUE TITLE
How to upload files in an iOS app built using Mobile SDK?

### ISSUE THREAD

**Issue by geekandt** [forcedotcom/SalesforceMobileSDK-iOS#3036]
Please fill out the following details:

1. Version of Mobile SDK Used: MobileSDK 6.2.0
2. Issue found in Native App or Hybrid App: Hybrid
3. OS Version: iOS 10 and above
4. Device: All devices

Do you have sample code on how we can upload files in our iOS app?

**Comment by wmathurin** [comment]
Please refer to the documentation https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/files_hybrid.htm
