### ISSUE TITLE
Loading a community page after native ios sdk login

### ISSUE THREAD

**Issue by sunilhs1986** [forcedotcom/SalesforceMobileSDK-iOS#3041]
Hi,

We are trying to achieve a scenario wherein a Customer logs in into a Salesforce IOS SDK and once logged in, he clicks on a link in the app that redirects him to a page on a Community in an IOS Webview. Here he can browse the community page as a logged in user and won’t have to login again.
 
We created a simple iOS native app, which should allow users to login into SF once and then open Lightning community app in a Webview. For this purpose we have implemented below steps:
1. User launches the mobile app;
2. App calls Mobile SDK, which redirects to community login page, where user enters login and password; That allows us to get the access token if this is required.
3. We get an authorization token and pass the community URL + token into WebView.
4. Based on this https://help.salesforce.com/articleView?id=remoteaccess_oauth_web_server_flow.htm&type=5, we tried to pass authorization token as a parameter:
 
<Community Url>services/oauth2/authorize?response_type=<auth token>&client_id=<clientId>&redirect_uri=<redirecturl>
 
However, the above code didn’t work and the user has to login twice. Once on the IOS Native App and second time on the Web view community page. Has anyone implemented this in any project and is aware of how to resolve this? Please let me know.
 
Regards
Sunil

**Comment by wmathurin** [comment]
How did you do step 3? Are you using frontdoor.jsp?

Why are you not starting with an iOS hybrid application? That is what they were built for.

**Comment by wmathurin** [comment]
We haven't heard back from you after last post (with questions / suggestions). So closing issue.
