### ISSUE TITLE
Is Native iOS login supported or planned on being supported?

### ISSUE THREAD

**Issue by MichaelWTA** [forcedotcom/SalesforceMobileSDK-iOS#3044]
Just a question, not an issue.

I'm wondering if we're currently able to create a native iOS login page instead of showing the webview for salesforce authentication. Or, if not, if that's something that may be available in the future.

Thanks!

**Comment by wmathurin** [comment]
Native login is on our roadmap.
Could you tell us more about how you are planning to use it / why you need it?
Thanks!

**Comment by MichaelWTA** [comment]
That's great to hear! Any idea on priority or timeline?

We'd just love to reduce the friction for our users and customize the process for them a bit. Mostly from a branding and feeling perspective.

And webviews are tricky with new devices coming out, and different screen orientations being available or locked. We feel like a native experience would suit our needs better.

**Comment by bhariharan** [comment]
@MichaelWTA No timeline at this time. Keep in mind that a "native login flow" could also involve some level of webview involvement for token exchange (we might be able to get away with a hidden webview in some cases). Also, native login flow will probably not support more advanced use cases like SSO/SAML/cert based login, etc. Have you tried building a custom login page on the Salesforce backend? That's typically our recommendation for branding and customizability of the login page.

**Comment by MichaelWTA** [comment]
Yup, that's what we're currently looking into. Unsure how well it'll work with upcoming darkmode support, etc. but it's a stepping stone =)
