### ISSUE TITLE
Unable to build iOS Hybrid app created app using XCode 11. 

### ISSUE THREAD

**Issue by coolmk09** [forcedotcom/SalesforceMobileSDK-iOS#3047]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.3
2. Issue found in Native App or Hybrid App:Hybrid app
3. OS Version: 13.0
4. Device: All
5. Steps to reproduce: Create an archieve
6. Actual behavior: Getting compilation errors
7. Expected Behavior:Should be able to create an archieve 
8. Error Log: 

> While building module 'Foundation' imported from /Users/mkumar/Desktop/repo/expriements/sdk/7.3/MyApp/platforms/ios/CordovaLib/CordovaLib_Prefix.pch:21:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:44:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFArray.h:49:1: error: unknown type name 'CF_IMPLICIT_BRIDGING_ENABLED'
CF_IMPLICIT_BRIDGING_ENABLED
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFArray.h:50:18: error: expected ';' after top level declarator
CF_EXTERN_C_BEGIN
                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFArray.h:74:47: error: unknown type name 'CFAllocatorRef'
typedef const void *    (*CFArrayRetainCallBack)(CFAllocatorRef allocator, const void *value);
                                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFArray.h:75:41: error: unknown type name 'CFAllocatorRef'
typedef void            (*CFArrayReleaseCallBack)(CFAllocatorRef allocator, const void *value);
                                                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFArray.h:76:21: error: function cannot return function type 'int (const void *)'
typedef CFStringRef     (*CFArrayCopyDescriptionCallBack)(const void *value);
                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFArray.h:77:18: error: function cannot return function type 'int (const void *, const void *)'
typedef Boolean         (*CFArrayEqualCallBack)(const void *value1, const void *value2);
                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFArray.h:79:5: error: unknown type name 'CFIndex'
    CFIndex                             version;
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFArray.h:82:5: error: unknown type name 'CFArrayCopyDescriptionCallBack'
    CFArrayCopyDescriptionCallBack      copyDescription;
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFArray.h:83:5: error: unknown type name 'CFArrayEqualCallBack'; did you mean 'CFArrayRetainCallBack'?
    CFArrayEqualCallBack                equal;
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFArray.h:74:24: note: 'CFArrayRetainCallBack' declared here
typedef const void *    (*CFArrayRetainCallBack)(CFAllocatorRef allocator, const void *value);
                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFArray.h:91:1: error: unknown type name 'CF_EXPORT'
CF_EXPORT
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFArray.h:92:1: error: expected identifier or '('
const CFArrayCallBacks kCFTypeArrayCallBacks;
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFArray.h:108:46: error: expected ';' after top level declarator
typedef const struct CF_BRIDGED_TYPE(NSArray) __CFArray * CFArrayRef;
                                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFArray.h:114:55: error: expected ';' after top level declarator
typedef struct CF_BRIDGED_MUTABLE_TYPE(NSMutableArray) __CFArray * CFMutableArrayRef;
                                                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFArray.h:120:1: error: unknown type name 'CF_EXPORT'
CF_EXPORT
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFArray.h:121:9: error: expected ';' after top level declarator
CFTypeID CFArrayGetTypeID(void);
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFArray.h:173:1: error: unknown type name 'CF_EXPORT'
CF_EXPORT
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFArray.h:174:11: error: expected ';' after top level declarator
CFArrayRef CFArrayCreate(CFAllocatorRef allocator, const void **values, CFIndex numValues, const CFArrayCallBacks *callBacks);
          ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFArray.h:194:1: error: unknown type name 'CF_EXPORT'
CF_EXPORT
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFArray.h:195:11: error: expected ';' after top level declarator
CFArrayRef CFArrayCreateCopy(CFAllocatorRef allocator, CFArrayRef theArray);
          ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
While building module 'Foundation' imported from /Users/mkumar/Desktop/repo/expriements/sdk/7.3/MyApp/platforms/ios/CordovaLib/CordovaLib_Prefix.pch:21:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:10: fatal error: could not build module 'CoreFoundation'
#include <CoreFoundation/CoreFoundation.h>
 ~~~~~~~~^
While building module 'Foundation' imported from /Users/mkumar/Desktop/repo/expriements/sdk/7.3/MyApp/platforms/ios/CordovaLib/CordovaLib_Prefix.pch:21:
While building module 'Security' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLCredential.h:9:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:27:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:28:10: fatal error: could not build module 'CoreFoundation'
#include <CoreFoundation/CFBase.h>
 ~~~~~~~~^
1 error generated.
While building module 'Foundation' imported from /Users/mkumar/Desktop/repo/expriements/sdk/7.3/MyApp/platforms/ios/CordovaLib/CordovaLib_Prefix.pch:21:
While building module 'CFNetwork' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:12:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/CFNetwork.framework/Headers/CFNetwork.h:18:10: fatal error: could not build module 'CoreFoundation'
#include <CoreFoundation/CoreFoundation.h>
 ~~~~~~~~^
1 error generated.
23 errors generated.
/Users/mkumar/Desktop/repo/expriements/sdk/7.3/MyApp/platforms/ios/CordovaLib/CordovaLib_Prefix.pch:21:13: fatal error: could not build module 'Foundation'
    #import <Foundation/Foundation.h>
     ~~~~~~~^
24 errors generated.

> 

I am getting this behaviour with XCode 11 and able to reproduce it with vanilla application. 
Please note app is running fine on simulator issue persists when running it on device or when creating an archieve. 

Is there any reason why this happening? It's a High priority issue we recieved till now not found any solution yet. 

Can someone assist me here ?

Thanks!
Manish Kumar

**Comment by coolmk09** [comment]
@bhariharan any comment?
Here is my system configuration 

Mac OS : 10.14.6 
cocoa pod version : 1.8

**Comment by bhariharan** [comment]
We have internal hybrid apps built on `Mobile SDK 7.3.0`, and we're able to archive them successfully on `Xcode 11`. I don't see anything directly related to `Mobile SDK` at play here. It looks like it's unable to find `CoreFoundation` classes from the error log you have posted. Have you tried embedding/linking `CoreFoundation` in the generated project?

**Comment by coolmk09** [comment]
I have tried to embedding/linking both but nothing work. 

Update: 
I have removed Cocoa pods installation and upgraded Xcode 11.1 and Mac Catalina. This resolves the issue.
