### ISSUE TITLE
SFSDKOAuthTokenEndpointRequest.idToken is never assigned

### ISSUE THREAD

**Issue by scinfu** [forcedotcom/SalesforceMobileSDK-iOS#3053]
1. Version of Mobile SDK Used: Latest commit ffa6ca5
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 12
4. Device: Simulator
5. Steps to reproduce:
	- Ddd scope openid
	- Login
	- Call SFSDKOAuth2.openIDToken(forRefresh: MYREQUEST)
	- Response in swift is an empty string, SFSDKOAuthTokenEndpointRequest.idToken is never assigned 

SFSDKOAuthTokenEndpointRequest.idToken is never assigned, SFSDKAuthUtilTests.testOpenIDToken test passes because in swift it returns an empty string while the test is only if it is null.

**Comment by bhariharan** [comment]
The fix will be in `Mobile SDk 8.0`. Thanks!
