### ISSUE TITLE
Correct way to deprecate setSessionConfiguration

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#3056]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.3.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: iOS 13
4. Device: iPad Pro
5. Steps to reproduce: n/a
6. Actual behavior: n/a
7. Expected Behavior: n/a
8. Error Log: n/a

I have the following code since before SDK 7.3:
```
        let config = URLSessionConfiguration.default
        config.allowsCellularAccess = true
        config.timeoutIntervalForRequest = 300.0
        config.timeoutIntervalForResource = 300.0
        config.httpMaximumConnectionsPerHost = 50
        config.requestCachePolicy = .reloadIgnoringLocalCacheData
        config.waitsForConnectivity = true
        
        Network.setSessionConfiguration(config)
```

I am now getting the deprecation warning:
> 'setSessionConfiguration' is deprecated: Deprecated in Salesforce Mobile SDK 7.3 and will be removed in Salesforce Mobile SDK 8.0. Use setSessionConfiguration:identifier instead

what session identifier should i use so that the session configuration i pass in is used by ALL the HTTP requests made by SDK?

**Comment by wmathurin** [comment]
You can call it whatever you want. Just use that name consistently.

**Comment by az-oolloow** [comment]
@wmathurin sorry, i never actually myself use those names? i am just saying, for example,

```
RestClient.shared.request(forQuery: "SELECT Something", apiVersion: "myVersionHere")
```

And i want all those requests to then use the right session config, which worked fine before...

**Comment by wmathurin** [comment]
I understand your question.
Simply replace
```swift
Network.setSessionConfiguration(config)
```
with
```swift
Network.setSessionConfiguration(config, identifier:NetworkEphemeralInstanceIdentifier)
```

**Comment by az-oolloow** [comment]
Great, i will test to see that it works and report back if there are any issues. at least my compile time warning is gone.
