### ISSUE TITLE
Push notification connected app definition not working

### ISSUE THREAD

**Issue by coolmk09** [forcedotcom/SalesforceMobileSDK-iOS#3059]
Please fill out the following details:
**CRITICAL PRIORITY ISSUE**

1. Version of Mobile SDK Used: 7.3
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: Latest
4. Device: All
5. Steps to reproduce: Create a trigger to send push notification using the connected app. 
6. Actual behavior: This requires me to use a different connected app every time when I deployed to client org that results in different consumer key and associated bundle Id. 
7. Expected Behavior: There should be one connected app definition, app should be able to install on client org and can send push notification based on developer connected org. 
8. Error Log: NA

Hi all, 

We have recently implemented Push notification functionality to our hybrid mobile application developed using Salesforce Mobile SDK. While developing Push notification we have created a new connected app and test the workflow by writing a trigger, everything goes fine until you are in same org. 

For production, we already have a connected app as part of manage package, this app is deployed to client org. I have made push notification related changes in my managed connected app, but when trying to execute the trigger it's unable to use the connected app name
I have tried both API name 

> msg.send('managepackagestring__ConnectedAppName', users);

and 

> msg.send('ConnectedAppName', users);

but nothing works, the trigger is unable to verify the connected app. Is there anything that I am missing? 

I don't think this requires separate IPA for each org, as a client can have multiple sandboxes or production environments. 

Please help me to resolve the issue. We have a CRITICAL deadline to complete this. 

@bhariharan 

Thanks
Manish Kumar

**Comment by bhariharan** [comment]
@coolmk09 Apex push notifications are designed to work only in the org that the connected app is created in. This is by design for security reasons. You can not create a connected app in an org and create triggers on that org, install the connected app in a different org through a managed package and expect the triggers to work there.

**Comment by coolmk09** [comment]
Hi @bhariharan, thanks for the quick comment. I have a concern here. 

I have multiple client using my application and every client has 5-10 salesforce environment. Does it require me to create different IPA with different bundle Id for each org? 

Its a big business case. 
is there any workaround?

**Comment by coolmk09** [comment]
How do I support push notification for AppStore/PlayStore version?

**Comment by bhariharan** [comment]
@coolmk09 As long as the triggers and the connected app are a part of the same managed package, it should work. Basically, the only restriction is that the code that sends push and the application are a part of the same namespace.
