### ISSUE TITLE
Crash UIApplicationInvalidInterfaceOrientation in -[UIViewController setInterfaceOrientation:]

### ISSUE THREAD

**Issue by MichaelWTA** [forcedotcom/SalesforceMobileSDK-iOS#3060]
Similar to old ticket that was abandoned:
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2723

We only support landscape in our app by setting `Supported interface orientations (iPad)` in our `info.plist` file.

1. Version of Mobile SDK Used: 7.3.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 12.4.1
4. Device: iPad Air 2
5. Steps to reproduce: Unknown. Seems to occur randomly on SF login screen. One report reads as follows:
> opened the app (horizontally), SF SSO tried to go vertically, I turned the iPad vertically and then horizontaly, app crashed (no message)
6. Actual behavior: Crash with no message
7. Expected Behavior: Don't crash or try to present vertical login screen
8. Error Log:

> Last Exception BackTrace: UIApplicationInvalidInterfaceOrientation: Supported orientations has no common orientation with the application, and [UIAlertController shouldAutorotate] is returning YES

> 0	CoreFoundation	0x000000020061527c	__exceptionPreprocess
> 1	libobjc.A.dylib	0x00000001ff7ef9f4	objc_exception_throw
> 2	CoreFoundation	0x000000020051f4ac	+[NSException raise:format:]
> 3	UIKitCore	0x000000022cd0210c	-[UIViewController __supportedInterfaceOrientations]
> 	4	UIKitCore	0x000000022cd02668	-[UIViewController __withSupportedInterfaceOrientation:apply:]
> 5	UIKitCore	0x000000022cd02e8c	-[UIViewController setInterfaceOrientation:]
> 6	UIKitCore	0x000000022cceda88	-[UIViewController viewDidMoveToWindow:shouldAppearOrDisappear:]
> 7	UIKitCore	0x000000022d71e340	-[UIView(Internal) _didMoveFromWindow:toWindow:]
> 8	UIKitCore	0x000000022d711b20	__45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke
> 9	Foundation	0x0000000200f8faf0	-[NSISEngine withBehaviors:performModifications:]
> 10	UIKitCore	0x000000022d711a04	-[UIView(Hierarchy) _postMovedFromSuperview:]
> 11	UIKitCore	0x000000022d720e54	-[UIView(Internal) _addSubview:positioned:relativeTo:]
> 12	UIKitCore	0x000000022ca0b190	-[_UIAlertControllerPresentationController presentationTransitionWillBegin]
> 13	UIKitCore	0x000000022cc182b4	__71-[UIPresentationController _initViewHierarchyForPresentationSuperview:]_block_invoke
> 14	UIKitCore	0x000000022cc15e00	__56-[UIPresentationController runTransitionForCurrentState]_block_invoke
> 15	UIKitCore	0x000000022d29ade8	_runAfterCACommitDeferredBlocks
> 16	UIKitCore	0x000000022d289938	_cleanUpAfterCAFlushAndRunDeferredBlocks
> 17	UIKitCore	0x000000022d2b67a8	_afterCACommitHandler
> 18	CoreFoundation	0x00000002005a65f4	__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
> 19	CoreFoundation	0x00000002005a131c	__CFRunLoopDoObservers
> 20	CoreFoundation	0x00000002005a1898	__CFRunLoopRun
> 21	CoreFoundation	0x00000002005a10ac	CFRunLoopRunSpecific
> 22	GraphicsServices	0x00000002027a1798	GSEventRunModal
> 23	UIKitCore	0x000000022d28f974	UIApplicationMain
> 24	m360	0x000000010013a864	main
> 25	libdyld.dylib	0x00000002000668dc	start

**Comment by MichaelWTA** [comment]
This is a great comprehensive explanation of what’s happening.

https://stackoverflow.com/questions/32169216/ios-error-supported-orientations-has-no-common-orientation-with-the-application

In `SFLoginViewController.m` line 247
`- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
    return UIInterfaceOrientationMaskPortrait;
}`

**Comment by az-oolloow** [comment]
@MichaelWTA the way we work around it (in Swift) is by declaring our own VC like so:

```
import Foundation
import SmartSync

class WhateverSFLoginViewController : SalesforceLoginViewController {
    override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
        return .all
    }
    
    override var shouldAutorotate: Bool {
        return true
    }
}
```

And in AppDelegate:

```
        UserAccountManager.shared.loginViewControllerConfig.loginViewControllerCreationBlock = {
            return WhateverSFLoginViewController();
        }
```

**Comment by MichaelWTA** [comment]
This issue is also being discussed here: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3063

An open question remains:
`It would be great if this was documented clearly somewhere so that users of your SDK don't end up with random crashes in their apps.

Also, is there a reason for only supporting portrait mode? Or a plan to support landscape mode in the future?`

**Comment by wmathurin** [comment]
This is fixed in dev. See https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3319. It will be part of our next release (9.0).
