### ISSUE TITLE
User is shown Allow Access screen when using app built with SDK 7.3

### ISSUE THREAD

**Issue by bryonCatalyst** [forcedotcom/SalesforceMobileSDK-iOS#3062]
Please fill out the following details:

I'm wondering if there is anything in SDK 7.3 that would cause pre-authorized community users to be shown the Allow Access screen after successful login when accessing an org.  A version of our app pointed at the same org (built with SDK version 6.2) does not show the Allow Access screen. 

1. Version of Mobile SDK Used: 7.3
2. Issue found in Native App or Hybrid App: React Native / iOS-only
3. OS Version: 12, 13
4. Device: iPhone X, iOS simulator

5. Steps to reproduce: 
We have a mobile app that community users log into. We are upgrading it to use SDK 7.3 from 6.2. We have the users set to pre-authorize access in the connected app settings.  In our production environment, the old version of the app authenticates the user immediately after successful login, but when I point the new build of the app (that uses 7.3 f the SDK) the user is presented with a screen that asked the user to allow access.

6. Actual behavior: user logs in and is presented the 'Allow Access' screen
7. Expected Behavior: user logs in and is granted immediate access to the app functionality

8. Error Log:  I see these messages in the console:

`2019-10-22 15:52:55.369272-0500 app[25624:350833] [SalesforceSDKCore] CLASS: SFOAuthCoordinator webView:didStartProvisionalNavigation: host=myhost.com : path=/secur/frontdoor.jsp
2019-10-22 15:52:56.453577-0500 app[25624:350833] [SalesforceSDKCore] CLASS: SFOAuthCoordinator webView:didStartProvisionalNavigation: host=myhost.com : path=/setup/secur/RemoteAccessAuthorizationPage.apexp
2019-10-22 15:52:58.623772-0500 app[25624:350833] [SalesforceSDKCore] CLASS: SFOAuthCoordinator webView:didStartProvisionalNavigation: host=myhost.com : path=/_ui/identity/oauth/ui/AuthorizationPage`

**Comment by wmathurin** [comment]
The showing or not of the consent screen is completely controlled on the server side (by pre-authorizing the profile https://success.salesforce.com/answers?id=9063A000000icyoQAA). 
During login, the SDK builds the authorization URL, loads it in a web view and then wait for the web view to go to the redirect URL. It has no influence on the steps in between.
Please make sure your test user is indeed pre authorized on the org you are login into.

**Comment by bryonCatalyst** [comment]
Ok, thanks for the info - I'll do some more checking.  Although the same user can log into the same org via the same connected app using 6.2 and they don't see the screen - the version based on 7.3 SDK shows the screen.  Also, the Android version of the app does not show the authorization screen (both the build using version 6.2 and the build version using 7.3).  I'll look at the link and see if I can figure out what's going on.  Thanks again.

**Comment by wmathurin** [comment]
Can you double check that all three apps are using the same oauth consumer key? 
It’s in the bootconfig.plist file on iOS and in the bootconfig.json file on Android. Maybe you forgot to update that file in your 7.3 app and it is using the default mobile SDK sample app connected app as a result?

**Comment by bryonCatalyst** [comment]
Ok, I'll check on that.  Also, it appears that the auth session is creating a new one every time, on the user record, rather than reusing the existing one.  I'll be right back!  :)

**Comment by bryonCatalyst** [comment]
The android app has a different Consumer Key (because both apps use Push Notifications)
The iOS 6.2 app and the iOS 7.3 app are both using the same consumer key.

**Comment by bryonCatalyst** [comment]
Here's some more info (if it is helpful):
Our server instance is NA21 (Production Instance)

On a different QA org, the iOS app with 7.3 does NOT show the authorization screen.
That org is a 'Developer' org on CS32

**Comment by bryonCatalyst** [comment]
Maybe this is a server issue?
Here's what I tried:

- I configured the iOS app to point to a different org, and here's a recap of what I'm seeing:

- QA (developer instance on CS32): no authorization screen is shown (Good)
- UAT environment (a 'Full Copy' instance located on CS33) - authorization screen is shown after authenticating - BAD)
- Prod (Production instance on NA21) - authorization screen is shown after authenticating (BAD)

I hope this is helpful - perhaps it is a server-side problem?

**Comment by wmathurin** [comment]
The pre-authorizing of certain user profiles (so that the consent screen is skipped) is an org level setting, did you make sure that it was done in your various orgs?

**Comment by bryonCatalyst** [comment]
Yes, double checked that - we've had these orgs set up for over. year now, and they all look the same.  I noticed this error on the environments that show the auth screen:

`Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service`

When I log into the environment where the Auth screen is not shown, I don't see any of these error issues - could Thisbe related to the move to WKWebView?

**Comment by bryonCatalyst** [comment]
I analyzed logs in the Xcode console for the login process for QA and Prod orgs - maybe you can see from these what I'm missing?

In the example that works, we don't see any mention of 'SFIdentityCoordinator:Starting identity request at...'

QA - Works
![Screen Shot 2019-10-23 at 11 43 29 AM](https://user-images.githubusercontent.com/49171610/67415678-0f738900-f58b-11e9-9d83-db911c5ccca0.png)

Prod - Shows Auth screen
![Screen Shot 2019-10-23 at 11 43 48 AM](https://user-images.githubusercontent.com/49171610/67415714-20bc9580-f58b-11e9-9dc3-76acc2e1c328.png)

**Comment by bryonCatalyst** [comment]
I think I see what's happening - I will post a new comment after I check my latest theory - it's likely an issue on my config side of things

**Comment by bryonCatalyst** [comment]
@wmathurin - thank you so much for your help with this!  
Everything is working perfectly, the issue had to do with a script I run on the Xcode build to replace the bootconfig.plist with the correct contents based on build target.  

The script was only copying the correct configuration for the QA environment and so we were essentially supplying the wrong Consumer Key value for the other builds / environments.

Thanks again for all of your help and patience!
