### ISSUE TITLE
Is it possible to create a record and query its field values in a single request?

### ISSUE THREAD

**Issue by Yannmm** [forcedotcom/SalesforceMobileSDK-iOS#3075]
Hi, when I create a record using smart sync and push it to server, the response body only contains a single field: id. Problem is some of fields are populated by server logic, which means my local record is incomplete, even if it's synced up successfully.

How can I ask server to return me both id and other field values? Like Name.

Here is what I upload:
```
{
	"allOrNone": false,
	"compositeRequest": [{
		"body": {
			"Co_Travel_Status__c": "Hold",
			"Account_Name_1__c": "",
			"Area_Sales_Director__c": "005i0000001wr8KAAQ",
			"TM_TS_Name__c": "005i0000001wr9JAAQ",
			"Doctor_Name__c": "",
			"Overall_Comments__c": "",
			"Start_Date__c": "2019-11-01",
			"End_Date__c": "2019-11-01"
		},
		"method": "POST",
		"referenceId": "local_14",
		"url": "\/services\/data\/v44.0\/sobjects\/Co_Travel__c"
	}]
}
```

And here is what I got, only "id", but I want more.
```
{
	"compositeResponse": [{
		"body": {
			"id": "a0b2a000000n1OwAAI",
			"success": true,
			"errors": []
		},
		"httpHeaders": {
			"Location": "/services/data/v44.0/sobjects/Co_Travel__c/a0b2a000000n1OwAAI"
		},
		"httpStatusCode": 201,
		"referenceId": "local_14"
	}]
}
```

Thank you.

**Comment by wmathurin** [comment]
You could run a sync down to get the extra fields. You could use a [SFRefreshSyncDown](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SmartSync/SmartSync/Classes/Target/SFRefreshSyncDownTarget.h) which refreshes all the record in a given table (for whatever fields you specify).

**Comment by Yannmm** [comment]
> You could run a sync down to get the extra fields. You could use a [SFRefreshSyncDown](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SmartSync/SmartSync/Classes/Target/SFRefreshSyncDownTarget.h) which refreshes all the record in a given table (for whatever fields you specify).

Thanks for your rely. Just to confirm:  ie. after creating 10 records, I can refresh those 10 records with one SFRefreshSyncDown. Am I right?

**Comment by wmathurin** [comment]
Yes.

**Comment by Yannmm** [comment]
> Yes.

Thanks a lot.
