### ISSUE TITLE
Potential memory leak in SFNetwork

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#3077]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.3.0
2. Issue found in Native App or Hybrid App: Native (swift) App
3. OS Version: 13.1
4. Device: iPad
5. Steps to reproduce: Run some network requests through SDK
6. Actual behavior: SFNetwork retains NSURLSession and NSURLSession delegate retains SFNetwork
7. Expected Behavior: SFNetwork has a weak ivar to hold NSURLSession
8. Error Log:

Everything else that has leaked in the screenshot is leaking because _NSURLSessionLocal is not released:

![image](https://user-images.githubusercontent.com/47766072/68098462-f5ce2c00-ff10-11e9-9359-5e439f082738.png)

**Comment by az-oolloow** [comment]
According to this, the URL Session has a `strong` reference to the delegate:
https://stackoverflow.com/a/28186738/2057955

**Comment by bbirman** [comment]
Thanks for reporting, we’ll look into it

**Comment by iowlit** [comment]
The same. Btw, it is possible to avoid memory leak by setting your own SessionManager in SFNetwork and delegate your own URLSession instances. Create one long life ephemeral and background session for performance purposes. Current SDK implementation instantiates URLSession for each request but seems like forgets to free them.

**Comment by az-oolloow** [comment]
@bbirman Just a reminder that this is still an issue.

**Comment by bbirman** [comment]
Thanks @az-oolloow. In 7.3 we introduced a shared background and shared ephemeral instance of SFNetwork which were intended to replace making a new session for every request. Is that what you're seeing? Or are you seeing more than those two? We do have some areas that make additional instances but they should be removed when they're done.

**Comment by iowlit** [comment]
I found URLSession related memory leaks in 7.2. In 7.3 works good. Shared instances solved the problem. Thanks for your assistance.
