### ISSUE TITLE
Is there a specific way to pull image files?

### ISSUE THREAD

**Issue by rahimimn** [forcedotcom/SalesforceMobileSDK-iOS#3081]
1. Version of Mobile SDK Used: 7.1
2. Issue found in Native App or Hybrid App: iOS Native App (Swift)

Not entirely sure if this is where to post this, so please let me know if there is a better place.
I'm trying to find a simple way to pull an image file from Salesforce, and I'm not having too much luck. I've looked at the documentation, and can't find anything helpful, so if there is another form of documentation that could help, please reference it.

Thanks in advance!

**Comment by wmathurin** [comment]
Have you looked at: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/ios_rest_apis_SFRestAPI_Files.htm
