### ISSUE TITLE
Issues tabs are missing from the iOS/Android ServiceSDK repositories

### ISSUE THREAD

**Issue by chrisperkins** [forcedotcom/SalesforceMobileSDK-iOS#3082]
The Issues tabs have been removed/hidden from the Github ServiceSDK iOS/Android repositories and the docs still point to the missing Github issues pages for SDK support. What is the proper way to file issues for the ServiceSDKs?

Sorry to pollute this repo but I haven't been able to get a reply from the contributors.

**Comment by bhariharan** [comment]
You'll need to follow official channels by filing a support case with `Salesforce`.

**Comment by chrisperkins** [comment]
They did change the docs finally, here is the link for support requests:

Embedded Service for Mobile Apps (Formerly Snap-Ins) SDK Support <https://help.salesforce.com/articleView?id=000351538&type=1&mode=1>
