### ISSUE TITLE
motionEnded does not trigger after SDK integration

### ISSUE THREAD

**Issue by murilodag** [forcedotcom/SalesforceMobileSDK-iOS#3084]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.3.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 12.2
4. Device: iPhone X
5. Steps to reproduce: Shake app with "isDevSupportEnabled = false" does not trigger motionBegan events
6. Actual behavior: motionEnded events are suppressed and are not trigger after SDK is integrated
7. Expected Behavior: motionEnded events must not be suppressed based on dev support flag (enabled or not)
8. Error Log: App feature is broken, but there is no log message.

**Comment by trooper2013** [comment]
@murilodag Thanks for reporting. We will take a look.

**Comment by bbirman** [comment]
@murilodag Thanks again for reporting, the fix will be in 8.0
