### ISSUE TITLE
Error in Running build with Salesforce framework (222.0.3)

### ISSUE THREAD

**Issue by astha123455677** [forcedotcom/SalesforceMobileSDK-iOS#3092]
Please fill out the following details:

1. Version of Mobile SDK Used:
2. Issue found in Native App or Hybrid App: Native App
3. OS Version:  10.15.1 (mac OS catalina)
4. Device: 
5. Steps to reproduce: - Not able to build with the framework (222.0.3)
6. Actual behavior: - when we are running build with run script then it is showing error   (ServiceCore.Framework is damages and can't be opened)   ... xcode version 10.2
Check screenshot Attached - [2019-11-19 (1)](https://user-images.githubusercontent.com/35763571/69144082-818aaf80-0af0-11ea-9973-39b2eff83e30.png)
[2019-11-19](https://user-images.githubusercontent.com/35763571/69144083-82234600-0af0-11ea-9cd1-60a5bd77ed4a.png)
7. Expected Behavior: -  build should Run 
8. Error Log:

**Comment by bhariharan** [comment]
@astha123455677 This is not the right forum for bugs in `ServiceSDK`. `MobileSDK` is a different product altogether.

**Comment by astha123455677** [comment]
Can you please help me providing the right link where I can raise this ticket and get the solution for same .

**Comment by brandonpage** [comment]
@astha123455677 Unfortunately, the Service SDK team is no longer supporting issues through github so you will need to contact Salesforce Support through the standard channels that you would for any other product.

**Comment by AndyKD** [comment]
@brandonpage I am facing the same issue, could you please guide, what is the meaning of this "Salesforce Support through the standard channels " Mean I need to connect to my Sales force support team?

This is related to SDK, Is there any community where I an get help.

Any suggestions are highly appreciated!

**Comment by brandonpage** [comment]
@AndyKD Unfortunately I am not a member of the Service Cloud SDK team and thus I have no expertise to help with that product.  The issues here are for the product in this repo, the Salesforce Mobile SDK.  You can file a case with Salesforce Support by following the instructions here: https://help.salesforce.com/articleView?id=workcom_contact_support.htm&type=5
