### ISSUE TITLE
Crash while presenting login webview

### ISSUE THREAD

**Issue by narenuppala** [forcedotcom/SalesforceMobileSDK-iOS#3095]
Please fill out the following details:

1. Version of Mobile SDK Used:  7.3
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: iOS 13.2
4. Device: iPhone X
5. Steps to reproduce: When I try to launch login webview app crashes with error - 'No superview for oauth web view invoke [super viewDidLayoutSubviews] in the SFLoginViewController subclass'
6. Actual behavior:
7. Expected Behavior:
8. Error Log:
<img width="855" alt="Screenshot 2019-12-03 at 2 44 34 AM" src="https://user-images.githubusercontent.com/33321736/69995946-09ec6400-1577-11ea-98e9-d1c869c11718.png">

Please find the crash log in the screenshot attached

**Comment by wmathurin** [comment]
Did you generate your application with `forceios` ?

**Comment by narenuppala** [comment]
No. I have integrated SDK in the project created using XCode 11.2.1. I noticed this issue only when I create a project using XCode 11.x. 
I tried integrating the SDK 7.3 in the project which is created using Xcode 10.x and it works fine

**Comment by wmathurin** [comment]
We recommend using `forceios` because it will create the correct `AppDelegate` etc.
When you generate a project using XCode 11.x, it's probably using SceneDelegate which is not supported by Mobile SDK 7.3 but will be supported by our next release (Mobile SDK 8.0, scheduled for later this month).
