### ISSUE TITLE
Hybrid IOS App login (remember me check not working)

### ISSUE THREAD

**Issue by Roamaon** [forcedotcom/SalesforceMobileSDK-iOS#3100]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.3.0
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: 13
4. Device: Simulator
5. Steps to reproduce: on login screen check [remember me], enter credentials, do login, do logout
6. Actual behavior: empty login field, no checkmark at [remember me]
7. Expected Behavior: pre-filled login field, checked [remember me]
8. Error Log: n/a

For Android all is okay. Looks like its WkWebView issue, on previous UIWebView it worked like a charm. Anyway need a solution from salesforce.com team.

**Comment by mattlacey** [comment]
@Roamaon how come you closed this? Did you find a way to make it work? Trying to solve the same problem and my searches haven't turned up much yet!

**Comment by Roamaon** [comment]
@mattlacey I just comment in
platforms/ios/Pods/SalesforceSDKCore/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Common/SFSDKWebViewStateManager.m

```
    //reset UIWebView related state if any
    [self removeUIWebViewCookies:@[SID_COOKIE] fromDomains:self.domains];
    [self removeWKWebViewCookies:self.domains withCompletion:NULL];

```
