### ISSUE TITLE
To be able to delete multiple records from an object

### ISSUE THREAD

**Issue by utejaswi** [forcedotcom/SalesforceMobileSDK-iOS#3104]
Please fill out the following details:

1. Version of Mobile SDK Used:  SDK 7.3
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 13
4. Device: Iphone 11
5. Steps to reproduce: N/A
6. Actual behavior: Unable to delete multiple records
7. Expected Behavior: To be able to delete multiple records from an object
8. Error Log:  Unable to delete multiple records

I have a list of ids of records to delete from an object. I see that RestClient provides an option to delete one record. Is there a way to delete multiple records at once?

**Comment by wmathurin** [comment]
There is no Rest API in the server to delete multiple records at once. However you could achieve the same result by creating a batch request made of the individual delete requests.
