### ISSUE TITLE
Attachments UI

### ISSUE THREAD

**Issue by geekandt** [forcedotcom/SalesforceMobileSDK-iOS#3105]
Please fill out the following details:

Version of Mobile SDK Used: MobileSDK 6.2.0
Issue found in Native App or Hybrid App:
Hybrid App -LinktgoApp
OS Version:
iOS 10 and above
Device: All devices
Hi Team,
Our devs need to know:

if there is an easier way to achieve the same "attachments" functionality without having to fully build the SF UI from scratch. And leverage our existing use of the Snap in SDK.

This would mean less development time to achieve the same result.

Our app developers would like to know if you could provide us with a working demo project (instead of links to documentation) that can be studied and analysed that will help expedite development?
Does SF have plans to include attachments to Case Management SDKs (Android and iOS)? And when if yes?
Is there a way to inherit from CaseUI classes to include this functionality?
Hope you can help.
As we asked in the Salesforce StackExchange and there is no answer.

**Comment by brandonpage** [comment]
This repository is for the Salesforce Mobile SDK, not the Service Cloud Snap-In's SDK.  Please contact support through the standard channels.
