### ISSUE TITLE
navigator.smartstore methods is not working on iOS 13

### ISSUE THREAD

**Issue by sarathi0333** [forcedotcom/SalesforceMobileSDK-iOS#3116]
Please fill out the following details:

1. Version of Mobile SDK Used: 4.0.0
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: iOS 13
4. Device: iPad Air 2
5. Steps to reproduce: navigator.smartstore.soupExists(soupName, successCB, FailureCB)
6. Actual behavior: The method is not getting executed the app freezes at this method
7. Expected Behavior: expected the method to invoke success callback or failure callback
8. Error Log: No error logs

Also raised the same issue on https://stackoverflow.com/q/59621447/5378357

**Comment by brandonpage** [comment]
Hi @sarathi0333, if you are in fact using Mobile SDK 4.0.0 released in 2015 you should upgrade to something more modern.  There is no way we would be able to to go back and debug or fix and issue from 4+ years ago.  Given you are running on iOS 13 did you perhaps mean 7.0.0?

**Comment by sarathi0333** [comment]
Hi @brandonpage , Thanks for the reply. I actually mean 4.0.0 only. If we want to update to the latest SDK do we require code change or it will be enough if we follow these guidelines below? https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/general_update_app.htm

**Comment by bhariharan** [comment]
@sarathi0333 `iOS 13` is fully supported in `Mobile SDK 8.0.0`. Please upgrade to the latest version of Mobile SDK and reopen this issue if it still exists in `Mobile SDK 8.0.0`. `4.0.0` is at least 4 years old and does not support `iOS 13`.

**Comment by sarathi0333** [comment]
Hi @bhariharan I tried the same with latest Mobile SDK 8.0.0. The issue remains the same. Also i am getting an error "undefined is not an object (evaluating 'navigator.smartstore.registerSoup')" on executing 
`navigator.smartstore.registerSoup({storeName: "Store1", isGlobalStore:false}, soupName ,indexSpecs, successCallback, errorCallback)`

replacing corresponding values for the argument.

Do i need to add any permissions to make it work in iOS 13.
