### ISSUE TITLE
 Error: Invalid `SalesforceSDKCore.podspec`

### ISSUE THREAD

**Issue by saranyaj86** [forcedotcom/SalesforceMobileSDK-iOS#3117]
Please fill out the following details:

1. Version of Mobile SDK Used: 'SalesforceSDKCore', '5.0.1'
2. Issue found in Native App or Hybrid App: Natve App
3. OS Version: 12.0
4. Device: ipad and iPhone
5. Ruby Version: 2.4.0
6. Cocopods version: 1.5.3
7. Steps to reproduce:
 Trying to pod install for pod 'SalesforceSDKCore', '5.0.1' and My swift version is 3.0. Got the below error

8. Error Log:
[!] Invalid `SalesforceSDKCore.podspec` file: undefined method `swift_versions=' for #<Pod::Specification name="SalesforceSDKCore">.

 #  from /Users/**/.cocoapods/repos/forcedotcom/SalesforceSDKCore/8.0.0/SalesforceSDKCore.podspec:12
 #  -------------------------------------------
 #    s.platform     = :ios, "12.2"
 >    s.swift_versions = ['5.0']
 #  
 #  -------------------------------------------

**Comment by brandonpage** [comment]
While I recommend you upgrade to the latest version of the SDK (v5 is  3 years old now), I believe your command is wrong.  Try ```pod 'SalesforceSDKCore', '~> 5.0.1'```

**Comment by brandonpage** [comment]
Somehow you are pulling the podspec for the latest (8.0.0) instead of 5.0.1, which requires iOS 12.2/Swift 5.
