### ISSUE TITLE
Ambiguous reference to member 'publisher(for:)'

### ISSUE THREAD

**Issue by jeremym148** [forcedotcom/SalesforceMobileSDK-iOS#3118]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.0
2. Issue found in Native App or Hybrid App: IOS Native
3. OS Version:13
4. Device: Simulator
5. Steps to reproduce:
let request: RestRequest = RestClient.shared.request(forQuery: "SELECT id, name FROM Account", apiVersion: nil)
       
       _ = RestClient.shared.publisher(for: request)

6. Actual behavior: Can't compile : error Ambiguous reference to member 'publisher(for:)'
7. Expected Behavior:
8. Error Log: Ambiguous reference to member 'publisher(for:)'

**Comment by wmathurin** [comment]
Are you using our iOS13NativeSwiftTemplate?
We are not seeing the issue (https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/master/iOS13NativeSwiftTemplate/iOS13NativeSwiftTemplate/ContactsForAccountModel.swift).

**Comment by wmathurin** [comment]
Closing since we can't repro the issue.
Also we just released 8.1, you should give it a try.
