### ISSUE TITLE
Hi @bhariharan I tried the same with latest Mobile SDK 8.0.0. The issue remains the same. Also i am getting an error "undefined is not an object (evaluating 'navigator.smartstore.registerSoup')" on executing

### ISSUE THREAD

**Issue by sarathi0333** [forcedotcom/SalesforceMobileSDK-iOS#3119]
Hi @bhariharan I tried the same with latest Mobile SDK 8.0.0. The issue remains the same. Also i am getting an error "undefined is not an object (evaluating 'navigator.smartstore.registerSoup')" on executing 
`navigator.smartstore.registerSoup({storeName: "Store1", isGlobalStore:false}, soupName ,indexSpecs, successCallback, errorCallback)`

replacing corresponding values for the argument.

Do i need to add any permissions to make it work in iOS 13.

_Originally posted by @sarathi0333 in https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3116#issuecomment-572464832_

**Comment by wmathurin** [comment]
What kind of hybrid application are you using (local or remote)? Is it a Visual Force page or are you using Lightning?

**Comment by wmathurin** [comment]
Make sure you don't try accessing smartstore until you get the deviceready event from cordova (see https://cordova.apache.org/docs/en/5.1.1/cordova/events/events.deviceready.html). 
We have numerous hybrid applications using SmartStore so we don't believe there is an issue with the SDK.
