### ISSUE TITLE
forceios failed on SmartStore podspec install submodule problem

### ISSUE THREAD

**Issue by iandrosov** [forcedotcom/SalesforceMobileSDK-iOS#3122]
I see this error for couple of days now that prevents generating a new iOS swift app. It seems some issues during the submodule installation of SmartStore module. This issue will also exist for Trailhead modules: https://trailhead.salesforce.com/content/learn/modules/mobile_sdk_native_ios/mobilesdk_ios_getting_started

Please fill out the following details:

1. Version of Mobile SDK Used: 8.0
node version: v10.16.0
npm: 6.13.6
XCode 11
2. Issue found in Native App or Hybrid App: Native Swift
3. OS Version: MacOS 10.14.6
4. Device: iPhone
5. Steps to reproduce: Run one of these commands:
forceios create
or
forceios createwithtemplate 
using iOS13NativeSwiftTemplate or default template all fail with same error on SmartStore install

6. Actual behavior:
I get this error:

Fetching podspec for `SmartStore` from `mobile_sdk/SalesforceMobileSDK-iOS`
[!] CDN: cocoapods- Relative path couldn't be downloaded: Specs/f/4/e/FMDB/index.txt Response: 301
/Users/iandrosov/code/ios/MyAPPS/toku/sdk80
forceios failed

Command failed: pod update

7. Expected Behavior: completed install od Mobile SDK dependencies from defined pod specs and generate new applications from iOS native swift template.

8. Error Log: when I try to run directly in my project ./install.js  attempt to reinstall SDK I get this error:

Installing sdk dependencies
mobile_sdk/SalesforceMobileSDK-iOS already exists - if you want to refresh it, please remove it and re-run install.js
Installing pod dependencies
Update all pods
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `MobileSync` from `mobile_sdk/SalesforceMobileSDK-iOS`
Fetching podspec for `SalesforceAnalytics` from `mobile_sdk/SalesforceMobileSDK-iOS`
Fetching podspec for `SalesforceSDKCommon` from `mobile_sdk/SalesforceMobileSDK-iOS`
Fetching podspec for `SalesforceSDKCore` from `mobile_sdk/SalesforceMobileSDK-iOS`
Fetching podspec for `SmartStore` from `mobile_sdk/SalesforceMobileSDK-iOS`
[!] CDN: cocoapods- Relative path couldn't be downloaded: Specs/f/4/e/FMDB/index.txt Response: 301
child_process.js:669
    throw err;
    ^

Error: Command failed: pod update
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at Object.<anonymous> (/Users/iandrosov/code/ios/MyAPPS/toku/sdk80/TokuApp/install.js:20:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19

**Comment by brandonpage** [comment]
What version of CocoaPods are you using?  Since you are seeing a CDN issue I would guess the version is too old.  We support 1.7 and 1.8.

**Comment by iandrosov** [comment]
pod --version
1.7.0

I did update cocoapods last week to this specific version. but I did not try 1.8.0

**Comment by wmathurin** [comment]
Actually cdn support came in version 1.7.2 (see https://blog.cocoapods.org/CocoaPods-1.7.2/). Try upgrading cocoapod and the problems should go away.

**Comment by iandrosov** [comment]
I updated to 1.8.0 and that gone even much worse errors on Ruby and gems
with pods 1.8 forceios cannot even create anything fails with the huge error log

source 'https://cdn.cocoapods.org/'

use_frameworks!

pod 'SalesforceSDKCommon', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SalesforceAnalytics', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SalesforceSDKCore', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SmartStore', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'
pod 'MobileSync', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'

end

# Comment the following if you do not want the SDK to emit signpost events for instrumentation. Signposts are  enabled for non release version of the app.
 post_install do |installer_representation|
       installer_representation.pods_project.targets.each do |target|
           target.build_configurations.each do |config|
               if config.name == 'Debug'
                   config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'DEBUG=1','SIGNPOST_ENABLED=1']
                   config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-DDEBUG','-DSIGNPOST_ENABLED']
               end
           end
       end
  end
```

### Error

```
NameError - uninitialized constant Concurrent::Promises
Did you mean?  Concurrent::Promise
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.0/lib/cocoapods-core/cdn_source.rb:62:in `block in preheat_existing_files'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.0/lib/cocoapods-core/cdn_source.rb:61:in `map'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.0/lib/cocoapods-core/cdn_source.rb:61:in `preheat_existing_files'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.0/lib/cocoapods-core/cdn_source.rb:253:in `update'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/sources_manager.rb:122:in `block (3 levels) in update'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/sources_manager.rb:121:in `block (2 levels) in update'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/sources_manager.rb:120:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/sources_manager.rb:120:in `block in update'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/sources_manager.rb:118:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/sources_manager.rb:118:in `update'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/installer/analyzer.rb:145:in `block in update_repositories'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/installer/analyzer.rb:143:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/installer/analyzer.rb:143:in `update_repositories'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/installer.rb:230:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/installer.rb:229:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/command/update.rb:63:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.


Command failed: pod update

**Comment by wmathurin** [comment]
The same issue is reported on the cocoapod  repo, with the solution. Please see https://github.com/CocoaPods/CocoaPods/issues/8948

**Comment by iandrosov** [comment]
It is fixed now, here are my steps:
Initially I attempted to fix ruby as noted here: https://github.com/rbenv/rbenv/issues/1145
but this did not work.
1. Update pod to 1.8.0 and then I try 
2. sudo gem update concurrent-ruby 
needed sudo since some of system directory access was not set
3. My ruby -v  ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18] seem bit old but still worked with SDK
SOLVED!
