### ISSUE TITLE
Login page not respecting device orientation

### ISSUE THREAD

**Issue by abdulucf** [forcedotcom/SalesforceMobileSDK-iOS#3125]
Please fill out the following details:

1. Version of Mobile SDK Used:  8.0.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 13.1
4. Device: iPad Pro 9.7 Inch
5. Steps to reproduce: 
**In Landscape mode**
- Tap on Gear Icon on login page
- Tap on Cancel Button 

6. Actual behavior:

Salesforce Login page turns portrait causing layout issues
7. Expected Behavior:
Login page should be in orientation of device.
![image-20200115-225151](https://user-images.githubusercontent.com/54814345/72533741-786f5200-3897-11ea-86ef-ed7abc288a27.png)
8. Error Log:

**Comment by Manish-Kr09** [comment]
Change orientation handling in **SFSDKAppLockViewController**,  **SFSDKAppLockViewController** and **SFSDKRootController** using the below code

> `- (BOOL)extended_shouldAutorotate{
    return YES;
}`

> `- (UIInterfaceOrientationMask)extended_supportedInterfaceOrientations {
        return UIInterfaceOrientationMaskAll;
}`

@bhariharan Is there any other way to do this without modifying the SDK classes?  I know we can extend SFSDKAppLockViewController and SFSDKAppLockViewController but SFSDKRootController is not accessible outside SalesforceSDK

Regards,
Manish Kumar

**Comment by abdulucf** [comment]
@Manish-Kr09  it isn't working. Kindly Uncheck the portrait orientations from Project's Info page. Only enable Landscape mode and try again.
Present Login screen, tap on gear icon, then tap back arrow

**Comment by Manish-Kr09** [comment]
You mean this, check the screenshot
<img width="1031" alt="Screenshot 2020-01-17 at 5 17 23 PM" src="https://user-images.githubusercontent.com/2398709/72610510-94352f80-394d-11ea-8bc9-6ee1602e2b12.png">

**Comment by abdulucf** [comment]
@Manish-Kr09 Yes. On login page tap gear icon and then tap back arrow while on landscape orientation

**Comment by Manish-Kr09** [comment]
@abdulucf  Here is how it behaves. 

![Screen-Recording-2020-01-17](https://user-images.githubusercontent.com/2398709/72616053-14629180-395c-11ea-822b-f7bcba424631.gif)

**Comment by brandonpage** [comment]
Due to some decisions made long ago around windowing we only support portrait orientation today.  We have discussed making this enhancement but it depends on the outcome of some other spike work.  That work will not be in the next release, but may come later this year.

**Comment by abdulucf** [comment]
OK  @brandonpage. Acknowledged

**Comment by jegauten** [comment]
Hi @brandonpage just to clarify the orientation support you are mentioning is regarding to the login page only right? thanks

**Comment by abdulucf** [comment]
@jegauten  The problem is when user taps on setting icon from login page

**Comment by jegauten** [comment]
@abdulucf i see, our issue is related, though it is just locked in portrait outright

**Comment by brandonpage** [comment]
@jegauten Ideally it would apply to all SDK controlled windows, but I can't promise that yet as the spike work has not been done.

**Comment by wmathurin** [comment]
The problem has been addressed (see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3319) and will be in our next release (Mobile SDK 9.0).
