### ISSUE TITLE
Is need additional field on SFSDKAppLockViewConfig

### ISSUE THREAD

**Issue by denysvarchenko** [forcedotcom/SalesforceMobileSDK-iOS#3132]
Hello,
Currently, I can set self.viewConfig.primaryColor and it will be used to fill the color of the passcode circle and for logout button.
The problem is that our navigation bar and primary color are violet, so the logout button become almost invisible. 

The best solution will be to add one more property to SFSDKAppLockViewConfig to setup logout button color.

What have be done:
1. I tried to subclass SFSDKPasscodeVerifyController and SFSDKAppLockViewController, and provide SFSDKAppLockViewController subclass in SFSecurityLockout. But these controllers are not public. I don't won't to copy your podspec and modify it a bit for this case. And it won't be safe to update umbrella and file visibility on post_install step in pod file.
Moreover, I believe these overrides may cause even more issues
2. It is possible also to use Runtime to override the implementation, but I want to avoid this.
3. UINavigationBar.appearance() also doesn't work because you are setting `[self.navigationItem.leftBarButtonItem setTintColor:self.viewConfig.primaryColor];` instead of `[self.logoutButton setTintColor:self.viewConfig.primaryColor];` (this fix also will help us).

Please check the screenshot to underhand what UI issue occurs
<img width="383" alt="image" src="https://user-images.githubusercontent.com/36194672/73264652-ed1d8700-41db-11ea-8a66-855dfac1b146.png">

Looking forward to hearing from you
Please fill out the following details:

1. Version of Mobile SDK Used:  7.3.0
2. Issue found in Native App or Hybrid App: iOS Native
3. OS Version: Any
4. Device: Any
5. Steps to reproduce: Trying to specify color for the Log Out button on the SFSDKPasscodeVerifyController
6. Actual behavior: The color is set to self.viewConfig.primaryColor
7. Expected Behavior: The color is set to the color different from self.viewConfig.primaryColor

**Comment by brandonpage** [comment]
I have submitted a PR for this issue: #3136

**Comment by bhariharan** [comment]
This will be a part of our next release, i.e. `Mobile SDK 8.1.0`.

**Comment by denysvarchenko** [comment]
Hello @bhariharan,
Thank you for a quick fix. 

Is it possible to push this fix to 7.3.0 version?
Currently, we agreed with a client to use iOS 11.0 as minimum iOS version and we will not be able to migrate to 8.1 in a nearest time

**Comment by bhariharan** [comment]
I'm afraid not. We don't patch older versions of Mobile SDK. However, you're welcome to cherry pick the fix on your fork of Mobile SDK if you need it sooner.
