### ISSUE TITLE
Back Button unable to hide due to readonly property

### ISSUE THREAD

**Issue by jimmythigpen** [forcedotcom/SalesforceMobileSDK-iOS#3133]
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/36d6f26886dc08289224cae30c26b04caef45c93/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Login/SFSDKLoginViewControllerConfig.h#L51

**Comment by wmathurin** [comment]
The best approach might be to create your own LoginViewController and override the shouldShowBackButton method.

For more details on how to do that please see: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2477#issuecomment-377044489
