### ISSUE TITLE
How to use ParentChildrenSyncUpTarget to create both a parent and its children?

### ISSUE THREAD

**Issue by Yannmm** [forcedotcom/SalesforceMobileSDK-iOS#3138]
Please fill out the following details:

1. Version of Mobile SDK Used:  7.3.0
2. Issue found in Native App or Hybrid App: Native swift
3. OS Version: 10.15.3
4. Device: iPad
5. Steps to reproduce:
Assume I create a parent record (P) and its child record (C), can I just upsert them into separate local soups and use ParentChildrenSyncUpTarget to sync them up in one call? If yes, how to connect those two records? Here is one solution I tried but does not work:
```
let p = P()
p.id = UUID()

let c = C()
c.id = UUID()
c.parent_id = p.id

store.upsert(p, "p_soup")
store.upsert(c, "c_soup")

// finally sync up with ParentChildrenSyncUpTarget
```

And here is the response I got: Parent is created successfully, but child does not.
```
{
	"compositeResponse": [{
		"body": {
			"id": "a0be0000009ZY4xAAG",
			"success": true,
			"errors": []
		},
		"httpHeaders": {
			"Location": "/services/data/v46.0/sobjects/Co_Travel__c/a0be0000009ZY4xAAG"
		},
		"httpStatusCode": 201,
		"referenceId": "a0be0000009ZY4sAAG"
	}, {
		"body": [{
			"errorCode": "NOT_FOUND",
			"message": "The requested resource does not exist"
		}],
		"httpHeaders": {},
		"httpStatusCode": 404,
		"referenceId": "2020130"
	}]
}
```

**Comment by wmathurin** [comment]
That's the idea.
Make sure your sync is configured properly.
Look at our test code for an example: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/MobileSync/MobileSyncTests/ParentChildrenSyncTests.m#L1306

**Comment by Yannmm** [comment]
Thanks @wmathurin. I finally solved it:
1. I misspell the name of child object type, that's where "The requested resource does not exist" comes from.
2. UUID is not good to be id, response will be like this:
```
			"message": "P: id value of incorrect type: @{09DF5203-0122-49BA-82D9-6CD256D6BDD3.id}",
			"errorCode": "MALFORMED_ID",
			"fields": ["parent_id"]
```
So I adopt the same way as in test code: local_randomNumber.
