### ISSUE TITLE
Push notifications can not be initialized from JS

### ISSUE THREAD

**Issue by yvbeek** [forcedotcom/SalesforceMobileSDK-iOS#3141]
**1. Version of React-Native SFMC SDK used:**
6.4.0

The React-Native SFMC library contains a few useful functions, but unfortunately it doesn't contain one to ask the user if they want to enable push notifications. That part has to be done from native code with:

```objective-c
[UNUserNotificationCenter.currentNotificationCenter
 requestAuthorizationWithOptions: options
 completionHandler:^(BOOL granted, NSError *error) {}
];
```

It would be great if this call (and the Android counterpart) could be wrapped by a function in `MCReactModule`. That way we can move the initialization over to the JS code and have more control over when to ask the user for permission to enable push notifications.

**Comment by brandonpage** [comment]
Hi @yvbeek. This repo is for the Salesforce Mobile SDK, not the Marketing Cloud Push SDK. Please use Stack Exchange for support for that product.
