### ISSUE TITLE
Creating many transparent windows (UIWindow) that float above our app for many different purposes

### ISSUE THREAD

**Issue by geekandt** [forcedotcom/SalesforceMobileSDK-iOS#3147]
Please fill out the following details:

1. Version of Mobile SDK Used: MobileSDK 6.2.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: iOS 13
4. Device: iPhone X
5. Steps to reproduce: 

We are in the process of implementing a third-party payment SDK in our iOS app, and we have encountered strange bugs and unexpected behaviour coming specifically from the SalesForce SDK, even when the SF SDK is not being invoked directly by our app.

Basically, the SalesForce Mobile SDK is creating many transparent windows (UIWindow) that float above our app for many different purposes. These windows have interfered with our app screens and stopped the app from working properly.

We would like to request that the SalesForce Mobile SDK pass the responsibility of displaying messages and errors with those windows to our app, so our app can display them in the best manner and we can optimise our own app's customer experience.

Thank you, and please let us know if this is achievable on your future roadmap.

**Comment by bhariharan** [comment]
@geekandt Have you tried our latest release, i.e. `Mobile SDK 8.0.0`. A bunch of window fixes and support for `iOS 13` have gone into this release. Please let us know and reopen this issue if you are still seeing issues with `8.0.0`.
