### ISSUE TITLE
App freeze at method [SalesforceSDKManager sdkPasteboard]

### ISSUE THREAD

**Issue by coulCod** [forcedotcom/SalesforceMobileSDK-iOS#3148]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.0.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 13.3
4. Device: simulator iPad Pro (12.9-inch) (3rd generation) (13.3)
5. Steps to reproduce:
 - Launch application
 - Tap on any UISearchBar
6. Actual behavior: Application freeze at SalesforceSDKManager line 205
7. Expected Behavior: ability to type text to search bar input
8. Error Log:  XPC connection interrupted

I can't reproduce this bug every time. Sometimes clear build folder helped for me. It’s not obvious to me that your library will do anything when I focus on the UISearchBar at all.

**Comment by wmathurin** [comment]
An XPC connection is interrupted when the remote process terminates.  This can happen for abnormal reasons (for example, the remote process crashing) and for normal reasons (the system terminating the remote process to recover memory).
The crash is either an iOS bug or from misusing UISearchBar.
Please research Apple forums for relevant help.

**Comment by coulCod** [comment]
This problem appears when I launch the application through the simulator. I use xcode 11. 
It really is not related to SFSDK. Thanks you.
