### ISSUE TITLE
SFLoginViewController UI is not proper for iOS 13

### ISSUE THREAD

**Issue by AbhishekChourasia16690** [forcedotcom/SalesforceMobileSDK-iOS#3149]
Hello Team,

Kindly find attached screenshot for error on iPAD Air 3rd Generation simulator and below are details.

1. Version of Mobile SDK Used: 6.2.0

2. Issue found in Native App or Hybrid App: Native iOS App

3. OS Version: iOS 13 & Mac OS 10.14.6

4. Device: Simulator

5. Steps to reproduce:
Run the app and first screen is the SFLoginViewController whose orientation is not correct.

6. Actual behavior:
Login screen orientation is not correct. Refer screenshot for more info.

7. Expected behavior: The orientation should not change in any case when the app is launched or if the environment is changed.

Waiting for your reply.

![iPad_Air_3rd_Generation_Error_1](https://user-images.githubusercontent.com/22599405/74820584-4e8ecc80-5328-11ea-9322-cc7b94a829a2.png)
![iPad_Air_3rd_Generation_Error_2](https://user-images.githubusercontent.com/22599405/74820586-50589000-5328-11ea-9952-add122d5174b.png)

Thanks & Regards,
Abhishek.

**Comment by wmathurin** [comment]
You are using a version of Mobile SDK that was released in 2018, more than a year before iOS 13 came out.

Please upgrade to the most recent version of Mobile SDK and the issue should be resolved.

**Comment by AbhishekChourasia16690** [comment]
Hello @wmathurin.

Can you tell me what version I need to add in podifile.

pod 'SalesforceSDKCore', '~> x.x'


Thanks & Regards,
Abhishek

**Comment by wmathurin** [comment]
You can find that information in the pod spec: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/SalesforceSDKCore.podspec#L4

It's 8.1.0.
