### ISSUE TITLE
Latest Pod version number 

### ISSUE THREAD

**Issue by AbhishekChourasia16690** [forcedotcom/SalesforceMobileSDK-iOS#3151]
Hello Team,

I need to know the latest pod version number for Mobile iOS SDK.

Thanks,
Abhishek.

**Comment by wmathurin** [comment]
You can find that information in the pod spec: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/SalesforceSDKCore.podspec#L4

It's 8.1.0.
