### ISSUE TITLE
Unable to update pod version

### ISSUE THREAD

**Issue by AbhishekChourasia16690** [forcedotcom/SalesforceMobileSDK-iOS#3152]
Hello Team,
When I entire below pod versions in my podfile.

pod 'SalesforceSDKCore', '~> 8.1.0'
pod 'SalesforceSDKCore', '~> 8.1.0'

I get the following error:
[!] CocoaPods could not find compatible versions for pod "SalesforceSDKCore":
  In Podfile:
    SalesforceSDKCore (~> 8.1.0)
Specs satisfying the `SalesforceSDKCore (~> 8.1.0)` dependency were found, but they required a higher minimum deployment target.

Please could you help me with the issue.

Thanks and Regards,
Abhishek.

**Comment by brandonpage** [comment]
Seems pretty straight forward: `required a higher minimum deployment target`.

What is your deployment target?  It needs to be >= iOS 12.2.

**Comment by AbhishekChourasia16690** [comment]
Hello @brandonpage,

I have set the deployment target to iOS 13 still I get below error:

!] CocoaPods could not find compatible versions for pod "SalesforceSDKCore":
  In Podfile:
    SalesforceSDKCore (~> 8.1.0)

Specs satisfying the `SalesforceSDKCore (~> 8.1.0)` dependency were found, but they required a higher minimum deployment target.

Kindly find attached for details.


Thanks,
Abhishek
![Screenshot 2020-02-24 at 2 41 19 PM](https://user-images.githubusercontent.com/22599405/75139890-d2bfc600-5713-11ea-9fac-9391c21c7b4c.png)

**Comment by wmathurin** [comment]
Could you check your podfile?
Make sure the first line looks lilke:
```
platform :ios, '12.2'
```
If you are targeting 13.0, you might be better off re-running forceios and regenerating your application from the new iOS 13 template by doing
```
forceios createwithtemplate --templaterepouri=iOS13NativeSwiftTemplate
```
There are changes in the app delegate (and there is a scene delegate also) - changing your pod file won't get you all the changes you need.

**Comment by AbhishekChourasia16690** [comment]
Hello @wmathurin,

I updated as per you mentioned above.

But when I run the app, I get the error mentioned in the screenshot.


Thanks,
Abhishek.
![Screenshot 2020-02-25 at 2 08 12 PM](https://user-images.githubusercontent.com/22599405/75229998-07e21c00-57d9-11ea-90b3-898a62fa875c.png)

**Comment by wmathurin** [comment]
Did you update the podfile or did you return forceios?

**Comment by AbhishekChourasia16690** [comment]
I just updated the podfile and deployment target in build settings.

This is how my podfile looks like now

# Uncomment this line to define a global platform for your project
# Uncomment this line if you're using Swift
use_frameworks!
inhibit_all_warnings!

target 'AppName' do
    platform :ios, '12.2'
    source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git' # needs to be first
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'SplunkMint'
    pod 'FMDB', :git => 'https://github.com/forcedotcom/fmdb', :branch => '2.7.2_xcode9'
    pod 'SalesforceSDKCore' , '~> 8.1.0'
    pod 'CocoaLumberjack'
end

**Comment by wmathurin** [comment]
Please run forceios like I recommended before and copy your app code into the generated app.
You will get the correct podfile and the correct AppDelegate files etc.
