### ISSUE TITLE
Issue In Uploading Build On Testflight

### ISSUE THREAD

**Issue by astha123455677** [forcedotcom/SalesforceMobileSDK-iOS#3153]
Please fill out the following details:
 **SDK version used - 222.0.3 (October 2019 Patch Release 2)**
1. Version of Mobile SDK Used: 12.4
2. Issue found in Native App or Hybrid App: Native App
3. OS Version:
4. Device:
5. Steps to reproduce: when User tries to Upload Build on testFlight, then it shows an error that **ServiceCore.framework is damaged**. Not able to Upload the Build on Test Flight. 
**This issue is coming in one Specific OS that is  - MacOS Catalina**
6. Actual behavior:
7. Expected Behavior: - Build should get Archived and upload in test Flight 
8. Error Log: Please check Screenshot Attached . 
<img width="991" alt="Screen Shot 2020-02-21 at 5 29 01 PM" src="https://user-images.githubusercontent.com/35763571/75032935-bd5a5a00-54cf-11ea-9fb9-0b9abedb4092.png">

**Comment by astha123455677** [comment]
Please provide help on this . We are not able to upload build on testflight with macboook version Mac OS Catalina .

**Comment by brandonpage** [comment]
This repo is for the Salesforce Mobile SDK.  Your issue is with a different product - the Service Cloud SDK, a.k.a Snap-Ins.  Please contact Salesforce Support through whatever means your company typically does.
