### ISSUE TITLE
Unable to build code with new version of SDK

### ISSUE THREAD

**Issue by AbhishekChourasia16690** [forcedotcom/SalesforceMobileSDK-iOS#3156]
Hello All,

I recently updated the Salesforce SDK as there was orientation issues in the app at login page for iOS 13. I updated to the latest version of SDK which is 8.1.0. Pod installed correctly but unable to build code.Kindly find attached for the same.

![Screenshot 2020-02-27 at 12 52 01 PM](https://user-images.githubusercontent.com/22599405/75421329-01ca7780-5960-11ea-9f31-e00eeb8dbae9.png)

I also used forceios to update the SDK properly using the command

forceios createwithtemplate --templaterepouri=iOS13NativeSwiftTemplate

And when asks me package name I'm unable to write as package name is not available for iOS. Could someone help me with how to find package name for forceios.

Thanks and Regards,
Abhishek.

**Comment by AbhishekChourasia16690** [comment]
![Screenshot 2020-02-27 at 12 52 01 PM](https://user-images.githubusercontent.com/22599405/75421784-0c394100-5961-11ea-9433-744c1b447ec5.png)

**Comment by wmathurin** [comment]
What do you mean package name is not available for iOS?
It's basically your bundle identifier (minus the app name).
![Screenshot 2020-02-27 11 03 40](https://user-images.githubusercontent.com/1012459/75477231-d68c5c00-5950-11ea-8a1b-69b255264b3b.png)
