### ISSUE TITLE
Using SFLayoutSyncManager to sync layouts

### ISSUE THREAD

**Issue by jpmonette** [forcedotcom/SalesforceMobileSDK-iOS#3157]
Please fill out the following details:

1. Version of Mobile SDK Used: `8.1.0`
2. Issue found in Native App or Hybrid App: Native
3. OS Version: `10.15.2`
4. Device: `iPad Pro 13.3.1`
5. Steps to reproduce:
This only seems to return the Master layout - you cannot select a specific layout or all layouts for sync:

```objective-c
// Getting Layouts for Account SObject
SFLayoutSyncManager *layoutSyncManager = [SFLayoutSyncManager sharedInstance];
[layoutSyncManager fetchLayoutForObject:kAccount layoutType:nil mode:SFSDKFetchModeServerFirst completionBlock:^(NSString *objectType, SFLayout *layout) {}];
```
6. Actual behavior:
Returns only `Account-(null)`
7. Expected Behavior:
Allow to pick a specific layout, or sync all layouts for object.
8. Error Log:
No error

**Comment by bhariharan** [comment]
@jpmonette 

The `layoutType` parameter can be used to supply the layout type that you want to use. The supported types are `Compact` and `Full`. More info on the API used to fetch layout is [here](https://developer.salesforce.com/docs/atlas.en-us.uiapi.meta/uiapi/ui_api_resources_record_layout.htm).

It looks like you've passed in `nil` for `layoutType` in your query above.

**Comment by jpmonette** [comment]
@bhariharan 

Hmmm I believe I read somewhere in the documentation that setting`nil` for `layoutType` would get `full` by default. So what does `nil` get if it is not all `Full`?

Also, I may have 10 different Full Page Layouts on my `Account` SObject. How can I query one? Or all? Or the one for a specific RecordType?

**Comment by bhariharan** [comment]
Yes - nil should populate Full by default. Let me check the code. And yes, it gives to the Full layout associated with that record type.

**Comment by jpmonette** [comment]
@bhariharan 

But which record type? This function has no parameter to set the record type 🤔- only the SObject, LayoutType and Mode.

**Comment by bhariharan** [comment]
Hmm, could you give me an example of the distinction? For sobject "Account", what are the different record types?

**Comment by jpmonette** [comment]
@bhariharan 
Well, a Salesforce Object like `Account` can have various Record Types to which we can assign different Page Layouts. For example, you could have an Employee RecordType on the Account Object, with a Page Layout assigned that is different from the Customer RecordType.

The endpoint to get the page layouts is this one:
`/vXX.X/sobjects/Object/describe/namedLayouts/layoutName`
`/services/data/v46.0/sobjects/Account/describe/layouts/0123z000000kxRl`
(https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_sobject_named_layouts.htm)

I feel this would be the most common need in terms of querying Page Layouts, no? This would allow to grab more than 1 per Salesforce Object, and get the one assigned to a RecordType.

**Comment by bhariharan** [comment]
That makes sense. Thanks @jpmonette! Let me take a look at tweaking the API to support that. I think the challenge is the API endpoint being used for this. `/describe/layouts` would probably solve your problem, but we're using the newer `uiapi` endpoint.

**Comment by jpmonette** [comment]
@bhariharan 
I just had a second look at the `/ui-api/layout/{objectApiName}` documentation you shared and spotted the param needs to be passed part of the request params:

![Capture d’écran, le 2020-02-28 à 13 28 48](https://user-images.githubusercontent.com/1114325/75552466-4290c200-5a2e-11ea-9aa2-1e5a73cc7d1e.png)

It seems like only `layoutType` and `mode` are exposed atm, missing the `recordTypeID`.

**Comment by bhariharan** [comment]
[Android PR](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2045). Will have something up for `iOS` soon as well.

**Comment by bhariharan** [comment]
[iOS PR](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3162). This should be in our next release, i.e. `Mobile SDK 8.2`.

**Comment by jpmonette** [comment]
Thanks @bhariharan for putting this together!
