### ISSUE TITLE
Interactive dismissal - iOS 13 - Salesforce login views

### ISSUE THREAD

**Issue by Sahityatarumani** [forcedotcom/SalesforceMobileSDK-iOS#3163]
Please fill out the following details:

1. Version of Mobile SDK Used:  8.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 13.3
4. Device: iphone 11 pro max
5. Steps to reproduce:
-Launch the app that integrates the Salesforce native mobile SDK.
- On the login screen, tap on the top and drag the view down.

6. Actual behavior: The login screen is dismissed, leaving the App launch screen. The app will need to be killed and launched again to get to the login screen.

7. Expected Behavior: The login screen should cover the whole screen and user should not be able to dismiss it.
8. Error Log:

This is a new feature with iOS 13. On all of our custom views, we are handling it by setting the modalPresentationStyle of the viewController to .fullScreen.
We need this handled for the Salesforce SDK specific views also.

**Comment by wmathurin** [comment]
We fixed that in 8.0 (see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Security/SFUserAccountManager.m#L1873).

Are you sure you are running 8.0?

**Comment by Sahityatarumani** [comment]
@wmathurin I am very sure we are using version 8.0.
Below is the code snippet we are using :
       UserAccountManager.shared.loginHost = loginDomain
        //Hide setting navbar in login view
        let loginViewConfig = SalesforceLoginViewControllerConfig()
        //Hide settings icon on the nav bar
        loginViewConfig.showsSettingsIcon = false
        //Set showNavBar to false if you want to hide the top bar
        loginViewConfig.showsNavigationBar = false
        UserAccountManager.shared.loginViewControllerConfig = loginViewConfig



I still see the interactive dismissal. Can you think of any reason why this wont work for me?

**Comment by wmathurin** [comment]
How did you generate your applicaton?
