### ISSUE TITLE
how to set the badge show 99+，when the number more than 99？

### ISSUE THREAD

**Issue by qinqinHe-iOS** [forcedotcom/SalesforceMobileSDK-iOS#3165]
Please fill out the following details:
hello，i have  some question for the sdk？
sdk version：224.0.0

1、this badge should show 99+？ how to set the badge show 99+，when the number more than 99？

2、can I set a fixed width for the  min window？Instead of changing with the name？

![image](https://user-images.githubusercontent.com/62280213/76833365-29797500-6866-11ea-8257-febc0863495a.png)

**Comment by brandonpage** [comment]
Hi @qinqinHe-iOS, this repo is for the Salesforce Mobile SDK, not Snap-In's (a.k.a. the Service Cloud SDK), which is the product in your screenshot above.  Please contact Salesforce customer support in whatever way you typically do that.  Thanks.
