### ISSUE TITLE
Browser=Unknown and Platform=IOS/Mac User getting logout from the application.

### ISSUE THREAD

**Issue by nzsrini** [forcedotcom/SalesforceMobileSDK-iOS#3166]
Please fill out the following details:

1. A version of Mobile SDK Used:  7.0

2. Issue found in Native App or Hybrid App: Native
3. OS Version: 13.1
4. Device: IPAD
5. Steps to reproduce:

We are observing user are getting logged off from the device when the session [expires.](url)
![Remote_session](https://user-images.githubusercontent.com/13563565/77032441-3bdfe400-6a09-11ea-9a41-45095482ef41.png)

Is there any possibility when browser == Unknown and Platform = IOS/Mac is causing the user to log out?

Does the SDK sends browser and platform information to Salesforce Login History or is it independent of SDk?

**Comment by wmathurin** [comment]
Could you give us more information on the way login is setup on your org?
Do you have a custom login flow or other restrictions in place?

**Comment by nzsrini** [comment]
1)  Org Authentication -SAML Single Sign-On Settings
2) SAML Identity Type | Federation ID
We do not have custom login flows.
What we are observing 
1) Instead of getting a refresh token, the user is getting logged out. 
Please can you point in right direction to figure out what the issue is exactly?

**Comment by wmathurin** [comment]
What's your refresh token policy (see https://help.salesforce.com/articleView?id=connected_app_manage_oauth.htm&type=5 for more info).

**Comment by nzsrini** [comment]
Not any more issue. Thanks for your help.
