### ISSUE TITLE
Syncing Down Updated Children using SFParentChildrenSyncUpTarget

### ISSUE THREAD

**Issue by jpmonette** [forcedotcom/SalesforceMobileSDK-iOS#3167]
1. Version of Mobile SDK Used:  `8.1.0`
2. Issue found in Native App or Hybrid App: `native`
3. OS Version: `macOS 10.15.3 (19D76)`
4. Device: `iPad`
5. Steps to reproduce:

I have a simple project using this `usersyncs.json`:

```json
{
  "syncs": [
    {
      "syncName": "DownSync",
      "syncType": "syncDown",
      "soupName": "AccountSoup",
      "target": {
        "iOSImpl": "SFParentChildrenSyncDownTarget",
        "parent": {
          "idFieldName": "Id",
          "sobjectType": "Account",
          "modificationDateFieldName": "LastModifiedDate",
          "soupName": "AccountSoup"
        },
        "parentFieldlist": ["Id", "Name", "FirstName", "LastName", "RecordTypeId"],
        "children": {
          "parentIdFieldName": "MED_Account__c",
          "idFieldName": "Id",
          "sobjectType": "MED_Contact_Information__c",
          "modificationDateFieldName": "LastModifiedDate",
          "soupName": "ContactInformationSoup",
          "sobjectTypePlural": "MED_Contact_Information__r"
        },
        "childrenFieldlist": ["Id", "MED_Account__c"],
        "relationshipType": "LOOKUP",
        "type": "parentChildren",
        "idFieldName": "Id"
      },
      "options": { "mergeMode": "OVERWRITE" }
    },
    {
      "syncName": "UpSync",
      "syncType": "syncUp",
      "soupName": "AccountSoup",
      "target": {
        "iOSImpl": "SFParentChildrenSyncUpTarget",
        "childrenCreateFieldlist": ["MED_Account__c"],
        "parentCreateFieldlist": ["Name", "FirstName", "LastName", "RecordTypeId"],
        "childrenUpdateFieldlist": ["Id", "MED_Account__c"],
        "parentUpdateFieldlist": ["Id", "Name", "FirstName", "LastName", "RecordTypeId"],
        "parent": {
          "idFieldName": "Id",
          "sobjectType": "Account",
          "modificationDateFieldName": "LastModifiedDate",
          "soupName": "AccountSoup"
        },
        "relationshipType": "LOOKUP",
        "type": "rest",
        "modificationDateFieldName": "LastModifiedDate",
        "children": {
          "parentIdFieldName": "MED_Account__c",
          "idFieldName": "Id",
          "sobjectType": "MED_Contact_Information__c",
          "modificationDateFieldName": "LastModifiedDate",
          "soupName": "ContactInformationSoup",
          "sobjectTypePlural": "MED_Contact_Information__r"
        },
        "parentUpdateFieldlist": ["Id", "Name", "FirstName", "LastName", "RecordTypeId"],
        "idFieldName": "Id"
      },
      "options": { "mergeMode": "LEAVE_IF_CHANGED" }
    }
  ]
}
```
Once I execute that run sync, `Account` and `MED_Contact_Information__c` are synced down. 

6. Actual behavior:

If I create (assign) a new `MED_Contact_Information__c` record to an existing / synced `Account`, or update an existing one and resync, the new record (or updated) is not coming across.

The reason is that the SOQL query generated by the SDK is:
```sql
select Id, Name, FirstName, LastName, RecordTypeId, LastModifiedDate, (select Id, MED_Account__c from MED_Contact_Information__r where LastModifiedDate > 2020-03-19T14:23:53.000+0000) from Account where LastModifiedDate > 2020-03-19T14:23:53.000+0000 order by LastModifiedDate
```
7. Expected Behavior:

To sync down newly created (or updated) `MED_Contact_Information__c` records.
8. Error Log:

No error

**Comment by wmathurin** [comment]
As document [here](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/entity_framework_sync_related.htm)

> SOQL limitations affect how Mobile Sync can select child records in a single query. As a result, reSync can sync the changed children of changed parents, but not the changed children of unchanged parents. To work around this limitation, you can use a separate custom target that directly queries child objects.

**Comment by jpmonette** [comment]
@wmathurin What if there is a new child added to a parent that didn't change? I believe both the Parent/Children Sync Target as well as the additional sync down you mentioned.

**Comment by wmathurin** [comment]
Sync up will sync parent-children if the parent or any of children changed.
For sync up, the `getDirtyRecordIdsSql` method on the target is the one responsible for identifying changed records.
For parent children sync up, it goes to: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/dev/libs/MobileSync/MobileSync/Classes/Util/SFParentChildrenSyncHelper.m#L72 on iOS and to: https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/dev/libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/ParentChildrenSyncTargetHelper.java#L98 on Android.

For sync down, we only get parent-children when the parent changed.
That is due to limitation with SOQL. For more information see https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/dev/libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/ParentChildrenSyncDownTarget.java#L220
