### ISSUE TITLE
Not Getting error log from new SDK 8.1.0

### ISSUE THREAD

**Issue by jagadishkolli3933** [forcedotcom/SalesforceMobileSDK-iOS#3168]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.1.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 13.3
4. Device: iPhone/iPad
5. Steps to reproduce:
 we got error while syncing data to salesforce.
6. Actual behavior:
we are not getting error log from SFSDKSmartSyncLogger.sharedInstance().fileLogger.readFile() in latest SDK 8.1.0
**How we will get the error log? Using fileLog, Support team will fix the issues based on the error log**

7. Expected Behaviour:
Our old version of app is running on 6.2 SDK.
Below code used to get the error:
let fileLog = SFSDKSmartSyncLogger.sharedInstance().fileLogger.readFile()
Using fileLog, customers will send  errors as mail. Support team will fix the issues based on the error log.
8. Error Log:
MobileSync] CLASS: SFMobileSyncNetworkUtils sendRequestWithMobileSyncUserAgent:response:{
    compositeResponse =     (
                {
            body =             (
                                {
                    errorCode = "DUPLICATE_VALUE";
                    fields =                     (
                    );
                    message = "duplicate value found: External_Id__c duplicates value on record with id: XXXX";
                }
            );
            httpHeaders =             {
            };
            httpStatusCode = 400;
            referenceId = "XXXXXX";
        }
    );
}

**Comment by wmathurin** [comment]
We no longer use SalesforceFileLogger by default.
But it's still available. To use see the instructions on https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Hybrid/pull/10
