### ISSUE TITLE
App Scan Failed : M5: Insufficient Cryptography 

### ISSUE THREAD

**Issue by hanu** [forcedotcom/SalesforceMobileSDK-iOS#3169]
Please fill out the following details:
The MD5 algorithm is reported prone to a hash collision weakness. This weakness
reportedly allows attackers to create multiple, differing input sources that, when the
MD5 algorithm is used, result in the same output fingerprint. Attackers could, for
example, create a rogue software update that would be accepted and executed by an
update mechanism that validates updates by checking the MD5 hash signature.
When requiring a hash signature in a cryptographic use it is recomended to utilize
SHA-256, SHA-512 or Triple DES.
Review CWE-327: "Use of a Broken or Risky Cryptographic Algorithm" for additional
information.
Instance Location:
/Frameworks/SalesforceSDKCore.framework/
SalesforceSDKCore

1. Version of Mobile SDK Used: 
2. Issue found in Native App or Hybrid App: Native 
3. OS Version: 12
4. Device: iPAD
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

**Comment by wmathurin** [comment]
What version of the SDK are you looking at?
The MD5 methods were deprecated in 7.2 (https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2934) and removed in 8.0 (https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3019).
