### ISSUE TITLE
Best use of userstore.json and usersync.json

### ISSUE THREAD

**Issue by jpmonette** [forcedotcom/SalesforceMobileSDK-iOS#3170]
General question related to `userstore.json` and `usersync.json`:

Is it fair to say that these 2 files are great when:
- the syncs targets and store doesn't change;
- to configure fairly static database and syncing configuration.

However, if you have an application where:
- columns may be added to a soup (alter soups) and;
- sync queries my change (delete + create syncs)

Best approach would be to create our own logic to create/alter soups/syncs.

Is that your understanding as well of how to use these config files versus rely on the SDK API?

Thanks

**Comment by wmathurin** [comment]
The config files for syncs and stores are there for convenience.
You can create syncs and soups programmatically. That's probably the way to go if you need things to change at run time.

For soups, you don't need to alter them for new fields unless you need to do queries based on the new fields. Records stored in SmartStore don't need to have the same shape.

For syncs, if you need to fetch different sets, you should create a new sync (for instance a different SOQLSyncDownTarget that uses a different SOQL query). Alternatively, you could define a custom sync target (e.g. a subclass of SOQLSyncDownTarget) that does not have a fixed SOQL query but instead builds it when run.

**Comment by wmathurin** [comment]
Closing since this is not reporting a bug.
For questions, it's best to go to: https://salesforce.stackexchange.com/questions/tagged/salesforcemobilesdk-ios
