### ISSUE TITLE
Important APIs are removed when updated to MobileSDK 8.1

### ISSUE THREAD

**Issue by geekandt** [forcedotcom/SalesforceMobileSDK-iOS#3171]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.1
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: iOS 10 and up
4. Device: All devices.
5. Steps to reproduce:
Tried to authenticate user but cannot authenticate using the older APIs.
The older APIs that has an issue:
UserAccountManager.handleAdvancedAuthenticationResponse(url, options: [:])
UserAccountManager.authViewHandler
6. Actual behavior:
Cannot compile because of deprecated API
7. Expected Behavior:
Can compile

**Comment by geekandt** [comment]
Any updates??

**Comment by bhariharan** [comment]
@geekandt I don't understand what the issue/question is. Deprecated APIs will show up as warnings, but you should be able to compile with them. Either way, ideally you should replace the usage of the deprecated API with its newer equivalent.

**Comment by geekandt** [comment]
@bhariharan  what re the newer equivalent for UserAccountManager.handleAdvancedAuthenticationResponse(url, options: [:])
UserAccountManager.authViewHandler?

**Comment by trooper2013** [comment]
@geekandt How are you using the handleAdvancedAuthenticationResponse in the app? AdvancedAuth now does not need url handling. It is handled internally by the sdk in the advanced auth mode. You will need to continue to register the scheme in the plist. Why is the  authViewHandler  used?

**Comment by geekandt** [comment]
@trooper2013 
egarding `handleAdvancedAuthenticationResponse`, we’ll try to remove it but `authViewHandler` is critical, We use `authViewHandler` to capture the webView of the authentication flow and rewrite the URL to authenticate users with their username and password
Here is the code
```
self.accountManger.authViewHandler = AuthViewHandler(display: { (authViewHolder) in

if let webview = authViewHolder.wkWebView,
let url = webview.url,
var components = URLComponents(url: url, resolvingAgainstBaseURL: false),
let salesforceLogin = self.localStorage.salesforceLogin,
self.presentedWebview == nil {

UIApplication.shared.keyWindow?.addSubview(webview)
UIApplication.shared.keyWindow?.sendSubviewToBack(webview)
self.presentedWebview = webview

DispatchQueue.main.async {
var queryItems = components.queryItems ?? []
queryItems.append(URLQueryItem(name: "login_hint", value: salesforceLogin))
components.queryItems = queryItems

components.host = EndpointConstant.Salesforce.communityHost

if let url = components.url {
webview.load(URLRequest(url: url))

print("Showing auth address: \(url.absoluteString)")
}
}
}
}, dismiss: {
print("dismissing auth")

DispatchQueue.main.async {

self.presentedWebview?.removeFromSuperview()
self.presentedWebview = nil
}
})
```

**Comment by geekandt** [comment]
any updates?

**Comment by trooper2013** [comment]
@geekandt You can do the same by extending LoginViewController class. Simply override the loginviewcontroller creation block in UserAccountManager. Do this in the app delegate where you have other code for sdk initialization. Your loginViewController's setOauthView will be called at runtime, and at  which time you could replace the url.

```
 UserAccountManager.shared.loginViewControllerConfig.loginViewControllerCreationBlock =  {
            return MyViewController()
 }
```

```
class MyLoginViewController extends LoginViewController {
    override var oauthView: UIView? {
        didSet {
            if let wkwebView = oauthView as? WKWebView {
                wkwebView.isHidden = true
                wkwebView.load(< URL >)
            }
        }
    }
}
```

**Comment by geekandt** [comment]
Hi @trooper2013  thank you for the suggestion. We have implemented this and all is good.
Please close.
