### ISSUE TITLE
How to fix this pod issue while updating the salesforceMobileSDK-iOS

### ISSUE THREAD

**Issue by sundariragavan** [forcedotcom/SalesforceMobileSDK-iOS#3173]
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `SalesforceSDKCore` depends upon `SalesforceAnalytics`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

The Swift pod `SmartStore` depends upon `FMDB` and `SQLCipher`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

**Comment by wmathurin** [comment]
How did you get here?
What version of the Mobile SDK are you using? 
How did you generate your application?
Are you using `forceios`?

**Comment by sundariragavan** [comment]
Now i'm updating the salesforceSDK-iOS version from 6.2.0 to 8.1.0. While updating the pod 
I'm getting this error

[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `SalesforceSDKCore` depends upon `SalesforceAnalytics`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

The Swift pod `SmartStore` depends upon `FMDB` and `SQLCipher`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

**Comment by wmathurin** [comment]
I recommend you run forceios and either import your code in the generated app or look at the generated app podfile and copy that to yours.

**Comment by sundariragavan** [comment]
How to create a app using forcereact create
 I'm getting this error

/usr/local/lib/node_modules/forcereact/shared/commandLineUtils.js:46
            throw new Error('Illegal argument: ' + fullArg);
            ^

Error: Illegal argument: ios
    at parseArgs (/usr/local/lib/node_modules/forcereact/shared/commandLineUtils.js:46:19)
    at Object.processArgsInteractive (/usr/local/lib/node_modules/forcereact/shared/commandLineUtils.js:67:19)
    at Object.readConfig (/usr/local/lib/node_modules/forcereact/shared/configHelper.js:91:26)
    at Object.createApp (/usr/local/lib/node_modules/forcereact/shared/createHelper.js:217:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/forcereact/forcereact.js:36:14)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)

**Comment by wmathurin** [comment]
How did you install forcereact, what version of node / npm are you running?

**Comment by marlonatlumary** [comment]
Facing the same issue here

**Comment by marlonatlumary** [comment]
@sundariragavan   How did you get it fixed??

**Comment by sundariragavan** [comment]
@marlonatlumary I have created new project and updated my code. 
https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/react_native_new_project.htm
