### ISSUE TITLE
Not able to install the SDK using pod

### ISSUE THREAD

**Issue by akhilsuyati** [forcedotcom/SalesforceMobileSDK-iOS#3174]
I have used the folowing pod file:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'



 
target 'SalesforcePOC' do
source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git' # needs to be first 
source 'https://github.com/CocoaPods/Specs.git'

pod 'MobileSync'

  use_frameworks!
  



end 
```

I am getting the error.

```
[!] Unable to find a specification for `SQLCipher/fts (~> 4.2.0)` depended upon by `SmartStore/SmartStore`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.


[!] Automatically assigning platform `iOS` with version `13.2` on target `SalesforcePOC` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`
```

I tried updating repo but that isn't working either.

I am able to install other pods though.

**Comment by wmathurin** [comment]
Could you create an application using `forceios` and let us know if that works.

**Comment by sundariragavan** [comment]
I'm also getting this error when i install the pod file 

[!] CocoaPods could not find compatible versions for pod "SQLCipher/fts":
  In snapshot (Podfile.lock):
    SQLCipher/fts (= 3.4.2, ~> 3.4.1)

  In Podfile:
    SmartStore (from `../mobile_sdk/SalesforceMobileSDK-iOS`) was resolved to 8.1.0, which depends on
      SmartStore/SmartStore (= 8.1.0) was resolved to 8.1.0, which depends on
        SQLCipher/fts (~> 4.2.0)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `SQLCipher/fts` inside your development pod `SmartStore`.
   You should run `pod update SQLCipher/fts` to apply changes you've made.

**Comment by akhilsuyati** [comment]
@wmathurin  , I cannot do that because i have the application already developed beforehand . Just need to add pods.

**Comment by wmathurin** [comment]
Here is what we suggest you do: generate an application with forceios on the side and use it to adjust your podfile, AppDelegate etc. That should get you to a working app really quickly.
