### ISSUE TITLE
The salesforce login page is goes black when open the minimised app

### ISSUE THREAD

**Issue by sundariragavan** [forcedotcom/SalesforceMobileSDK-iOS#3175]
Please fill out the following details:

1. Version of Mobile SDK Used:  6.2.0
2. Issue found in Native App or Hybrid App: React Native
3. OS Version: 13.3
4. Device: iPhone 8 (13.3)
5. Steps to reproduce: 
                  Install the salesforce login integrated app 
                  open the app don't login
                  Just minimize the app
                  Open Again the login screen is not displaying ,the screen is goes black
                  Clear the background and open the app again , able to see the login screen.
                  The other version of the iphone mobile its working fine ( For example iPhone 8 (11.3)
6. Actual behavior: The screen is goes when open the minized app from background
7. Expected Behavior: Should able to see the login screen.
8. Error Log:

**Comment by wmathurin** [comment]
Please upgrade to the latest version of Mobile SDK (which has full support for iOS 13).
Mobile SDK 6.0 came out around the time iOS 11 was released - over two years ago.
