### ISSUE TITLE
'SFSDKSmartStoreLogger.h' file not found

### ISSUE THREAD

**Issue by mr0perfect** [forcedotcom/SalesforceMobileSDK-iOS#3180]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.1.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 12.2
4. Device: iPhone
5. Steps to reproduce: 
I'm upgrading all Mobile SDK Pods from 5.3.0 to 8.1.0 in the **Podfile**. As part of this my pod file looks like below

pod 'FMDB', :git => 'https://github.com/forcedotcom/fmdb', :branch => 'sdk'
**(if I don't mention the git and branch values here for FMDB, SmartStore is getting updated to 4.1.2 which is strange)**

pod 'SalesforceSDKCommon'
pod 'SalesforceAnalytics'
pod 'SalesforceSDKCore'
pod 'SmartStore'
pod 'MobileSync'

**Below Versions got installed as part of pod update**

FMDB(2.7.5)
SalesforceSDKCommon(8.1.0)
SalesforceAnalytics(8.1.0)
SalesforceSDKCore(8.1.0)
SmartStore(8.1.0)
MobileSync(8.1.0)

6. Actual behavior: When I open the project.xcworkspace and build the project I'm seeing the below error in **FMDatabasePool.m** class

#import "SFSDKSmartStoreLogger.h" -> **'SFSDKSmartStoreLogger.h' file not found**

7. Expected Behavior: 
Not sure why I'm seeing this issue. Is FMDB pod needed and if needed what should be the version of FMDB pod. How can I resolve this issue and do i need to make any changes in other files also after updating the pods?

I tried cleaning the project and building it again but still no luck.

8. Error Log:

**Comment by wmathurin** [comment]
The podfile should look like: https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/master/iOSNativeSwiftTemplate/Podfile

We recommend you generate an application with forceios and copy its pod file (and AppDelegate etc) into your existing project.
