### ISSUE TITLE
syncState.hasFailed returning False 

### ISSUE THREAD

**Issue by nzsrini** [forcedotcom/SalesforceMobileSDK-iOS#3182]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.1.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version:13.4 
4. Device:
5. Steps to reproduce:
6. Actual behavior:
syncState.hasFailed  is returning False
7. Expected Behavior:
syncState.hasFailed  should  return True
8. Error Log:
compositeResponse =     (
                {
            body =             (
                                {
                    errorCode = "INACTIVE_OWNER_OR_USER";
                    fields =                     (
                    );
                    message = "operation performed with inactive user [xxxx] as owner of xxxxxx";
                }
            );
            httpHeaders =             {
            };
            httpStatusCode = 400;
            referenceId = "local_8";
        }
    );

=================Trace--========================
 SFAdvancedSyncUpTask syncUpMultipleEntries
sendCompositeRequest-- 
sendRequestWithMobileSyncUserAgent

=====
we have upgraded application  SDK 5.2.0  to SDK 8.1.0.

**Comment by wmathurin** [comment]
It's not a client side issue.
Look at the error reported by the server: "operation performed with inactive user [xxxx] as owner of xxxxxx".
For some ideas on how that could happen, see:
https://success.salesforce.com/answers?id=9063A000000iXVSQA2

**Comment by nzsrini** [comment]
Totally understand it's not the issue of client-side.  
 Still when an error is received by client-side 
for example, Validation error while syncing and 
last_error__= "body = (
{
errorCode = "INACTIVE_OWNER_OR_USER";
fields = (
);
message = "operation performed with inactive user [xxxx] as owner of xxxxxx";
}
);
httpHeaders = {
};
httpStatusCode = 400;
referenceId = "local_8";
}"

Isn't supposed to be giving status syncState.hasFailed== true.

FYI: Old issue.
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2612

**Comment by wmathurin** [comment]
I understand your question now.

This is the behavior by design:
- the sync operation is only marked as failed if it could not get through all the records it needed to sync, for instance if the server is not reachable or the connection gets dropped.
- if it was able to send all local records to the server, the operation is marked as successful even if the server refused some of them for validation reason. A validation error on one record does not stop the sync operation from moving forward, it captures the error on the record and move on to the next one.

**Comment by nzsrini** [comment]
@wmathurin   Please can you confirm/comment the following scenarios.
1) Network failures-- will return syncState.hasFailed== True
2) Session expires/user connection issues  -- will return syncState.hasFailed== True

Any Validation errors /Trigger errors: Application code has to look for last errors and need to parse the last_error to display to the user.

Is any Utility method parses the last_error? or we have to use the string operations to parse the error?

Even the last_error is having error : 
sync.syncUp-- will try to resync the rows with last_error?

**Comment by wmathurin** [comment]
Network failures will return failed.
Access token expiration are handled automatically by the network classes of the SDK (token is refreshed and request is replayed).
Refresh token expiration/revocation cause the SDK to wipe user related data.

For validation errors, application should look for "dirty" records after running the sync (records that still have the locally modified flag set) and inspect the last error field.
We don't provide a helper method for parsing it at this point.

If you re-run sync up, it will run try every "dirty" records (the presence or absence of a last error is not taken into account).
