### ISSUE TITLE
NSError.domain is an URL instead of NSErrorDomain

### ISSUE THREAD

**Issue by simonnickel** [forcedotcom/SalesforceMobileSDK-iOS#3186]
1. Version of Mobile SDK Used: 8.1
2. Issue found in Native App or Hybrid App: Both
3. OS Version: All
4. Device: All
5. Steps to reproduce: Send request with error result.
6. Actual behavior: 

In the following delegate call:
```- (void)request:(SFRestRequest *)request didFailLoadWithError:(NSError*)error rawResponse:(NSURLResponse *)rawResponse;```

In case of an error which is not identified as an network error or does have a specific filtered status code. The error.domain is filled with the requests url, instead of an actual NSErrorDomain.

7. Expected Behavior:
error.domain is NSErrorDomain
8. Error Log: none

This is caused by SFRestAPI.m in line 388:
```return [[NSError alloc] initWithDomain:response.URL.absoluteString code:statusCode userInfo:errorDict];```

It is called by line 318 and creates an error in case of a response with successful network response, but HTTP status code indicating that something is wrong.

I guess instead of ```response.URL.absoluteString```, it should be ```kSFRestErrorDomain```. I am not sure though if this is the correct domain, would create a PR otherwise.

Can anyone verify that this would be the correct domain in that case?

**Comment by simonnickel** [comment]
Can anyone tell me if my assumption is correct? Would create a PR then.

**Comment by trooper2013** [comment]
@simonnickel A PR is welcome.

**Comment by bbirman** [comment]
Thanks @simonnickel for reporting! Fixed here: #3229
