### ISSUE TITLE
Upgrade to SDK7.3 from 5 causing issue and not showing the login screen of app.

### ISSUE THREAD

**Issue by Manjeetmetacube** [forcedotcom/SalesforceMobileSDK-iOS#3187]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.3
2. Issue found in Native App or Hybrid App:Hybrid App
3. OS Version:
4. Device: iOS mobile 
5. Steps to reproduce:upgrade app from SDK 5to 7.Now the application login is not even loaded.
6. Actual behavior: application show error message on launch.
7. Expected Behavior:Application should not show any error message and take the user to login page.
8. Error Log:

Hi,

Our earlier app which was on SDK5 was working with VPN tunneling of network traffic.In this SDK 5 we were using uiwebview as default 

But when we did upgrade app to the SDK 7 
The application when used through vpn tunnel network does not work and shows below error.

Can not connect to server the operation could not be completed.The operation not permitted.

This is the same behaviour with SF SDK based plain app also.

The suspect is the wkwebview and network tunnel through VPn .Do we have any work around for this in app?

The quick response will be really appreciated.

@wmathurin wm

Thanks, 
Manjeet

**Comment by bhariharan** [comment]
@Manjeetmetacube What is the error - could you post a stack trace? `Apple` has replaced `UIWebView` with `WKWebView` and as a result, `Mobile SDK` doesn't support `UIWebView` anymore either.

**Comment by Manjeetmetacube** [comment]
Hi,
I guess from SDK 7 mobile SDK usage wkwebview for login page.And the earlier SDK 5 login screen was using uiwebview and it is working fine now also.
I am attaching the error screenshot:

![ADE48FE6-604A-437C-AE40-F7D8B4EBED61](https://user-images.githubusercontent.com/30166868/80179152-86aed600-861d-11ea-821e-ec2b8fe0fdf9.png)

**Comment by Manjeetmetacube** [comment]
Yes and application is having problem when using wkwbview and running through any VPN network traffic tunnel.
Any update on this?

**Comment by wmathurin** [comment]
We need more information. We log in to apps built on top of Mobile SDK through VPN all the time without problems.

**Comment by Manjeetmetacube** [comment]
Does it work properly with wkwebview and MI network vpn tunnel?

**Comment by wmathurin** [comment]
You should probably follow up with Mobile Irons.
During login, all the Mobile SDK does is:
- build the authorization URL 
- load it into a WKWebView
- wait for the webview to go to the redirect url
I'm going to close the issue because I don't believe the issue lies with the Mobile SDK.
