### ISSUE TITLE
Visual force remoting support in Mobile SDK for local offline hybrid app?

### ISSUE THREAD

**Issue by Manjeetmetacube** [forcedotcom/SalesforceMobileSDK-iOS#3190]
Please fill out the following details:

1. Version of Mobile SDK Used: 8
2. Issue found in Native App or Hybrid App: local Hybrid
3. OS Version:
4. Device: All
5. Steps to reproduce:
6. Actual behavior: Visual force remoting working on web but does not work on mobile.
7. Expected Behavior:
8. Error Log:

Hi,

Question is Visual force remoting supported on local Mobile hybrid app using new network plugin?
Any work around for this?
@bhariharan @wmathurin

**Comment by wmathurin** [comment]
Could you tell how you are trying / planning to use them in a local hybrid application?

**Comment by Manjeetmetacube** [comment]
Without visual force page context is it possible in local app?

**Comment by wmathurin** [comment]
Probably not. I would recommend using apex rest instead. force.js which uses the network plugin has a convenience method for it.
