### ISSUE TITLE
Switch user flow and changing the connection(sanbox to prod or viceversa) shows the previous screen

### ISSUE THREAD

**Issue by Manjeetmetacube** [forcedotcom/SalesforceMobileSDK-iOS#3194]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.1.0
2. Issue found in Native App or Hybrid App:Hybrid App
3. OS Version:
4. Device: iPhone
5. Steps to reproduce: Login in Hybrid app -> Click on Add account->
Login screen ->change the connection->In between it shows the previous logged in screen-> then take to the login screen
6. Actual behavior:It Shows the previous screen
7. Expected Behavior: Should not show the previous screen
8. Error Log:

**Comment by Manjeetmetacube** [comment]
Hi,

Can you please provide any workaround for this?

Thanks,
Manjeet

**Comment by Manjeetmetacube** [comment]
@wmathurin

**Comment by riquier** [comment]
This is also affecting us we are on 8.1 using React Native

**Comment by gkotula** [comment]
Hi all, looking for some clarification:  Is it getting _stuck_ on the previous screen, or is the previous screen simply flashing onto the screen for a moment before changing to the new login screen?

Thanks!

**Comment by AnuragTiwari1** [comment]
Hi @gkotula, @wmathurin we are still facing this with v10.1.1 using React Native, the previous screen simply flashing onto the screen for a moment before changing to the new login screen, 

please suggest workaround for this.
