### ISSUE TITLE
Salesforce "sanpshot" window is appearing where it should not be.

### ISSUE THREAD

**Issue by ankita-chhikara** [forcedotcom/SalesforceMobileSDK-iOS#3195]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.3.0
2. Issue found in Native App or Hybrid App: Native app
3. OS Version: all versions
4. Device: all devices
5. Steps to reproduce: Explained the issue below
6. Actual behavior: Salesforce "snapshot" window appears where it should not be
7. Expected Behavior: Salesforce "snapshot" window should not appear
8. Error Log: NA

Issue:
We are using Salesforce Mobile SDK to authenticate into salesforce. As soon as the SDK is initialized, one additional window, named "snapshot" is created by salesforce. Confirmed this by UI debug mode and I can see the SFSDKWindow created in view hierarchy.
1 - When the app is backgrounded, app switcher view created in our app; which is used to cover the app screen on background, is replaced by a plain white view ("snapshot" window). Our app switcher view is visible on background when the salesforce sdk has not been initialized.
2 - We are using another SDK which triggers "SFAuthenticationSession" to launch a safari web view. Because of the "snapshot" window, mentioned previously, the safari session launched by another SDK gets attached to "snapshot" window instead of app's main window. As a result, nothing is visible on the screen. And when we make the app background, we can see the safari web view on the "snapshot" window. Also in the view hierarchy, I can see that "SFAuthenticationViewController" inside "SFSDKWindow".

We tried to resolve both of the above issues by setting the window to nil as following:
SFSDKWindowManager.shared().snapshotWindow.window = nil

This code worked on SDK version 6.2.0 . But after upgrading to 7.3.0, its not working anymore.

Now we need some resolution to deactivate the "snapshot" window.

**Comment by wmathurin** [comment]
Could you try with the latest version (8.1) and see if the issue is still happening?

**Comment by ankita-chhikara** [comment]
Hi @wmathurin , 
We have other third party frameworks in out app, (like ServiceSDK). We were having multiple issues when upgrading to 8.1 and thus have been recommended to use 7.3.0 version. 
But now the code which worked earlier is not working.

**Comment by az-oolloow** [comment]
I second that, there is some swizzling somewhere in the SDK which throws the white screen over your app when it goes to background, seems like a privacy feature. The problem it caused for us was that this white screen did not support landscape (like the rest of the SDK), so the user could not get to the control centre in landscape when using our app. Since we use a fork of the SDK we patched it ourselves, but it'd be really nice to have an official option to just disable this behaviour altogether,.

**Comment by trooper2013** [comment]
@az-oolloow @ankita-chhikara You can use the Salesforce SDK Manager to deactivate snapshot capability. Set useSnapshotView to `NO` or false.

**Comment by ankita-chhikara** [comment]
@trooper2013 Your suggestion worked. Thanks.
