### ISSUE TITLE
Error Domain=Server Error Code=1 / Information

### ISSUE THREAD

**Issue by nzsrini** [forcedotcom/SalesforceMobileSDK-iOS#3197]
Please fill out the following details:

1. version of Mobile SDK Used: 8.1.0

Please can you help, when can we expect these type of errors what do they mean?

"error description": "The operation couldn\u2019t be completed. (Server Error error 1.)"
Domain=SalesforceSDKCore.RestClientError Code=0 "(null)"}

**Comment by wmathurin** [comment]
Error code 0 is used when for errors reported by the rest API (non HTTP errors).
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/RestAPI/SFRestAPI.h#L33

Inspect the raw response that came back with the error for more information.
