### ISSUE TITLE
Layout components is an array of dictionaries

### ISSUE THREAD

**Issue by elvarliiv** [forcedotcom/SalesforceMobileSDK-iOS#3200]
The following code crashes at the moment on:     
if let c = ii.layoutComponents {. 

I also submited a fix as a pull request

guard let s = layout?.sections else {return}
                    for ss in s {
                        if let r = ss.layoutRows {
                            for rr in r {
                                if let i = rr.layoutItems {
                                    for ii in i {
                                        if let c = ii.layoutComponents {. 
                                            for cc in c {
                                                print(cc)
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }

**Comment by elvarliiv** [comment]
@siilats

**Comment by bbirman** [comment]
@elvarliiv thanks for reporting, fixed here: #3230
