### ISSUE TITLE
getDateFromIsoDateString : Null Exception.

### ISSUE THREAD

**Issue by nzsrini** [forcedotcom/SalesforceMobileSDK-iOS#3201]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.01
2. Issue found in Native App or Hybrid App:
3. OS Version:
4. Device: IOS
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

+ (NSDate *)SFMobileSyncObjectUtils.getDateFromIsoDateString
![Screen Shot 2020-05-19 at 8 53 10 PM](https://user-images.githubusercontent.com/13563565/82306336-09effb80-9a13-11ea-832e-66f0e1c0dc98.png)
:(NSString *)isoDateString {
    if (isoDateString.length == 0) {
        return nil;
    }
    
    return [isoDateFormatter dateFromString:isoDateString];
}

 We have updated the code to fix the issue.

+ (NSDate *)getDateFromIsoDateString:(NSString *)isoDateString {
+   if(![isoDateString isKindOfClass:[NSNull class]]){
+        return nil;
     }

Please can you review and update SDK.

**Comment by bbirman** [comment]
@nzsrini, thanks for reporting, we'll check it out

**Comment by bbirman** [comment]
This should be fixed by #3204.

**Comment by az-oolloow** [comment]
@bbirman is that PR part of 8.1?

**Comment by bbirman** [comment]
@az-oolloow it's not in 8.1 but it will be a part of 8.2
