### ISSUE TITLE
Inspect SmartStore using SQLite Explorer.

### ISSUE THREAD

**Issue by nzsrini** [forcedotcom/SalesforceMobileSDK-iOS#3202]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.1.0
2. Issue found in Native App or Hybrid App: Native APP.

Is it possible to disable encryption of datastore for debugging?

**Comment by wmathurin** [comment]
We don't expose an easy way to do that.
A developer in Xcode could simply comment out the code to `[db setKey:key]` in `+ (FMDatabase*) unlockDatabase:(FMDatabase*)db key:(NSString*)key salt:(NSString *)salt`in `SFSmartStoreDatabaseManager.m` and rebuild / restart the application.
