### ISSUE TITLE
Notify delegate of failure - obtain raw data?

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#3206]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.1.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 13.4.1
4. Device: iPad
5. Steps to reproduce: N/A
6. Actual behavior: Code issue
7. Expected Behavior: No code issue
8. Error Log: N/A

In SFRestApi, if the request fails with error, the delegate only receives the NSError and NSURLResponse out of NSURLSession callback, see here: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/RestAPI/SFRestAPI.m#L296

It would be beneficial to extend the delegate protocol to pass back the raw data as well.

**Comment by trooper2013** [comment]
@az-oolloow Is the error response from the rest api a non-JSON response?

**Comment by az-oolloow** [comment]
@trooper2013 the error is JSON, and it is parsed by the SDK into an NSError, but for some workflows where the error is returned by my RestResource API it is easier for me to parse the raw JSON. Considering the data is already provided by `URLSession` API, this change is relatively small?

**Comment by wmathurin** [comment]
Coming our next release (8.2), we now return the response (if available) to the error callback: see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3222
