### ISSUE TITLE
Localization of the pin code screen

### ISSUE THREAD

**Issue by denysvarchenko** [forcedotcom/SalesforceMobileSDK-iOS#3207]
Hello,
1. We are using SalesforceMobileSDK 7.3.0.
2. Native iOS app.
3-5 doesn't matter.

We need to have different localisations for title and instructions on the Create and Verify passcode controllers.
6. Currently in the Localizable.strings file I can see 3 localisation stings for these strings:
```
"createPasscodeNavTitle" = "Change PIN";
"confirmPasscodeNavTitle" = "Change PIN";
"verifyPasscodeNavTitle" = "Passcode";
```
So on the Create passcode view controller `createPasscodeNavTitle` and `verifyPasscodeNavTitle` are used. But the same localisations are used both for updateMode and create mode. So we cannot set for create passcode mode titles like `Create PIN` -> `Verify PIN` and for update mode `Set new PIN` -> `Verify new PIN`. The Verify passcode controller also is not flexible because it uses `verifyPasscodeNavTitle`,  and this title is used on Create passcode controller.

7. I would like to have possibility titles and instructions for al possible screen states. There should be 4 titles for Create passcode controller and 1 for Verify passcode controllers.

Could you please advice is there any way to make titles and instructions flexible? (without creating passcode controllers from scratch or duplicating your view controllers from SDK)

**Comment by bbirman** [comment]
@denysvarchenko, we've added additional strings for your use case here: #3231
