### ISSUE TITLE
A user account must be in the  SFUserAccountLoginStateLoggedIn state in order to create a sync for a user store.

### ISSUE THREAD

**Issue by abdulucf** [forcedotcom/SalesforceMobileSDK-iOS#3209]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.0.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 13.5
4. Device: iPAD Pro
5. Steps to reproduce: 

- Login in to the App

- Try to sync down using SmartSync(It will work)
- Logout from the app without closing it and log in again
- Try to sync down again (without closing the app) you will see the following message

> A user account must be in the  SFUserAccountLoginStateLoggedIn state in order to create a sync for a user store.

6. Actual behavior: Unable to use smartsync after logging back in without closing the app
7. Expected Behavior: User should be able to use smartsync no matter how many times he logs in without terminating the app
8. Error Log:

**Comment by wmathurin** [comment]
During logout the user smartstore is wiped, you should hold on to sync manager instances or smartstore instances anywhere in your code, or things will not work when a logout/login take place.
Instead, call `SmartStore.shared(...)`or `SyncManager.sharedInstance(...)` every time you need them.
