### ISSUE TITLE
UserId vs. FullUserId (Android and iOS Parity)

### ISSUE THREAD

**Issue by luonglegs** [forcedotcom/SalesforceMobileSDK-iOS#3211]
### Please fill out the following details:
This issue was brought up in the Salesforce Android SDK repo but I was told I should create a ticket for yall to address this. I believe the TL;DR is that iOS might need to standardize the 18 char on `userId`.

All of the discussions and details can be seen here:
https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/2071

1. Version of Mobile SDK Used: iOS
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Latest
4. Device: iPhone X
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log: N/A

**Comment by bhariharan** [comment]
Thanks @luonglegs! We will take a look.

**Comment by az-oolloow** [comment]
How did you get to `currentUser.userId` which returns 15 chars for you?

We get current user's id like this:
`UserAccountManager.shared.currentUserAccount?.idData?.userId` and this ALWAYS returns 18 chars for us.

**Comment by bbirman** [comment]
This should be fixed by #3214 and will be in the 8.2 release
