### ISSUE TITLE
PENTEST

### ISSUE THREAD

**Issue by yankelandroid** [forcedotcom/SalesforceMobileSDK-iOS#3212]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.3.0(1)
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: ios 12.0 *
4. Device: iphone

Hi I need to make pentest into my app and try to do man in the middle.
When i try it i receive an error 
Is there any ssl pinning into the sdk
If yes how can i remove it please ?

**Comment by wmathurin** [comment]
How are you doing you MITM pen testing?

**Comment by yankelandroid** [comment]
I would like to know does the SDK contain a pinning certificate or do I have to put one in place?

**Comment by wmathurin** [comment]
It does not contain a pinning certificate.

**Comment by yankelandroid** [comment]
ok I would like to put a pinning certificate in my application but I saw that it goes through urlsession or alamofire
Is there a way to implement it with the sdk using urlsession
If yes would you have a doc so that I know how to do it,
thank you so much

**Comment by wmathurin** [comment]
For "how to do xxx" question, please go to https://salesforce.stackexchange.com/questions/tagged/salesforcemobilesdk-ios.
Github issues are meant for reporting actual bugs with the Mobile SDK.

**Comment by az-oolloow** [comment]
@yankelandroid Just fork the SDK, the Rest API classes simply wrap NSURLSession and are pretty easy to modify.
