### ISSUE TITLE
SFBatchUploadTarget requires different permissions than SFSyncUpTarget

### ISSUE THREAD

**Issue by jwilliamscort** [forcedotcom/SalesforceMobileSDK-iOS#3215]
I have a weird edge case where the SFBatchSyncUp target fails for a user, but the SFSyncUpTarget succeeds. The object being synced is ContentVersion, and the user in question is using a Customer Community Login license. If I batch sync other objects, or use a full seat user, both targets work the same. 

Looking at the logs from the SFBatchSyncUpTarget syncs, it appears that the first item in the batch syncs successfully, but all remaining items return the following error:

body =             (
                                {
                    errorCode = "INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY";
                    fields =                     (
                        NetworkId
                    );
                    message = "You do not have the level of access necessary to perform the operation you requested. Please contact the owner of the record or your administrator if access is necessary.";
                },
                                {
                    errorCode = "INVALID_ID_FIELD";
                    fields =                     (
                        FirstPublishLocationId
                    );
                    message = "You must have a valid content feature license to publish into a private library.";
                }
            );

When the same sync is performed with SFSyncUpTarget, all items sync as expected.

Is there a different permission set that the SFBatchSyncUpTarget uses that the SFSyncUpTarget does not?

1. Version of Mobile SDK Used: 7.3.0
2. Issue found in Native App or Hybrid App: React Native App
3. OS Version: 13.3
4. Device: iPhone 8 Plus
5. Steps to reproduce: Sync Up of ContentVersion object with SFBatchSyncUpTarget vs. SFSyncUpTarget
6. Actual behavior: SFBatchSyncUpTarget fails on all but the first item in the sync.
7. Expected Behavior: All items sync correctly.
8. Error Log:

2020-06-04 20:16:17.576159-0500 Onsite Dev[7209:13774987] [SmartSync] CLASS: SFSmartSyncNetworkUtils sendRequestWithSmartSyncUserAgent:response:{
    compositeResponse =     (
                {
            body =             {
                errors =                 (
                );
                id = 068W0000000xm2dIAA;
                success = 1;
            };
            httpHeaders =             {
                Location = "/services/data/v46.0/sobjects/ContentVersion/068W0000000xm2dIAA";
            };
            httpStatusCode = 201;
            referenceId = "local_1591319751112";
        },
                {
            body =             (
                                {
                    errorCode = "INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY";
                    fields =                     (
                        NetworkId
                    );
                    message = "You do not have the level of access necessary to perform the operation you requested. Please contact the owner of the record or your administrator if access is necessary.";
                },
                                {
                    errorCode = "INVALID_ID_FIELD";
                    fields =                     (
                        FirstPublishLocationId
                    );
                    message = "You must have a valid content feature license to publish into a private library.";
                }
            );
            httpHeaders =             {
            };
            httpStatusCode = 400;
            referenceId = "local_1591319754786";
        },
                {
            body =             (
                                {
                    errorCode = "INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY";
                    fields =                     (
                        NetworkId
                    );
                    message = "You do not have the level of access necessary to perform the operation you requested. Please contact the owner of the record or your administrator if access is necessary.";
                },
                                {
                    errorCode = "INVALID_ID_FIELD";
                    fields =                     (
                        FirstPublishLocationId
                    );
                    message = "You must have a valid content feature license to publish into a private library.";
                }
            );
            httpHeaders =             {
            };
            httpStatusCode = 400;
            referenceId = "local_1591319758345";
        },
                {
            body =             (
                                {
                    errorCode = "INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY";
                    fields =                     (
                        NetworkId
                    );
                    message = "You do not have the level of access necessary to perform the operation you requested. Please contact the owner of the record or your administrator if access is necessary.";
                },
                                {
                    errorCode = "INVALID_ID_FIELD";
                    fields =                     (
                        FirstPublishLocationId
                    );
                    message = "You must have a valid content feature license to publish into a private library.";
                }
            );
            httpHeaders =             {
            };
            httpStatusCode = 400;
            referenceId = "local_1591319762152";
        },
                {
            body =             (
                                {
                    errorCode = "INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY";
                    fields =                     (
                        NetworkId
                    );
                    message = "You do not have the level of access necessary to perform the operation you requested. Please contact the owner of the record or your administrator if access is necessary.";
                },
                                {
                    errorCode = "INVALID_ID_FIELD";
                    fields =                     (
                        FirstPublishLocationId
                    );
                    message = "You must have a valid content feature license to publish into a private library.";
                }
            );
            httpHeaders =             {
            };
            httpStatusCode = 400;
            referenceId = "local_1591319768035";
        }
    );
}

**Comment by wmathurin** [comment]
The requests we send through SFBatchSyncUpTarget are the same we send one by one with SFSyncUpTarget. I don't think the problem lies with the SDK / client side code. I think you might be hitting an issue with the server side code handling of content version API calls. Can you manually repro the issue using [workbench](https://workbench.developerforce.com/login.php)?

**Comment by wmathurin** [comment]
A similar issue was reported for a different object type (leads), see https://trailblazers.salesforce.com/answers?id=9063A000000iOuOQAU.
It looks like a server side issue, and it means that for some object types, you might have to use the SFSyncUpTarget.
