### ISSUE TITLE
useragent should always be "<sf-useragent> <wkwebview-useragent>"

### ISSUE THREAD

**Issue by AubreyHewes** [forcedotcom/SalesforceMobileSDK-iOS#3216]
Please fill out the following details:

1. Version of Mobile SDK Used: 
https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin.git#v8.1.0 -> 
https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Hybrid#v8.1.0 -> 
https://github.com/forcedotcom/SalesforceMobileSDK-iOS#v8.1.0 -> 

2. Issue found in Native App or Hybrid App:
Hybrid App

3. OS Version:

4. Device:
iPad

5. Steps to reproduce:

  - Create a new hybrid app that displays the `navigator.userAgent` in the index.html
  - Run the app
  - After login the app displays the following user agent `<sf-useragent> <wkwebview-useragent>`
  - Stop the app
  - Restart the app
  - _You should not have to login..._
  - The app displays the following user agent `<sf-useragent>`

6. Actual behavior:
user agent is sometimes `"<sf-useragent> <wkwebview-useragent>"` and sometimes `"<sf-useragent>"`

This breaks expectations in libraries depending on a standard useragent

It seems that due to the async nature of retrieving the wkwebview useragent it is set too late when not requiring a login...

7. Expected Behavior:
user agent is always `"<sf-useragent> <wkwebview-useragent>"`

8. Error Log:
n/a

Does anyone know how I can fix this. Currently I have hardcoded the wkwebview useragent using the solution in https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1902#issuecomment-275819180 .. Though I would prefer to not hardcode and get it from wkwebview itself. Actually I would prefer that the SF code works.

Thanks.

#2240 #1902

**Comment by wmathurin** [comment]
Could you try with 8.0 or 8.1?
For 8.0, we fixed a user agent related issue: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2990

**Comment by AubreyHewes** [comment]
@wmathurin This is with v8.1.0 (sorry original post initially had a wrong version, I changed it straight away). Thanks.

**Comment by wmathurin** [comment]
We get the wkwebview-useragent through an asynchronous call (see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/dev/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Common/SalesforceSDKManager.m#L1008) so there is a short window of time at start up where your user agent will only be sf-user-agent instead of sf-user-agent wkwebview-useragent.
Is this a critical issue for your application?

**Comment by AubreyHewes** [comment]
@wmathurin yeah it is breaking as it is always "<sf-useragent>", as the async callback occurs after the view has loaded and so the `navigator.userAgent` is never updated.
The app uses a library that depends on a recognizable user-agent.

**Comment by AubreyHewes** [comment]
It is actually very easy to reproduce...

Issue actually as the issue describes....

Open app and login and redirect to index.html user agent is <sf-useragent> <webkit-useragent>
Close app 
Open app (login not required...) index.html is opened user agent is <sf-useragent>

As the useragent is updated async so after the view (if already logged in).. the user agent is the minimal <sf-useragent> and not <sf-useragent> <webkit-useragent>. Breaking app library expectancies.

This is not a offhand issue and should be resolved asap.

The only other solution is a custom useragent which breaks/makes-unknown future core updates...

**Comment by AubreyHewes** [comment]
Good to hear that someone will look at it!

**Comment by bhariharan** [comment]
Fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3331), this will be in our next release, i.e. `Mobile SDK 9.0`.
