### ISSUE TITLE
How to display the screen, before the salesforce login screen

### ISSUE THREAD

**Issue by sundariragavan** [forcedotcom/SalesforceMobileSDK-iOS#3221]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.1.0
2. Issue found in Native App or Hybrid App:React Native
3. OS Version:
4. Device:
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior: Could you please explain how to implement ?
8. Error Log:

**Comment by bhariharan** [comment]
@sundariragavan This forum is reserved for known bugs/issues with our code. For general queries, please read our developer guide or post on Salesforce Stack Exchange.
