### ISSUE TITLE
Push notification API

### ISSUE THREAD

**Issue by Nehora** [forcedotcom/SalesforceMobileSDK-iOS#3235]
Hi,
https://help.salesforce.com/articleView?id=connected_app_mobile_push_notifications.htm&type=5
I saw in this link it must using SalesforceMobileSDK for having the option to use Salesforce push notification in my iOS application.
The problem is we can't use in our project this SF SDK because of business logic.
I tried searching for an SF api to support the registration for push notification (instead of using `SFPushNotificationManager` function), but I didn't find something relevant.
How can I do that?
I assume if you do it in the SDK, there is a rest call/ an endpoint to use.

Thanks,
Nehora

**Comment by wmathurin** [comment]
Mobile SDK is open source, you can look at the source code to see exactly what we do. Mobile SDK only uses public APIs on the server.
