### ISSUE TITLE
Hybrid Remote App: App crashes if an Invalid Url is entered in connections

### ISSUE THREAD

**Issue by Jas05** [forcedotcom/SalesforceMobileSDK-iOS#3243]
Please fill out the following details:

1. Version of Mobile SDK Used: 
7.0, 8.1.0, 8.2.0

2. Issue found in Native App or Hybrid App:
Hybrid App

3. OS Version:
 iOS13.5
4. Device:
iPhone Pro Max, iPhone XR
5. Steps to reproduce:

- Open App,
- Click on Setting Icon on top right Corner
- Click on + Icon
- Enter a Invalid Url (with special characters)
- Click on Done
- App Will crash - and will never recover.

6. Actual behavior:
The app show an error dialog message in a loop.
Please have a look at the attached video

[RPReplay_Final1576831680.mp4.zip](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/4972511/RPReplay_Final1576831680.mp4.zip)
 
7. Expected Behavior:
The app should show the error(Invalid Url) but should allow the users to correct it.
8. Error Log:

**Comment by wmathurin** [comment]
By design, we don't want the start url to be configurable at runtime.
If you have that need in your application, you can fork the SDK and make the changes there.

**Comment by trooper2013** [comment]
@Jas05 Another thing you could do is, avoid the default error handling in this scenario. Can be done by adding a delegate to the SFUserAccountManager which will handle errors. Your app can decide to show an alternative alert and provide a means of handling an unreachable or invalid endpoint that could be configured by the user.

**Comment by wmathurin** [comment]
(Disregard my previous answer, I misunderstood the issue).
