### ISSUE TITLE
Can not retrieve data in BackgroundMode with BackgroundTask  

### ISSUE THREAD

**Issue by akaromka** [forcedotcom/SalesforceMobileSDK-iOS#325]
How can  I retrieve data in BackgroundMode? I setup BackgroundTask and send Request to Server, when I  click on Home Button, my request  freezes.

**Comment by camflan** [comment]
Please consider this a plead to bump this up on the timeline. We require background tasks for our app and are currently implementing our own – which I'm sure you would prefer we weren't :)

**Comment by bhariharan** [comment]
I believe this is now supported as of ```Mobile SDK 3.2```, since we have a new ```SalesforceNetwork``` library that supports background tasks.
