### ISSUE TITLE
Any Update on parseIdsFromResponses?

### ISSUE THREAD

**Issue by nzsrini** [forcedotcom/SalesforceMobileSDK-iOS#3258]
Thanks for this field.
Logic fails 
when the application doesn't receive the response from Salesforce when the network is unavailable but the record is already created at S.F end.

The application tries to update when the network is available again using external field then application receive a response with statuscode= 200 (Sucess).
///
In parseIdsFromResponses method, code is checking only status code==201.(Created)
 when we receive status 200 parseIdsFromResponses is returning null.

When it returns null it is not updated to local store.

====================================
+ (NSDictionary<NSString*, NSString*> *)parseIdsFromResponses:(NSArray<SFSDKCompositeResponse*>*)responses {
    NSMutableDictionary *refIdToId = [NSMutableDictionary new];
    for (SFSDKCompositeSubResponse* response in responses) {
        if (response.httpStatusCode == 201 ) {
            NSString *serverId = response.body[kCreatedId];
            refIdToId[response.referenceId] = serverId;
        }
    }
    return refIdToId;
}
-======
--- From Salesforce --
Example JSON response
In API version 46.0 and later, the HTTP status code is 200 (OK) and the successful response is:
{
    "id" : "001D000000Kv3g5IAB",
    "success" : true,
    "errors" : [ ],
    "created": false
}

_Originally posted by @nzsrini in https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3093#issuecomment-638141061_

**Comment by wmathurin** [comment]
Thanks for reporting this bug.

**Comment by wmathurin** [comment]
Fix will be in Mobile SDK 9.0 - see related pull requests above.
