### ISSUE TITLE
App crashes if non-JSON response (e.g. proxy) returned for MobileSync operation

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#3265]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.3.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 13.6.1
4. Device: iPad mini
5. Steps to reproduce:

Setup a proxy (e.g. Burp Suite) and run a MobileSync SOQL operation.
Intercept requests and drop them.

6. Actual behavior:
The app crashes

7. Expected Behavior:
The app does not crash.

8. Error Log:
N/A
---
This happens because the `SFRestAPI` simply passes the source NSData if the JSON parsing fails: (https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/dev/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/RestAPI/SFRestAPI.m#L382)

and the `SFSoqlSyncDownTarget` expects the result to be `NSDictionary` and never checks that it actually is. So when run in Swift this results in `unrecognized selector sent to instance` crash because `NSData` does not have `objectForKeyedSubscript:` method (aka NSDictionary's `[key]` subscript)

https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/dev/libs/MobileSync/MobileSync/Classes/Target/SFSoqlSyncDownTarget.m#L144

Solution: check if `responseJson` is actually `NSDictionary` before trying to use it.

**Comment by wmathurin** [comment]
Thanks for reporting this bug.

**Comment by wmathurin** [comment]
In a real life scenario, how do you get a successful response from a Rest API SOQL query that is NOT a valid json?

**Comment by az-oolloow** [comment]
@wmathurin if the device is going through a corporate proxy, and there is an issue on the corporate proxy end, in our environment the proxy returns an HTML payload. This causes the application to crash if this happens during sync.

**Comment by wmathurin** [comment]
It seems like an issue with your proxy - it should not return a 2xx response if it's not a proper response.
The whole SDK assumes that salesforce provided end points return the expected payloads.
I recommend you subclass SOQLSyncDownTarget and modify the code accordingly if you can't fix the proxy.

**Comment by az-oolloow** [comment]
Yeah, for our part we are looking at moving away from MobileSync/SmartSync altogether as it is not flexible enough for us, I raised it mostly as it is a simple fix and it would benefit other users of the SDK.
