### ISSUE TITLE
Multiple Named Sync Down per Soup

### ISSUE THREAD

**Issue by jpmonette** [forcedotcom/SalesforceMobileSDK-iOS#3270]
1. Version of Mobile SDK Used: `8.3.0`
2. Issue found in Native App or Hybrid App: React-Native
3. OS Version: `macOS 10.15.5 (19F101)`
4. Device: `iPad`
5. Steps to reproduce: `N/A`
6. Actual behavior: `N/A`
7. Expected Behavior: `N/A`
8. Error Log: `N/A`

---

Is it possible to have more than one named sync down for the same soup?

For example, I have an `Account` soup, where I would like to have the following Sync Down targets:

- SOQL `SELECT Id, Name FROM Account WHERE Type = 'Doctor'`
- SOQL `SELECT Id, Name FROM Account WHERE Type = 'Nurse'`

I understand it would be possible to combine them both in that simple case, but I would like to have the flexibility to add / remove some `Account.Type` over time, as well as use some more complex `WHERE` filtering criteria.

**Comment by wmathurin** [comment]
Yes you can feed a soup using different syncs (or even "manually" meaning saving records you fetched using our Rest API wrappers). You will have to be careful with reSync and cleanReSyncGhosts if the same record could have come from both syncs.
If you have records that came from different syncs in your soup, we recommend you use the Refresh sync down target to get their latest version. See https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/entity_framework_refresh_target.htm

**Comment by jpmonette** [comment]
@wmathurin Just to have a better understanding on what would be the successful sync strategy, which order of operation should I follow when I want to sync both remote and local changes?

Let's say my local database has been sourced with the following 2 syncDowns:
1. SOQL `SELECT Id, Name FROM Account WHERE Type = 'Doctor'`
2. SOQL `SELECT Id, Name FROM Account WHERE Type = 'Nurse'`

Also, let's say I:
- manually created a record locally that isn't covered by those 2 WHERE filtering criteria;
- delete a record on the server that was synced down by `1. SOQL`

To successfully syncup/syncdown, I would have to execute:

1. Sync Up Account Soup
2. ReSync `1. SOQL` Named Sync Down
   - That would bring any new/update `WHERE Type = 'Doctor'`
3. ReSync `2. SOQL` Named Sync Down 
   - That would bring any new/update `WHERE Type = 'Nurse'`
4. `Refresh` Sync Down (that would syncdown changes from any manually created records)
   - That would make sure that any extra record not covered by the 2 named syncs have their updates synced down

Is that the right order of execution? And how could I handle deleted records if `cleanResyncGhosts` is against a named sync?

**Comment by wmathurin** [comment]
Refresh will look for new versions of any records in the table. Therefore it overlaps somewhat with steps 2. and 3. You still need steps 2. and 3 however because there could be new records on the server matching your SOQL queries.

cleanResyncGhosts can take a sync id or sync name. 
Downloaded records record the sync id they came down with. 
cleanResyncGhosts looks for all the records "tagged" with that sync id, check if they are still in the result set of the SOQL query.
The problem is that if the set of records returned by query 1 and query 2 overlaps, cleanResyncGhosts for sync 2 could drop a record still matched by query 1 just because it's no longer in query 2 result set.

**Comment by jpmonette** [comment]
@wmathurin 
So let's say we have this configuration:

- 0 Sync Down
- 1 Sync Up on Accounts

Following steps are taken:

1. Record #1 and #2 are created on Mobile
2. Sync Up is executed against the Account soup
3. Record #1 is deleted from server
4. Record #2 is updated from server
4. Refresh is executed against the Account soup

I assume at this point, #2 would be updated locally with the changes, but #1 would still be there. Is this accurate?

If so, what is the recommended approach to go with cleaning ghosts of such records that may have been deleted on the server but not associated with any sync downs?

**Comment by wmathurin** [comment]
Running cleanReSyncGhosts for the refresh sync should take care of removing record 1.
