### ISSUE TITLE
SPM Support

### ISSUE THREAD

**Issue by starchey** [forcedotcom/SalesforceMobileSDK-iOS#3277]
Any plan to add SPM support?

**Comment by bhariharan** [comment]
We're evaluating it, and will consider adding support at a future time. We don't have a timeline yet.

**Comment by kristohear** [comment]
Any updates on it?

**Comment by bhariharan** [comment]
Not yet. We're waiting on some of our dependencies, such as `SQLCipher` to support SPM.

**Comment by kristohear** [comment]
@bhariharan but you guys are using it as a static prebuild xcframework now, as can be seen: external/ThirdPartyDependencies/sqlcipher/
Another third party dependency I see is FMDB(They support SPM), but it is added as git submodule.
Are there any other blockers?

**Comment by KarimAlweheshy** [comment]
Any updates on this? only third party that doesn't use spm yet. 
Please give this priority

**Comment by wmathurin** [comment]
@kristohear the static xcframework and the submodule are only used for the sample apps within the SalesforceMobileSDK-iOS repo. 
Apps that consume Mobile SDK do so by using forceios (which brings dependencies through Cocoapod).
When we add SPM support, we want to do it cleanly and not be packaging third party dependencies within the Mobile SDK.

**Comment by dppeak** [comment]
We try to avoid Cocoapods at all costs.  We're currently bring in the Mobile SDK as a git submodule and would much rather bring it in via XCFrameworks or using SPM.

**Comment by bhariharan** [comment]
@dppeak Since our source code is available, you could build our libraries using `xcodebuild` and bring it in as an `xcframework`, if you'd like.

**Comment by az-oolloow** [comment]
@wmathurin with Carthage no longer being officially supported one would hope that SPM support is somewhere close on the horizon. Cocoapods for SF SDK is painful.

**Comment by bhariharan** [comment]
@az-oolloow Could you provide details on which part of consuming our SDK using Cocoapods is painful? Cocoapods is the most popular dependency framework in the iOS ecosystem, and we have thousands of apps (both internal and external) using Cocoapods for consuming our SDK with no issues. It would be great if you could specify what your pain points are, so that we  can try to address them.

**Comment by jaapmengers** [comment]
I can't speak for  @az-oolloow, but in our team we're trying to move away from Cocoapods entirely and use SPM exclusively. The SF SDK along with some other libraries are preventing us from doing that. It would be great to know what the status for SPM support is.

**Comment by mthole** [comment]
+1 to this thread. SPM support is pretty standard in the iOS development world now and many folks are moving away from CocoaPods. Please add support ASAP.

**Comment by wiedem** [comment]
Cocoapods is a dead horse. We've also pulled it from all our native projects.
I really hope that the Salesforce development team will now react quickly, because Cocoapods with its intrusive way of manipulating the project files was never a good solution and only born out of necessity since there was no good alternative.

**Comment by gmckenzi** [comment]
@bhariharan This SDK is the only remaining pod in our project. And because it's a pod we can't split our app into local Swift Packages (referencing pods from a package isn't workable). So because the Salesforce Mobile SDK is a pod, it is impacting our ability to modularize our codebase using SPM.

**Comment by mthole** [comment]
@gmckenzi You might be able to take the .xcframeworks release by Salesforce and distribute them yourself via a forked repo that vends them to SPM. I no longer use this, but this worked for me back in 2021/2022 https://github.com/mthole/ServiceSDK-iOS/blob/master/Package.swift -- it's out of date, but something similar should be doable.

**Comment by wmathurin** [comment]
Finally added in Mobile SDK 11.1.0. For more information see: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/releases/tag/v11.1.0
