### ISSUE TITLE
Smart store not supporting iOS simulator in xcode 12

### ISSUE THREAD

**Issue by hanu** [forcedotcom/SalesforceMobileSDK-iOS#3279]
Please fill out the following details:

1. Version of Mobile SDK Used: 
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS Simulator
4. Device:
5. Steps to reproduce: Compiler failed
6. Actual behavior: used to work in Xcode11
7. Expected Behavior:
8. Error Log:Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_SFSDKLogger", referenced from:
      objc-class-ref in SFSDKSmartStoreLogger.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by brandonpage** [comment]
What version of the Mobile SDK are you using?  This compiler issues does not happen on v8.2.0.

**Comment by hanu** [comment]
pod 'SmartStore',:tag => '8.2.0', :path => 'SFDCsdk/SalesforceMobileSDK-iOS'

**Comment by wmathurin** [comment]
You should use :tag or :path not both at once.
Are you sure that directory SFDCsdk/SalesforceMobileSDK-iOS contains Mobile SDK 8.2?

**Comment by brandonpage** [comment]
I have not seen any issues building from within Xcode 12.

If you are building via the command line there is [an Apple bug](https://developer.apple.com/forums/thread/658071) that has existed for a while (I assume due to Catalyst) that could potentially be the cause of build issues for simulators.  I have found that adding `ARCHS=x86_64` to my xcargs when running xcodebuild fixes the issue.

**Comment by hanu** [comment]
Here is the pod versions

source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git' # needs to be first
  source 'https://github.com/CocoaPods/Specs.git'

  pod 'FMDB'
  
  pod 'SalesforceAnalytics', '~>8.2.0'
  pod 'SalesforceSDKCore','~>8.2.0'
  pod 'SmartStore', '~>8.2.0'
  pod 'SmartSync','~>7.2.0'

Trying since yesterday, removed all pods and installed again still seeing this error

<img width="673" alt="Screen Shot 2020-10-01 at 12 26 19 PM" src="https://user-images.githubusercontent.com/332682/94836735-5562df00-03e1-11eb-9156-31d8c1f36c5b.png">
<img width="1245" alt="Screen Shot 2020-10-01 at 12 26 13 PM" src="https://user-images.githubusercontent.com/332682/94836744-56940c00-03e1-11eb-9dbe-c078ef2974a1.png">

**Comment by wmathurin** [comment]
You shouldn't use SmartSync (it's called MobileSync now).

Take a look at the podfile in our generated apps https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/dev/iOSNativeTemplate/Podfile

If you don't want to point to a local :path, you can replace the :path entries with tags (as long as you use the extra `source` at the top).

Also Mobile SDK 8.3 was released last week.

**Comment by az-oolloow** [comment]
Just confirming that from our side (using Carthage though) we're fine on Xcode 12 and iOS 12 Simulator.

**Comment by wmathurin** [comment]
Unable to see the issue on our end - please re-open issue if you are able to repro it with the latest SDK.
