### ISSUE TITLE
Does Mobile SDK support idempotence / how does it support it?

### ISSUE THREAD

**Issue by jpmonette** [forcedotcom/SalesforceMobileSDK-iOS#3288]
This is more a general question about the behavior of the Mobile SDK when syncing on bad network.

Let's take the following scenario:

1. App execute a sync up to create 1 record;
2. Mobile SDK sends request to the Salesforce API;
3. Salesforce API receives the request and creates the record;
4. Network connection crashes before the mobile application receives the response.

What would happen next? Is the record rolled back on the Salesforce side, or is it created and the record on the device is not linked to it (Salesforce ID is not synced back)?
If the network connection is restored and the user tries to sync up again, is this going to create a duplicate record?

Thanks

**Comment by wmathurin** [comment]
If you need idempotent creation, use "upsert by external id" where the external id is a locally generated unique id.
It is supported with Mobile Sync. For more information see: https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/entity_framework_native_sync_up_external_id.htm

**Comment by az-oolloow** [comment]
@wmathurin the documentation is not very clear on this, doesn't this require us to configure those external ID fields on the sObjects in Salesforce? (which was always my assumption and which is why it is not always acceptable)

**Comment by wmathurin** [comment]
To avoid duplication, upsert by external id is the only way to go (because upsert are idempotent - so running the call a second time won't create a duplicate record).

**Comment by az-oolloow** [comment]
@wmathurin sorry, that still doesn't answer my question.

When you say 'external id' does it mean we need to have a field in an object in Salesforce server side designated as 'external id'?

**Comment by wmathurin** [comment]
Correct,  you need a custom field that has the External ID attribute, meaning that it contains unique record identifiers from a system outside of Salesforce (in this case the clients).
