### ISSUE TITLE
Is there a soup size limit, or sync size limit?

### ISSUE THREAD

**Issue by jpmonette** [forcedotcom/SalesforceMobileSDK-iOS#3290]
Is it possible to confirm if there is a technical limitation within either MobileSync, SmartStore or the API that would set a limit to how many records can be synced (using the Standard SOQL Sync Down Target)?

There are numerous examples in the documentation where a `LIMIT 10000` is set on sync down targets, and it seems quite arbitrary (and misleading that there may be a hard limit), especially considering the sync down target seems to support the `nextRecordsUrl`.

Example here in the doc:
https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/entity_framework_native_sync_down.htm?search_text=10000

I found this old ticket as well that seems to have doubt for the exact same reason:
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1455

**Comment by wmathurin** [comment]
There is no limit. The limit 10000 in the examples are indeed arbitrary - we have customers that are synching a lot more records than that.
It's up to the application. If you are going to have many records, make sure your UI does not block/wait on the sync operation, if you show the records in a list view, don't fetch them all from the db but use paging etc.
