### ISSUE TITLE
Are MERGE_ACCEPT_YOURS, MERGE_FAIL_IF_CONFLICT and MERGE_FAIL_IF_CHANGED merge modes still supported?

### ISSUE THREAD

**Issue by jpmonette** [forcedotcom/SalesforceMobileSDK-iOS#3291]
It seems like following merge modes in the documentation have no reference within both the iOS and Android codebases. Are they deprecated/outdated? If so, is it possible to update the documentation?

Missing merge modes:

- `MERGE_ACCEPT_YOURS`,
- `MERGE_FAIL_IF_CONFLICT` and 
- `MERGE_FAIL_IF_CHANGED`

What seems to be the only currently supported merge modes:

- `OVERWRITE` and
- `LEAVE_IF_CHANGED`

Reference:
https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/entity_framework_conflict_detection.htm?search_text=merge%20mode

**Comment by wmathurin** [comment]
Before the existing Mobile Sync native implementation, we had a javascript based sync library for hybrid apps (https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/dev/libs/mobilesync.js). These flags/that documentation apply to that library.
