### ISSUE TITLE
 Grant type not supported error in reactNative SDK for iPad/iphone

### ISSUE THREAD

**Issue by vivekdeshmane** [forcedotcom/SalesforceMobileSDK-iOS#3311]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.3.0
2. Issue found in Native App or Hybrid App: React Native
3. OS Version:14.2
4. Device: iPhone/iPad
5. Steps to reproduce: We are using reactNative salesforce mobile SDK on iPhone/iPad and logging in using custom domain and SSO sign in and requesting data from salesforce using SDK,
6. Actual behavior: we are able to login but post login getting Grant type error, Hence we are not able to retrieve data from SFDC.
7. Expected Behavior: Post login, We should able to retrieve data instead Grant type error. 
8. Error Log: Error: {
    NSLocalizedDescription = "grant type not supported";
    error = "unsupported_grant_type";
}

**Comment by bhariharan** [comment]
@vivekdeshmane This forum is reserved for bugs/issues with the library code. As the error indicates, it looks like the OAuth scopes you're requesting do not match with what's configured on the connected app.
