### ISSUE TITLE
Any update on the release of SalesforceMobileSDK-iOS 9.0 version?

### ISSUE THREAD

**Issue by jeevanandhamr** [forcedotcom/SalesforceMobileSDK-iOS#3321]
Please fill out the following details:

We are currently using the SalesforceMobileSDK-iOS 8.1.0 in our project and planning to upgrade to latest SDK during end of December 2020 or early January 2021.

Could you please let us know the expected date of release of the version 9.0?

So that we can plan our work accordingly whether to upgrade to 8.3.0 or wait for 9.0 if it is not taking longer time to release.

1. Version of Mobile SDK Used: 8.1.0
2. Issue found in Native App or Hybrid App: No issue
3. OS Version: iOS
4. Device:
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

Thanks

**Comment by bhariharan** [comment]
Tentatively early Feb 2021. #safeharbor

This forum is reserved for issues with our code. For other general queries, please use Stack Exchange.

**Comment by jeevanandhamr** [comment]
Thank you very much for the information. Sure, next time I will use Stack Exchange for this kind of queries.
