### ISSUE TITLE
SDK prevents user from seeing "Select Pictures..." modal

### ISSUE THREAD

**Issue by rpander93** [forcedotcom/SalesforceMobileSDK-iOS#3334]
iOS14 contains a new option that allows user to give the app only access to certain pictures in your camera roll. When the user is prompted to grant access and selects this option, an iOS modal should appear where the user can select the pictures. The Salesforce SDK instead prevents this modal from the user appearing, so the permission handler is never called and to the user it appears as if nothing has happened.

Our app has been rejected from the App Store review due to this.

I create two projects in [this repository](https://github.com/rpander93/react-native-permission-test).

For the one without the SDK installed, if you press the Request permission button you'll see the pop-up. Select the option "Select Photos..." and you can select a number of pictures. After that, you return to the app and this [log statement will be printed](https://github.com/rpander93/react-native-permission-test/blob/abb0c9d3d89a3b611d235a1456510342dbf2828d/PermissionTest/App.tsx#L39).

For the one with the SDK installed, after pressing the "Request permissions" button and selecting the "Select Photos..." option you may or may not briefly see the modal appearing (if you do, it immediately vanishes again). [This log statement](https://github.com/rpander93/react-native-permission-test/blob/abb0c9d3d89a3b611d235a1456510342dbf2828d/PermissionTestSalesforceSDK/app.js#L39) is never printed.

1. Version of Mobile SDK Used: 8.3
2. Issue found in Native App or Hybrid App: React Native
3. OS Version: iOS 14
4. Device: multiple
5. Steps to reproduce: Clone repository & install apps. Follow steps above.
6. Actual behavior: Select Photos modal to appear
7. Expected Behavior: Modal immediately disappears
8. Error Log:

**Comment by wmathurin** [comment]
What are you using to show the modal from React Native?
If you are using react-native-image-picker, have you seen the solution [here](https://github.com/react-native-image-picker/react-native-image-picker/issues/1340)?

**Comment by rpander93** [comment]
![afbeelding](https://user-images.githubusercontent.com/1412227/106863227-7bb6c500-66c8-11eb-85b4-4c997cd70788.png)

This is the modal I'm referring to. It's from iOS, so you cant show it in a react native modal obviously. It should appear automatically after requesting the permission for the 1st time and picking the "Select Photos..." option. From the projects in my example, you see that this breaks when the SDK is included.

**Comment by rpander93** [comment]
@wmathurin any chance this can be resolved soon? We've had to remove this functionality altogether now.

**Comment by wmathurin** [comment]
It's getting fixed with https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3337
It will be in our soon to be released Mobile SDK 9.0.
