### ISSUE TITLE
Build 9.0.0 using Carthage with --use-xcframeworks

### ISSUE THREAD

**Issue by simonnickel** [forcedotcom/SalesforceMobileSDK-iOS#3339]
Trying to build the newest SDK version with the new Carthage version (supporting xcframeworks).

But the build seems to be failing.

Please fill out the following details:

1. Version of Mobile SDK Used: 9.0.0
2. Issue found in Native App or Hybrid App: Build SDK with Carthage
3. OS Version: Xcode 12.4
4. Device: -
5. Steps to reproduce: `carthage update --use-xcframeworks`
6. Actual behavior: Build failed
7. Expected Behavior: Framework is build.
8. Error Log: 
```
...
*** Building scheme "MobileSync" in SalesforceMobileSDK.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/.../Carthage/Checkouts/SalesforceMobileSDK-iOS/SalesforceMobileSDK.xcworkspace -scheme MobileSync -configuration Release -derivedDataPath /Users/.../Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/SalesforceMobileSDK-iOS/v9.0.0 -sdk iphonesimulator -destination platform=iOS\ Simulator,id=DF1F4C5B-349B-47E4-84F4-2C7BBC2D9589 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build VALIDATE_WORKSPACE=NO (launched in /Users/.../Carthage/Checkouts/SalesforceMobileSDK-iOS)

This usually indicates that project itself failed to compile.
```

**Comment by bhariharan** [comment]
`Mobile SDK` does not officially support `Carthage`, we recommend using `Cocoapods` instead.

**Comment by brandonpage** [comment]
@simonnickel I got Mobile SDK consumption via Carthage working while testing the Mobile SDK 9.0 release a couple weeks ago using a workaround provided by the Carthage team on github.

I created a file called `tmp.xcconfig` with the following:
```
EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64=arm64 arm64e armv7 armv7s armv6 armv8
EXCLUDED_ARCHS=$(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT))
```

Run `export XCODE_XCCONFIG_FILE=$PWD/tmp.xcconfig` before running your usual Carthage commands.

I tested this using `carthage bootstrap --use-xcframeworks` on the Carthage test setup I have been testing against for many releases.

**Comment by simonnickel** [comment]
@brandonpage I will give that a try, thanks!

**Comment by simonnickel** [comment]
@brandonpage Thanks again, this works 😊

**Comment by glambhimani** [comment]
I am using tmp.xcconfig file and when running `carthage bootstrap --use-xcframeworks `I am getting below error : 

$ carthage bootstrap --use-xcframeworks
*** Checking out SalesforceMobileSDK-iOS at "119ac34302de12420519324d5b5eca233621821b"
*** xcodebuild output can be found in /var/folders/pd/zmbt5b015511dchpbdf8vszh0000gn/T/carthage-xcodebuild.2mi7JI.log
*** Building scheme "SalesforceSDKCommon" in SalesforceMobileSDK.xcworkspace
*** Building scheme "SalesforceAnalytics" in SalesforceMobileSDK.xcworkspace
*** Building scheme "MobileSync" in SalesforceMobileSDK.xcworkspace
*** Building scheme "SalesforceSDKCore" in SalesforceMobileSDK.xcworkspace
*** Building scheme "SmartStore" in SalesforceMobileSDK.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/anjali/Projects/Upwork/SourceCodeGit/Carthage/Checkouts/SalesforceMobileSDK-iOS/SalesforceMobileSDK.xcworkspace -scheme SmartStore -configuration Release -derivedDataPath /Users/anjali/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/SalesforceMobileSDK-iOS/119ac34302de12420519324d5b5eca233621821b -sdk iphonesimulator -destination platform=iOS\ Simulator,id=2AD803EB-A3FC-497E-9665-E403470297F1 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build VALIDATE_WORKSPACE=NO (launched in /Users/anjali/Projects/Upwork/SourceCodeGit/Carthage/Checkouts/SalesforceMobileSDK-iOS)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/pd/zmbt5b015511dchpbdf8vszh0000gn/T/carthage-xcodebuild.2mi7JI.log

```
In Log file : ld: library not found for -lsqlcipher-iphonesimulator
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **
```

**Comment by az-oolloow** [comment]
@bhariharan it is really sad that Carthage is no longer officially supported, makes migrating to 9.0 that much more painful.
