### ISSUE TITLE
Login sometimes redirects to salesforce.com home page (Native app)

### ISSUE THREAD

**Issue by iowlit** [forcedotcom/SalesforceMobileSDK-iOS#3340]
1. Version of Mobile SDK Used: 8.3.0
2. Issue found in Native App or Hybrid App: Both
3. OS Version: 14,*
4. Device: iPads

Details and STR attached here https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3328

I assume that the issue takes place in SalesforceSDKCore (I've left the https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3328#issuecomment-779862506). 
The issue is rather related to this repo as far as Cordova SDK just wraps the SalesforceSDKCore.
Maybe someone else has also faced the issue and knows the solution.

**Comment by az-oolloow** [comment]
Commented on https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/466

But we basically get the exact same behaviour as @iowlit

**Comment by wmathurin** [comment]
The login flow inside the webview is a black box in the Mobile SDK and is entirely driven by the server side oauth code.
I believe the server side team is aware of the issue but it's considered low priority. I can't say when or whether it will get fixed.
