### ISSUE TITLE
on iOS app keeps launching login screen asking for credentials - React Native

### ISSUE THREAD

**Issue by DiaaAlzein** [forcedotcom/SalesforceMobileSDK-iOS#3341]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.0.0
2. Issue found in Native App or Hybrid App: React Native app
3. OS Version: iOS 13.4.1
4. Device: iPhone XS Max 
5. Steps to reproduce: 
    - Create an empty project using Salesforce command line tool 
    - run `react-native run-ios`
    - Enter credentials then press login and finish the login steps
    - React Native app starts then it launch the login screen again (loop never ends)
6. Actual behavior:  Login screen keeps showing after user finish the login process
7. Expected Behavior: Just like Android case, user enters credentials only once and app starts
8. Error Log: No logs

**Comment by lal1020** [comment]
@DiaaAlzein The same issue still occurs in our project also, is your bug is closed now?

**Comment by DiaaAlzein** [comment]
@lal1020 yes downgrading the cocoapods fixed the issue, here are the configuration and versions used:

* cocoapods - 1.9.3
* @react-native-mapbox-gl/maps - 8.1.0
* Ruby - 2.7.1
* Xcode 12.2
