### ISSUE TITLE
Using SDK with Notification Service Extension ?

### ISSUE THREAD

**Issue by jiwansvmx** [forcedotcom/SalesforceMobileSDK-iOS#3345]
Does the SDK work with UNNotificationServiceExtension ?
1. Version of Mobile SDK Used:  `8.3.0`
2. Issue found in Native App or Hybrid App: `React Native`
3. OS Version: `10.15.7,  Xcode Version: 12.0.1, CocoaPod Version: 1.10.0 , ios: '12.2'`
4. Device: `iphone X , ios Version:13.6.1`
5. Steps to reproduce: 

- Setup a notification service extension 
```swift
import UserNotifications
import SalesforceSDKCommon
import SalesforceSDKCore
import SmartStore

class NotificationService: UNNotificationServiceExtension {
  
  var contentHandler: ((UNNotificationContent) -> Void)?
  var bestAttemptContent: UNMutableNotificationContent?
  
  override init() {
    super.init()
    SalesforceSDKCommon.DataSharingHelper.shared.appGroupName = getAppGroupName()
    SalesforceSDKCommon.DataSharingHelper.shared.isAppGroupEnabled = true
    // SalesforceManager.initializeSDK() This causes a crash
  }
  func getAppGroupName() -> String {
    let prefix = "group."
    return prefix + Bundle.main.bundleIdentifier!.replacingOccurrences(of: ".nsextension", with: "")
  }
  
  override func didReceive(_ request: UNNotificationRequest, withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void) {
    self.contentHandler = contentHandler
    bestAttemptContent = (request.content.mutableCopy() as? UNMutableNotificationContent)
    if let bestAttemptContent = bestAttemptContent {
      guard let currentUserAccount = UserAccountManager.shared.currentUserAccount else { // currentUserAccount is always nil
        NSLog("NotificationService  %@", "couldn't get current user account");
        contentHandler(bestAttemptContent)
        return
      }
      NSLog("NotificationService %@", "access token is \(String(describing: currentUserAccount.credentials.accessToken))")
      contentHandler(notificationContent)
    }
  }
  
  override func serviceExtensionTimeWillExpire() {
    if let contentHandler = contentHandler, let bestAttemptContent =  bestAttemptContent {
      contentHandler(bestAttemptContent)
    }
  }
  
}
```
Here is the app delegate
```objc
@implementation AppDelegate

- (id)init
{
  self = [super init];
  if (self) {
    
    [SFSDKDatasharingHelper sharedInstance].appGroupName = [self getAppGroupName];
    [SFSDKDatasharingHelper sharedInstance].appGroupEnabled = YES;
    // Need to use SalesforceReactSDKManager in Salesforce Mobile SDK apps using React Native
    [SalesforceReactSDKManager initializeSDK];
//    [SFKeychainItemWrapper setAccessibleAttribute:kSecAttrAccessibleAfterFirstUnlock];
    

    [SalesforceSDKManager sharedManager].useSnapshotView = false;
    //App Setup for any changes to the current authenticated user
    __weak typeof (self) weakSelf = self;
    [[NSNotificationCenter defaultCenter] addObserverForName:kSFNotificationUserDidLogout  object:nil queue:[NSOperationQueue mainQueue]  usingBlock:^(NSNotification *note) {
      [weakSelf resetViewState: ^ {
        [weakSelf initializeAppViewState];
        [weakSelf authenticateIfRequired];
      }];
    }];
    
  }
  
  return self;
}

- (NSString *) getAppGroupName {
  NSString *bundleId = [[NSBundle mainBundle] bundleIdentifier];
  return [@"group." stringByAppendingString:bundleId];
}

```
I have app-groups setup and able to share user defaults between app and extension.

6.  Actual behavior:

 Couple of issue
-   `SalesforceManager.initializeSDK()` This crashes the extension . The debugger pauses on some webkit function.
-  `UserAccountManager.shared.currentUserAccount` in NotificationService is always nil.  I dug and noticed that 
the error from [this line](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/UserAccount/SFDefaultUserAccountPersister.m#L257) is actually ignored but when I passed error parameter got the following error.
![Screen Shot 2021-03-05 at 4 27 18 PM](https://user-images.githubusercontent.com/32343606/110188532-dbd87e00-7dd0-11eb-98ed-405e2d71abb0.png)

In addition, I did  `po encKey.keyAsString` at the breakpoint and noticed that the key is different when running in the app vs when running in the extension.

That's as far as i could get.

7. Expected Behavior: Should be able to access user account in the extension.

8. Error Log: Attached above

Thanks in advance!!!!

**Comment by wmathurin** [comment]
Did you look at our template that uses the notification service extension: https://github.com/forcedotcom/SalesforceMobileSDK-Templates/tree/dev/iOSNativeSwiftEncryptedNotificationTemplate ?

**Comment by jiwansvmx** [comment]
@wmathurin Thanks for responding. I just looked at and it's not the same because the template doesn't use app groups.

**Comment by wmathurin** [comment]
Have you read our documentation on the topic [there](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/ios_using_app_extensions.htm)?

**Comment by jiwansvmx** [comment]
Actually, I was under the wrong impression.  Adding to  same app group is not enough, you need to both the app and the extension to same keychain access groups access group as well.   I just retried by adding same `keychain-access-groups` to both the app and the extension in their respective entitlements and now works. 
Thanks @wmathurin for pointing me at the docs.
