### ISSUE TITLE
Does Salesforce Mobile SDK 9.0 compatible with react native maps using google maps in iOS?

### ISSUE THREAD

**Issue by Minrit** [forcedotcom/SalesforceMobileSDK-iOS#3346]
1. Version of Mobile SDK Used: 9.0
2. Issue found in Native App or Hybrid App: React Native
3. OS Version: mac OS 10.15.7 XCode 12.4
4. Device: iPhone 12 Pro Max
5. Steps to reproduce: I imported the [react native maps](https://github.com/react-native-maps/react-native-maps) into the project and try to use Google Maps, but I get some link errors during compile. After checking the project, I found that it seemed that `use_frameworks!` in the podfile caused the issue. But after I removed this code, the `pod install` couldn't be done for mobile sdk.

**Comment by wmathurin** [comment]
Could you tell in more details how you imported the react native maps?
Generated app using forcereact v9.0.0 support auto-linking, so you should only need to update your package.json, then run npm update followed by pod update.

**Comment by Minrit** [comment]
If I just tried to use react native maps, everything is OK. But if I want to change the map provider to Google according to [this](https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#enabling-google-maps-on-ios-react-native-all-versions) I got some fun compile errors caused by Google Maps and Google Maps Utils. And if I remove the `use_frameworks!` in podfile and mobile sdk, everything in map works well.

**Comment by Minrit** [comment]
Could anyone help me with this?

**Comment by wmathurin** [comment]
Could you try adding the following to the podfile of your application?
Maybe react-native apps does not support being compiled as a dynamic framework.
```
pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.eql?('react-native-maps')
        def pod.build_type
          Pod::BuildType.static_library
        end
      end
    end
  end
```

**Comment by wmathurin** [comment]
Closing issue since we have not heard back after our last suggestion.
