### ISSUE TITLE
Archiving app with the SalesforceMobileSDK fails even though the app buils and runs fine

### ISSUE THREAD

**Issue by igorkulman** [forcedotcom/SalesforceMobileSDK-iOS#3356]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.1.0
2. Issue found in Native App or Hybrid App: native
5. Steps to reproduce: 

I have a native Swift app with SalesforceMobileSDK 8.1.0 added as git submodule to the workspace

<img width="246" alt="Screen Shot 2021-03-29 at 13 46 37" src="https://user-images.githubusercontent.com/4746070/112832170-3940b180-9095-11eb-966d-a2d03fba4895.png">

The app builds and runs just fine in both the simulator and an actual device.

The problem is that when I want to archive the app for distribution building the SmartStore project fails with 3 errors

<img width="1220" alt="Screen Shot 2021-03-29 at 13 49 37" src="https://user-images.githubusercontent.com/4746070/112832457-a3595680-9095-11eb-8a28-35e3abc5e234.png">

```
SalesforceMobileSDK-iOS/libs/SmartStore/SmartStore/Classes/SFSDKStoreConfig.m:47:33: Use of undeclared identifier 'SFSDKResourceUtils'
```

```
SalesforceMobileSDK-iOS/libs/SmartStore/SmartStore/Classes/SFSDKStoreConfig.m:60:42: No visible @interface for 'NSDictionary' declares the selector 'nonNullObjectForKey:'
```

```
SalesforceMobileSDK-iOS/libs/SmartStore/SmartStore/Classes/SFSDKStoreConfig.m:69:75: No visible @interface for 'NSDictionary' declares the selector 'nonNullObjectForKey:'
```

This is quite strange because the app just runs fine, only archiving is the problem and it is currently blocking the project

**Comment by wmathurin** [comment]
The preferred approach is to use `forceios` to generate your application. It will bring the Mobile SDK dependencies through cocoapod. We test that with every release and it is used by countless customers without problems.

**Comment by igorkulman** [comment]
I added the SDK to an existing app and using Cocoapods is not an option in my environment

**Comment by wmathurin** [comment]
If you don't want to use cocoapods, please follow the manual steps documented [here](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/ios_new_native_project_manual.htm).
