### ISSUE TITLE
prepare-framework failing

### ISSUE THREAD

**Issue by TomSwift** [forcedotcom/SalesforceMobileSDK-iOS#3375]
Our `prepare-framework` (https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_ios.meta/service_sdk_ios/ios_prepare_for_appstore.htm) build step has become unreliable.   It seems to fail 50% or more of the time with this error:

```
500 Can't verify SSL peers without knowing which Certificate Authorities to trust http://www.apple.com/DTDs/PropertyList-1.0.dtd
Handler couldn't resolve external entity at line 2, column 101, byte 140
error in processing external entity reference at line 2, column 101, byte 140:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
====================================================================================================^
<plist version="1.0">
<string>com.salesforce.ChatCoreBundle</string>
 at /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level/XML/Parser.pm line 187.
Command PhaseScriptExecution failed with a nonzero exit code

```
It fails both in our local builds (XCode 12.4) and hosted builds (XCode 12.2.2) so is not specific to one build machine or environment.   

1. Version of Mobile SDK Used: 224.0.0
2. Issue found in Native App or Hybrid App: native
3. OS Version: macOS 10.15.7
4. Device: n/a, build issue
5. Steps to reproduce: run build with prepare-framework build step
6. Actual behavior: build fails
7. Expected Behavior: build succeeds
8. Error Log:

**Comment by bhariharan** [comment]
`ServiceSDK` is a different product - this is not the right forum for queries regarding `ServiceSDK`.
