### ISSUE TITLE
Custom localisation for passcode screens

### ISSUE THREAD

**Issue by oleksandrPolukhin** [forcedotcom/SalesforceMobileSDK-iOS#3387]
Hey! On the Passcode screens (SFSDKPasscodeCreateController, etc) we need to use not the language that is used on the device, but the one that the user selects before login. Is there some way to replace the bundle from which SFSDKResourceUtils will take localized strings or some other alternative way? In version 8.3, which we are still using, there is an opportunity to replace passcode screens, but you removed it in version 9.0.0. Swizzling is not the best option either.

**Comment by wmathurin** [comment]
Passcode screen are going away in (the soon to be released) 9.2.
