### ISSUE TITLE
I am using tmp.xcconfig file and when running `carthage bootstrap --use-xcframeworks `I am getting below error :

### ISSUE THREAD

**Issue by glambhimani** [forcedotcom/SalesforceMobileSDK-iOS#3390]
I am using tmp.xcconfig file and when running `carthage bootstrap --use-xcframeworks `I am getting below error : 

$ carthage bootstrap --use-xcframeworks
*** Checking out SalesforceMobileSDK-iOS at "119ac34302de12420519324d5b5eca233621821b"
*** xcodebuild output can be found in /var/folders/pd/zmbt5b015511dchpbdf8vszh0000gn/T/carthage-xcodebuild.2mi7JI.log
*** Building scheme "SalesforceSDKCommon" in SalesforceMobileSDK.xcworkspace
*** Building scheme "SalesforceAnalytics" in SalesforceMobileSDK.xcworkspace
*** Building scheme "MobileSync" in SalesforceMobileSDK.xcworkspace
*** Building scheme "SalesforceSDKCore" in SalesforceMobileSDK.xcworkspace
*** Building scheme "SmartStore" in SalesforceMobileSDK.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/anjali/Projects/Upwork/SourceCodeGit/Carthage/Checkouts/SalesforceMobileSDK-iOS/SalesforceMobileSDK.xcworkspace -scheme SmartStore -configuration Release -derivedDataPath /Users/anjali/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/SalesforceMobileSDK-iOS/119ac34302de12420519324d5b5eca233621821b -sdk iphonesimulator -destination platform=iOS\ Simulator,id=2AD803EB-A3FC-497E-9665-E403470297F1 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build VALIDATE_WORKSPACE=NO (launched in /Users/anjali/Projects/Upwork/SourceCodeGit/Carthage/Checkouts/SalesforceMobileSDK-iOS)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/pd/zmbt5b015511dchpbdf8vszh0000gn/T/carthage-xcodebuild.2mi7JI.log

```
In Log file : ld: library not found for -lsqlcipher-iphonesimulator
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **
```

_Originally posted by @glambhimani in https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3339#issuecomment-846524948_

**Comment by rwhitley** [comment]
As of Mobile SDK 9.0, Carthage is no longer supported. https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/ios_carthage.htm

Please use CocoaPods instead: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/ios_cocoapods.htm

**Comment by glambhimani** [comment]
I have tried this workaround and it was working : https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3339
