### ISSUE TITLE
How to decrypt the notification from Salesforce push notification

### ISSUE THREAD

**Issue by Minrit** [forcedotcom/SalesforceMobileSDK-iOS#3396]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.0
2. Issue found in Native App or Hybrid App: React Native
3. OS Version: 14.6
4. Device: iPhone 12 Pro Max

What we want is to get the content in the payload of the notification from Salesforce. Our app was created by 'forcereact' according to [Salesforce Mobile SDK React Native](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/react_native_intro.htm) We have tried to use the 'decryptNotificationContent' in the 'SFSDKPushNotificationDecryption.m' but we always got a null value. We have tried to debug why this happened and found that 'getRSAKeyRefWithTag' in the 'SFSDKCryptoUtils' couldn't get the private key.

**Comment by wmathurin** [comment]
Please have a look at this template: https://github.com/forcedotcom/SalesforceMobileSDK-Templates/tree/dev/iOSNativeSwiftEncryptedNotificationTemplate
