### ISSUE TITLE
403 on services/oauth2/userinfo in case of expired session

### ISSUE THREAD

**Issue by Lyubinets** [forcedotcom/SalesforceMobileSDK-iOS#3398]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 14.4.1
4. Device:iPad
5. Steps to reproduce: send RestRequest (services/oauth2/userinfo) via RestClient with expired token
6. Actual behavior: returns 403 and error
7. Expected Behavior: should try to refresh token as it was in old version 7
8. Error Log: 
<NSHTTPURLResponse: 0x2811ce300> { URL: https://naz--uat.my.salesforce.com/services/oauth2/userinfo } { Status Code: 403, Headers {
    "Cache-Control" =     (
        "no-cache,must-revalidate,max-age=0,no-store,private"
    );
    "Content-Security-Policy" =     (
        "upgrade-insecure-requests"
    );
    Date =     (
        "Thu, 08 Jul 2021 12:31:01 GMT"
    );
    "Set-Cookie" =     (
        "CookieConsentPolicy=0:0; domain=naz--uat.my.salesforce.com; path=/; expires=Fri, 08-Jul-2022 12:31:01 GMT; Max-Age=31536000",
        "BrowserId=WvZ079_oEeuE0eN6gQ7UDg; domain=.salesforce.com; path=/; expires=Fri, 08-Jul-2022 12:31:01 GMT; Max-Age=31536000"
    );

I am using this API to identify if session is still valid. I was expecting that AuthHelper.loginIfRequired will do all work, but it looks like it does not refresh token. Running sync without valid tokken causing crash. So I need to check if token is valid in this way, but latest version does not handle and don't refresh token in case of 403

**Comment by Lyubinets** [comment]
Here is commit where handling of 403 was removed https://github.com/forcedotcom/SalesforceMobileSDK-iOS/commit/5159060d07b40f05d66df96d75eb4cb89a5912ce#diff-d19e19adcb0a01e1e71d3f7bf979be23355da3011f8880cc2112b71bb877b928

**Comment by wmathurin** [comment]
For an example of code that does a cheap request to refresh token check out https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Hybrid/blob/dev/libs/SalesforceHybridSDK/SalesforceHybridSDK/Classes/SFHybridViewController.m#L761.

That being said, sync should not crash if the access token is expired. Instead the token should be refreshed automatically and request replayed. Could you give us more information (type of sync, type of app, tec).

**Comment by Lyubinets** [comment]
"RestClient.shared.requestForUserInfo()" Is not working properly in latest SDK because it's not refreshing token. 
You can see it in the next screenshot. Here I have expired token and RestClient.shared.requestForUserInfo() returns 403.
<img width="735" alt="Screenshot 2021-07-12 at 12 08 43" src="https://user-images.githubusercontent.com/13054201/125261472-f7690d80-e309-11eb-8777-4ade90366425.png">
<img width="1073" alt="Screenshot 2021-07-12 at 12 04 01" src="https://user-images.githubusercontent.com/13054201/125261541-0780ed00-e30a-11eb-8764-79fdf6bebeab.png">

**Comment by wmathurin** [comment]
You’ll get 403 for /userinfo  if your refresh token has expired or your user profile doesn’t have API access. You shouldn’t be using /userinfo for  refresh anymore. There is a  dedicated refresh() API on iOS and Android to address this issue. It goes directly against the /token endpoint and performs a refresh (1 API call (vs) 2, and no 403 risk).

See SFUserAccountManager.h
```objective-c
- (BOOL)refreshCredentials:(nonnull SFOAuthCredentials *)credentials
                completion:(nullable SFUserAccountManagerSuccessCallbackBlock)completionBlock
                   failure:(nullable SFUserAccountManagerFailureCallbackBlock)failureBlock NS_REFINED_FOR_SWIFT;
```

For instance, you could do
```objective-c
  _ = AppContext.current.userAccountManager.refresh(credentials: credentials) { [weak self] (result) in
            DispatchQueue.main.async { [weak self] in
                switch result {
                case .success((let userAccount, let authInfo)):
                    self?.authenticationCompletion(responseUrl?.absoluteString, authInfo: authInfo)
                case .failure(let error):
                    switch error {
                    case .refreshFailed(underlyingError: let error, authInfo: let authInfo):
                        self?.authFailureCallbackBlock(authInfo, error)
                    default:
                    }
                }
            }
```

**Comment by Lyubinets** [comment]
Thanks, this refresh API works for me. Anyway I still use /userinfo to check if session is valid, because I don't want to refresh token more than its needed. In my case crash happens randomly if token is expired and I call some big synchronisation process. I have list of entities and run sync with NSOperation, so I have up to 7 running sync processes in parallel. I was not able to reproduce it today, but there was some multithreading crash inside SFSDK. I will report it if I will have more info.
Thanks again, you helped a lot.
