### ISSUE TITLE
Submission to Apple with new MFA requirements - recommended approach

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SalesforceMobileSDK-iOS#3412]
Now that in February 2022 MFA will be mandatory, what is Salesforce best practice on submitting apps built on this native SDK to Apple for review?

Our app is logging in through standard login.salesforce.com and uses the built in WKWebView UI presented by the SDK.

One workaround we found is temporary auth code but it's a whole extra manual step when submitting the app and those expire 24 hours max.

**Comment by mattlacey** [comment]
Doesn't seem to be much feedback at all on issues on GH - we're going to be coming up against this as well, and as you say, it's getting pressing!

**Comment by JimBTek** [comment]
so looks like the most recent SDK supports MFA via the standard login flow EXCEPT it dumps you into Salesforce Classic instead of your app on the first go.

**Comment by tscholze** [comment]
I know this is old, but what works, at least for me:

Add the Secret to user Demo-Apple-User to the message box besides the credentials form in App Store Connect

**Comment by wmathurin** [comment]
See https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/265
