### ISSUE TITLE
RestClient.shared.send throws timed out error.

### ISSUE THREAD

**Issue by petrovRV** [forcedotcom/SalesforceMobileSDK-iOS#3414]
Is it possible to increase the time out for a request?

I have tried batch request in postman, this spends more than 80 seconds.
But on an iPad, I was faced with an error "time out" that throws after 60 seconds.
This error throws in this file SFRestAPI.m (297 line).

**Comment by az-oolloow** [comment]
@petrovRV since it is not clear how exactly you're calling RestClient as you didn't provide any code (e.g. I've no idea if this works for Combine extensions) you can set the session configuration like so:

```
        let config = URLSessionConfiguration.default
        config.timeoutIntervalForRequest = 400.0
        config.timeoutIntervalForResource = 400.0
        Network.setSessionConfiguration(config, identifier: NetworkEphemeralInstanceIdentifier)
```
