### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by martinop** [forcedotcom/SalesforceMobileSDK-iOS#3425]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.0.2
2. Issue found in Native App or Hybrid App: React Native App
3. OS Version: Mac Os Catalina (10.15.7)
4. Device: Emulator iPhone 11 (14.4)
5. Steps to reproduce: try to compile
6. Actual behavior: error on compile
7. Expected Behavior: compile

![image](https://user-images.githubusercontent.com/10482079/134721194-29a751ed-2557-4156-bf35-144d529fdf66.png)

**Comment by martinop** [comment]
with the play button (xcode) @wmathurin

**Comment by wmathurin** [comment]
Did you create the application using `forcereact`? Could you try the latest Mobile SDK version (9.1.1).

**Comment by martinop** [comment]
yes with `forcereact`, the problem at this moment is with the iOs SDK I'm using the dev branch

**Comment by wmathurin** [comment]
What version of Xcode are you using?

**Comment by wmathurin** [comment]
We have fixed the issue for our upcoming release (9.2). See https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/dev/ReactNativeTemplate/ios/Podfile#L34

**Comment by martinop** [comment]
I have Version 12.4 (12D4e),  I have this error
![image](https://user-images.githubusercontent.com/10482079/136712307-a01909bf-30df-4db9-9bad-c0ef427438e0.png)
 @wmathurin 

![image](https://user-images.githubusercontent.com/10482079/136712335-6d600160-5424-45bf-a701-093c543ec1c5.png)
![image](https://user-images.githubusercontent.com/10482079/136712340-6c0a3261-a986-4ed6-b8a4-5c3eeac52e09.png)

**Comment by martinop** [comment]
I'm not using a M1 machine

**Comment by wmathurin** [comment]
Mobile SDK 9.2: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/gs_whatsnew.htm

**Comment by martinop** [comment]
so i'm using react-native-force and the current version is 10.0.0 I can't found 9.2.0

**Comment by martinop** [comment]
what kind of solution is that? anyway I did that and I have this error:
![image](https://user-images.githubusercontent.com/10482079/137004459-60315063-8e22-4b11-bd38-7b7d9cf2a350.png)
but I'm using the same scopes (bootconfig.plist) from the previous project
