### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_SFSDKLogger && Undefined symbol: _OBJC_METACLASS_ $_SFSDKLogger

### ISSUE THREAD

**Issue by SreekanthGudisi** [forcedotcom/SalesforceMobileSDK-iOS#3426]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.2.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version:  15
4. Device: Simulator 15 and iPhone 14.7
5. Steps to reproduce: 

**Using XCode - 13 and below pods**

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def common_pods
   # Pods for SalesForceSDK
   pod 'SalesforceAnalytics', :path => 'mobilesdk/SalesforceMobileSDK-iOS'
   pod 'SalesforceSDKCore', :path => 'mobilesdk/SalesforceMobileSDK-iOS'
   pod 'SmartStore', :path => 'mobilesdk/SalesforceMobileSDK-iOS'
   pod 'SmartSync', :path => 'mobilesdk/SalesforceMobileSDK-iOS'
   pod 'SalesforceSwiftSDK', :path => 'mobilesdk/SalesforceMobileSDK-iOS'
   pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit', :tag => '5.0.3'
end

target 'CFL FI' do
  
  use_frameworks!
  common_pods

end
```

8. Error Log:

**When I suppose to run the app it's giving the following image error.** 

<img width="1141" alt="Screenshot 2021-09-26 at 4 24 28 AM" src="https://user-images.githubusercontent.com/23524697/134866430-b7261186-8eae-4801-ac32-0c2ea3bdfd8c.png">

**I have tried deleting derived data, pod deintegrate and pod install but not working.**

**Comment by wmathurin** [comment]
Mobile SDK 6.2 was released quite a few years back.
We will soon release Mobile SDK 9.2 and it works with the latest version of XCode and iOS. 
We recommend you upgrade.
