### ISSUE TITLE
Login screen: switching to another app to copy/paste the username or password does not store the info

### ISSUE THREAD

**Issue by geospatialqueryapi** [forcedotcom/SalesforceMobileSDK-iOS#3432]
Please fill out the following details:

1. Version of Mobile SDK Used: 
9.2.0

2. Issue found in Native App or Hybrid App:
Native App 

3. OS Version:
15.0
4. Device:
iPhone 12.0

5. Steps to reproduce:
Login screen: switching to Notes to copy/paste the username or password

6. Actual behavior:
Going back refreshes the login screen and loses the previously entered info.

7. Expected Behavior:
Should store the entered values temporarily otherwise the user should remember
both username and password.

**Comment by brandonpage** [comment]
I am not able to reproduce this behavior, the login page does not refresh when I return to the app.
