### ISSUE TITLE
Blank blue screen on force touch of email, and navigation to external safari app for hyperlinks

### ISSUE THREAD

**Issue by umangshuMTX** [forcedotcom/SalesforceMobileSDK-iOS#3435]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.0.0
2. Issue found in Native App or Hybrid App: Not redirecting to an external link on custom community login page 
3. OS Version:14.5
4. Device:iPhone 11
5. Steps to reproduce: Click on any email hyperlink and links within the custom
<img width="480" alt="Screenshot 2021-10-05 at 11 52 45 AM" src="https://user-images.githubusercontent.com/60922890/135971663-d7060a63-6525-48ee-ad91-2b64d811be3f.png">
 community page.
6. Actual behavior: Force touch on email and any other link make the screen goes blue. 
7. Expected Behavior: Should redirect to the link or open email, also needs to open link to external safari app
8. Error Log:

**Comment by gkotula** [comment]
Hello @umangshuMTX Apologies for the long delay in getting back to you, but are you still encountering this issue with the latest Mobile SDK version?

**Comment by umangshuMTX** [comment]
Yes, still with the older version of SDK.

**Comment by gkotula** [comment]
> Yes, still with the older version of SDK.

Could you check whether this issue is reproducible with the latest version of the SDK?  It may be resolved simply with an update.  Thanks!

**Comment by gkotula** [comment]
Closing due to lack of response.
