### ISSUE TITLE
Unable to Set Sforce-Auto-Assign using Smartsync

### ISSUE THREAD

**Issue by vivekdeshmane** [forcedotcom/SalesforceMobileSDK-iOS#3444]
**A version** of Mobile SDK Used: 8.3.0
**Issue found in Native App or Hybrid App:** React Native
**OS Version:**14.2
**Device**: iPhone/iPad
**Steps to reproduce:** We are using react-native salesforce mobile SDK on iPhone/iPad  and  While creating SFDC Lead using smartSync/reSynce, We want to set auto-assignment rule false to avoid lead assignment rule logic in SFDC.
**Actual behaviour**: We can't see the option to set Sforce-Auto-Assign flag false like REST API set header option.
Could you please let us know if mobile SDK Smartsync support this feature or not?

**Comment by wmathurin** [comment]
One way to do it with today's code is to:
* Extend the sync up target class that you use,
* Override the sendRequest class (see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/dev/libs/MobileSync/MobileSync/Classes/Target/SFSyncUpTarget.m#L279) - the SFRestRequest object has `setHeaderValue:forHeaderName:` method (see https://forcedotcom.github.io/SalesforceMobileSDK-iOS/Documentation/SalesforceSDKCore/html/Classes/SFRestRequest.html#//api/name/setHeaderValue:forHeaderName:).
