### ISSUE TITLE
Can we continue to use SFSDKBiometricViewController to show app specific message before iOS asks permission for biometrics

### ISSUE THREAD

**Issue by PPunya** [forcedotcom/SalesforceMobileSDK-iOS#3452]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.2.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 14.6, 15.1
4. Device: Any iPhone
5. Steps to reproduce: 
Install iOS app. Open the app. Provide user credentials and login. 

6. Actual behavior:
After successful login, alert is shown by iOS.
![IMG_FADB8460BBE0-1 copy 2](https://user-images.githubusercontent.com/68283420/145433813-8f4324c1-d155-4b7a-8ecd-d34d77d34c57.jpeg)

7. Expected Behavior:
We want something like this:
A screen asking user about permission and if user selects Yes, then only iOS asks permission.
![IMG_1689 copy 2](https://user-images.githubusercontent.com/68283420/145430150-46526cd8-ccf2-45ee-b5ab-344b37e3442a.PNG)
![IMG_1688 copy](https://user-images.githubusercontent.com/68283420/145433784-5e391dee-b5dd-4d17-9665-5416a6817ba0.PNG)

8. Error Log:
NA

**Comment by gkotula** [comment]
We have taken note of this and several other similar requests to enable more customization around the lock screen; however, we cannot commit to a timeframe to add this functionality at this time.

**Comment by wmathurin** [comment]
Closing this issue since SFSDKBiometricViewController has been deprecated in 9.x and removed in 10.0.
