### ISSUE TITLE
iOS 15: Login screen disappears and all pasted values  need to be entered again.

### ISSUE THREAD

**Issue by geospatialqueryapi** [forcedotcom/SalesforceMobileSDK-iOS#3466]
Please fill out the following details:

1. Version of Mobile SDK Used: 
9.2.1
2. Issue found in Native App or Hybrid App:
I've aa native  iOS App with a button starting Salesforce functionality.
When the user clicks on this button a modal view is presented and 1st time users 
need to login:
---
import SwiftUI
import MobileSync
import SalesforceSDKCore

struct SFModalViewUI: View {
    var body: some View {
        VStack(alignment: .center){
           MyListView()
        }
        .onAppear(perform: start)
    }
}
func start() {
    Task {
        AuthHelper.loginIfRequired {
            // Setup store based on config userstore.json
            MobileSyncSDKManager.shared.setupUserStoreFromDefaultConfig()
            // Setup syncs based on config usersyncs.json
            MobileSyncSDKManager.shared.setupUserSyncsFromDefaultConfig()
        }
    }
}
---

3. OS Version:
iOS 15.2

4. Device:
iPhone 13 Pro Max

5. Steps to reproduce:
The login needs custom domain and username. For convenience
they are stored in iOS Notes.

5.1 Custom Domain/copy from iOS Notes.
5.2 Switch to the iOS App - Login screen - Custom Domain/paste
5.3 Switch to iOS Notes/ copy username
5.4 Switch to iOS App - Login screen disappears and all pasted values 
need to be entered again.

6. Actual behavior:
The App goes in background mode upon switching to Notes.
Login screen disappears and all pasted values 
need to be entered again.

7. Expected Behavior:
The user should be able to switch between the App and Notes
to copy paste values.

**Comment by wmathurin** [comment]
We created a bug in our internal bug tracking system.

**Comment by wmathurin** [comment]
I've tried both Mobile SDK 12.2 (latest currently released) and Mobile SDK in dev (the upcoming release) and was unable to reproduce the issue. 
NB: I tried advanced auth and "regular" auth (which uses WKWebView).
