### ISSUE TITLE
iOS, Apple AppStore - Salesforce AppExchange - Connected App for end users

### ISSUE THREAD

**Issue by geospatialqueryapi** [forcedotcom/SalesforceMobileSDK-iOS#3467]
I want my iOS App to be downloaded from Apple AppStore and
to work with an App be distribute on the Salesforce AppExChange marketplace.
The Apps are not for internal use but for external users wanting to subscribe.

1. The user installs the App from Salesforce AppExchange. 
2. Then the user installs the app from Apple Appstore.
3. The user starts the iOS App. A login screen is presented.
The user logs in.

There is a question about the Connected App. Will our connected App
have always the same values for remoteAccessConsumerKey and oauthRedirectURI?
It will be included in the App Package which will be installed from AppExChange marketplace.

in bootconfig.plist
there are two keys: remoteAccessConsumerKey
and oauthRedirectURI
Can I hard code these values? Or the user has to supply them somehow?

**Comment by wmathurin** [comment]
Each app should use a different connected app (so don't use the one that is embedded in the template/generated app). That way, org admin can revoke a token of a user for a specific app. 

Connected app that you create are "global", meaning they are available on all orgs. So admin don't create the connected app, the app developers do and embed the remoteAccessConsumerKey and oauthRedirectURI in their app (in the bootconfig file). 

Org admins can also control access to a connected app (see https://help.salesforce.com/s/articleView?id=sf.connected_app_manage.htm&type=5) e.g. to prevent a certain app from running against their org.

**Comment by geospatialqueryapi** [comment]
As I understand right now I'm using ScratchOrg created the ConnectedApp
in it. Calling sfdx force:source:pull -u 
I see consumerKey and callbackUrl downloaded in the source.
From what I understand when I convert my App for distribution
these values will stay the same and I can upload the SF App to AppExchange
and the iOS App on AppStore without change.

**Comment by wmathurin** [comment]
This thread should address your questions: https://salesforce.stackexchange.com/questions/197992/when-and-where-should-a-connected-app-be-created-during-dx-managed-package-devel

**Comment by geospatialqueryapi** [comment]
Looks like with Scratch Org there will be complications.
I suppose it is better to use a Sandbox.

**Comment by geospatialqueryapi** [comment]
How long till login is requested again?

**Comment by wmathurin** [comment]
Here are relevant parts of our documentation:

- [refresh token flow](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/oauth_refresh_token_flow.htm)
- also checkout the part of [refresh token policy](https://help.salesforce.com/s/articleView?id=sf.connected_app_manage_oauth.htm&type=5)

**Comment by geospatialqueryapi** [comment]
I mean the login screen. How often the user has to use the login screen?
Because right now there are three pieces of information the user has 
to enter:
1. custom domain
2. username
3. password

The user has to switch between say Notes and the iOS App, copy/paste these 
values tree times. But because switching back and forth between apps makes the
SF SDK based App to go in background, when switching back to it the screen refreshes
and loses the previous copy/paste. 

In practice I can test by copy pasting one value like custom domain and manually entering
username and password. If the user has to enter all this info often it makes the iOS App
very inconvenient to use. Howlong before login screen appears again?

One good solution will be to use the Face ID. Any information about how to implement it will be vary valuable.

**Comment by wmathurin** [comment]
They only need to login once unless the refresh token has an expiration. If the connected app can be configured to require a passcode/biometric unlock to access the app every time it is launched (once you have gone through that initial login flow). More [here](https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/ios_native_login_passcodes.htm)

**Comment by geospatialqueryapi** [comment]
For enabling Face ID:
https://help.salesforce.com/s/articleView?id=sf.branded_apps_biometric_id_ios_android.htm&type=5
By default, users must reenter biometric ID credentials when the app is in the background for more than 15 minutes. You can set your own time value requirement by adding a custom attribute.

This will be unnecessary I believe.

My ConnectedApp is configured as: Refresh token is valid until revoked.
So the Login screen will never appear again.

What about the case the user wants to Log Off? What iOS SDK function I've to use?

**Comment by wmathurin** [comment]
To logout current user do
In Objective-C
```objective-c
[[SFUserAccountManager  sharedInstance] logout];
```
In Swift
```swift
UserAccountManager.shared.logout()
```

**Comment by wmathurin** [comment]
This Bulk API 2.0 is enabled by default for Performance, Unlimited, Enterprise, and Developer Editions. More [here](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_intro.htm).

**Comment by geospatialqueryapi** [comment]
It is great it is enabled by default! Thank you!
