### ISSUE TITLE
Crash when adding the URL of an organization with advanced authentication settings in IOS to Add Destination

### ISSUE THREAD

**Issue by ryukou** [forcedotcom/SalesforceMobileSDK-iOS#3483]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.2.1
2. Issue found in Native App or Hybrid App:Native App
3. OS Version:15
4. Device:Iphone13
5. Steps to reproduce:
　Add a connection destination with advanced authentication turned on on the login screen
6. Actual behavior:
　Crash
　After restarting, the connection destination is added
7. Expected Behavior:
　Connection destination is added without crashing

**Comment by zaitsman** [comment]
Yeah IIRC that is patched in a later version.
Also make sure your users enter the `*.my.salesforce.com` URL not `*.lightning.force.com`, the latter causes the app to go into perpetual attempt to get well known url.

**Comment by gkotula** [comment]
Hi @ryukou Can you confirm whether you are still observing this issue after updating to the latest Mobile SDK version?  Thanks!

**Comment by gkotula** [comment]
Closing due to lack of response.
