### ISSUE TITLE
If you use Google with SSO at a connection destination with advanced authentication turned on, an authentication error will occur.

### ISSUE THREAD

**Issue by ryukou** [forcedotcom/SalesforceMobileSDK-iOS#3484]
Please fill out the following details:
1. Version of Mobile SDK Used: 9.2.1
2. Issue found in Native App or Hybrid App:Native App
3. OS Version:15
4. Device:Iphone13
5. Steps to reproduce:
　If you use Google with SSO at a connection destination with advanced authentication turned on, an authentication error will occur.
6. Actual behavior:
　I can't log in
7. Expected Behavior:
　Log in
8. Error Log:
can't connect to the server invalid client credentials

I have a problem with Require Secret for Web Server Flow, but can't I log in?
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2768

**Comment by bhariharan** [comment]
You need to uncheck `Require Secret for Web Server Flow` for advanced authentication to work on mobile. Please read the section on `Advanced Authentication` in our developer guide for more details.
