### ISSUE TITLE
SFSDKCryptoUtils randomly throws error

### ISSUE THREAD

**Issue by muhaos** [forcedotcom/SalesforceMobileSDK-iOS#3490]
Details:
1. Version of Mobile SDK Used: 9.1.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 14,15
4. Device: all
5. Steps to reproduce: random
6. Actual behaviour: SFSDKCryptoUtils randomly throws error.
7. Expected Behavior: No errors should be thrown.
8. Error Log: See below

From time to time we had sporadic error that threw from the SFSDK:
`SFSDKCryptoUtils Error decrypting data with EC key. Error code: The operation could not be completed. (CryptoTokenKit error -2.)`
or 
`SFSDKCryptoUtils Error decrypting data with EC key. Error code: The operation could not be completed. (CryptoTokenKit error -7.)`
Which eventually would fail all SF Api requests with "INVALID_AUTH_HEADER" error while keeping user logged in.

This could happen during usage of the App, and we could not see particular patterns which precedes the error. Restarting the App won't help.
Also, we already have  set KeychainHelper.setAccessibleAttribute(.afterFirstUnlock) in the app delegate during app startup.

**Comment by gkotula** [comment]
Hi muhaos,

This issue is tricky to reproduce, but it may be fixed in later versions of the SDK.  Could you try updating the SDK to the latest version and seeing if that fixes this issue?  Thanks!

**Comment by wmathurin** [comment]
A number of fixes have gone in the our crypto code. Please upgrade the SDK and let us know if the issue happens again.
