### ISSUE TITLE
Blue screen flash for some milli seconds, while logging into iPad

### ISSUE THREAD

**Issue by sluzhynskyi** [forcedotcom/SalesforceMobileSDK-iOS#3491]
<img width="1239" alt="Screen Shot 2022-03-04 at 9 55 04 AM" src="https://user-images.githubusercontent.com/44615981/158779435-f5f5a0a6-dfd2-49a3-9990-7274f4463712.png">

Reproduced even on sample projects such as RestAPIExplorer

1. Version of Mobile SDK Used: **v10.0.0**
2. Issue found in Native App or Hybrid App: **Native**
3. OS Version: **15.2**
4. Device: **iPad Air 4th generation**
5. Steps to reproduce:
- Input your credentials to login screen
- On "Access Permission" screen press **Deny**.
 - Try again to log in.
 - Notice that Blue screen flash for some milli seconds, while logging.
6. Actual behavior: Blue screen flashes
7. Expected Behavior: Blue screen doesn't flash
8. Error Log: -

**Comment by AsceticMonk** [comment]
Thanks for reporting @sluzhynskyi! We will take a look of this.

**Comment by gkotula** [comment]
@NANDANKARUMANCHI We have this issue tracked in our internal bug tracking system, but we cannot commit to a timeframe to fix this issue.
