### ISSUE TITLE
Localisation for login page

### ISSUE THREAD

**Issue by JonyMateos** [forcedotcom/SalesforceMobileSDK-iOS#3499]
Version of Mobile SDK Used: SalesforceSDKCore 7.3 (integrated through CocoaPods)

Hi,

We are using the Salesforce SDK. Login and registration process are working fine. 
At the moment, we can see the main login page in English but not in other languages like Spanish. Registration page and other pages are also appearing in English only. That happens even if the iPhone is in Spanish.

I'm using a url with the following format:
`userManager.loginHost = "devsfid-name.suffix.force.com/something"`
(userManager is the SFUserAccountManager)

**Is there any way to send a custom parameter or add a suffix to the url? 
or should the webview adapt automatically to phone's language?**
When the login webview starts loading, I can see that the SDK adds a path at the end, like `/path/s/login`. We would like to add a custom parameter at the end `?language=es`

If we test the full url in a web browser, the login page is visible in Spanish.
The full url is something like: `https://devsfid-name.suffix.force.com/something/path/s/login/language=es`

I hope there is any way to localise the login page in Mobile. Any help would be much appreciated.

Thanks,

Jon

**Comment by brandonpage** [comment]
Hi @JonyMateos, I just [responded to you on Trailhead](https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000Gh4dBSAR).

**Comment by JonyMateos** [comment]
If possible, I would like to have a response from the iOS team, as this is quite specific
