### ISSUE TITLE
The error while attempting to login

### ISSUE THREAD

**Issue by mkkroliks** [forcedotcom/SalesforceMobileSDK-iOS#3501]
Please fill out the following details:

Version of Mobile SDK Used: 10.0.0
Issue found in Native App or Hybrid App: Native
OS Version: 14.2 or any other.
Device: iPhone 12 or any other.
Steps to reproduce: **Video attached below** -> Turn off wifi and try to sign in, turn on wifi and try to sign in. In order to be able to sign in again, the user has to delete an app and install it again.
Actual behavior: SalesforceLoginViewController displays a web view with an error description
Expected Behavior: SalesforceLoginViewController displays a sign in fields.

**Error Log:**
![161498763-29459e32-0264-4e13-9bdc-22afb98120c1](https://user-images.githubusercontent.com/2151961/166206338-54fb3f65-e57b-40e4-9530-a6ef3bd4bf7b.png)

**Note to a video:** In the 32nd second I turned off the internet connection and turned it on again in the 47th second.
https://user-images.githubusercontent.com/2151961/166212791-a5e5543e-34a3-4e59-ab8b-72812af30bbe.mp4

I looked through network traffic and for correctly working login process, SDK is making request using the app domain specified under `SFDCOAuthLoginHost` .
![162162970-8b8a97de-a040-4016-8d70-6e9abc59020a](https://user-images.githubusercontent.com/2151961/166208831-857b3d45-4628-437a-9e97-e0d0de53e825.png)

For a failing flow it's making request using salesforce domain.
![162163020-fa8d420c-7672-42d1-96da-f524d3161311](https://user-images.githubusercontent.com/2151961/166208877-0a62bcd3-c004-4cf8-86fa-1a731305f85d.png)

**AppStore link to an app**: https://apps.apple.com/us/app/aafp/id646918504

**Comment by brandonpage** [comment]
Thanks for reporting this @mkkroliks.  

I have filed an internal bug (W-11093531) to track this issue.  We will update you here with any developments.

**Comment by mkkroliks** [comment]
Hey @brandonpage! Thank you for your interest. What is a status of an issue? When can we expect a fix? This is really important one, since it blocks the use of our app.

**Comment by bbirman** [comment]
Hi @mkkroliks, we're looking into potential solutions now. Is the app disabling the settings icon on the login screen using SFSDKLoginViewControllerConfig (objc)/SalesforceLoginViewControllerConfig (swift)? More info on the config [here](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/oauth_hide_gear_icon.htm)

**Comment by mkkroliks** [comment]
@bbirman Yes, `showsSettingsIcon` is set to `false`

**Comment by bbirman** [comment]
thanks for confirming! this should be fixed with #3514 and will be included in our 10.1 release
