### ISSUE TITLE
SFDefaultUserManagementListViewController behaviour

### ISSUE THREAD

**Issue by llyrProximity** [forcedotcom/SalesforceMobileSDK-iOS#3505]
Please fill out the following details:

1. Version of Mobile SDK Used: 10
2. Issue found in Native App or Hybrid App: Native App 
3. OS Version: 15.4
4. Device: iPad

Have three users logged in, logout one user. SDK code displays SFDefaultUserManagementListViewController as there are two others available to log in. Can we override this controller as we'd like use our own. If not is there away to a block/notification on New User and cancel buttons?

**Comment by bbirman** [comment]
If you want to use you own user list view controller, you can move off of `AuthHelper.registerBlock(forCurrentUserChangeNotifications:…` (mentioned in step 5 of [this doc](https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/ios_new_native_no_template.htm)) and listen to the notifications yourself. Then you could follow the existing pattern [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/dev/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Util/SFSDKAuthHelper.m#L85-L108) and subclass SFDefaultUserManagementViewController to use a custom list view controller
