### ISSUE TITLE
Tel: URL in Login View shows Unsupported URL dialog

### ISSUE THREAD

**Issue by reubenbijl** [forcedotcom/SalesforceMobileSDK-iOS#3508]
Please fill out the following details:

1. Version of Mobile SDK Used: 
  - 8.1.0
2. Issue found in Native App or Hybrid App:
 - Native app
3. OS Version:
 - All
4. Device:
 - All
5. Steps to reproduce:
 - Include a telephone number in the login webview
 - Tap the telephone number in the login
 - Error, cannot load page
6. Actual behavior:
 - Error message, cannot load page
7. Expected Behavior:
  - Call number
8. Error Log:
[SalesforceSDKCore] CLASS: SFOAuthCoordinator webView:didStartProvisionalNavigation: host=(null) : path=(null)
[ProcessSwapping] 0x1100f14a0 - [pageProxyID=31, webPageID=40, PID=14295, navigationID=5] ProvisionalPageProxy::didFailProvisionalLoadForFrame: frameID=3
[Process] 0x128815e18 - [pageProxyID=31, webPageID=32, PID=14292] WebPageProxy::didFailProvisionalLoadForFrame: frameID=3, domain=NSURLErrorDomain, code=-1002, isMainFrame=1
[SalesforceSDKCore] CLASS: SFOAuthCoordinator SFOAuthCoordinator:didFailLoadWithError: error code: -1002, description: unsupported URL, URL: ***
[SalesforceSDKCore] CLASS: SFSDKAuthHelper Authentication failed: unsupported URL.

**Comment by wmathurin** [comment]
Our navigation delegate does not handle tel: URL. See https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/dev/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/OAuth/SFOAuthCoordinator.m#L715

Marked as "enhancement".

**Comment by valentin-salamatov** [comment]
Hi there! I've got the same issue when navigating to the Privacy page (https://www.salesforce.com/us/company/privacy) and clicking telephone hyperlinks in different places.

I’m wondering if there is a way to get around this problem and open the Privacy page in some browser application instead of WKWebView?

<img width="384" alt="Screenshot 2023-01-11 at 12 41 55" src="https://user-images.githubusercontent.com/122388932/211788602-8f7f6711-ad8a-490a-99c2-3f9d4be3c736.png">

**Comment by wmathurin** [comment]
If/when we get to that [enhancement](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3508#issuecomment-1199638417), all tel links should start working.

**Comment by bbirman** [comment]
We added a property on SFUserAccountManager in https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3674 so that apps can add their own URL handling
