### ISSUE TITLE
dictionaryItemFromKeychain: Error attempting to look up keychain item: errSecInteractionNotAllowed

### ISSUE THREAD

**Issue by vanguardflag** [forcedotcom/SalesforceMobileSDK-iOS#3510]
Please fill out the following details:

1. Version of Mobile SDK Used: 
    pod 'MarketingCloudSDK', '~> 8.0.4'
2. Issue found in Native App or Hybrid App:
  Native App
3. OS Version:
  iOS 15.1.0
4. Device:
 All Device
5. Steps to reproduce:
We are seeing an extremely large spike in iOS crashes that are apparently caused by the SF Mobile SDK trying to read sensitive information from the keychain. Our iOS dev team has investigated and their initial conclusion is because of the current permission level the phone won’t allow it and as result the app will crash.

It is unknown exactly what the customer experience is, other than fatal crash. We are not sure if the crash is “only” happening in the background app state, or if this is foreground. Regardless, we would like to solve the issue quickly as possible.

11. Actual behavior:
12. Expected Behavior:
13. Error Log:
<img width="1276" alt="Screenshot 2022-05-23 at 17 14 17" src="https://user-images.githubusercontent.com/10689405/169862635-8a4437a5-e0a1-4508-b47b-102fd3b67b9b.png">

i see this bug alot most offer to use this
SFKeychainItemWrapper.setAccessibleAttribute(kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly)  
but i didnt find this one in sdk.
what can i do?

**Comment by bhariharan** [comment]
This isn't the right forum for `MarketingCloudSDK` issues. That is a different product.

**Comment by billmote** [comment]
> Please fill out the following details:
> 
> 1. Version of Mobile SDK Used:
>    pod 'MarketingCloudSDK', '~> 8.0.4'
> 2. Issue found in Native App or Hybrid App:
>    Native App
> 3. OS Version:
>    iOS 15.1.0
> 4. Device:
>    All Device
> 5. Steps to reproduce:
>    We are seeing an extremely large spike in iOS crashes that are apparently caused by the SF Mobile SDK trying to read sensitive information from the keychain. Our iOS dev team has investigated and their initial conclusion is because of the current permission level the phone won’t allow it and as result the app will crash.
> 
> It is unknown exactly what the customer experience is, other than fatal crash. We are not sure if the crash is “only” happening in the background app state, or if this is foreground. Regardless, we would like to solve the issue quickly as possible.
> 
> 11. Actual behavior:
> 12. Expected Behavior:
> 13. Error Log:
> 
> <img alt="Screenshot 2022-05-23 at 17 14 17" width="1276" src="https://user-images.githubusercontent.com/10689405/169862635-8a4437a5-e0a1-4508-b47b-102fd3b67b9b.png">
> 
> i see this bug alot most offer to use this SFKeychainItemWrapper.setAccessibleAttribute(kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly) but i didnt find this one in sdk. what can i do?

Please open a support case for the iOS Marketing Cloud MobilePush SDK.
