### ISSUE TITLE
Error while exporting .ipa

### ISSUE THREAD

**Issue by mkkroliks** [forcedotcom/SalesforceMobileSDK-iOS#3527]
Please fill out the following details:

1. Version of Mobile SDK Used: 10.1.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: Not Applicable
4. Device:Not Applicable
5. Steps to reproduce: While exporting .ipa: 

`set -o pipefail && xcodebuild "-exportArchive" "-archivePath" "/var/folders/jw/g2nxpyn956dffdjs0vn8h9nm0000gn/T/xcodeArchive1464055189/XYZ.xcarchive" "-exportPath" "/var/folders/jw/g2nxpyn956dffdjs0vn8h9nm0000gn/T/xcodeIPAExport4013409041/exported" "-exportOptionsPlist" "/var/folders/jw/g2nxpyn956dffdjs0vn8h9nm0000gn/T/xcodeIPAExport4013409041/export_options.plist" | xcpretty`

I'm getting the following error:

`error: exportArchive: ipatool failed with an exception: #<CmdSpec::NonZeroExitException: $ /Applications/Xcode-13.2.1.app/Contents/Developer/usr/bin/python3 /Applications/Xcode-13.2.1.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Applications/Xcode-13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin --sdk /Applications/Xcode-13.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -o /var/folders/jw/g2nxpyn956dffdjs0vn8h9nm0000gn/T/ipatool20220701-3844-pw9w4i/thinned-out/arm64/Payload/XYZ.app/Frameworks/SalesforceSDKCommon.framework/SalesforceSDKCommon --generate-dsym /var/folders/jw/g2nxpyn956dffdjs0vn8h9nm0000gn/T/ipatool20220701-3844-pw9w4i/thinned-out/arm64/Payload/XYZ.app/Frameworks/SalesforceSDKCommon.framework/SalesforceSDKCommon.dSYM --strip-swift-symbols /var/folders/jw/g2nxpyn956dffdjs0vn8h9nm0000gn/T/ipatool20220701-3844-pw9w4i/thinned-in/arm64/Payload/XYZ.app/Frameworks/SalesforceSDKCommon.framework/SalesforceSDKCommon`

I didn't have any issues with previous version: 10.0.0.

**Comment by bbirman** [comment]
Hi @mkkroliks apologies for the delayed response, is this issue still happening?

**Comment by wmathurin** [comment]
Closing for lack of responses.
