### ISSUE TITLE
App crashes on launch when the user is logged in

### ISSUE THREAD

**Issue by pushp1010** [forcedotcom/SalesforceMobileSDK-iOS#3536]
Please fill out the following details:

1. Version of Mobile SDK Used:  9.0.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 15.6.1
4. Device: iPhone 13 Pro
5. Steps to reproduce: When you launch the application and user is already logged in and application got crashed with below crash logs
6. Actual behavior: It  is crashing on launching the application 
7. Expected Behavior: App should not crash with this behaviour
8. Error Log:  attaching logs

line causing crash is below
`Super.rootviewcontroller = nil
`
Function responsible for crash:

```
- (void)disableWindow {
    BOOL isActive = self.windowScene.activationState == UISceneActivationStateForegroundActive;
    if ([self isSnapshotWindow] || isActive) {
        if (self.windowLevel > 0)
            self.windowLevel = self.windowLevel * -1;
        self.alpha = 0.0;
        super.rootViewController = nil;
        [self stashRootViewController];
    }
}
```

Incident Identifier: 6FAFF906-4833-48CC-947E-E4B100970837
Hardware Model:      iPhone14,3
Process:             XXXXXXXX [22667]
Path:                /private/var/containers/Bundle/Application/6277B953-D7FB-4003-BCDC-58D2F027DE2E/XXXXXXXXX.app/XXXXXXXXXXX
Identifier:          XXXXXXXXXXX
Version:             1.0 (24)
AppStoreTools:       13F100
AppVariant:          1:iPhone14,3:15
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                Non UI
Parent Process:      launchd [1]
Coalition:           com. XXXXXXXXXXX. XXXXXXXXXXX [1154]

Date/Time:           2022-08-29 21:43:31.5179 +0300
Launch Time:         2022-08-29 14:48:12.1123 +0300
OS Version:          iPhone OS 15.6.1 (19G82)
Release Type:        User
Baseband Version:    1.70.01
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: OBJC 1 

Triggered by Thread:  0

Kernel Triage:
VM - Compressor failed a blocking pager_get
VM - Compressor failed a blocking pager_get
VM - Compressor failed a blocking pager_get
VM - Compressor failed a blocking pager_get
VM - Compressor failed a blocking pager_get

Thread 0 name:
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001f0ad4464 __terminate_with_payload + 8
1   libsystem_kernel.dylib        	0x00000001f0ad5c44 abort_with_payload_wrapper_internal + 136 (terminate_with_reason.c:106)
2   libsystem_kernel.dylib        	0x00000001f0ad5bbc abort_with_reason + 32 (terminate_with_reason.c:116)
3   libobjc.A.dylib               	0x00000001d1bf80b4 _objc_fatalv(unsigned long long, unsigned long long, char const*, char*) + 116 (objc-errors.mm:202)
4   libobjc.A.dylib               	0x00000001d1bf8040 _objc_fatal(char const*, ...) + 32 (objc-errors.mm:218)
5   libobjc.A.dylib               	0x00000001d1bd0acc weak_register_no_lock + 392 (objc-weak.mm:422)
6   libobjc.A.dylib               	0x00000001d1bd5924 objc_storeWeak + 448 (NSObject.mm:363)
7   UIKitCore                     	0x00000001bb2eda94 -[_UIRootPresentationController initWithPresentedViewController:presentingWindow:] + 108 (_UIRootPresentationController.m:24)
8   UIKitCore                     	0x00000001bb566c78 -[UIWindow setRootViewController:] + 484 (UIWindow.m:2399)
9   SalesforceSDKCore             	0x00000001057bf550 0x10578c000 + 210256
10  UIKitCore                     	0x00000001bc3885e8 __138-[UIWindowScene _evaluateSceneKeyWindowForWindowMadeKey:consideringVisibility:findingNewKeyWindowIfNeeded:ignoringOldKeyWindow:forReason:]_block_invoke.535 + 132 (UIWindowScene.m:1209)
11  UIKitCore                     	0x00000001bb46a96c -[_UIKeyWindowEvaluator _evaluateApplicationKeyWindowWithComparisonWindowScene:changingKeyWindowSceneActions:sceneKeyWindowActions:ignoringOldKeyWindow:sceneResignKeyWindowActions:andSceneBecomeKey... + 996 (_UIKeyWindowEvaluator.m:559)
12  UIKitCore                     	0x00000001bb4db7bc -[_UIKeyWindowEvaluator evaluateApplicationKeyWindowForWindowScene:withWindowMadeKey:sceneKeyWindowActions:ignoringOldKeyWindow:sceneResignKeyWindowActions:andSceneBecomeKeyWindowActions:forReason:] + 288 (_UIKeyWindowEvaluator.m:652)
13  UIKitCore                     	0x00000001bb47b5fc -[UIWindowScene _evaluateSceneKeyWindowForWindowMadeKey:consideringVisibility:findingNewKeyWindowIfNeeded:ignoringOldKeyWindow:forReason:] + 1868 (UIWindowScene.m:1182)
14  UIKitCore                     	0x00000001bb4f03bc -[UIWindowScene _windowUpdatedVisibility:] + 576 (UIWindowScene.m:1080)
15  UIKitCore                     	0x00000001bb4af878 -[UIWindow _updateLayerOrderingAndSetLayerHidden:actionBlock:] + 204 (UIWindow.m:0)
16  UIKitCore                     	0x00000001bb4f69c8 -[UIWindow dealloc] + 480 (UIWindow.m:1411)
17  libsystem_blocks.dylib        	0x000000022a795804 _Block_release + 192 (runtime.cpp:176)
18  UIKitCore                     	0x00000001bb5be95c -[_UIAfterCACommitBlock run] + 84 (_UIAfterCACommitQueue.m:154)
19  UIKitCore                     	0x00000001bb4d1b4c -[_UIAfterCACommitQueue flush] + 192 (_UIAfterCACommitQueue.m:228)
20  UIKitCore                     	0x00000001bb3fb23c _runAfterCACommitDeferredBlocks + 644 (UIApplication.m:3038)
21  UIKitCore                     	0x00000001bb3fb960 _cleanUpAfterCAFlushAndRunDeferredBlocks + 132 (UIApplication.m:3002)
22  UIKitCore                     	0x00000001bb7d46ec _UIApplicationFlushCATransaction + 84 (UIApplication.m:3079)
23  UIKitCore                     	0x00000001bba6ed5c _UIUpdateSequenceRun + 84 (_UIUpdateSequence.mm:112)
24  UIKitCore                     	0x00000001bc0f5edc schedulerStepScheduledMainSection + 144 (_UIUpdateScheduler.m:778)
25  UIKitCore                     	0x00000001bc0f56a4 runloopSourceCallback + 92 (_UIUpdateScheduler.m:870)
26  CoreFoundation                	0x00000001b8ed3414 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28 (CFRunLoop.c:1972)
27  CoreFoundation                	0x00000001b8ee41a0 __CFRunLoopDoSource0 + 208 (CFRunLoop.c:2016)
28  CoreFoundation                	0x00000001b8e1d6f8 __CFRunLoopDoSources0 + 368 (CFRunLoop.c:2061)
29  CoreFoundation                	0x00000001b8e2305c __CFRunLoopRun + 828 (CFRunLoop.c:2951)
30  CoreFoundation                	0x00000001b8e36bc8 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
31  GraphicsServices              	0x00000001d4fa2374 GSEventRunModal + 164 (GSEvent.c:2200)
32  UIKitCore                     	0x00000001bb7aab58 -[UIApplication _run] + 1100 (UIApplication.m:3511)
33  UIKitCore                     	0x00000001bb52c090 UIApplicationMain + 364 (UIApplication.m:5064)
34  XXXXXXXX              	0x00000001009bef5c 0x100658000 + 3567452
35  dyld                          	0x0000000101a55da4 start + 520 (dyldMain.cpp:879)

Thread 1 name:
Thread 1:
0   libsystem_kernel.dylib        	0x00000001f0aa74a0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001f0aa7ae4 mach_msg + 76 (mach_msg.c:119)
2   CoreFoundation                	0x00000001b8e1ed30 __CFRunLoopServiceMachPort + 372 (CFRunLoop.c:2646)
3   CoreFoundation                	0x00000001b8e231bc __CFRunLoopRun + 1180 (CFRunLoop.c:3000)
4   CoreFoundation                	0x00000001b8e36bc8 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
5   Foundation                    	0x00000001ba629444 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236 (NSRunLoop.m:373)
6   Foundation                    	0x00000001ba66ae0c -[NSRunLoop(NSRunLoop) runUntilDate:] + 92 (NSRunLoop.m:420)
7   UIKitCore                     	0x00000001bb724cc4 -[UIEventFetcher threadMain] + 524 (UIEventFetcher.m:1167)
8   Foundation                    	0x00000001ba67941c __NSThread__start__ + 808 (NSThread.m:972)
9   libsystem_pthread.dylib       	0x000000022a8199ac _pthread_start + 148 (pthread.c:891)
10  libsystem_pthread.dylib       	0x000000022a818e68 thread_start + 8

Thread 2 name:
Thread 2:
0   libsystem_kernel.dylib        	0x00000001f0aa74a0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001f0aa7ae4 mach_msg + 76 (mach_msg.c:119)
2   FirebaseCrashlytics           	0x0000000104436484 0x10441c000 + 107652
3   libsystem_pthread.dylib       	0x000000022a8199ac _pthread_start + 148 (pthread.c:891)
4   libsystem_pthread.dylib       	0x000000022a818e68 thread_start + 8

Thread 3 name:
Thread 3:
0   libsystem_kernel.dylib        	0x00000001f0aa74a0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001f0aa7ae4 mach_msg + 76 (mach_msg.c:119)
2   CoreFoundation                	0x00000001b8e1ed30 __CFRunLoopServiceMachPort + 372 (CFRunLoop.c:2646)
3   CoreFoundation                	0x00000001b8e231bc __CFRunLoopRun + 1180 (CFRunLoop.c:3000)
4   CoreFoundation                	0x00000001b8e36bc8 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
5   CFNetwork                     	0x00000001b98b31dc +[__CFN_CoreSchedulingSetRunnable _run:] + 472 (CoreSchedulingSet.mm:1372)
6   Foundation                    	0x00000001ba67941c __NSThread__start__ + 808 (NSThread.m:972)
7   libsystem_pthread.dylib       	0x000000022a8199ac _pthread_start + 148 (pthread.c:891)
8   libsystem_pthread.dylib       	0x000000022a818e68 thread_start + 8

Thread 4 name:
Thread 4:
0   libsystem_kernel.dylib        	0x00000001f0aa74a0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001f0aa7ae4 mach_msg + 76 (mach_msg.c:119)
2   CoreFoundation                	0x00000001b8e1ed30 __CFRunLoopServiceMachPort + 372 (CFRunLoop.c:2646)
3   CoreFoundation                	0x00000001b8e231bc __CFRunLoopRun + 1180 (CFRunLoop.c:3000)
4   CoreFoundation                	0x00000001b8e36bc8 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
5   WebCore                       	0x00000001c9228d9c RunWebThread(void*) + 760 (WebCoreThread.mm:679)
6   libsystem_pthread.dylib       	0x000000022a8199ac _pthread_start + 148 (pthread.c:891)
7   libsystem_pthread.dylib       	0x000000022a818e68 thread_start + 8

Thread 5 name:
Thread 5:
0   libsystem_kernel.dylib        	0x00000001f0aa74a0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001f0aa7ae4 mach_msg + 76 (mach_msg.c:119)
2   CoreFoundation                	0x00000001b8e1ed30 __CFRunLoopServiceMachPort + 372 (CFRunLoop.c:2646)
3   CoreFoundation                	0x00000001b8e231bc __CFRunLoopRun + 1180 (CFRunLoop.c:3000)
4   CoreFoundation                	0x00000001b8e36bc8 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
5   AudioSession                  	0x00000001c244bf04 CADeprecated::GenericRunLoopThread::Entry(void*) + 164 (GenericRunLoopThread.h:95)
6   AudioSession                  	0x00000001c24558f0 CADeprecated::CAPThread::Entry(CADeprecated::CAPThread*) + 92 (CAPThread.cpp:324)
7   libsystem_pthread.dylib       	0x000000022a8199ac _pthread_start + 148 (pthread.c:891)
8   libsystem_pthread.dylib       	0x000000022a818e68 thread_start + 8

Thread 6:
0   libsystem_pthread.dylib       	0x000000022a818e54 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	0x000000022a818e54 start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	0x000000022a818e54 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	0x000000022a818e54 start_wqthread + 0

Thread 10 name:
Thread 10:
0   libsystem_kernel.dylib        	0x00000001f0aa7f24 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x000000022a820298 _pthread_cond_wait + 1236 (pthread_cond.c:636)
2   JavaScriptCore                	0x00000001c4166148 scavenger_thread_main + 1232 (pas_scavenger.c:135)
3   libsystem_pthread.dylib       	0x000000022a8199ac _pthread_start + 148 (pthread.c:891)
4   libsystem_pthread.dylib       	0x000000022a818e68 thread_start + 8

Thread 11:
0   libsystem_pthread.dylib       	0x000000022a818e54 start_wqthread + 0

Thread 12:
0   libsystem_pthread.dylib       	0x000000022a818e54 start_wqthread + 0

Thread 13:
0   libsystem_pthread.dylib       	0x000000022a818e54 start_wqthread + 0

Thread 14:
0   libsystem_pthread.dylib       	0x000000022a818e54 start_wqthread + 0

Thread 15:
0   libsystem_pthread.dylib       	0x000000022a818e54 start_wqthread + 0

Thread 16 name:
Thread 16:
0   libsystem_kernel.dylib        	0x00000001f0aa8138 __ulock_wait + 8
1   libsystem_platform.dylib      	0x000000022a8109ac _os_unfair_lock_lock_slow + 172 (lock.c:578)
2   libobjc.A.dylib               	0x00000001d1bcd79c objc_object::sidetable_clearDeallocating() + 96 (lock_private.h:716)
3   libobjc.A.dylib               	0x00000001d1bd0200 objc_destructInstance + 156 (objc-object.h:552)
4   libobjc.A.dylib               	0x00000001d1bd9a00 _objc_rootDealloc + 80 (objc-runtime-new.mm:8250)
5   libxpc.dylib                  	0x000000022a858ba0 -[OS_xpc_object dealloc] + 56 (object.m:27)
6   libxpc.dylib                  	0x000000022a848214 _xpc_dictionary_node_free + 84 (dictionary.c:79)
7   libxpc.dylib                  	0x000000022a845878 _xpc_dictionary_dispose + 48 (dictionary.c:1269)
8   libxpc.dylib                  	0x000000022a858b84 -[OS_xpc_object dealloc] + 28 (object.m:26)
9   libxpc.dylib                  	0x000000022a83a82c _xpc_array_dispose + 44 (array.c:351)
10  libxpc.dylib                  	0x000000022a858b84 -[OS_xpc_object dealloc] + 28 (object.m:26)
11  libxpc.dylib                  	0x000000022a8458f4 _xpc_dictionary_dispose + 172 (dictionary.c:1287)
12  libxpc.dylib                  	0x000000022a858b84 -[OS_xpc_object dealloc] + 28 (object.m:26)
13  libxpc.dylib                  	0x000000022a842c70 _xpc_connection_mach_event + 1000 (connection.c:1424)
14  libdispatch.dylib             	0x00000001b8b18af0 _dispatch_client_callout4 + 20 (object.m:600)
15  libdispatch.dylib             	0x00000001b8b34b2c _dispatch_mach_msg_invoke + 464 (mach.c:2418)
16  libdispatch.dylib             	0x00000001b8b20000 _dispatch_lane_serial_drain + 376 (inline_internal.h:0)
17  libdispatch.dylib             	0x00000001b8b3584c _dispatch_mach_invoke + 456 (mach.c:2740)
18  libdispatch.dylib             	0x00000001b8b20000 _dispatch_lane_serial_drain + 376 (inline_internal.h:0)
19  libdispatch.dylib             	0x00000001b8b20c80 _dispatch_lane_invoke + 392 (queue.c:3944)
20  libdispatch.dylib             	0x00000001b8b2b500 _dispatch_workloop_worker_thread + 648 (queue.c:6732)
21  libsystem_pthread.dylib       	0x000000022a8190bc _pthread_wqthread + 288 (pthread.c:2599)
22  libsystem_pthread.dylib       	0x000000022a818e5c start_wqthread + 8

Thread 17:
0   libsystem_pthread.dylib       	0x000000022a818e54 start_wqthread + 0

Thread 18 name:
Thread 18:
0   CoreFoundation                	0x00000001b8e39278 CFStringGetLength + 100 (CFInternal.h:865)
1   CoreFoundation                	0x00000001b8e45594 _CFURLCreateWithURLString + 1272 (CFURL.c:1923)
2   libnetwork.dylib              	0x00000001b9c1d784 nw_utilities_copy_sanitized_url + 128 (nw_utilities.c:244)
3   libnetwork.dylib              	0x00000001b9bf6c14 -[NWOSURLEndpoint initWithURL:] + 408 (url_endpoint.m:100)
4   libnetwork.dylib              	0x00000001b9ba326c nw_endpoint_copy + 80 (endpoint.m:788)
5   libnetwork.dylib              	0x00000001b9c32dc4 -[NWConcrete_nw_parameters initWithParameters:stripConnected:shallowCopy:] + 840 (parameters.m:1625)
6   libnetwork.dylib              	0x00000001ba19a1d0 nw_endpoint_resolver_create_child_parameters + 116 (parameters.m:2677)
7   libnetwork.dylib              	0x00000001b9bd378c nw_endpoint_resolver_update + 6372 (endpoint_resolver.m:925)
8   libnetwork.dylib              	0x00000001b9bde0a8 __52-[NWConcrete_nw_endpoint_resolver startWithHandler:]_block_invoke.3 + 96 (endpoint_resolver.m:209)
9   libnetwork.dylib              	0x00000001b9be62d8 __nw_resolver_update_client_block_invoke + 92 (resolver.m:987)
10  libdispatch.dylib             	0x00000001b8b16e6c _dispatch_call_block_and_release + 32 (init.c:1517)
11  libdispatch.dylib             	0x00000001b8b18a30 _dispatch_client_callout + 20 (object.m:560)
12  libdispatch.dylib             	0x00000001b8b220a4 _dispatch_workloop_invoke + 2076 (inline_internal.h:2622)
13  libdispatch.dylib             	0x00000001b8b2b500 _dispatch_workloop_worker_thread + 648 (queue.c:6732)
14  libsystem_pthread.dylib       	0x000000022a8190bc _pthread_wqthread + 288 (pthread.c:2599)
15  libsystem_pthread.dylib       	0x000000022a818e5c start_wqthread + 8

Thread 19:
0   libsystem_pthread.dylib       	0x000000022a818e54 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000001   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000105d89ff0   x6: 0x0000000000000280   x7: 0x0000000127d2cdf0
    x8: 0x0000000000000020   x9: 0x0000000212664010  x10: 0x0000000000001290  x11: 0x0000000000000000
   x12: 0x00000000bbc02005  x13: 0x000000003bc02000  x14: 0x000000003bc00000  x15: 0x0000000000000052
   x16: 0x0000000000000208  x17: 0x0000000215457048  x18: 0x0000000000000000  x19: 0x0000000000000080
   x20: 0x0000000105d89ff0  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x0000000000000001
   x24: 0x0000000000000008  x25: 0x00000002126673c0  x26: 0x0000000000000002  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016f7a3f30   lr: 0x00000001f0ad5c44
    sp: 0x000000016f7a3ef0   pc: 0x00000001f0ad4464     cpsr: 0x1000
   esr: 0x56000080  Address size fault

Binary Images:
0x100658000 - 0x1013cffff XXXXXXXXXXX arm64  <85b647604e053c5b90f1e1dd8eb66c8c> /private/var/containers/Bundle/Application/6277B953-D7FB-4003-BCDC-58D2F027DE2E/XXXXXXXXXXX.app/XXXXXXXXXXX
0x101a3c000 - 0x101a93fff dyld arm64e  <66e1fb2668f8379ba052eb8b8291b5e1> /usr/lib/dyld
0x10441c000 - 0x10445bfff FirebaseCrashlytics arm64  <d525448ed90a38088f5a83cd8d4c03af> /private/var/containers/Bundle/Application/6277B953-D7FB-4003-BCDC-58D2F027DE2E/XXXXXXXXXXX.app/Frameworks/FirebaseCrashlytics.framework/FirebaseCrashlytics
0x10578c000 - 0x10584ffff SalesforceSDKCore arm64  <5cf1e5b12c0b3790ba88bc6a49722a06> /private/var/containers/Bundle/Application/6277B953-D7FB-4003-BCDC-58D2F027DE2E/XXXXXXXXXXX.app/Frameworks/SalesforceSDKCore.framework/SalesforceSDKCore
0x1b8b15000 - 0x1b8b5afff libdispatch.dylib arm64e  <e3ea4f635d11342aaf199f58dbc8e259> /usr/lib/system/libdispatch.dylib
0x1b8e18000 - 0x1b926dfff CoreFoundation arm64e  <6b22dd8135853be6bc77ba19810ec0f2> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
0x1b963b000 - 0x1b9afcfff CFNetwork arm64e  <106410ffdd4f3527ad531980fe8b0ddd> /System/Library/Frameworks/CFNetwork.framework/CFNetwork
0x1b9afd000 - 0x1ba591fff libnetwork.dylib arm64e  <0dbe8d5848823c66b0310239c020ee4c> /usr/lib/libnetwork.dylib
0x1ba610000 - 0x1ba91afff Foundation arm64e  <ee1abaf23d7137fb906715aa79528619> /System/Library/Frameworks/Foundation.framework/Foundation
0x1bb296000 - 0x1bcb33fff UIKitCore arm64e  <137a95aada6d332cbc01e13bb9b6e317> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
0x1c2445000 - 0x1c246ffff AudioSession arm64e  <98e4676874ff374c9b70303bffce2d33> /System/Library/PrivateFrameworks/AudioSession.framework/AudioSession
0x1c407b000 - 0x1c54fffff JavaScriptCore arm64e  <e76b377fc862395a9439d12b09a59e07> /System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore
0x1c863f000 - 0x1caba8fff WebCore arm64e  <46356aa10f253215915edbc81e3b4699> /System/Library/PrivateFrameworks/WebCore.framework/WebCore
0x1d1bcb000 - 0x1d1c07fff libobjc.A.dylib arm64e  <f6368be9109b3405b282624040529afd> /usr/lib/libobjc.A.dylib
0x1d4fa1000 - 0x1d4fa9fff GraphicsServices arm64e  <a094e7b51d4037c5902756d86988ec4b> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
0x1f0aa6000 - 0x1f0adbfff libsystem_kernel.dylib arm64e  <1fb39303587b320eaeb8e51a54c8a4a9> /usr/lib/system/libsystem_kernel.dylib
0x22a794000 - 0x22a795fff libsystem_blocks.dylib arm64e  <8684215d9d4131dd9f25fdbc827ba1af> /usr/lib/system/libsystem_blocks.dylib
0x22a810000 - 0x22a816fff libsystem_platform.dylib arm64e  <e44b288b8df03923a311837535b6a7e9> /usr/lib/system/libsystem_platform.dylib
0x22a818000 - 0x22a823fff libsystem_pthread.dylib arm64e  <adc41700002e3a2bb4a1eb5fbf575770> /usr/lib/system/libsystem_pthread.dylib
0x22a833000 - 0x22a86ffff libxpc.dylib arm64e  <b183213379dc3e42b704ef71f75a577e> /usr/lib/system/libxpc.dylib

EOF

**Comment by bbirman** [comment]
Thanks for reporting! From the stack trace, it looks like the crash would be prevented with https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3521 which was included in Mobile SDK 10.1

**Comment by gkotula** [comment]
@pushp1010 Can you confirm whether upgrading to Mobile SDK 10.1 or later fixes the issue?  Thanks!

**Comment by pushp1010** [comment]
Yes It works fine now.
