### ISSUE TITLE
Question about Authentication Between Two Apps in same Org.

### ISSUE THREAD

**Issue by nzsrini** [forcedotcom/SalesforceMobileSDK-iOS#3540]
Please fill out the following details:

1. Version of Mobile SDK Used: 10.2.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: IOS
4. Device: 

is it possible to transfer the access token from one app to other app in the same org? 
Use case : APP-A, APP-B (connected apps) in same org.
Requirement: If the community user already logged into the APP-A, Is it possible to make the user log into APP-B with out the authentication (ie.. user not required to enter username and password)? using the the access token generated in APP-A ?

**Comment by brandonpage** [comment]
Hi @nzsrini,

Yes.  Please check out our [documentation for Identity Provider Apps](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/auth_identity_providers.htm).  If APP-A is an IDP and the user is logged in, you can either launch APP-B from APP-A or tap a button on the login screen of APP-B to authenticate without username and password.  

I will close this issue, but feel free to ask additional questions here in this thread or on [our Trailhead page](https://trailhead.salesforce.com/trailblazer-community/groups/0F94S000000kH0HSAU?tab=discussion&sort=LAST_MODIFIED_DATE_DESC).
