### ISSUE TITLE
Domain migration support

### ISSUE THREAD

**Issue by iowlit** [forcedotcom/SalesforceMobileSDK-iOS#3541]
The SF SDK does not handle any domain migration f.e. [enhanced domains](https://help.salesforce.com/s/articleView?id=release-notes.rn_security_domains_enable_enhanced_ru.htm&type=5&release=232). 
All requests fails with 301 or 307 status codes as on the screenshot attached:

![Screenshot 2022-09-21 at 19 01 53](https://user-images.githubusercontent.com/25912107/191558091-d657adf9-e5b6-4d99-98a9-345d2501cdf0.png)

Is it an item for a future release? 
Or maybe someone knows some workaround on this (re-login is not acceptable)?

Thanks in advance

**Comment by iowlit** [comment]
The only possible workaround that I've found is to swizzle SFNetwork's "URLSession:task:willPerformHTTPRedirection:newRequest:completionHandler:" and allow any redirections. But I am not sure whether the fix is save.

**Comment by wmathurin** [comment]
Thanks @iowlit 
We will look into handling 301/307 automatically in a future release.

**Comment by bbirman** [comment]
Added automatic redirects for Salesforce URLs [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3629), thanks again for reaching out!
