### ISSUE TITLE
Need to include more domains for deleting cookies

### ISSUE THREAD

**Issue by PPunya** [forcedotcom/SalesforceMobileSDK-iOS#3549]
Please fill out the following details:

1. Version of Mobile SDK Used: 10.1.1
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: 16.0
4. Device: All iPhones with iOS 15.0 or more
5. Steps to reproduce: Use an org that has enabled 'enhanced domains' Login to the app, then logout.
6. Actual behavior: Invokes the biometric and logs in the user again.
7. Expected Behavior: Should show login screen

Observation:
After the domain change, the new URL has .site.com instead of .force.com. As SFSDKWebViewStateManager.m's domains array does not have @".site.com", the SDK is unable delete all cookies after logout. Have verified locally that after adding this domain to the list, then above issue does not occur.

Experience Cloud sites | -
-- | --
Old | SandboxName-ExperienceCloudSitesSubdomainName.InstanceName.force.com
New | MyDomainName--SandboxName.sandbox.my.site.com

 Reference: https://help.salesforce.com/s/articleView?id=sf.domain_name_url_format_changes_enable_enhanced.htm&type=5
 
 Kindly suggest if there is any other solution to this issue or domain list should be enhanced.

**Comment by PPunya** [comment]
Commenting for visibility.

**Comment by gkotula** [comment]
Apologies for for the delayed response.  We acknowledge this issue's importance and are looking into the best path forward to fix it.  Thank you for your patience!

**Comment by bbirman** [comment]
@sheryDiplomat, yes the fix will be in the upcoming release
