### ISSUE TITLE
SCSFileTransferEvent is not coming with all events  ServiceCloud.shared().chatCore.session.allEvents

### ISSUE THREAD

**Issue by bondarchukssl** [forcedotcom/SalesforceMobileSDK-iOS#3550]
We are expected that SCSFileTransferEvent will be coming alongside [SCSChatEventProtocol] protocol.
But getting everything except SCSFileTransferEvent.

Is it a bug or should we look on some other interface rather than  ServiceCloud.shared().chatCore.session.allEvents ?
 Version of Mobile SDK Used:   pod 'ServiceSDK/Chat', '234.1.0'

**Comment by bhariharan** [comment]
This isn't the right forum for `ServiceSDK` issues - that is a different product. Please open an investigation with Salesforce.
