### ISSUE TITLE
Customize theme for Lock Screen controls and background

### ISSUE THREAD

**Issue by pushp1010** [forcedotcom/SalesforceMobileSDK-iOS#3551]
Please fill out the following details:

1. Version of Mobile SDK Used: 10.2.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 14 and later
4. Device: iPhone
5. Steps to reproduce: Login using connected app
6. Actual behavior: We migrated from Salesforce iOS SDK v9.0.0 to v10.2.0. In  the attached screenshot, the screen displayed is a view “ScreenLockUIView”.
7. Expected Behavior: Please suggest if there is a way to modify the colors and fonts for background and other controls.
8. Error Log: NA

<img width="414" alt="Issue1" src="https://user-images.githubusercontent.com/52121407/197781255-4f009857-6537-48bc-a533-2a00641d85f3.png">

**Comment by gkotula** [comment]
@pushp1010 Apologies, but we cannot commit to a release date for this enhancement at this time.

**Comment by pushp1010** [comment]
@gkotula  any updates on it?

**Comment by bbirman** [comment]
This doesn't currently have a release date, we'll post here with any updates

**Comment by wmathurin** [comment]
We have just released Mobile SDK 11.0 which contains enhancements in that area (https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3586). It's a different user experience, the unlock sheet pops up over the login screen (which has always been customizable).
![bio_auth_demo](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/assets/1012459/8e5e652c-3a87-4adb-b4a6-d1252c7b4276)

Please re-open this issue if you feel that it still does not address your needs.
