### ISSUE TITLE
No redirection to settings from “ScreenLockUIView” as in Android

### ISSUE THREAD

**Issue by pushp1010** [forcedotcom/SalesforceMobileSDK-iOS#3552]
Please fill out the following details:

1. Version of Mobile SDK Used:  10.2.0
2. Issue found in Native App or Hybrid App:  native
3. OS Version: iOS 14 and later
4. Device: All iOS device 
5. Steps to reproduce:  Go to passcode screen
6. Actual behavior:We are using Salesforce iOS SDK version 10.2.0 and for users who do not have passcode or Face ID configured already in device, attached screen is showing up. 
7. Expected Behavior:Here we don’t see any option for user to get redirected to settings but latest Android SDK version has a redirection button. Is it possible to prioritize this feature to make the user experience similar across platforms?
8. Error Log: NA. 

![Issue2](https://user-images.githubusercontent.com/52121407/197797146-4cb47f38-0440-40d6-8b16-f039c74dc568.PNG)

**Comment by brandonpage** [comment]
Hi @pushp1010,  unfortunately it is impossible to navigate the user directly to the security settings on iOS (like we do on Android).  Any tricky attempts to do this risk AppStore rejection, which is the last thing we want.  If you think instruction or something else on screen would be helpful let us know.  

Thanks,
Brandon
