### ISSUE TITLE
Sign In with Apple error

### ISSUE THREAD

**Issue by mkkroliks** [forcedotcom/SalesforceMobileSDK-iOS#3553]
I'm getting the following error while attempting to "sign in with apple".
<img width="422" alt="Screen Shot 2022-11-02 at 15 28 36" src="https://user-images.githubusercontent.com/2151961/199515995-85ead78b-8706-4104-914f-b8b9c6fdc886.png">

The error appears only on the release version. It works fine on the simulator.

1. Version of Mobile SDK Used: 10.1.1
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: Any
4. Device: iPhone and iPad 
5. Steps to reproduce: Click "SIGN IN WITH APPLE", submit credentials, or click cancel.
6. Actual behavior: "Can't connect to the server: Frame load interrupted" error appears on a screen
7. Expected Behavior: The error shouldn't appear on a screen. 
8. Error Log: "Can't connect to the server: Frame load interrupted"

**Comment by bhariharan** [comment]
You need to turn on Advanced Authentication to use 'Sign in with Apple'. Please review the Advanced Authentication section in our dev guide.

**Comment by wmathurin** [comment]
[Here](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/auth_advanced_using.htm) is a link to the advanced auth documentation.

**Comment by mkkroliks** [comment]
Thank you!

**Comment by mkkroliks** [comment]
@bhariharan should it be done on an app side?

**Comment by bhariharan** [comment]
@mkkroliks It needs to be configured on the org side and validated on the client.
