### ISSUE TITLE
Is it possible to log in as another user using SDK?

### ISSUE THREAD

**Issue by oofimaconsumer** [forcedotcom/SalesforceMobileSDK-iOS#3554]
Web version has a feature that allows administrators to log in as another user: https://help.salesforce.com/s/articleView?id=sf.logging_in_as_another_user.htm&type=5

But I cannot find any information anywhere about how I can add this ability to my app. So, are there any additional authentication scope or something else that I can use?

**Comment by wmathurin** [comment]
It's only available through the user interface and not through APIs. It's discussed in this (old) [post](https://salesforce.stackexchange.com/questions/126723/how-to-login-as-another-user-through-soap-api).
