### ISSUE TITLE
Unable to create build in xcode 14.0

### ISSUE THREAD

**Issue by point8290** [forcedotcom/SalesforceMobileSDK-iOS#3555]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.1.1
2. Issue found in Native App or Hybrid App: Hybrid app
3. OS Version: macos Ventura 
4 Steps to reproduce: Try to build in xcode 14
6. Actual behavior: unable to build app
7. Expected Behavior: should be able to build 
8. Error Log: Duplicate interface definition for class 'CDVInvokedURLCommand'

**Comment by brandonpage** [comment]
Hi @point8290 Mobile SDK 5.1.1 is about 5 years old, please update.  I can guarantee xcode 14 works without issue on the latest, Mobile SDK 10.2.
