### ISSUE TITLE
Apple Sign in error when using biometrics to login/ cancel

### ISSUE THREAD

**Issue by skodeds** [forcedotcom/SalesforceMobileSDK-iOS#3557]
Version of Mobile SDK Used: 10.1.1
Issue found in Native App or Hybrid App: Native App
OS Version: Any
Device: iPhone and iPad
Steps to reproduce: Click "SIGN IN WITH APPLE", submit credentials using biometrics (Face ID or finger print), or click cancel.
Actual behavior: "Can't connect to the server: Frame load interrupted" error appears on a screen
Expected Behavior: The error shouldn't appear on a screen.
Error Log: "Can't connect to the server: Frame load interrupted"
This issue is for login into "Experience Cloud" (formerly Community Cloud).

We created a ticket earlier - Refer to https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3553  but the proposed solution does not apply in this scenario. 

When using Apple login, if we enter Apple username/password, login works fine on both the Browser and Mobile App.

When using Apple login with biometric ID, it only works with the browser.  When using Apple biometric id on the mobile App we get the error above.

Since this login is for Experience Cloud only, it is not turned on in My Domain.

**Comment by militantjones** [comment]
The error, captured in our Headspin instance has the following details - 

AuthKitUIService(UIKitCore) | com.apple.AuthKitUIService
<Error>: No "UIViewServicePermittedViewControllerClasses" array in View Service bundle "com.apple.AuthKitUIService"'s Info.plist. Cannot check validity of request for class "AKAuthorizationRemoteViewController". This will become failure in a future build.

The error occurs also if they tap the "Cancel" before invoking any biometrics.

**Comment by wmathurin** [comment]
A number of changes have taken place since the issue was first opened. Please re-open the issue if it still persists on the latest version of Mobile SDK (12.0).
