### ISSUE TITLE
PIN Unlock Event (Hybrid App)

### ISSUE THREAD

**Issue by jhtest** [forcedotcom/SalesforceMobileSDK-iOS#356]
Registering a soups prior to PIN unlock is causing errors - 
Is there an event listener for when a user unlocks the app with the PIN code?

I.e.  something like: document.addEventListener("pinUnlockSuccess", onPinUnlockFunction, false);
 
The log seems to write the following, but I don't know how to subscribe to it in the container: "SFSecurityLockout|Sending passcode flow completed notification with validation success = 1"

**Comment by huminzhi** [comment]
We added an internal work of this on our backlog... closing this issue..

**Comment by bhariharan** [comment]
@huminzhi Let's keep it open till we get this implemented and merge it.
