### ISSUE TITLE
Soft logout feature in Salesforce mobile SDK

### ISSUE THREAD

**Issue by pushp1010** [forcedotcom/SalesforceMobileSDK-iOS#3563]
Please fill out the following details:

1. Version of Mobile SDK Used:  10.2.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 16 and later
4. Device:  iPhone  11 and above
5. Steps to reproduce:  if user taps on logout and closes the app, then comes back to the app again.
6. Actual behavior: Currently, when we logout a user using SDK’s methods, all his details are removed from the app and only way to login is by entering credentials into webview.
7. Expected Behaviour: User should be able to see the screen with username/ID and authenticate using biometric to login back like many banking applications support this way of login. Screenshot attached
8. Error Log:

 Please suggest if this feature exists in current version of SDK or it can be taken as future enhancement.

![MicrosoftTeams-image (24)](https://user-images.githubusercontent.com/52121407/209320838-2d4ee591-7cdb-489a-b2c2-2f9ed1677471.png)

**Comment by bbirman** [comment]
This is currently working as designed, thanks for the feedback for future enhancements!

**Comment by wmathurin** [comment]
The feature (soft logout / biometric authentication) is coming in our next version of Mobile SDK (11.0) scheduled for late spring or early summer.
It's being currently implemented (see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3586).
