### ISSUE TITLE
Server Error: Can't connect to the server: Access Token missing after iPad restore

### ISSUE THREAD

**Issue by Zokor** [forcedotcom/SalesforceMobileSDK-iOS#3564]
Is this problem fixed already? we've been having this issue for quite some time (years )

Please fill out the following details:

Version of Mobile SDK Used
9.0.0

Issue found in Native App or Hybrid App
Hybrid App

OS Version
Problem detected since iOS 14 (maybe since ever)

Device
iPad

Steps to reproduce:
Restore an iPad from a backup ( or copy device )

Actual behavior:
![image](https://user-images.githubusercontent.com/5063752/210337091-f39a0278-04b8-474c-90c5-3908ef9cddef.png)

It doesn't happen all the time, a way to pass through this would be awesome.

Expected Behavior
To login :)

**Comment by bhariharan** [comment]
We don't support Keychain backup/restore actions.

**Comment by Zokor** [comment]
But there ain't any way to prevent this ? Something like if access token is missing fetch another one?

**Comment by wmathurin** [comment]
Could you try with the latest Mobile SDK (10.2)? I would expect the user to be taken back to the login screen. 
(Without the refresh token, we cannot simply fetch another access token, the user needs to login again).

**Comment by Zokor** [comment]
We have the latest SDK, it's a very rare problem that happens when a user gets his content copied from and old iPad to a new iPad

**Comment by gkotula** [comment]
To be clear, even if the users delete the app after encountering the issue after a device restore, and then reinstall the app, they are still blocked from being able to log in?

**Comment by bbirman** [comment]
There was a similar sounding issue that was fixed in 10.1.0, but if you're still seeing the issue in newer versions could you share any logs you have?

**Comment by wmathurin** [comment]
Closing issue, for lack of updates. Please re-open if you are still having the issue and you are using the most recent version of the Mobile SDK (or at least 10.1).
