### ISSUE TITLE
Crashes in SFSDKCompositeResponse and SFSDKBatchResponse

### ISSUE THREAD

**Issue by iowlit** [forcedotcom/SalesforceMobileSDK-iOS#3568]
1. Version of Mobile SDK Used: 10.1.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 16.*
4. Device: iPad/iOS

There are several crashes in our crashlitics:

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x9e88 __exceptionPreprocess
1  libobjc.A.dylib                0x178d8 objc_exception_throw
2  CoreFoundation                 0x17e84c +[NSObject(NSObject) _copyDescription]
3  CoreFoundation                 0x1ffa0 ___forwarding___
4  CoreFoundation                 0x88350 _CF_forwarding_prep_0
5  SalesforceSDKCore              0x42fcc -[SFSDKBatchResponse initWith:] + 31 (SFSDKBatchResponse.m:31)
6  SalesforceSDKCore              0x3534c __64-[SFRestAPI(Blocks) sendBatchRequest:failureBlock:successBlock:]_block_invoke + 73 (SFRestAPI+Blocks.m:73)
7  SalesforceSDKCore              0x35414 -[SFRestAPI(Blocks) triggerDelegatesForRequest:success:withObject:rawResponse:error:] + 85 (SFRestAPI+Blocks.m:85)
8  SalesforceSDKCore              0x32c88 -[SFRestAPI notifyDelegateOfSuccess:request:data:rawResponse:] + 460 (SFRestAPI.m:460)
9  SalesforceSDKCore              0x31d08 __56-[SFRestAPI enqueueRequest:requestDelegate:shouldRetry:]_block_invoke + 308 (SFRestAPI.m:308)
10 FirebasePerformance            0x1c800 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke_2 + 307 (FPRNSURLSessionInstrument.m:307)
11 FirebasePerformance            0x1c800 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke_2 + 307 (FPRNSURLSessionInstrument.m:307)
12 CFNetwork                      0x2005c CFURLRequestSetMainDocumentURL
13 CFNetwork                      0x2ffb4 _CFNetworkErrorCopyLocalizedDescriptionWithHostname
14 libdispatch.dylib              0x24b4 _dispatch_call_block_and_release
15 libdispatch.dylib              0x3fdc _dispatch_client_callout
16 libdispatch.dylib              0xb694 _dispatch_lane_serial_drain
17 libdispatch.dylib              0xc214 _dispatch_lane_invoke
18 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread
19 libsystem_pthread.dylib        0xdf8 _pthread_wqthread
20 libsystem_pthread.dylib        0xb98 start_wqthread

<img width="1794" alt="Screenshot 2023-01-30 at 17 46 58" src="https://user-images.githubusercontent.com/25912107/215780406-2e07b422-007b-42e6-9e4f-f8f56fbba4e2.png">

and

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x92d1c __exceptionPreprocess
1  libobjc.A.dylib                0x14ee4 objc_exception_throw
2  CoreFoundation                 0x16375c +[NSObject(NSObject) _copyDescription]
3  CoreFoundation                 0x2c61c ___forwarding___
4  CoreFoundation                 0x2b82c _CF_forwarding_prep_0
5  SalesforceSDKCore              0x440b4 -[SFSDKCompositeResponse initWith:] + 56 (SFSDKCompositeResponse.m:56)
6  SalesforceSDKCore              0x35214 __68-[SFRestAPI(Blocks) sendCompositeRequest:failureBlock:successBlock:]_block_invoke + 66 (SFRestAPI+Blocks.m:66)
7  SalesforceSDKCore              0x35414 -[SFRestAPI(Blocks) triggerDelegatesForRequest:success:withObject:rawResponse:error:] + 85 (SFRestAPI+Blocks.m:85)
8  SalesforceSDKCore              0x32c88 -[SFRestAPI notifyDelegateOfSuccess:request:data:rawResponse:] + 460 (SFRestAPI.m:460)
9  SalesforceSDKCore              0x31d08 __56-[SFRestAPI enqueueRequest:requestDelegate:shouldRetry:]_block_invoke + 308 (SFRestAPI.m:308)
10 FirebasePerformance            0x1c800 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke_2 + 307 (FPRNSURLSessionInstrument.m:307)
11 FirebasePerformance            0x1c800 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke_2 + 307 (FPRNSURLSessionInstrument.m:307)
12 CFNetwork                      0x1fa84 CFURLRequestSetMainDocumentURL
13 CFNetwork                      0x300f8 _CFNetworkErrorCopyLocalizedDescriptionWithHostname
14 libdispatch.dylib              0x63094 _dispatch_call_block_and_release
15 libdispatch.dylib              0x64094 _dispatch_client_callout
16 libdispatch.dylib              0xa73c _dispatch_lane_serial_drain$VARIANT$mp
17 libdispatch.dylib              0xb224 _dispatch_lane_invoke$VARIANT$mp
18 libdispatch.dylib              0x14ec8 _dispatch_workloop_worker_thread
19 libsystem_pthread.dylib        0x1e10 _pthread_wqthread
20 libsystem_pthread.dylib        0x193c start_wqthread

Under some strange circumstances it appears to be possible to receive corrupted response data. The invalid argument exception `-[OS_dispatch_data objectForKey:]: unrecognized selector sent to instance` occurs in SFSDKCompositeResponse and SFSDKBatchResponse initialisers. The classes expect NSDictionary as an argument but get OS_dispatch_data instead due to corrupted response. 

STR:

1. Intercept services/data/v50.0/composite/batch or services/data/v50.0/composite responses
2. Corrupt a response body - make JSON invalid (delete brackets or whatever)
3. Execute the updated response.

**Comment by bbirman** [comment]
Thanks @iowlit for your contribution!

**Comment by iowlit** [comment]
Hi @bbirman. Do you know when the fix is going to be released? In v11 the fix is missing. We are still experiencing such crashes.

**Comment by iowlit** [comment]
Yes, sorry, my bad. I did not see it in diff for v11, it was introduced earlier. 
Thanks @bbirman
