### ISSUE TITLE
Maximum size of request reached. Maximum size of request is 52428800 bytes

### ISSUE THREAD

**Issue by Zokor** [forcedotcom/SalesforceMobileSDK-iOS#3575]
Hi all,

We're getting this problem:

[{"soupName":"coreLog","options":{"fieldlist":["Core_Source__c","Core_Type__c","Core_Message__c","Core_Hash__c","Amalia_CreatedDate__c"],"mergeMode":"LEAVE_IF_CHANGED"},"isGlobalStore":false,"error":"{\n    error =     (\n                {\n            errorCode = \"JSON_PARSER_ERROR\";\n            message = \"; nested exception is: \\n\\tcommon.exception.ApiException: Maximum size of request reached. Maximum size of request is 52428800 bytes.\";\n        }\n    );\n}","_soupEntryId":6379,"maxTimeStamp":0,"type":"syncUp","progress":99,"endTime":1677667996376,"target":{"idFieldName":"Id","modificationDateFieldName":"LastModifiedDate","iOSImpl":"SFCollectionSyncUpTarget","type":"rest","maxBatchSize":200},"totalSize":129,"storeName":"defaultStore","startTime":1677667991542,"status":"FAILED","name":"syncUp_coreLog"}]

Anyway for the SDK  (we're using the 10.2) to go past this limit ? There's dataloader, but the users using the iPad cannot use it... we need the sync to go past this limits. 

Thank you

**Comment by wmathurin** [comment]
Could you provide more details: what kind of sync up target were you using and how was it configured?

**Comment by wmathurin** [comment]
The server end point has a limit on how much data it can take at once. Are some of the fields you are uploading very large?
You should try specifying a maxBatchSize for your sync up with a value lower than the default (200).

**Comment by wmathurin** [comment]
Hopefully our suggestion (lower maxBatchSize) proved helpful. Please re-open an issue if you are still having a problem.
