### ISSUE TITLE
Login in Digital Experience environment After logging out, the access permission screen will appear.

### ISSUE THREAD

**Issue by ryukooo** [forcedotcom/SalesforceMobileSDK-iOS#3578]
Please fill out the following details:

1. Version of Mobile SDK Used: 10.1
2. Issue found in Native App or Hybrid App:Native Appp
　　Also confirmed at https://github.com/forcedotcom/SalesforceMobileSDK-Templates/tree/dev/iOSNativeSwiftTemplate
3. OS Version: iOS16.1
4. Device:ipone X
5. Steps to reproduce:
Login in Digital Experience environment
After logging out, the access permission screen will appear.

Return to the login screen if you are not a Digital Experience organization.

I had a similar question
　-　https://salesforce.stackexchange.com/questions/386601/mobilesdk-for-ios-force-user-to-login-and-re-authenticate-after-logout
　- https://salesforce.stackexchange.com/questions/398796/when-user-tries-to-logout-using-revokeapi-and-when-again-tries-to-login-user-ge

6. Actual behavior:
   Transition to the login access permission screen with the previous credentials
7. Expected Behavior:
     I want to transition to the login screen
8. Error Log:
  
![Simulator Screen Shot - iPhone 14 Pro - 2023-03-24 at 14 14 15](https://user-images.githubusercontent.com/28751562/227430646-d11502a3-d86e-4e0b-88a1-2d6c16ef24b3.png)
    
![Simulator Screen Shot - iPhone 14 Pro - 2023-03-24 at 14 14 21](https://user-images.githubusercontent.com/28751562/227430627-812dfd62-561b-42c1-91a8-6a1093980671.png)

**Comment by ryukooo** [comment]
wmathurin Thank you!
It seems to be happening without advanced authentication. Is there any way to return to the logout screen here?

**Comment by wmathurin** [comment]
We will investigate and let you know what we find out.

**Comment by ryukooo** [comment]
wmathurin Thanks.

**Comment by ryukooo** [comment]
@wmathurin 
how is the situation here.

**Comment by ryukooo** [comment]
@wmathurin 
Could you inform us about the current status?

**Comment by bbirman** [comment]
@ryukooo, from [this link =](https://salesforce.stackexchange.com/questions/386601/mobilesdk-for-ios-force-user-to-login-and-re-authenticate-after-logout)in your earlier post, does using "prompt=login" resolve the issue?

**Comment by ryukooo** [comment]
thank you @bbirman 
Just to confirm, is there any plan to fix it as SalesforceMobileSDK?

**Comment by bbirman** [comment]
We're planning on adding support for prompt=login

**Comment by ryukooo** [comment]
thank you @bbirman .
I solved it by adding "prompt=login" to the SDK.
Looking forward to your fix.

**Comment by ryukooo** [comment]
@bbirman It would be great if you could show me your schedule.
when are you scheduled

**Comment by ryukooo** [comment]
@wmathurin
It would be helpful if you could let us know the situation first by 5/15.
Sorry.

**Comment by ryukooo** [comment]
Sorry for commenting so many times.
Is it possible for this to occur on Android as well?

**Comment by wmathurin** [comment]
We are planning to add prompt=login on both iOS and Android in our next versions of Mobile SDK (11.0) scheduled for late spring / early summer.

**Comment by ryukooo** [comment]
thank you @wmathurin

**Comment by ryukooo** [comment]
@wmathurin
Is the Digital Experience environment as well as the non-Digital Experience environment?
> During login, there are **short term** cookies being setup which are not tied to the main session and are not invalidated if you logout right away. As a result, if you login then logout **shortly after**, you will skip the first screen where you enter your credentials and find yourself directly into the allow/deny screen. This issue happens **only when using advanced authentication**, because the login flow takes place in a ASWebAuthenticationSession. With regular authentication, we use a fresh WebView every time and therefore don't have any left over cookies.
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3578#issuecomment-1485815940

Also, please confirm that adding "prompt=login" will solve the problem.

Thank you.

**Comment by wmathurin** [comment]
Yes it should solve it.

**Comment by wmathurin** [comment]
This is fixed in dev (and will be in our next release 11.0).
The fix came with this PR: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3592

**Comment by ryukooo** [comment]
@wmathurin
thank you.
When will release 11.0 be out?
Please let me know if you have a scheduled date.

Please respond by 6/19 if possible.

**Comment by wmathurin** [comment]
The plan is currently end of next week #safeharbor.
