### ISSUE TITLE
Register data from SFMobileSyncNetworkUtils into local soup and fetch the local soup value?

### ISSUE THREAD

**Issue by adijazz91** [forcedotcom/SalesforceMobileSDK-iOS#3580]
Please fill out the following details:

1. Version of Mobile SDK Used: 10.2.0
2. Issue found in Native App or Hybrid App:Native iOS(Objective-C)
3. OS Version: 15.0
4. Device: iphone 13
5. Steps to reproduce:  Trying to store data to local soup and then fetch it. Attaching a complete log and step file
6. Actual behavior: Getting error while running SFQuerySpec
7. Expected Behavior: It should return the data from local soup.
8. Error Log: 
[StepsAndLog-10.2.0.pdf](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/11121241/StepsAndLog-10.2.0.pdf)

**Comment by wmathurin** [comment]
Soup name is **case sensitive**.
In `createUserSoup`,  you register a `User` soup.
```objective-c
[store registerSoup:@"User" withIndexSpecs:accountIndexSpecs error:&error];
```
You sync down target goes to the `User` soup.
```objective-c
[manager syncDownWithTarget:syncTarget soupName:@"User" updateBlock:^(SFSyncState * _Nonnull sync)
```

But in the `fetchLocalSoup`, you query the `user` soup
```objective-c
 NSString *localSoqlQuery = [NSString stringWithFormat:@"select * from {user} WHERE {user:Id} ='%@'", [Utility getUserId]];
```

**Comment by adijazz91** [comment]
tried with lower case as well still no success.
Attaching the logs.
[StepsAndLog-1-Salesofrce-SDKv10.2.0.pdf](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/11135132/StepsAndLog-1-Salesofrce-SDKv10.2.0.pdf)
