### ISSUE TITLE
Make sure you're running a packager server or have included a .jsbundle file in your application bundle. (Release build))

### ISSUE THREAD

**Issue by taitranomi** [forcedotcom/SalesforceMobileSDK-iOS#3583]
Please fill out the following details:

1. Version of Mobile SDK Used: 10.2.0
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: 16.2
4. Device: Iphone 14 Pro
5. Steps to reproduce:

- Step 1: Go to Xcode => Product => Scheme => Edit Scheme => change all schemes to Release
<img width="229" alt="Screenshot 2023-04-22 at 16 54 54" src="https://user-images.githubusercontent.com/37283275/233777131-a579a002-0721-40e7-9f5b-86c66d97ab33.png">

- Step 2: Click on Start active Scheme button
<img width="413" alt="Screenshot 2023-04-22 at 16 59 15" src="https://user-images.githubusercontent.com/37283275/233777300-78f437ec-6999-4273-b0a4-955f727c8676.png">

7. Actual behavior: error shows in below image
![Screenshot 2023-04-21 at 20 48 46](https://user-images.githubusercontent.com/37283275/233777337-4dbce7ed-8894-4bd1-8a7e-c5c4a4f2c7a2.png)

8. Expected Behavior: Run successfully without any error
9. Error Log: 

**_libc++abi: terminating with uncaught exception of type NSException
terminating with uncaught exception of type NSException
Terminating app due to uncaught exception 'RCTFatalException: No bundle URL present.

Make sure you are running a packager server or have included a .jsbundle file in your application bundle., reason: No bundle URL present.

Make sure you are running a packager server or have included a .jsbundle file in your application bundle.
CoreSimulator 857.14 - Device: iPhone 14 Pro (2C76A6AC-301A-4153-B4A9-2D7C3AE1593C) - Runtime: iOS 16.2 (20C52) - DeviceType: iPhone 14 Pro
(lldb)_**

**Comment by wmathurin** [comment]
Have you included the .jsbundle or are your running the packager server (by doing `npm start` or `yarn start` from the root directory of your project)?

**Comment by wmathurin** [comment]
Closing for lack of response. Hopefully my previous comment was useful.
