### ISSUE TITLE
Way to Ignore "modifyQueryIfNeeded" in SFSoqlSyncDownTarget class?

### ISSUE THREAD

**Issue by adijazz91** [forcedotcom/SalesforceMobileSDK-iOS#3594]
Please fill out the following details:

1. Version of Mobile SDK Used:  10.2.0
2. Issue found in Native App or Hybrid App: Objective-C
3. OS Version: iOS 16
4. Device: iPad mini (6th Gen)
5. Steps to reproduce: While syncing down create SFSycnDownTarget in the target creation you can see in a class "SFSoqlSyncDownTarget.h/.m" we have a function "[syncTarget modifyQueryIfNeeded];" which basically Inserts the mandatory 'LastModifiedDate' field if it doesn't exist and then Inserts the mandatory 'Id' field if it doesn't exist and also inserting the Order by 'LastModifiedDate' field if no order by specified.
6. Actual behavior: This forcefully adding these Attribute doesn't meet our business requirement. As in various soups we do not have LastModified as an Attribute.
7. Expected Behavior: Some argument injection or condition  were we can byapss this forcefully addition of these Attributes.
8. Error Log: Attaching the log
[Logs_OrderBY_LastModifiedAndID.pdf](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/11514057/Logs_OrderBY_LastModifiedAndID.pdf)

**Comment by wmathurin** [comment]
If the sync targets that come with Mobile SDK do not meet your business requirements, you can define custom sync target. You don't have to write them from scratch, you could subclass an existing one.
For more information see: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/entity_framework_native_custom_down_targets.htm
