### ISSUE TITLE
Identifying composite Request not working in 10.2.0

### ISSUE THREAD

**Issue by iosdroid** [forcedotcom/SalesforceMobileSDK-iOS#3595]
Please fill out the following details:

1. Version of Mobile SDK Used: 10.2.0
2. Issue found in Native App or Hybrid App:Native
3. OS Version:16.2

 @objc class func sendRequestWithMobileSyncUserAgent(_ request: RestRequest, failureBlock: @escaping RestRequestFailBlock, successBlock: @escaping RestResponseBlock) {
        if let theCompReq = request as? CompositeRequest {
            doCompositeRestCall(theCompReq, failureBlock: failureBlock, successBlock: successBlock)
        } else {
            doNormalRestCall(request, failureBlock: failureBlock, successBlock: successBlock)
        }
    }

**Comment by wmathurin** [comment]
Closing for lack of details.
