### ISSUE TITLE
iOS Mobile Application is getting Crashed in Background

### ISSUE THREAD

**Issue by kusumarakesh** [forcedotcom/SalesforceMobileSDK-iOS#3597]
Please fill out the following details:

1. Version of Mobile SDK Used:  MobileSync (9.2.1)
2. Issue found in Native App or Hybrid App: Native iOS Application
3. OS Version: iOS 16.4.1
4. Device: iPhone
5. Steps to reproduce: The application is crashing in background. This is tracked using Firebase Analytics. Respective images are attached below
6. Actual behavior:
7. Expected Behavior:
8. Error Log: Stack trace file is attached below

<img width="1419" alt="Screenshot 2023-05-22 at 11 33 49 PM" src="https://github.com/forcedotcom/SalesforceMobileSDK-iOS/assets/103421485/97377813-2682-47e1-af10-7fb03ed55fab">
<img width="1347" alt="Screenshot 2023-05-22 at 11 34 02 PM" src="https://github.com/forcedotcom/SalesforceMobileSDK-iOS/assets/103421485/1091a071-63d9-4aa3-ab75-2bb0ca8cdd35">

[uk.org.pharmpress.bnf_issue_7e1118c2f3ac75741a94b21a9131bf31_crash_session_7a503a84e9b64025b20e359d7378c2d4_DNE_0_v2_stacktrace.txt](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/11540927/uk.org.pharmpress.bnf_issue_7e1118c2f3ac75741a94b21a9131bf31_crash_session_7a503a84e9b64025b20e359d7378c2d4_DNE_0_v2_stacktrace.txt)

**Comment by bbirman** [comment]
That should be fixed in 10.1, can you try updating to the latest?

**Comment by kusumarakesh** [comment]
> That should be fixed in Mobile SDK 10.1, can you try updating to the latest?
Thanks @bbirman  Let us try to use the latest one as per your recommendation.

**Comment by wmathurin** [comment]
Closing for now. Re-open if you are still having the issue (on the latest Mobile SDK).
