### ISSUE TITLE
Upgrade iPad application using Salesforce SDK 6.2.0 to latest version of SDK 

### ISSUE THREAD

**Issue by jpdavanzo** [forcedotcom/SalesforceMobileSDK-iOS#3598]
**Problem Statment:**

We have an iPad application using SalesforeSDK 6.2.0 trying to upgrade to latest version of SDK (10).

Steps tried to upgrade to latest version of the SDK

1. Used the Salesforce the forceios npm script to create the sample swift_native app. 
2. Copied the podfile details from new sample iOS project to my existing old app 

Podfile : -

**———— File start ————**

require_relative './mobile_sdk/SalesforceMobileSDK-iOS/mobilesdk_pods'

 

platform :ios, '14.0'

 

project 'SwiftEventApp.xcodeproj'

target 'SwiftEventApp' do

  source 'https://cdn.cocoapods.org/'

  use_frameworks!

  use_mobile_sdk!

**end**

Comment the following if you do not want the SDK to emit signpost events for instrumentation. Signposts are  enabled for non release version of the app.
post_install do |installer|

  signposts_post_install(installer)

**end**

**—————— File End ————**

 

3 Open terminal in same existing project folder and run terminal command -

$ pod install

1. Copy other files and folder to my project folder -

-   mobile_sdk, 
-   package.json, 
-   userstore.json, 
-   usersyncs.json, 
-   bootconfig.plist

2. Updated the config details in bootconfig.plist
3. Made following code changes in the attached patch files

 

**Questions:** 

1. Please review both the patch files is the changes are correct to make api call, performSOQLQuery and other changes
2. How we can multiple build configure environments in bootconfig.json
3. What is the use of userstore.json, usersyncs.json how can we configure and use it in my codebase
4. Following API are deprecated please help to how to fix it

//        SalesforceSDKManager.shared().postLaunchAction =

{ //            [unowned self] (launchActionList: SFSDKLaunchAction) in //            let launchActionString =    SalesforceSDKManager.launchActionsStringRepresentation(launchActionList) //            //self.log(.info, msg:"Post-launch: launch actions taken: \(launchActionString)"); //            self.setupRootViewController(); //        }
//

 

 

//        SalesforceSDKManager.shared().launchErrorAction = {

//            [unowned self] (error: Error?, launchActionList: SFSDKLaunchAction) in

//            if let actualError = error

{ //                //self.log(.error, msg:"Error during SDK launch: \(actualError.localizedDescription)") //            }
else

{ //                //self.log(.error, msg:"Unknown error during SDK launch.") //            }
//            self.initializeAppViewState()

//            SalesforceSDKManager.shared().launch()

//        }

 

 

//        SalesforceSDKManager.shared().postLogoutAction =

{ //            [unowned self] in //            self.handleSdkManagerLogout() //        }
//        SalesforceSDKManager.shared().switchUserAction =

{ //            [unowned self] (fromUser: SFUserAccount?, toUser: SFUserAccount?) -> () in //            self.handleUserSwitch(fromUser, toUser: toUser) //        }
[patch2.txt](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/11545948/patch2.txt)
[patch1.txt](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/11545949/patch1.txt)

**Comment by bbirman** [comment]
- Here's more information on [userstore.json](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/offline_config_files.htm) and [usersyncs.json](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/entity_framework_sync_related.htm) 
- The bootconfig only supports one connected app
- You can use loginIfRequired [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/79b236fe3d3b8f64373dd03aaf94494c273a4c13/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Util/SFSDKAuthHelper.h#L41) as the entry point for the SDK and add the code that you have in postLaunchAction in the completion block. There are methods in the same class for handling logout

**Comment by wmathurin** [comment]
Closing the issue. Hopefully the information provided above was useful. For more help on how to something with the Mobile SDK, please post on our [stack exchange](https://salesforce.stackexchange.com/questions/tagged/mobilesdk).
