### ISSUE TITLE
Logout - Not redirecting the user to Login screen after logout

### ISSUE THREAD

**Issue by adijazz91** [forcedotcom/SalesforceMobileSDK-iOS#3610]
Please fill out the following details:

1. Version of Mobile SDK Used: 10.2.0
2. Issue found in Native App or Hybrid App: iOS(Objective-C)
3. OS Version: iOS 16.0
4. Device: iPhone 14
5. Steps to reproduce: When I Do logout it does not load the login screen instead load the "Deny" and  "Allow" screen
6. Actual behavior: Not laoding login screen after calling any of these method "[[SFUserAccountManager sharedInstance] logout];
                [[SFUserAccountManager sharedInstance] logoutAllUsers];"
7. Expected Behavior: Once logout it should load Login Screen where user can enter Username and password.
8. Error Log: Attaching the File and Screenshot

![Simulator Screenshot - iPhone 14 - 2023-06-12 at 19 26 48](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/assets/13691904/94e1b407-7e3a-4dbe-93d6-34f32a926337)
[log_User_Logout_Issue.pdf](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/11724044/log_User_Logout_Issue.pdf)

**Comment by wmathurin** [comment]
This is fixed in dev (and will be in our next release 11.0).
The fix came with this PR: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3592

**Comment by adijazz91** [comment]
When can we see the global release on this PR?

**Comment by wmathurin** [comment]
11.0 is scheduled to ship before the end of June.
