### ISSUE TITLE
open hyperlink inside app

### ISSUE THREAD

**Issue by ankur0202** [forcedotcom/SalesforceMobileSDK-iOS#3625]
Please fill out the following details:

1. Version of Mobile SDK Used: 238.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 16.0
4. Device: iPhone 13
5. Steps to reproduce: click on any hyperlink in chat window it's redirecting to safari
6. Actual behavior: want to make few link redirection within the app
7. Expected Behavior: it's should redirect with app
8. Error Log: NA

**Comment by bbirman** [comment]
This repo doesn't include chat, please reach out to Salesforce support
