### ISSUE TITLE
Passcode Screen Not Displayed OR Disappear

### ISSUE THREAD

**Issue by chidsami** [forcedotcom/SalesforceMobileSDK-iOS#3631]
Please fill out the following details:

1. Version of Mobile SDK Used: 10.2.0
2. Issue found in Native App or Hybrid App: iOS Native 
3. OS Version: 16.2
4. Device: Tested in iPhone 14 Pro Max & iPhone 7
5. Steps to reproduce: Launch the Salesforce Connected App and enter the credentials in Salesforce Login page. After successful login Passcode screen will be displayed. Don't enter the passcode. Minimise the app and launch the app again. Passcode screen disappeared. 
6. Actual behavior: App not displayed passcode screen when application coming to foreground from background.
7. Expected Behavior: App should displayed passcode screen when application coming to foreground from background.
8. Error Log: NA

**Comment by bbirman** [comment]
Could you trying using Mobile SDK 11.0? https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3571 in was for a similar sounding issue and released in 11.0

**Comment by chidsami** [comment]
Hi @bbirman ,
I can able to reproduce the above issue in Salesforce SDK 11.0.

**Comment by bbirman** [comment]
Thanks for the update, we'll investigate it more

**Comment by wmathurin** [comment]
We believe the issue no longer exists in the most recent version of Mobile SDK. Please open an issue if you are somehow able to reproduce it still.
