### ISSUE TITLE
Getting "invalid client credentials" after upgrading to SDK 11.0

### ISSUE THREAD

**Issue by mrcase** [forcedotcom/SalesforceMobileSDK-iOS#3633]
Please fill out the following details:

1. Version of Mobile SDK Used: 11.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 16.4
4. Device: iPad Pro
5. Steps to reproduce: When we attempt an Okta login, we go through the entire login process (Log in with Okta Single Sign-on New), it goes through a push notification step (which leads me to believe my password is correct), and then once that step is done, I get a popup that says "Server Error.  Can't connect to the server:  invalid client credentials".

I don't see any instructions for anything we were supposed to have changed to switch to SDK 11.  Am I missing something?
7. Actual behavior: Popup saying "Server Error.  Can't connect to the server:  invalid client credentials".
8. Expected Behavior: To login to the app.
9. Error Log: Nothing shows up in the logs.

**Comment by bbirman** [comment]
Can you see if the “Require Secret for Web Server Flow” checkbox is selected on your connected app? In 11.0 we changed the default auth flow and it doesn't work unless that box is deselected (more info [here](https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/oauth_web_server_flow.htm))

**Comment by mrcase** [comment]
Where would that checkbox be?   Is that in Salesforce itself?

**Comment by mrcase** [comment]
Yeah, it looks like we do have that checkbox checked.   I'll see if I can get that unchecked.   Thank you!

**Comment by wmathurin** [comment]
Otherwise, check out the doc that @bbirman linked earlier, it describes a way to opt out of the new flow (web server flow) and instead use the old flow (user agent flow).

**Comment by wmathurin** [comment]
Closing this. Let us know if you are still having issues after updating the connected app / or after switching back to user agent flow.
