### ISSUE TITLE
App cant start with login page

### ISSUE THREAD

**Issue by any552211** [forcedotcom/SalesforceMobileSDK-iOS#3635]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.0.2
2. Issue found in Native App or Hybrid App: Hybrid 
3. OS Version: 16.5
4. Device: iPhone 13
5. Steps to reproduce: open app
6. Actual behavior:
App shows an error message
"Bootstrap error page: Your app specifies authentication at startup, but there are no credentials. Did you run [[SalesforceSDKManager sharedManager] launch]? Error context: AppLoading"
7. Expected Behavior:
Show Login Screen
8. Error Log: N/A
![画像1](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/assets/105183654/9db75805-41a0-452f-97b5-eae317175d75)

This app is usually run as normal but when error occurred, it cant start with login screen as normal even after restart app neither restart device.
After reinstall the app, the problem disappeared.

**Comment by wmathurin** [comment]
Is it a hybrid remote or an hybrid local application?
What are the values of isLocal, shouldAuthenticate and attemptOfflineLoad in your bootconfig.json file?

**Comment by wmathurin** [comment]
Closing for lack of details.
