### ISSUE TITLE
Using the AuthHelper and retrieving the oauth token from salesforce does not include its data on SalesforceMobileSDK-iOS

### ISSUE THREAD

**Issue by ekahannah** [forcedotcom/SalesforceMobileSDK-iOS#3655]
Please fill out the following details:

1. Version of Mobile SDK Used: 11.0.1
2. Issue found in Native App or Hybrid App: Native iOS
3. OS Version: 16.4
4. Device: iPad Air Emulator
5. Steps to reproduce: User login to a webview which retrieves Oauth token from server backend, then takes the  user to home page in a webview.
6. Actual behavior: Once user successfully login, the user cant see its data.  It seems that it did not load the apexremote path 
7. Expected Behavior:Once user successfully login, the user should see its data. It should load the apexremote path 
8. Error Log:

**Comment by wmathurin** [comment]
For your use case, it might be easier starting with our hybrid remote template: see [doc](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/hybrid_intro.htm).

**Comment by wmathurin** [comment]
Closing issue - we provided a work around 6+ months ago.
