### ISSUE TITLE
Request for Auto-Login After Password Creation/Reset

### ISSUE THREAD

**Issue by bhagwat8024** [forcedotcom/SalesforceMobileSDK-iOS#3656]
Please fill out the following details:

1. Version of Mobile SDK Used:  11.0.0
2. Issue found in Native App or Hybrid App: Native IOS
3. OS Version: version > 15.0
4. Device: All
5. Steps to reproduce: New or existing functionality
6. Actual Behaviour:  After resetting or create password the password, the application redirects to the login screen.
7. Expected Behaviour: After resetting or create the password, the application should not ask for login, It should redirect the user to the dashboard or a home screen. is there a way to achieve it via Salesforce SDK?
The user should be able to log in to the application with the newly reset password/ create password. Is there a way to assign accesstoken to SFUsermanager it will fetch the user information needed so that we can continue using the application with login again

**Comment by brandonpage** [comment]
Hi @bhagwat8024, as described in an [identical Android issue](https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/2477) this is, unfortunately, out of the control of the Mobile SDK as it is handled by the server.
