### ISSUE TITLE
crashing with index out of range issue: isNewerThanServer

### ISSUE THREAD

**Issue by nzsrini** [forcedotcom/SalesforceMobileSDK-iOS#3657]
Please fill out the following details:

1. Version of Mobile SDK Used: '11.0.1'
2. Issue found in Native App or Hybrid App: Native App
3. OS Version:16.4
4. Device: Simulator
5. Steps to reproduce:
Configuration: "mergeMode":"LEAVE_IF_CHANGED"
 if (options.mergeMode == SFSyncStateMergeModeOverwrite) {
        NSMutableDictionary* result = [NSMutableDictionary new];
        
        for (NSDictionary* record in records) {
            result[record[SOUP_ENTRY_ID]] = @YES;
        }
        
        resultBlock(result);
    } else {
        **[target areNewerThanServer:syncManager records:records resultBlock:resultBlock];**
    }

If the case is  records are empty , Then the application is crashing with index out of range issue:

(void)isNewerThanServer:(SFMobileSyncSyncManager *)syncManager
                   records:(NSArray<NSDictionary*>*)records
                     index:(NSUInteger)I
                    result:(NSMutableDictionary*)result
              resultBlock:(SFSyncUpRecordsNewerThanServerBlock)resultBlock
{
    **NSDictionary* record = records[i];**

Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array'
When The application is trying to synch and when we do not have any records to sync, The records array is empty and it is causing index out range exception.

7. Actual behavior:  it should handle index out of range gracefully
8. Expected Behavior:
9. Error Log:

**Comment by wmathurin** [comment]
We will take a look. Thank you for reporting the issue.

**Comment by wmathurin** [comment]
Fixing here: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3661
