### ISSUE TITLE
Can't add google recaptcha

### ISSUE THREAD

**Issue by sheryDiplomat** [forcedotcom/SalesforceMobileSDK-iOS#3658]
we have custom community login page in IOS,
we need to add recaptcha, but we get please update browser.
(works fine in android)
is there any solution to this?

![Greenshot 2023-10-25 20 17 55](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/assets/81548020/ae484858-1e04-4bf9-a65b-3e5c2a93596d)

**Comment by wmathurin** [comment]
What version of the Mobile SDK are you using?
What version of iOS are you running your application on?
Are you using regular authentication or [advanced authentication](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/auth_advanced_using.htm)?

**Comment by sheryDiplomat** [comment]
Mobile SDK version is 11.0.1 
iphone version 16.7.1 (but happens in all versions)
regular authentication

**Comment by sheryDiplomat** [comment]
Hi,
Any ideas?

**Comment by wmathurin** [comment]
Could you try with [advanced authentication](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/auth_advanced_using.htm) ? I looks like the embedded web view is not supported by ReCaptcha.

**Comment by wmathurin** [comment]
Closing for lack of response to our last suggestion/question.
