### ISSUE TITLE
Missing permissions for IDP Flow 

### ISSUE THREAD

**Issue by ghamuirev** [forcedotcom/SalesforceMobileSDK-iOS#3664]
1. Version of Mobile SDK Used: 11.0.1
2. Issue found in Native App or Hybrid App: Native iOS
3. OS Version: 17.0.1
4. Device: iPhone 15 Pro

5. Steps to reproduce:
Setup one connected app as the IDprovider, and another as a client.
On request to use the provider for authentication we receive an error in the IDP flow.
On the response from 'idpRefreshTokenAndAuthenticate' function (line 961 in the SFUserAccountManager class) is an error caught within the failureBlock:
message: limits resource is not enabled 
errorCode: API_DISABLED_FOR_ORG

Upon searching for a solution for the issue I found that in the system permissions for the user the following fields must be enabled:
API Enabled 
View Roles and Role Hierarchy
View Setup and Configuration 

For some users we are able to enable the View Roles and View Setup fields, and IDP flow works as intended. However, for community users we are unable to access these fields, and so are unable to continue with the IDP authentication. 

I am curious as to why we need the View Roles and Setup fields enabled for the IDP flow to work. In our case with the community user, is there another way to potentially continue the flow without enabling these fields?

6. Actual behavior:
Receive the 'limits resource is not enabled':'API_DISABLED_FOR_ORG' error, stopping the refresh token/authentication flow

7. Expected Behavior:
Continue IDP flow and authenticate user

8. Error Log:
[0]	__NSDictionaryM *	2 key/value pairs	0x000060000030c180
[0]	(null)	@"message" : @"limits resource is not enabled"	
[1]	(null)	@"errorCode" : @"API_DISABLED_FOR_ORG"

**Comment by wmathurin** [comment]
Thanks for reporting we will take a look.

**Comment by wmathurin** [comment]
The fix is now in dev see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3665.
It will be in our next version of the Mobile SDK (11.1)
