### ISSUE TITLE
Unable to log in with SSO from outside the IP restrictions of [Apply IP restrictions and relax refresh tokens] in 11.1.0

### ISSUE THREAD

**Issue by ryukooo** [forcedotcom/SalesforceMobileSDK-iOS#3673]
Please fill out the following details:

1. Version of Mobile SDK Used: 
11.1.0
2. Issue found in Native App or Hybrid App:
Native App
3. OS Version:
16.0
4. Device:
iPhone 15
5. Steps to reproduce:
  1. Set the IP address in the profile.
  2. Set "IP Relaxation"  "Relax IP restrictions for activated devices"  in the connected application settings
  3.Log in to Salesforce with SSO authentication
  4. Even if I enter the authentication token and allow access, I am not logged in.
  5.If you look at your login history, it will be a restricted IP address.

*You can log in to the Salesforce app.
You can also log in with SDK10.2.0.
6. Actual behavior:
Can't log in
7. Expected Behavior:
Must be able to log in using the Salesforce app or SDK10.2.0.
8. Error Log:
![IMG_0178](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/assets/28751562/59552cab-a88b-4b28-928f-ce44c42b82c0)

**Comment by wmathurin** [comment]
IP restriction enforcement are completely done server side and the Mobile SDK has no controls over them.
I recommend you post your question somewhere on https://salesforce.stackexchange.com/.
