### ISSUE TITLE
When opening any image url link, getting Failed to load resource: Too many http redirects

### ISSUE THREAD

**Issue by meta-krishna-meghwal** [forcedotcom/SalesforceMobileSDK-iOS#3685]
Please fill out the following details:

URL that we are loading : https://***.sandbox.my.salesforce.com/servlet/rtaImage?eid=*******&feoid=*****&refid=****
1. Version of Mobile SDK Used: 10.2
2. Issue found in Native App or Hybrid App: Hybrid 
3. OS Version: iOS 17.3
4. Device: I-Phone XS Max
5. Steps to reproduce:
     Create a salesforce mobile SDK hybrid app for ios platform with version 10.2
     Login in the app, first time after installing the app
     Navigate to any screens which shows images
     
7. Actual behaviour:
     The images are not downloaded
9. Expected behaviour:
     Images should be downloaded correctly
11. Error Log:
     Getting the error: Failed to load resource: Too many http redirects
<img width="1440" alt="Screenshot 2024-02-19 at 12 24 47" src="https://github.com/forcedotcom/SalesforceMobileSDK-iOS/assets/79202243/0a4c1bb1-9572-43e5-9168-5f020f2b7c2a">

**Comment by wmathurin** [comment]
Could you try with the most recent version of Mobile SDK (12.0) to see if the issue still exists?

**Comment by wmathurin** [comment]
Closing for lack of response from customer. Please open a new issue if the problem still exists (in the latest version of Mobile SDK).
