### ISSUE TITLE
Biometric Login not working

### ISSUE THREAD

**Issue by iosdroid** [forcedotcom/SalesforceMobileSDK-iOS#3691]
Please fill out the following details:

1. Version of Mobile SDK Used: 11.1.0
2. Issue found in Native App or Hybrid App:Naive
3. OS Version:iOS 17
4. Device:iPad
5. Steps to reproduce:we are enable the custom attribute in our connected app settings in salesforce and configure the code in as per the document mentioned [Biometric Login](https://developer.salesforce.com/docs/platform/mobile-sdk/guide/biometric-auth.html)
6. Actual behavior: After click enable nothing happen
7. Expected Behavior:it should the faceid button as per sdk config
8. Error Log:
Error Domain=com.salesforce.security.keychainException Code=-25300 "The specified item could not be found in the keychain." UserInfo={com.salesforce.security.keychainException.errorCode=-25300, NSLocalizedDescription=The specified item could not be found in the keychain.}

**Comment by wmathurin** [comment]
Could you try again with the latest version of Mobile SDK 12.0?

**Comment by iosdroid** [comment]
I will check and confirm

**Comment by kqisalesforce** [comment]
Hello @iosdroid just wanted to follow-up if this is still an issue?

**Comment by wmathurin** [comment]
Closing issue - no response from customer.
