### ISSUE TITLE
v11.1.0 - Successful login but gets an error popup, SFOAuthSessionRefresher completeWithError: Code=668

### ISSUE THREAD

**Issue by patilvivekw** [forcedotcom/SalesforceMobileSDK-iOS#3692]
Please fill out the following details:

1. Version of Mobile SDK Used: v11.1.0
2. Issue found in Native App or Hybrid App: Native iOS App
3. OS Version: iOS 17.2
4. Device: iPhone 15 Pro (Simulator) & iPhone 13 (physical)
5. Steps to reproduce: 

        1. During the initialization flow, disable hybrid authentication
        2. MobileSyncSDKManager.shared.useHybridAuthentication = false
        3. go through normal login flow with response_type=code
        4. Authentication succeeds (we also receive accessToken), but it ends up throwing a system error [PFA Screenshot of the same
![Simulator Screenshot - iPhone 15 Pro - 2024-03-18 at 18 03 19](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/assets/67308754/2206b374-5048-4f90-bb2c-0a8a67a895fc)
]

7. Actual behavior: The user sees a server error popup
8. Expected Behavior: The user should be taken to the homepage with no error messages
9. Error Log:

CLASS: SFOAuthCoordinator loadWebViewWithUrlString:cookie: Loading web view for 'SFOAuthTypeWebServer' auth flow, with URL: https://[ourdomain].sandbox.my.site.com/services/oauth2/authorize?client_id=[CLIENT_ID]&redirect_uri=myapp://authentication/success&display=touch&device_id=[DEVICE_ID]&response_type=code&code_challenge=BxxfNECJDigkvr6wTeheAVGHre9MEbTrHDdtr8LkIZE&scope=web%20api%20refresh_token
CLASS: SFSDKWebViewStateManager [SFSDKWebViewStateManager sharedProcessPool]: No process pool exists.  Creating new instance.
CLASS: SFOAuthCoordinator webView:didStartProvisionalNavigation: host=[ourdomain].sandbox.my.site.com : path=/services/oauth2/authorize
CLASS: SFOAuthCoordinator webView:didStartProvisionalNavigation: host=[ourdomain].sandbox.my.site.com : path=/s/login

--->Entered username password credentials along with MFA verification<----

CLASS: SFOAuthCoordinator webView:didStartProvisionalNavigation: host=[ourdomain].sandbox.my.site.com : path=/secur/frontdoor.jsp
CLASS: SFOAuthCoordinator webView:didStartProvisionalNavigation: host=[ourdomain].sandbox.my.site.com : path=/setup/secur/RemoteAccessAuthorizationPage.apexp
-[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:]  perform input operation requires a valid sessionID
-[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:]  perform input operation requires a valid sessionID
CLASS: SFOAuthCoordinator handleWebServerResponse: Received web server response.  Beginning token exchange.
CLASS: SFOAuthCoordinator beginTokenEndpointFlow: Initiating authorization code flow.
CLASS: SFIdentityCoordinator SFIdentityCoordinator:Starting identity request at https://test.salesforce.com/id/[ORGID]/[USERID]
CLASS: SFIdentityCoordinator sendRequest: Identity request failed due to expired credentials.  Attempting to refresh credentials.
CLASS: SFSDKOAuth2 accessTokenForRefresh:completion:: Initiating refresh token flow.
CLASS: SFJsonUtils WARNING error parsing json: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set. around line 2, column 0." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set. around line 2, column 0., NSJSONSerializationErrorIndex=2}
CLASS: SFSDKOAuth2 handleTokenEndpointResponse:request:data:urlResponse:: JSON parse error: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set. around line 2, column 0." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set. around line 2, column 0., NSJSONSerializationErrorIndex=2}
**CLASS: SFOAuthSessionRefresher completeWithError: Refresh failed with error: Error Domain=com.salesforce.OAuth.ErrorDomain Code=668** "JSON text did not start with array or object and option to allow fragments not set. around line 2, column 0." UserInfo={NSJSONSerializationErrorIndex=2, response_data=
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html><head><title>Down For Maintenance</title><script src="/static/111213/js/perf/stub.js" type="text/javascript"></script><link class="user"
.
.
.
[Our System maintenance page html]
```

**Comment by jeevanandhamr** [comment]
Hi Team

We are also facing this issue while using webserver flow (default from 11.0.0 SDK) instead of user-agent flow. We have also made useHybridAuthentication = false and response_type = code.

In Salesforce connected app settings: (as is from the beginning)

- Require Secret for Web Server Flow is deselected as specified in https://developer.salesforce.com/docs/platform/mobile-sdk/guide/oauth-web-server-flow.html

The following two flags are also deselected:

- Require Proof Key for Code Exchange (PKCE) Extension for Supported Authorization Flows	
- Require Secret for Refresh Token Flow

While analysing we found that it is happening when we pass code_verifier parameter in accesstoken request.

```
Class: SFSDKOAuth2.m, Method: accessTokenForApprovalCode, Line: 200
[params appendFormat:@"&%@=%@", kSFOAuthCodeVerifierParamName, endpointReq.codeVerifier];
```
We know that it is not recommended to bypass above parameter due to security reasons.

Could you please help us know to fix this issue whether we need to make some configuration changes in salesforce settings or making code changes in the app or waiting for new SDK upgrade with this issue fix?

**Comment by brandonpage** [comment]
Hi @patilvivekw and @jeevanandhamr, what is the reason for not wanting PKCE?  

It is strongly recommended by our auth and security teams so we are requiring it with the Web Server flow.  As I understand it there are no downside to using PKCE and no additional work on your end other that selecting the option in the connected app.

**Comment by prasannag** [comment]
Hi @brandonpage, thanks for taking a look at this. I work with @patilvivekw who is the OP and it looks like @jeevanandhamr is having the same issue independently. 

We would like to use PKCE, but we are hitting the issue @patilvivekw has posted. 

Are there other customers who are currently successfully using the Web Server flow using the SDK?

**Comment by jeevanandhamr** [comment]
> Hi @patilvivekw and @jeevanandhamr, what is the reason for not wanting PKCE?
> 
> It is strongly recommended by our auth and security teams so we are requiring it with the Web Server flow. As I understand it there are no downside to using PKCE and no additional work on your end other that selecting the option in the connected app.

Hi @brandonpage - No specific reason for disabling PKCE in our connected app. It was disabled before the time we took over this project. I have already tried enabling that flag and it does not resolve our issue as mentioned by @prasannag.

**Comment by patilvivekw** [comment]
Hey @brandonpage ,

We tried several options and combinations to get past the Server error (668) while trying to log into Salesforce iOS SDK.
Below is the list of things we have tried with no luck.

1.	Selecting and deselecting PKCE – Our internal teams also recommend enabling this setting in SF connected app which we did and we saw the (668) error regardless of this setting.
2.	Require Secret for Web Server Flow – deselected
![Salesforce PKCE Enabled](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/assets/67308754/618c7bdd-72c1-4b24-8f10-b5c882a63139)

3.	We have this “**Issue JSON Web Token (JWT)-based access tokens for named users**” setting enabled – we referred this link for it - https://help.salesforce.com/s/articleView?id=sf.connected_app_enable_jwt.htm&type=5
4.	**Note that with the above setting enabled, we are able to see the longer OAuth access token in /login response** [PFA screenshot of the same], 
![SF login with webServer flow](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/assets/67308754/90349027-a387-4ce2-b51c-751577757841)

but after this step the SDK tries to connect to the [https://test.salesforce.com/id/[ORGID]/[USERID]
(https://test.salesforce.com/id/%5bORGID%5d/%5bUSERID)] endpoint but is unable to pass the already received accessToken in headers and hence we see the 403 response for this endpoint call and later on the UI we see the Server error (668).
5.	With the “Issue JSON Web Token (JWT)-based access tokens for named users” disabled and using web server flow we are able to successfully login and received a smaller token like below one
**00D4Y00000092PL!AQEAQDMDqMkpkDEF.9IEx2CVuOXFxuPEp35_Tz3DKNFnX_1<some more chars>**
but our understanding is that this is not a secure token as the normal longer OAuth token we received earlier (refer screenshot)

**Finally, we want to understand what we can change or any additional setting/configuration we are missing which will enable the SDK to return the longer OAuth token ?**

**Comment by brandonpage** [comment]
Okay, apologies for assuming this was one team -- but it sounds like both are having the same issue.  

Since we rolled out the Web Sever flow we have had quite a few customers reach out about auth issues but so far 100% of them were resolved by the customer deselecting "Require Secret for Web Server Flow" in their connected apps.  Since you have clearly done that this appears to be a real issue we will try to resolve right away.

**Comment by prasannag** [comment]
Thanks @brandonpage. While we wait, I want to validate something hopefully straightforward. 

Does the Salesforce Mobile SDK for iOS support the use of JWT insteaf of opaque tokens when using the connected app?

**Comment by brandonpage** [comment]
Closing this issue as it was entirely resolved on the server.

@prasannag Sorry for the super slow response, I lost track of this thread after conversing more regularly about this issue on Trailhead.  Today we support as much as the server does.  Client side we don't particularly care what kind of token the server provides as long as we can use it to make REST calls and get a new one when it expires.  If there are server side developments in the future that aren't automatically supported we will be sure to cal that out.
