### ISSUE TITLE
App crash while logout in IOS

### ISSUE THREAD

**Issue by ashish-kumar1994** [forcedotcom/SalesforceMobileSDK-iOS#3700]
Please fill out the following details:

1. Version of Mobile SDK Used: 10.2.0
2. Issue found in Native App or Hybrid App: React Native
3. OS Version: IOS
4. Device: IPhone 14
5. Steps to reproduce: When is logout the app that time error is caused
6. Actual behavior: App crash
7. Expected Behavior: User should be logout successfully and showing the login screen
8. Error Log:
 
 SFSmartStoreReactBridge.querySoup failed: {"message":"querySoup failed: no store found"}
 ERROR  {"message": "querySoup failed: no store found"

**Comment by wmathurin** [comment]
This issue has been fixed in dev. See https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/351
It will be in our next release (Mobile SDK 12.0).
