### ISSUE TITLE
iOS SFDCOAuthLoginHost not supporting multiple servers in PList

### ISSUE THREAD

**Issue by mahipalsingh-syt** [forcedotcom/SalesforceMobileSDK-iOS#3704]
Please fill out the following details:

1. Version of Mobile SDK Used: 11
2. Issue found in Native App or Hybrid App: Hybrid
3. OS Version: iOS
4. Device: iPhone 
5. Steps to reproduce: try to add multiple hosts in PList under SFDCOAuthLoginHost
6. Actual behavior: it should support multiple hosts same as Android <servers>
7. Expected Behavior: in iOS it should support multiple host with host uri and name in form of dictionary 
8. Error Log:

Android support Multiple Servers : 
https://developer.salesforce.com/docs/platform/mobile-sdk/guide/communities-login-endpoint.html

But in iOS its support only one host. 
https://developer.salesforce.com/docs/platform/mobile-sdk/guide/oauth-custom-login-host-ios.html

**Comment by bbirman** [comment]
One other option is to add hosts programmatically so that you can do more than one, example snippet:
```
SFSDKLoginHost *host = [SFSDKLoginHost hostWithName:@"My Host" host:@"login.salesforce.com" deletable:YES];
[[SFSDKLoginHostStorage sharedInstance] addLoginHost:host]; 
```

**Comment by wmathurin** [comment]
Closing issue - we provided a workaround.
