### ISSUE TITLE
Server Error Can't connect to the server: Unexpected HTTP response code from the identity service: 404. only on iOS

### ISSUE THREAD

**Issue by alexdemesa22** [forcedotcom/SalesforceMobileSDK-iOS#3709]
I would like to share an issue regarding the login process using the Salesforce SDK on iOS (latest version of the operating system). Currently, without using a VPN, I am unable to proceed with the app login and receive the following error message: "Server Error: Can't connect to the server. Unexpected HTTP response code from the identity service: 404."

Below is the response from Salesforce when debugging using Xcode (without using VPN):

<img width="993" alt="Screenshot 2024-04-25 at 6 48 07 PM" src="https://github.com/forcedotcom/SalesforceMobileSDK-iOS/assets/58238761/5393d955-088b-406a-baff-1ed725ecee54">

We are using SalesforceSDK version 8.4.x and the latest version of Xcode. Interestingly, when using a VPN and connecting to America, the login is successful.

Do you have any suggestions or solutions that you could share with us?

Thank you

Please fill out the following details:

1. Version of Mobile SDK Used: 8.4.x
2. Issue found in Native App or Hybrid App: Native App (iOS) using ionic 5 framework
3. OS Version:17.4.1
4. Device:Iphone 11
5. Steps to reproduce:
   - Login using the app integrated on Salesforce SDK iOS
   - Without using VPN the app cannot proceed to the home page instead it shows an error Server error 404 identity service
7. Actual behavior:  cannot proceed to the app due to VPN issues
8. Expected Behavior:to be able to proceed to the app
9. Error Log:

**Comment by wmathurin** [comment]
Mobile SDK did not release a 8.4 version. Could you double check the version of the Mobile SDK you are using?

**Comment by wmathurin** [comment]
Is your org on gov cloud?
This looks like a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/361

**Comment by alexdemesa22** [comment]
Hi @wmathurin, the issue is now resolved on the gov cloud. The login flow is working as expected on iOS, and the SDK version is 8.3.x, not 8.4.x. Thanks, and I'll close this ticket.

Here's the link to the related issue for reference: (https://issues.salesforce.com/issue/a028c00000z01vmAAA/unexpected-http-response-code-from-the-identity-service-404-after-ios-app-login-for-government-orgs-on-ios-version-1731)"
