### ISSUE TITLE
403 on api calles to IGoDigital.com

### ISSUE THREAD

**Issue by keyvanygh** [forcedotcom/SalesforceMobileSDK-iOS#3717]
Our analytics tool shows considerable number of api calls to "IGoDigital.com" which I believe is part of Salesforce SDK, can you please help me resolve this issue? should we update SDK version?
<img width="1390" alt="Screenshot 2024-05-28 at 3 24 19 PM" src="https://github.com/forcedotcom/SalesforceMobileSDK-iOS/assets/24761725/576309e8-28fb-4a37-a489-6cd5187fbcec">

1. Version of Mobile SDK Used: 8.1.2
2. Issue found in Native App or Hybrid App: Native iOS
6. Actual behavior: 100% error on api call
7. Expected Behavior: 0% error
8. Error Log:
<img width="1126" alt="Screenshot 2024-05-28 at 3 27 02 PM" src="https://github.com/forcedotcom/SalesforceMobileSDK-iOS/assets/24761725/160ada6b-7b80-43d6-a915-c6234daf4710">

**Comment by wmathurin** [comment]
There is no Mobile SDK 8.1.2.
I think this might be an issue for the Salesforce ServiceSDK.
That is a different product. Please open an investigation with Salesforce.
