### ISSUE TITLE
App setup with SalesforceMobileSDK 12.1 is crashing on installation 

### ISSUE THREAD

**Issue by hemantsumanmetacube** [forcedotcom/SalesforceMobileSDK-iOS#3720]
I have created a new ios app using forcehybrid and when i try to run it, after installation it crashes 

When I build the app it throws error: 

`Multiple commands produce '/Users/username/Library/Developer/Xcode/DerivedData/sample-grltipsmwmybdhhheyyvvgdgywxw/Build/Products/Debug-iphoneos/sample.app/Assets.car'`

I am able to resolve this error by removing Assets.xcassets from `Copy bundle resources` section.
Same type of errror is thrown for `Image.xcassets` and `SalesforceSDKAssets.xcassets`

**Comment by wmathurin** [comment]
You probably meant 12.0.1?
What version of Xcode are you using?

**Comment by hemantsumanmetacube** [comment]
Yes, I am using SalesforceMobileSDK Version 12.0.1 and Xcode version 15.2

**Comment by wmathurin** [comment]
We just released Mobile SDK 12.1, could you try again and see if the issue still exists?

**Comment by wmathurin** [comment]
Closing issue. We have not heard from customer in a long time.
Please open a new issue if you are still having the same problem and are using the latest Mobile SDK.
