### ISSUE TITLE
App generated using SalesforceMobileSDK 12.1 is not installing on iOS 15, Can we downgrade the deployment target from iOS 16?

### ISSUE THREAD

**Issue by hemantsumanmetacube** [forcedotcom/SalesforceMobileSDK-iOS#3722]
I created an ios app using forcehybrid, and when i am trying to install it in iOS 15 device, it is not installing.

I checked the minimum deployment version and it is ios 16, Can we downgrade it?

**Comment by brandonpage** [comment]
Use Mobile SDK 11.1.  forcehybrid is also versioned the same way as the SDK, will use the correlated version of the SDK and generate a working starting app for that version.
