### ISSUE TITLE
Need an Option to customize ScreenLockUIView

### ISSUE THREAD

**Issue by StarrySite** [forcedotcom/SalesforceMobileSDK-iOS#3723]
Please fill out the following details:

1. Version of Mobile SDK Used: 11.1.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 16+
4. Device: iPhone
5. Steps to reproduce: When we cancel the biometric authentication, ScreenLockUIView will appear.
6. Actual behavior: Default screen appears, unable to customize as it is not exposed outside of SDK 
7. Expected Behavior: Need option to customize ScreenLockUIView based on our app theme.
8. Error Log:

I am able to notice that there are already 2 issues (https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3450 & https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3551) raised expecting the same option in the SDK, but they were closed by saying "We have just released Mobile SDK 11.0 which contains enhancements in that area (https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3586). It's a different user experience, the unlock sheet pops up over the login screen (which has always been customizable)."

The option we are expecting is different from the solution provided as part of (https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3586). Could you please provide the way to customize ScreenLockUIView's background color, image, button styles etc?

**Comment by brandonpage** [comment]
@StarrySite Thank you for expressing interest in issue, direct customer feedback like this is the best way for us to know what work to prioritize.  We have internal work items to track this for both Android and iOS.  I cannot promise when this will be delivered but it is on our backlog.
