### ISSUE TITLE
Behaviour Difference in Sandbox and production regarding refresh token

### ISSUE THREAD

**Issue by bhagwat8024** [forcedotcom/SalesforceMobileSDK-iOS#3731]
Please fill out the following details:
 
1. Version of Mobile SDK Used: 11.0.0
2. Issue found in Native App or Hybrid App:Native App
3. OS Version:Any
4. Device:Any
5. Issue: 
We are experiencing an issue where hitting the refresh token API simultaneously results in failed error responses in the production environment, whereas the same API calls code do not fail in the lower sandbox environment. This discrepancy in behavior between the two environments needs to be addressed. Please let us know is there any configuration which we need to enable/disable to have exactly same behaviour in each org
 
6.Steps to Reproduce:
 
Make multiple requests to the refresh token API in the production environment.
Observe the failed error responses: "Failed: Token request is already being processed."
Perform the same steps in the lower sandbox environment all the requests of refresh refresh token succeed without any errors.
 
7.Expected Behavior:
The refresh token API should behave consistently across all environments, allowing multiple requests without resulting in failed error responses.

@brandonpage Appreciate your help here.

**Comment by brandonpage** [comment]
We do not handle Sandbox and differently than production.  If you are experiencing differences between the two you should bring that to the attention of the appropriate team on the server.

**Comment by brandonpage** [comment]
[The server only handles one token refresh at a time per client](https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_refresh_token_flow.htm&type=5).  Are you purposefully hitting the refresh endpoint multiple times simultaneously?  Or are you saying we are doing that for your production environment but not sandbox?

**Comment by bhagwat8024** [comment]
@brandonpage  as we were not aware about this scenario at code level when we implemented refresh token, this behavior came into existence.  since we know this behavior now we are trying to replicate is lower stanbox which is not behaving same as production. please suggest if any config changes need to achieve same behavior in lower sandbox.

**Comment by brandonpage** [comment]
@bhagwat8024 Have you resolved the issue?  This seems like either an issue in your production/sandbox configs or a problem with on the server itself.  I don't see how this could be a Mobile SDK issue but if you can show me otherwise I will reopen.

**Comment by bhagwat8024** [comment]
@brandonpage  yes we solved it by calling refresh token api once at a time
