### ISSUE TITLE
Error when archiving: Multiple commands produce `SQLCipher.bundle`

### ISSUE THREAD

**Issue by MarkHinojosa** [forcedotcom/SalesforceMobileSDK-iOS#3736]
Please fill out the following details:
1. Version of Mobile SDK Used: 11.0.1
2. Issue found in Native App or Hybrid App: React Native App
3. OS Version: MacOS 13.6
4. Device: Iphone
5. Steps to reproduce: Forcereact create -> build archive
6. Actual behavior: archive fails with Multiple Commands Produce error involving FMDB-SQLCipher and SQLCipher-SQLCipher PODS
7. Expected Behavior: Archive Succeeds 
8. Error Log: Multiple commands produce '/Users/user/Library/Developer/Xcode/DerivedData/ApplicationNameAndID/Build/Intermediates.noindex/ArchiveIntermediates/ApplicationName/IntermediateBuildFilesPath/uninstalledProducts/iphoneos/SQLCipher.bundle` 

Xcode 15.1

Didn't post this in the RN version because it looks like it is a collision of the dependencies in this project. 

The app will run but fails when archiving. 12.1.0 is seemingly not yet available when using the forcereact create command. 

I'd appreciate any help with this. 
Thanks!

**Comment by wmathurin** [comment]
Could you try with the latest version of Mobile SDK (12.0.1) ?

**Comment by MarkHinojosa** [comment]
If I manually set salesforcemobileSDK-iOS.git#12.0.1, it gives me an error:
CocoaPods could not find compatible versions for pod "SalesforceSDKCommon" :
in Podfile: 
SalesForceReact (from `../node_modules/react-native-force`) was resolved to 11.1.0, which depends on SalesforceReact/SalesforceReact (= 11.1.0) was resolved to 11.1.0, which depends on SalesforceSDKCommon (~> 11.1.0)

SalesforceSDKCommon (from `../mobile_sdk/SalesforceMobileSDK-iOS`)

**Comment by wmathurin** [comment]
You need to also point to 12.0.1 in your package.json like we do in the template: https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/v12.0.1/ReactNativeTemplate/package.json#L19

**Comment by MarkHinojosa** [comment]
Success! Thank you greatly!

**Comment by mhinojosaCort** [comment]
Hello, same person different account. (This is my work account and will try to use this one from here on).

Anyway, your suggestion on using 12.0.1 did resolve the archiving issue however, now I get a runtime error in the main.m file.
This is the section of code that is being highlighted by xcode: 
       int retVal = UIApplicationMain(argc, argv, @"SFApplication", @"AppDelegate");

this is the error:
   Thread 1: "Unable to instantiate the UIApplication subclass instance. No class named SFApplication is loaded."

**Comment by wmathurin** [comment]
We do not have a SFApplication class anymore. We changed the template accordingly - if you did no re-run forceios, you could do the same change in your project. See https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/391
