### ISSUE TITLE
AVPlayer "Server Not Properly Configured" Error in Production

### ISSUE THREAD

**Issue by bhagwat8024** [forcedotcom/SalesforceMobileSDK-iOS#3739]
1. Version of Mobile SDK Used: 11.0.0
  2. Issue found in Native App or Hybrid App:Native
  3. OS Version:Any
  4. Device:Any
  5. Description:We are using AVPlayer for streaming videos in our iOS application. The streaming works fine in lower sandbox environment, but we are encountering a "server not properly configured" error in the production environment.
  6. Steps to Reproduce:Configure AVPlayer with a video URL from the production server.Attempt to play the video.
  7. Expected Behavior:The video should stream successfully as it does in the sandbox environment.
  8. Actual Behavior:AVPlayer fails to stream the video and reports a "server not properly configured" error.
  Error Domain=AVFoundationErrorDomain Code=-11850 "Operation Stopped" UserInfo={NSLocalizedFailureReason=The server is not correctly configured., NSLocalizedDescription=Operation Stopped, NSUnderlyingError=0x600000ecc960 {Error Domain=NSOSStatusErrorDomain Code=-12939 "(null)"}}

  11.code snippet:
   let urlString = Config.communityURL.absoluteString + APIEndPoints.downloadDocument(id: videoId).rawValue
          guard let url = URL(string: urlString) else {
              self.init()
              return
          }
          let headers = Config.videoAuthHeader()
          let asset = AVURLAsset(url: url, options: [Constants.assetHeaderKey: headers])
          let playerItem = AVPlayerItem(asset: asset)
          self.init(playerItem: playerItem)
  
  **please let us know if there is any type of configuration changes needed on platform of salesforce backend side.**
@wmathurin appreciate your help here.

**Comment by bbirman** [comment]
@bhagwat8024 those endpoints are outside Mobile SDK's scope, please reach out to Salesforce support
