### ISSUE TITLE
Mobile SDK 11.1.0 Xcode Archive build is failing - error Multiple Commands Produce

### ISSUE THREAD

**Issue by YanTylets** [forcedotcom/SalesforceMobileSDK-iOS#3743]
Please fill out the following details:

1. Version of Mobile SDK Used:  11.1.0
2. Issue found in Native App or Hybrid App: React Native app
3. OS Version: Sonoma (14.1.1), Xcode version 15.4, react native version 0.70.14
4. Device: Any
5. Steps to reproduce: Make a build with Archive command in Xcode
6. Actual behavior: Build fails with error: 
Multiple commands produce '/Users/lomraydev/Library/Developer/Xcode/DerivedData/D2App-gujztpjlmsjxmadwmklhyxxdszcd/Build/Intermediates.noindex/ArchiveIntermediates/D2App/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SQLCipher.bundle'
Target 'FMDB-SQLCipher' (project 'Pods') has create directory command with output '/Users/lomraydev/Library/Developer/Xcode/DerivedData/D2App-gujztpjlmsjxmadwmklhyxxdszcd/Build/Intermediates.noindex/ArchiveIntermediates/D2App/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SQLCipher.bundle'
Target 'SQLCipher-SQLCipher' (project 'Pods') has create directory command with output '/Users/lomraydev/Library/Developer/Xcode/DerivedData/D2App-gujztpjlmsjxmadwmklhyxxdszcd/Build/Intermediates.noindex/ArchiveIntermediates/D2App/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SQLCipher.bundle'
7. Expected Behavior: Successful build
8. Error Log:
[Build D2App_2024-07-23T14-19-46.txt](https://github.com/user-attachments/files/16361605/Build.D2App_2024-07-23T14-19-46.txt)

**Comment by wmathurin** [comment]
Could you update to the latest version of Mobile SDK (12.0.1) and see if the issue still exists?

**Comment by YanTylets** [comment]
@wmathurin With version 12.0.1 this error does disappear, you are right. But the problem is that for version 12 the minimum supported iOS version is 16. And this is not suitable for us, because many users have devices that do not support iOS version more than 15. So I would like to find a solution to this error on SDK 11.1.0.

**Comment by wmathurin** [comment]
Unfortunately we do no have the bandwidth to patch old version of Mobile SDK or support older versions of iOS.

**Comment by wmathurin** [comment]
Closing as Mobile SDK 11 is no longer supported.
