### ISSUE TITLE
Javascript Static Resource MIME Type is not returning correctly and it is throwing error with iOS18

### ISSUE THREAD

**Issue by hemantsumanmetacube** [forcedotcom/SalesforceMobileSDK-iOS#3750]
it's throwing the below error:

Refused to execute https://*.my.salesforce.com/resource/1722959303321/T1C_Base__DealsLib/src/ace-lib.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.

SDK Version: 12.0.1
iOS Version: 18.0

**Comment by wmathurin** [comment]
Can you give us more context?
When is the error above happening? Is it during login or is in afterwards? Is your application native or hybrid? What version of Mobile SDK are you using?

**Comment by hemantsumanmetacube** [comment]
We are using MobileSDK Version : 12.0.1, the app is hybrid local app generated using forcehybrid package and, the error is happening when we are trying to load a static resources after login in the app. and it's specific to iOS18 Beta.

**Comment by wmathurin** [comment]
We have not yet tested against iOS 18 beta. We plan to do that for our next minor release (12.2).

**Comment by hemantsumanmetacube** [comment]
Is there any timeline for 12.2 release, what would be the release date?

**Comment by wmathurin** [comment]
The plan is October #safeharbor.
Fixes to issues to uncover will be in dev ahead of the release date.

**Comment by wmathurin** [comment]
12.2 has now been released (and iOS18 is out of beta). Are you still seeing the issue?

**Comment by wmathurin** [comment]
Closing issue - we have not heard from customer in a long time.
Please open new issue if you are still having the problem and are running the latest Mobile SDK.
