### ISSUE TITLE
12.0.1 - Crash on devices running iOS 15

### ISSUE THREAD

**Issue by mattlacey** [forcedotcom/SalesforceMobileSDK-iOS#3755]
We've just pushed out a new build of our app, and one thing it includes is an update to 12.0.1. We've hard reports of crashes from some users running iOS 15 to say the app won't open. I can see two devices with crashes in Xcode but don't get a crash stack, and I don't have a device myself I can test with. I have tested on a Simulator and got the log below, it appears as though something in the SDK is dynamically referencing something not available in iOS 15. In the simulator I'm running iOS 15.0 but users are on the latest 15 build which is 15.8.3

I could push out a new version with an older SDK, followed by a another new version with 12.0.1 and a min target of 16.0 but want to see if there's an easier fix that will cause less hassle for our users.

Please fill out the following details:

1. Version of Mobile SDK Used: 12.0.1
2. Issue found in Native App or Hybrid App: Native (technically hybrid but our own wrapper - we're not even getting to the hybrid part) 
3. OS Version: iOS 15.x - confirmed 15.8.3 on device. iOS 16+ working as expected
4. Device: iPad Air 
5. Steps to reproduce: Launch our app built with the SDK
6. Actual behavior: Crash 
7. Expected Behavior: No crash :) 
8. Error Log:
```
dyld[3574]: Symbol not found: _$s10Foundation11JSONDecoderC6decode_4fromxxm_AA4DataVtKSeRzlFTj
  Referenced from: /Users/matt/Library/Developer/Xcode/DerivedData/PIClienteling-hczkinmtakpycbbetkhjoijsagpe/Build/Products/Debug-iphonesimulator/SalesforceSDKCore.framework/SalesforceSDKCore
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 15.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation
Message from debugger: Terminated due to signal 6
```

**Comment by mattlacey** [comment]
@wmathurin Sorry to tag you but hoping if someone can do a quick test of the SDK code!

**Comment by mattlacey** [comment]
I just realised the release notes for 12.0.0 say the base deployment target is 16.0. Guess that'd do it 🤦 

Guess I need to downgrade!

**Comment by mattlacey** [comment]
Version 11.1.0 works without issue on iOS 15 as per the release notes. Not sure why the Swift Package Manager can't show a proper warning or block the install but there you go.

**Comment by wmathurin** [comment]
Sorry for not responding earlier.
We bump up the the base target, the deployment target and Xcode version with every major release of Mobile SDK.
- for MSDK 11, base was 16, deployment 15 and Xcode version 14.
- for MSDK 12, base is 17, deployment 16 and Xcode version 15.
- for MSDK 13, base should be 18, deployment 17 and Xcode version 16.

**Comment by mattlacey** [comment]
Yeah, somehow I'd missed it in the release notes (saying that, would be good to have this table visible somewhere, can be hard to find the older release notes) and we only test ourselves on 16+ so missed the issue this time. All good!
