### ISSUE TITLE
Blank screen after login

### ISSUE THREAD

**Issue by bhagwat8024** [forcedotcom/SalesforceMobileSDK-iOS#3757]
Please fill out the following details:

1. Version of Mobile SDK Used: 11.0.0
2. Issue found in Native App or Hybrid App: Native IOS
3. OS Version: Any
4. Device: Any 
5. Steps to Reproduce:
  - Open the app on the client's device.
  - Attempt to log in using valid credentials.
  - After completing the login process, a blank screen appears instead of redirecting to the main app screen.

6. Actual Behavior:
  - After the login flow, the app shows a blank screen, preventing the user from accessing the app.

7. Expected Behavior:
  - After login, the user should be redirected to the main screen of the app and granted access to the Salesforce services.
  
8.Additional Information:
The issue is isolated to this specific device or location. I was able to log in using the same credentials on my device without any issues, suggesting that the problem may be related to the client's specific environment (device, network, or location).

@wmathurin appreciate your help

**Comment by wmathurin** [comment]
Could you check if there are IP restrictions configured for this user profile?
See https://help.salesforce.com/s/articleView?id=sf.connected_app_continuous_ip.htm&type=5

**Comment by bhagwat8024** [comment]
@wmathurin 
we have these parameter set
![Image (6)](https://github.com/user-attachments/assets/5c8bb497-0e6b-44a1-b09b-b1f32c5c2ac4)

**Comment by wmathurin** [comment]
Could you check the device logs or the console output if you launch the application from Xcode?
Are any errors being reported there?

**Comment by bhagwat8024** [comment]
This issue is happening in client device in production , we don't have any access of any logs
@wmathurin

**Comment by depushpendra** [comment]
@wmathurin  

I would like to add steps to replicate again here:

1. The client installs the app from Appstore
2. The client opens the application
3. Clicks on Sign up button and all screens appear
4. Clicks on login button and first screen appears to allow for notifications
5. After that, the screen goes blank. User does not reach to the page to input username, We are using custom page url to load the login page

**Comment by wmathurin** [comment]
Could test your application with the latest version of Mobile SDK (12.2.)? 11.0 came out almost 1 1/2 years ago and unfortunately, we don't have the bandwidth to investigate/fix issues against old versions.

**Comment by wmathurin** [comment]
If you want to login while in lock down you will have to exclude the app and salesforce.com. Please refer to [Apple's documentation](https://support.apple.com/en-us/105120#:~:text=How%20to%20turn%20on%20Lockdown%20Mode%20on%20iPhone,On%20%26%20Restart%2C%20then%20enter%20your%20device%20passcode.).

**Comment by wmathurin** [comment]
Closing - hopefully my last comment was helpful.
