### ISSUE TITLE
iOS Application is getting crashed after Microsoft Intune SDK integration - [UIApplication session] 

### ISSUE THREAD

**Issue by shivcelumula** [forcedotcom/SalesforceMobileSDK-iOS#3763]
Please fill out the following details:

1. Version of Mobile SDK Used:  11.1.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: iOS 17.2
4. Device: Xcode Simulator 
5. Steps to reproduce: Run the app, Intune authentication happens automatically and then app crashes.
6. Actual behavior: App is crashing after Intune authentication.
7. Expected Behavior: App should show Salesforce sign-in web view, post Intune authentication
8. Error Log:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIApplication session]: unrecognized selector sent to instance 0x109e07590'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff80049b761 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff800063904 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff8004b0873 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   UIKitCore                           0x00007ff805bf2efc -[UIResponder doesNotRecognizeSelector:] + 266
	4   CoreFoundation                      0x00007ff80049fef4 ___forwarding___ + 1459
	5   CoreFoundation                      0x00007ff8004a20f8 _CF_forwarding_prep_0 + 120
	6   SalesforceSDKCore                   0x000000010942e148 -[SalesforceSDKManager handleSceneDidActivate:] + 120
	7   TruView-QA                          0x00000001070824b8 cmarDeviceComplianceEnabled + 527980
	8   TruView-QA                          0x0000000107082699 cmarDeviceComplianceEnabled + 528461
	9   TruView-QA                          0x0000000106ffc5a2 $s14IntuneMAMSwift0aB5ErrorOMa + 71042
	10  TruView-QA                          0x00000001071db9c6 cmarDeviceComplianceEnabled + 1942394
	11  TruView-QA                          0x00000001072d89fa cmarInternalIsDeviceJailbroken + 156083
	12  TruView-QA                          0x00000001072d9304 cmarInternalIsDeviceJailbroken + 158397
	13  TruView-QA                          0x00000001072e0b40 cmarInternalIsDeviceJailbroken + 189177
	14  TruView-QA                          0x00000001072d6142 cmarInternalIsDeviceJailbroken + 145659
	15  TruView-QA                          0x0000000107254771 cmarDeviceComplianceEnabled + 2437413
	16  TruView-QA                          0x000000010725358d cmarDeviceComplianceEnabled + 2432833
	17  TruView-QA                          0x00000001072544b1 cmarDeviceComplianceEnabled + 2436709
	18  TruView-QA                          0x00000001070173ab cmarDeviceComplianceEnabled + 89439
	19  TruView-QA                          0x0000000107255f8d cmarDeviceComplianceEnabled + 2443585
	20  TruView-QA                          0x00000001072d4653 cmarInternalIsDeviceJailbroken + 138764
	21  TruView-QA                          0x00000001072d0c5a cmarInternalIsDeviceJailbroken + 123923
	22  UIKitCore                           0x00007ff805ffb002 -[UITextField keyboardInput:shouldInsertText:isMarkedText:] + 214
	23  UIKitCore                           0x00007ff80594c870 -[UIKeyboardImpl(UIKitInternal) callShouldInsertText:onDelegate:] + 165
	24  UIKitCore                           0x00007ff8058f5bda -[UIKeyboardImpl callShouldInsertText:] + 129
	25  UIKitCore                           0x00007ff80591db71 -[UIKeyboardImpl addWordTerminator:afterSpace:afterAcceptingCandidate:elapsedTime:executionContext:] + 122
	26  UIKitCore                           0x00007ff80591a6c6 __49-[UIKeyboardImpl addInputEvent:executionContext:]_block_invoke + 497
	27  UIKitCore                           0x00007ff805966689 -[UIKeyboardTaskExecutionContext returnExecutionToParentWithInfo:] + 232
	28  UIKitCore                           0x00007ff80591ad5a -[UIKeyboardImpl acceptAutocorrectionForWordTerminator:executionContextPassingTIKeyboardCandidate:] + 762
	29  UIKitCore                           0x00007ff80591a155 -[UIKeyboardImpl addInputEvent:executionContext:] + 997
	30  UIKitCore                           0x00007ff805919ba8 __97-[UIKeyboardImpl addInputString:withFlags:withInputManagerHint:withInputSource:executionContext:]_block_invoke + 439
	31  UIKitCore                           0x00007ff805919933 -[UIKeyboardImpl addInputString:withFlags:withInputManagerHint:withInputSource:executionContext:] + 1313
	32  UIKitCore                           0x00007ff80591940c -[UIKeyboardImpl addInputString:withFlags:withInputManagerHint:executionContext:] + 28
	33  UIKitCore                           0x00007ff80591719a -[UIKeyboardImpl handleStringInput:withFlags:withInputManagerHint:executionContext:] + 271
	34  UIKitCore                           0x00007ff8059403ca -[UIKeyboardImpl handleKeyWithString:forKeyEvent:executionContext:] + 1165
	35  UIKitCore                           0x00007ff8058d9f41 -[UIKeyboardImpl performOperations:withTextInputSource:] + 34
	36  UIKitCore                           0x00007ff80593fa04 -[UIKeyboardImpl handleKeyEvent:executionContext:] + 4316
	37  UIKitCore                           0x00007ff80593e525 __33-[UIKeyboardImpl handleKeyEvent:]_block_invoke + 45
	38  UIKitCore                           0x00007ff8059686dc -[UIKeyboardTaskEntry execute:] + 193
	39  UIKitCore                           0x00007ff805966e66 -[UIKeyboardTaskQueue continueExecutionOnMainThread] + 376
	40  UIKitCore                           0x00007ff805967422 -[UIKeyboardTaskQueue addTask:] + 139
	41  UIKitCore                           0x00007ff80593e4b5 -[UIKeyboardImpl handleKeyEvent:] + 373
	42  CoreFoundation                      0x00007ff8004a238c __invoking___ + 140
	43  CoreFoundation                      0x00007ff80049f6b3 -[NSInvocation invoke] + 302
	44  UIKitCore                           0x00007ff8060cea4b -[UIRepeatedAction invoke] + 265
	45  UIKitCore                           0x00007ff8060ceccd -[UIRepeatedAction _preInvocationTimerFire] + 70
	46  UIKitCore                           0x00007ff805bdedfc -[UIApplication _handleKeyboardPressEvent:] + 3335
	47  UIKitCore                           0x00007ff805bc5dc9 -[UIApplication pressesBegan:withEvent:] + 403
	48  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	49  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	50  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	51  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	52  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	53  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	54  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	55  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	56  UIKitCore                           0x00007ff8061efefc -[UIScrollView pressesBegan:withEvent:] + 188
	57  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	58  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	59  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	60  UIKitCore                           0x00007ff805feac1b -[UITextField pressesBegan:withEvent:] + 377
	61  UIKitCore                           0x00007ff805c057d5 -[UIWindow _sendButtonsForEvent:] + 489
	62  UIKitCore                           0x00007ff805c06b70 -[UIWindow sendEvent:] + 4095
	63  UIKitCore                           0x00007ff805bdc010 -[UIApplication sendEvent:] + 772
	64  UIKitCore                           0x00007ff805bdd646 -[UIApplication _handleKeyUIEvent:] + 573
	65  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEvent:] + 76
	66  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEvent:] + 76
	67  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEvent:] + 76
	68  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEvent:] + 76
	69  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEvent:] + 76
	70  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEvent:] + 76
	71  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEvent:] + 76
	72  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEvent:] + 76
	73  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEvent:] + 76
	74  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEvent:] + 76
	75  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEven
libc++abi: terminating due to uncaught exception of type NSException

**It is crashing specifically on below line in SalesforceSDKManager.m file

NSString *sceneId = scene.session.persistentIdentifier;**

Please let me know if you need more informations. Thanks

**Comment by wmathurin** [comment]
Can you repro the issue with the latest version of Mobile SDK (12.1) ?

**Comment by shivcelumula** [comment]
Thank you @wmathurin , looks like upgrading the SDK version fixed the crash. But now after I provide the login credentials, I get this error, instead of successful login.

<img width="273" alt="Screenshot 2024-10-13 at 23 14 20" src="https://github.com/user-attachments/assets/0e3023e4-6fe9-48e7-8520-e4479e141cf0">


CLASS: SFSDKAuthHelper Authentication failed: invalid client credentials.
-[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:]  perform input operation requires a valid sessionID
-[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:]  perform input operation requires a valid sessionID
container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
A NULL string is not a valid group container identifier.
container_create_or_lookup_app_group_path_by_app_group_identifier: client sent invalid parameters
nw_socket_handle_socket_event [C5.1.1.1:3] Socket SO_ERROR [54: Connection reset by peer]
nw_read_request_report [C5] Receive failed with error "Connection reset by peer"

**Comment by wmathurin** [comment]
Could you tell us what version of Mobile SDK you came from and what version of Mobile SDK you are on now?

If you are on Mobile SDK 11 or above, web server flow is now the default authentication flow.
But for it to work, your connected application must be configured NOT to require secret for web server flow. If changing the connected app is not an option, you can opt out for user agent flow in your application.

For more information see https://developer.salesforce.com/docs/platform/mobile-sdk/guide/oauth-web-server-flow.html

**Comment by shivcelumula** [comment]
It was 10.0.0 previously and now we upgraded it to 12.1.1.
As per the documentation, I have disabled the web server authentication and it worked.  Thank you..!!
