### ISSUE TITLE
iOS App getting crashed, when app is going to background mode

### ISSUE THREAD

**Issue by shivcelumula** [forcedotcom/SalesforceMobileSDK-iOS#3767]
Please fill out the following details:

1. Version of Mobile SDK Used: 12.1.1
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 17.2 (Happening in all versions)
4. Device: iPhone 15 Pro Max Simulator (Also happening in all simulators and real devices)
5. Steps to reproduce: Login to app and go into background mode
6. Actual behavior: App is crashing
7. Expected Behavior: App shouldn't crash and function normal
8. Error Log: 

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIApplication session]: unrecognized selector sent to instance 0x108806c70'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff80049b761 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff800063904 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff8004b0873 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   UIKitCore                           0x00007ff805bf2efc -[UIResponder doesNotRecognizeSelector:] + 266
	4   CoreFoundation                      0x00007ff80049fef4 ___forwarding___ + 1459
	5   CoreFoundation                      0x00007ff8004a20f8 _CF_forwarding_prep_0 + 120
	6   SalesforceSDKCore                   0x00000001072d0a8f -[SalesforceSDKManager handleSceneDidEnterBackground:] + 111
	7   TruView-QA                          0x0000000104e85bc8 cmarDeviceComplianceEnabled + 527980
	8   TruView-QA                          0x0000000104e85da9 cmarDeviceComplianceEnabled + 528461
	9   TruView-QA                          0x0000000104dfff56 $s14IntuneMAMSwift0aB5ErrorOMa + 71718
	10  TruView-QA                          0x0000000104fe0d6c cmarDeviceComplianceEnabled + 1949712
	11  TruView-QA                          0x000000010507e400 cmarDeviceComplianceEnabled + 2594468
	12  UIKitCore                           0x00007ff805bc683e __47-[UIApplication _applicationDidEnterBackground]_block_invoke + 126
	13  UIKitCore                           0x00007ff8051f36b1 +[UIViewController _performWithoutDeferringTransitionsAllowingAnimation:actions:] + 153
	14  UIKitCore                           0x00007ff805bc6760 -[UIApplication _applicationDidEnterBackground] + 94
	15  UIKitCore                           0x00007ff804ef2ea5 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke_2 + 763
	16  UIKitCore                           0x00007ff8055d8f44 _UIScenePerformActionsWithLifecycleActionMask + 87
	17  UIKitCore                           0x00007ff804ef2b1f __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 198
	18  UIKitCore                           0x00007ff804ef2580 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 249
	19  UIKitCore                           0x00007ff804ef2968 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 813
	20  UIKitCore                           0x00007ff804ef2194 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 341
	21  UIKitCore                           0x00007ff804eff6fb __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_blo	22  UIKitCore                           0x00007ff805488b08 +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:fromCurrentState:actions:completion:] + 865
	23  UIKitCore                           0x00007ff8055f7563 _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion + 261
	24  UIKitCore                           0x00007ff804eff38a -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 347
	25  UIKitCore                           0x00007ff804cd1caa __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.610 + 877
	26  UIKitCore                           0x00007ff804cd065f -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 245
	27  UIKitCore                           0x00007ff804cd1812 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 252
	28  UIKitCore                           0x00007ff8054be182 -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] + 466
	29  FrontBoardServices                  0x00007ff8078d43f4 -[FBSScene updater:didUpdateSettings:withDiff:transitionContext:completion:] + 850
	30  FrontBoardServices                  0x00007ff8079070ef __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke_2 + 149
	31  FrontBoardServices                  0x00007ff8078e2353 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 213
	32  FrontBoardServices                  0x00007ff807907027 __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke + 381
	33  libdispatch.dylib                   0x000000010685d9f7 _dispatch_client_callout + 8
	34  libdispatch.dylib                   0x0000000106861389 _dispatch_block_invoke_direct + 507
	35  FrontBoardServices                  0x00007ff8079309a7 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	36  FrontBoardServices                  0x00007ff807930881 -[FBSMainRunLoopSerialQueue _targetQueue_performNextIfPossible] + 188
	37  FrontBoardServices                  0x00007ff8079309cf -[FBSMainRunLoopSerialQueue _performNextFromRunLoopSource] + 19
	38  CoreFoundation                      0x00007ff8003f8283 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	39  CoreFoundation                      0x00007ff8003f81c5 __CFRunLoopDoSource0 + 157
	40  CoreFoundation                      0x00007ff8003f79c2 __CFRunLoopDoSources0 + 215
	41  CoreFoundation                      0x00007ff8003f20f7 __CFRunLoopRun + 919
	42  CoreFoundation                      0x00007ff8003f197d CFRunLoopRunSpecific + 557
	43  GraphicsServices                    0x00007ff80fe9d08f GSEventRunModal + 137
	44  UIKitCore                           0x00007ff805bbb53d -[UIApplication _run] + 972
	45  UIKitCore                           0x00007ff805bbffab UIApplicationMain + 123
	46  TruView-QA                          0x0000000105064928 cmarDeviceComplianceEnabled + 2489292
	47  TruView-QA                          0x0000000104babfe2 main + 146
	48  dyld                                0x00000001061893e0 start_sim + 10
	49  ???                                 0x0000000107e1e418 0x0 + 4427211800
)
libc++abi: terminating due to uncaught exception of type NSException

**Comment by shivcelumula** [comment]
Can someone please look into this..?

**Comment by bbirman** [comment]
We haven't been able to reproduce this issue but based on the crash log we made this change to address it https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3778/files#r1856026615

**Comment by shivcelumula** [comment]
Thank you for the fix. So which version of SalesforceMobileSDK do I need to upgrade to for this fix..?

**Comment by wmathurin** [comment]
It's currently in dev and will be in our next version of Mobile SDK early next year.

**Comment by shivcelumula** [comment]
Hi @wmathurin,

I just want to touch base on the SDK version, where this fix will be available.
