### ISSUE TITLE
A blank screen is shown when user denies connected app access during web server auth flow

### ISSUE THREAD

**Issue by iowlit** [forcedotcom/SalesforceMobileSDK-iOS#3768]
1. Version of Mobile SDK Used: 12.0.1 (issue started reproducing from version 11.0.0 and persists on all newer versions)
3. Issue found in Native App or Hybrid App: Native app
4. OS Version: 18.0 (issue also reproduces on older versions)
5. Device: iPad Air 5th generation (issue reproduces across all devices)
6. Steps to reproduce: 
-   Open the mobile app.
-   Enter user credentials.
-   Tap the "Log In" button (the 'Allow Access?' screen should appear).
-   Tap the "Deny" button.
8. Actual behavior: A blank screen is shown
9. Expected Behavior: A "Server Error" popup should appear with two buttons: "OK" and "Dismiss".

Please note that the issue does not reproduce if **useWebServerAuthentication** is set to **false** 

**Screenshots:**
User-agent flow:
![Screenshot at Oct 23 10-41-17](https://github.com/user-attachments/assets/846eca43-ea0a-41ec-91c0-4a8eaf221470)
Web server flow:
![Screenshot at Oct 23 10-39-25](https://github.com/user-attachments/assets/6e09ea00-fcff-40c0-b478-9909e05fca60)

**Comment by wmathurin** [comment]
I tried on the latest version of Mobile SDK (12.2) and dev and was unable to reproduce the issue.

12.2
![AdvancedDeny122](https://github.com/user-attachments/assets/7e781fcf-8585-42c7-ae90-d7fcec38eeaf)

Dev
![AdvancedDeny13](https://github.com/user-attachments/assets/0535719f-1b53-4de5-9bf0-7cf5930031a3)

**Comment by iowlit** [comment]
Hi @wmathurin, thanks for your response!
The issue is reproducible on sandbox (test.salesforce.com), here are the steps to replicate it:

- Open the mobile app.
- Select Sandbox
- Enter user credentials.
- Tap the "Log In" button (the 'Allow Access?' screen should appear).
- Tap the "Deny" button.
![Screenshot 2025-01-02 at 18 43 23](https://github.com/user-attachments/assets/6fc6d682-cef2-4901-9546-4dcc2447b351)
