### ISSUE TITLE
Salesforce RetUrl Stripped query string

### ISSUE THREAD

**Issue by palaniraja** [forcedotcom/SalesforceMobileSDK-iOS#391]
Hi,

I'm trying to use create contact with prefilled info. But there is an issue when i use frontdoor.jsp with retURL. It does not redirect to the url given in query string retURL.

```
https://ap1.salesforce.com/secur/frontdoor.jsp?sid=<REALLY_LONG_OAUTH_TOKEN_HERE>&retURL=003/e?name_firstcon2=palani&name_lastcon2=raja
```

At the moment it strips everything after first query parameter

it redirects to `https://ap1.salesforce.com//e?name_firstcon2=palani` ignoring `name_lastcon2=raja`

**Comment by ratishmah** [comment]
Do you know why the url is stripped off when i open in safari browser on ipad? @akhileshgupta  @khawkins  @bhariharan

**Comment by ratishmah** [comment]
https://myapp.cs22.my.salesforce.com/accountID#accountID_RelatedHistoryList_target
The Part after # is ignore . Any ideas?

**Comment by bhariharan** [comment]
@ratishmah I can't think of any reason. Try posting on our community [here](https://plus.google.com/u/1/communities/114225252149514546445). This forum is reserved for ```Mobile SDK``` bugs.
