### ISSUE TITLE
Can't use new version of Salesforce libraries since I upgraded XCode and iOS

### ISSUE THREAD

**Issue by trvd1707** [forcedotcom/SalesforceMobileSDK-iOS#530]
I'm using XCode Version 5.1 (5B130a) and iOS 7.1. I have my project set with $(ARCHS_STANDARD_32_BIT)

Since this upgrade I was not able to build my project anymore.

I was able to clone SalesforceMobileSDK-iOS and build all the libraries, but when I try to use them in my project I get the following errors when building for the device with iOS 6.1:
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_MKNetworkEngine", referenced from:
      objc-class-ref in libSalesforceNetworkSDK.a(SFNetworkEngine.o)
  "_OBJC_CLASS_$_RKRequestDelegateWrapper", referenced from:
      objc-class-ref in MM_RestOperation.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

When building for the Simulator with iOS 7.1 I get even more errors and sf libraries are ingored because they don't have i386 slice:

ld: warning: ld: warning: ld: warning: ignoring file /Users/tvandusen/Development/Features 1/Common/restframework/Required/Libraries/SalesforceSDK/libSalesforceSDKCore.a, **missing required architecture i386** in file /Users/tvandusen/Development/Features 1/Common/restframework/Required/Libraries/SalesforceSDK/libSalesforceSDKCore.a (3 slices)ignoring file /Users/tvandusen/Development/Features 1/Common/restframework/Required/Libraries/SalesforceNetworkSDK/libSalesforceNetworkSDK.a, missing required architecture i386 in file /Users/tvandusen/Development/Features 1/Common/restframework/Required/Libraries/SalesforceNetworkSDK/libSalesforceNetworkSDK.a (2 slices)ignoring file /Users/tvandusen/Development/Features 1/Common/restframework/Required/Libraries/SalesforceOAuth/libSalesforceOAuth.a, missing required architecture i386 in file /Users/tvandusen/Development/Features 1/Common/restframework/Required/Libraries/SalesforceOAuth/libSalesforceOAuth.a (2 slices)

ld: warning: ignoring file /Users/tvandusen/Development/Features 1/Common/restframework/Required/Libraries/SalesforceSDK/libSalesforceNativeSDK.a, missing required architecture i386 in file /Users/tvandusen/Development/Features 1/Common/restframework/Required/Libraries/SalesforceSDK/libSalesforceNativeSDK.a (2 slices)
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_RKRequestDelegateWrapper", referenced from:
      objc-class-ref in MM_RestOperation.o
  "_OBJC_CLASS_$_SFAccountManager", referenced from:
      objc-class-ref in MM_LoginViewController.o
  "_OBJC_CLASS_$_SFOAuthCoordinator", referenced from:
      objc-class-ref in PL_AppDelegate.o
      objc-class-ref in MM_RestOperation.o
      objc-class-ref in MM_SyncManager.o
      objc-class-ref in MM_SFObjectDefinition+SOAP_DescribeLayout.o
      objc-class-ref in MM_LoginViewController.o
      l_OBJC_$_CATEGORY_SFOAuthCoordinator_$_MMFramework in MM_LoginViewController.o
      objc-class-ref in PL_MenuViewController.o
      ...
  "_OBJC_CLASS_$_SFOAuthCredentials", referenced from:
      objc-class-ref in MM_LoginViewController.o
  "_OBJC_CLASS_$_SFRestAPI", referenced from:
      objc-class-ref in MM_RestOperation.o
      l_OBJC_$_CATEGORY_SFRestAPI_$_silence in MM_RestOperation.o
      objc-class-ref in MM_SyncManager.o
      objc-class-ref in MM_SFChange.o
      objc-class-ref in MM_SFObjectDefinition.o
      objc-class-ref in MMSF_Object.o
      objc-class-ref in MM_LoginViewController.o
      ...
  "_OBJC_CLASS_$_SFRestRequest", referenced from:
      objc-class-ref in MM_RestOperation.o
      objc-class-ref in MMSF_Loan__c.o
      objc-class-ref in MMSF_Loan_Officer__c.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by MadhavaReddyP** [comment]
SalesforceMobileSDK with 64 bit ios integration errors. Plz help me out

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RKRequestDelegateWrapper", referenced from:
      objc-class-ref in MM_RestOperation.o
      objc-class-ref in libDSAREST Library.a(MM_RestOperation.o)
  "_OBJC_CLASS_$_SA_AlertView", referenced from:
      objc-class-ref in MM_LoginViewController.o
      objc-class-ref in MM_RestOperation.o
      objc-class-ref in MM_OrgMetaData.o
      objc-class-ref in MM_SyncManager.o
      objc-class-ref in MM_ContextManager.o
      objc-class-ref in MM_BaseViewController.o
      objc-class-ref in ZM_SearchViewController.o
      ...
  "_OBJC_CLASS_$_SA_BlockButton", referenced from:
      objc-class-ref in libDSAREST Library.a(MM_RecordFieldColumnView.o)
  "_OBJC_CLASS_$_SA_BlockWrapper", referenced from:
      objc-class-ref in MM_SFChange.o
      objc-class-ref in libDSAREST Library.a(MM_SFChange.o)
  "_OBJC_CLASS_$_SA_Connection", referenced from:
      objc-class-ref in MM_RestOperation.o
      objc-class-ref in libDSAREST Library.a(MM_RestOperation.o)
      objc-class-ref in libDSAREST Library.a(MM_SFObjectDefinition+SOAP_DescribeLayout.o)
  "_OBJC_CLASS_$_SA_ConnectionQueue", referenced from:
      objc-class-ref in MM_SFChange.o
      objc-class-ref in MM_LoginViewController.o
      objc-class-ref in MM_RestOperation.o
      objc-class-ref in MM_SyncManager.o
      objc-class-ref in MM_ContextManager.o
      objc-class-ref in MM_BaseViewController.o
      objc-class-ref in DSA_AppDelegate.o
      ...
  "_OBJC_CLASS_$_SA_PleaseWaitDisplay", referenced from:
      objc-class-ref in MM_SFObjectDefinition.o
      objc-class-ref in MM_BaseViewController.o
      objc-class-ref in DSA_AppDelegate.o
      objc-class-ref in DSA_SettingsMenuViewController.o
      objc-class-ref in DSARestClient.o
      objc-class-ref in libDSAREST Library.a(MM_SFObjectDefinition.o)
  "_kConnectionNotification_ConnectionStateChanged", referenced from:
      +[MM_SFChange load] in MM_SFChange.o
      +[MM_LoginViewController load] in MM_LoginViewController.o
      -[MM_SyncManager init] in MM_SyncManager.o
      -[DSARestClient init] in DSARestClient.o
      -[MM_SyncManager init] in libDSAREST Library.a(MM_SyncManager.o)
      +[MM_SFChange load] in libDSAREST Library.a(MM_SFChange.o)
      +[MM_LoginViewController load] in libDSAREST Library.a(MM_LoginViewController.o)
      ...
  "_kNotification_PersistentStoreResetDueToSchemaChange", referenced from:
      -[MM_ContextManager init] in MM_ContextManager.o
      -[MM_ContextManager contextAtPath:model:] in MM_ContextManager.o
      -[MM_ContextManager init] in libDSAREST Library.a(MM_ContextManager.o)
      -[MM_ContextManager contextAtPath:model:] in libDSAREST Library.a(MM_ContextManager.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by khawkins** [comment]
I'm not sure what version of the SDK you're using, but `RKRequestDelegateWrapper` (i.e. RestKit support) was removed from the Mobile SDK well before we implemented 64-bit support.

I would recommend posting to our [Google Plus Community](http://sfdc.co/mobilesdkcommunity), to see if anyone else has encountered your error.

**Comment by MadhavaReddyP** [comment]
I am using Salesforce mobile SDK version 3.1 and getting following error.

Undefined symbols for architecture x86_64:
"OBJC_CLASS$RKRequestDelegateWrapper", referenced from:
objc-class-ref in MM_RestOperation.o
objc-class-ref in libDSAREST Library.a(MM_RestOperation.o)
"_OBJC_CLASS$SA_AlertView", referenced from:
objc-class-ref in MM_LoginViewController.o
objc-class-ref in MM_RestOperation.o
objc-class-ref in MM_OrgMetaData.o
objc-class-ref in MM_SyncManager.o
objc-class-ref in MM_ContextManager.o
objc-class-ref in MM_BaseViewController.o
objc-class-ref in ZM_SearchViewController.o

**Comment by khawkins** [comment]
None of these classes are in the Mobile SDK.

**Comment by MadhavaReddyP** [comment]
RKRequistDelegateWrapper, How to replace this class methods in new version of Salesforce
RKRequestDelegateWrapper *wrappedDelegate = [RKRequestDelegateWrapper wrapperWithRequest:request];
	[self.activeRequests addObject:wrappedDelegate];
	[wrappedDelegate send];

So, Where we need to replace above methods. Plz help me out

**Comment by fr33kill** [comment]
@MadhavaReddyP @trvd1707 
Hi, any luck with getting new updated SA_Base framework?

**Comment by jaswanth55** [comment]
SalesforceMobileSDK with 64 bit ios integration errors. Plz help me out

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SFApplication", referenced from:
      objc-class-ref in main.o
  "_OBJC_CLASS_$_SFAuthenticationManager", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_SFHybridViewController", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_SFLogger", referenced from:
      objc-class-ref in AppDelegate.o
  "_kSFLoginHostChangedNotification", referenced from:
      -[AppDelegate init] in AppDelegate.o
      -[AppDelegate dealloc] in AppDelegate.o
  "_kSFUserLogoutNotification", referenced from:
      -[AppDelegate init] in AppDelegate.o
      -[AppDelegate dealloc] in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
