### ISSUE TITLE
Remove dependencies on sqlcipher

### ISSUE THREAD

**Issue by Codeglee** [forcedotcom/SalesforceMobileSDK-iOS#532]
These dependencies make it impossible for us to have custom sqlite additions.

As it is we get duplicate 187 duplicate symbols for example:
ld: warning: directory not found for option '-F"/.../Dependencies"'
duplicate symbol _sqlite3_mutex_enter in:
    /.../Library/Developer/Xcode/DerivedData/Project-ehywuiuynikozibolrepnmpnwpqj/Build/Intermediates/Project.build/Debug-iphonesimulator/Project.build/Objects-normal/i386/sqlite3.o
    Dependencies/sqlcipher/libsqlcipher.a(sqlite3.o)

**Comment by sevem** [comment]
Same problem. I want to use a SalesforceMobileSDK-CordovaPlugin in combination with a sqlite cordova plugin. Everything works fine if I use only one of the plugins. But the combination of SalesforceMobileSDK-CordovaPlugin and Cordova-sqlite-storage I got a linker error.

**Comment by dlcerva** [comment]
+1 Any direction on how one would 'unlink' sqlcipher?

**Comment by khawkins** [comment]
If you're consuming the SDK through CocoaPods, the SDK does have a dependency on SQLCipher.  But that said, if you're using the `use_frameworks!` configuration, SmartStore's use of SQLCipher can live side by side with inclusion of SQLite in other parts of your application.

For the Cordova plugin, unfortunately the situation is more complicated.  While in theory you could unlink libsqlcipher.a in your project and link SQLite instead, libSmartStore.a was built with the `SQLITE_HAS_CODEC` preprocessor directive, which means it's not going to find some of the SQLCipher-specific symbols it expects to be there.  For this case, you'd need to rebuild libSmartStore.a from the main SDK, *without* the `SQLITE_HAS_CODEC` preprocessor directive, then replace the existing copy of libSmartStore.a in your app.  Let me know if you'd like specific steps for accomplishing this, and I can write something up.
