### ISSUE TITLE
attemptofflineload with hybrid_remote

### ISSUE THREAD

**Issue by Gurnaik-Randhawa** [forcedotcom/SalesforceMobileSDK-iOS#679]
I have an existing hybrid iOS app that was developed using version 1.5 of the SDK.
This has now been upgraded to use the latest version 2.2. Everything is now working except for loading when offline. 

I use HTML5 manifest cache to cache all the files for the app locally.
In the version 1.5 SDK the app loads up from scratch when the device is offline.
In the new 2.2 version of the the SDK when the device is off line it works fine if it is already loaded but will not load from scratch like the 1.5 version.

In the 2.2 version it hangs with the last line in the logfile 
Failed to load webpage with error: The Internet connection appears to be be offline
Which it is but it should use the cached version.

**Comment by Gurnaik-Randhawa** [comment]
Hi 

I did not have time to complete and test and release our project with the 2.2 version of the SDK. 

I am now upgrading it to the version 3.1.0 and have the same problem as above.
The app uses the cache manifest to cache all the file required in the browser application cache.
With our current 1.5 version you can launch the app when the device is offline.

With the 3.1 SDK I get the Bootstrap Error Page
Error code :1 
Error Description: Your device is offline Can't continue
Error Context: AppLoading

In the bootconfig.json i have

{
  "remoteAccessConsumerKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "oauthRedirectURI": "sdfc://success",
  "oauthScopes": [
    "web",
    "api"
  ],
  "isLocal": false,
  "startPage": "/apex/formshomeV2",
  "errorPage": "error.html",
  "shouldAuthenticate": true,
  "attemptOfflineLoad": true
}

**Comment by khawkins** [comment]
Is this after you've already previously authenticated in an online session?

**Comment by Gurnaik-Randhawa** [comment]
Hi Kevin

Yes it is after you are previously authenticated. But then relaunch the app
not just bring it to the fore ground.

Sent from my iPhone

On 18 Mar 2015, at 03:32 pm, Kevin Hawkins <notifications@github.com> wrote:

Is this after you've already previously authenticated in an online session?

—
Reply to this email directly or view it on GitHub
<https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/679#issuecomment-83022326>
.
