### ISSUE TITLE
App crashes after PIN security screen in Salesforce SDK 2.3

### ISSUE THREAD

**Issue by manish-metacube** [forcedotcom/SalesforceMobileSDK-iOS#740]
Hi All, 

I have developed an hybrid app in sencha touch 2.4 using salesforce 2.2. We have recently implemented PIN security in our app but after upgrading to salesforce 2.3 app is unable to run. 

When I run the project after authentication, PIN security screen comes and once I click on Done, it <b>crashes</b>

Here is logs : 

<pre>2014-09-23 15:31:54.527 MySampleApp[88998:60b] Apache Cordova native platform version 3.6.3 is starting.
2014-09-23 15:31:54.528 MySampleApp[88998:60b] Multi-tasking -> Device: YES, App: YES
2014-09-23 15:31:54.530 MySampleApp[88998:60b] Unlimited access to network resources
2014-09-23 15:31:54:586 MySampleApp[88998:60b] INFO|SFAuthenticationManager|No current user account, so creating a new one.
2014-09-23 15:31:54.604 MySampleApp[88998:60b] active
2014-09-23 15:32:15:347 MySampleApp[88998:60b] INFO|SFSecurityLockout|Skipping 'lock' since not authenticated
2014-09-23 15:32:15.349 MySampleApp[88998:60b] -[UIApplication lastEventDate]: unrecognized selector sent to instance 0x10db062b0
2014-09-23 15:32:15.352 MySampleApp[88998:60b] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIApplication lastEventDate]: unrecognized selector sent to instance 0x10db062b0'
*** First throw call stack:
(
    0   CoreFoundation                      0x00000001004f3495 __exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x0000000102ca099e objc_exception_throw + 43
    2   CoreFoundation                      0x000000010058465d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
    3   CoreFoundation                      0x00000001004e4d8d ___forwarding___ + 973
    4   CoreFoundation                      0x00000001004e4938 _CF_forwarding_prep_0 + 120
    5   MySampleApp                           0x000000010005c557 -[SFUserActivityMonitor startMonitoring] + 75
    6   MySampleApp                           0x000000010006ab60 +[SFSecurityLockout startActivityMonitoring] + 80
    7   MySampleApp                           0x0000000100062d93 -[SFAuthenticationManager finalizeAuthCompletion] + 85
    8   MySampleApp                           0x000000010006b8db +[SFSecurityLockout unlockSuccessPostProcessing:] + 184
    9   MySampleApp                           0x0000000100064d15 __48-[SFAuthenticationManager retrievedIdentityData]_block_invoke + 355
    10  MySampleApp                           0x000000010006b8db +[SFSecurityLockout unlockSuccessPostProcessing:] + 184
    11  MySampleApp                           0x0000000100064b90 -[SFAuthenticationManager retrievedIdentityData] + 433
    12  MySampleApp                           0x000000010005ce62 -[SFIdentityCoordinator notifyDelegateOfSuccess] + 119
    13  MySampleApp                           0x000000010005d182 -[SFIdentityCoordinator processResponse] + 303
    14  Foundation                          0x000000010248936b __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 48
    15  Foundation                          0x000000010233cbdb -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 210
    16  Foundation                          0x000000010233caec -[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 69
    17  CFNetwork                           0x0000000106cf5637 ___ZN27URLConnectionClient_Classic26_delegate_didFinishLoadingEU13block_pointerFvvE_block_invoke + 107
    18  CFNetwork                           0x0000000106cf3802 ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 84
    19  CoreFoundation                      0x0000000100499f74 CFArrayApplyFunction + 68
    20  CFNetwork                           0x0000000106c663e7 _ZN19RunloopBlockContext7performEv + 133
    21  CFNetwork                           0x0000000106c66217 _ZN17MultiplexerSource7performEv + 247
    22  CFNetwork                           0x0000000106c6603a _ZN17MultiplexerSource8_performEPv + 72
    23  CoreFoundation                      0x0000000100482d21 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    24  CoreFoundation                      0x00000001004825f2 __CFRunLoopDoSources0 + 242
    25  CoreFoundation                      0x000000010049e46f __CFRunLoopRun + 767
    26  CoreFoundation                      0x000000010049dd83 CFRunLoopRunSpecific + 467
    27  GraphicsServices                    0x00000001041b3f04 GSEventRunModal + 161
    28  UIKit                               0x0000000100774e33 UIApplicationMain + 1010
    29  MySampleApp                           0x000000010001db97 main + 71
    30  libdyld.dylib                       0x00000001035205fd start + 1
    31  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException </pre>

@khawkins @akhileshgupta - Can you please confirm if this is a known issue and if there's a workaround?

Regards!
Manish Kumar

**Comment by AkshathaJ** [comment]
Hie

Im facing similar issue when I updated sales force mobile sdk from 3.0 to 3.3.

I ve done following things in terminal,

cordova plugin rm com.salesforce
cordova platform rm ios
cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin
cordova platform add ios
cordova prepare

Please let me know if i missed somewhere.

**Comment by anilabsinc-ajay** [comment]
Still occurs in sdk 6.1.1
