### ISSUE TITLE
Back screen for 3+ seconds during launching

### ISSUE THREAD

**Issue by mguillet** [forcedotcom/SalesforceMobileSDK-iOS#775]
I believe the issue started when migrating to Cordova 3.5+ but for some reasons, I feel like it's getting worst.

I created an empty application with ``forceios`` and recorded its launch in a (fancy) iPhone 6 simulator.
![ctmq8](https://cloud.githubusercontent.com/assets/701325/4539922/0a04866c-4e02-11e4-976c-ac0fd259a09e.gif)

While the GIF is a bit ugly, you can still see that the app pauses for almost 3 sec with nothing presented to the user but a black screen.

I originally thought that this happened because of your swizzling of AppDelegate but I then tried to launch the application without a network connection. The 3 seconds lag then became much longer and I've killed the app before I could see something interesting after one minute.

Interestingly, from where I'm at, when I run this in my local terminal I get also a 3 seconds delay. 

    $ time curl https://login.salesforce.com 2> /dev/null > /dev/null

    real	0m3.397s
    user	0m0.034s
    sys	0m0.016s

Can we do something about it? Could you consider showing the application splash screen during this time?

**Comment by bhariharan** [comment]
We've upgraded to ```Cordova 3.9.2``` in the latest release and I don't see this anymore.
