### ISSUE TITLE
Using Salesforce Mobile SDK 2.1, keychain issues

### ISSUE THREAD

**Issue by brad36** [forcedotcom/SalesforceMobileSDK-iOS#785]
Seems to happen after inactivity or lock screen. I'm using XCode 5.1.1, iOS 7.1.2 and the user already has gone through oauth previously. Any ideas how to fix? Thanks!

2014-10-11 22:15:52:817 iPath[5470:60b] ERROR|SFCrypto|App id keychain data missing or corrupted. Attempting to reset.

2014-10-11 22:15:52:858 iPath[5470:60b] ERROR|SFKeychainItemWrapper|Error adding keychain item: (-34018)

2014-10-11 22:15:52:858 iPath[5470:60b] WARN|SFCrypto|Could not save the base app identifier to the keychain (result: Unknown status code (-34018)). Retrying.

2014-10-11 22:15:52.890 iPath[5470:60b] SFOAuthCredentials:tokenForKey: (-34018) error retrieving "com.salesforce.oauth.access" item matching "{ acct = "iPath-Default-login.salesforce.com"; class = genp; "m_Limit" = "m_LimitOne"; "r_Attributes" = 1; svce = "com.salesforce.oauth.access"; }"

**Comment by brad36** [comment]
Appears to me that version 3.0 of the SDK has significantly improved this issue. I've had no recurrences, and by giving my app 3 min of background processing to finish what its doing, I think that helps also. So well done, very pleased with that. One I have noticed is that when Salesforce requires a password change over oAuth, that process will still sometimes take the user through to a Salesforce Web UI instead of into the mobile app. Would be nice to fix that too. Any time that happens the user is like "whoa, wasn't expecting that, what do I do now". But otherwise, vast improvement, thanks!

**Comment by khawkins** [comment]
Glad to hear it.  We've noticed the same with some of our internal apps, but it's great to hear from others as well.

**Comment by brad36** [comment]
Am still occasionally seeing something in v3.0, whether this is the same issue not sure...

SIGSEGV SEGV_ACCERR at 0xee145ed0
Thread : Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x359c7f56 objc_msgSend + 21
1  CoreFoundation                 0x2744e805 -[__NSDictionaryM setObject:forKey:] + 180
2  iPath                          0x00289701 -[SFKeychainItemWrapper setObject:forKey:] + 488
3  iPath                          0x0028a1f1 -[SFKeychainItemWrapper setValueData:] + 124
4  iPath                          0x0040c4bf -[SFOAuthCredentials updateKeychainWithTokenData:forService:] (SFOAuthCredentials.m:449)
5  iPath                          0x0040b421 -[SFOAuthCredentials setAccessToken:withSFEncryptionKey:] (SFOAuthCredentials.m:342)
6  iPath                          0x00409495 -[SFOAuthCredentials setAccessToken:] (SFOAuthCredentials.m:150)
7  iPath                          0x004114f3 -[SFOAuthCoordinator updateCredentials:forTokenRefresh:] (SFOAuthCoordinator.m:458)
8  iPath                          0x00411163 -[SFOAuthCoordinator handleRefreshResponse] (SFOAuthCoordinator.m:426)
9  iPath                          0x00413b97 -[SFOAuthCoordinator connectionDidFinishLoading:] (SFOAuthCoordinator.m:678)
10 CFNetwork                      0x27074e29 __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 56
11 CFNetwork                      0x27074de3 -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 182
12 CFNetwork                      0x27074ed5 -[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 36
13 CFNetwork                      0x26f88c87 ___ZN27URLConnectionClient_Classic26_delegate_didFinishLoadingEU13block_pointerFvvE_block_invoke + 78
14 CFNetwork                      0x270260d5 ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 60
15 CFNetwork                      0x26f79a35 RunloopBlockContext::_invoke_block(void const*, void*) + 60
16 CoreFoundation                 0x27442c6d CFArrayApplyFunction + 36
17 CFNetwork                      0x26f798ef RunloopBlockContext::perform() + 182
18 CFNetwork                      0x26f797b5 MultiplexerSource::perform() + 216
19 CFNetwork                      0x26f79649 MultiplexerSource::_perform(void*) + 48
20 CoreFoundation                 0x274f8faf __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 14
21 CoreFoundation                 0x274f83bf __CFRunLoopDoSources0 + 218
22 CoreFoundation                 0x274f6a25 __CFRunLoopRun + 772
23 CoreFoundation                 0x27443201 CFRunLoopRunSpecific + 476
24 CoreFoundation                 0x27443013 CFRunLoopRunInMode + 106
25 GraphicsServices               0x2ebdf201 GSEventRunModal + 136
26 UIKit                          0x2abe7a59 UIApplicationMain + 1440
27 iPath                          0x0010980f main (main.m:33)

**Comment by carlcarter** [comment]
@brad36 we also had a number of OAuth workflow issues with 3.0 and 3.1 - we upgraded to 3.2 and all the ones we were seeing have been resolved.

**Comment by brad36** [comment]
Ok thanks, Carl, that's positive news, I will look into upgrading to 3.2 also then.
