### ISSUE TITLE
SmartStore Inspector with custom store name (iOS)

### ISSUE THREAD

**Issue by andredsp** [forcedotcom/SalesforceMobileSDK-iOS#792]
Hello, I'm trying to use the SFSmartStoreInspectorViewController (iOS SDK 2.3) but it seems to access only stores created with kDefaultSmartStoreName, which is not the case for me (my app creates two stores with custom names).

I think a method like presentWithStore: or similar way would be great.

**Comment by wmathurin** [comment]
Coming to the next version of the SalesforceMobileSDK for iOS (version 3.2):
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/988
