### ISSUE TITLE
SOQL Query Builder methods can't be used in Swift

### ISSUE THREAD

**Issue by Arrisi** [forcedotcom/SalesforceMobileSDK-iOS#858]
I'm not sure if any issues can be filed for Swift compatibility, but the SOQL query builder methods cannot be used because of the "where" parameter.  "Where" is now a keyword in Swift and will throw an error during compilation.

**Comment by bhariharan** [comment]
@Arrisi This has been fixed in [this](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/986) pull request and will be a part of our upcoming release.
