### ISSUE TITLE
timeIntervalSinceReferenceDate crash

### ISSUE THREAD

**Issue by odyssey1357** [forcedotcom/SalesforceMobileSDK-iOS#874]
Hello. I am using SalesForce SDK 3.0 in my app. While my application usage I got some feedbacks about crash at "application becomes active" event. I got a little log from BugSense:

-[__NSCFString timeIntervalSinceReferenceDate]: unrecognized selector sent to instance 
/*----------------------------------------------*/
0	CoreFoundation	<redacted> + 130	
1	libobjc.A.dylib	objc_exception_throw + 38	
2	CoreFoundation	<redacted> + 202	
3	CoreFoundation	<redacted> + 706	
4	CoreFoundation	_CF_forwarding_prep_0 + 24	
5	CoreFoundation	<redacted> + 44	
6	MyApp	+[SFSecurityLockout inactivityExpired] + 100	
7	MyApp	+[SFSecurityLockout validateTimer] + 60	
8	MyApp	-[SalesforceSDKManager handleAppForeground:] + 1060
/*----------------------------------------------*/

P.S. I got a plist file with UserDefaults from one of my app users. I found this key-value pair:
	<key>timer.lastactivity</key>
	<string>Мария</string>
I know "timer.lastactivity" must keep date value, but it keeps string. My app doesn't use UserDefaults value by key "timer.lastactivity".

What's wrong? How can it be fixed.
Thanks for reply.

**Comment by khawkins** [comment]
That's...very strange.  The value that's set for `timer.lastactivity` should always be a date, the getting and setting of which is fully encapsulated by the `SFInactivityTimerCenter` class.

Do you have a reproduction scenario for this?  And can you tell me how you originated the Mobile SDK into your app (forceios, the distribution repo binaries, etc.)?

**Comment by khawkins** [comment]
In the absence of further information, I can't reproduce this bug.  Feel free to reopen if you can provide a reproduction case.

**Comment by ClaudeSutterlin** [comment]
For what it's worth, we're experiencing this issue as well. Upwards of 1000 occurrences a day. I'll report back if I find any information to assist in debugging.
