### ISSUE TITLE
pod install fails

### ISSUE THREAD

**Issue by cgreening** [forcedotcom/SalesforceMobileSDK-iOS#876]
I've created a Podfile to install the SDK:

```
pod 'SalesforceMobileSDK-iOS', :git => 'git@github.com:forcedotcom/SalesforceMobileSDK-iOS.git'
```

Running `pod install` results in the following error:

```
Pre-downloading: `SalesforceMobileSDK-iOS` from `git@github.com:forcedotcom/SalesforceMobileSDK-iOS.git`
Downloading dependencies
Installing SalesforceMobileSDK-iOS (3.0.0)
[!] /bin/bash 
set -e
sed -i -e 's/#import \"Categories\//#import \"/g' external/MKNetworkKit/MKNetworkKit/MKNetworkKit.h

sed: external/MKNetworkKit/MKNetworkKit/MKNetworkKit.h: No such file or directory
```

**Comment by khawkins** [comment]
Make sure you use the `:submodules => true` directive in your Podfile, as the Mobile SDK makes use of submodules.  Feel free to re-open if this doesn't resolve your issue.

**Comment by powerje** [comment]
I'm seeing this and I am using :submodules => true

It seems to work properly sometimes, but eventually will fail and then not work again. I'm not sure what is triggering the success or failure, but I've literally ran `pod update`, switched to my master branch and rebased - which all this did was update the Podfile/Podfile.lock, run `pod update` again and I see the error.

The exact line in my Podfile is:
`pod 'SalesforceMobileSDK-iOS', :git => 'git@github.com:forcedotcom/SalesforceMobileSDK-iOS.git', :submodules => true`

**Comment by powerje** [comment]
OK, upon further testing it looks like removing the line from my Podfile and updating (leaving out Salesforce) then adding Salesforce back in it works, the first time, and while it is updating it says:
`
Pre-downloading: `SalesforceMobileSDK-iOS` from `git@github.com:forcedotcom/SalesforceMobileSDK-iOS.git`, submodules `true`
`

Performing a `pod update` directly after that fails with the error but the downloading line is different:

`
Pre-downloading: `SalesforceMobileSDK-iOS` from `git@github.com:forcedotcom/SalesforceMobileSDK-iOS.git`, commit `aea2b7aa4220854b9ae5f3fd15d2e37af9159983`
`

Makes me think this is a Cocoapods issue - future updates aren't listening to the use of submodules maybe?

**Comment by powerje** [comment]
Looks like this is a known Cocoapods issue:
https://github.com/CocoaPods/CocoaPods/issues/2317

I'm not sure what the workaround/fix is. Probably submitting the pod to Cocoapods proper would fix it as we wouldn't need to rely on the `:git` option.
