### ISSUE TITLE
Styling login screen in a native app 

### ISSUE THREAD

**Issue by powerje** [forcedotcom/SalesforceMobileSDK-iOS#877]
Is there a way to style the login screen? In iOS 8 (probably on 7 as well) the login screen interferes with the status bar.

I'm using the 2.3 SDK, and just saw the 3.0 SDK has been released - perhaps that fixes this issue?

Ideally though I'd like to be able to adjust the logo image and background/button/text colors as well.

This is an example of the problem I'm seeing re: the status bar:
![ios simulator screen shot jan 8 2015 11 25 23 am](https://cloud.githubusercontent.com/assets/481245/5665822/174ea814-9729-11e4-9c73-4b74fb3a4984.png)

**Comment by khawkins** [comment]
It's interesting that you're seeing a status bar at all for the login view.  The default configuration of `SFAuthorizingViewController` has `prefersStatusBarHidden` set to `YES`.  Are you overriding that behavior in your app?

To answer your question, you can override the auth view display and dismissal entirely, by overriding the value of `[SFAuthenticationManager sharedManager].authViewHandler`, to specify your own display logic.  You can see how it's set by default in the `init` method of the authentication manager.  I've also created [a project](https://github.com/khawkins/Sandbox/tree/master/AuthInPopover) that demonstrates overriding the auth view to display in a popover controller.

**Comment by powerje** [comment]
Interesting, I'm not setting `prefersStatusBarHidden` myself. Is that the default in the 2.3 SDK as well? I haven't updated to 3.0 yet (perhaps I should?).

Thank you for the example project, I will look over it to see how I might customize the login page further.

**Comment by khawkins** [comment]
Yes, it's the default behavior of the 2.3 SDK as well, so I'm not sure that an update to 3.0 will fix that specific issue.  Do you have the `UIViewControllerBasedStatusBarAppearance` value set to `NO` in your app plist file, perhaps?

**Comment by powerje** [comment]
@khawkins oh good catch, I do indeed! Getting rid of that hides the status bar entirely from the login screen.

Thanks!
