### ISSUE TITLE
Images from Salesforce  are not visible after salesforce upgrade. 

### ISSUE THREAD

**Issue by manish-metacube** [forcedotcom/SalesforceMobileSDK-iOS#878]
Hi all, 
I have developed an application using mobile sdk 2.2. Recently we have upgraded our codebase to latest mobile SDK 3.0. With our earlier codebase we are able to see images and logo coming from salesforce. but after upgrading Logo's and images are not visible
Here is code to show image : 
   &lt;img src="https://c.cs14.content.force.com/servlet/rtaImage?eid=001c000000Qq11W&amp;feoid=00Nc0000000rOK7&amp;refid=0EMc00000008R7i"&gt; 

images are in bytes array.

@khawkins : Can you please help me on this? 

Can someone help me on this?

Regards, 

Manish Kumar

**Comment by manish-metacube** [comment]
One update : 

We have verified that images coming from specific server are not randering 

* Images coming from
 "https://x.xxx.content.force.com/servlet/servlet.ImageServer?id=xxxxx"
are rendering properly
* Images coming from
"https://x.xxx.content.force.com/servlet/rtaImage?eid=xxxxx" are NOT
randering.  

The difference between the 2 URLs is that one references an externally available document , while the other is 'private'. It feel like this has something to do with a change in how the mobile sdk
manages the session. 
 
@khawkins any suggestion?

**Comment by wmathurin** [comment]
Have you tried bearer token URLs?
http://www.salesforce.com/us/developer/docs/chatterapi/Content/intro_requesting_bearer_token_url.htm

**Comment by manish-metacube** [comment]
Hi Wolfgang, 

Thanks for your comment. My application uses mobile sdk 3.0 and we are using forcetk.mobilesdk.js which generates header for me. 

<code>
var getRequestHeaders = function(client) {
			var headers = {};

			headers[client.authzHeader] = "Bearer " + client.sessionId;
			headers['Cache-Control'] = 'no-store';
			// See
			// http://www.salesforce.com/us/developer/docs/chatterapi/Content/intro_requesting_bearer_token_url.htm#kanchor36
			headers["X-Connect-Bearer-Urls"] = true;
			if (client.userAgentString !== null) {
				headers['User-Agent'] = client.userAgentString;
				headers['X-User-Agent'] = client.userAgentString;
			}
			return headers;
}</code>

I am using rest service to get image urls and injecting image content's to html. but images specifically coming from https://x.xxx.content.force.com/servlet/rtaImage?eid=xxxxx are not randering. 

Regards,
Manish Kumar

**Comment by wmathurin** [comment]
If you make a connect call using forcetk that returns URLs for images then those URLs will be self-authenticating (i.e. will have a bearer token) thanks to the x-connect-bearer-urls request header that forcetk uses. But if you build the image URL yourself then they won't be self-authenticating. How did you get the "https://x.xxx.content.force.com/servlet/rtaImage?eid=xxxxx" URLs?

**Comment by manish-metacube** [comment]
I am calling a REST via forcetk that gives me these image URL for sales force object. Then I am using this URL to show image/logo for salesforce object.

**Comment by gauravkheterpal** [comment]
@khawkins - Do you have a definitive ETA on when this will be fixed? This is quiet severe and I'm sure a lot of customers will run into this eventually.

**Comment by manish-metacube** [comment]
Hi, 

I have got a workaround, not sure this is a right solution but works for me. 

I have added following ajax code to get current session via frontdoor url for the image. 

<code>
 $.ajax({url: forcetkClient.instanceUrl + "/secur/frontdoor.jsp?sid=" + forcetkClient.sessionId , success: function(result){
 // my scuccess callback
}});	
</code>

On my success callback I am setting same url again on html image field and it surprisingly loads the image. 

I am still looking for the root cause


Regards,
Manish Kumar

**Comment by bhavna24** [comment]
Hi all,

I am using latest version of salesforce mobile sdk (3.2) in my native iOS application. I am trying to display profile picture of logged in user through this code - 

        SFIdentityData *idData = [SFAuthenticationManager sharedManager].idCoordinator.idData;
        NSData *data = [NSData dataWithContentsOfURL:idData.pictureUrl];
        [self.testImageView setImage:[UIImage imageWithData:data]];

I am getting pictureUrl and also able to convert it in NSData but when i am trying to create UIImage through this data , it is always returning nil.

Can someone help me on this?

Regards,
Bhavna Gupta

**Comment by akhileshgupta** [comment]
@bhavna24 can you please post this question on our G+ community: plus.google.com/communities/114225252149514546445

Just to give you a quick idea, the pictureUrl returned by the identity data doesn't contain the user session token. Hence, the data for the URL will not be of an image.

**Comment by akhileshgupta** [comment]
For security purpose, we have decided to not automatically add the salesforce session cookies to a hybrid local webview. You should use the bearer urls for the images in such scenario. Checkout the [documentation here](https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/intro_requesting_bearer_token_url.htm).
