### ISSUE TITLE
Auto-generated umbrella/wrapper headers

### ISSUE THREAD

**Issue by NachoMan** [forcedotcom/SalesforceMobileSDK-iOS#881]
The different library projects should have auto-generated umbrella headers auto-generated to ease in use of these libraries, instead of requiring developers to import individual headers on a case-by-case basis.  This is a similar pattern to what Apple provides with their frameworks, and makes it easier to manage cross-header dependencies.

**Comment by bhariharan** [comment]
I believe this is available in the latest version of the Mobile SDK.
