### ISSUE TITLE
Some classes are incorrectly importing UIKit when Foundation is more appropriate

### ISSUE THREAD

**Issue by NachoMan** [forcedotcom/SalesforceMobileSDK-iOS#883]
When trying to adapt some of the Salesforce Mobile SDK libraries to be cross-platform between iOS and Mac OS X, I discovered a number of classes are importing UIKit/UIKit.h even though it doesn't use any UIKit-specific features within those classes.  Instead they should only import Foundation/Foundation.h or another applicable framework to ease in porting these classes between platforms.

**Comment by kchitalia** [comment]
This issue has been fixed.
