### ISSUE TITLE
Credentials / Account Info objects difficult to test

### ISSUE THREAD

**Issue by NachoMan** [forcedotcom/SalesforceMobileSDK-iOS#884]
When adding unit tests to classes that depend upon SFUserAccount and SFOAuthCredentials instances (e.g. network classes that consume the MobileSDK) it's extremely difficult to use these classes without mocking every interface because of the way the SFOAuthCredentials class' accessor methods make explicit calls to the keychain.  It would be great to utilize either a class-cluster or dependency injection pattern to allow unit tests to stub out the accessToken and refreshToken properties.

**Comment by huminzhi** [comment]
Create an internal work to track this.. so closing this one.
