### ISSUE TITLE
Another PIN issue, smart store not working if user resets the PIN

### ISSUE THREAD

**Issue by manish-metacube** [forcedotcom/SalesforceMobileSDK-iOS#944]
Hi All, 

We got another critical issue with PIN, If you have smart store and PIN enabled and you reset the PIN soups will no longer works now.

Here are the steps to reproduce the issue: 

1.       Log in for the first time
2.       Idle or navigate away to activate the PIN verification form
3.       Hit forget passcode, you are brought back to the login form
4.       Enter your credentials again
5.       Enter your PIN information again.
6.       You will be logged in successfully, however, after that you will not able to use smart store now. 

After looking at logs I have verified that it executes the error handler for registering soups and unable to create soups and hence the issue. 

Regards,
Manish Kumar

**Comment by bhariharan** [comment]
```Forgot Passcode``` logs the user out and removes existing ```SmartStore``` databases. When you log back in, a new instance of ```SmartStore``` is created. Are you attempting to re-create a database with the same name as before? What's the exact stack trace of the error?

**Comment by rockstart4ever** [comment]
Sorry for late reply. Yes, I am re registering soups but getting error on soup registration

**Comment by manish-metacube** [comment]
Hi All, 

Sorry i was away for long time. Yes, We are re-registering soups but getting error. Unfortunately there is no description available for error. 

Regards,
Manish Kumar

**Comment by bhariharan** [comment]
Which version of the Mobile SDK are you using?

**Comment by manish-metacube** [comment]
Mobile SDK 3.1

**Comment by manish-metacube** [comment]
any update?

**Comment by bhariharan** [comment]
@manish-metacube Is this still happening in Mobile SDK 3.2? If so, could you log a customer support case for this?

**Comment by manish-metacube** [comment]
Yes, this exists for 3.2 as well.

**Comment by carlcarter** [comment]
I can confirm this still exists for v3.2 on our inhouse native iOS app also.

**Comment by bhariharan** [comment]
We have a fix for this issue [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1076), and will be in our next release (```3.3```). Meanwhile, feel free to apply it locally in your app.
