### ISSUE TITLE
EXC_BAD_ACCESS (code=1) Exception on upSync

### ISSUE THREAD

**Issue by rootdevelop** [forcedotcom/SalesforceMobileSDK-iOS#945]
The crash is caused by an EXC_BAD_ACCESS (code=1) exception which is the result of either a corrupt pointer or a deallocated chunk. This exception occurred in the sendRESTRequest method (SFRestAPI+Blocks.m). 

When I looked further I discovered that the “request" parameter was nil.

The method is called by the SFSmartSyncSyncManager.m in the syncUpOneEntry.

This method contains the following part:
```objective-c
// Do we need to do a create, update or delete
    SFSyncManagerAction action = kSyncManagerActionNone;
    if ([record[kSyncManagerLocallyDeleted] boolValue])
        action = kSyncManagerActionDelete;
    else if ([record[kSyncManagerLocallyCreated] boolValue])
        action = kSyncManagerActionCreate;
    else if ([record[kSyncManagerLocallyUpdated] boolValue])
        action = kSyncManagerActionUpdate;
    
    if (action == kSyncManagerActionNone) {
        // Next
        [self syncUpOneEntry:sync recordIds:recordIds index:i+1 updateSync:updateSync failRest:failRest];
    }
```

From what I understand, based on the value of the object the action is set to the needed value and default is kSyncManagerActionNone. However, when the condition "action == kSyncManagerActionNone” is hit, syncUpEntry is recalled with a index+1, but the method isn’t returned. Which means that the code below will still execute and result in an exception.

After testing, I believe this should fix the problem:
```objective-c
    if (action == kSyncManagerActionNone) {
        // Next
        [self syncUpOneEntry:sync recordIds:recordIds index:i+1 updateSync:updateSync failRest:failRest];
        return;
    }
```

**Comment by wmathurin** [comment]
We have updated the plugin https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/pull/54 and the master branch on the ios repo https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/946 with this fix and another one (both were already in the unstable branch for the upcoming release).
