### ISSUE TITLE
App Freeze with defer login

### ISSUE THREAD

**Issue by cslwkah** [forcedotcom/SalesforceMobileSDK-iOS#951]
Defer login is used in my app as some pages must be shown before login.  I added following code on a button clicked function:

    SFAuthenticationManager* authMgr = [SFAuthenticationManager sharedManager];
    [authMgr loginWithCompletion: ^(SFOAuthInfo * info) {
        NSLog(@"Logined done");
        [self showMemberOnlyView];//control the visibility of the hidden view
        
    } failure: ^(SFOAuthInfo * info, NSError * e) {
        NSLog(@"login fail");
        [authMgr logout];
    }];
}

I can see the log of "Logined done" but my app is freeze.  The app doesn't give me response for clicking any tabbar button or normal button.  It works fine after I killed the app and re-launch again.  Any idea?

**Comment by khawkins** [comment]
This does not look like an issue in the Mobile SDK.  However, the [Mobile SDK community](http://sfdc.co/mobilesdkcommunity) may be able to help you solve it.  I'm going to close this out in the meantime, as we reserve the Issues forum for bugs in the SDK itself.

**Comment by cslwkah** [comment]
I still think it is a bug after I found that there is a similar closed issue at https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/847  He solved the problem by modifying the SF SDK source code, which is a workaround only.

I posted my problem on the Mobile SDK community but still not solved yet.  Do you have any workable example for defer login!?  

Thanks.
