### ISSUE TITLE
CocoaPods and SmartSync

### ISSUE THREAD

**Issue by alexcfawcett** [forcedotcom/SalesforceMobileSDK-iOS#973]
I am trying to move to using the Cocoa-Pods to manage the SalesForce SDK and I’m having issues with SmartSync, the error is:

'SFSmartSyncPersistableObject.h' file not found
This file isn’t mentioned in the public_header_files: 

https://github.com/CocoaPods/Specs/blob/master/Specs/SalesforceMobileSDK-iOS/3.1.1/SalesforceMobileSDK-iOS.podspec.json#L331

**Comment by khawkins** [comment]
Ah yes, an oversight on our part.  Thanks for bringing it to our attention.  We'll have a fix out in the near future.

**Comment by khawkins** [comment]
This should be fixed in the 3.1.2 release of our pod.  Please re-open if the header file update hasn't fixed your issue.

**Comment by khawkins** [comment]
Fix in [Pull #974](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/974).
