### ISSUE TITLE
Settings.bundle overrides application one

### ISSUE THREAD

**Issue by dcacenabes** [forcedotcom/SalesforceMobileSDK-iOS#984]
Hi,

We're using salesforce mobile SDK using Cocoapods. Our application uses the Settings.bundle and Root.plist files to display some settings in iOS settings app. It is being overridden by the Salesforce one, and our options are not displaying.

**Comment by oliverwoolgar** [comment]
I have experienced the same problem. Until this is fixed we implemented a system in our build steps to delete the SF settings bundle and replace with ours before the application is packaged.

**Comment by akhileshgupta** [comment]
It currently works as expected because we do provide certain configurations via settings. But we do understand the problems due to this and in future we will look at removing the settings bundle. Keeping this issue open for that.

**Comment by jeffreyjackson** [comment]
any update on this?  cc @brad36

**Comment by brad36** [comment]
@akhileshgupta I disagree - not working as expected at all, the expectation is that when you update the pod, the app will function with custom settings. Settings e.g. root.plist are intended to be customizable, this issue breaks that. Hoping for a fix soon. Thanks

**Comment by jeffreyjackson** [comment]
@oliverwoolgar can you share with us your implementation?  I'm considering a couple ways to do this until SF team creates a solution.

**Comment by carlcarter** [comment]
We've implemented a custom fix for this by making a copy of settings.bundle which we manage within our project. 

Then during the build steps we copy our version over the Salesforce version of the file. 

I'll come back and put the details here tomorrow when I'm back in the office 

Sent from my iPhone

On 29 Jun 2015, at 18:04, Jeffrey Jackson <notifications@github.com> wrote:

@oliverwoolgar can you share with us your implementation? I'm considering a couple ways to do this until SF team creates a solution.

**Comment by carlcarter** [comment]
Create a new Build Phase for your target and do this after 'Copy Bundle Resources' but before 'Copy Pod Resources'


echo "Removing existing Settings.bundle file and replacing with our own"
rm -rf "${BUILT_PRODUCTS_DIR}/Settings.bundle"
cp -r "${SRCROOT}/<path-to-file-in-your-project>/Settings.bundle" "${BUILT_PRODUCTS_DIR}/Settings.bundle"
echo "Done"

![Uploading Screen Shot 2015-06-30 at 10.58.21.png…]()

**Comment by brad36** [comment]
@carlcarter Works a treat, thank you! cc @jeffreyjackson

**Comment by carlcarter** [comment]
You're welcome @brad36

**Comment by wmathurin** [comment]
In our upcoming release, we are getting rid of the settings bundle.
Instead the login screen will have an extra button that allows you to change login host.
You can already try it in unstable: the change came with #1368. And the removal of the settings bundle is coming in with: #1379.

**Comment by toddhalfpenny** [comment]
@wmathurin This looks good, thanks. Just wondering if this means it's still possible to set pre-defined login endpoints and for these to be exposed via the new button?

**Comment by bhariharan** [comment]
@toddhalfpenny Yes - they will be a part of the login screen itself. The new login screen has a navigation controller setup with the ability to add custom hosts and the existing preset hosts (Production and Sandbox).

**Comment by toddhalfpenny** [comment]
Great stuff, thanks @bhariharan - look forward to trying it out.
