### ISSUE TITLE
Can not save Device token into Salesforce

### ISSUE THREAD

**Issue by pvpandya** [forcedotcom/SalesforceMobileSDK-iOS#991]
When using APNS, after device token is received from Apple, when SFPushNotificationManager.m tries to store the device token to Salesforce, it errors out with following message:
Registration for notifications with Salesforce failed with status 404
2015-04-14 15:45:17:134 PushNotificationApp[2107:3c07] ERROR| SFPushNotificationManager|Response:(
        {
        errorCode = "NOT_FOUND";
        message = "The requested resource does not exist";
    }
)

What I found that POST REST call that is being made it to endpoint below is giving above error: /services/data/v31.0/sobjects/MobilePushServiceDevice 

Any help would be appreciated. I tried this on two different Salesforce org and also used workbench but could not locate MobilePushServiceDevice sObject.

When I try stand alone Push Notification that bypasses Salesforce, APNS does receive and send message to device.

Thanks

**Comment by bhariharan** [comment]
```MobilePushServiceDevice``` is a hidden object, and can not be accessed through ```Workbench```. There are a set of perms that need to be enabled on your org in order to get push notifications working. You'll also need to enable push notifications in your connected app. Please follow the instructions [here](https://help.salesforce.com/help/pdfs/en/salesforce_mobile_push_notifications_implementation.pdf) to get this working.

**Comment by pvpandya** [comment]
Bharath,

thanks for quick action. I am following the same guide and have connected app that has the Mobile Push Notification turned on as below:

![image](https://cloud.githubusercontent.com/assets/4159296/7161017/aa03aa06-e35a-11e4-91a6-121720414918.png)

Below is the screen shot of how the push notifications are enabled for the org:

![image](https://cloud.githubusercontent.com/assets/4159296/7161139/7d4fa0ea-e35b-11e4-9a16-fcaca2078e08.png)

Other part is I followed same steps in two different orgs and both of them see same issue.

Let me know if it is easy to have quick call to discuss this.  You can send me email as piyush.pandya@gmail.com
Thanks
