### ISSUE TITLE
When upgrading app, smartStore is being corrupted

### ISSUE THREAD

**Issue by manish-metacube** [forcedotcom/SalesforceMobileSDK-iOS#998]
Hi All, 

We got another serious issue, We had released our app earlier using mobile SDK 2.2 and recently provided them another updated version upgraded with mobile SDK 3.1. When he/she upgrade the app (without deleting or sometime after deleting the old instance), smart store failed to reinitialise/re-register and hence no longer work, any specific reason for  that?

Regards,
Manish Kumar

**Comment by pradeepkumargali** [comment]
Thanks for reporting @manish-metacube  We are also facing this issue on iOS.

**Comment by manish-metacube** [comment]
Update: 

Here is error log that i received the error: 

+ error logs 

<code>
[Error] TIMING com.salesforce.smartstore:pgRegisterSoup failed
	(anonymous function) (com.salesforce.util.exec.js, line 42)
	callbackFromNative (cordova.js, line 288)
	(anonymous function) (cordova.js, line 1098)
	nativeEvalAndFetch (cordova.js, line 1106)
	nativeCallback (cordova.js, line 1095)
	global code (index.html, line 1)
	appendChild ([native code], line 0)
	createExecIframe (cordova.js, line 851)
	pokeNativeViaIframe (cordova.js, line 1062)
[Log] onErrorRegSoup: null (inline.js, line 589)
[Log] In device ready Application Version No. 1.3 (main.js, line 83)

[Error] TIMING com.salesforce.smartstore:pgRegisterSoup failed
	(anonymous function) (com.salesforce.util.exec.js, line 42)
	callbackFromNative (cordova.js, line 288)
	(anonymous function) (cordova.js, line 1098)
	nativeEvalAndFetch (cordova.js, line 1106)
	nativeCallback (cordova.js, line 1095)
	global code (index.html, line 1)
	appendChild ([native code], line 0)
	createExecIframe (cordova.js, line 851)
	pokeNativeViaIframe (cordova.js, line 1062)
[Log] onErrorRegSoup: null (inline.js, line 589)

[Error] TIMING com.salesforce.smartstore:pgRegisterSoup failed
	(anonymous function) (com.salesforce.util.exec.js, line 42)
	callbackFromNative (cordova.js, line 288)
	(anonymous function) (cordova.js, line 1098)
	nativeEvalAndFetch (cordova.js, line 1106)
	nativeCallback (cordova.js, line 1095)
	global code (index.html, line 1)
	appendChild ([native code], line 0)
	createExecIframe (cordova.js, line 851)
	pokeNativeViaIframe (cordova.js, line 1062)
[Log] onErrorRegSoup: null (inline.js, line 589)

[Error] TIMING com.salesforce.smartstore:pgRegisterSoup failed
	(anonymous function) (com.salesforce.util.exec.js, line 42)
	callbackFromNative (cordova.js, line 288)
	(anonymous function) (cordova.js, line 1098)
	nativeEvalAndFetch (cordova.js, line 1106)
	nativeCallback (cordova.js, line 1095)
	global code (index.html, line 1)
	appendChild ([native code], line 0)
	createExecIframe (cordova.js, line 851)
	pokeNativeViaIframe (cordova.js, line 1062)
[Log] onErrorRegSoup: null (inline.js, line 589)

[Error] TIMING com.salesforce.smartstore:pgRegisterSoup failed
	(anonymous function) (com.salesforce.util.exec.js, line 42)
	callbackFromNative (cordova.js, line 288)
	(anonymous function) (cordova.js, line 1098)
	nativeEvalAndFetch (cordova.js, line 1106)
	nativeCallback (cordova.js, line 1095)
	global code (index.html, line 1)
	appendChild ([native code], line 0)
	createExecIframe (cordova.js, line 851)
	pokeNativeViaIframe (cordova.js, line 1062)
[Log] onErrorRegSoup: null (inline.js, line 589)

[Error] TIMING com.salesforce.smartstore:pgRegisterSoup failed
	(anonymous function) (com.salesforce.util.exec.js, line 42)
	callbackFromNative (cordova.js, line 288)
	(anonymous function) (cordova.js, line 1098)
	nativeEvalAndFetch (cordova.js, line 1106)
	nativeCallback (cordova.js, line 1095)
	global code (index.html, line 1)
	appendChild ([native code], line 0)
	createExecIframe (cordova.js, line 851)
	pokeNativeViaIframe (cordova.js, line 1062)
[Log] onErrorRegSoup: null (inline.js, line 589)

[Error] TIMING com.salesforce.smartstore:pgRegisterSoup failed
	(anonymous function) (com.salesforce.util.exec.js, line 42)
	callbackFromNative (cordova.js, line 288)
	(anonymous function) (cordova.js, line 1098)
	nativeEvalAndFetch (cordova.js, line 1106)
	nativeCallback (cordova.js, line 1095)
	global code (index.html, line 1)
	appendChild ([native code], line 0)
	createExecIframe (cordova.js, line 851)
	pokeNativeViaIframe (cordova.js, line 1062)
[Log] onErrorRegSoup: null (inline.js, line 589)
</code>


Above log is also applicable for #944 too.
-Manish Kumar

**Comment by bhariharan** [comment]
@manish-metacube There's not much information in the trace other than the failure of ```registerSoup```. Is this a one-time occurrence, or are you encountering this on a regular basis? Does the issue exist in ```Mobile SDK 3.2```?

**Comment by akhileshgupta** [comment]
Please reopen if you are still encountering this issue.

**Comment by ravish1234** [comment]
I am also facing the same issue. When upgraded with latest mobile SDK, SmartStore failed while registering for soup. Below are the logs.

WARNING|SFSmartStore|sharedStoreWithName:user: Cannot create shared store with name 'defaultStore' for nil user.  Did you mean to call [SFSmartStore sharedGlobalStoreWithName:]?
INFO|SFCrypto|Base app identifier not configured.  Creating a new value.
INFO|SFCrypto|Saving the new base app identifier to the keychain.
Crypto|Successfully created a new base app identifier and stored it in the keychain.
WARNING|SFSmartStore|sharedStoreWithName:user: Cannot create shared store with name 'defaultStore' for nil user.  Did you mean to call [SFSmartStore sharedGlobalStoreWithName:]?
TIMING com.salesforce.smartstore:pgSoupExists: 68ms
WARNING|SFSmartStore|sharedStoreWithName:user: Cannot create shared store with name 'defaultStore' for nil user.  Did you mean to call [SFSmartStore sharedGlobalStoreWithName:]?
TIMING com.salesforce.smartstore:pgRegisterSoup: 5ms
ERROR: TIMING com.salesforce.smartstore:pgRegisterSoup failed
